<?=Application_Model_Partials::getMenuPostulante(); ?>
<?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages)) ?>    

    <section class="my_applications_wrap">
      <div class="center_box">
        <div class="my_applications">
          <div class="my_applications_header">
            <h1>Mis Postulaciones</h1><span>Tu detalle de postulaciones está disponible con una antiguedad de 2 años o 100 últimas postulaciones</span>
          </div>
          <div class="my_applications_columns_name">
            <div class="my_applications_first_column_title"><span>Proceso de selección</span></div>
            <div class="my_applications_second_column_title"><span>Postulantes</span></div>
            <div class="my_applications_third_column_title"><span>Tiempo</span></div>
            <div class="my_applications_fourth_column_title"><span>Acciones</span></div>
          </div>
          <div class="my_applications_results">
              
            <?php if (count($this->postulaciones) > 0) : ?>
              
            <?php foreach ($this->postulaciones as $item) : ?>              
            <?php 
                    $url = $this->url(array(
                            'slug' => $item['slugaviso'],
                            'empresaslug' => App_Util::validateSlugEmpresa($item['empresaslug'],$item['mostrar_empresa']),
                            'ubicacionslug' => $item['ubicacionslug'],
                            'url_id' => $item['urlaviso']
                        ), 
                        'aviso_detalle', 
                        true
                    ); 
                                        
                    $urlMensajes = $this->url(array(
                        'controller' => 'notificaciones', 
                        'action' => 'index',
                        'postulacion' => $item['idpostulacion']
                    ));
                    
                    $urlDespostular = $this->url(array(
                        'controller' => 'postulaciones', 
                        'action' => 'eliminar-postulacion',
                        'id' => $item['idpostulacion']
                    ));
                    
                    $oFecha = new DateTime($item['fecha_creacion']);
                    $oFechaActual = new DateTime('now');
                    $diff = $oFecha->diff($oFechaActual);                    
                    
                    $cad = '';
                    if ($diff->days > 0) {
                        $cad = 'Hace '.$diff->days. ' día(s)';
                    } elseif ($diff->days === 0 && $diff->h === 0 && $diff->m === 0 && $diff->s === 0) {
                        $cad = 'Hoy';
                    } elseif ($diff->days === 0 && $diff->h === 0 && ($diff->m === 0) && ($diff->s > 0) ) {
                        $cad = 'Hace '.$diff->s .' segundo(s)';
                    } elseif ($diff->days === 0 && $diff->h === 0 && ($diff->m > 0)) {
                        $cad = 'Hace '.$diff->m .' minuto(s)';
                    } elseif ($diff->days === 0 && ($diff->h > 0)) {
                        $cad = 'Hace '.$diff->h .' hora(s)';                        
                    }
                    
                    $diasDuracion = $cad;
                    
                    $estados = isset($this->postulaciones->estados[$item['idpostulacion']]) 
                            ? $this->postulaciones->estados[$item['idpostulacion']] : array();
                                       
                    $estadosItems = array(
                        'postulo' => array(
                            'icon' => 'icon_check',
                            'texto' => 'POSTULACION',
                            'background' => 'background_1'
                        ),
                        'vio_cv' => array(
                            'icon' => 'icon_ojo',
                            'texto' => 'VIO MI CV',
                            'background' => 'background_2'
                        ),
                        'mensajes' => array(
                            'icon' => 'icon_mail',
                            'texto' => 'PREGUNTA',
                            'background' => 'background_3'
                        ),
                        'mensaje' => array(
                            'icon' => 'icon_mail',
                            'texto' => 'PREGUNTA',
                            'background' => 'background_3'
                        ),
                        'pregunta' => array(
                            'icon' => 'icon_mail',
                            'texto' => 'RESPUESTA',
                            'background' => 'background_4'
                        )
                    );
                    
                    $logo = trim($item['logoanuncio']);                    
                    $logo = (empty($logo) || $item['mostrar_empresa']==0) ? 
                            ($this->verLogoDefecto ? $this->S('/images/' . $this->logoDefecto): '')  : 
                            ELEMENTS_URL_LOGOS . $item['logoanuncio'].$this->E()->getLastCommit();
                    
                    
            ?>
            <div class="my_applications_result">
              <div class="my_applications_part_1">
                <div class="image_center"><img src="<?=$logo?>" alt="<?=$item['empresa']?>"></div>
              </div>
              <div class="my_applications_part_2">
                <div class="my_applications_part_2_1">
                  <div class="my_applications_first_column_value"><span class="application_title"><?= $item['puesto'] ?></span>
                      <?php if (!$item['online']) { ?>
                      <span class="application_expired">Cerrado</span>
                      <?php } ?>
                  </div>
                  <div class="my_applications_second_column_value"><span><i class="icon icon_people"></i><?=$item['total_postulantes']; ?></span></div>
                  
                  <div class="my_applications_third_column_value"><span><?=$diasDuracion;?></span></div>                  
                  <div class="my_applications_fourth_column_value"><span><?=$diasDuracion;?></span>
                    <ul>
                        <li><a href="<?=$url?>" onclick="ga('send','event','postulaciones','compartir','<?=$item['urlaviso']?>_<?=$this->id_postulante?>');" title="Ver Aviso" target="_blank"><i class="icon icon_share"></i></a></li>
                        <?php if( isset($this->notas) ){?>
                            <?php if( ($this->notas[$item['idpostulacion']])>0 ){?>
                        <li><a href="<?=$urlMensajes?>" onClick="ga('send','event','postulaciones','mensajes','<?=$item['urlaviso']?>_<?=$this->id_postulante?>');" title="Ver Mensajes"><i class="icon icon_mail"></i></a></li>
                            <?php }?>
                        <?php }?>
                        <?php if ($item['online']) { ?>
                        <li class="my_applications_close_process"><a data-href="<?=$urlDespostular?>" onClick="ga('send','event','postulaciones','eliminar','<?=$item['urlaviso']?>_<?=$this->id_postulante?>');"  title="Retirarme de la postulación"><i class="icon icon_delete"></i></a></li>
                        <?php } ?>
                    </ul>
                  </div>
                  
                </div>
                  
                <div class="my_applications_part_2_2">
                  <div class="my_applications_history_border"></div>
                  <div class="my_applications_history_indicator">
                    <i  class="my_applications_arrow down"></i>
                  </div>
                  <div class="my_applications_history_up"><a href="javascript:;" title="ver línea de tiempo">Ver línea del tiempo</a></div>
                  
                  
                  <div class="my_applications_history_down hide">
                    <div class="my_applications_history">                 
                    <?php  foreach ($estados as $key => $value) : ?>   
                        <?php if (is_array($value)) : ?>                            
                                <?php foreach ($value as $itemValue) : ?>
                                    <div class="my_applications_events">
                                        <span class="my_applications_events_title"><?=$estadosItems[$key]['texto']?></span>
                                        <span class="my_applications_events_icon <?=$estadosItems[$key]['background']?>">
                                          <div class="my_applications_events_hover"></div>
                                          <i class="icon <?=$estadosItems[$key]['icon']?>"></i>
                                        </span>
                                        <span class="my_applications_events_date"><?=$itemValue?></span>
                                    </div>
                                <?php endforeach; ?>                                                                            
                        <?php else : ?>
                      <div class="my_applications_events">
                          <span class="my_applications_events_title"><?=$estadosItems[$key]['texto']?></span>
                          <span class="my_applications_events_icon <?=$estadosItems[$key]['background']?>">
                            <div class="my_applications_events_hover"></div>
                            <i class="icon <?=$estadosItems[$key]['icon']?>"></i>
                          </span>
                          <span class="my_applications_events_date"><?=$value?></span>
                      </div>
                        <?php endif; ?>
                                              
                      <?php  endforeach; ?>
                        
                      <div class="my_applications_events process_ends">
                          <span class="my_applications_events_icon"></span>
                          <span class="my_applications_events_date">Fin del Proceso</span>
                      </div>
                        
                    </div>
                  </div>                  
                  
                  
                </div>
                  
                  
              </div>
              <div class="my_applications_part_2_2 my_applications_history_mobile">
                <div class="my_applications_history_border"></div>
                  <div class="my_applications_history_indicator">
                    <i  class="my_applications_arrow down"></i>
                  </div>
                <div class="my_applications_history_up"><a href="javascript:;" title="ver línea de tiempo">Ver línea del tiempo</a></div>
                <div class="my_applications_history_down hide">
                  <div class="my_applications_history">
                      
                    <?php  foreach ($estados as $key => $value) : ?>
                      
                      <?php if (is_array($value)) : ?>
                            <?php foreach ($value as $itemValue) : ?>
                        <div class="my_applications_events">
                            <span class="my_applications_events_icon <?=$estadosItems[$key]['background']?>">
                                <div class="my_applications_events_hover"></div>
                                <i class="icon <?=$estadosItems[$key]['icon']?>"></i>
                            </span>
                            <div class="my_applications_events_info">
                                <span class="my_applications_events_title"><?=$estadosItems[$key]['texto']?></span>
                                <span class="my_applications_events_date"><?=$itemValue?></span>
                            </div>
                        </div>
                            <?php endforeach; ?>
                      <?php else : ?>
                        <div class="my_applications_events">
                            <span class="my_applications_events_icon <?=$estadosItems[$key]['background']?>">
                                <div class="my_applications_events_hover"></div>
                                <i class="icon <?=$estadosItems[$key]['icon']?>"></i>
                            </span>
                            <div class="my_applications_events_info">
                                <span class="my_applications_events_title"><?=$estadosItems[$key]['texto']?></span>
                                <span class="my_applications_events_date"><?=$value?></span>
                            </div>
                        </div>
                      <?php endif; ?>                    
                    <?php  endforeach; ?>  
                      
             
                      
                      
                    <div class="my_applications_events process_ends">
                        <span class="my_applications_events_icon"></span>
                        <span class="my_applications_events_date">Fin del Proceso</span>
                    </div>
                      
                  </div>
                </div>
              </div>
            </div>
            <?php endforeach; ?>            
              
            <?php else: ?>
              <div class="no_results">Aún no cuentas con postulaciones.</div>
            <?php endif;?>
            
            
          </div>
        </div>
            <?php   /*
        <div class="search_results_pagination_wrapper">
          <div class="search_results_pagination">
         //$this->paginationControl($this->postulaciones, 'Sliding','postulaciones/_pagination.phtml') 
          </div>        
        </div>*/ ?>
       <div class="search_results_pagination row">
        <?= $this->partial('avisos-sugeridos/_pag.phtml',array(
          'totalPage'  => count($this->postulaciones) ,
          'pageActual' => $this->paginaActual
        )); ?>
        </div>
      </div>
    </section>

