<?=Application_Model_Partials::getMenuPostulante(); ?>

<?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages)) ?>

	 <div class="contenedor-postulacion-emepleobusco">
		<div class="postulacion-title">Mis Postulaciones</div>
		<div class="postulacion-subtitle">Tu detalle de postulaciones está disponible con una antiguedad de 2 años o 100 últimas postulaciones</div>
		<?php
		foreach ($this->postulaciones as $key => $value) {
			$segundos = strtotime('now') - strtotime($value['fecha']);
			$a_dias = intval($segundos/60/60/24);
			//var_dump($value);
			$ver_aviso = SITE_URL . $this->url(array(
							'slug' => $value['slugaviso'], 'url_id' => $value['urlaviso']), 'aviso', true);
		?>
		<div class="row smb cont-row-post">
		  <div class="descr-puesto-title"><?=$value['puesto']?></div>
		  <div class="rwo smb cont-block-description">
			 <div class="block-postulante col-xs-6 col-sm-4 col-md-4 spb">
				<div class="content-block-postulante"><span class="bold">Postulantes: </span><span class="number-postulante"><?=$value['total_postulantes']?></span></div>
			</div><span class="block-tiempo col-xs-6 col-sm-4 col-md-4 spb"><span class="bold">Tiempo:</span><span>hace <?=$a_dias?> días</span></span>
			 <div class="block-acciones col-xs-12 col-sm-4 col-md-4 spb"><a href="<?=$ver_aviso?>" title="Ver aviso"><i aria-hidden="true" class="icon-acciones fa fa-external-link-square"></i></a></div>
		  </div>
		  <div class="descr-puesto-cont col-xs-3 col-sm-2 col-md-2 spb">
			 <div class="content-table-cell">
				<div class="content-table-cell-interno">
				  <div class="cont-img-empersa"><img src="http://aquiempleos.local/elements/empleo/logos/<?=$value['logoanuncio']?>" class="img-empresa"></div>
				</div>
			 </div>
		  </div>
		  <div class="block-description col-xs-9 col-sm-10 col-md-10 spb">
			 <div class="row contenedor-linea-tiempo smb">
				<div class="content-time-line">
				  <div class="time-line"></div>
				</div>

				<?php
				$contador = 1;
				if( array_key_exists('pregunta',$this->postulaciones->estados[$value['idpostulacion']]) && array_key_exists('mensaje',$this->postulaciones->estados[$value['idpostulacion']]) ){
					//existen 2 indices (mensaje,pregunta)
					foreach ($this->postulaciones->estados[$value['idpostulacion']] as $key_estados => $value_estados) {
						if($contador>5)break;

						if($contador <= 2){//primer y segundo indice
							//imprime solo primer valor del indice
							if($key_estados == 'postulo'){
								echo $this->Contenedor($contador,$key_estados,$value_estados);
								$contador++;
							}
							else {
								echo $this->Contenedor($contador,$key_estados,$value_estados[0]);
								$contador++;
							}
						}
						else{//tercer indice,imprime valores del tercer indice
							foreach ($value_estados as $value_estados2) {
								if($contador>5)break;
								echo $this->Contenedor($contador,$key_estados,$value_estados2);
								$contador++;
							}
						}
					}//endforeach
				}else{//no hay un tercer indice
					foreach ( $this->postulaciones->estados[$value['idpostulacion']] as $key_estados => $value_estados) {
						if($contador>5)break;

						if($key_estados == 'postulo'){
							echo $this->Contenedor($contador,$key_estados,$value_estados);
							$contador++;
						}
						else {
							foreach ($value_estados as $value_estados2) {
								if($contador>5)break;
								echo $this->Contenedor($contador,$key_estados,$value_estados2);
								$contador++;
							}
						}
					}
				}
				?>

			 </div>
		  </div>
		</div>
		<?php } ?>
	 </div>
