<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages"=>$this->flashMessages)) ?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <?= $this->partial('mi-cuenta/_sec-menu.phtml', array('menu_post_sel' => $this->menu_post_sel)) ?>
                    <div class="iAccount" id="innerMain">
                        <div class="centerMC">
                           <?= $this->partial('_partials/_pago_satisfactorio.phtml','empresa', array('aw'=>$this->anuncioWeb->toArray())) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
