<div class="bgAll gridS20">
	<div class="gridForm">

		<div class="legend">
            <? if(substr($this->rol, 0,5)!=Application_Form_Login::ROL_ADMIN): ?>
			    <a href="<?php echo $this->url(array('module'=>'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),false,true) ?>">Inicio</a> »
            <? else: ?>
                <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'gestion', 'action' => 'index'),false,true) ?>">Inicio</a> »
            <? endif; ?>
			<span class="noLink">Personaliza tu aviso</span>

		</div>
            <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
		<h2 class="titleOrig">Pague su Aviso</h2>
		<blockquote id="modStepsForm"><img src="<?=$this->S('/images/empresa/avisoPaso4_2.jpg');?>" alt="Paso 4"/></blockquote>
		<div class="gridIStepEmp" class="all">
			<?= $this->partial('_partials/_voucher_pago_efectivo.phtml','empresa', 
                array(
                    "anuncioWeb"=>$this->anuncioWeb,
                    "usuario"=>$this->auth["usuario"], 
                    "fhCierre"=>$this->fhCierre,
                    "rol"=>$this->auth["usuario"]->rol,
                    "moneda"=>$this->moneda,
                    "igv"=>$this->igv
                ) 
                ) ?>
		</div>
	</div>
</div>
