<div class="bgAll gridS20">
	<div class="gridForm">
		<div class="legend">
                    <? if($this->auth["usuario"]->rol!="admin"): ?>
			<a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'gestion', 'action' => 'index'),false,true) ?>">Inicio</a>
                    <? else: ?>
                        <a href="/admin/">Inicio</a>
                    <? endif; ?>
			<span class="noLink">Personaliza tu aviso</span>
		</div>
            <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
		<h2 class="titleOrig">Pague su Aviso</h2>
		<blockquote id="modStepsForm"><img src="<?=$this->S('/images/empresa/avisoPaso4_2.jpg')?>" alt="Paso 4"/></blockquote>
		<div class="gridIStepEmp" class="all">
			<?= $this->partial('_partials/_pago_satisfactorio.phtml','empresa', array('aw'=>$this->compra, 'rol' => $this->auth["usuario"]->rol)) ?>
		</div>
	</div>
</div>