<!-- ERROR 404 DE HOME -->

<div class="container contenedor-error404">
    <img class="img-error404" alt="" src="<?= $this->S('/svg/404 icono.svg'); ?>">
    <div class="row">
        <span class="text-no-encontrado">No podemos encontrar la página que estas buscando.</span>
        <p>Prueba nuevamente con esta opción:</p>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="controls">
                <?php if (MODULE == 'empresa'): ?>
                    <a href="/empresa" type="buttom" name="btnRegresarHome" id="btnRegresarHome" title="RegresarHome" class="btn btn-home center" value="">Regresar al Home</a>
                    <?php if ($this->authEmpresa) : ?>
                        <a href="/empresa/publica-aviso/index/tarifa/1" type="buttom" name="btnPublicaAviso" id="btnPublicaAviso" title="PublicaAviso" class="btn btn-publicar center" value="">Publicar Aviso</a>
                    <?php else : ?>
                        <a href="#modalLoginUser" data-toggle="modal" type="buttom" name="btnPublicaAviso" id="btnPublicaAviso" title="PublicaAviso" class="btn btn-publicar center" value="">Publicar Aviso</a>
                    <?php endif; ?>
                <?php else : ?>
                    <a href="/" type="buttom" name="btnRegresarHome" id="btnRegresarHome" title="RegresarHome" class="btn btn-home center" value="">Regresar al Home</a>

                    <a href="<?=
                    $this->url(array(
                        'pais' => 'peru',
                        'empresa' => $this->aviso["empresaslug"]), 'buscar',
                        true)
                    ?>" type="buttom" name="btnBuscador" id="btnBuscador" title="Buscador" class="btn btn-buscar center" value="">Ir al Buscador</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
