<!--   <div class="jobs_ads_results_info row"><span class="jobs_ads_extra"><span class="font_size_manage"><i class="smaller_font animated slower">A-</i><i class="bigger_font animated slower">A+</i></span></span> -->
</div>
<div class="suggested_tabs_content animated">
  <ul>
		<?php if(count($this->avisos)>0) { ?>
		<?php foreach($this->avisos as $item) : ?>
		<?php
		  $urlA = explode('/',str_replace('http://','',$item['url']));
//        $url = SITE_URL.'/'.$urlA[1]."/".$urlA[2];
		  $url = SITE_URL.'/'.$urlA[1]."/".$item['slug']."-".App_Util::validateSlugEmpresa($item['empresaslug'],$item['mostrar_empresa'])."-".$item['ubicacionslug']."-".$item['url_id'];
		  $logo = ($item["logoanuncio"] == "" || $item['logoanuncio']
			 == " " || $item["logoanuncio"] == NULL) ?
			 $this->verLogoDefecto ? $this->S('/images/' . $this->logoDefecto)
				: ''  : ELEMENTS_URL_LOGOS . $item["logoanuncio"].$this->E()->getLastCommit();

		  $destacado = ($item['prioridad'] <= EMPLEOBUSCO_BUSQUEDA_DESTACADOS);
		  ?>
		  <li>
			 <a class="jobs_ads <?php echo ($destacado ? 'jobs_ads_highlight_job' : ''); ?>"  href="<?php echo $item['url'] ?>" title="Ver aviso" >

				<?=($destacado) ? '<span class="top_job_offer"><i class="icon icon_snood"></i><span>DESTACADO</span></span>' : '';?>
				<div class="row">
				<div class="jobs_ads_image_container">
				  <div class="center_image"><img src="<?=$logo?>" alt="<?= $item["empresa_rs"] ?>" width="87" height="87"></div>
				</div>
				<div class="jobs_ads_description">
				  <h3><?=$item['puesto']?></h3>
				  <?php if (isset($item['empresaslug'])) { ?>
				  <span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
				  <?php } else { ?>
				  <span title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
				  <?php }  ?>
				  <p><?php echo mb_substr($this->escape($item["description"]), 0,$this->recortaraviso, 'utf-8') . " ..."?></p>
				  <p class="search_address"><i class="icon icon_location"></i><?= $item["ubicacion"]; ?></p>
				</div>

				<div class="jobs_ads_options_wrapper">
				  <div class="jobs_ads_options">
				  <span><?= $item["dias_fp"] ?></span>
				  <?php if($this->tab != 'favoritos') : ?>
				  <button class="btn btn_hightlight" data-page="<?=$this->paginaActual?>" data-id="<?=$item['id']?>" data-urlaviso="<?=$item['idAviso']?>" title="Agregar a favoritos" data-highlight="<?=$this->Util()->urlAvisoFavoritosAjax($this->tab);?>">
					 <span class="btn_label"><i class="icon icon_star_hover animated paintStarAnimation"></i></span>
					 <span class="btn_spinner tiny"></span>
				  </button>
				  <?php endif; ?>
					  <?php if($this->tab != 'eliminados') : ?>
				  <button class="btn btn_delete_ads" data-page="<?=$this->paginaActual?>" data-id="<?=$item['id']?>" title="Eliminar" data-del="<?=$this->Util()->urlAvisoEliminadosAjax($this->tab);?>">
					 <span class="btn_label"><i class="icon icon_delete2"></i></span>
					 <span class="btn_spinner tiny"></span>
				  </button>
						<?php endif; ?>
				  </div>
				</div>

				</div>
			 </a>
		  </li>
		<?php endforeach;?>
		<?php } else { ?>
		<div class="not_enough_message<?=(empty($this->avisos)) ? "" : " hide"?>">
		  <?php if(!$this->tieneAreas) :?>
			 <p class="title">¿No tienes sugerencias?</p>
			 <p>AquiEmpleos te recomienda completar tus áreas de interés, tu ubicación y tus pretensiones salariales.</p>
			 <a class="btn btn_primary" href="<?=SITE_URL.'/registro/paso2'?>" title="Completa para cambiar tus sugerencias.">Completar</a>
		  <?php else : ?>
			 <p>No hay avisos sugeridos para mostrar.</p>
			 <a href="/mi-cuenta/mis-datos-personales" class="btn btn_primary">Ir a mi cuenta</a>
		  <?php endif; ?>

		</div>
		<?php } ?>

  </ul>
</div>
