<div id="dataResutlAdmin">
    <div id="msgResult" class="none cf">
        <div id="msgResultBox"></div>
        <a id="msgResultClose" href="#">X</a>
    </div>
    <div id="formAdminContent">
        <div id="gridTableR" class="blockAR theta right">
            <div class="iBlockAR">
                <div id="titleyBtn" class="all">
                <h2 class="titleMAU">Gestionar Procesos de "<?=$this->usuarioEmpresa['nombres']?> <?=$this->usuarioEmpresa['apellidos']?>"</h2>
                </div>
                <!--<div id="linksTable" class="all"></div>-->
                <h3>Asignar un nuevo proceso</h3>                                
                <form id="formAdmin" method="post" action="<?= $this->url(array('action' => 'asignar'))?>" admin-id="<?=$this->usuarioEmpresa['id']?>" class="frm-horizontal">

                    <div class="control-group">
                        <label for="fEmail" class="control-label">Área:</label>
                        <div class="controls">
                            <select id="areaId" name="anuncio_id" class="sel-xxsmall">
                                <option value="">Seleccione un área</option>
                                <?foreach ($this->areas as $id => $area) :?>                                    
                                    <option value="<?=$id?>"><?=$area?></option>
                                <?endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="cgroup-inline">
                        <label for="fEmail" class="control-label">Procesos:</label>
                        <div class="control-group">
                            <select id="anuncioId" name="anuncio_id" class="sel-xxsmall">
                                <option value="">Seleccione proceso</option>
                            </select>
                            <div class="min-loading none" id="loading-process"></div>
                        </div>
                        <div class="control-group">
                            <input id="btnFormAdmin" class="btn btn-primary" type='submit' value="Asignar proceso" />
                            <div class="min-loading none" id="loading-assigProcess"></div>
                        </div>
                    </div>
                    <!--<table>
                        <tr>
                            <td>Área:</td>
                            <td>
                                <select id="areaId" name="anuncio_id">
                                    <option value="">Seleccione un área</option>
                                    <?foreach ($this->areas as $id => $area) :?>                                    
                                        <option value="<?=$id?>"><?=$area?></option>
                                    <?endforeach;?>
                                </select>
                            </td>
                            <td>Procesos:</td>
                            <td>
                                <select id="anuncioId" name="anuncio_id" style="max-width:345px;">
                                    <option value="">Seleccione proceso</option>
                                </select>
                                <div class="min-loading none" id="loading-process"></div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2">
                                <input id="btnFormAdmin" type='submit' value="Asignar proceso" />
                                <div class="min-loading none" id="loading-assigProcess"></div>
                            </td>
                        </tr>
                    </table>-->
                </form>
                <p />
                <h3>Procesos asignados a "<?=$this->usuarioEmpresa['nombres']?> <?=$this->usuarioEmpresa['apellidos']?>"</h3>
                <div id="layerOpacity" class="none"><div class="min-loading"></div></div>
                <div id="tableDataGrid">
                    <table class="dataGrid">
                        <thead>
                            <tr>
                                <th class="data5 titleGrid">Proceso</th>
                                <th class="data5 titleGrid">Fecha Asignación</th>
                                <th class="data5 titleGrid"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <? foreach ($this->procesosAsignados as $procesoAsignado) :?>
                            <tr>
                                <td><?=$procesoAsignado['puesto']?></td>
                                <td><?=$procesoAsignado['fecha_asignacion']?></td>
                                <td><a class="abtnDelete" href="<?= $this->url(array('action' => 'quitar', 'anuncio_id' => $procesoAsignado['anuncio_id']))?>"><span class="btnDelete"></span><span>Eliminar</span></a></td>
                            </tr>
                            <? endforeach;?>
                        </tbody>
                    </table>
                    <div class="paginador mT10">
                        <?= $this->paginationControl($this->procesosAsignados, 'Sliding', 'paginador.phtml') ?>
                    </div>                               
                </div>
            </div>
            <div class="closeAdminBlock">
                <a id="closeAdmin" class="btn btn-default" href="#">Cerrar</a>
            </div>
        </div>
    </div>
</div>
