<div id="dataFormAddNADM" rel="<?= $this->log ?>" >
    <h3 class="titleAPLR"><?=
        $this->action == 'editar' ? 'Edita ' : 'Ingresa '
        ?>los datos de Administrador</h3>
    <?php if ($this->error) { ?>
      <div class="box-message">El email ya existe</div>
    <?php } ?>
    <div class="cntFormEMC">
        <form id="formEMC" action="" method="post" enctype="multipart/form-data" class="frm-horizontal small">
            <div class="control-group">
                <label for="fEmail" class="control-label"><em>*</em> Email: </label>
                <div class="controls">
                <?=
                $this->formUsu->email->setAttribs(array(
                    'id' => 'fEmail',
                    'required'=>'',
                    'data-parsley-type'=>'email',
                    'data-parsley-trigger'=>'change',
                    'class' => 'input-xmedium'))->renderViewHelper();
                ?>
                </div>
            </div>
           
            <?=
            $this->partial('registro-empresa/_administrador_paso1.phtml',
                'empresa', array('formAdministrador' => $this->formAdm));
            ?>
            <div class="wrap-btn center">
                <input id="saveEmpPID" type="submit" class="saveEmpPD btn btn-primary" value="Grabar" rel ="<?= $this->id ?>" idem= "<?= $this->idEmpresa ?>" />
                <a href="?" class="closeWMM cancelEmpPD btn btn-default">Cancelar</a>
            </div>
        </form>
    </div>
</div>