<div class="job-item">
<table>
<tr>
	<td>Título:</td>
	<td>
		<?php echo $this->form->getElement('titulo')->renderViewHelper() ?>
		<?php echo $this->form->getElement('titulo')->renderErrors() ?>
	</td>
</tr>
<tr>
	<td>Empresa:</td>
	<td><?php echo $this->form->getElement('empresa')->renderViewHelper() ?></td>
</tr>
<tr>
	<td>Rubro:</td>
	<td><?php echo $this->form->getElement('rubro')->renderViewHelper() ?></td>
</tr>
</table>

</div>