<h2>Form Manager</h2>

<form method="post" action="">

<div id="jobs_section">
<?php 
foreach ($this->forms as $form) {
    echo $this->partial('test/_subform.phtml', 'default', array('form' => $form));
}
?>
</div>

<p>
	<a href="#" id="add_job_link">Agregar trabajo</a>
</p>

<p>
	<input type="submit" value="Guardar" />
</p>

</form>

<div id="job_template" style="display:none;">
<?php echo $this->partial('test/_subform.phtml', 'default'
    , array('form' => $this->manager->getForm('blank'))); ?>
</div>

<script type="text/javascript">
var d = new Date();
var ind = d.getTime();

$('#add_job_link').click(function (){
	var html = $('#job_template').html();
	html = html.replace(/manager_blank/ig, 'manager_' + ind);
	$('#jobs_section').append(html);
	return false;
});

</script>