<div class="bgAll gridS20">
    <div class="gridForm">
        <div id="contentRetM">
            <h6 class="titleRetM">Confirmación</h6>
            <div id="cntFormRetC" class="all alignC">
                <p class="f14">Ahora ya eres parte de AquiEmpleos</p><br>
                <a id="btnRetPagIni" class="btn btn-primary" href="/">Ir a página principal</a>
            </div>
        </div>
    </div>
</div>
