<div class="bgAll gridS20">
    <div class="gridForm">
        <div id="contentRetM">    
            <h6 class="titleRetM">La direccion actual es invalida.</h6>
            <div id="cntFormRetC" class="wrap-btn center">
                <a id="btnRetPagIni" class="btn btn-primary" href="/">Ir a página principal</a>
                <br>
                <p class="f14 error">Su cuenta no fue confirmada</p>
            </div>		    
        </div>
    </div>
</div>		