<div class="modal fade page_modal recover_password_modal" tabindex="-1" role="dialog" id="modalRecoverPassword">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title modal-recuperar-contra-title">¿Olvidaste tu contraseña?</h4>
      </div>
      <div class="modal-body">
        <form class="type1" id="frmRecoverPassword" action="<?=$this->return;?>">
            <p class="text-modal-title">Ingresa tu email y te enviaremos una nueva contraseña. Si te logueaste con Facebook ingresa el email de tu cuenta de Facebook</p>
            <fieldset class="input_control_wrapper border_input_control">
                <div class="">
                    <label>Ingresa tu email</label>
                    <div class="contenedor-msj-error">
                        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                        <span>No ingreso un email válido</span>
                    </div>
                    <div class="contenedor-msj-ajax">
                    </div>
                    <?= str_replace('type="text"', 'type="email"',$this->newrecuperarClaveForm->txtEmailForgot->setAttribs(array('id' => 'txtEmailForgot','size'=>'50','placeholder'=>'','required'=>''))->renderViewHelper());?>
                </div>
            </fieldset>
            <button class="btn btn_tertiary mt10 btn-enviar-correo" type="submit">
                <span class="btn_label">Enviar correo</span>
                <span class="btn_spinner"></span>
            </button>
            <?php //=$this->newrecuperarClaveForm->hidRecoverPassword->renderViewHelper();?>
            <?=$this->newrecuperarClaveForm->rol->renderViewHelper();?>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

