<div class="page_modal welcome_information_modal hide" id="welcomeInformationModal">
  <div class="align_center sub_title_mobile"><span>Tenemos <b><?=($this->information > 0) ? $this->information:''?></b> sugerencias de puestos</span><i class="icon icon_cross"></i></div>
  <div class="boby_welcome">
    <p>Revisamos más de <b>50,000 ofertas</b> de empleo disponibles en el mercado y las comparamos con tu perfil identificando las que encajan mejor contigo.</p>
    <b>¿Cómo mejorar mi ofertas sugeridas?</b><br><br>
    <div class="wrapper">
      <img src="/static/main/img/welcome_profile.jpg" width="299">
      <div class="info">
        <i class="icon icon_arrowh_left"></i>
        Marca en tus favoritos una sugerencia de empleo.<br><br>
        <i class="icon icon_arrowh_left last"></i>
        Descarta las ofertas sugeridas que no coincidan con lo que estás buscando.
      </div>
    </div>
    <h4 class="message">Así aprenderemos qué es lo que más te gusta para sugerirte otros empleos ideales para ti.</h4>
  </div>
</div>