<div class="modal fade in" id="modal_comentarios" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <form action="<?= SITE_URL.$this->formCuestionario->getAction(); ?>" method="post" class="form-horizontal">
            <div class="modal-content">
                <div class="modal-header modal-header-postula">
                    <button type="button" class="close close-postula" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="myModalLabel">Dejanos tu comentario</h4>
                </div>
                <div class="modal-body">
                     <?php $i= 0?>
                    <?php foreach ($this->formCuestionario->getElements() as $pregunta) : ?>
                        <?php if ($pregunta->getType() != 'Zend_Form_Element_Image') : ?>
                            <?php if ($pregunta->getType()
                                != 'Zend_Form_Element_Hidden') : ?>

                                <div class="texto-modal"><?= $i.
                                '.  '.$pregunta->getLabel(); ?></div>
                                <?=
                                $pregunta->setAttribs(array(
                                    'id' => 'question'.$i,
                                    'class'=>'comentario-area form-control',
                                    'maxlength' => 750,
                                    'required' => ''))->renderViewHelper()
                                ?>
                                <div class="texto-modal">

                                    
                                </div>
                            <?php else : ?>
                                <?= $pregunta->renderViewHelper() ?>
                            <?php endif; ?>
                            <?php $i++; ?>
                        <?php endif; ?>
<?php endforeach; ?>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="size two">Aceptar</button>
                </div>
            </div>
        </form>
    </div>
</div>