<div id="modalConfirmLeaveApplication" class="page_modal modal_confirm_leave_application hide">
  <div class="title">¿Estás seguro que deseas dejar este proceso de selección?</div>
  <div class="button_container">
      <a class="btn btn_save">
          <span class="btn_label">Dejar proceso</span>
          <span class="btn_spinner"></span>
      </a>
      <a class="btn btn_cancel">Cancelar</a></div>
</div>