<div class="page_modal modal_not_enough_information hide" id="modalNotEnoughInformation">
  <div class="title"><?=(CONTROLLER =='aviso' && MODULE =='postulante' && ACTION == 'ver')?'Esta empresa necesita saber más de ti':'Para adquirir un perfil destacado necesitas llenar estos datos'; ?></div>
  <ul id="not_enough_information_form_error" class="message_validate error hide"></ul>
    <form id="frmNotEnoughInformation" class="type1" method="post" novalidate="novalidate" action="<?=SITE_URL?>/mi-cuenta/actualizar-datos-perfil/" autocomplete="off">
        <div class="form_box">
            <div class="form_row">
               <div class="form_col12">
                  <fieldset>
                  <label>GENERO</label>
                  <?=$this->newCompleteRecord->selGenero->setAttribs(array('id' => 'selGenero','class'=>'pretty_select_2'))->renderViewHelper()?>
                  </fieldset>
               </div>
            </div>
            <div class="form_row">
                <div class="form_col12">
                  <fieldset>
                    <label>DOCUMENTO DE IDENTIDAD</label>
                    <?=$this->newCompleteRecord->selDocumento->setAttribs(array('id' => 'selDocumento','class'=>'pretty_select_2'))->renderViewHelper()?>
                  </fieldset>
                </div>
            </div>
            <div class="form_row">
              <div class="form_col12">
                <fieldset>
                <label>NÚMERO</label>
                <?=$this->newCompleteRecord->txtNumero->setAttribs(array('id' => 'txtNumero','placeholder'=>'','required'=>'','aria-required'=>'true', 'minlength'=> '8', 'maxlength'=> '8'))->renderViewHelper()?>
                </fieldset>
              </div>
            </div>
            <div class="form_row">
                <div class="form_col12">
                  <fieldset>
                    <label>PAIS</label>
                    <?=$this->newCompleteRecord->selPais->setAttribs(array('id' => 'selPais','placeholder'=>'Perú' ,'required'=>'','aria-require'=>'true', 'class'=>'pretty_select_2'))->renderViewHelper()?>
               </fieldset>
                </div>
            </div>
            <div class="form_row">
              <div class="form_col12">
                <fieldset>
                  <label>UBICACIÓN</label>
                  <?=$this->newCompleteRecord->txtUbicacion->setAttribs(array('id' => 'txtUbicacion','placeholder'=>'Ingresa  ciudad, estado','required'=>'','aria-required'=>'true', 'autocomplete'=>"off"))->renderViewHelper()?>
                  <input type="hidden" class="txtIdUbicacion" name="txtIdBusqueda" id="txtIdUbicacion">
               </fieldset>
              </div>
            </div>
        </div>
        <div class="button_container row">
            <a class="btn btn_cancel" id="clsModalNotEnoughInformation" href="javascript:;">Cancelar</a>
            <a class="btn btn_save" id="smbModalNotEnoughInformation">
               <span class="btn_label">Completar</span>
               <span class="btn_spinner"></span>
            </a>
        </div>
      <?=isset($this->layout->redirect)?'<input type="hidden" name="redirect" value="'.$this->layout->redirect.'">':''?>
      <?= $this->newCompleteRecord->tokenhiden->renderViewHelper() ?>
      <?=isset($this->layout->question)?'<input type="hidden" name="question" value="'.$this->layout->question.'">':''?>
      <?=isset($this->layout->url_id)?'<input type="hidden" name="ulr_id" value="'.$this->layout->url_id.'">':''?>
    </form>
</div>
