<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>
            <div id="innerMain" class="grid20 center">
                <div class="loginVM left">
                    <h2 class="alignC">Ingresa</h2>
                    <form id="fLoginWMH" action="<?=$this->baseUrl('/auth/login') ?>" method="post">
                        <?=$this->loginForm->auth_token->renderViewHelper()?>
                        <?=$this->loginForm->tipo->renderViewHelper()?>
                        <fieldset class="mB10">
                            <?=$this->loginForm->userEmail->setAttribs(array('alt'=>'Ingresa tu mail', 'id'=>'wmMail','class'=>'f11 inputSm placeH cGray'))->renderViewHelper()?>
                            <div class="hide f11 mB5 mL5 respW">&nbsp;</div>
                            <?=$this->loginForm->userPass->setAttribs(array('alt'=>'Ingresa tu password', 'id'=>'wmPass','class'=>'f11 inputSm placeH cGray'))->renderViewHelper()?>
                            <div class="hide f11 mB5 mL5 respW">&nbsp;</div>
                        </fieldset>
                        <fieldset>
                            <div class="left send6 anch100">
                                <?=$this->loginForm->Submit->setAttribs(array('id'=>'sLoginWMH','class'=>'left sendWMH active btn btn-primary','value' => 'Aceptar'))->renderViewHelper()?>
                            </div>
                            <div class="right grid3 theta">
                                <label for="saveKeyWM">
                                    <?=$this->loginForm->save->setAttribs(array('id'=>'saveKeyWM','class'=>'mR5 noBdr'))->renderViewHelper()?>
                                    <span class="saveKeyF">Guardar sesión</span>
                                </label>
                                <a href="#olvidasteClave" id="forgotPass" class="mL20">¿Olvidaste tu clave?</a> </div>
                        </fieldset>
                        <?=$this->loginForm->return;?>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
