<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>	
            <div class="gridTab">
            <div class="gridIT">
                <h5 class="h5TitleAdm">Módulo de Administración</h5>
                <?=$this->partial('_partials/_accion-admin.phtml',array('nombres'=>$this->nombres,'apellidos'=>$this->apellidos,'urlvolver'=>$this->urlvolver,'activo'=>$this->activo,'idPostulante'=>$this->idPostulante))?>
                    <div class="row">
                        <div class="grids-2">
                            <?=$this->partial('mi-cuenta/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rel' => $this->idPostulante,'slug'=>$this->slug))?>
                        </div>
                        <div class="grids-7">
                            <h2>Datos personales</h2>
                            <?= $this->partial('_partials/_post_datos_personales.phtml',
                                array('emailMicuenta'=>$this->emailMicuenta,
                                    'modulo'=>$this->modulo,
                                    'controlador'=>$this->controlador,
                                    'formPostulante'=>$this->formPostulante,
                                    'mes' => $this->mes,
                                    'formUsuario'=>$this->formUsuario,
                                    'imgPhoto' => $this->imgPhoto,
                                    'config' => $this->config,
                                    'idPostulante'=>$this->idPostulante,
                                    'rol'=>$this->rol,'sexo'=>$this->sexo
                                )
                            ); ?>
                        </div>
                    </div>
        		</div>
        	</div>
        </div>
    </div>
</div>
