<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>	
		<div class="gridTab">
    		<div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
    		<?=$this->partial('_partials/_accion-admin.phtml',array('nombres'=>$this->nombres,'apellidos'=>$this->apellidos,'urlvolver'=>$this->urlvolver,'activo'=>$this->activo,'idPostulante'=>$this->idPostulante))?>
                <div id="innerMain" class="iAccount">
                   <?=$this->partial('mi-cuenta/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rel' => $this->idPostulante,'slug'=>$this->slug))?>
                     <div class="blockAR grid15 alpha right">
                   <div class="iBlockAR wrap-edit">
                     	<h2 class="titleMAU">Programas</h2>
                         <?= $this->partial('_partials/_programas.phtml','postulante',
                             array('formPrograma'=>$this->formPrograma,
                             		'isLinkedin'=>$this->isLinkedin,
                             		'isPrograma'=>$this->isPrograma,
                             		'managerPrograma'=>$this->managerPrograma,
                                        'idPostulante'=>$this->idPostulante,
                                        'action' => $this->action,
                                        'modulo' => $this->modulo,
                                        'csrfhash_a_tok' => true
                                 )
                             ); ?>
    						
    					</div>
    				</div>
    			</div>
    		</div>
    	</div>			
	</div>
	</div>
</div>
