<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>	
    		<div class="gridTab">
        	<div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
        	<?=$this->partial('_partials/_accion-admin.phtml',array('nombres'=>$this->nombres,'apellidos'=>$this->apellidos,'urlvolver'=>$this->urlvolver,'activo'=>$this->activo,'idPostulante'=>$this->idPostulante))?>
                <div id="innerMain" class="iAccount">
                   <?=$this->partial('mi-cuenta/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rel' => $this->idPostulante,'slug'=>$this->slug))?>
                     <div class="blockAR grid15 alpha right">
                   <div class="iBlockAR cntAlertCP">
                    <h2>Mi privacidad</h2>
                    
                     <?= $this->partial('_partials/_privacidad.phtml','postulante',
                     array('formPrivacidad'=>$this->formPrivacidad)
                     ); ?>
                    
                  </div>
                </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
