web:
    build: ./docker/web/
    volumes:
        - ./src:/var/www/html
    links:
        - memcached
        - mongo
#        - mysql
#        - redis
#        - solr
    ports:
        - "80:80"

memcached:
    image: memcached:latest
#    ports:
#      - "11211:11211"

mongo:
    command: --storageEngine=wiredTiger
    image: mongo:latest
#    ports:
#       - "27017:27017"

#mysql:
#    image: mysql:latest
#    ports:
#        - "3316:3306"
#    environment:
#        MYSQL_ROOT_PASSWORD: kokos1234

#redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"

#solr:
#    image: makuk66/docker-solr:4.10.4
#    ports:
#        - "8983:8983"

nodejs:
    image: node:latest
    environment:
          - SRC_DIR=/usr/src/frontend
    volumes:
        - ./frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    command: /usr/local/bin/npm install
    command: /usr/src/frontend/node_modules/gulp/bin/gulp.js watch
    ports:
        - "3000:3000"
        - "3001:3001"
