<fieldset class="form_control">
    <label class="lbl_control">Contraseña Actual</label>
    <?=$this->formCambioClave->oldpswd->setAttribs(array('class'=>'txt_control',  'type'=>'password','tabindex'=>'2','required'=>'', 'minlength' => 6,'maxlength'=>32))->renderViewHelper(); ?>
</fieldset>
<fieldset class="form_control progress">
    <label class="lbl_control">Nueva Contraseña</label>
    <?=$this->formCambioClave->pswd->setAttribs(array('class'=>'txt_control txt_password_progress', 'type'=>'password','tabindex'=>'2','required'=>'', 'minlength' => 6, 'maxlength'=>32))->renderViewHelper(); ?>      
</fieldset>
<fieldset class="form_control">
    <label class="lbl_control">Confirmar Contraseña</label>
    <?=$this->formCambioClave->pswd2->setAttribs(array('class'=>'txt_control', 'type'=>'password','tabindex'=>'3','required'=>'', 'minlength' => 6, 'maxlength'=>32))->renderViewHelper(); ?>       
</fieldset>
<?=$this->formCambioClave->tok->renderViewHelper();  ?>
<input type="hidden" name="username" id="username" value="<?=$this->username; ?>" />
<input type="hidden" name="csrfhash" id="ocultohash" value="<?= CSRF_HASH ?>" />