<form id="frmUserExperience" class="type1 mt20" action="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'update-experiencias-ajax'));?>" method="post" autocomplete="off" class="type1" <?=($this->noneSkill)? "":'style="display: none;"'?> >
  <div class="form_box border_grey">
    <div class="form_row">
      <div class="form_col6">
        <fieldset>
          <label>Empresa</label>
            <?= $this->formExperiencia->txtExperience->setAttribs(array('required' => '', 'minlength'=>'3', 'maxlength'=>'75'))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col6">
        <fieldset>
          <label>industria</label>
            <?= $this->formExperiencia->txtIndustry->setAttribs(array('class' => '', 'minlength'=>'3', 'maxlength'=>'75'))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col6">
        <fieldset>
          <label>puesto</label>
            <?= $this->formExperiencia->txtJob->setAttribs(array('required' => 'false', 'minlength'=>'3', 'maxlength'=>'75'))->renderViewHelper(); ?>
            <?=$this->formExperiencia->hidJob->setAttribs(array('id'=>'hidJob'))->setValue(29)->renderViewHelper();?>
        </fieldset>
      </div>
      <div class="form_col6">
        <fieldset>
          <label>Lugar</label>
          <label class="radio_inline">
            <input type="radio" name="togglefields" checked="checked" value="lugar"/> Oficina
          </label>
          <label class="radio_inline">
            <input type="radio" name="togglefields" value="obra"/> Obra/Campo
          </label>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col6">
        <fieldset>
          <label>Área</label>
            <?= $this->formExperiencia->selLevelArea->setAttribs(array('required' => '', 'class' => ''))->renderViewHelper(); ?>
        </fieldset>                
      </div>
      <div class="form_col6">
        <fieldset>
          <label>Nivel de Puesto</label>
          <?= $this->formExperiencia->selLevelJob->setAttribs(array('required'=>'', 'class' => ''))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row hide toggle_place_form">
      <div class="form_col6">
        <fieldset>
          <label>Tipo</label><?= $this->formExperiencia->selProjectType->setAttribs(array('required' => '','class' => 'pretty_select_2x'))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col6"></div>
    </div>
    <div class="form_row hide toggle_place_form">
      <div class="form_col6">
        <fieldset>
          <label>Nombre del proyecto</label>
            <?= $this->formExperiencia->txtNameProjectType->setAttribs(array('required' => '', 'class' => ''))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col6">
        <fieldset>
          <label>Presupuesto</label>
            <?= $this->formExperiencia->txtBudgetProjectType->setAttribs(array('placeholder' => '('.$this->moneda.')'))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col3">
        <fieldset>
          <label>Inicio</label>
            <?= $this->formExperiencia->selMonthBegin->setAttribs(array('required' => '', 'class' => 'pretty_select_2x'))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col3">
        <fieldset>
          <label>Año</label>
          <?= $this->formExperiencia->txtYearBegin->setAttribs(array('required' => '', 'placeholder' => "yyyy",'minlength' => '4', 'maxlength' => '4', 'max' => date('Y') ))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col3">
        <fieldset>
          <label>Fin</label>
          <?= $this->formExperiencia->selMonthEnd->setAttribs(array('required' => '', 'class' => 'pretty_select_2x'))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col3">
        <fieldset>
          <label>Año</label>
          <?= $this->formExperiencia->txtYearEnd->setAttribs(array('required' => '', 'placeholder' => "yyyy", 'minlength' => '4', 'maxlength' => '4', 'max' => date('Y'), 'data-currentmonth' => (int) date('m') , 'data-current-year' => date('Y') ))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col12">
        <fieldset>
          <label class="lbl_control"> Actualmente trabajando
              <input type="checkbox" name="chkInProgress" id="chkInProgress">
              <?//= $this->formExperiencia->chkInProgress->renderViewHelper(); ?>
          </label>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col12">
        <div class="form-group">
          <fieldset>
            <label class="col-sm-3">Descripción laboral</label>
              <?= $this->formExperiencia->txaComments->setAttribs(array('class'=> '','rows' => '6', 'cols' => '750', 'required' => ''))->renderViewHelper(); ?>
              <span class="response"></span>
              <?php $cantComentario = 1500 - strlen($this->formExperiencia->txaComments->getValue()); ?>
              <p class="max_nummber">(Te quedan <b class="fewWordsLeftAlert"><?= $cantComentario ?></b> caracteres)</p>
          </fieldset>
        </div>
      </div>
    </div>
    <div class="form_row buttons_row">
      <button class="btn btn_save" disabled>
        <span class="btn_label">Guardar</span>
        <span class="btn_spinner"></span>
      </button>
      <button class="btn btn_cancel type_basic" type="button">Cancelar</button>
    </div>
    <?=$this->formExperiencia->hidExperiences->setAttribs(array('id'=>'hidExperiences'))->renderViewHelper();?>
  </div>
</form>
