  <form id="frmLanguages" autocomplete="off" class="type1 mt20" method="post" action="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'update-idiomas-ajax'))?>"  <?=($this->noneSkill)? "":'style="display: none;"'?>>
    <div class="form_box border_grey">
      <div class="form_row">
        <div class="form_col12">
          <fieldset>
            <label>Idioma</label>
            <?=$this->formIdioma->selLanguage->setAttribs(array( 'id' => 'selLanguage','class'=>'pretty_select_2x' , 'required'=>''))->renderViewHelper();?>
          </fieldset>
        </div>
      </div>
      <div class="form_row">
        <div class="form_col6">
          <fieldset>
            <label>Nivel Escrito</label>
            <?=$this->formIdioma->selLevelWritten->setAttribs(array( 'id' => 'selLevelWritten', 'class'=>'pretty_select_2x', 'required'=>''))->renderViewHelper();?>
          </fieldset>
        </div>
        <div class="form_col6">
          <fieldset>
            <label>Nivel Oral</label>
              <?=$this->formIdioma->selLevelOral->setAttribs(array( 'id' => 'selLevelOral', 'class'=>'pretty_select_2x', 'required'=>''))->renderViewHelper();?>
          </fieldset>
        </div>
      </div>
      <div class="form_row buttons_row">
        <button class="btn btn_save" disabled>
          <span class="btn_label">Guardar</span>
          <span class="btn_spinner"></span>
        </button>
        <button class="btn btn_cancel type_basic" type="button">Cancelar</button>
      </div>
    </div>
    <input id="hidLanguage" name="hidLanguage" type="hidden" value="0">
  </form>