<?php
$active = 'is_active';
$idPostulante = isset($this->dataperfil['idpostulante']) ? $this->dataperfil['idpostulante'] : '';
$currentMenuPerfil = in_array(
        $this->menu_post_sel,
        array(
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOSPERSONALES,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_UBICACION,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_EXPERIENCIAS,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_ESTUDIOS,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_OTROESTUDIOS,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_IDIOMAS,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_PROGRAMAS,
            App_Controller_Action_Postulante::MENU_POST_SIDE_MISDATOS_LOGROS
        ));?>
<section class="sub_menu_box">
    <?php if ($this->auht) { ?>
  <div class="center_box pd-bottom ">
    <ul class="row ">
      <li class="<?= $currentMenuPerfil ? $active : ''?>"><a href="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'mis-datos-personales'),"default",true)?>" onClick="ga('send', 'event', 'menu_postulante', 'mis-datos-personales','menu_<?=$idPostulante?>');"   >Mi perfil</a></li>
      <li class="<?=$this->menu_post_sel == App_Controller_Action_Postulante::MENU_POST_SIDE_MISPOSTULACIONES ? $active : ''?>"><a href="<?=$this->url(array('module'=>'postulante','controller'=>'postulaciones','action'=>'index'),"default",true)?>"  onClick="ga('send','event','menu_postulante','postulaciones','menu_<?=$idPostulante?>');" >Mis postulaciones</a></li>
      <li class="<?=$this->menu_post_sel == App_Controller_Action_Postulante::MENU_POST_SIDE_MISNOTIFICACONES ? $active : ''?>"><a href="<?=$this->url(array('module'=>'postulante','controller'=>'notificaciones','action'=>'index'),"default",true)?>" onClick="ga('send', 'event', 'menu_postulante', 'notificaciones','menu_<?=$idPostulante?>');">Mis notificaciones</a></li> 
    </ul>
  </div>
    <?php } ?>
</section>
