<form id="frmOtherEducation" autocomplete="off" class="type1 mt20" <?=($this->noneSkill)? "":'style="display: none;"'?> method="post" action="/mi-cuenta/mis-otros-estudios-ajax">
	 <div class="form_box border_grey">
		<div class="form_row">
		  <div class="form_col12">
			 <fieldset>
				<label>Nombre</label>
				<?=$this->formOtroEstudio->txtOtherName->setAttribs(array(
				'id' => 'txtOtherName', 'tabindex' => '1', 'placeholder'=>"Ingrese nombre de estudio", 'class'=>"input_control", 'required'=>'', 'data-parsley-pattern'=>'/^[a-z-ñáéíóúÑÁÉÍÓÚ ]+$/gi'))->renderViewHelper();?>
			 </fieldset>
		  </div>
		</div>
		<div class="form_row">
		  <div class="form_col6">
			 <fieldset>
				<label>Institución</label>
				<?=$this->formOtroEstudio->txtOtherInstitution->setAttribs(array(
				'id' => 'txtOtherInstitution', 'tabindex' => '2', 'placeholder'=>"Ingrese nombre de institución", 'class'=>"input_control", 'required'=>''))->renderViewHelper();?>
				<input type="hidden" id="hidOtherInstitution" name="hidOtherInstitution">
			 </fieldset>
		  </div>
		  <div class="form_col6">
			 <fieldset>
				<label>Tipo</label>
				<?= $this->formOtroEstudio->selOtherType->setAttribs(array('id' => 'selOtherType', 'tabindex' => '3', 'class'=>'pretty_select_2x'))->renderViewHelper();?>
		  </div>
		</div>
		<div class="form_row">
		  <div class="form_col12">
			 <fieldset>
				<label>País</label>
				<?= $this->formOtroEstudio->selOtherCountry->setAttribs(array('id' => 'selOtherCountry', 'tabindex' => '4', 'class'=>'pretty_select_2x'))->renderViewHelper();?>
			 </fieldset>
		  </div>
		</div>
		<div class="form_row">
		  <div class="form_col6">
			 <fieldset>
				<label>Inicio</label>
				<?= $this->formOtroEstudio->selOtherMonthBegins->setAttribs(array('id' => 'selOtherMonthBegins', 'tabindex' => '5', 'class'=>'pretty_select_2x'))->renderViewHelper();?>
			 </fieldset>
		  </div>
		  <div class="form_col6">
			 <fieldset>
				<label>Fecha</label>
				<?=$this->formOtroEstudio->txtOtherYearBegins->setAttribs(array('class' => 'input_control','placeholder' => "yyyy",
				'id' => 'txtOtherYearBegins', 'tabindex' => '6', 'required'=>''))->renderViewHelper();?>
			 </fieldset>
		  </div>
		</div>
		<div class="form_row">
		  <div class="form_col6">
			 <fieldset>
				<label>Fin</label>
				<?= $this->formOtroEstudio->selOtherMonthEnd->setAttribs(array('id' => 'selOtherMonthEnd', 'tabindex' => '7', 'class'=>'pretty_select_2x'))->renderViewHelper();?>
			 </fieldset>
		  </div>
		  <div class="form_col6">
			 <fieldset>
				<label>Fecha</label>
				<?=$this->formOtroEstudio->txtOtherYearEnd->setAttribs(array('class' => 'input_control','placeholder' => "yyyy",
				'id' => 'txtOtherYearEnd', 'tabindex' => '8', 'required'=>'', 'data-currentmonth' => (int)date('m'), 'data-current-year' => date('Y')))->renderViewHelper();?>
			 </fieldset>
		  </div>
		</div>
		<div class="form_row">
		  <div class="form_col12">
			 <fieldset>
				<label class="lbl_control"> Actualmente estudiando
				  <input type="checkbox" name="actuallyStudying" id="actuallyStudying">
				</label>
			 </fieldset>
		  </div>
		</div>
		<div class="form_row buttons_row">
		  <button class="btn btn_save" disabled>
			 <span class="btn_label">Guardar</span>
			 <span class="btn_spinner"></span>
		  </button>
		  <button class="btn btn_cancel type_basic" type="button">Cancelar</button>
		</div>
	 </div>
	 <input id="hidOtherStudy" name="hidOtherStudy" type="hidden" value="0">
</form>
