<?php
/**
 * @todo cambiar todo esto
 */
if (isset($this->postulante['actionName'])) {
    $match = round($this->postulante['match']);
    if ($match > 0 && $match < 100) {
        $matchMod = $match - 10;
    }
    if ($match == 0) {
        $matchMod = $match;
    }
    if ($match == 100) {
        $matchMod = $match - 30;
    }
} else {
    $matchMod = $this->PorcentajePerfil($this->postulante['idpostulante']);
}
$leng = strlen($this->postulante['estado_civil']);?>
<div class="all mB20">
    <div class="r2 bLBlue left" id="infoPerfilCP">
        <?php
        if ($this->postulante['fotovariable'] != "") :
            ?>
            <div class="left" id="imgPPubPC">
                <img width='100' alt=<?= $this->escape($this->postulante['nombres'] . " " . $this->postulante['apellidos']); ?> src="<?= ELEMENTS_URL_IMG . $this->postulante['fotovariable'] ?>">
            </div>
        <?php endif; ?>
        <?php
        if ($this->postulante['fotovariable'] != "") :
            ?>
            <dl class="dlList right" id="infoPPubPC">
            <?php else: ?>
                <dl class="dlList" id="infoPPubPC">
                <?php endif; ?>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    ?>
                    <dt class="titleNPCP">
                    <span class="namePCP">
                        <?= $this->escape($this->postulante['nombres']); ?>
                    </span>
                    <span class="apellPCP">
                        <?= $this->escape($this->postulante['apellidos']); ?>
                    </span>
                    </dt>

                <?php else: ?>
                    <dt class="titleNPCP">
                    <span class="namePCP">
                        <?= $this->escape($this->postulante['nombres']); ?>
                    </span>
                    </dt>
                <?php endif; ?>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    if ($this->mejor_nivel_puesto != null) {
                        ?>
                        <dd class="fieldPCP c6">
                            <span class="tlfPCP">
                                <?= $this->mejor_nivel_puesto['nivel_estudio'] ?> <?= $this->mejor_nivel_puesto['nivel_estudio_tipo'] ?> (<?= $this->escape($this->mejor_nivel_puesto['carrera']) ?>)</span>
                        </dd>
                        <dd class="fieldPCP c6">
                            <span class="tlfPCP">
                                <?= ($this->mejor_nivel_puesto['colegiatura_numero']) ? 'Colegiado (' . $this->escape($this->mejor_nivel_puesto['colegiatura_numero']) . ')' : ''; ?></span>
                        </dd>
                        <?php
                    }
                endif;
                ?>
                <dd class="fieldPCP c6">
                    <span class="agePCP">
                        <?= $this->Edad($this->postulante['fecha_nac']) ?> años - </span>
                    <span class="marriedPCP">
                        <?= (!empty($this->postulante['estado_civil'])) ?
                         ucfirst(Application_Model_Postulante::$estadoCivil[$this->postulante['estado_civil']]) : ''; ?>
                    </span>
                </dd>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    ?>
                    <dd class="fieldPCP c6">
                        <span class="distPCP">
                            <?= $this->postulante['ubicacion'] ?>
                            <?= ($this->postulante['extranjero'] == 1) ? ' - (Dispuesto para viajar)' : ''; ?>
                        </span>
                    </dd>
                <?php endif; ?>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    ?>
                    <dd class="fieldPCP c6">
                        <span class="docTPCP">
                            <?= strtoupper($this->postulante['tipo_doc']) ?>
                        </span>
                        <span class="docNPCP">
                            <?= $this->postulante['num_doc'] ?>
                        </span>
                    </dd>
                <?php endif; ?>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    ?>
                    <dd class="fieldPCP c6">
                        <span class="tlfPCP">
                            <?= $this->postulante['telefono'] ?>
                        </span>
                    </dd>
                <?php endif; ?>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    ?>
                    <dd class="fieldPCP c6">
                        <span class="mailPCP">
                            <a href=mailto:<?= $this->postulante['email'] ?>>
                                <?= $this->postulante['email'] ?>
                            </a>
                        </span>
                    </dd>
                    <?php
                    if ($this->postulante['path_cv'] != null) {
                        $docCV = $this->postulante['path_cv'];
                        $doc = strtolower(substr($docCV, strlen($docCV) - 3, strlen($docCV)));
                        $target = '';
                        if ($doc == 'pdf')
                            $target = "TARGET='_blank'";
                        ?>
                        <dd class="fieldPCP c6">
                            <span class="mailPCP">
                                <a href="<?= ELEMENTS_URL_CVS . $this->postulante['path_cv'] ?>" <?= $target ?>>Ver CV</a>
                            </span>
                        </dd>
                    <?php } ?>
                <?php endif; ?>
            </dl>
    </div>
    <?php
    if (!isset($this->ocultar) && $this->ocultar != true) :
        ?>
        <?php if ($this->postulante['presentacion'] != "") {
            ?>
            <dl class="dlList right" id="summaryPPC">
                <dt class="titlePreCP titlePRCP bold">
                <span class="titlePRLeft <?=
                isset($this->postulante['actionName']) ? 'left' : ''
                ?>">Presentación</span>
                      <?php if (isset($this->postulante['actionName'])) { ?>
                    <span class="titlePRRight right">
                        <?=
                        isset($this->postulante['etapa_actual']) ? $this->postulante['etapa_actual'] : ''
                        ?>
                    </span>
                <?php } ?>
                </dt>
                <dd class="fieldPCP summaryFPCP c6">
                    <?= $this->escape($this->postulante['presentacion']); ?>
                </dd>
                <?php if (isset($this->postulante['actionName'])) { ?>

                    <dd id="processMathA" class="dataGrid">
                        <div class="rank right">
                            <span class="showRank" style="left:<?php echo $matchMod ?>%">
                                <?php echo $matchMod; ?>
                                %
                            </span>
                            <span class="barRank" style="width:<?php echo $matchMod; ?>%"> </span>
                        </div>
                        <div class="right txtRefMatch">Match </div>
                    </dd>

                <?php } ?>
            </dl>
        <?php } else { ?>
            <dl class="dlList right" id="summaryPPC">
                <dt class="titlePreCP titlePRCP bold">
                <span class="titlePRLeft left"></span>
                <span class="titlePRRight right"><?=
                    isset($this->postulante['etapa_actual']) ? $this->postulante['etapa_actual'] : ''
                    ?></span>
                </dt>
                <?php if (isset($this->postulante['actionName'])) { ?>
                    <dd id="processMathA" class="dataGrid">
                        <div class="rank right">
                            <span class="showRank" style="left:<?= $matchMod ?>%"><?= $match ?>%</span>
                            <span class="barRank" style="width:<?= $match ?>%"> </span>
                        </div>
                        <div class="right txtRefMatch">Match </div>
                    </dd>
                <?php } ?>
            </dl>
        <?php } ?>
    <?php endif; ?>
</div>
<?php
if (isset($this->postulante['actionName']) || (isset($this->postulante['verLastUpdate']) && $this->postulante['verLastUpdate'] == true)) {
    ?>
    <div class="msgYellow mB10 r5 msgPerfilEPL">
        <div class="msgInPerfilEPL">
            <span class="namePEeMp">
                <?= $this->escape($this->postulante['nombres']) . ' ' . $this->escape($this->postulante['apellidos']); ?>
            </span> actualizó su CV por última vez el <span class="dateDMAPEeMp">
                <?= $this->FriendlyDate($this->postulante['ultima_actualizacion']) . ' ( hace ' . $this->Hace($this->postulante['ultima_actualizacion']) . ')' ?>
            </span>
            <a class="icoCloseMsjD sptIcoEmp" href="#">
                <span class="hide">Cerrar</span>
            </a>
        </div>
    </div>
<?php } ?>

<?php
if (isset($this->postulante['mensajeProcesos']) && $this->postulante['mensajeProcesos']['verMensajeProcesos']) {
    ?>
    <div class="msgYellow mB10 r5 msgPerfilEPL">
        <div class="msgInPerfilEPL">
            <span class="namePEeMp">
                <?= $this->postulante['mensajeProcesos']['mensajeNombreProcesos'] ?>
            </span>
            <span class="dateDMAPEeMp">
                <?= $this->postulante['mensajeProcesos']['nombreProcesos'] ?>
            </span>
            <a class="icoCloseMsjD sptIcoEmp" href="#">
                <span class="hide">Cerrar</span>
            </a>
        </div>
    </div>
<?php } ?>
<?php
if (!isset($this->ocultar) && $this->ocultar != true):
    ?>
    <div id="urlPublic" class="feildsetB r2">
        <p class="c6 mB0">Mi perfil público:</p>
        <?
        $urlPP = $this->url(array('slug' => $this->postulante['slug']), 'perfil_publico', true);
        ?>
        <a href="<?= $urlPP ?>" target="_blank"><?= SITE_URL ?><?= $urlPP ?></a>
    </div>
<?php endif; ?>
<?php
if (count($this->experiencias) > 0) :
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Experiencia</h5>
        <div class="fieldsC">
            <?
            foreach ($this->experiencias as $i => $item):
                ?>
                <div class="all dListLR <?=
                ($i + 1 == count($this->experiencias)) ? ' lastDBdr' : ''
                ?>">
                    <dl class="dlList dListL left">
                        <dt class="titleJCP">
                        <span class="jobPCP">
                            <?php if ($item['id_puesto'] == Application_Model_Puesto::OTROS_PUESTO_ID)  {
                                echo $item['puesto'];
                            } else {
                                $puesto = mb_strtolower($item['nombre_puesto']);
                                echo ucfirst($puesto);
                            }
                            ?>
                        </span>
                        </dt>
                        <dd class="fieldPCP c6">
                            <span class="empPCP"><?php echo $this->escape($item['empresa']) ?></span>
                        </dd>
                        <?php if ($item['lugar'] == 2) { ?>
                            <dd class="fieldPCP c3">
                                <span class="bold f11"><?php echo $item['tipo_proyecto']; ?></span>
                            </dd>
                            <dd class="fieldPCP c3">
                                <span class="relTxtAE f11">
                                    <?php
                                    if (!empty($item['nombre_proyecto'])) {
                                        echo $item['nombre_proyecto'];
                                        echo (!empty($item['costo_proyecto']) && (float) $item['costo_proyecto'] > 0) ? ' ($ ' . $item['costo_proyecto'] . ')' : '';
                                    }
                                    ?>
                                </span>
                            </dd>
                        <?php } ?>
                        <dd class="fieldPCP c6">
                            <?php if ($item['rubro'] != '') : ?>
                                <span class="rubPCP">(<?php echo$this->escape($item['rubro']); ?>)</span>
                            <?php endif; ?>
                        </dd>
                        <dd class="fieldPCP c6">
                            <span class="fIniPCP f11">
                                <?php
                                echo $this->ItemList('Mes', $item['inicio_mes']) . " " . $item['inicio_ano']
                                ?>
                            </span> - <span class="fEndPCP f11">
                                <?php
                                echo
                                $item['actualmente'] == '1' ? ' (Actualmente)' : $this->ItemList('Mes', $item['fin_mes']) . " " . $item['fin_ano'];
                                ?>
                            </span>
                        </dd>
                    </dl>
                    <dl class="dlList dListR right">
                        <?
                        if ($item['comentarios'] != ''):
                            ?>
                            <dt class="titleDLCP c3">Descripción de tareas</dt>
                            <dd class="fieldPCP c9">
                                <?php echo $this->escape($item['comentarios']); ?>
                            </dd>
                        <? endif; ?>
                    </dl>

                    <div class="all">
                        <?
                        if (isset($item['referencias']) && count($item['referencias']) > 0):
                            ?>
                            <div class="cntRefer r5">
                                <dl class="dlListRefer">
                                    <dt class="dtListRefer ">Referencias</dt>
                                    <?
                                    foreach ($item['referencias'] as $i => $refer):
                                        ?>
                                        <dd class="ddListRefer">
                                            <span class="sNameRefer sReferen">
                                                <?= $this->escape($refer['nombre']); ?>
                                            </span>
                                            <span class="sPuestoRefer sReferen">
                                                <?= $this->escape($refer['cargo']); ?>
                                            </span>
                                            <span class="sTlf1Refer sReferen">
                                                <?= $this->escape($refer['telefono']); ?>
                                            </span>
                                            <span class="sTlf2Refer sReferen">
                                                <?= $this->escape($refer['telefono2']); ?>
                                            </span>
                                            <span class="sEmailRefer sReferen">
                                                <?= $this->escape($refer['email']); ?>
                                            </span>
                                        </dd>
                                    <? endforeach; ?>
                                </dl>
                            </div>
                        <? endif; ?>
                    </div>

                </div>

            <? endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php
if (count($this->estudios) > 0) :
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Estudios</h5>
        <div class="fieldsC">

            <?
            foreach ($this->estudios as $i => $item):
               ?>
                <?php
                if ($item['id_nivel_estudio'] != 1) {
                    ?>
                    <dl class="dlList dlListN<?=
                    ($i + 1 == count($this->estudios)) ? ' lastDlLN' : ''
                    ?>">
                        <dt class="titleJCP">
                        <span class="jobPCP">
                            <?php
                            if ($item['id_nivel_estudio'] == 3 || $item['id_nivel_estudio'] == 2) :
                                ?>
                                <?= $this->escape($item['nivel_nombre']) ?>
                            <?php else : ?>
                                <?= $this->escape($item['titulo']) ?> (<?= $this->escape($item['nivel_nombre'].' '.$item['nivel_tipo_nombre']) ?>)
                            <?php endif; ?>
                        </span>
                        </dt>
                        <?php
                        if ($item['id_nivel_estudio'] != 3 || $item['id_nivel_estudio'] != 2) {
                            ?>
                            <dd class="fieldPCP c9">
                                <span class="rubPCP">
                                    <?= $this->escape($item['institucion']) ?>&nbsp;</span>
                            </dd>
                        <?php } else { ?>
                            <dd class="fieldPCP c9">
                                <span class="rubPCP">
                                    <?= $this->escape($item['otro_institucion']) ?>&nbsp;</span>
                            </dd>
                        <?php } ?>
                        <?php
                        if (!empty($item['colegiatura_numero'])) :
                            ?>
                            <dd class="fieldPCP c9">
                                <span class="tlfPCP">
                                    <?= 'Colegiado (' . $this->escape($item['colegiatura_numero']) . ')'; ?>&nbsp;</span>
                            </dd>
                        <?php endif; ?>
                        <dd class="fieldPCP c6">
                            <span class="fIniPCP f11">
                                <?=
                                $this->ItemList('Mes', $item['inicio_mes']) . " " . $item['inicio_ano']
                                ?>
                            </span> -
                            <span class="fEndPCP f11">
                                <?=
                                $item['actualmente'] == '1' ? ' (Actualmente)' : $this->ItemList('Mes', $item['fin_mes']) . " " . $item['fin_ano'];
                                ?>
                            </span>
                        </dd>
                    </dl>
                <?php } else { ?>
                    <dl class="dlList dlListN<?=
                    ($i + 1 == count($this->estudios)) ? ' lastDlLN' : ''
                    ?>">
                        <dt class="titleJCP">
                        <span class="jobPCP">
                            <?= $this->escape($item['nivel_nombre']) ?>
                        </span>
                        </dt>
                    </dl>
                <?php } ?>
            <? endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php
if (count($this->otrosEstudios) > 0) :
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Otros Estudios</h5>
        <div class="fieldsC">

            <?
            foreach ($this->otrosEstudios as $i => $item):
               ?>
                    <dl class="dlList dlListN<?=
                    ($i + 1 == count($this->otrosEstudios)) ? ' lastDlLN' : ''
                    ?>">
                        <dt class="titleJCP">
                        <span class="jobPCP">
                                <?= $this->escape($item['titulo']) ?> (<?= $this->escape($item['nivel_tipo_nombre']) ?>)
                        </span>
                        </dt>
                            <dd class="fieldPCP c9">
                                <span class="rubPCP">
                                    <?= $this->escape($item['institucion']) ?>&nbsp;</span>
                            </dd>
                        <dd class="fieldPCP c6">
                            <span class="fIniPCP f11">
                                <?=
                                $this->ItemList('Mes', $item['inicio_mes']) . " " . $item['inicio_ano']
                                ?>
                            </span> -
                            <span class="fEndPCP f11">
                                <?=
                                $item['actualmente'] == '1' ? ' (Actualmente)' : $this->ItemList('Mes', $item['fin_mes']) . " " . $item['fin_ano'];
                                ?>
                            </span>
                        </dd>
                    </dl>
            <? endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php
if (count($this->idiomas) > 0) :
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Idiomas</h5>
        <div class="fieldsC">
            <?php foreach ($this->idiomas as $i => $item) :?>
                <p class="oneDdCP c3"><span class="nItemPCP"><?=
                        ucwords(mb_strtolower($this->ItemList('idioma', $item['idioma']), "utf8"))
                        ?></span> <span class="nivelPCP"><?=
                        $this->ItemList('DominioIdioma', $item['nivel'])
                        ?></span></p>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
<?php
if (count($this->programas) > 0) {
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Programas</h5>
        <div class="fieldsC">
            <?php
            foreach ($this->programas as $i => $item):
                ?>
                <p class="oneDdCP c3"><span class="nItemPCP"><?=
                        ucwords(mb_strtolower($item['programa']));
                        ?></span> <span class="nivelPCP"><?= ucfirst($item['nivel']); ?></span></p>
                    <?php endforeach; ?>
        </div>
    </div>
<?php } ?>
<?php
if (count($this->aptitudes) > 0) {
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Aptitudes</h5>
        <div class="fieldsC">
            <?php
            foreach ($this->aptitudes as $i => $item):
                ?>
                <p class="oneDdCP c3"><span class="nItemPCP"><?=
                        ucwords(mb_strtolower($item['mostrar']));
                        ?></span> </p>
                    <?php endforeach; ?>
        </div>
    </div>
<?php } ?>
<?php
if (count($this->logros) > 0) {
    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Logros</h5>
        <div class="fieldsC">
            <?php
            foreach ($this->logros as $i => $item):
                ?>
                <p class="oneDdCP c3"><span class="nItemPCP"><?=
                        ucwords(mb_strtolower($item['logro']));
                        ?></span> <span class="nivelPCP"><?= ucfirst($item['institucion']); ?></span></p>
                    <?php endforeach; ?>
        </div>
    </div>
<?php } ?>
<?php if (!empty($this->postulante['discapacidad']) > 0) {    ?>
    <div class="feildsetC r2">
        <h5 class="titleIMAU">Discapacidad</h5>
        <div class="fieldsC">
            <p class="oneDdCP c3">
                <span class="nivelPCP"> Tipo de discapacidad: </span>
                <span class="nItemPCP"><?=Application_Model_Postulante::$tipoDiscapacidad[$this->postulante['discapacidad']];?></span>
            </p>
            <?php if (!empty($this->postulante['conadis']) ) { ?>
            <p class="conadis_image"><img src="<?= $this->S('/images/conadis.png')?>" alt="conadis" width="40" height="34" /></p>
            <p class="oneDdCP c3">
                <span class="nivelPCP">  El postulante es una persona con discapacidad registrada en el Consejo Nacional para la Integración de la Persona con Discapacidad  </span>
                <span class="nItemPCP">(CONADIS)</span>
            </p>
            <?php } ?>
        </div>
    </div>
<?php } ?>
