<?php
$leng = strlen($this->postulante['estado_civil']);
?>
<style type="text/css"> 
    body { margin:20px!important; font-family: Arial, Helvetica, sans-serif;} 
    table { margin:0; padding:0; border-collapse: collapse; border-spacing: 0 }
    th,td { padding: 10px }
    @media print{
        .img-upload {
            height: 132px;
            position: relative;
            width: 132px;
        }
        .center-img img {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
        }
    }
</style>
<table style="width:<?=($this->postulante['fotovariable'] != '') ? '83%' : '85%'?>"> 
    <tbody>
        <tr>
            <td align="center" valign="middle" style="width:<?=($this->postulante['fotovariable'] != '') ? '20%' : ''?>; border-width: 1px 0 1px 1px; border-style: solid; border-color: #B2E0F5; vertical-align: top">
                <?php
                if ($this->postulante['fotovariable'] != '') :
                    ?>
                    <table border="0" style="border-width: 2px; border-style: solid; border-color: #CCCCCC;width:132px;height:152px;">
                      <tr>
                        <td align="center" valign="middle"><img alt="<?= $this->postulante['nombres'] . " " . $this->postulante['apellidos'] ?>" src="<?= ELEMENTS_URL_IMG . $this->postulante['fotovariable'] ?>"/></td>
                      </tr>
                    </table>
                <?php endif; ?>
            </td>
            <td style="width:<?=
            ($this->postulante['fotovariable'] != '') ? '80%' : '83%'
            ?>; border-width: 1px 1px 1px 0; padding:5px 0 0; border-style: solid; border-color: #B2E0F5">
                <div style="font-size:18pt; padding-bottom:2px; color:black">
                    <span><?= $this->postulante['nombres'] ?></span>
                    <span><?= $this->postulante['apellidos'] ?></span>
                </div>
                <?php
                if (!isset($this->ocultar) && $this->ocultar != true):
                    if ($this->mejor_nivel_puesto != null) {
                        ?>
                        <div style="font-size:13pt; padding-bottom:2px; color:#666">
                            <span>
                                <?= $this->mejor_nivel_puesto['nivel_estudio'] ?> <?= $this->mejor_nivel_puesto['nivel_estudio_tipo'] ?> (<?= $this->escape($this->mejor_nivel_puesto['carrera']) ?>)</span>
                        </div>
                        <div style="font-size:13pt; padding-bottom:2px; color:#666">
                            <span class="tlfPCP">
                                <?= ($this->mejor_nivel_puesto['colegiatura_numero']) ? 'Colegiado (' . $this->escape($this->mejor_nivel_puesto['colegiatura_numero']) . ')' : ''; ?></span>
                        </div>
                        <?php
                    }
                endif;
                ?>      
                <div style="font-size:13pt; padding-bottom:2px; color:#666">
                    <span><?= $this->Edad($this->postulante['fecha_nac']) ?> años - </span>
                    <span ><?=
                        $this->postulante['sexoMF'] == 'M' ? ucfirst($this->postulante['estado_civil']) : ucfirst(substr($this->postulante['estado_civil'], 0, $leng - 1) . 'a')
                        ?></span>
                </div>
                <div style="font-size:13pt; padding-bottom:2px; color:#666">
                    <span><?= $this->postulante['ubicacion'] ?><?= ($this->postulante['extranjero'] == 1) ? ' - (Dispuesto para viajar)' : ''; ?></span>
                </div>
                <div style="font-size:13pt; padding-bottom:2px; color:#666">
                    <span><?= strtoupper($this->postulante['tipo_doc']) ?></span>
                    <span><?= $this->postulante['num_doc'] ?></span>
                </div>
                <div style="font-size:13pt; padding-bottom:2px; color:#666">
                    <span><?= $this->postulante['telefono'] ?></span>
                </div>
                <div style="font-size:13px; padding-bottom:2px; color:#007FD3">
                    <span><a style="font-size:13pt; color:#007FD3" href=mailto:<?= $this->postulante['email'] ?>><?= $this->postulante['email'] ?></a></span>
                </div>
            </td>
        </tr>

    </tbody>
</table>


<?php
$pres = $this->postulante['presentacion'];
?>
<?php if ($pres != '') : ?>
<div style="width:83%">
        <div style="color:black; font-size:15pt; padding:0 0 2px 0; padding-top: 6px; margin:0 0 2px 10px">Presentación</div>
        <div style="font-size:9pt; line-height:1.2; color:#666; margin:0 0 2px 10px"><?= $pres ?></div>
</div>
<?php endif; ?>

<div style="height:20px; width:85%"></div>

<?php
if (isset($this->ocultar) && $this->ocultar == true):
    ?>
    <div style="width:85%; padding:0; margin:0; border: 1px solid #B2E0F5">
        <div style="padding:10px 10px 20px">
            <div style="color:#666; padding:0 0 5px; font-size:13pt">Ver tu perfil público:</div>
            <div>
                <?
                $urlPP = $this->url(array('slug' => $this->postulante['slug']), 'perfil_publico', true);
                ?>
                <a style="font-size:14pt; color:#007FD3" href="<?= $urlPP ?>" target="_blank"><?= SITE_URL ?><?= $urlPP ?></a>
            </div>
        </div>
    </div>
<?php endif; ?>

<?php
if (count($this->experiencias) > 0) :
    ?>
    <div style="height:20px; width:83%"></div>
    <div style="width:83%; padding:0; margin:0; border: 1px solid #B2E0F5">
        <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Experiencia</div>
        <div style="padding:20px 10px">
            <?
            foreach ($this->experiencias as $i => $item):
                ?>
                <?
                if (isset($item['referencias']) && count($item['referencias']) > 0):
                    ?>	
                    <div style="width:83%; padding:0 0 5px">
                    <? else : ?>
                        <div style="width:83%; padding:0 0 20px">
                        <? endif; ?>
                        <div style="font-size:16pt; color:#333"><?php echo $this->escape($item['puesto']); ?></div>
                        <div><span style="font-size:12pt; color:#F60"><?php echo $this->escape($item['empresa']); ?></span></div>
                        <div><span style="font-size:12pt; color:#333"><?php echo $this->escape($item['tipo_proyecto']); ?></span></div>
                        <?php if (!empty($item['nombre_proyecto'])) { ?>
                            <div><span style="color:#999999;font-style:italic;"><?php
                                    echo $item['nombre_proyecto'];
                                    echo (!empty($item['costo_proyecto'])) ? ' ($ ' . $item['costo_proyecto'] . ')' : '';
                                    ?>
                                </span></div>
                        <?php } ?>
                        <div><?php
                            if ($item['rubro'] != '') :
                                ?>
                                <span style="font-size:13pt; color:#666">
                                    (<?php echo $this->escape($item['rubro']); ?>)
                                </span>
                            <?php endif; ?>
                        </div>
                        <div style="padding:0 0 5px"><span style="font-size:11pt; color:#666"><?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?></span> - <span style="font-size:11pt; color:#666"><?=
                                $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano'];
                                ?></span></div>
                        <div style="font-size:11pt; color:#333">Descripción de tareas:</div>
                        <div style="font-size:12pt; color:#999"><?php echo $this->escape($item['comentarios']); ?></div>
                    </div>

                    <?
                    if (isset($item['referencias']) && count($item['referencias']) > 0):
                        ?>
                        <div style="border:1px solod #E3E3E3; background-color:#F3F3F3; padding:10px">
                            <div style="font-size:14px; color:#666666">Referencias</div>
                            <?
                            foreach ($item['referencias'] as $i => $refer):
                                ?>
                                <div style="line-height:1.2">
                                    <span style="font-size:13px; color:#9F9F9F"><?php echo $this->escape($refer['nombre']); ?></span>
                                    <span style="font-size:13px; color:#9F9F9F"><?php echo $this->escape($refer['cargo']); ?></span>
                                    <span style="font-size:13px; color:#9F9F9F"><?php echo $this->escape($refer['telefono']); ?></span>
                                    <span style="font-size:13px; color:#9F9F9F"><?php echo $this->escape($refer['telefono2']); ?></span>
                                    <span style="font-size:13px; color:#9F9F9F"><?php echo $this->escape($refer['email']); ?></span>
                                </div>
                            <? endforeach; ?>
                        </div>
                        <div style="height:20px; width:83%"></div>
                    <? endif; ?>

                <? endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php
    if (count($this->estudios) > 0) :
        ?>
        <div style="height:20px; width:83%"></div>
        <div style="width:83%; padding:0; margin:0; border: 1px solid #B2E0F5">
            <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Estudios</div>
            <div style="padding:20px 10px">
                <?
                foreach ($this->estudios as $i => $item):
                    ?>
                    <?php
                    if ($item['id_nivel_estudio'] != 1) {
                        ?>
                        <div style="width:83%; padding:0 0 20px">
                            <div style="font-size:16pt; color:#333">
                                <?php
                                if ($item['id_nivel_estudio'] == 3 || $item['id_nivel_estudio'] == 2) :
                                    ?>
                                    <?php echo $this->escape($item['nivel_nombre']); ?>
                                <?php else : ?>
                                    <?php echo $this->escape($item['titulo']); ?> (<?php echo $this->escape($item['nivel_nombre'].' '.$item['nivel_tipo_nombre']); ?>)
                                <?php endif; ?>
                            </div>
                            <?php
                            if ($item['id_nivel_estudio'] != 3 || $item['id_nivel_estudio'] != 2) {
                                ?>
                                <div style="font-size:14pt; color:#999"><?= $item['institucion'] ?>&nbsp;</div>
                            <?php } else { ?>
                            <div style="font-size:14pt; color:#999"><?= $item['otro_institucion'] ?>&nbsp;</div>
                            <?php } ?>
                            <?php
                            if (!empty($item['colegiatura_numero'])) {
                                ?>
                                <div style="font-size:14pt; color:#999"><?= 'Colegiado (' . $this->escape($item['colegiatura_numero']) . ')'; ?>&nbsp;</div>
                            <?php } ?>
                            <div style="font-size:14pt; color:#666"><?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?> </span> - <span class="fEndPCP f11"><?=
                                    $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano'];
                                    ?></div>
                        </div>
                    <?php } else { ?>
                        <div style="width:83%; padding:0 0 20px">
                            <div style="font-size:16pt; color:#333"><?php echo $this->escape($item['nivel_nombre']); ?></div>
                        </div>
                    <?php } ?>
                <? endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php
    if (count($this->otrosEstudios) > 0) :
        ?>
        <div style="height:20px; width:83%"></div>
        <div style="width:83%; padding:0; margin:0; border: 1px solid #B2E0F5">
            <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Otros Estudios</div>
            <div style="padding:20px 10px">
                <?
                foreach ($this->otrosEstudios as $i => $item):
                    ?>
                        <div style="width:83%; padding:0 0 20px">
                            <div style="font-size:16pt; color:#333">
                                    <?php echo $this->escape($item['titulo']); ?> (<?php echo $this->escape($item['nivel_tipo_nombre']); ?>)
                            </div>
                                <div style="font-size:14pt; color:#999"><?= $item['institucion'] ?>&nbsp;</div>
                            <div style="font-size:14pt; color:#666"><?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?> </span> - <span class="fEndPCP f11"><?=
                                    $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano'];
                                    ?></div>
                        </div>
                <? endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php
    if (count($this->idiomas) > 0) :
        ?>
        <div style="height:20px; width:83%"></div>
        <div style="width:83%; padding:0; margin:0; border: 1px solid #B2E0F5">
            <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Idiomas</div>
            <div style="padding:20px 10px">
                <?php
                foreach ($this->idiomas as $i => $item):
                    ?>
                    <div style="padding:0 0 5px"><span style="font-size:14pt; padding-right:5px; color:#333; font-weight:bold"><?=
                            ucwords(mb_strtolower(($this->ItemList('idioma', $item['idioma'])), "utf8"))
                            ?></span> <span style="font-size:14pt; color:#333"><?=
                            $this->ItemList('DominioIdioma', $item['nivel'])
                            ?></span></div>
                    <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php
    if (count($this->programas) > 0) :
        ?>
        <div style="height:20px; width:83%"></div>
        <div style="width:83%; padding:0; margin:0; border: 1px solid #B2E0F5">
            <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Programas</div>
            <div style="padding:20px 10px">
                <?
                foreach ($this->programas as $i => $item):
                    ?>
                    <div style="padding:0 0 5px"><span style="font-size:14pt; padding-right:5px; color:#333; font-weight:bold"><?=
                            ucwords(mb_strtolower($item['programa'])) ?></span> 
                        <span style="font-size:14pt; color:#333"><?= $item['nivel'] ?></span></div>
                    <? endforeach; ?>
            </div>
        </div>
    <?php endif; ?>
    <?php
    if ($this->postulante['website'] != '') :
        ?>
        <div style="height:20px; width:83%"></div>
        <div style="width:83%; padding:0; margin:0 0 10px; border: 1px solid #B2E0F5">
            <div style="background-color:#CCECFB; font-size:15pt; color:black; padding:10px">Sitio Web</div>
            <?php
            $cadOne = "http://";
            $website = $this->postulante['website'];
            if (strpos($cadOne, $website)) {
                $website = $cadOne . str_replace($cadOne, "", $website);
            }  else {
                $extCad = substr(strtolower($website), 0,4);
                if ($extCad != 'http')
                    $website = $cadOne . $website;
            }
            $cadTwo = "https://";
            if (strpos($cadTwo, $website)) {
                $website = $cadTwo . str_replace($cadTwo, "", $website);
            } 
            ?>
            <div style="padding:20px 10px"><a style="font-size:14pt; color:#007FD3" target="_blank" href="<?php echo $website; ?>" class="nUrlPCP"><?php echo $website; ?></a></div>
        </div>
    <?php endif; ?>
