<?php if ($this->existe) {?>
<form id="frmReference" action="/mi-cuenta/referencia-ajax" autocomplete="off" class="type1 mt20"  method="post">
  <div class="form_box border_grey">
    <div class="form_row">
      <div class="form_col12">
        <fieldset>
          <label>experiencia</label>
                    <?= $this->form->selCareReference->setAttribs(array('class' => 'pretty_select_2'))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col6">
        <fieldset>
          <label>Nombre</label>
          <?= $this->form->txtNameReference->setAttribs(array('class' => 'input_control','placeholder'=>'Ingrese nombre de quien te refiere', 'required' => '', 'maxlength' => '75', 'minlength' => '2'))->renderViewHelper(); ?>                      
        </fieldset>
      </div>
      <div class="form_col6">
        <fieldset>
          <label>puesto</label>
          <?= $this->form->txtPositionReference->setAttribs(array('class' => 'input_control','placeholder'=>'Ingrese nombre de puesto', 'required' => '', 'maxlength' => '75', 'minlength' => '2'))->renderViewHelper(); ?>                      
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col6">
        <fieldset>
          <label>teléfono 1</label>
                          <?= $this->form->txtTelephoneReferenceOne->setAttribs(array('class' => 'input_control','placeholder'=>'Ingrese teléfono de la referencia', 'required' => '', 'maxlength' => '75', 'minlength' => '6'))->renderViewHelper(); ?>
        </fieldset>
      </div>
      <div class="form_col6">
        <fieldset>
          <label>teléfono 2</label>
                    <?= $this->form->txtTelephoneReferenceTwo->setAttribs(array('class' => 'input_control','placeholder'=>'Ingrese teléfono de la referencia', 'maxlength' => '75', 'minlength' => '6'))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row">
      <div class="form_col12">
        <fieldset>
          <label>Email</label>
              <?= $this->form->txtTelephoneReferenceEmail->setAttribs(array('class' => 'input_control','placeholder'=>'Ingrese Email de la referencia', 'required' => '', 'maxlength' => '100', 'minlength' => '2'))->renderViewHelper(); ?>
        </fieldset>
      </div>
    </div>
    <div class="form_row buttons_row">
      <input id="hidReference" name="hidReference" type="hidden" value="0">
      
      <button class="btn btn_save" disabled>
        <span class="btn_label">Guardar</span>
        <span class="btn_spinner"></span>
      </button>
      <button class="btn btn_cancel type_basic" type="button">Cancelar</button>
    </div>
  </div>
</form>
<?php }?>
