<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
?>
<div id="e<?php echo $ind ?>_expeN" class="skillN" rol="<?= $this->form->id_estudio!=null? $this->form->id_estudio->getValue():'0';?>" >			
	<div id="e<?php echo $ind ?>_expTDiv" class="expTDiv <?$this->isLinkedin || $this->isEstudio?'':'hide'?>">
	<?php if (isset($this->isLinkedin) || $this->isEstudio == true) { ?>
	<blockquote class="addReg">
		<span class="wCount left">
			<span class="countN"><?php echo $ind + 1; ?></span>
		</span>
		<span class="wJob left">
			<span class="jobReg bold"><?=$this->form->id_carrera->getMultiOption($this->form->id_carrera->getValue()); ?></span> en 
			<span class="eJob bold"><?=$this->form->id_institucion->getMultiOption($this->form->id_institucion->getValue()); ?></span>
		</span>
		<a href="#Editar" class="editB upF" title="Editar"><span class="sEditB f11">Editar</span></a>
		<a rel="#e<?php echo $ind ?>_expeN" rol="#winAlert" href="#winAlert" class="deleteB winAlertM" title="¿Estás seguro que deseas eliminar?"><span class="sDeleteB f11">Eliminar</span></a>
	</blockquote>
	<?php } ?>
	</div>
	<?$isError = $this->form->isErrors(); ?>
	<div id="e<?php echo $ind ?>_fSkill" class="fSkill <?=(!$isError && $this->isEstudio)?'hide':''?>" >
		<div class="block" rel="sectionEst">
			<label for="<?=$this->form->id_nivel_estudio->getAttrib('id')?>" class="labelN"><span class="req"
				title="Requerido">*</span> Nivel:</label>
				<?$hasError = $this->form->id_nivel_estudio->hasErrors(); ?>
				<?php if (!$hasError && ($this->isLinkedin || $this->isEstudio)) { ?>
				<?=$this->form->id_nivel_estudio->setAttribs(array('class'=>'selectN left selectReq ready'))->renderViewHelper(); ?>
				<?php } else { ?>
				<?=$this->form->id_nivel_estudio->setAttribs(array('class'=>'selectN left selectReq'))->renderViewHelper(); ?>
				<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->id_nivel_estudio->errMsg:''?></span>
		</div>
		<div class="block" rel="sectionEst">
			<label for="<?=$this->form->id_institucion->getAttrib('id')?>" class="labelN"><span class="req"
				title="Requerido">*</span> Nombre de la institución:</label>
			<?$hasError = $this->form->id_institucion->hasErrors(); ?>
			<?php if (!$hasError && ($this->isLinkedin || $this->isEstudio)) { ?>
			<?=$this->form->id_institucion->setAttribs(array('class'=>'fNiv selectN left selectReq ready'))->renderViewHelper(); ?>
			<?php } else { ?>
			<?=$this->form->id_institucion->setAttribs(array('class'=>'fNiv selectN left selectReq'))->renderViewHelper(); ?>
			<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->id_institucion->errMsg:''?></span>
		</div>
		<div class="block" rel="sectionEst">
			<label for="<?=$this->form->id_carrera->getAttrib('id')?>" class="labelN"><span class="req"
				title="Requerido">*</span> Carrera:</label>
				<?$hasError = $this->form->id_carrera->hasErrors(); ?>
				<?php if (!$hasError && ($this->isLinkedin || $this->isEstudio)) { ?>
    			<?=$this->form->id_carrera->setAttribs(array('class'=>'fNiv selectN left selectReq ready'))->renderViewHelper(); ?>
    			<?php } else { ?>
    			<?=$this->form->id_carrera->setAttribs(array('class'=>'fNiv selectN left selectReq'))->renderViewHelper(); ?>
    			<?php } ?>
				<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->id_carrera->errMsg:''?></span>
		</div>
		<div class="block bDate initDate" rel="sectionEst">
			<label for="<?=$this->form->inicio_ano->getAttrib('id')?>" class="labelN"><span class="req"
				title="Requerido">*</span> Fecha de Inicio:</label>
			<div class="iBlockM left">
				<?=$this->form->inicio_mes->setAttribs(array('class'=>'monthY1 selectMN left', 'rel'=>'1'))->renderViewHelper(); ?>
				<?=$this->form->inicio_ano->setAttribs(array('class'=>'fIni left clearH cGray iDateY numReq ready','maxlength'=>'4','alt'=>'2010'))->renderViewHelper(); ?>
			</div>	
			<span class="response rIni def cGray left"> </span>
		</div>
		<div class="block bDate endDate" rel="sectionEst">
			<label for="<?=$this->form->fin_ano->getAttrib('id')?>" class="labelN"><span class="req"
				title="Requerido">*</span> Fecha de Fin:</label>
			<div class="iBlock left">
				<?=$this->form->fin_mes->setAttribs(array('class'=>'monthY2 selectMN inputOn left', 'rel'=>'1'))->renderViewHelper(); ?>
				<?=$this->form->fin_ano->setAttribs(array('class'=>'fFin left clearH cGray iDateY inputOn numReq ready','maxlength'=>'4','alt'=>'2011'))->renderViewHelper(); ?>
			</div>
			<div class="iBlockN left">
				<label for="<?=$this->form->en_curso->getAttrib('id')?>">
				<?=$this->form->en_curso->setAttribs(array('class'=>'checkWorkE checkN left inputOff noBdr'))->renderViewHelper(); ?>
				 Actualmente estudiando</label>
			</div>
			<span class="response rFin cGray left def"> </span>
		</div>
		<div class="hide">
		<?=$this->form->id_estudio;?>
		</div>
	</div>
</div>

