<? $active = "active"; ?>
<div class="ctn-smenu">
    <ul class="row">
        <li><a class="<?=$this->menu_post_sel==App_Controller_Action_Postulante::MENU_POST_INICIO?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'index'),null,true)?>">Inicio</a></li>
        <li><a class="<?=$this->menu_post_sel==App_Controller_Action_Postulante::MENU_POST_MIS_DATOS?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'mis-datos-personales'),null,true)?>">Mi Perfil</a></li>
        <li><a class="<?=$this->menu_post_sel==App_Controller_Action_Postulante::MENU_POST_MIS_POSTULACIONES?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'postulaciones','action'=>'index'),null,true)?>">Postulaciones</a></li>
        <li><a class="<?=$this->menu_post_sel==App_Controller_Action_Postulante::MENU_POST_MIS_NOTIFICACIONES?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'notificaciones','action'=>'index'),null,true)?>">Notificaciones</a></li>
        <li><a class="<?=$this->menu_post_sel==App_Controller_Action_Postulante::MENU_POST_SUBE_CV?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'subir-cv','action'=>'index'),null,true)?>">Subir mi CV</a></li>
    </ul>
</div>
