<?php $active2 = 'active'; ?>
<div class="configuration_options">        
    <ul class="list_options"> 
        <li class="title_options"><a href="javascript:;">Configuración <i class="icon icon_mesh"></i></a></li>
        <li><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'mis-alertas'),false,true)?>" class="item border_bottom <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_ALERTAS?$active2:''?>">Mis alertas</a></li>
        <li><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'cambio-de-clave'),false,true)?>" class="item border_bottom <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_CAMBIOCLAVE?$active2:''?>">Contraseña</a></li>
        <?/*<li><a href="javascript:;" class="item <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_REDES_SOCIALES?$active2:''?>">Asociar a redes</a></li>*/?>
        <li><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'privacidad'),false,true)?>" class="item <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_PRIVACIDAD?$active2:''?>">Privacidad</a></li>
        <li><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'eliminar-cuenta'),false,true)?>" class="item <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_ELIMINAR_CUENTA?$active2:''?>">Eliminar cuenta</a></li>
    </ul>
</div>