<?php $active2 = "active"; ?>
<div class="grids-2 fix">
    <h5 class="black-title txt-left">Perfil Profesional</h5>
    <ul class="wrap-menu">
        <?php $url = SITE_URL.'/mi-cuenta/mis-datos-personales'; ?>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_DATOSPERSONALES?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-datos-personales'?>">Datos personales</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_EXPERIENCIA?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-experiencias'?>">Experiencia</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_ESTUDIOS?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-estudios'?>">Estudios</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_OTROSESTUDIOS?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-otros-estudios'?>">Otros Estudios</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_IDIOMAS?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-idiomas'?>">Idiomas</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_PROGRAMAS?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-programas'?>">Programas</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_REFERENCIAS?$active2:''?>"><a href="<?=SITE_URL.'/mi-cuenta/mis-referencias'?>">Referencias</a></li>
    </ul>
    <h5 class="black-title txt-left">Datos</h5>
    <ul class="wrap-menu">
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_PERFILPUBLICO?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'mi-perfil'),false,true)?>">Ver perfil p&uacute;blico</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_PERFILDESTACADO?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'perfil-destacado'),false,true)?>">Mi Perfil Destacado</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_CAMBIOCLAVE?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'cambio-de-clave'),false,true)?>">Cambio de clave</a></li>
        <li class="redSocialCP <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_REDES_SOCIALES?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'redes-sociales'),false,true)?>">Asocia tu cuenta</a></li>
        <li class="<?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_PRIVACIDAD?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'privacidad'),false,true)?>">Mi Privacidad</a></li>
        <li class="liLast <?=$this->menu_sel_side==App_Controller_Action_Postulante::MENU_POST_SIDE_ALERTAS?$active2:''?>"><a href="<?=$this->url(array('controller'=>'mi-cuenta','action'=>'mis-alertas'),false,true)?>">Mis Alertas</a></li>
    </ul>                
</div>

