<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel))
?>

<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
    <div class="legend history"><a href="/mi-cuenta">Inicio</a> » <span class="noLink">Avisos de empleo sugeridos</span></div>
    <div id="legendTitNF" class="legend rel">
        <h2 id="titleModSP" class="bold">
            Puestos sugeridos para tu perfil
        </h2>
        <a id="atencionModl" class="icoSpt winModal" href="#winAtencionN">Atención</a>
    </div>
    <div class="pagination bBGray">
        <?php
        $cantAnuncios
            = count($this->listaAnunciosSugeridos)
        ?>
        <p class="pagLegend mB0 cGray">Mostrando <?php echo $cantAnuncios ?> sugerido<?php
            echo $cantAnuncios > 1 ? 's' : ''
            ?></p>
    </div>
    <?
    $x
        = 0;
    foreach ($this->listaAnunciosSugeridos as $item):
        ?>
        <? $x++; ?>                
        <div class="blockEntry <?=
        $x % 2 == 0 ? "evenList" : "";
        ?> ">
            <a name="aviso_<?= $item['id_anuncio_web'] ?>"></a>
            <div class="all">
                <?php
                $url
                    = $this->url(array('slug' => $item['slug'], 'url_id' => $item['url_id']),
                    'aviso_resultado', true);
                ?> 
                <div class="contenImg left">
                    <?
                    $logo = ($item["logoanuncio"] == "" || $item["logoanuncio"] == NULL)
                            ?
                        $this->verLogoDefecto ? $this->S('/images/' . $this->logoDefecto)
                                : ''  : ELEMENTS_URL_LOGOS . $item["logoanuncio"];
                    if ($logo != ''):
                        ?>
                        <a class="logoEntry left" href="<?=
                        substr($url, -strlen($url), strlen($url) - 10)
                        ?>">
                            <img <?=
                            ($this->ImgLadoMayor($logo)) == "width" ? "width='90'"
                                    : "height='90'";
                            ?>
                                src="<?= $logo; ?>" alt="<?= $item["empresa_rs"] ?>" title="<?= $item["empresa_rs"] ?>">
                        </a>
                    <? endif; ?>
                </div>
                <div class="dataEntry left">
                    <h2 class="jobEntry mB5 bold"><a href="<?=
                        substr($url, -strlen($url), strlen($url) - 10)
                        ?>"><?= $item["puesto"] ?></a></h2>
                    <h3 class="nameEntry"><?= $item["empresa_rs"] ?> - <?= $item["display_name"]; ?> </h3>
                    <p class="dataStr mB0 c3" ><?=
                        substr($item["funciones"] . " " . $item["responsabilidades"],
                            0, $this->recortaraviso) . " ..."
                        ?></p>
                </div>
                <div class="options right"> <span class="currentTime">
                        <?
                        if ($item["dias_fp"] != 0):
                            ?>
                            Publicado hace <em class="bold"><?= $item["dias_fp"] ?> días
                            <? else: ?>
                                Publicado hoy    
                            <? endif; ?>
                        </em></span>
                    <div class="spanView"><a class="linkView" href="<?=
                                             $this->url(array(
                                                 'slug' => $item['slug'],
                                                 'url_id' => $item['url_id']),
                                                 'aviso', true)
                                             ?>">Ver aviso</a></div>
                </div>
            </div>
        </div>
    <? endforeach; ?>
</div>