<div class="configuration_wrapper">    
      <?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages))?>    
      <div class="center_box">         
        <?= $this->partial('mi-cuenta/_sidebar-menu_mi_cuenta_datos.phtml', array('menu_sel_side' => $this->menu_sel_side)) ?>          
        <div class="content_wrapper">            
            <span class="title_content">Contraseña</span>
            <form action="" method="post" id="frmChangePassword" class="type1 frm_password">
                <?=
                $this->partial('mi-cuenta/_cambio_clave_mi_cuenta.phtml',array(
                    'formCambioClave' => $this->formCambioClave,
                    'username' => $this->username
                ));
                ?>                                              
                <button type="submit" class="btn btn_save">Guardar</button>
            </form>
            
        </div>
    </div>
</div>