<?=
$this->partial('_partials/_navigation.phtml',array(
	 'menu_sel' => $this->menu_sel
))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',array(
	 'menu_post_sel' => $this->menu_post_sel
))
?>
<div id="wrapper" class="row">
<?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
	<div class="row">
		<div class="grids-3 wrap-dash">
			<h6 class="black-title small">Perfil Profesional</h6>
			<div class="profile row">
				<div class="center-img"><img <?=
								($this->imgPhoto != '') ? (($this->ImgLadoMayor(ELEMENTS_ROOT_IMG . $this->imgPhoto))
									 == "width" ? "width='90'" : "height='90'") : "";
								?> alt="<?= $this->escape($this->nombres . " " . $this->apellidos); ?>" src="<?=
									 ($this->imgPhoto == '') ? $this->S('/images/profile-default.jpg') . '" width="90'
												: ELEMENTS_URL_IMG . $this->imgPhoto;
									 ?>"></div>
				<div class="profile-summary">
					<p><?= $this->escape($this->nombres . " " . $this->apellidos); ?></p>
					<div class="rank" data-percent="<?= $this->porcentaje ?>">
						<span> </span>
					</div>
					<span><span class="percent"><?= $this->porcentaje ?>%</span> del perfil completo</span>
					<a href="/mi-cuenta/mis-datos-personales" type="button" class="btn btn-primary" title="Completa tu Perfil">Completa tu Perfil</a>
				</div>
			</div>
			<div class="profile-detail">
				 <?php if(!empty($this->vis)){?>
				<p>Tu perfil ha sido visto <b><?php echo $this->vis?></b> veces</p>
				 <?php }?>
				 <?php if(!empty($this->bus)){?>
				<p>Tu CV se ha mostrado <b><?php echo $this->bus?></b> veces</p>
				 <?php }?>

				<?php
					 if ($this->porcentaje < 100) {
						  ?>
				<h6 class="titleIDMC">Tips para completar tu perfil</h6>
				<ul class="listDMC all mB20">
<!--               <li><a href="/mi-cuenta/mis-experiencias" title="Añade Experiencia">Añade Experiencia</a></li>
					<li><a href="/mi-cuenta/mis-estudios" title="Añade Estudios">Añade Estudios</a></li>
					<li><a href="/mi-cuenta/mis-idiomas" title="Añade Idiomas">Añade Idiomas</a></li>
					<li><a href="/mi-cuenta/mis-programas" title="Añade Programas">Añade Programas</a></li>
					<li><a href="/mi-cuenta/mis-referencias" title="Añade Referencias">Añade Referencias</a></li>
					<li><a href="javascript:;" title="Pide Recomendaciones">Pide Recomendaciones</a></li>-->
								<?php
								foreach ($this->incompletos as $x) {
									 ?>


									 <li class="itemDMC"><a href="<?=
										  ($x == $this->var->sug->subircv) ? $this->var->url->subircv
													 : (
												($x == $this->var->sug->experiencia) ? $this->var->url->experiencia
														  : (
													 ($x == $this->var->sug->estudios) ? $this->var->url->estudios
																: (
														  ($x == $this->var->sug->idiomas) ? $this->var->url->idiomas
																	 : (
																($x == $this->var->sug->programas)
																		  ? $this->var->url->programas
																		  : (
																	 ($x == $this->var->sug->presentacion)
																				? $this->var->url->presentacion
																				: (
																		  ($x == $this->var->sug->tuweb)
																					 ? $this->var->url->tuweb
																					 : (
																				($x == $this->var->sug->foto)
																						  ? $this->var->url->foto
																						  : "")))))))
										  ?>">
												<?= $x ?></a><span class="emBlock enumDMC alignR txtEnfasis right">+<?=
												($x == $this->var->sug->subircv) ? $this->var->peso->subircv
														  : (
													 ($x == $this->var->sug->experiencia) ? $this->var->peso->experiencia
																: (
														  ($x == $this->var->sug->estudios) ? $this->var->peso->estudios
																	 : (
																($x == $this->var->sug->idiomas)
																		  ? $this->var->peso->idiomas
																		  : (
																	 ($x == $this->var->sug->programas)
																				? $this->var->peso->programas
																				: (
																		  ($x == $this->var->sug->presentacion)
																					 ? $this->var->peso->presentacion
																					 : (
																				($x == $this->var->sug->tuweb)
																						  ? $this->var->peso->tuweb
																						  : (
																					 ($x == $this->var->sug->foto)
																								? $this->var->peso->foto
																								: "0")))))))
												?> %</span></li>
									 <?php } ?>
					 <?php }?>
				</ul>
				<h6 class="titleIDMC">Tu perfil público</h6>
					 <ul class="listDMC">
						  <li class="itemDMC linkDMC lastItemDMC">
								<?php
								$urlPP
									 = $this->url(array('slug' => $this->slug),
									 'perfil_publico', true);
								?>
								<a title="<?= SITE_URL ?><?= $urlPP ?>" class="tooltipApt" href="<?= $urlPP ?>" target="_blank">Tu perfil público</a>
						  </li>
					 </ul>
			</div>
		</div>
		<div class="grids-3">
			<ul class="dashboard-option row">
			<li><a href="/mi-cuenta/mis-datos-personales" title="Mis datos"><i class="icon  icon_person"></i><p>MIS DATOS</p></a></li>
			<li><a href="/postulaciones" title="Postulaciones"><i class="icon icon_menu"></i> <p>POSTULACIONES</p></a></li>
<!--         <li><a href="javascript:;" title="Alertas"><span class="icon-card"></span> <p>ALERTAS</p></a></li>-->
			<li><a href="/notificaciones" title="Mensajes"><i class="icon icon_message"></i> <p>MENSAJES</p></a></li>
<!--         <li><a href="javascript:;" title="Importar Datos"><span class="icon-linkedIn"></span> <p>IMPORTAR DATOS DE LINKEDIN</p></a></li>-->
			<?php if(empty($this->destacado)){?>
			<li><a href="/perfil-destacado" title="Destaca tu perfil"><i class="icon icon_star2"></i> <p>DESTACA TU PERFIL</p></a></li>
			<?php }?>
			</ul>
		</div>
		<div class="grids-300 interest-jobs">
			<p class="title">MIS NOTIFICACIONES</p>

			<ul class="list-items2">
		  <?php
		  foreach ($this->notificaciones as $n):
				?>
					<li>
					<span class="icon-row big"></span>
					<p><?=
						  $this->escape(substr($n['cuerpo'], 0, 64)) . '...'
						  ?></p>
				</li>
		  <?php endforeach; ?>
			</ul>
		</div>
	</div>
		<?php /*
		<div class="blog-wrapper">
			<h4 class="EMPLEOBUSCO-title middle"><i class="icon icon_pencil"></i>BLOG EMPLEOBUSCO</h4>
			<div class="left-blog">
				<div class="center-img"><img src="/static/images/elements/image_blog.jpg"></div>
				<a class="subtitle-blog" href="javascript:;">Asesor virtual: Si llevo mucho tiempo contratado temporalmente por una empresa,
				¿tengo derecho a obtener un contrato indefinido?</a>
				<p>Por: <span class="for">Marco Antonio Zegarra</span></p>
			</div>
			<div class="right-blog">
				<ul class="row">
					<li>
					<a class="subtitle-blog" href="javascript:;">Asesor virtual: Si llevo mucho tiempo contratado temporalmente por una empresa,
					¿tengo derecho a obtener un contrato indefinido?</a>
					<p>Por: <span class="for">Marco Antonio Zegarra</span></p>
					<p>Uno de los supuestos de desnaturalización de los contratos sujetos a modalidad – contenidos en la...</p>
					</li>
					<li>
					<a class="subtitle-blog" href="javascript:;">Asesor virtual: Si llevo mucho tiempo contratado temporalmente por una empresa,
					¿tengo derecho a obtener un contrato indefinido?</a>
					<p>Por: <span class="for">Marco Antonio Zegarra</span></p>
					<p>Uno de los supuestos de desnaturalización de los contratos sujetos a modalidad – contenidos en la...</p>
					</li> onClick="ga('send', 'event', 'buscar_avisos','mas_puestos', 'mas_puestos');"
					<li>
					<a class="subtitle-blog" href="javascript:;">Asesor virtual: Si llevo mucho tiempo contratado temporalmente por una empresa,
					¿tengo derecho a obtener un contrato indefinido?</a>
					<p>Por: <span class="for">Marco Antonio Zegarra</span></p>
					<p>Uno de los supuestos de desnaturalización de los contratos sujetos a modalidad – contenidos en la...</p>
					</li>
					<li>
					<a class="subtitle-blog" href="javascript:;">Asesor virtual: Si llevo mucho tiempo contratado temporalmente por una empresa,
					¿tengo derecho a obtener un contrato indefinido?</a>
					<p>Por: <span class="for">Marco Antonio Zegarra</span></p>
					<p>Uno de los supuestos de desnaturalización de los contratos sujetos a modalidad – contenidos en la...</p>
					</li>
				</ul>
			</div>
		</div>
		*/?>

	 <!--Eliminar todo el div de abajo -->
	 <?php /*
	 <div class="centerMC" id="centerDashPos">
		  <div class="dashboardMC left">
				<h6 class="black-title small">Mis datos</h6>
				<div class="iDashMC r5B bLBlue">
					 <div class="all mB10 blockHeadCM">
						  <div class="imgPerfil left alignC">
								<img <?=
								($this->imgPhoto != '') ? (($this->ImgLadoMayor(ELEMENTS_ROOT_IMG . $this->imgPhoto))
									 == "width" ? "width='90'" : "height='90'") : "";
								?> alt="<?= $this->escape($this->nombres . " " . $this->apellidos); ?>" src="<?=
									 ($this->imgPhoto == '') ? $this->S('/images/profile-default.jpg') . '" width="90'
												: ELEMENTS_URL_IMG . $this->imgPhoto;
									 ?>"></div>
						  <div class="headPerfil right">
								<em class="emBlock namePerf mB5 bold f14 c6"><?= $this->escape($this->nombres . " " . $this->apellidos); ?></em>
								<div class="rank mB5" id="rank">
									 <span style="width:<?= $this->porcentaje ?>%" class="barRank"> </span>
								</div>
								<div class="bold porcentIMC"><span class="porcentLoad"><?= $this->porcentaje ?>%</span> del perfil completo</div>
								<div class="alignC">
									 <?
									 if ($this->porcentaje < 100) :
										  ?>
										  <em class="emBlock txtEnfasis f11">Incrementa posibilidades</em>
										  <a href="<?= $this->var->url->completacv ?>">Completa tu Perfil</a>
									 <? endif; ?>
								</div>
						  </div>
					 </div>
					 <?
					 if ($this->porcentaje < 100) {
						  ?>
						  <h6 class="titleIDMC">Tips para completar tu perfil</h6>
						  <ul class="listDMC all mB20">
								<?
								foreach ($this->incompletos as $x) {
									 ?>
									 <li class="itemDMC"><a href="<?=
										  ($x == $this->var->sug->subircv) ? $this->var->url->subircv
													 : (
												($x == $this->var->sug->experiencia) ? $this->var->url->experiencia
														  : (
													 ($x == $this->var->sug->estudios) ? $this->var->url->estudios
																: (
														  ($x == $this->var->sug->idiomas) ? $this->var->url->idiomas
																	 : (
																($x == $this->var->sug->programas)
																		  ? $this->var->url->programas
																		  : (
																	 ($x == $this->var->sug->presentacion)
																				? $this->var->url->presentacion
																				: (
																		  ($x == $this->var->sug->tuweb)
																					 ? $this->var->url->tuweb
																					 : (
																				($x == $this->var->sug->foto)
																						  ? $this->var->url->foto
																						  : "")))))))
										  ?>">
												<?= $x ?></a><span class="emBlock enumDMC alignR txtEnfasis right">+<?=
												($x == $this->var->sug->subircv) ? $this->var->peso->subircv
														  : (
													 ($x == $this->var->sug->experiencia) ? $this->var->peso->experiencia
																: (
														  ($x == $this->var->sug->estudios) ? $this->var->peso->estudios
																	 : (
																($x == $this->var->sug->idiomas)
																		  ? $this->var->peso->idiomas
																		  : (
																	 ($x == $this->var->sug->programas)
																				? $this->var->peso->programas
																				: (
																		  ($x == $this->var->sug->presentacion)
																					 ? $this->var->peso->presentacion
																					 : (
																				($x == $this->var->sug->tuweb)
																						  ? $this->var->peso->tuweb
																						  : (
																					 ($x == $this->var->sug->foto)
																								? $this->var->peso->foto
																								: "0")))))))
												?> %</span></li>
									 <? } ?>
						  </ul>
					 <? } else { ?>
						  <!--h6 class="titleIDMC">Tu perfil esta completo</h6-->
					 <? } ?>
					 <h6 class="titleIDMC">Tu perfil público</h6>
					 <ul class="listDMC">
						  <li class="itemDMC linkDMC lastItemDMC">
								<?
								$urlPP
									 = $this->url(array('slug' => $this->slug),
									 'perfil_publico', true);
								?>
								<a title="<?= SITE_URL ?><?= $urlPP ?>" class="tooltipApt" href="<?= $urlPP ?>" target="_blank">Tu perfil público</a>
						  </li>
					 </ul>
				</div>
		  </div>
		  <div class="dashboardMC middleMC left">
				<h6 class="black-title small">Mis postulaciones</h6>
				<div class="iDashMC r5B bLBlue">

					 <?
					 if (count($this->postulaciones) == 0) {
						  ?>
						  <h6 class="titleIDMC mTopMC">
								No tienes Postulaciones
						  </h6>
						  <ul class="listDMC heightDMC"></ul>
					 <? } else { ?>
						  <h6 class="titleIDMC">
								Estas son tus postulaciones
						  </h6>
						  <div class="infoDataPost">
								(<span class="numTotMsj"><?= $this->estadisticas[0] ?></span> mensajes)
								(<span class="numRespMsj"><?= $this->estadisticas[2] ?></span> por responder)
								(<span class="numNoReads"><?= $this->estadisticas[1] ?></span> no leídos)
						  </div>
						  <div class="limitScrollD">
								<ul class="listDMC heightDMC">
									 <?
									 foreach ($this->postulaciones as $item):
										  ?>
										  <?
										  $url
												= $this->url(array('slug' => $item['slugaviso'],
												'url_id' => $item['urlaviso']), 'aviso',
												true);
										  ?>
										  <li class="itemDMC linkDMC"><a href="<?= $url ?>"><?= $item["puesto"] ?></a> <span class="c6 emRel"><?=
													 $item["empresa"] != "" ? '(' . $item["empresa"] . ')'
																: ''
													 ?></span></li>
									 <? endforeach; ?>
								</ul>
						  </div>
						  <div class="asideDMC alignR all"><a href="/postulaciones">Ver más</a></div>
					 <? } ?>
				</div>

		  </div>
		  <div class="dashboardMC left">
				<h6 class="black-title small">Mis notificaciones</h6>
				<div class="iDashMC r5B bLBlue">
					 <?php
					 if ($this->verNotificacionesAnuncios == 1 && count($this->result)
						  != 0) {
						  ?>
						  <!-- h6 class="titleIDMC mTopMC">AquiEmpleos ha seleccionado empleos que te</h6-->
						  <div class="infoDataPost">
								<h6 class="titleIDMC titlePMP"> AquiEmpleos ha seleccionado empleos que te pueden interesar (de acuerdo a tu perfil).</h6>
						  </div>
						  <ul class="listDMC ">
								<?php
								foreach ($this->listaAnunciosSugeridos as $item) {
									 ?>
									 <li class="itemDMC">
										  <a href="<?=
										  $this->url(array(
												'slug' => $item['slug'], 'url_id' => $item['url_id']),
												'aviso', true);
										  ?>"><?= $item['puesto']; ?></a>
										  <span class="c6 emRel"><?=
												$item["empresa_rs"] != "" ? '(' . $item["empresa_rs"] . ')'
														  : ''
												?></span>
									 </li>
								<?php } ?>
						  </ul>
						  <div class="asideDMC alignR all">
								<a href="<?=
								$this->url(array(
									 'module' => 'postulante', 'controller' => 'mi-cuenta',
									 'action' => 'anuncios-sugeridos'), "default", true)
								?>">Ver más</a>
						  </div>
					 <?php } ?>
					 <?
					 if (count($this->notificaciones) > 0) {
						  ?>
						  <?php
						  if (count($this->result) == 0) {
								?>
								<h6 class="titleIDMC r5T">Tienes notificaciones</h6>
						  <?php } else { ?>
								<h6 class="titleIDMC r5T">Otras notificaciones</h6>
						  <?php } ?>
						  <div class="infoDataPost">
								<span class="cntNotifs">Total (<span class="numTotNotifs"><?= $this->notif_total ?></span>)</span>
								<span class="cntNumNotifs">No leidas (<span class="numRespNotifs"><?= $this->notif_no_leidas ?></span>)</span>
						  </div>
						  <ul class="listDMC heightDMC">
								<?
								foreach ($this->notificaciones as $n):
									 ?>
									 <li class="itemDMC linkDMC"><span class="c6 emRel"><?=
												$this->escape(substr($n['cuerpo'], 0, 64)) . '...'
												?></span></li>
								<? endforeach; ?>
						  </ul>
						  <div class="asideDMC alignR all"><a href="/notificaciones">Ver más</a></div>
					 <? } else { ?>
						  <?php
						  if (count($this->result) == 0) {
								?>
								<h6 class="titleIDMC mTopMC">No tienes notificaciones</h6>
								<ul class="listDMC heightDMC">
								</ul>
						  <?php } ?>
					 <? } ?>
				</div>
		  </div>
	 </div>
	 */?>
		<?php //}?>
</div>
