
<nav class="cont-menu row">
    <br>
</nav>
<div class="wrapper mB0">
    <div class="head-title row">
        <ul class="steps">
            <li>Tus<br> Datos<span></span></li>
            <li>Tu Perfil<br> Profesional<span></span></li>
            <li class="act"><br>¡Listo!<span></span></li>
        </ul>
        <div class="title-step">
            <div class="legend"> <a href="<?=SITE_URL?>">Inicio</a> » <span class="noLink">Paso3 - Listo!</span>
            </div>
            <h1>Actualiza tus datos</h1>
        </div>
    </div>
    <div class="message_update">
        <h2 class="welcome">¡Gracias por actualizar tu perfil profesional!</h2>
        <p class="text-medium">Ahora tendrás mejores oportunidades para que más empresas puedan contactar contigo.
        Recuerda postular a las ofertas que más se acerquen a tu perfil profesional</p>
        <p class="text-medium">Acabas de postular a <span class="title-big"><?=$this->puesto?></span>.<br><span>Puedes seguir postulando usando nuestros filtros de búsqueda</span></p>
    </div>

<?php if (!$this->validaPd) { ?>
<div class="blue_band register">
        <ul class="row">
            <li>Obtén el trabajo que buscas en el menor tiempo.<br>Destácate y mantente informado de tus procesos de selección</li>
            <li><a href="<?=SITE_URL.'/perfil-destacado'?>" class="btn btn-primary">Adquiere tu Perfil Destacado</a></li>
            <li class="box_man"></li>
        </ul>
    </div>
<?php } ?>
</div>
<div class="box-center mT20 row">
    <div class="grids-6">
        <div class="head-search small">
            <?=
            $this->partial('_partials/_home_search_box.phtml',
                array('form' => $this->form))
            ?>
        </div>
        <div class="row sections-lists" style="position:relative">
            <?=
            $this->partial('home/_filtro_area.phtml',
                array('groupAreas1' => $this->groupAreas1, 'groupAreas2' => $this->groupAreas2))
            ?>
            <?=
            $this->partial('home/_filtro_nivel.phtml',
                array('groupNivelPuesto1' => $this->groupNivelPuesto1,
                'groupNivelPuesto2' => $this->groupNivelPuesto2))
            ?>
            <?=
            $this->partial('home/_filtro_ubicacion.phtml',
                array('groupDistritos1' => $this->groupDistritos1, 'groupDistritos2' => $this->groupDistritos2))
            ?>
        </div>
    </div>
    <aside class="grids-300">
        <?=
        $this->partial('_partials/_avisos_relacionados.phtml',
            array('anunciosRelacionados' => $this->avisosrelacionados))
        ?>
    </aside>
</div>