<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="profile_wrapper">
  <div class="center_box"> 
    <div class="content_body profile_detail_wrapper">
      <?=Application_Model_Partials::getPerfilPorcentaje(); ?>    
       <?= $this->partial('mi-cuenta/_perfil-publico.phtml', array('postulante'=>$this->postulante,'slug' => $this->slug)) ?>
    </div>
    <aside><?php Application_Model_Partials::getAvisosSugeridos(); ?></aside>
  </div>
</section>