<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="profile_wrapper">
  <div class="center_box">
	 <div class="content_body profile_detail_wrapper">
		<?=Application_Model_Partials::getPerfilPorcentaje(); ?>
		<div class="skill_body">
		  <?=$this->form->hidToken->setAttribs(array('id'=>'hidToken'))->renderViewHelper();?>
		  <div class="skill_buttons row">
			 <?php /* <button class="btn btn_cuaternary">Importar CV</button> */ ?>
			 <?php
			 $href = "href='importar-datos/param1/mis-logros'";
			 if ($this->showImport) {
				  $href = 'javascript;';
			 } ?>
				<?php
				/*

			 <a <?=$href?> class="btn btn_import_linkedin"> <i class="icon icon_linkedin"> </i><span>Importar de Linkedin</span></a>

				 */
			 ?>
			 <h2 class="skill_category"><i class="icon icon_medal"></i>Logros</h2>
			 <button class="btn btn_white flt_right" id="btnAddSkill"  <?=(count($this->lislogros)>0) ? '':'disabled="disabled"'?>>Agregar Otro</button>
			 <a class="btn btn_print flt_right" target="_blank" title="Imprimir" href="<?=$this->url(array(
				  'module' => 'postulante',
				  'controller' => 'mi-cuenta',
				  'action' => 'pdf',
				  'slug' => $this->slug), "default", true)?>">
				  <i class="icon icon_print"></i></a>
		  </div>
		  <?php if (count($this->lislogros)>0) {?>
		  <ul class="title_content_edit">
			 <?php foreach ($this->lislogros as $value ) {  ?>
			 <li>
				<div class="title_skills row">
				  <div class="block_text">
					 <h2><?=$value['txtPrize']?></h3>
					 <h3 class="item1">Emitido por <i><?=$value['txtInstitution']?></i></h3>
					 <p> <i href="#" class="icon icon_clock2"></i> <?=$value['txtMonth'];?> <?=$value['txtDateAchievement']?></p>
				  </div>
				  <div class="block_buttons">

					 <button class="btn btn_delete" data-id="<?=$value['id_logros']?>">
						<span class="btn_label"><i class="icon icon_delete2"></i></span>
						<span class="btn_spinner"></span>
					 </button>
					 <button class="btn btn_edit" data-id="<?=$value['id_logros']?>">
						<span class="btn_label"><i class="icon icon_pencil"></i></span>
						<span class="btn_spinner"></span>
					 </button>
				  </div>
				</div>
			 </li>
			 <?php  } ?>
		  </ul>
		  <?php }else{ ?>
			 <?=$this->partial('mi-cuenta/_logros.phtml', array('form' => $this->form, 'noneSkill' => true));?>
			 <ul class="title_content_edit hide"></ul>
		  <?php } ?>
		</div>
	 </div>
	 <aside><?php Application_Model_Partials::getAvisosSugeridos(); ?></aside>
  </div>
</section>

<script id="tplUserAchievements" type="text/template">
	 <?=$this->partial('mi-cuenta/_logros.phtml', array('form' => $this->form, 'noneSkill' => true));?>
</script>
<script id="tplSkillTitle" type="text/template">
  <div class="block_text">
	 <h2><%=txtPrize%></h3>
	 <h3 class="item1">Emitido por <i><%=txtInstitution%></i></h3>
	 <p> <i href="#" class="icon icon_clock2"></i> <%=txtMonth%> <%=txtDateAchievement%></p>
  </div>
  <div class="block_buttons">
	 <button class="btn btn_delete" data-id="<%=hidAchievements%>">
		<span class="btn_label"><i class="icon icon_delete2"></i></span>
		<span class="btn_spinner"></span>
	 </button>
	 <button class="btn btn_edit" data-id="<%=hidAchievements%>">
		<span class="btn_label"><i class="icon icon_pencil"></i></span>
		<span class="btn_spinner"></span>
	 </button>
  </div>
</script>
<script id="tplSkillBox" type="text/template">
  <li>
	 <div class="title_skills row">
		<% include tplSkillTitle %>
	 </div>
  </li>
</script>
