<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="profile_wrapper">
  <div class="center_box"> 
    <div class="content_body profile_detail_wrapper">
      <?=Application_Model_Partials::getPerfilPorcentaje(); ?>
      <?//=$this->formPostulante->hidToken->setAttribs(array('id'=>'hidToken'))->renderViewHelper();?> 
      <?php
      /*
      <div class="mt20 align_right">
        <button class="btn btn_secondary" id="btnAddSkill">Agregar Hobbie</button>
      </div>
      */
      ?>
      <form id="frmUserHobbies" autocomplete="off" class="type1 mt20" action="">
        <div class="form_box border_grey">
          <div class="form_row">
            <div class="form_col12 hobbies_mini_form">
              <fieldset>
                <label>Hobbie</label>
                <input type="text" name="txtHobbies" id="txtHobbies" placeholder="Ingresa tus hobbies o pasatiempos" class="input_control"/>
              </fieldset>
            </div>
            <div class="form_col12 step3_skills_selected_container">

              <?php foreach($this->hobbies as $item) : ?>
                <div class="step3_skills_selected_item" data-value="<?=$item['nombre']?>" data-id="<?=$item['id']?>">
                <label><?=$item['nombre']?></label>
                <span class="close_skills hobbies">X</span>
                <input type="hidden" value="<?=$item['id']?>" name="aptitudes[]">
              </div>
              <?php endforeach; ?>

            </div>
          </div>
          <div class="form_row buttons_row">
            <button class="btn btn_save mt20 mb20">
              <span class="btn_label">Guardar</span>
              <span class="btn_spinner"></span>
            </button>
            <?php /*<button class="btn btn_cancel mt20 mb20" type="button">Cancelar</button>*/ ?>
          </div>
          <input id="hidHobbies" name="hidHobbies" type="hidden" value="0">
        </div>
      </form>
    </div>
    <aside>
      <?php Application_Model_Partials::getAvisosSugeridos(); ?>
    </aside>
  </div>
</section>
<?php
/*
<script id="tplUserHobbies" type="text/template">
	
</script>
<script id="tplSkillTitle" type="text/template">
    <h2><%=title1%></h2>
    <h3 class="item1">Nivel Escrito <i>(<%=title2%>)</i></h3>
    <h3 class="item2">Nivel Oral <i>(<%=title3%>)</i></h3>
</script>
<script id="tplSkillBox" type="text/template">
  <li>
    <div class="title_skills row">
      <div class="block_text">
        <% include tplSkillTitle %>
      </div>
      <div class="block_buttons">
        <button class="btn btn_edit" data-id="<%=id%>">
          <span class="btn_label"><i class="icon icon_pencil"></i></span>
          <span class="btn_spinner"></span>
        </button>
        <button class="btn btn_delete" data-id="<%=id%>">
          <span class="btn_label"><i class="icon icon_delete2"></i></span>
          <span class="btn_spinner"></span>
        </button>
      </div>
    </div>
  </li>
</script>
*/ 
?>

<script type='text/template' id="tplItemSkill">
  <div class='<%= classItem %>' data-value="<%= value %>" data-id="<%= id %>">
    <label><%= value %></label>
    <span class='<%= classClose %> hobbies'>X</span>
    <% if(id==''){ %>
      <input type="hidden" value="<%= value %>" name="aptitudes[]">
    <% }else{ %>
      <input type="hidden" value="<%= id %>" name="aptitudes[]">
    <% } %>
  </div>
</script>