<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="profile_wrapper">
  <div class="center_box">
	 <div class="content_body profile_detail_wrapper">
		<?=Application_Model_Partials::getPerfilPorcentaje(); ?>
		<div class="skill_body">
		  <?=$this->formOtroEstudio->hidToken->setAttribs(array('id' => 'hidToken'))->renderViewHelper();?>
		  <div class="skill_buttons row">
			 <h2 class="skill_category"><i class="icon icon_books"></i>Otros Estudios</h2>
			 <button class="btn btn_white flt_right" id="btnAddSkill" <?=(count($this->lisOtrosEstudios)>0) ? '':'disabled="disabled"'?>>Agregar Otro</button>
			 <a class="btn btn_print flt_right" target="_blank" title="Imprimir" href="<?=$this->url(array(
					 'module' => 'postulante',
					 'controller' => 'mi-cuenta',
					 'action' => 'pdf',
					 'slug' => $this->slug), "default", true)?>">
					 <i class="icon icon_print"></i></a>
		  </div>
		  <?php if (count($this->lisOtrosEstudios)>0) : ?>
			 <ul class="title_content_edit">
				<?php foreach ($this->lisOtrosEstudios as $value ) {  ?>
				<li>
				  <div class="title_skills row">
					 <div class="block_text">
						<h2><?=$value['otro_estudio']?></h2>
						 <h3 class="item2"><?=$value['nombre']?></h3>
						 <h3 class="item2"><i>
						  <?=App_Util::setMonth($value['inicio_mes'])?> <?=$value['inicio_ano']?> -
						  <?=($value['fin_mes']===NULL && $value['fin_ano']===NULL)?
									 'Actualmente Estudiando':
									 App_Util::setMonth($value['fin_mes']) .' '.$value['fin_ano'];
						  ?> </i>
						</h3>
					 </div>
					 <div class="block_buttons">
						<button class="btn btn_delete" data-id="<?=$value['id_estudio']?>">
						  <span class="btn_label"><i class="icon icon_delete2"></i></span>
						  <span class="btn_spinner"></span>
						</button>
						<button class="btn btn_edit" data-id="<?=$value['id_estudio']?>">
						  <span class="btn_label"><i class="icon icon_pencil"></i></span>
						  <span class="btn_spinner"></span>
						</button>
					 </div>
				  </div>
				</li>
				<?php  } ?>
			 </ul>
		  <?php else :  ?>
			 <?=$this->partial('mi-cuenta/_otros_estudios.phtml', array('formOtroEstudio' => $this->formOtroEstudio, 'noneSkill' => true));?>
			 <ul class="title_content_edit hide"></ul>
		  <?php endif; ?>
		</div>
	 </div>
	 <aside><?php echo Application_Model_Partials::getAvisosSugeridos(); ?></aside>
  </div>
</section>

<script id="tplOthersStudies" type="text/template">
	 <?=$this->partial('mi-cuenta/_otros_estudios.phtml', array('formOtroEstudio' => $this->formOtroEstudio, 'noneSkill' => true));?>
</script>

<script id="tplSkillTitle" type="text/template">
  <div class="block_text">
	 <h2><%=txtOtherName%></h2>
	 <h3><%=txtOtherInstitution%></h3>
	 <h3><%=selOtherMonthBegins%> <%=txtOtherYearBegins%> - <%if(actuallyStudying == 1 ){%>Actualmente Estudiando<%}else{%><%=selOtherMonthEnd%> <%=txtOtherYearEnd%><%}%></h3>
  </div>
  <div class="block_buttons">
	 <button class="btn btn_delete" data-id="<%=hidOtherStudy%>">
		<span class="btn_label"><i class="icon icon_delete2"></i></span>
		<span class="btn_spinner"></span>
	 </button>
	 <button class="btn btn_edit" data-id="<%=hidOtherStudy%>">
		<span class="btn_label"><i class="icon icon_pencil"></i></span>
		<span class="btn_spinner"></span>
	 </button>
  </div>
</script>

<script id="tplSkillBox" type="text/template">
  <li>
	 <div class="title_skills row">
		<% include tplSkillTitle %>
	 </div>
  </li>
</script>
