<?=Application_Model_Partials::getMenuPostulante(); ?>

<?= $this->partial('_partials/_new_messages.phtml', array("flashMessages" => $this->flashMessages)); ?>
<section class="profile_wrapper">

    <div class="center_box">
        <div class="content_body profile_detail_wrapper">
            <?= Application_Model_Partials::getPerfilPorcentaje(); ?>
            <div class="skill_body">
                <div class="skill_buttons row">
                    <?php /* <button class="btn btn_cuaternary">Importar CV</button> */ ?>

                    <h2 class="skill_category"><i class="icon icon_person2"></i>Datos Personales</h2>
                    <?php /* if ($this->showImport) : ?>
                      <a href='/mi-cuenta/importar-datos/param1/mis-datos-personales' class="btn btn_import_linkedin flt_right"> <i class="icon icon_linkedin"> </i><span>Importar</span></a>
                      <?php endif; */ ?>
                    <a class="btn btn_print flt_right" target="_blank" href="<?=
                    $this->url(array(
                        'module' => 'postulante', 'controller' => 'mi-cuenta',
                        'action' => 'pdf',
                        'slug' => $this->slug), "default", true)
                    ?>">
                        <i class="icon icon_print"></i></a>
                </div>
                <?=
                $this->partial('mi-cuenta/_datos_personales.phtml', array('formPostulante' => $this->formPostulante,
                    'imgPhoto' => $this->imgPhoto));
                ?>
            </div>
        </div>
        <aside><?php echo Application_Model_Partials::getAvisosSugeridos(); ?></aside>
    </div>
</section>
