<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="profile_wrapper">
  <div class="center_box">
	 <div class="content_body profile_detail_wrapper">
		<?=Application_Model_Partials::getPerfilPorcentaje(); ?>
		<div class="skill_body">
		  <?=$this->formPrograma->hidToken->setAttribs(array('id'=>'hidToken'))->renderViewHelper();?>
		  <div class="skill_buttons row">
			 <h2 class="skill_category"><i class="icon icon_mouse"></i>Informática</h2>
			 <?php  /*if ($this->showImport) : ?>
				<a href='/mi-cuenta/importar-datos/param1/mis-programas' class="btn btn_import_linkedin"> <i class="icon icon_linkedin"> </i><span>Importar de Linkedin</span></a>
			 <?php endif;*/  ?>
			 <button class="btn btn_white flt_right" id="btnAddSkill" <?=(count($this->itemProgramas)>0) ? '':'disabled="disabled"'?> >Agregar Otro</button>
			 <a class="btn btn_print flt_right" title="Imprimir" target="_blank" href="<?=$this->url(array(
				  'module' => 'postulante',
				  'controller' => 'mi-cuenta',
				  'action' => 'pdf',
				  'slug' => $this->slug), "default", true)?>">
				  <i class="icon icon_print"></i></a>
		  </div>
		  <?php if (count($this->itemProgramas)>0) : ?>
			 <ul class="title_content_edit">
				<?php foreach ($this->itemProgramas as $value ) :  ?>
				<li>
				  <div class="title_skills row">
					 <div class="block_text">
						<h2><?=$value['nombre']?></h3>
						<h3 class="item1">Nivel <i>(<?=$value['nivel']?>)</i></h3>
					 </div>
					 <div class="block_buttons">
						<button class="btn btn_delete" data-id="<?=$value['id_dominioComputo']?>">
						  <span class="btn_label"><i class="icon icon_delete2"></i></span>
						  <span class="btn_spinner"></span>
						</button>
						<button class="btn btn_edit" data-id="<?=$value['id_dominioComputo']?>">
						  <span class="btn_label"><i class="icon icon_pencil"></i></span>
						  <span class="btn_spinner"></span>
						</button>
					 </div>
				  </div>
				</li>
				<?php endforeach; ?>
			 </ul>
		  <?php else :  ?>
			 <?=$this->partial('mi-cuenta/_programas.phtml', array('formPrograma' => $this->formPrograma, 'noneSkill' => true));?>
			 <ul class="title_content_edit hide"></ul>
		  <?php endif; ?>
		</div>
	 </div>
	 <aside><?php Application_Model_Partials::getAvisosSugeridos(); ?></aside>
  </div>
</section>

<script id="tplUserPrograms" type="text/template">
	 <?=$this->partial('mi-cuenta/_programas.phtml', array('formPrograma' => $this->formPrograma, 'noneSkill' => true));?>  
</script>
<script id="tplSkillTitle" type="text/template">
  <div class="block_text">
	 <h2><%=txtProgram%></h2>
	 <h3 class="item1">Nivel <i>(<%=selLevel%>)</i></h3>
  </div>
  <div class="block_buttons">
	 <button class="btn btn_delete" data-id="<%=hidPrograms%>">
		<span class="btn_label"><i class="icon icon_delete2"></i></span>
		<span class="btn_spinner"></span>
	 </button>
	 <button class="btn btn_edit" data-id="<%=hidPrograms%>">
		<span class="btn_label"><i class="icon icon_pencil"></i></span>
		<span class="btn_spinner"></span>
	 </button>
  </div>
</script>
<script id="tplSkillBox" type="text/template">
  <li>
	 <div class="title_skills row">
		<% include tplSkillTitle %>
	 </div>
  </li>
</script>
