<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta charset="UTF-8">
        <style type="text/css">
            body{
                font-family: scfly;
                box-sizing: border-box;
            }
            .container{
                max-width: 1170px;
                padding-right: 15px;
                padding-left: 15px;
                margin-right: auto;
                margin-left: auto;
                font-family: scfly;
            }
            .container:after, .container:before, .row:after, .row:before{
                display: table;
                content: " ";
            }
            .row {
                margin-right: 0 !important;
                margin-left: 0 !important;
                padding: 0.5em 0;
            }
            .row:before{
                display: table;
                content: " ";
            }
            table {
                border-collapse: collapse;
/*                border: 1px solid black;
*/            }

            .col-md-12{
                width: 100%;
                position: relative;
                min-height: 1px;
                padding-right: 15px;
                padding-left: 15px;
            }
            .col-md-4{
                width: 33.33333333333333%;
                float: left;
            }
            .col-md-8{
                width: 66.66666666666666%;
                float: left;
            }
            
            .contenedor-mi-perfilCV{
                padding-top: 1em; color: #555;
            }
            .foto-CV{
                width: 160px;
                border:1px solid black;
                margin-right: 1em;
                padding:0.5em 4em;
                text-align: center;
            }
            .dato-CV{
                display: block;
                line-height: 1.5em;
            }
            .name{
                font-weight: bold;
                font-size: 20px;
                color: black;
            }
            .mail{
                color: #2A5E9A;
            }
            .font-black{
                color: black;
                font-size: 18px;
            }
            .font-yellow{
                color:#e4a300;

            }
            .box-title-datoCV{
                background: #2A5E9A;
                color: white;
                width: 100%;
                padding: 0.5em 1em;
            }
            .box-title-datoCV span{
                font-size: 18px;
            }
            .box-pd{
                padding: 0.5em 1em;
            }

        </style>
    </head>
    <body>
        <div class="container contenedor-mi-perfilCV">
            <section class="row">
                <table>
                    <tr>

                    <?php //var_dump($this->postulante); die();?>
                        <td rowspan="6" class="foto-CV">
                            <?php $_fot = $this->postulante['postulante']['fotovariable']; ?>
                            <img src="<?php echo (!empty($_fot))? ELEMENTS_URL_IMG . $_fot : $this->S('/images/profile-default.jpg') ?>">
                        </td>
                        <td></td>
                        <td> <?= $this->postulante['postulante']['nombres'] ?> <?= $this->postulante['postulante']['apellidos'] ?></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><?= $this->Edad($this->postulante['postulante']['fecha_nac']) ?> años - 
                        <?= $this->postulante['postulante']['sexoMF'] == 'M' ? ucfirst($this->postulante['postulante']['estado_civil']) : ucfirst(substr($this->postulante['postulante']['estado_civil'], 0, $leng - 1) . 'a')
                        ?>
                        <?//= $this->postulante['postulante']['estado_civil'] ?>
                        </td>
                    </tr>
                    <tr>
                        <td></td>                    
                        <td>
                        <?= strtoupper($this->postulante['postulante']['tipo_doc']) ?>
                        <?= $this->postulante['postulante']['num_doc'] ?>                        
                        </td>
                    </tr>
                    <tr>
                        <td></td>                        
                        <td>C: <?= $this->postulante['postulante']['celular'] ?></td>
                    </tr>
                    <tr>
                        <td></td>                        
                        <td><?= $this->postulante['postulante']['email'] ?></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>                    
                        <td></td>
                    </tr>
                </table>
                <div class="contenedor-ubicacion row">
                    <div class="box-title-datoCV">
                        <span class="title-ubicacion">Ubicación</span>
                    </div>
                    <div class="box-dato-ubicaion box-pd">
                        <span class="pais dato-CV"><?= $this->postulante['postulante']['ubicacion'] ?></span>
                        <span class="distrito dato-CV"></span>
                        <span class="disponibilida dato-CV"><?= ($this->postulante['postulante']['extranjero'] == 1) ? ' Tengo disponibilidad para trabajar en provicia/extranjero' : ''; ?></span>
                    </div>
                </div>
                <div class="contenedor-experiencia row">
                    <?php if (count($this->postulante['experiencias']) > 0): ?>

                    <div class="box-title-datoCV">
                        <span class="title-experiencia">Experiencia</span>
                    </div>

                    <?php foreach ($this->postulante['experiencias'] as $i => $item): ?>

                        <div class="box-datos-experiencia box-pd">
                            <span class="cargo font-black dato-CV"><?php echo $this->escape($item['puesto']); ?></span>
                            <span class="empresa font-yellow dato-CV"><?php echo $this->escape($item['empresa']); ?> (<?php echo $this->escape($item['rubro']); ?>)</span>
                            <span class="fecha-trabajo dato-CV">
                                <?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?>
                             - <?= $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano']; ?>
                             </span>
                            <span class="tareas dato-CV">Descripcion de tareas:</span>
                            <span class="descrpcion-tareas dato-CV">
                                <?php echo $this->escape($item['comentarios']); ?>
                            </span>
                        </div>
                    <? endforeach ?>
                    <? endif ?>

                </div>
                <div class="contenedor-estudios row">
                    <?php if (count($this->postulante['estudios']) > 0): ?>

                    <div class="box-title-datoCV">
                        <span>Estudios</span>
                    </div>

                    <?php foreach ($this->postulante['estudios'] as $i => $item): ?>

                        <?php if ($item['id_nivel_estudio'] != 1): ?>
                        <div class="box-dato-estudios box-pd">
                            <span class="font-black dato-CV">
                            <?php if ($item['id_nivel_estudio'] == 3 || $item['id_nivel_estudio'] == 2) : ?>
                                <?php echo $this->escape($item['nivel_nombre']); ?>
                            <?php else : ?>
                                <?php echo $this->escape($item['titulo']); ?> (<?php echo $this->escape($item['nivel_nombre'].' '.$item['nivel_tipo_nombre']); ?>)
                            <?php endif; ?>
                            </span>
                            <span class="font-yellow dato-CV">
                            <?php
                                if ($item['id_nivel_estudio'] != 3 || $item['id_nivel_estudio'] != 2) {
                                    echo $item['institucion'];
                                } else { 
                                    echo $item['otro_institucion'];
                                }
                            ?>                            
                            </span>
                            <span class=" dato-CV">
                                <?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?> - 
                                <?= $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano'];
                                ?>                                
                            </span>
                            <span class=" dato-CV"></span>
                        </div>
                        <?php endif ?>                        
                    <? endforeach ?>
                    <? endif ?>
                    
                </div>
                <div class="contenedor-otros-estudios row">
                    <?php if (count($this->postulante['otrosEstudios']) > 0): ?>                    
                    <div class="box-title-datoCV">
                        <span>Otros Estudios</span>
                    </div>
                    
                    <?php foreach ($this->postulante['otrosEstudios'] as $i => $item): ?>
                    
                        <div class="box-dato-otros-estudios box-pd">
                            <span class="font-black dato-CV">
                            <?php echo $this->escape($item['titulo']); ?> (<?php echo $this->escape($item['nivel_tipo_nombre']); ?>)
                            </span>
                            <span class="font-yellow dato-CV"><?= $item['institucion'] ?></span>
                            <span class=" dato-CV">
                            <?= Application_Model_Mes::$lista[$item['inicio_mes']] . " " . $item['inicio_ano'] ?> - <?= $item['actualmente'] == '1' ? ' (Actualmente)' : Application_Model_Mes::$lista[$item['fin_mes']] . " " . $item['fin_ano']; ?>
                            </span>
                            <span class=" dato-CV"></span>
                        </div>
                    <?php endforeach ?>
                    <?php endif ?>
                </div>
                <div class="contenedor-idiomas row">
                    <?php if (count($this->postulante['idiomas']) > 0): ?>
                    <div class="box-title-datoCV">
                        <span>Idiomas</span>
                    </div>

                    <?php foreach ($this->postulante['idiomas'] as $i => $item): ?>
                        <div class="box-dato-idiomas box-pd">
                            <span class="font-black dato-CV">
                                <?= ucwords(mb_strtolower(($item['nombreIdioma']), "utf8"))?>
                            </span>
                            <span class=" dato-CV"><?= $item['selLevelWritten'] ?></span>
                        </div>
                    <?php endforeach ?>
                    <?php endif ?>
                    
                </div>
                <div class="contenedor-informatica row">
                    <?php if (count($this->postulante['programas']) > 0): ?>
                    <div class="box-title-datoCV">
                        <span>Informatica</span>
                    </div>

                    <?php foreach ($this->postulante['programas'] as $i => $item): ?>

                        <div class="box-dato-informatica box-pd">
                            <span class="nombre-programa font-black dato-CV">
                                <?= ucwords(mb_strtolower($item['programa'])) ?>
                            </span>
                            <span class="nivel-escrito dato-CV"><?= $item['nivel'] ?></span>
                        </div>
                    <?php endforeach ?>
                    <?php endif ?>
                </div>
                <div class="contenedor-referencias row">
                    <?php if (count($this->postulante['referencias']) > 0): ?>

                    <div class="box-title-datoCV">
                        <span>Referencias</span>
                    </div>

                    <?php foreach ($this->postulante['referencias'] as $i => $item): ?>

                        <div class="box-dato-referencia box-pd">
                            <span class="font-black dato-CV"></span>
                            <span class="dato-CV"></span>                            
                            <span class="dato-CV font-yellow">
                            <?php echo $this->escape($item['nombre']); ?>
                            </span>
                            <span class="dato-CV"><?php echo $this->escape($item['cargo']); ?></span>
                            <span class="dato-CV"><?php echo $this->escape($item['telefono']); ?></span>
                            <span class="dato-CV"><?php echo $this->escape($item['telefono2']); ?></span>
                            <span class="dato-CV"><?php echo $this->escape($item['email']); ?></span>
                        </div>
                    <?php endforeach ?>
                    <?php endif ?>
                </div>
                <div class="contenedor-logros row">
                    <?php if (count($this->postulante['logros']) > 0): ?>

                    <div class="box-title-datoCV">
                        <span>Logros</span>
                    </div>
                    <?php foreach ($this->postulante['logros'] as $i => $item): ?>

                    <div class="box-dato-logros box-pd">
                        <span class="font-black dato-CV"><?php echo $this->escape($item['logro']); ?> - <?php echo $this->escape($item['ano']); ?></span>
                        <span class=" dato-CV"><?php echo $this->escape($item['institucion']); ?></span>
                        <span class=" dato-CV"><?php echo $this->escape($item['descripcion']); ?></span>
                    </div>
                    <?php endforeach ?>
                    <?php endif ?>
            </div>
        </section>
</div>

    </body>
</html>