<div class="configuration_wrapper">
    <?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages))?>    
    <div class="center_box">
        <?= $this->partial('mi-cuenta/_sidebar-menu_mi_cuenta_datos.phtml', array('menu_sel_side' => $this->menu_sel_side)) ?>          
        <div class="content_wrapper"><span class="title_content">Privacidad</span>            
          <div class="information">
            <?=
            $this->partial('_partials/_privacidad_mi_cuenta.phtml', 
                    'postulante', array(
                        'privacidadPostulante' => $this->privacidadPostulante
                    )
            );
            ?> 
          </div>            
        </div>
    </div>
</div>