<div class="control-group">
	<label for="txtNombres" class="control-label"><em>*</em> Nombres:</label>
	<div class="controls">
		<?=$this->formAdministrador->nombres->setAttribs(array('id'=>'txtNombres','class'=>'input-xmedium','required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-minlength'=>'2', 'data-parsley-maxlength'=>'80', 'data-parsley-pattern'=>'/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöüÄËÏÖÜ ]+$/gi'))->renderViewHelper(); ?>

		<?php if ($this->formAdministrador->nombres->hasErrors()): ?>
        <div class="has-error">
            <span id="" class="help-block">
            <?php foreach ($this->formAdministrador->nombres->getMessages() as $error): ?>
                <small><?php echo $error ?></small> <br>            
            <?php endforeach ?>
            </span>
        </div>
        <?php endif ?>
	</div>
</div>
<div class="control-group">
	<label for="txtApellidos" class="control-label"><em>*</em> Apellido:</label>
	<div class="controls">
		<?=
		$this->formAdministrador->apellidos->setAttribs(array(
			'id' => 'txtApellidos', 'class' => 'input-xmedium', 'required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-minlength'=>'2', 'data-parsley-maxlength'=>'50', 'maxlength'=>50, 'data-parsley-pattern'=>'/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöüÄËÏÖÜ ]+$/gi'))->renderViewHelper();
		?>

		<?php if ($this->formAdministrador->apellidos->hasErrors()): ?>
        <div class="has-error">
            <span id="" class="help-block">
            <?php foreach ($this->formAdministrador->apellidos->getMessages() as $error): ?>
                <small><?php echo $error ?></small> <br>            
            <?php endforeach ?>
            </span>
        </div>
        <?php endif ?>
	</div>
</div>
<div class="control-group">
	<label for="txtPuesto" class="control-label no-req"><em> </em> Puesto:</label>
	<div class="controls">
		<?=
		$this->formAdministrador->puesto->setAttribs(array(
			'id' => 'txtPuesto', 'class' => 'input-xmedium', 'data-parsley-trigger'=>'change', 'data-parsley-pattern'=>'/^[a-z0-9-ñáéíóúÑÁÉÍÓÚäëïöüÄËÏÖÜ ]+$/gi'))->renderViewHelper();
		?>
	</div>
</div>
<div class="control-group">
	<label for="txtArea" class="control-label no-req"><em> </em> Área:</label>
	<div class="controls">
		<?=
		$this->formAdministrador->area->setAttribs(array(
			'id' => 'txtArea', 'class' => 'input-xmedium', 'data-parsley-trigger'=>'change', 'data-parsley-pattern'=>'/^[a-z-ñáéíóúÑÁÉÍÓÚäëïöüÄËÏÖÜ ]+$/gi'))->renderViewHelper();
		?>
	</div>
</div>
<?php echo $this->formAdministrador->csrf_token->renderViewHelper(); ?>
<div class="cgroup-inline">
	<label class="control-label"><em>*</em> Teléfono fijo/celular:</label>
	<div class="control-group parsley_message_bottom w180">
	    <?=$this->formAdministrador->telefono->setAttribs(array('id'=>'fTlfAmin1','class'=>'input-xmiddle number', 'placeholder' => 'Ingrese entre 8-14 Dígitos', 'required'=>'', 'data-parsley-trigger'=>'change','data-parsley-minlength'=>'8', 'data-parsley-maxlength'=>'14'))->renderViewHelper(); ?>
    </div>
    <div class="control-group last">
    	<label class="no-req">Anexo:</label>
	    <?=$this->formAdministrador->anexo->setAttribs(array('id'=>'fAnexo1','class'=>'input-xsmall number'))->renderViewHelper(); ?>
    </div>
</div>

<div class="cgroup-inline">
    <label class="control-label no-req">Teléfono fijo/celular:</label>
	<div class="control-group parsley_message_bottom w180">	                         
		<?=$this->formAdministrador->telefono2->setAttribs(array('id'=>'fTlfAmin2','class'=>'input-xmiddle number', 'placeholder' => 'Ingrese entre 8-14 Dígitos', 'data-parsley-minlength'=>'8', 'data-parsley-maxlength'=>'14'))->renderViewHelper(); ?>
    </div>
    <div class="control-group last">
		<label class="no-req">Anexo:</label>
		<?=$this->formAdministrador->anexo2->setAttribs(array('id'=>'fAnexo2','class'=>'input-xsmall number'))->renderViewHelper(); ?>
    </div>                    
</div>
<?php echo $this->formAdministrador->csrf_token->renderViewHelper(); ?>