<style>
    #wrapper{
        margin-top: 2em;
    }
    .sin-margin{
        margin-right: 0;
        margin-left: 0;
    }
    .frm-horizontal .control-label em,.req{
        color:#b94a4a;
    }
    .input-xmedium,.input-xmiddle,.input-xsmall{
        padding: 15px !important;
    }
    .btn-salir{
        background: #2a5e9b;
        text-shadow: none;
        color: white;
        border: none;
        border-radius: 0;
    }
    .btn-continuar{
        background: #FFA200;
        text-shadow: none;
        color: white;
        border: none;
        border-radius: 0;
    }
    .hideDiv {
        display: none;
    }
    .page_default{
        margin-top: 4em;
    }
    .message{
        background: rgba(255, 0, 0, 0.33);
        border: 1px solid #c30d0d;
        padding: 1em;
        border-radius: 5px;
        margin-left: 11em;
        width: 73%;
    }
    .icon {
        margin-right: 0.5em;
    }
</style>
    <?= $this->partial('_partials/_new_messages.phtml', 'postulante', array("flashMessages" => $this->flashMessages)); ?>

<div id="wrapper" class="width-control">
    <div class="legend"><a href="/empresa/">Inicio</a> » <span class="noLink">Registro de Empresa</span></div>

    <div class="row sin-margin">
        <p class="right">Los campos con <span class="req">*</span> son necesarios</p>
        <h2 class="title-big">Datos de la empresa</h2>
    </div>
    <form action="" method="post" id="frmCompanyRegistration" enctype="multipart/form-data" class="frm-horizontal large">
        <div class="wrap-controls">
            <?=
            $this->partial('registro-empresa/_usuario_paso1.phtml', array(
                'formUsuario' => $this->frmUsuario,
                'emailMicuenta' => $this->emailMicuenta,
                'controlador' => $this->controlador,
                'modulo' => $this->modulo,
                'controlador' => $this->controlador
                    )
            );
            ?>
            <?=
            $this->partial('registro-empresa/_empresa_paso1.phtml', array(
                'formEmpresa' => $this->frmEmpresa,
                'imgPhoto' => $this->imgPhoto,
                'config' => $this->config,
                'idEmpresa' => $this->idEmpresa,
                'numPalabraRazonComercial' => $this->numPalabraRazonComercial,
                'numPalabraRazonSocial' => $this->numPalabraRazonSocial
                    )
            );
            ?>
        </div>
        <h2>Ubicación</h2>
        <div class="wrap-controls">
<?=
$this->partial('registro-empresa/_ubigeoEmpresa_paso1.phtml', array(
    'formEmpresa' => $this->frmEmpresa));
?>
        </div>
        <h2>Administrador</h2>
        <div class="wrap-controls">
<?=
$this->partial('registro-empresa/_administrador_paso1.phtml', array(
    'formAdministrador' => $this->frmAdministrador,
    'idEmpresa' => $this->idEmpresa));
?>
        </div>
        <div class="row">
            <div class="grids-7 parsley_message_bottom">
                <label class="ioption m0"><input id="chkPolitics" type="checkbox" value="politics" name="politics" checked="checked" required>Entiendo y Acepto las <a target="" href="#">Políticas de Privacidad de aquiempleos.com</a></label>
            </div>
            <div class="grids-2 txt_right">
                <a href="#escapeForm" class="btn btn-salir btn-default winModal">Salir</a>
                <button type="submit" id="btnCompanyRegister" class="btn btn-continuar btn-primary">Continuar &gt;</button>
            </div>
        </div>
    </form>
</div>
