<nav class="cont-menu row"><br></nav>
<div id="wrapper" class="row">
	 <div class="legend"> <a href="/empresa/">Inicio</a> » <span class="noLink">Registro de Empresa</span> </div>
	 <div class="gridIFormEmp">
		  <div id="innerMain" class="center">
				<div id="content" class="formRegister">
					 <div id="formReg">
						  <h2 class="imgBgEmp"><span class="hide">AquiEmpleos Empresa</span></h2>
						  <div class="fieldsetE" id="endRegisterEmp">
								<div id="txtP3Emp" class="grid18 center">
									 <p class="pNone alignC f38 bold">¡Enhorabuena! ¡Ahora forma parte de AquiEmpleos!</p>
									 <p class="pNone f18 alignC">El portal número 1 de Perú, donde los peruanos buscan y<br/>encuentran más empleo.</p>
									 <p class="pLupaEmp">Ya puede publicar sus avisos y disfrutar <br/>de los beneficios de AquiEmpleos.</p>
								</div>
						  </div>
						  <div id="btnsEndRegE" class="wrap-btn center">
								<a id="btnsEndRegELef" class="btn btn-default btn-xsmall" href="<?=
								$this->url(array(
									 'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
									 "default", true)
								?>">Ir a mi cuenta</a>
								<a id="btnsEndRegERig" class="btn btn-primary btn-xsmall" href="<?=
								$this->url(array(
									 'module' => 'empresa', 'controller' => 'publica-aviso',
									 'action' => 'index'), "default", true)
								?>">Publica tu aviso</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
</div>
