<?php
$logo = ($this->auth['empresa']['logo2']=='') ? $this->S('/images/icon-empresa-blank.png') :ELEMENTS_URL_LOGOS . $this->auth['empresa']['logo2'];
?>

<div class="contenedor_publica_Aviso">
    <div class="row text-aviso">
    <?php if($this->compra['medioPago'] == 'pf'): ?>
        Hola <?php echo $this->compra['nombreContacto'] ?>, estás a punto de publicar tu aviso <span class="name-aviso"><?php echo $this->compra['anuncioPuesto'] ?>.</span>
        Sólo deberás de realizar el pago con el cógigo <span class="cogigo-publico"><?php echo $this->compra['compraId'] ?></span> en los canales de pago que tiene PuntoFácil

    <?php elseif($this->compra['medioPago'] == 'pv'): ?>
        Hola <?php echo $this->compra['nombreContacto'] ?>, estás a punto de publicar tu aviso <span class="name-aviso"><?php echo $this->compra['anuncioPuesto'] ?>.</span>
        Sólo deberás de realizar el pago con el cógigo <span class="cogigo-publico"><?php echo $this->compra['compraId'] ?></span> en los canales de pago de La Prensa
    <?php else: ?>
        Felicitaciones <?php echo $this->compra['nombreContacto'] ?>, has publicado tu aviso <span class="name-aviso"><?php echo $this->compra['anuncioPuesto'] ?>.</span>
    <?php endif; ?>

    </div>
    <div class="row">
        <table>
            <tr>
                <td rowspan="4" class="contenedor-img">
                    <div class="img-aviso">
                        <img src="<?php echo $logo ?>" alt="">
                    </div>
                </td>
                <td class="bgr-perla">
                    <span>Tipo de Aviso Web:</span>
                </td>
                <td class="bgr-perla">
                    <span><?php echo ($this->compra['medioPago'] == 'gratuito') ? 'Gratuito' : $this->tipoAviso ?></span>
                </td>
            </tr>

            <tr class="bgr-perla">
              <td>
                  <span>Vigencia Web:</span>
              </td>
              <td>
                  <span><?php echo ($this->compra['medioPago'] == 'gratuito') ? '180' : $this->compra['beneficios']['ndiaspub']['valor'] ?> días</span>
              </td>
            </tr>
            <tr class="bgr-perla">
            <?php //anuncioImpresoId ?>
              <td>
                  <span>Tipo de Aviso impreso:</span>
              </td>
              <td>
                  <span><?php echo $this->compra['producto'] ?></span>
              </td>
            </tr>
            <tr class="bgr-perla">
            <!--
                <td>
                    <span>F.Pub.Impreso:</span>
                </td>
                <td>
                    <span>180 días</span>
                </td>
            -->
            </tr>
        </table>
    </div>
    <div class="row contenedor-icon-social">
        <ul>
            <li class="social-icon">
                <a href="https://www.facebook.com/aquiempleos" target="_black"><i class="fa fa-facebook" aria-hidden="true"></i></a>
            </li>
            <li class="social-icon">
                <a href="https://twitter.com/aquiempleos" target="_black"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </li>
        </ul>
    </div>
    <div class="row btn-aviso-satisfactorio">
        <ul>
            <li>
                <a class="btn_ver_proceso" href="<?php echo $this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'index'),"default",true)?>">Ir a mis procesos</a>
            </li>
            <li>
                <a class="btn_otro_aviso" href="<?php echo SITE_URL ?>/empresa/publica-aviso/paso1">Publicar otro aviso</a>
            </li>
        </ul>
    </div>
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>

    <div class="gridIStepEmp" class="all">
        <?php //var_dump($this->tipoContrato); exit;   ?>
        <?=
        $this->partial('_partials/_pago_satisfactorio.phtml',
            array('aw' => $this->compra, 'tipoContrato' => $this->tipoContrato, 'saldoFinal' => $this->saldoFinal,
            'rol' => $this->auth["usuario"]->rol,'moneda'=>$this->moneda,'promo'=>$this->promo,'promoMsg'=>$this->promoMsg))
        ?>
    </div>
</div>
