
<style type="text/css">
  @font-face{
    font-family:"iconFonts";
    src:url(<?=MEDIA_URL?>/main/fonts/iconFonts/iconFonts-webfont.eot);
    src:url(<?=MEDIA_URL?>/main/fonts/iconFonts/iconFonts-webfont.eot?#iefix) format("embedded-opentype"),
    url(<?=MEDIA_URL?>/main/fonts/iconFonts/iconFonts-webfont.woff) format("woff"),
    url(<?=MEDIA_URL?>/main/fonts/iconFonts/iconFonts-webfont.ttf) format("truetype"),
    url(<?=MEDIA_URL?>/main/fonts/iconFonts/iconFonts-webfont.svg#iconFonts) format("svg");
    font-style:normal;
    font-weight:400;
  }
  @font-face{
    font-family:"museo300";
    src:url(<?=MEDIA_URL?>/main/fonts/museo300/museo300-webfont.eot);
    src:url(<?=MEDIA_URL?>/main/fonts/museo300/museo300-webfont.eot?#iefix) format("embedded-opentype"),
    url(<?=MEDIA_URL?>/main/fonts/museo300/museo300-webfont.woff) format("woff"),
    url(<?=MEDIA_URL?>/main/fonts/museo300/museo300-webfont.ttf) format("truetype"),
    url(<?=MEDIA_URL?>/main/fonts/museo300/museo300-webfont.svg#museo300) format("svg");
    font-style:normal;
    font-weight:400
  }
  @font-face{
    font-family:"museo500";
    src:url(<?=MEDIA_URL?>/main/fonts/museo500/museo500-webfont.eot);
    src:url(<?=MEDIA_URL?>/main/fonts/museo500/museo500-webfont.eot?#iefix) format("embedded-opentype"),
    url(<?=MEDIA_URL?>/main/fonts/museo500/museo500-webfont.woff) format("woff"),
    url(<?=MEDIA_URL?>/main/fonts/museo500/museo500-webfont.ttf) format("truetype"),
    url(<?=MEDIA_URL?>/main/fonts/museo500/museo500-webfont.svg#museo500) format("svg");
    font-style:normal;
    font-weight:400
  }
  @font-face{
    font-family:museoSans;
    src:url(<?=MEDIA_URL?>/main/fonts/museoSans/museoSans-webfont.eot);
    src:url(<?=MEDIA_URL?>/main/fonts/museoSans/museoSans-webfont.eot?#iefix) format("embedded-opentype"),
    url(<?=MEDIA_URL?>/main/fonts/museoSans/museoSans-webfont.woff) format("woff"),
    url(<?=MEDIA_URL?>/main/fonts/museoSans/museoSans-webfont.ttf) format("truetype"),
    url(<?=MEDIA_URL?>/main/fonts/museoSans/museoSans-webfont.svg#museoSans) format("svg");
    font-style:normal;
    font-weight:400
  }
</style>