<h3 class="titleAPLR">Editar </h3>
<form method="post" class="all formFieldAdm hide" id="formFieldEditarApi" msg-error="<?= $this->error ?>" action="<?= $this->url(array('module'=>'admin','controller'=>'api','action'=>'editar-usuario-ajax'),'default',true) ?>">
    <div class="block">
        <label for="fDomain" class="labelN"> Dominio web de la empresa: </label>
        <?=$this->formAgregarUsuario->domain->setAttribs(array('id'=>'fDomain','class'=>'inputN left', 'maxlength' => '75'))->renderViewHelper(); ?>
        <?$hasError = $this->formAgregarUsuario->domain->hasErrors(); ?>
        <span class="response cGray left<?= $hasError?' bad':''?>"><?= $hasError? $this->formAgregarUsuario->domain->errMsg:''?></span>
    </div>
    <div class="block">
        <label for="fCheckDomainApi" class="labelN">Conexión restringida: </label>
        <div class="left clearBApi">
            <?=$this->formAgregarUsuario->force_domain->setAttribs(array('id'=>'fCheckDomainApi1','class'=>'left'))->renderViewHelper(); ?>
            <span class="response cGray left">Se permitirá el acceso sólo desde las direcciones IP de la empresa.</span>
        </div>
    </div>
    <div class="block">
        <label for="estado" class="labelN">Estado: </label>
        <div class="left clearBApi">
            <?=$this->formAgregarUsuario->estado->setAttribs(array('id'=>'estado','class'=>'left'))->renderViewHelper(); ?>
        </div>
        <span class="response cGray left"></span>
    </div>
    <div class="block">
        <label for="fInicioApi" class="labelN"> Fecha de Inicio: </label>
        <div class="left clearBApi">
        <?=$this->formAgregarUsuario->fecha_ini->setAttribs(array('id'=>'fInicioApi','class'=>'inputFecha left'))->renderViewHelper(); ?>
        </div>
        <?$hasError = $this->formAgregarUsuario->fecha_ini->hasErrors(); ?>
        <span class="response cGray left<?= $hasError?' bad':''?>"><?= $hasError? $this->formAgregarUsuario->fecha_ini->errMsg:''?></span>
    </div>
    <div class="block">
        <label for="fFinApi" class="labelN"> Fecha de Fin: </label>
        <div class="left clearBApi">
        <?=$this->formAgregarUsuario->fecha_fin->setAttribs(array('id'=>'fFinApi','class'=>'inputFecha left', 'readonly' => 'readonly'))->renderViewHelper(); ?>
        </div>
        <?$hasError = $this->formAgregarUsuario->fecha_fin->hasErrors(); ?>
        <span class="response cGray left<?= $hasError?' bad':''?>"><?= $hasError? $this->formAgregarUsuario->fecha_fin->errMsg:''?></span>
    </div>
    <?=$this->formAgregarUsuario->idUsuApi ?>
    <?=$this->formAgregarUsuario->usuario_id ?>
     <div class="all" id="cntOptSaveApi">
        <input id="saveUserAPI"  type="submit" class="active btnSptAdm sptAdm" value="">
     </div>
    <input name="tok" type="hidden" value="<?=CSRF_HASH?>"/>
</form>
