<?php if ($this->module == 'postulante') : ?>
	 <?php
	 $urlAviso = SITE_URL . $this->url(array(
				'slug' => $this->aviso["slug"],
				'empresaslug' => App_Util::validateSlugEmpresa($this->aviso["empresaslug"],$this->aviso['mostrar_empresa']),
				'ubicacionslug' => $this->aviso["ubicacionslug"],
				'url_id' => $this->aviso["url_id"],
				),
				'aviso_detalle', true);
	 ?>
<?php endif; ?>

<div class="box-content">
  <div class="row">
    <div class="col-md-7">
      <p class="content">

      <?php //print_r($this->aviso); die(); ?>
      <?php echo nl2br($this->escape($this->aviso['funciones'])); ?>
      </p>
      <hr>
      <div class="box-content-sub">
        <small><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $this->escape($this->aviso['fecha']); ?>
        <div class="row">
          <div class="col-md-8">
            <table>
              <tr>
                <td>Ciudad:</td>
                <td class="td-class"><?php echo $this->escape($this->aviso['ciudad']); ?></td>
              </tr>

              <tr>
                <td>Área:</td>
                <td class="td-class"><?php echo $this->escape($this->aviso['area_puesto']); ?></td>
              </tr>

              <tr>
                <td>Remuneración:</td>
                <td class="td-class">
                	<?php if ($this->aviso['mostrar_salario'] == 1 && !($this->aviso['salario_min'] == null && $this->aviso['salario_max'] == null)) : ?>
	                	<?php if ($this->aviso['salario_min'] == 0) : ?>
									  Menor a <?php echo $this->moneda?> <?= $this->aviso['salario_max']; ?>
									  <?php elseif ($this->aviso['salario_max'] == '') : ?>
									  Mayor a <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?>
									  <?php elseif ($this->aviso['salario_min'] != $this->aviso['salario_max']) : ?>
									  Entre <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?> y <?php echo $this->moneda?> <?= $this->aviso['salario_max']; ?>
									  <?php else : ?>
									  <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?>
									  <?php endif; ?>
									<?php endif; ?>
                </td>
              </tr>
            </table>
          </div>
          <div class="col-md-4">
            <table>
              <tr>
              	<td></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-5">
    	<?php
				 $fixClass = "";
				 if ($this->aviso['mostrar_empresa'] != "0" && ($this->aviso['logo_empresa'] != "" || $this->aviso['logo_empresa'] != null)) {
					  ?>
				 <?php if (isset($this->aviso['slug_empresa'])) { ?>
				<a href='<?=$this->url(array('pais'=>'peru','empresa'=>$this->aviso['slug_empresa']),'buscar',false);?>' title="<?= $this->escape($this->aviso['nombre_empresa']) ?>">
					 <img alt="<?= $this->escape($this->aviso['nombre_empresa']) ?>" src="<?= ELEMENTS_URL_LOGOS . $this->aviso['logo_empresa'] ?>" title="<?= $this->escape($this->aviso['nombre_empresa']) ?>" width="200"></a>
					  <?php } else { ?>
				<a title="<?= $this->escape($this->aviso['nombre_empresa']) ?>">
					 <img alt="<?= $this->escape($this->aviso['nombre_empresa']) ?>" src="<?= ELEMENTS_URL_LOGOS . $this->aviso['logo_empresa'] ?>" title="<?= $this->escape($this->aviso['nombre_empresa']) ?>" width="200">
				</a>
					  <?php } ?>
				 <?php } else { ?>
				<a title="<?= $this->escape($this->aviso['nombre_empresa']) ?>">
					 <img alt="<?= $this->escape($this->aviso['nombre_empresa']) ?>" src="<?= $this->S('/images/' . $this->LogoDefecto) ?>" title="<?= $this->escape($this->aviso['nombre_empresa']) ?>" width="200">
				</a>
				 <?php }?>
    </div>
  </div>
  <hr>
  <div class="description">
    <p class="description-title">La Empresa</p>
    <p class="description-content">
    	<?php
				 if ($this->aviso['mostrar_empresa'] != 0) {
				 if (isset($this->aviso['slug_empresa'])) { ?>
					  <a href='<?=$this->url(array('pais'=>'peru','empresa'=>$this->aviso['slug_empresa']),'buscar',false);?>' target="_blank" title="<?= $this->escape($this->aviso['nombre_empresa']); ?>"><?= $this->escape($this->aviso['nombre_empresa']); ?></a>
				 <?php } else { ?>
					  <h2><?= $this->escape($this->aviso['nombre_empresa']); ?></h2>
				 <?php }
				 ?>
			<?php } else { ?>
				 <h2><?= $this->escape($this->aviso['nombre_comercial']); ?></h2>
			<?php } ?>
    </p>
    <!--<p class="description-content">Dirección de la empresa ??</p>-->
    <!--<p class="description-content">Página Web de la empresa ??</p>-->
    <hr>
    <div class="box-yellow">
    	<a href="javascript:;" title="Comparte por Linkedin" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_linkedin');">
      	<span class="fa fa-linkedin rsocial" aria-hidden="true"></span>
      </a>
      <a href="javascript:;" title="Comparte en Twitter" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_twitter');">
      	<span class="fa fa-twitter rsocial" aria-hidden="true"></span>
      </a>
      <a href="javascript:;" title="Comparte en Facebook" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_facebookr');">
      	<span class="fa fa-facebook rsocial" aria-hidden="true"></span>
      </a>

      <div class="box-right">
        <a href="<?=$this->url(array('pais'=>'peru','empresa'=>$this->aviso['slug_empresa']),'buscar',false);?>"><span class="buttom-gray-w">Avisos de la empresa</span></a>

        <?php if ($this->AnuncioHelper($this->aviso)->showBtnPostular()) : ?>
			  <?php if ($this->isAuth === false ||(isset( $this->auth['usuario']) && $this->auth['usuario']->rol === 'postulante')) : ?>
					<?php if ($this->hasPostulado === false && ($this->hasDesPostulado === false)) : ?>
						 <?php if ($this->cuestionario === true) : ?>
							  <?php
									$urlPostula = '#questionsWM';
									$winModal = 'show_questions';

//									if ($this->updateCV) :
//										 $urlPostula = '#winUpdateCV';
//										 $winModal = 'trigger_modal_not_enough_information';
//									endif;
									if($this->auth == null) :
										 $winModal = 'login_init';
									endif;
							  ?>
							  <a class="btn_apply_job <?= $winModal?>"
									  href="<?= $this->urlAviso ?>/postular" title="Postula"
									  data-trigger-modal="<?=$urlPostula?>"
									  ><span class="buttom-blue-w">Postular</span></a>

							 <?php else : ?>
							 <?php

										 $resParams = $this->searchResultsUrl == '' ? '' : '/es-resultado/true';
										  $urlPostula = 'javascript:;';
										  $winModal = '';
										 if ($this->auth == null) :
											  $urlPostula = 'javascript:;';
											  $winModal = 'login_init';
										 else : //update CV
											  if ($this->updateCV) :
													//$urlPostula = '#winUpdateCV';
													//$winModal = 'trigger_modal_not_enough_information';
											  else :
													$urlPostula =  $this->urlAviso. '/postular' . $resParams;
													$winModal = 'winModal';
											  endif;
										  endif;   ?>
										 <a class="btn_apply_job"
											  href="<?= (empty($winModal)) ? $this->urlAviso. '/postular' : $urlPostula; ?>"
											  data-href="<?= ($this->auth == null) ? $this->urlAviso . '/postular' . $resParams : $this->urlAviso ?>"
												 data-trigger-modal="<?=$urlPostula?>"
											  title="Postula"><span class="buttom-blue-w">Postular</span></a>
							 <?php endif; ?>
						<?php endif; ?>
				  <?php endif; ?>
				<?php endif; ?>
      </div>
    </div>
    <hr>
  </div>
  <div class="sobre-aviso">



    <p>Requisitos</p>
    <ul><?php
		  if (count($this->aviso['estudios']) > 0) : ?>
		  <?php
		  foreach ($this->aviso['estudios'] as $a) :
				if($a['nivel_estudio']=='Otros Estudios') :
				?><li  itemprop="educationRequirements">
					 <?php
					 if ($a['nivel_estudio_tipo']=='Otros') : ?>
					 <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio']) ?>
					 <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].': '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ': ' . $this->escape($a['carrera']): '')?>.
					 <?php else : ?>
					 <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio'].': '.$a['nivel_estudio_tipo']) ?>
					 <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].': '.$a['nivel_estudio_tipo'].' en '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ' en ' . $this->escape($a['carrera']): '')?>.
					 <?php endif; ?>
				</li>
				<?php else : ?>
				<li  itemprop="educationRequirements">
					 <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio'].' '.$a['nivel_estudio_tipo']) ?>
					 <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].' '.$a['nivel_estudio_tipo'].' en '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ' en ' . $this->escape($a['carrera']): '')?>.
				</li>
				<?php endif; ?>
				<?php endforeach; ?>
	 	<?php endif; ?>
	 	<?php if (count($this->aviso['experiencias']) > 0) : ?>
		  <?php foreach ($this->aviso['experiencias'] as $e) : ?>
				<li itemprop="experienceRequirements">Experiencia:
					 <?= $this->escape($e['nombre_puesto']) ?> en el área de <?= $this->escape($e['nombre_area']) ?><?=
					 ($this->Meses($e['experiencia'])) ? ' con ' . $this->Meses($e['experiencia']) . ' de experiencia.'
								: '.'
					 ?>
				</li>
		  <?php endforeach; ?>
	 	<?php endif; ?>
	 	<?php if (count($this->aviso['idiomas']) > 0) : ?>
		  <?php foreach ($this->aviso['idiomas'] as $i) : ?>
				<li itemprop="skills">Idioma
					 <?=
					 $this->escape($this->ItemList('idioma', $i['idioma']))
					 ?> a nivel <?=
					 $this->escape($i['nivel_idioma'] == 'basico' ? 'básico'
									 : $i['nivel_idioma'])
					 ?>
				</li>
		  <?php endforeach; ?>
	 	<?php endif; ?>
	 	<?php if (count($this->aviso['programas']) > 0): ?>
		  <li itemprop="skills">Manejo de programas:
				<?php
				for ($i
				= 0; $i < count($this->aviso['programas']); $i++):
					 ?>
					 <?= $this->escape($this->aviso['programas'][$i]['nombre_programa']) ?> a nivel <?=
					 $this->escape($this->aviso['programas'][$i]['nivel_programa']
						  == 'basico' ? 'básico' : $this->aviso['programas'][$i]['nivel_programa'])
					 ?><?=
					 ($i + 1 == count($this->aviso['programas'])) ? '.' : ', '
					 ?>
				<?php endfor; ?>
		  </li>
	 	<?php endif; ?>
		</ul>


  </div>
  <div class="text-center">
  	<br>
  	<?php if ($this->AnuncioHelper($this->aviso)->showBtnPostular()) : ?>
		  <?php if ($this->isAuth === false ||(isset( $this->auth['usuario']) && $this->auth['usuario']->rol === 'postulante')) : ?>
				<?php if ($this->hasPostulado === false && ($this->hasDesPostulado === false)) : ?>
					 <?php if ($this->cuestionario === true) : ?>
						  <?php
								$urlPostula = '#questionsWM';
								$winModal = 'show_questions';

//								if ($this->updateCV) :
//									 $urlPostula = '#winUpdateCV';
//									 $winModal = 'trigger_modal_not_enough_information';
//								endif;
								if($this->auth == null) :
									 $winModal = 'login_init';
								endif;
						  ?>
						  <a class="btn_apply_job <?= $winModal?>"
								  href="<?= $this->urlAviso ?>/postular" title="Postula"
								  data-trigger-modal="<?=$urlPostula?>"
								  >
								  	<span class="buttom-blue-w change">Postular</span>
								  </a>

						 <?php else : ?>
						 <?php

									 $resParams = $this->searchResultsUrl == '' ? '' : '/es-resultado/true';
									  $urlPostula = 'javascript:;';
									  $winModal = '';
									 if ($this->auth == null) :
										  $urlPostula = 'javascript:;';
										  $winModal = 'login_init';
									 else : //update CV
										  if ($this->updateCV) :
//												$urlPostula = '#winUpdateCV';
//												$winModal = 'trigger_modal_not_enough_information';
										  else :
												$urlPostula =  $this->urlAviso. '/postular' . $resParams;
												$winModal = 'winModal';
										  endif;
									  endif;   ?>
									 <a class="btn_apply_job"
										  href="<?= (empty($winModal)) ? $this->urlAviso. '/postular' : $urlPostula; ?>"
										  data-href="<?= ($this->auth == null) ? $this->urlAviso . '/postular' . $resParams : $this->urlAviso ?>"
											 data-trigger-modal="<?=$urlPostula?>"
										  title="Postula"><span class="buttom-blue-w change">Postular</span></a>
						 <?php endif; ?>
					<?php endif; ?>
			  <?php endif; ?>
			<?php endif; ?>
			<!--
    <div class="boton-postular">
      <div class="buttom-blue-w change">Postular</div>
    </div>
-->
      <div class="rs">
        <a href="javascript:;" title="Comparte por Linkedin" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_linkedin');">
        	<span class="fa fa-linkedin rsocial move" aria-hidden="true"></span>
        </a>
        <a href="javascript:;" title="Comparte en Twitter" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_twitter');">
        	<span class="fa fa-twitter rsocial move" aria-hidden="true"></span>
        </a>
        <a href="javascript:;" title="Comparte en Facebook" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_facebookr');">
        	<span class="fa fa-facebook rsocial move" aria-hidden="true"></span>
        </a>
      </div>

  </div>
</div>
