<?php if ($this->AnuncioHelper($this->aviso)->showContent()) : ?>    
  <div class="job_box_wrapper">
      <h3 class="job_box_title">Descripción del Puesto</h3>
      <div class="job_box_information" itemprop="description">
          <?= nl2br($this->escape($this->aviso['funciones'])); ?>
      </div>
  </div>    
  <?php if (!empty($this->aviso['responsabilidades'])) :?>
  <div class="job_box_wrapper">
      <h3 class="job_box_title">Otros</h3>
      <div class="job_box_information">
          <?= nl2br($this->escape($this->aviso['responsabilidades'])); ?>
      </div>
  </div>
  <?php endif;?>
  <?php if (count($this->aviso['programas']) > 0 || count($this->aviso['idiomas']) > 0 || count($this->aviso['experiencias']) > 0 || count($this->aviso['estudios']) > 0) : ?>
      <div class="job_box_wrapper">
          <h3 class="job_box_title">Requisitos</h3>
          <div class="job_box_information">                                    
              <ul><?php if (count($this->aviso['estudios']) > 0) : ?>
              <?php foreach ($this->aviso['estudios'] as $a) :?>
                <?php if($a['nivel_estudio']=='Otros Estudios') :
                  ?><li  itemprop="educationRequirements">
                      <?php                             
                      if ($a['nivel_estudio_tipo']=='Otros') : ?>
                      <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio']) ?>
                      <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].': '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ': ' . $this->escape($a['carrera']): '')?>.
                      <?php else : ?>
                      <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio'].': '.$a['nivel_estudio_tipo']) ?>
                      <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].': '.$a['nivel_estudio_tipo'].' en '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ' en ' . $this->escape($a['carrera']): '')?>.
                      <?php endif; ?>
                  </li>                        
                  <?php else : ?>
                  <li  itemprop="educationRequirements">
                      <?= ($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?'':$this->escape($a['nivel_estudio'].' '.$a['nivel_estudio_tipo']) ?>
                      <?=($a['otra_carrera'] != '' || $a['otra_carrera'] !=NULL)?$a['nivel_estudio'].' '.$a['nivel_estudio_tipo'].' en '.$this->escape($a['otra_carrera']):(($a['carrera'] != '') ? ' en ' . $this->escape($a['carrera']): '')?>.
                  </li>
                  <?php endif; ?>
                  <?php endforeach; ?>
          <?php endif; ?>
          <?php if (count($this->aviso['experiencias']) > 0) : ?>
              <?php foreach ($this->aviso['experiencias'] as $e) : ?>
                  <li itemprop="experienceRequirements">Experiencia: 
                      <?= $this->escape($e['nombre_puesto']) ?> en el área de <?= $this->escape($e['nombre_area']) ?><?=
                      ($this->Meses($e['experiencia'])) ? ' con ' . $this->Meses($e['experiencia']) . ' de experiencia.'
                              : '.'
                      ?>
                  </li>
              <?php endforeach; ?>
          <?php endif; ?>
          <?php if (count($this->aviso['idiomas']) > 0) : ?>
              <?php foreach ($this->aviso['idiomas'] as $i) : ?>
                  <li itemprop="skills">Idioma 
                      <?=$this->escape($this->ItemList('idioma', $i['idioma'])) ?> a nivel <?=$this->escape($i['nivel_idioma'] == 'basico' ? 'básico' : $i['nivel_idioma']) ?>
                  </li>
              <?php endforeach; ?>
          <?php endif; ?>
          <?php if (count($this->aviso['programas']) > 0): ?>
              <li itemprop="skills">Manejo de programas: 
                  <?php  for ($i = 0; $i < count($this->aviso['programas']); $i++): ?>
                      <?= $this->escape($this->aviso['programas'][$i]['nombre_programa']) ?> a nivel <?= $this->escape($this->aviso['programas'][$i]['nivel_programa'] == 'basico' ? 'básico' : $this->aviso['programas'][$i]['nivel_programa'])?><?=($i + 1 == count($this->aviso['programas'])) ? '.' : ', '?>
                  <?php endfor; ?>
              </li>
          <?php endif; ?>
              </ul>
          </div>
      </div>    
  <?php endif; ?>
  <?php if ($this->aviso['mostrar_salario'] == 1 && !($this->aviso['salario_min'] == null && $this->aviso['salario_max'] == null)) : ?>
      <h3 class="job_box_title">Condiciones Salariales</h3>
      <div class="job_box_information">
          <ul>
              <?php if ($this->aviso['salario_min'] == 0) : ?>
              <li>Sueldo: Menor a <?php echo $this->moneda?> <?= $this->aviso['salario_max']; ?></li>
              <?php elseif ($this->aviso['salario_max'] == '') : ?>
              <li>Sueldo: Mayor a <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?></li>
              <?php elseif ($this->aviso['salario_min'] != $this->aviso['salario_max']) : ?>
              <li>Sueldo: Entre <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?> y <?php echo $this->moneda?> <?= $this->aviso['salario_max']; ?></li>
              <?php else : ?>
              <li>Sueldo: <?php echo $this->moneda?> <?= $this->aviso['salario_min']; ?></li>
              <?php endif; ?>
          </ul>
      </div>
  <?php endif; ?>
<?php  endif; ?>   
<?php if ($this->module == 'postulante') : ?>
  <div class="job_options_wrapper">         
      <div class="button_container">
      <?php if ($this->AnuncioHelper($this->aviso)->showBtnPostular()) : ?> 
          <?php if ($this->postular): ?>
                   <a class="btn btn_apply_job bg_secondary <?= $this->postular['winModal']?>" 
                        onClick="ga('send', 'event', 'postulacion','oferta_trabajo','<?= $this->postular['area_puesto_slug'] ?>_<?= $this->postular['nivel_puesto_slug'] ?>_<?= $this->postular['url_id'] ?>_<?=$postular['postulante']?>');"
                        href="<?=$this->postular['urlPostula']  ?>" 
                        data-href="<?=$this->postular['urlPostula']  ?>" title="Postula"
                        data-trigger-modal="<?=$this->postular['modalPostular'];?>" 
                        ><span>Postula</span></a>
            <?php  endif; ?>
       <?php endif;  ?>           
      </div>
  </div>
  <?php if ($this->lookAndFeel) :?>
  <div class="job_share">
    <div data-email="<?=$this->ulrDestino;?>" data-url="<?=$this->ulrDestino;?>" data-title="<?= $this->aviso['puesto']; ?>" class="job_options_share"><span>Comparte este aviso</span>
          <ul>
            <li><a class="btn_share_social mail" title="Comparte por email" href="javascript:;" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_email');" ><i class="icon icon_email color_primary border_primary"></i></a></li>              
            <li><a class="btn_share_social fb" title="Comparte en Facebook" href="javascript:;" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_facebook');"><i class="icon icon_facebook color_primary border_primary"></i></a></li>
            <li><a class="btn_share_social twitter" title="Comparte en Twitter" href="javascript:;" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_twitter');"><i class="icon icon_twitter color_primary border_primary"></i></a></li>
            <li><a class="btn_share_social linkedin" title="Comparte por Linkedin" href="javscript:;" onClick="ga('send','event','Avisos de Empleo','oferta_trabajo','compartir_<?=$this->aviso["url_id"];?>_<?=$this->postulante;?>_linkedin');"><i class="icon icon_linkedin color_primary border_primary"></i></a></li>
          </ul>
      </div>
  </div>
  <?php endif; ?>     
<?php endif; ?>
<?php if ($this->LookAndFeelColors['mostrar_mapa']) :?>          
<div class="map_location">
    <div class="map_location_button">
        <button id="btnGetMap">Dar click para activar</button>
    </div>
    <div id="mapCanvas" class="map" data-color="<?=$this->LookAndFeelColors['background']?>" data-latitud="<?=$this->LookAndFeelColors['latitud']?>"   data-longitud="<?=$this->LookAndFeelColors['longitud']?>"></div>
</div>
<?php endif; ?>     
