<div class="row smb">
    <div class="col-xs-8 col-sm-8  col-md-8  separate-ficha-aviso spb">
        <i class="fa fa-clock-o text-gray-small-icon" aria-hidden="true"></i>
        <span class="text-gray-small">Hace</span>
        <span class="text-gray-small"><?= $this->Hace($this->aviso['fh_pub']) ?></span>
        <div class="row smb">
            <div class="col-md-8 spb">
                
                <div class="col-xs-4 col-sm-3 col-md-4 spb text-label">Ciudad: </div>
                <div class="col-xs-8 col-sm-9 col-md-8 spb text-label-content"><?= $this->aviso['ubigeo_nombre'] ?></div>
                <div class="col-xs-4 col-sm-3 col-md-4 spb text-label">Área:</div>
                <div class="col-xs-8 col-sm-9 col-md-8 spb text-label-content"><?= $this->aviso['area_puesto'] ?></div>
                <div class="col-xs-4 col-sm-3 col-md-4 spb text-label">Empresa:</div>
                <div class="">
                <h2 class = "col-xs-8 col-sm-9 col-md-8 spb text-label-content cuadro">
                    <?= $this->aviso['empresa_rs'] ?>
                </h2>
                </div>
            </div>
        
        </div>
    </div>
    <div class="col-xs-4 col-sm-4 col-md-4 spb contenedor-img-cell-center">
        <div class="contenedor-table-cell-2">
            <div class="img-table-cell">
                <img src="<?= $this->E()->getElementLogos($this->aviso['logo_empresa']); ?>" class="img-center-cell" alt="<?= $this->aviso['empresa_rs'] ?>" >
            </div>
        </div> 
    </div>
</div>
    
    

