<h1><?= $this->LuceneCast($this->aviso['puesto']); ?></h1>
<h2><?= $this->LuceneCast($this->escape($this->aviso['nombre_empresa'])); ?></h2>
<h3><?= $this->LuceneCast($this->escape($this->aviso['ciudad'])); ?></h3>
<p><?= nl2br($this->LuceneCast($this->escape($this->aviso['funciones']))); ?></p>
<p><?= nl2br($this->LuceneCast($this->escape($this->aviso['responsabilidades']))); ?></p>
<ul>
    <? if (count($this->aviso['estudios'])): ?>
        <? foreach ($this->aviso['estudios'] as $a) : ?>
            <li><?= mb_strtolower($this->escape($a['nivel_estudio'])) ?> <?= mb_strtolower($this->escape($a['carrera'])) ?></li>
        <? endforeach; ?>
    <? endif; ?>
    <? if (count($this->aviso['experiencias'])): ?>
        <? foreach ($this->aviso['experiencias'] as $e) : ?>
            <li><?= mb_strtolower($this->escape($e['nombre_puesto'])) ?> <?= mb_strtolower($this->escape($e['nombre_area'])) ?></li>
        <? endforeach; ?>
    <? endif; ?>
    <? if (count($this->aviso['idiomas'])): ?>
        <? foreach ($this->aviso['idiomas'] as $i): ?>
            <li>
                <?= mb_strtolower($this->escape($this->ItemList('idioma', $i['idioma']))) ?>
                <?//=$this->escape($i['nivel_idioma']) ?>
            </li>
        <? endforeach; ?>
    <? endif; ?>
    <? if (count($this->aviso['programas'])): ?>
        <? foreach ($this->aviso['programas'] as $k => $i): ?>
            <li>
                <?= mb_strtolower($this->escape($this->aviso['programas'][$k]['nombre_programa'])) ?>
                <?//=$this->escape($this->aviso['programas'][$k]['nivel_programa']) ?>
            </li>
        <? endforeach; ?>
    <? endif; ?>
</ul>