<div class="bgAll gridS20">
	 <ul id="navigation" class="gridS20">
		  <li class="home itemNav first"><a class="btnH linkNav" href="./index.html">Inicio</a></li>
		  <li class="jobPost itemNav itemActive"><a class="btnJ linkNav" href="#">Avisos de Empleo</a></li>
		  <li class="account itemNav"><a class="btnA linkNav" href="#">Mi Cuenta</a></li>
		  <li class="whatis itemNav last"><a class="btnW linkNav" href="#">¿ Que es AquiEmpleos ?</a></li>
	 </ul>
	 <div id="innerMain" class="grid20 center">
		  <div class="legend history"><a href="./aviso.empleo.html">Inicio</a> » <span class="noLink">Avisos de empleo</span></div>
		  <div class="blockPost msgPJob mB10">
				<p class="f18 mB10 legendJ">Has postulado satisfactoriamente a:</p>
				<div class="msgIJob all rel"> <a href="#" class="logoEntry left"><img src="<?=$this->S('/images/logoKotear.jpg');?>" alt="Kotear"/></a> <a href="#" class="r2" id="goAccount">Ir a mi cuenta</a>
					 <div class="dataEntry left">
						  <h2 class="jobEntryM"><a class="linkJobE" href="#">Diseñador gráfico web</a></h2>
						  <h3 class="nameEntry">Corporación wong</h3>
					 </div>
				</div>
		  </div>
		  <div id="content" class="grid13 rel left alpha">
				<div class="bgMDTIE">
					 <div class="modFind bLBlue r10">
						  <div class="bgImageF rel">
								<form id="formFind" action="./busqueda.resultado.html">
									 <h2 class="titleFind">Encuentra tu próximo Trabajo</h2>
									 <fieldset id="nAdvance" class="field mB5">
										  <input id="fieldSearch" class="cGray mB10 fieldSch placeH" type="text" alt="Busca por puesto, ubicaci&oacute;n, empresa, etc" value="Busca por puesto, ubicaci&oacute;n, empresa, etc" />
									 </fieldset>
									 <fieldset id="advanced" class="field hide mB5">
										  <h5 class="f13 bold">&Aacute;rea</h5>
										  <select class="selectA">
												<option>Area 1</option>
												<option>Area 2</option>
										  </select>
										  <h5 class="f13 bold">Nivel de puesto</h5>
										  <select class="selectA">
												<option>Puesto 1</option>
												<option>Puesto 2</option>
										  </select>
										  <h5 class="f13 bold">Ubicación</h5>
										  <select class="selectA">
												<option>Ubicación 1</option>
												<option>Ubicación 2</option>
										  </select>
									 </fieldset>
									 <fieldset id="sbtSearchC" class="right btnImgH btnAdv">
										  <input id="sbtSearch" class="active btnPink" type="submit" value=""/>
									 </fieldset>
								</form>
								<div class="advanced"><a href="#" id="searchAdv">B&uacute;squeda avanzada</a></div>
						  </div>
					 </div>
				</div>
				<div class="all">
					 <div class="bgASTIE left">
						  <div class="modList r10 bGray">
								<h3 class="icoAreas">&Aacute;reas profesionales</h3>
								<ul class="listCat">
									 <li class="item"><a href="./busqueda.resultado.html">Administracion</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Asistente</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Secretar&iacute;a</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Ingen&iacute;ero industrial</a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Arquitecto</a><span class="count">(32)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Administracion</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Asistente</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Secretar&iacute;a</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Ingen&iacute;ero industrial</a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Arquitecto</a><span class="count">(32)</span></li>
								</ul>
								<div class="asideList"> <a href="#moreWM1" class="winIModal">Ver todos</a> </div>
						  </div>
					 </div>
					 <div class="bgASTIE left">
						  <div class="modList r10 bGray">
								<h3 class="icoNivel">Nivel del puesto</h3>
								<ul class="listCat">
									 <li class="item"><a href="./busqueda.resultado.html">Alta gerencia</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Gerencia media</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Jefatura / Supervisi&oacute;n</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Ejecutivo comercial</a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Analista asistente</a><span class="count">(32)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Alta gerencia</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Gerencia media</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Jefatura / Supervisi&oacute;n</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Ejecutivo comercial</a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Analista asistente</a><span class="count">(32)</span></li>
								</ul>
								<div class="asideList"> <a href="#moreWM2" class="winIModal">Ver todos</a> </div>
						  </div>
					 </div>
					 <div class="bgASTIE left">
						  <div class="modList r10 bGray last">
								<h3 class="icoUbigeo">Por Ubicac&iacute;on</h3>
								<ul class="listCat">
									 <li class="item"><a href="./busqueda.resultado.html">Lima</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Trujillo</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Arequipa</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Tacna </a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Tumbes</a><span class="count">(32)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Lima</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Trujillo</a><span class="count">(722)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Arequipa</a><span class="count">(322)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Tacna </a><span class="count">(122)</span></li>
									 <li class="item"><a href="./busqueda.resultado.html">Tumbes</a><span class="count">(32)</span></li>
								</ul>
								<div class="asideList"> <a href="#moreWM3" class="winIModal">Ver todos</a> </div>
						  </div>
					 </div>
					 <div id="moreWM1" class="moreWM bgWM1 hide">
						  <div class="rel">
								<h3>&Aacute;reas profesionales</h3>
								<a class="closeH0WM icoCWM" href="#cerrar"><span class="hide">Cerrar</span></a> </div>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Administrativas y comerciales</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arquitect&oacute;s y urban&iacute;s</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Biolog&iacute;a</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Administrativas y comerciales</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Administrativas y comerciales</a></li>
						  </ul>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Comunicaciones</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Educaci&oacute;n</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Ingenier&iacute;a</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Psicologicas y Sociales</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Sistemas / TI</a></li>
						  </ul>
						  <ul class="ulWM mT10 left">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Turismo, Hoteler&iacute;a, Restaurantes</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Legal</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Medicina</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Sistemas / TI</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Turismo, Hoteler&iacute;a, Restaurantes</a></li>
						  </ul>
					 </div>
					 <div id="moreWM2" class="moreWM bgWM2 hide">
						  <div class="rel">
								<h3>Nivel del puesto</h3>
								<a class="closeH0WM icoCWM" href="#cerrar"><span class="hide">Cerrar</span></a> </div>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Alta gerencia</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Gerencia media</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Jefatura / Supervisi&oacute;n</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Ejecutivo comercial</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Analsita asistente</a></li>
						  </ul>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Analsita asistente</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Ejecutivo comercial</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Jefatura / Supervisi&oacute;n</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Gerencia media</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Alta gerencia</a></li>
						  </ul>
						  <ul class="ulWM mT10 left">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Alta gerencia</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Gerencia media</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Jefatura / Supervisi&oacute;n</a></li>
						  </ul>
					 </div>
					 <div id="moreWM3" class="moreWM bgWM3 hide">
						  <div class="rel">
								<h3>Por ubicaci&oacute;n</h3>
								<a class="closeH0WM icoCWM" href="#cerrar"><span class="hide">Cerrar</span></a> </div>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Lima</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Trujillo</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arequipa</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Tacna</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Tumbes</a></li>
						  </ul>
						  <ul class="ulWM left mT10 mR5">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arequipa</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Trujillo</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Lima</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Tumbes</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arequipa</a></li>
						  </ul>
						  <ul class="ulWM mT10 left">
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arequipa</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Trujillo</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Lima</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Tumbes</a></li>
								<li class="liWM mB5"><a class="itemMWM f11" href="./busqueda.resultado.html">Arequipa</a></li>
						  </ul>
					 </div>
				</div>
		  </div>
		  <div id="sidebar" class="grid7 right theta bgSITIE">
				<div class="innerAside r10 bLBlue bgLBlue">
					 <div class="modArticle bgWhite r10 bgBLTIE mB0">
						  <h4 class="bgH4S titleAside">Avisos relacionados<span class="icoArtRel">&nbsp;</span></h4>
						  <ul class="listArticle">
								<li class="itemArticle"> <span class="dateArticle"><a href="./aviso.empleo.postulado.html">Diseñador Gráfico Senior</a></span> <span class="txtArticle bold">Corporación Wong</span> <span class="txtArticle cGray">Lima</span> </li>
								<li class="itemArticle"> <span class="dateArticle"><a href="./aviso.empleo.postulado.html">Diseñador Gráfico Senior</a></span> <span class="txtArticle bold">Corporación Wong</span> <span class="txtArticle cGray">Lima</span> </li>
								<li class="itemArticle"> <span class="dateArticle"><a href="./aviso.empleo.postulado.html">Diseñador Gráfico Senior</a></span> <span class="txtArticle bold">Corporación Wong</span> <span class="txtArticle cGray">Lima</span> </li>
								<li class="itemArticle"> <span class="dateArticle"><a href="./aviso.empleo.postulado.html">Diseñador Gráfico Senior</a></span> <span class="txtArticle bold">Corporación Wong</span> <span class="txtArticle cGray">Lima</span> </li>
						  </ul>
						  <div class="asideLink"> <a href="#" class="btnGoBlog">Ver más</a> </div>
						  <div class="hide bgBLBIE">&nbsp;</div>
					 </div>
				</div>
				<div class="hide bgSIBIE">&nbsp;</div>
		  </div>
	 </div>
</div>
