<?php echo Application_Model_Partials::getMenuPostulante(); ?>
<?php if($this->ispostulante) { ?>    
    <section class="message_box error">
        <div class="center_box">
            <div class="message">
                <i class="icon icon_check"></i>
                <span>Para postular al aviso debe estar logueado como postulante.</span></div>
            <i class="icon icon_cross"></i>
        </div>
    </section>
<?php } ?>      

<section class="aviso">
  <div class="container">
    <hr class="linea">
    <div class="row">
      <div class="col-md-7">
        <p class="titular"><span>Oferta</span> de empleo</p>

        <?php echo $this->partial('_partials/_new_messages.phtml', array("flashMessages" => $this->flashMessages)); ?>

        <?php
          switch($this->aviso['prioridad']) {          
            case 1:
                $_medal = "medal1.svg";
                $_class = "box-subtitular-d-oro";
                break;

            case 2:
                $_medal = "medal2.svg";
                $_class = "box-subtitular-d-plata";
                break;

            default:                
                $_class = "box-subtitular";
                break;
          }
        ?>

        <?php if(!empty($_medal)): ?>
        <div class="box-star">
          <img src="<?php echo $this->S('eb/svg/'.$_medal); ?>" alt="" class="bandera-left">
        </div>
        <?php endif ?>
        <div class="<?php echo $_class; ?> text-left">
          <p><?php echo $this->aviso['puesto'] ?></p>
        </div>
        
        <?=$this->partial('aviso/_new_ver_aviso_actual.phtml',
                array('aviso' => $this->aviso,
                'online' => $this->online,
                'hasPostulado' => $this->hasPostulado,
                'hasDesPostulado' => $this->hasDesPostulado,
                'cuestionario' => $this->cuestionario,
                'searchResultsUrl' => $this->searchResultsUrl,
                'auth' => $this->auth,
                'urlAviso' => $this->urlAviso,
                'module' => $this->module,
                'isAuth' => $this->isAuth,
                'acceso' => $this->acceso,
                'micuentaUrl' => $this->micuentaUrl,
                'seo' => $this->seo,
                'updateCV' => $this->updateCV,
                'LogoDefecto' =>$this->LogoDefecto,
                'postulante' => $this->postulante,
                'moneda' => $this->moneda,
                'lookAndFeel'=>$this->lookAndFeel  , 'LookAndFeelColors'=>$this->LookAndFeelColors
                    ))       
        ?>

      </div>
      <div class="col-md-5">
        
        <?php
            if (count($this->anunciosRelacionados) > 0) {
                echo $this->partial('_partials/_avisos_relacionados.phtml',array(
                    'anunciosRelacionados' => $this->anunciosRelacionados,
                    'verLogoDefecto' => $this->verLogoDefecto,
                    'slugArea' => $this->slugArea,
                    'slugNivel' => $this->slugNivel,
                    'LogoDefecto' =>$this->LogoDefecto,
                ));
            }
            if (count($this->anunciosSugeridos) > 0) {
                echo $this->partial('_partials/_ver_avisos_sugeridos.phtml',array(
                    'avisosSugerencias' => $this->anunciosSugeridos,
                    'verLogoDefecto' => $this->verLogoDefecto,
                    'slugArea' => $this->slugArea,
                    'slugNivel' => $this->slugNivel,
                    'LogoDefecto' =>$this->LogoDefecto,
                    'paginaActual'=>1
                ));
            }
        ?>
      </div>
    </div>
  </div>
</section>