<?=$this->partial('aviso/_ver_aviso_lucene.phtml', array(
    'aviso' => $this->aviso,
    'online' => $this->online,
    'hasPostulado' =>$this->hasPostulado,
    'cuestionario' => $this->cuestionario, 
    'searchResultsUrl' => $this->searchResultsUrl,
    'auth' =>$this->auth,
    'urlAviso'=> $this->urlAviso,
    'module' => $this->module,
    'isAuth' => $this->isAuth,
    'acceso' => $this->acceso
))?>