<style type="text/css">
  .bg_primary { background:<?= $this->LookAndFeelColors['bg_primary']?>;  }
  .color_primary { color:<?= $this->LookAndFeelColors['bg_primary']?>; }
  .border_primary { border-color:<?= $this->LookAndFeelColors['bg_primary']?>; }
  /*Para la estrella*/
  .job_description .btn_hightlight .icon {color: <?=$this->LookAndFeelColors['bg_primary']?>;}
  .bg_secondary { background:<?=$this->LookAndFeelColors['bg_secondary']?>!important; }
</style>
<?php echo Application_Model_Partials::getMenuPostulante();?>
<?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages));?>
<?php if ( $this->ispostulante ) : ?>
    <section class="message_box error">
        <div class="center_box">
          <div class="message">
              <i class="icon icon_check"></i>
              <span>Para postular al aviso debe estar logueado como postulante.</span></div>
          <i class="icon icon_cross"></i>
        </div>
    </section>
<?php endif; ?>
<section class="aviso <?=($this->lookAndFeel)?' look_and_feel': ''?>">
  <div class="job_header bg_primary">
    <div class="banner_box">
      <img class="banner_image lazy" data-src="<?=$this->LookAndFeelColors['banner_alta']?>" src="<?=$this->LookAndFeelColors['banner']?>" alt="Imagen principal">
    </div>
    <div class="center_box">
      <div class="job_box_speech">
        <?php foreach ($this->Menus()->ValiIsNotAvisoCiegoLink($this->aviso,$this->isNotAvisoCiego) as $key => $value) {?>
          <a class="job_box_image_container" href='<?= $value['href']?>' title="<?= $value['title']?>">
            <div class="center_image"><img alt="<?= $value['alt']?>" src="<?= $value['src']?>"></div>
          </a>
        <?php } ?>
        <div class="slogan"><?=$this->LookAndFeelColors['eslogan']?></div>
      </div>
      <div class="breadcrumb">
        <?php foreach ($this->Menus()->ListMenusBuscadorAviso($this->aviso) as $key => $value) {?>
        <div itemtype="http://data-vocabulary.org/Breadcrumb" itemscope>
            <a href="<?=$value['href']?>" itemprop="url" title="<?=$value['title']?>">
                <span itemprop="title"><?=$value['title']?></span>
            </a>
        </div><span>/</span>
       <?php } ?>
        <div>
            <a href="javascript:;" title="<?= $this->aviso['puesto'] ?>">
                <span><?= $this->aviso['puesto'] ?></span>
            </a>
        </div>
      </div>
      <div class="mobile_column_company">
        <a href="#" class="show_company btn"><i class="icon icon_arrow_right"></i></a>
      </div>
    </div>
  </div>
  <div class="job_body">
    <div class="job_body_bg"></div>
    <div class="center_box">
      <div class="row">
          <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
          <div class="job_description_wrapper">
              <?=$this->AnuncioHelper($this->aviso)->divCintilloNew($this->S('/main/img/job_finished.png')); ?>
              <?php if ($this->hasPostulado != false) : ?>
                  <div class="job_box_already_have_applied">
                      <?php $nomEmpresa = ($this->aviso['mostrar_empresa'] != 0) ? $this->aviso['nombre_empresa'] : $this->aviso['nombre_comercial'];    ?>
                      <?php if(empty($this->destacado)) : ?>
                      <div class="info_cv">
                          <h4 class="title_cv m0">¡Felicitaciones!</h4>
                          <p><?= strtotime(date('Y-m-d H:i:s')) < (strtotime($this->hasPostulado) + 12) ? 'Acabas de postular' : 'Ya postulaste'; ?> al puesto de <?= $this->aviso['puesto'] ?> en <?=$nomEmpresa?></p>
                      </div>
                      <div class="image_cv"></div>
                      <?php else : ?>
                          <h4 class="title_cv m0">¡Felicitaciones!</h4>
                          <p><?=strtotime(date('Y-m-d H:i:s')) < (strtotime($this->hasPostulado) + 12) ? 'Acabas de postular' : 'Ya postulaste'; ?> al puesto de <?= $this->aviso['puesto'] ?> en <?=$nomEmpresa?></p>
                      <?php endif; ?>
                  </div>
              <?php endif; ?>
                  <div class="job_description color_primary row <?php echo ($this->hasPostulado) ? 'job_box_finished': '';?>">
                    <div class="row_1">
                      <div class="job_icon">
                        <i class="icon icon_briefcase"></i>
                      </div>
                      <h1 class="job_description_title">
                        <label itemprop="title"><?= $this->aviso['puesto']; ?></label>
                      </h1>
                      <?php if ($this->module == 'postulante') : ?>
                        <div class="job_description_options">
                        <?php if ($this->AnuncioHelper($this->aviso)->showBtnPostular()) : ?>
                        <?=$this->AnuncioHelper(null)->validaFavorito($this->auth,$this->aviso,$this->isAuth)?>
                        <?php endif; ?>
                        </div>
                      <?php endif; ?>
                    </div>
                    <div class="row_2">
                      <?php
                        if ($this->aviso['mostrar_empresa'] != 0) {
                          if (isset($this->aviso['slug_empresa'])) { ?>
                            <div class="job_icon">
                              <i class="icon icon_building"></i>
                            </div>
                            <h2 class="job_description_title"><label itemprop="title"><a href='/buscar/empresa/<?=$this->aviso['slug_empresa']?>' target="_blank" title="<?= $this->escape($this->aviso['nombre_empresa']); ?>"><?= $this->escape($this->aviso['nombre_empresa']); ?></a></label></h2>
                          <?php } else { ?>
                            <div class="job_icon">
                              <i class="icon icon_building"></i>
                            </div>
                            <h2 class="job_description_title"><label itemprop="title"><?= $this->escape($this->aviso['nombre_empresa']); ?></label></h2>
                          <?php } ?>
                        <?php }  ?>
                    </div>
                    <div class="row_3">
                      <div class="job_icon">
                        <i class="icon icon_map_location"></i>
                      </div>
                      <h4 itemprop="jobLocation" itemtype="http://schema.org/Place"><?= $this->escape($this->aviso['ciudad']); ?></h4>
                      <?php if ($this->module == 'postulante') : ?>
                        <div class="mobile_job_description_options">
                        <?php if ($this->AnuncioHelper($this->aviso)->showBtnPostular()) : ?>
                        <?=$this->AnuncioHelper(null)->validaFavorito($this->auth,$this->aviso,$this->isAuth)?>
                        <?php endif; ?>
                        </div>
                      <?php endif;  ?>
                    </div>
                  </div>
                <?=$this->partial('aviso/_new_ver_aviso.phtml',
                         array('aviso' => $this->aviso,
                         'online' => $this->online,
                         'hasPostulado' => $this->hasPostulado,
                         'hasDesPostulado' => $this->hasDesPostulado,
                         'cuestionario' => $this->cuestionario,
                         'searchResultsUrl' => $this->searchResultsUrl,
                         'auth' => $this->auth,
                         'urlAviso' => $this->urlAviso,
                         'module' => $this->module,
                         'isAuth' => $this->isAuth,
                         'acceso' => $this->acceso,
                         'micuentaUrl' => $this->micuentaUrl,
                         'seo' => $this->seo,
                         'updateCV' => $this->updateCV,
                         'LogoDefecto' =>$this->LogoDefecto,
                         'postulante' => $this->postulante,
                         'lookAndFeel'=>$this->lookAndFeel  ,
                         'LookAndFeelColors'=>$this->LookAndFeelColors,
                         'postular'=>$this->AnuncioHelper(null)->postular($this),
                         'moneda'=>$this->moneda,
                         'ulrDestino'=> SITE_URL .$this->url(array('slug' => $this->aviso["slug"], 'url_id' => $this->aviso["url_id"]), 'aviso', true)
                             ))       ?>
        </div>
        <aside class="company bg_tertiary color_aside">
           <?php
                echo $this->partial('_partials/_avisos_empresas.phtml',array(
                    'aviso' => $this->aviso,
                    'anunciosRelacionados' => $this->anunciosRelacionados,
                    'verLogoDefecto' => $this->verLogoDefecto,
                    'slugArea' => $this->slugArea,
                    'slugNivel' => $this->slugNivel,
                    'LogoDefecto' =>$this->LogoDefecto,
                    'LookAndFeelColors'=>$this->LookAndFeelColors,
                    'module' => $this->module,
                    'auth' => $this->auth,
                    'isAuth' => $this->isAuth
                ));        ?>
        </aside>
      </div>
    </div>
  </div>
</section>
<script type="text/template" id="staticImage">
  <img id="imageMap" class="google_map_location" src="http://maps.googleapis.com/maps/api/staticmap?size=<%= sizeWidth %>x400&amp;center=<%= latitud %>,<%= longitud %>&amp;zoom=17&amp;maptype=roadmap&amp;markers=icon:http://chart.apis.google.com/chart?chst=d_map_pin_letter%26chld=%E2%80%A2%257C<%= color %>%7C<%= latitud %>,<%= longitud %>&amp;sensor=false&amp;style=feature:all%7Celement:all%7Cvisibility:on&amp;style=feature:administrative%7Celement:labels.text.fill%7Ccolor:0x444444&amp;style=feature:landscape%7Celement:all%7Ccolor:0xf2f2f2&amp;style=feature:poi%7Celement:all%7Cvisibility:off&amp;style=feature:road%7Celement:all%7Csaturation:-100%7Clightness:45&amp;style=feature:road.highway%7Celement:all%7Cvisibility:simplified&amp;style=feature:road.arterial%7Celement:labels.icon%7Cvisibility:off&amp;style=feature:transit%7Celement:all%7Cvisibility:off&amp;style=feature:water%7Celement:all%7Ccolor:0x<%= color %>%7Cvisibility:on">
</script>
