<section class="aviso">

    <div class="container spb">

        <div class="row smb contenido-ficha">
            <div class="col-md-7 spb">
                <?php if ($this->hasPostulado) { ?>
                    <div class="flash-message-ya-postulaste">
                        <i class="fa fa-check-circle" aria-hidden="true"></i>
                        <span>¡ Ya has postulado !</span>
                    </div>
                <?php } ?>
               <!-- <a href="#" class="link-empresa">Loro S.A.C</a> -->
                

                <div class=" text-left container-title-oro">
                    <?php if (!empty($this->verAviso($this->aviso)->medalla())) : ?>
             
                        <img src="<?= $this->S('/eb/svg/'.$this->verAviso($this->aviso)->medalla()); ?>" alt="" class="bandera-oro">

                    <?php endif;?>
                        <h1 class="<?= $this->verAviso($this->aviso)->tipoAvios() ?> cuadro">
                            <?= $this->aviso['puesto'] ?>
                        </h1>
                </div>
                <div class="">
                    <?=
                    $this->partial('aviso/_ver-aviso.phtml',
                        array(
                        "aviso" => $this->aviso,
                        'auth' => $this->auth,
                        'cuestionario' => $this->cuestionario,
                        'hasPostulado' => $this->hasPostulado,
                        'ispostulante' => $this->ispostulante,
                        'moneda' => $this->moneda,
                        'url'=>$this->url 
                    ));
                    ?>
                </div>
            </div>

            <div class="col-md-5 spb contenedor-derecho-ficha">
                <!-- <a href="#" class="link-empresa no-visibility">Oferta de empleo</a> -->
                <?=
                $this->partial('_partials/_avisos-similares.phtml',
                    array(

                    "anunciosRelacionados" => $this->anunciosRelacionados,
                    "url" => $this->url
                ));
                ?>
            </div>
        </div>
    </div>
</section>
