<form id="formDivAvi" action="" method="post" >
	<h3>Dividir Avisos</h3>
 	
 	<table id="dataDivAviso" summary="Aviso original" class="dataGrid">
		<thead>
			<tr>
				<th class="dataC1 titleGrid alignC" colspan="2">Aviso Original</th>
			</tr>
		</thead>
 		<tbody>
 			<tr>
 				<td class="data1 bold">Título</td>
 				<td class="data2"><?= $this->escape(ucfirst($this->puesto)); ?></td>
 			</tr>	
 			<tr>
 				<td class="data1 bold">Vigencia</td>
 				<?php if ($this->fh_pub!= null && $this->fh_vencimiento != null) { ?>
 				<td class="data2"><?= $this->fh_pub.' al '.$this->fh_vencimiento; ?></td>
 				<?php } else {?>
 				<td class="data2">Sin fecha de publicación</td>
 				<?php } ?>
 			</tr>	 
 			<tr>
 				<td class="data1 bold">Cliente</td>
 				<td class="data2"><?= $this->razon_social; ?></td>
 			</tr>	  						
 		</tbody>
 		
 	</table>
 	
 	<!--
 	<div class="textDownR">
	 	<div class="bold nameTDR">Aviso Original</div>	
 		<div class="bold nameTDR">Título</div>
 		<?//= $this->escape(ucfirst($this->puesto)); ?>
 		<div class="bold nameTDR">Vigencia</div>
 		<?//= $this->fh_pub.' al '.$this->fh_vencimiento; ?> 	
		<div class="bold nameTDR">Cliente</div>
 		<?//= $this->razon_social; ?>
	</div> 
	-->
	
	<h3>Ingrese los datos de los nuevos</h3>
	<!--
	<div class="bold nameTDR">Ingrese los datos de los nuevos</div>
	-->
	<p class="c6">El primer título reemplazará al del aviso original; los siguientes generarán nuevos
                  avisos. Conforme vaya ingresando títulos de puesto irán apareciendo más cajas de texto,
                  pudiendo ingresar hasta un máximo de 14 títulos.
    </p>
	<div id="flowIptDivAv">
		<fieldset class="all">
        <?php if ($this->avisoF <= 13) {
            $this->avisoF = $this->avisoF+1;
        }?>
        <ol id="ulListDivs" class="ulListDivs">
        <?php for ($i = 0; $i < $this->avisoF; $i++) { ?>
            <li class="cntBlockIpt <?php echo ($i== 0 || $i== 1)? '':'hide'?>" <?php echo ($i== 0 || $i== 1)? '':'' ?>>

                    <label class="<?= $i== 0? '':'c6' ?> labelMoN"><?php //echo $i+1?>Título del nuevo aviso : </label>
                    <input type="text" 
                        name="nuevoId_<?php echo $i+1?>" 
                        id="nuevoId_<?php echo $i+1?>" 
                        class="iptData inputMoN <?php echo ($i== 0)? 'noHide':''?>" 
                        value="<?php echo $i== 0? $this->puesto:'' ?> " 
                        <?php echo $i== 0? 'rel="'.$this->id.'"':''?> />

            </li>
        <?php }?>
        </ol>
		</fieldset>
	</div>
	<fieldset class="all">
		<input type="submit" id="submitDividirAviso" class="sptAdm btnSptAdm" value=""  >
	</fieldset>
</form>
