<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>	
    		<div class="gridTab">
                    <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <?=$this->partial('_partials/_accion-adminAvisoPreferencial.phtml',
                        array(
                        	'puesto'=>$this->puesto,
                        	'avisoPreferencialAdminUrl'=>$this->avisoPreferencialAdminUrl,
                        	'online'=>$this->online,
                        	'idAviso'=>$this->idAviso,
                            'avisoF' => $this->avisoF,
                            'avisoMax'=> $this->avisoMax
                        )
                    )?>
                     <div id="avisoAdmin">
        				<!-- Inicio Form -->
                		<h2 class="titleOrig">Datos del puesto</h2>
                        <!-- Inicio de Lista de avisos -->
                        <?php if (isset($this->div) && $this->div > 1) {?>
                        <div class="cntPagerAP">
                            <p class="f14 cntPuestosW">Puestos</p>
                            <p class="pTextAPW">(Puede completar cada puesto en cualquier orden. Si faltase algún puesto, puede seleccionar cualquiera de ellos y nuevamente dividirlo)</p>
                            <div class="allDivAPP">
                                <?= $this->ListaPreferencialAdmin('listPagerAP1', $this->maximoAnuncios, $this->dataPosicion) ?>
                                <div id="btnsDivAP" class="txt_right">
                                    <!--
                                    <h3 class="left titlePagerM">Rellene los datos del Puesto Número <span><?= $this->dataPosicion['current'] ?></span> </h3>
                                    -->
                                    <?php if (isset($this->avisoWebId) && $this->primero !=$this->avisoWebId ) : ?>
                                        <a id="btnDeleteP" class="btn btn-primary" href="<?= $this->url(array('module' => 'admin', 'controller' => 'aviso-preferencial', 'action' => 'eliminar-aviso', 'aviso' => $this->avisoWebId), false, true) ?>">
                                            Eliminar
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                        <!-- Fin de Lista de avisos -->
                		<div class="gridIFormEmp resG">
                			<div id="innerMain" >
                				<div id="content" class="formRegister">
                					<form action="" id="frmPublishAd" method="post">
            						<?php echo $this->partial('_partials/_paso2_aviso.phtml', 'admin', 
                    				    array(
                    				    'form' => $this->form, 
                    				    'isDato' => $this->isDato,
                    				    'numPalabraPuesto' => $this->numPalabraPuesto,
	                    				'numPalabraOtroNombre' =>$this->numPalabraOtroNombre,
                    				    'modulo' =>$this->modulo,
                    				    'nombreComercial' => $this->nombreComercial,
                    				    'formEstudio' => $this->formEstudio, 'managerEstudio'=> $this->managerEstudio, 'isEstudio' => $this->isEstudio, 'isEditarEstudio' => $this->isEditarEstudio,
                                                    'formOtroEstudio' => $this->formOtroEstudio,'managerOtroEstudio' => $this->managerOtroEstudio,'isOtroEstudio' => $this->isOtroEstudio,'isEditarOtroEstudio' => $this->isEditarOtroEstudio,
                    				    'formExperiencia' => $this->formExperiencia, 'managerExperiencia'=> $this->managerExperiencia, 'isExperiencia' => $this->isExperiencia, 'isEditarExperiencia' => $this->isEditarExperiencia, 
                    				    'formIdioma' => $this->formIdioma, 'managerIdioma'=> $this->managerIdioma, 'isIdioma' => $this->isIdioma, 'isEditarIdioma' => $this->isEditarIdioma,
                    				    'formPrograma' => $this->formPrograma, 'managerPrograma'=> $this->managerPrograma, 'isPrograma' => $this->isPrograma, 'isEditarPrograma' => $this->isEditarPrograma,
                    				    'formPregunta' => $this->formPregunta, 'managerPregunta'=> $this->managerPregunta, 'isPregunta' => $this->isPregunta, 'isEditarPregunta' => $this->isEditarPregunta, 'frmUbigeo' => $this->frmUbigeo
                    				    )
            					    ); ?>
            					    <div class="wrap-btn right mT20">
                            			<span id="msgErrorStep2" class="left error"></span>

                            			<a id="btnSaveCAP" href="#" data-tipo="" class="btn btn-primary btnSaveCDAP">Guardar Cambios</a>

                                        <?php if (count($this->avisoF) < $this->avisoMax) {?>
                            			<a id="btnSaveDAP" href="#" data-tipo="duplicar" class="btn btn-primary btnSaveCDAP">Guardar y Duplicar</a>
                                        <input id="dup" name="dup" type="hidden" value="">
                                        <?php } ?>
                                	</div>
                                    <input type="hidden" name="redirctGua" value="" id="redirctGua" />
                    				</form>
                    				<?php echo $this->partial('_partials/_paso2_aviso_blank.phtml', 'admin', 
                					    array(
                					    'managerEstudio'=> $this->managerEstudio,
                                                            'managerOtroEstudio' => $this->managerOtroEstudio,
                					    'managerExperiencia'=> $this->managerExperiencia, 
                					    'managerIdioma'=> $this->managerIdioma,
                					    'managerPrograma'=> $this->managerPrograma,
                					    'managerPregunta'=> $this->managerPregunta,
                					    )
                				    ); ?>
                				</div>
                			</div>
        					<!-- Fin Form -->
                    	</div>
                        <a id="linkBtnFPaso" href="#escapeFormPaso" class="winModal"></a>
               	 	</div>
           	 	</div>
    		</div>
		</div>
	</div>
</div>
