<label class="ioption"><?=$this->formAlertas->prefs_emailing_avisos->setAttribs(array('id'=>'chkSendEmail'))->renderViewHelper(); ?>Deseo recibir periódicamente avisos de empleos que se ajusten a mi perfil.</a>
</label>
<label class="ioption"><?=$this->formAlertas->prefs_emailing_info->setAttribs(array('id'=>'chkSendEmailAds'))->renderViewHelper(); ?>Deseo recibir periódicamente información y publicidad útil que me permita mantenerme actualizado en el mercado laboral.</a>
</label>