<?php /* ?>
<label class="ioption">
<?=$this->formAlertas->prefs_emailing_avisos->setAttribs(array('id'=>'chkSendEmail'))->renderViewHelper(); ?> 
    Deseo recibir periódicamente avisos de empleos que se ajusten a mi perfil.
</label>
<label class="ioption">
<?=$this->formAlertas->prefs_emailing_info->setAttribs(array('id'=>'chkSendEmailAds'))->renderViewHelper(); ?> 
    Deseo recibir periódicamente información y publicidad útil que me permita mantenerme actualizado en el mercado laboral.
</label>

<?php */ ?>


<div class="form_control">
    <label class="ioption" for="chkSendEmail">

      <?=$this->formAlertas->prefs_emailing_avisos->setAttribs(array('id'=>'chkSendEmail'))->renderViewHelper(); ?> 
      <div class="option_info">
        <p>Reporte de actividad.</p>
        <p>Resumen mensual de actividades entre las empresas y tu perfil.</p>
      </div>

    </label>
</div>

<div class="form_control">
    <label class="ioption" for="chkSendEmailAds"> 
        <?=$this->formAlertas->prefs_emailing_info->setAttribs(array('id'=>'chkSendEmailAds'))->renderViewHelper(); ?> 
        <div class="option_info">
          <p>Deseo recibir periódicamente avisos de empleos que se ajusten a mi perfil.</p>
          <p>Envío semanal de avisos de empleo de acuerdo a tu perfil.</p>
        </div>
    </label>
</div>


<div class="form_control">
    <label class="ioption" for="chkSendEmailInfoML"> 
      <?=$this->formAlertas->prefs_emailing_mercado->setAttribs(array('id'=>'chkSendEmailInfoML'))->renderViewHelper(); ?> 
      <div class="option_info">
        <p>Deseo recibir periódicamente información y publicidad útil que me permita mantenerme actualizado en el mercado laboral.</p>
      </div>
    </label>
</div>
