<?php
$ind = (isset($this->indice)) ? $this->indice : 'blank';

if($this->form->id_estudio != null &&  $this->form->id_estudio->getValue() != ''){
	$dataRol = 'data-rol="'.$this->form->id_estudio->getValue().'"';
}
if(isset($this->idPostulante)){
	$dataRel = 'data-rel="'.$this->idPostulante.'"';
}
$dataInd = 'data-index="' . $ind . '"';
?>

<?php if ($this->form->is_disabled->getValue()) { ?>
	<li <?= $dataRol?> <?= $dataRel?> <?= $dataInd ?>>
		<?php if (isset($this->isLinkedin) && $this->isLinkedin==true  || $this->isEstudio == true) { ?>
			<?php if ($this->form->id_nivel_estudio->getValue() != null && $this->form->id_nivel_estudio->getValue() != "0" || isset($this->isLinkedin)) : ?>
				<ul class="skill-title row">
					<li><?php echo $ind + 1; ?>. </li>
					<li>
                        <?php if ($this->form->id_nivel_estudio->getValue() != 1 && $this->form->id_nivel_estudio->getValue() != 2 && $this->form->id_nivel_estudio->getValue() != 3) :?>
							<b><?= $this->escape($this->form->otro_carrera->getValue()); ?></b> en <b><?= $this->escape($this->form->institucion->getValue()); ?></b>
						<?php else : ?>
							<b><?= $this->escape($this->form->id_nivel_estudio->getMultiOption($this->form->id_nivel_estudio->getValue())); ?></b>
						<?php endif; ?>
					</li>
					<li class="last">
						<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
					</li>
				</ul>
			<?php endif; ?>
		<?php } ?>
	</li>
	<?php
} else {
	?>
	<li <?= isset($dataRol) ? $dataRol : ''?> <?= isset($dataRel) ? $dataRel : '' ?> <?= $dataInd ?>>
		<?php if (isset($this->isLinkedin) && $this->isLinkedin==true || $this->isEstudio == true) { ?>
			<?php if ($this->form->id_nivel_estudio->getValue() != "0" || isset($this->isLinkedin)) : ?>
				<ul class="skill-title row">
					<li><?php echo $ind + 1; ?>. </li>
					<li>
                        <?php if ($this->form->id_nivel_estudio->getValue() != 1 && $this->form->id_nivel_estudio->getValue() != 2 && $this->form->id_nivel_estudio->getValue() != 3) {
							?>
							<?php if ($this->form->id_carrera->getValue() == Application_Model_Carrera::OTRO_CARRERA) { ?>
                                    <b><?= $this->escape($this->form->otro_carrera->getValue()); ?></b>
                                    <?php } else { ?>
                                    <b><?=$this->escape($this->form->id_carrera->getMultiOption($this->form->id_carrera->getValue()));?></b>
                            <?php }  ?>
                             en <b><?= $this->escape($this->form->institucion->getValue()); ?></b>
                        <?php } else if ($this->form->id_nivel_estudio->getValue() == 1) { ?>
							<b><?= $this->escape($this->form->id_nivel_estudio->getMultiOption($this->form->id_nivel_estudio->getValue())); ?></b>
                        <?php } else { ?>
							<b><?= $this->escape($this->form->id_nivel_estudio->getMultiOption($this->form->id_nivel_estudio->getValue())); ?></b> en <b><?= $this->escape($this->form->institucion->getValue()); ?></b>
                        <?php } ?>
					</li>
					<li class="last">
						<a href="#Editar" class="action-icons edit" title="Editar"></a>
						<a href="javascript:;" class="action-icons delete" title="Eliminar"></a> 
					</li>
				</ul>
			<?php endif; ?>
		<?php } ?>

                             <?php $hideSinEstudios = (in_array($this->form->id_nivel_estudio->getValue(),array(1,2,3)))?' hide':'' ?>
		<? $isError = $this->form->isErrors(); ?>
		<div class="skill-content<?=(!$isError && $this->isEstudio === true) ? ' hide' : ''?><?= $isError ? ' active' : '' ?>" >
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Grado:</label>
				<div class="controls">
					<? $hasError = $this->form->id_nivel_estudio->hasErrors(); ?>
					<?php if (in_array($this->form->id_nivel_estudio->getValue(),array(1,2,3))): ?>
						<?= $this->form->id_nivel_estudio->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->id_nivel_estudio->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
					<?php endif; ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_estudio->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group<?=$hideSinEstudios?>">
				<label for="" class="control-label"><em>*</em> Estado:</label>
				<div class="controls">
					<? $hasError = $this->form->id_nivel_estudio_tipo->hasErrors(); ?>
                    <?php if (in_array($this->form->id_nivel_estudio->getValue(),array(1,2,3,9))) { ?>
                        <?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
                    <?php } else { ?>
                        <?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                    <?php } ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_estudio_tipo->errMsg : '' ?></span>
				</div>
			</div>
			<?php $class_colegiado =(in_array($this->form->id_nivel_estudio_tipo->getValue(), Application_Model_NivelEstudio::$_nivelColegiado)) ? '' : ' hide';?>
			<div class="control-group<?=$class_colegiado?>">
				<label for="" class="control-label no-req"><em>&nbsp;</em> N&uacute;mero de Colegiatura:</label>
				<div class="controls">
					<? $hasError = $this->form->colegiatura_numero->hasErrors(); ?>
					<?= $this->form->colegiatura_numero->setAttribs(array('class' => 'input-xsmall number'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->colegiatura_numero->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Nombre de la institución:</label>
				<div class="controls ui-widget">
					<? $hasError = $this->form->institucion->hasErrors(); ?>
                    <?php if ($this->form->id_nivel_estudio->getValue() == 1) { ?>
						<?= $this->form->institucion->setAttribs(array('class' => 'input-xmedium second_title require', 'autocomplete' => 'off','disabled' => 'disabled'))->renderViewHelper(); ?>
                    <?php } else { ?>
                    <?= $this->form->institucion->setAttribs(array('class' => 'input-xmedium second_title require', 'autocomplete' => 'off'))->renderViewHelper(); ?>
                    <?php } ?>
					<?//= $this->form->id_institucion ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->institucion->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> País:</label>
				<div class="controls">
					<? $hasError = $this->form->pais_estudio->hasErrors(); ?>
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
						<?= $this->form->pais_estudio->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->pais_estudio->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
					<?php endif; ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->pais_estudio->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group<?=$hideSinEstudios?>">
				<label for="" class="control-label"><em>*</em> Tipo de Carrera:</label>
				<div class="controls">
					<? $hasError = $this->form->id_tipo_carrera->hasErrors(); ?>
					<?php if (!$hasError && ($this->isLinkedin || $this->isEstudio)) { ?>
						<?php
						if ($this->form->id_nivel_estudio->getValue() != 1 &&
								$this->form->id_nivel_estudio->getValue() != 2 &&
								$this->form->id_nivel_estudio->getValue() != 3 &&
								$this->form->id_nivel_estudio->getValue() != 9) {
							?>
							<?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                        <?php } else { ?>
                            <?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
                        <?php } ?>
					<?php } else { ?>
						<?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
					<?php } ?>

					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_tipo_carrera->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group<?=$hideSinEstudios?>">
				<label for="" class="control-label"><em>*</em> Carrera:</label>
				<div class="controls">
					<? $hasError = $this->form->id_carrera->hasErrors(); ?>
					<?php
					if ($this->form->id_nivel_estudio->getValue() != 1 &&
							$this->form->id_nivel_estudio->getValue() != 2 &&
							$this->form->id_nivel_estudio->getValue() != 3 &&
							$this->form->id_nivel_estudio->getValue() != 9) {
						?>

						<?php if ($this->form->otro_carrera->getValue() == ''){ ?>
							<?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
	                    <?php } else { ?>
	                        <?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
	                    <?php } ?>
                    <?php } else { ?>
                        <?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
                    <?php } ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_carrera->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group<?=($this->form->id_carrera->getValue() == 15) ? '' : ' hide'; ?>">
				<label for="" class="control-label"><em>*</em> Descripci&oacute;n Carrera:</label>
				<div class="controls">
					<? $hasError = $this->form->otro_carrera->hasErrors(); ?>
					<?php if (in_array($this->form->id_carrera->getValue(),array(69,65,101,184,125,103,15,50,130,94,158,152,86,207,76))){ ?>
						<?= $this->form->otro_carrera->setAttribs(array('class' => 'input-xmedium require first_title', 'autocomplete' => 'off'))->renderViewHelper(); ?>
                    <?php } else { ?>
                        <?= $this->form->otro_carrera->setAttribs(array('class' => 'input-xmedium require', 'autocomplete' => 'off'))->renderViewHelper(); ?>
                    <?php } ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otro_carrera->errMsg : '' ?></span>
				</div>
			</div>
			<div class="cgroup-inline">
				<label for="" class="control-label"><em>*</em> Inicio:</label>
				<div class="control-group">
					<input type="hidden" value="<?= $this->form->inicio_mes->getValue() ?>/<?= $this->form->inicio_ano->getValue() ?>"/>
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
                                                <? $this->form->inicio_mes->setAttribs(array('disabled' => 'disabled'));?>
					<?php endif; ?>
                                        <?= $this->form->inicio_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
				</div>
				<div class="control-group">
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
                                                <? $this->form->inicio_ano->setAttribs(array('disabled' => 'disabled'));?>
					<?php endif; ?>
     					<?= $this->form->inicio_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<? $hasError = $this->form->inicio_ano->hasErrors(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->inicio_ano->errMsg : '' ?></span>
				</div>
			</div>
			<div class="cgroup-inline">
				<label for="" class="control-label"><em>*</em> Fin:</label>
				<div class="control-group">
					<input type="hidden" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
                                                <? $this->form->fin_mes->setAttribs(array('disabled' => 'disabled'));?>
					<?php endif; ?>
					<?php if ($this->form->en_curso->getValue() == 1) : ?>
						<?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall'))->setValue(date('n'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<?php endif; ?>
				</div>
				<div class="control-group">
					<input type="hidden" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
                                                <? $this->form->fin_ano->setAttribs(array('disabled' => 'disabled'));?>
					<?php endif; ?>
					<?php if ($this->form->en_curso->getValue() == 1) : ?>
						<?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall'))->setValue(date('Y'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<?php endif; ?>
				</div>
				<div class="control-group">
					<label class="ioption">
					<?php if ($this->form->id_nivel_estudio->getValue() == 1): ?>
                                                <? $this->form->en_curso->setAttribs(array('disabled' => 'disabled'));?>
					<?php endif; ?>
						<?= $this->form->en_curso->renderViewHelper(); ?>Actualmente estudiando
					</label>
					<? $hasError = $this->form->inicio_ano->hasErrors(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->fin_ano->errMsg : '' ?></span>
				</div>
			</div>

			<div class="hide">
				<?= $this->form->id_estudio; ?>
				<?= $this->form->is_disabled; ?>
			</div>
		</div>
	</li>
	<?php
}
?>