<?php
$ind = (isset($this->indice)) ? $this->indice : 'blank';

if ($this->form->id_Experiencia != null && $this->form->id_Experiencia->getValue() != '') {
    $dataRol = 'data-rol="' . $this->form->id_Experiencia->getValue() . '"';
}
if (isset($this->idPostulante)) {
    $dataRel = 'data-rel="' . $this->idPostulante . '"';
}
$dataInd = 'data-index="' . $ind . '"';
?>

<?php if ($this->form->is_disabled->getValue() ) { ?>
    <li <?= $dataRol ?> <?= $dataRel ?> <?= $dataInd ?>> 
        <?php if (isset($this->isLinkedin) && $this->isLinkedin==true || $this->isExperiencia === true) : ?>
            <?php if ($this->form->otro_puesto->getValue() != null && $this->form->otra_empresa->getValue() != null) { ?>
                <ul class="skill-title row">
                    <li><?php echo $ind + 1; ?>. </li>
                    <li>
                        <b><?php
                            if ($this->form->otro_puesto->getValue() == '') {
                                echo $this->escape($this->form->nombre_puesto->getValue());
                            } else {
                                echo $this->escape($this->form->otro_puesto->getValue());
                            }
                            ?> en 
                        </b>
                            <b><?= $this->escape($this->form->otra_empresa->getValue()); ?></b>
                    </li>
                    <li class="last">
                        <a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
                    </li>
                </ul>
        <?php } ?>
    <?php endif; ?>
    </li>
    <?php } else { ?>
    <li <?= (isset($dataRol) ? $dataRol : '') ?> <?= (isset($dataRel) ? $dataRel : '' ) ?> <?= $dataInd ?>> 
        <?php if (isset($this->isLinkedin) && $this->isLinkedin==true || $this->isExperiencia === true) : ?>
        <?php //if ($this->form->otro_puesto->getValue() != null && $this->form->otra_empresa->getValue() != null) {  ?>
        <?php if ($this->form->id_puesto->getValue() != "0") { ?>
                <ul class="skill-title row">
                    <li><?php echo $ind + 1; ?>. </li>
                    <li>
                        <?php if ($this->form->id_puesto->getValue() == 1292) { ?>
                            <b><?= $this->escape($this->form->otro_puesto->getValue()); ?></b> en 
                            <b><?= $this->escape($this->form->otra_empresa->getValue()); ?></b>
                        <?php } else { ?>
                            <b><?= $this->escape($this->form->id_puesto->getMultiOption($this->form->id_puesto->getValue())); ?></b> en 
                            <b><?= $this->escape($this->form->otra_empresa->getValue()); ?></b>
                    <?php } ?>
                    </li>
            <? //Estás seguro que deseas eliminar la experiencia seleccionada?<br> Si aceptas también se eliminarán tus referencias. ?>
                    <li class="last">
                        <a href="#Editar" class="action-icons edit" title="Editar"></a>
                        <a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
                    </li>
                </ul>
            <?php } ?>
    <?php endif; ?>
    <? $isError = $this->form->isErrors(); ?>

        <div class="skill-content<?= (!$isError && $this->isExperiencia === true) ? ' hide' : '' ?><?= $isError ? ' active' : '' ?>" >
            <div class="control-group">
                <label for="" class="control-label"><em>*</em> Empresa:</label>
                <div class="controls">
    <? $hasError = $this->form->otra_empresa->hasErrors(); ?>
    <?= $this->form->otra_empresa->setAttribs(array('class' => 'input-xmedium second_title require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otra_empresa->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group">
                <label for="" class="control-label no-req"><em>&nbsp;</em> Rubro/Industria:</label>
                <div class="controls">
    <?= $this->form->otro_rubro->setAttribs(array('class' => 'input-xmedium'))->renderViewHelper(); ?>
                </div>
            </div>
            <div class="control-group">
                <label for="" class="control-label"><em>*</em> Nombre del puesto:</label>
                <div class="controls">
                    <? $hasError = $this->form->id_puesto->hasErrors(); ?>
                    <?php if ($this->form->otro_puesto->getValue() != "") { ?>
                        <?= $this->form->id_puesto->setAttribs(array('class' => 'sel-medium require', 'data-title' => 'first_title'))->renderViewHelper(); ?>
                    <?php } else { ?>
                        <?= $this->form->id_puesto->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
                    <?php } ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_puesto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group<?= ($this->form->id_puesto->getValue() == Application_Model_Puesto::OTROS_PUESTO_ID) ? '' : ' hide'; ?>">
                <label for="" class="control-label"><em>*</em> Descripción del puesto:</label>
                <div class="controls">
                    <? $hasError = $this->form->otro_puesto->hasErrors(); ?>
                    <?php if ($this->form->otro_puesto->getValue() != "") { ?>
                        <?= $this->form->otro_puesto->setAttribs(array('class' => 'input-xmedium first_title require'))->renderViewHelper(); ?>
                    <?php } else { ?>
                        <?= $this->form->otro_puesto->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
                    <?php } ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otro_puesto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group">
                <label for="" class="control-label"><em>*</em> Nivel del puesto:</label>
                <div class="controls">
    <? $hasError = $this->form->id_nivel_puesto->hasErrors(); ?>
    <?= $this->form->id_nivel_puesto->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_puesto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group<?= ($this->form->id_nivel_puesto->getValue() == Application_Model_Puesto::OTROS_NIVEL_PUESTO_ID) ? '' : ' hide'; ?>">
                <label for="" class="control-label"><em>*</em> Descripción de nivel puesto:</label>
                <div class="controls">
    <? $hasError = $this->form->otro_nivel_puesto->hasErrors(); ?>
    <?= $this->form->otro_nivel_puesto->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otro_nivel_puesto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group">
                <label for="" class="control-label"><em>*</em> Area:</label>
                <div class="controls">
    <? $hasError = $this->form->id_area->hasErrors(); ?>
    <?= $this->form->id_area->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_area->errMsg : '' ?></span>
                </div>
            </div>
            <div class="cgroup-inline">
                <label class="control-label"><em>*</em> Lugar:</label>
    <?php $hasError = $this->form->lugar->hasErrors(); ?>
    <?php foreach ($this->form->lugar->getMultioptions() as $option => $value) { ?>
                    <div class="control-group">
                        <label class="ioption">
                            <input type='radio' name='managerExperiencia_<?= (isset($this->index))?$this->index:'blank' ?>_lugar' id='managerExperiencia_<?= (isset($this->index))?$this->index:'blank' ?>_lugar-<?= $option ?>' value='<?= $option ?>' <?= ($this->form->lugar->getValue() == $option) ? ' checked="checked"' : '' ?>><?= $value ?>
                        </label>
                    </div>
    <?php } ?>
                <div class="control-group">
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->lugar->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group<?= ($this->form->lugar->getValue() == 2) ? '' : ' hide'; ?>">
                <label for="" class="control-label"><em>*</em> Tipo de Proyecto:</label>
                <div class="controls">
    <? $hasError = $this->form->id_tipo_proyecto->hasErrors(); ?>
    <?= $this->form->id_tipo_proyecto->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_tipo_proyecto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group<?= ($this->form->lugar->getValue() == 2) ? '' : ' hide'; ?>">
                <label for="" class="control-label"><em>*</em> Nombre de la Obra/Proyecto:</label>
                <div class="controls">
    <? $hasError = $this->form->nombre_proyecto->hasErrors(); ?>
    <?= $this->form->nombre_proyecto->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->nombre_proyecto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group<?= ($this->form->lugar->getValue() == 2) ? '' : ' hide'; ?>">
                <label for="" class="control-label no-req"><em>&nbsp;</em> Costo de la Obra/Proyecto (<?php echo $this->moneda?>):</label>
                <div class="controls">
    <? $hasError = $this->form->costo_proyecto->hasErrors(); ?>
    <?= $this->form->costo_proyecto->setAttribs(array('class' => 'input-xsmall decimal'))->renderViewHelper(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->costo_proyecto->errMsg : '' ?></span>
                </div>
            </div>
            <div class="cgroup-inline">
                <label for="" class="control-label"><em>*</em> Inicio:</label>
                <div class="control-group">
                    <input type="hidden" value="<?= $this->form->inicio_mes->getValue() ?>/<?= $this->form->inicio_ano->getValue() ?>"/>
                    <?= $this->form->inicio_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
                </div>
                <div class="control-group">
    <?= $this->form->inicio_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
    <? $hasError = $this->form->inicio_ano->hasErrors(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->inicio_ano->errMsg : '' ?></span>
                </div>
            </div>
            <div class="cgroup-inline">
                <label for="" class="control-label"><em>*</em> Fin:</label>
                <div class="control-group">
                    <input type="hidden" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
                    <?php if ($this->form->en_curso->getValue() == 1) : ?>
                        <?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall', 'disabled' => 'disabled'))->setValue(date('n'))->renderViewHelper(); ?>
                    <?php else : ?>
        <?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
    <?php endif; ?>
                </div>
                <div class="control-group">
                    <input type="hidden" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
                    <?php if ($this->form->en_curso->getValue() == 1) : ?>
                        <?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall', 'disabled' => 'disabled'))->setValue(date('Y'))->renderViewHelper(); ?>
                    <?php else : ?>
        <?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
    <?php endif; ?>
                </div>
                <div class="control-group">
                    <label class="ioption">
                    <?= $this->form->en_curso->renderViewHelper(); ?>Actualmente trabajando
                    </label>
    <? $hasError = $this->form->inicio_ano->hasErrors(); ?>
                    <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->fin_ano->errMsg : '' ?></span>
                </div>
            </div>
            <div class="control-group">
                <label for="" class="control-label no-req"><em>&nbsp;</em> Descripci&oacute;n de tareas:</label>
                <div class="controls">
                    <?= $this->form->comentarios->setAttribs(array('rows' => '6', 'cols' => '60'))->renderViewHelper(); ?>
                    <span class="response"></span>
    <?php $cantComentario = 140 - strlen($this->form->comentarios->getValue()); ?>
                    <div class="count-letter">Te quedan <span id="count-char"><?= $cantComentario ?></span> de 140 caracteres</div>
                </div>
            </div>
            <div class="hide">
    <?= $this->form->id_Experiencia; ?>
    <?= $this->form->is_disabled; ?>
            </div>
        </div>
    </li>
    <?php
}
?>
