<?php
$ind = (isset($this->indice)) ? $this->indice : 'blank';

if($this->form->id_dominioIdioma != null &&  $this->form->id_dominioIdioma->getValue() != ''){
	$dataRol = 'data-rol="'.$this->form->id_dominioIdioma->getValue().'"';
}
if(isset($this->idPostulante)){
	$dataRel = 'data-rel="'.$this->idPostulante.'"';
} 
$dataInd = 'data-index="' . $ind . '"';
?>
<?php if ($this->form->is_disabled->getValue()) { ?>
<li <?= $dataRol?> <?= $dataRel?> <?= $dataInd ?>>
	<?php if ($this->isIdioma === false) : ?>
		<?php //if ($this->form->id_idioma->getValue() != "0" && $this->form->nivel_idioma->getValue() != "0") : ?>
			<ul class="skill-title row">
				<li><?php echo $ind + 1; ?>. </li>
				<li>
					<?php if ($this->form->id_idioma->getValue() != "0") : ?>
						<b><?= $this->escape($this->form->id_idioma->getMultiOption($this->form->id_idioma->getValue())); ?></b>
					<?php else : ?>
						<b><?= $this->escape($this->form->id_idioma->getMultiOption($this->form->cabecera_idioma->getValue())); ?></b>
					<?php endif; ?>
					nivel
					<?php if ($this->form->nivel_idioma->getValue() != "0") : ?>
						<b><?= $this->escape($this->form->nivel_idioma->getMultiOption($this->form->nivel_idioma->getValue())); ?></b>
					<?php else : ?>
						<b><?= $this->escape($this->form->nivel_idioma->getMultiOption($this->form->cabecera_nivel->getValue())); ?></b>
					<?php endif; ?>
				</li>
				<li class="last">
					<a href="#Editar" class="action-icons edit" title="Editar"></a>
					<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
				</li>
			</ul>
		<?php //endif; ?>
    <?php endif; ?>
    </li>
<?} else {
	?>
	<li <?= isset($dataRol) ? $dataRol : '' ?> <?= isset($dataRel) ? $dataRel : '' ?> <?= $dataInd ?>>
		<?php if ($this->isIdioma === false) : ?>
                    <?php if ($this->form->id_idioma->getValue() != "0" && $this->form->nivel_idioma->getValue() != "0") : ?>
			<ul class="skill-title row">
				<li><?php echo $ind + 1; ?>. </li> 
				<li><?php if ($this->form->id_idioma->getValue() != "0" ) : ?>
						<b><?= $this->escape($this->form->id_idioma->getMultiOption($this->form->id_idioma->getValue())); ?></b>
					<?php endif; ?>
					 nivel 
					<?php if ($this->form->nivel_idioma->getValue() != "0") : ?>
						<b><?= $this->escape($this->form->nivel_idioma->getMultiOption($this->form->nivel_idioma->getValue())); ?></b>
					<?php endif; ?>
				</li> 
				<li class="last">
					<a href="#Editar" class="action-icons edit" title="Editar"></a>
					<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
				</li>
			</ul>
                            <?php endif; ?>
		<?php endif; ?>
		<? $isError = $this->form->isErrors(); ?>
		<div class="skill-content<?= ($isError || !isset($this->isIdioma) || $this->isIdioma == true) ? '' : ' hide' ?><?= $isError ? ' active' : '' ?>">
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Idioma:</label>
				<div class="controls">
					<? $hasError = $this->form->id_idioma->hasErrors(); ?>
					<?= $this->form->id_idioma->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_idioma->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Nivel:</label>
				<div class="controls">
					<? $hasError = $this->form->nivel_idioma->hasErrors(); ?>
					<?= $this->form->nivel_idioma->setAttribs(array('class' => 'sel-medium second_title require'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->nivel_idioma->errMsg : '' ?></span>
				</div>
			</div>
            <div class="hide">
                   <?= $this->form->id_dominioIdioma; ?>
                   <?= $this->form->cabecera_idioma; ?>
                   <?= $this->form->cabecera_nivel; ?>
                   <?= $this->form->is_disabled; ?>
           </div>
		</div>
	</li>
<?php } ?>