<?php
$ind = (isset($this->indice)) ? $this->indice : 'blank';

if($this->form->id_estudio != null &&  $this->form->id_estudio->getValue() != ''){
	$dataRol = 'data-rol="'.$this->form->id_estudio->getValue().'"';
}
if(isset($this->idPostulante)){
	$dataRel = 'data-rel="'.$this->idPostulante.'"';
} 
$dataInd = 'data-index="' . $ind . '"';
?>
<?php if ($this->form->is_disabled->getValue()) { ?>
	<li <?= $dataRol?> <?= $dataRel?> <?= $dataInd ?>>
		<?php if ($this->isOtroEstudio === false) { ?>
			<?php if ($this->form->id_nivel_estudio_tipo->getValue() != null && $this->form->id_nivel_estudio_tipo->getValue() != "0") : ?>
				<ul class="skill-title row">
					<li><?php echo $ind + 1; ?>. </li>
					<li> <b><?= $this->escape($this->form->otro_estudio->getValue()); ?></b> en <b><?= $this->escape($this->form->institucion->getValue()); ?></b>
					</li>
					<li class="last">
						<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
					</li>
				</ul>
			<?php endif; ?>
		<?php } ?>
	</li>
	<?php
} else { 
	?>
	<li <?= isset($dataRol) ? $dataRol: '' ?> <?= isset($dataRel) ? $dataRel : ''?> <?= $dataInd ?>>
		<?php if ($this->isOtroEstudio === false) {?>
			<?php if ($this->form->id_nivel_estudio_tipo->getValue() != "0" && $this->form->otro_estudio->getValue() != "" && $this->form->institucion->getValue() != "") : ?>
				<ul class="skill-title row">
					<li><?php echo $ind + 1; ?>. </li>
					<li><b><?= $this->escape($this->form->otro_estudio->getValue()); ?></b> en <b><?= $this->escape($this->form->institucion->getValue()); ?></b>
					</li>
					<li class="last">
						<a href="#Editar" class="action-icons edit" title="Editar"></a>   
						<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
					</li>
				</ul>
			<?php endif; ?>
		<?php } ?>
		<? $isError = $this->form->isErrors(); ?>
		<div class="skill-content<?= ($isError || !isset($this->isOtroEstudio) || $this->isOtroEstudio == true) ? '' : ' hide' ?><?= $isError ? ' active' : '' ?>">
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Tipo de Estudio:</label>
				<div class="controls">
					<? $hasError = $this->form->id_nivel_estudio_tipo->hasErrors(); ?>
					<?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_estudio_tipo->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Nombre:</label>
				<div class="controls">
					<? $hasError = $this->form->otro_estudio->hasErrors(); ?>
					<?= $this->form->otro_estudio->setAttribs(array('class' => 'input-xmedium first_title require'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otro_estudio->errMsg : '' ?></span>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> Nombre de la institución:</label>
				<div class="controls">
					<? $hasError = $this->form->institucion->hasErrors(); ?>
					<?= $this->form->institucion->setAttribs(array('class' => 'input-xmedium second_title require', 'autocomplete' => 'off'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->institucion->errMsg : '' ?></span>
					<?= $this->form->id_institucion->setAttribs(array('class' => ' insClvInst')) ?>
				</div>
			</div>
			<div class="control-group">
				<label for="" class="control-label"><em>*</em> País:</label>
				<div class="controls">
					<? $hasError = $this->form->pais_estudio->hasErrors(); ?>
					<?= $this->form->pais_estudio->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->pais_estudio->errMsg : '' ?></span>
				</div>
			</div>
			<div class="cgroup-inline">
				<label for="" class="control-label"><em>*</em> Inicio:</label>
				<div class="control-group">
					<input type="hidden" class="iptDVar iptInicio" value="<?= $this->form->inicio_mes->getValue() ?>/<?= $this->form->inicio_ano->getValue() ?>"/>
					<?= $this->form->inicio_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
				</div>
				<div class="control-group">
					<?= $this->form->inicio_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<? $hasError = $this->form->inicio_ano->hasErrors(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->inicio_ano->errMsg : '' ?></span>
				</div>
			</div>
			<div class="cgroup-inline">
				<label for="" class="control-label"><em>*</em> Fin:</label>
				<div class="control-group">
					<input type="hidden" class="iptDVar iptFin" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
					<?php if ($this->form->en_curso->getValue() == 1) : ?>
						<?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall', 'disabled' => 'disabled'))->setValue(date('n'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->fin_mes->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<?php endif; ?>
				</div>
				<div class="control-group">
					<input type="hidden" class="iptDVar iptFin" value="<?= $this->form->fin_mes->getValue() ?>/<?= $this->form->fin_ano->getValue() ?>" />
					<?php if ($this->form->en_curso->getValue() == 1) : ?>
						<?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall', 'disabled' => 'disabled'))->setValue(date('Y'))->renderViewHelper(); ?>
					<?php else : ?>
						<?= $this->form->fin_ano->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
					<?php endif; ?>
				</div>
				<div class="control-group">
					<label class="ioption">
						<?= $this->form->en_curso->renderViewHelper(); ?>Actualmente estudiando
					</label>
					<? $hasError = $this->form->inicio_ano->hasErrors(); ?>
					<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->fin_ano->errMsg : '' ?></span>
				</div>
			</div>
			<div class="hide">
				<?= $this->form->id_estudio; ?>
				<?= $this->form->is_disabled; ?>
                                <?= $this->form->id_nivel_estudio->renderViewHelper(); ?>
			</div>
		</div>
	</li>
	<?php
}
?>