<div class="wrap-controls">
    <div id="divWrapFile" class="control-group">
        <label for="fPhoto" class="control-label no-req">Fotografía:
            <br/><br/>
            <p class="txt_small">Tamaño máximo <?php echo $this->config->formatSize?></p>
            <p class="txt_small">Formatos permitidos: JPG, PNG</p>
            <p class="txt_small">Los archivos no deben medir<br/> más de 640px X 480px</p>
        </label>
        <div class="controls">
            <?php 
            $dataFile = '';
            if ($this->imgPhoto != '')
                    $dataFile = ' data-exits="1"';
            ?>
            <div id="divImage" class="img-upload center-img">
                <img src="<?=($this->imgPhoto == '') ? $this->S('/images/profile-default.jpg') : ELEMENTS_URL_IMG . $this->imgPhoto . "?" . time();?>" alt="Foto de Perfil" />
            </div>
            <?php if ($this->modulo != 'admin') { ?>
            <div class="img-actions">
                <input type="hidden" name="filesize" value="<?php echo $this->config->app->maxSizeFile?>" id="MAX_FILE_SIZE">
                <input type="hidden" name="tipo" value="pos">
                <a id="divDelFot" href="javascript:;" title="Eliminar foto" <?=$dataFile?> data-rel="<?= $this->idPostulante ?>" class="icon-trash <?= (isset($this->imgPhoto) && $this->idPostulante != null && $this->idPostulante == '') || $this->imgPhoto != '' ? '' : 'hide' ?>"></a>

                <input type="file" name="path_foto" id="txtLogo" class="medium">
                <?php if ($this->modulo != 'admin') { ?>
                <? $hasError = $this->formPostulante->path_foto->hasErrors(); ?>
                <?php } ?>
                <br>
                <span class="response <?= isset($hasError) ? ' bad' : '' ?>"><?= isset($errMsg)  ? $errMsg : '' ?></span>
            </div>
            <?php } ?>
        </div>
    </div>
    <div class="control-group">
        <label for="fNames" class="control-label"><em>*</em> Nombres:</label>
        <?
        $hasError = $this->formPostulante->nombres->hasErrors();
        ?>
        <div class="controls">
            <?=$this->formPostulante->nombres->setAttribs(array(
                'id' => 'fNames', 'class' => 'input-xmedium', 'tabindex' => '5','required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-minlength'=>'2', 'data-parsley-maxlength'=>'80', 'maxlength'=>80, 'data-parsley-pattern'=>'/^[a-zA-ZáéíóúÁÉÍÓÚñÑäëïöüÿÄËÏÖÜ ]+$/gi'))->renderViewHelper();?>
        </div>
        
    </div>
    <div class="control-group">
        <label for="fLastnameP" class="control-label"><em>*</em> Apellido Paterno:</label>
        <?
        $hasError = $this->formPostulante->apellido_paterno->hasErrors();
        ?>
        <div class="controls">
            <?=
            $this->formPostulante->apellido_paterno->setAttribs(array(
                'id' => 'fLastnameP', 'class' => 'input-xmedium', 'tabindex' => '6','required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-minlength'=>'2', 'data-parsley-maxlength'=>'50', 'maxlength'=>50, 'data-parsley-pattern'=>'/^[a-zA-ZáéíóúÁÉÍÓÚñÑäëïöüÿÄËÏÖÜ ]+$/gi'))->renderViewHelper();
            ?> 
        </div>
        
    </div>
    <div class="control-group">
        <label for="fLastnameM" class="control-label"><em>*</em> Apellido Materno:</label>
        <?
        $hasError = $this->formPostulante->apellido_materno->hasErrors();
        ?>
        <div class="controls">
            <?=
            $this->formPostulante->apellido_materno->setAttribs(array(
                'id' => 'fLastnameM', 'class' => 'input-xmedium', 'tabindex' => '6','required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-minlength'=>'2', 'data-parsley-maxlength'=>'50', 'maxlength'=>50, 'data-parsley-pattern'=>'/^[a-zA-ZáéíóúÁÉÍÓÚñÑäëïöüÿÄËÏÖÜ ]+$/gi'))->renderViewHelper();
            ?>    
        </div>
        
    </div>
    <div class="cgroup-inline">
        <label for="selDay" class="control-label"><em>*</em> Fecha de nacimiento:</label>
        <?=$this->formPostulante->fecha_nac->setAttribs(array(
            'id' => 'hidBirthDate'))->renderViewHelper();
        ?>
        <?php $fechaNac = $this->formPostulante->fecha_nac->getValue();
        if (!empty($fechaNac)) {
            $fechaNac = explode('/', $fechaNac);
            $dia = $fechaNac[0];$mes = $fechaNac[1];$ano = $fechaNac[2]; }?>
        
        <div class="control-group parsley_message_bottom">
            <select name="selDia" required data-parsley-trigger="change" data-parsley-error-message="Requerido">
                <option value="">-- Día --</option>
                <?php for ($i = 1; $i<=31; $i++) { 
                    if (!empty($fechaNac)) {
                        if ($dia == $i) { ?>
                        <option value="<?=$i?>" selected><?=$i?></option>    
                        <?php } else { ?>
                        <option value="<?=$i?>"><?=$i?></option>    
                        <?php } ?>
                <?php } else { ?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php } ?>
                <?php } ?>
            </select>
        </div>
        <div class="control-group parsley_message_bottom">
            <select name="selMes" required data-parsley-trigger="change" data-parsley-error-message="Requerido">
                <option value="">-- Mes --</option>
                <?php foreach ($this->mes as $key => $value) { ?>
                <?php if (!empty($fechaNac)) {
                if ($mes == $key) { ?>
                        <option value="<?=$key?>" selected><?=$value?></option>    
                        <?php } else { ?>
                        <option value="<?=$key?>"><?=$value?></option>
                        <?php } ?>
                <?php } else { ?>
                <option value="<?=$key?>"><?=$value?></option>
                <?php } ?>
                <?php } ?>    
            </select>
        </div>
        <div class="control-group parsley_message_bottom">
            <select name="selAnio" required data-parsley-trigger="change" data-parsley-error-message="Requerido">
                <option value="">-- Año --</option>
                <?php for ($i = 1910; $i<=1996; $i++) {?>
                <?php if (!empty($fechaNac)) {
                if ($ano == $i) { ?>
                        <option value="<?=$i?>" selected><?=$i?></option>    
                        <?php } else { ?>
                        <option value="<?=$i?>"><?=$i?></option>    
                        <?php } ?>
                <?php } else { ?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php } ?>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="cgroup-inline">
        <label class="control-label"><em>*</em> Sexo:</label>     
        <div class="control-group">
            <label class="ioption">
              <input type="radio" value="M" <?=(isset($this->sexo) && $this->sexo=='M')?'checked="checked"':''?> name="sexoMF" >Masculino</label>
        </div>
        <div class="control-group">
            <label class="ioption">
                <input type="radio" value="F" <?=(isset($this->sexo) && $this->sexo=='F')?'checked="checked"':''?>  name="sexoMF">Femenino</label>
        </div>
    </div>
    <div class="control-group">
        <label for="txtDocument" class="control-label"><em>*</em> Documento de Identidad:</label>
        <div class="cgroup-inline">
            <div class="control-group parsley_message_bottom">
                <?=
                $this->formPostulante->tipo_doc->setAttribs(array(
                    'id' => 'fSelDoc', 'class' => ''))->renderViewHelper();
                ?>
            </div>
            <?php $dni = substr($this->formPostulante->tipo_doc->getValue(),0,1)  ?>
            <div class="control-group last">
                
                <?php if (is_null($dni) || $dni == "d" || empty($dni)) { ?>
                <?=$this->formPostulante->num_doc->setAttribs(array('id' => 'txtDocument', 'class' => 'input-xxmiddle number input-w97', 'data-rel' => $this->idPostulante, 'required' => '', 'data-parsley-trigger' => 'change', 'data-parsley-type' => 'number', 'required' => '', 'data-parsley-errors-container'=>'#responseDni', 'minlength' => '8', 'data-parsley-minlength' => '8','data-parsley-minlength-message' => 'El CI debe ser de 8 dígitos', 'maxlength' => '8'))->renderViewHelper();?>
                <?php } else { ?>
                <?=$this->formPostulante->num_doc->setAttribs(array('id' => 'txtDocumentCe', 'class' => 'input-xxmiddle input-w97', 'data-rel' => $this->idPostulante, 'required' => '', 'data-parsley-trigger' => 'change', 'data-parsley-type' => 'alphanum', 'required' => '', 'data-parsley-errors-container'=>'#responseDni', 'minlength' => '1', 'data-parsley-minlength' => '8','data-parsley-minlength-message' => 'Ingrese carné de extranjería válido','data-parsley-type-message' => 'Ingrese carné de extranjería válido','maxlength' => '12'))->renderViewHelper();?>
                <?php } ?>
                <div class="parsley_info" id="responseDni"></div>
                
            </div>
        </div>
    </div>
    <!-- Telefonos Fijos / celulare -->
    <div class="control-group">
        <label for="fTlfFC2" class="control-label no-req">Teléfono fijo:</label>
        <div class="controls">
            <?
            $hasError = $this->formPostulante->telefono->hasErrors();
            ?>
            <?=
            $this->formPostulante->telefono->setAttribs(array(
                'id' => 'fTlfFC2', 'class' => 'input-xmedium number', 'data-parsley-type' => 'number'))->renderViewHelper();
            ?>
            <span class="response cGray left<?= $hasError ? ' bad' : ''
            ?>"><?= $hasError ? $this->formPostulante->telefono->errMsg : ''
            ?> </span> 
        </div>
    </div>
    <div class="control-group">
        <label for="fTlfFC" class="control-label no-req" >Teléfono celular:</label>
        <div class="controls">
            <?
            $hasError = $this->formPostulante->celular->hasErrors();
            ?>
            <?=
            $this->formPostulante->celular->setAttribs(array(
                'id' => 'fTlfFC', 'class' => 'input-xmedium number', 'data-parsley-type' => 'number'))->renderViewHelper();
            ?>
            <span class="response cGray left<?= $hasError ? ' bad' : ''
            ?>"><?= $hasError ? $this->formPostulante->celular->errMsg : ''
            ?> </span>
        </div>
    </div>
    <div class="control-group">
        <label for="fEstCvil" class="control-label no-req">Estado civil:</label>
        <div class="controls">
            <?=
            $this->formPostulante->estado_civil->setAttribs(array(
                'id' => 'fEstCvil', 'class' => 'sel-medium'))->renderViewHelper();
            ?>
            <span class="response cGray left"> </span> 
        </div>
    </div>
</div>
<div class="wrap-controls">
    <div class="control-group">
        <label for="fPais" class="control-label"><em>*</em> País:</label>
        <div class="controls">
            <?
            $hasError = $this->formPostulante->pais_residencia->hasErrors();
            ?>
            <?=
            $this->formPostulante->pais_residencia->setAttribs(array(
                'id' => 'fPais', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'rel' => Application_Model_Ubigeo::PERU_UBIGEO_ID, 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();
            ?>
            <span class="response cGray left<?= $hasError ? ' bad' : ''
            ?>"><?= $hasError ? $this->formPostulante->pais_residencia->errMsg : ''
            ?> </span>
        </div>
    </div>
    <div class="control-group">
        <label for="fDepart" class="control-label"><em>*</em> Departamento:</label>
        <div class="controls">
            <?
            $hasError = $this->formPostulante->id_departamento->hasErrors();
            ?>
            <?php if ($this->formPostulante->pais_residencia->getValue() == Application_Model_Ubigeo::PERU_UBIGEO_ID) { ?>
            <?=$this->formPostulante->id_departamento->setAttribs(array('id' => 'fDepart', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'rel' => Application_Model_Ubigeo::LIMA_UBIGEO_ID, 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
            <?php } else { ?>
            <?=$this->formPostulante->id_departamento->setAttribs(array('disabled'=>'', 'id' => 'fDepart', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'rel' => Application_Model_Ubigeo::LIMA_UBIGEO_ID, 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
            <?php } ?>
            <span class="response cGray left<?= $hasError ? ' bad' : ''
            ?>"><?= $hasError ? $this->formPostulante->id_departamento->errMsg : ''
            ?></span>
        </div>
    </div>
    <div class="control-group">
        <label for="fProvin" class="control-label"><em>*</em> Provincia:</label>
        <div class="controls">
        
        <?php if ($this->formPostulante->id_departamento->getValue() == Application_Model_Ubigeo::LIMA_UBIGEO_ID) { ?>
        <?=$this->formPostulante->id_provincia->setAttribs(array('id' => 'fProvin', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'rel' => Application_Model_Ubigeo::LIMA_PROVINCIA_UBIGEO_ID, 'data-callao' => Application_Model_Ubigeo::CALLAO_PROVINCIA_UBIGEO_ID, 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
        <?php } else { ?>
        <?=$this->formPostulante->id_provincia->setAttribs(array('disabled' =>'','id' => 'fProvin', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'rel' => Application_Model_Ubigeo::LIMA_PROVINCIA_UBIGEO_ID, 'data-callao' => Application_Model_Ubigeo::CALLAO_PROVINCIA_UBIGEO_ID, 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
        <?php } ?>      
            
        </div>
    </div>
    <div class="control-group">
        <label for="fDistri" class="control-label"><em>*</em> Distrito:</label>
        <div class="controls">
        
        <?php if ($this->formPostulante->id_provincia->getValue() == Application_Model_Ubigeo::LIMA_PROVINCIA_UBIGEO_ID) { ?>
        <?=$this->formPostulante->id_distrito->setAttribs(array('id' => 'fDistri', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
        <?php } else { ?>
        <?=$this->formPostulante->id_distrito->setAttribs(array('disabled' => '','id' => 'fDistri', 'class' => 'sel-medium', 'required' => '', 'pattern' => '[1-9]', 'data-parsley-excluded' => '[disabled]'))->renderViewHelper();?>
        <?php } ?>    
        
        </div>
    </div>
    <!--
    <div class="cgroup-inline">
        <label class="control-label no-req"><em> </em> Estoy disponible para trabajar en provincia/extranjero:</label>
        <div class="control-group">
            <label class="ioption">
                <?=
                $this->formPostulante->disponibilidad_provincia_extranjero->setAttribs(array(
                    'id' => 'chkWorkWorld', 'class' => 'mT10'))->renderViewHelper();
                ?>
            </label>
        </div>
    </div>-->
</div>
<!--
<div class="wrap-controls">
    <div class="control-group">
        <label for="txtUrl" class="control-label no-req">Tu página web:</label>
        <div class="controls">
            <?= $this->formPostulante->website->setAttribs(array('id' => 'txtUrl', 'class' => 'input-xmedium', 'placeholder' => 'http://', 'data-parsley-trigger'=>'change', 'data-parsley-errors-container'=>'#responseUrl', 'data-parsley-type' => 'url'))->renderViewHelper(); ?>
            <div class="parsley_info" id="responseUrl"><div class="txt_small">Te recomendamos que ingreses una web que hable mejor de tu lado profesional.</div></div>
        </div>        
    </div>
</div>
<div class="wrap-controls">
    <div class="control-group">
        <label for="txtAboutForYou" class="control-label no-req">Acerca de ti:</label>
        <div class="controls">
            <?=
            $this->formPostulante->presentacion->setAttribs(array(
                'id' => 'txtAboutForYou', 'class' => 'input-xmedium', 'rows' => '7',
                'cols' => '61', 'tabindex' => '20', 'placeholder' => 'Escribe una breve descripción sobre tu experiencia profesional', 'data-parsley-trigger'=>'change', 'maxlength' => '750', 'data-parsley-errors-container'=>'#responseAboutForYou'))->renderViewHelper();
            ?>
            <div class="parsley_info" id="responseAboutForYou"><div class="txt_small">Te recomendamos que escribas una descripción que complemente tu experiencia profesional.<br>
            <?=$hasError ? $this->formPostulante->presentacion->errMsg : 'Ingrese máximo 750 caracteres.'?>
            </div></div>
            <div class="count-letter">Te quedan <span id="count-char">750</span> de 750 caracteres</div>
        </div>
             
    </div>
</div>
-->
