<?php  
$ind = (isset($this->indice)) ? $this->indice : 'blank';

if($this->form->id_referencia != null &&  $this->form->id_referencia->getValue() != ''){
	$dataRol = 'data-rol="'.$this->form->id_referencia->getValue().'"';
}
if(isset($this->idPostulante)){
	$dataRel = 'data-rel="'.$this->idPostulante.'"';
}
$dataInd = 'data-index="' . $ind . '"';
?>
<li <?= isset($dataRol) ? $dataRol : ''?> <?= isset($dataRel) ? $dataRel : ''?> <?= $dataInd ?>>
	<?php if (isset($this->isLinkedin) || $this->isReferencia == true) { ?>
		<ul class="skill-title row">
			<li><?php echo $ind + 1; ?>. </li>
			<li><b><?=$this->escape($this->form->nombre->getValue()); ?></b> es <b><?=$this->escape($this->form->cargo->getValue()); ?></b>
			</li>
			<li class="last">
				<a href="#Editar" class="action-icons edit" title="Editar"></a>
				<a href="javascript:;" class="action-icons delete" title="Eliminar"></a>
			</li>
		</ul>
	<?php } ?>
	<?$isError = $this->form->isErrors(); ?>
	<div class="skill-content<?=(!$isError && $this->isReferencia)?' hide':''?><?=$isError? ' active':'' ?>" >
		<div class="control-group">
			<label for="" class="control-label"><em>*</em> Experiencia:</label>
			<div class="controls">
				<? $hasError = $this->form->listaexperiencia->hasErrors(); ?>
				<?= $this->form->listaexperiencia->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->listaexperiencia->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label"><em>*</em> Nombre:</label>
			<div class="controls">
				<? $hasError = $this->form->nombre->hasErrors(); ?>
				<?= $this->form->nombre->setAttribs(array('class' => 'input-xmedium second_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->nombre->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label"><em>*</em> Puesto:</label>
			<div class="controls">
				<? $hasError = $this->form->cargo->hasErrors(); ?>
				<?= $this->form->cargo->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->cargo->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label"><em>*</em> Telefono:</label>
			<div class="controls">
				<? $hasError = $this->form->telefono->hasErrors(); ?>
				<?= $this->form->telefono->setAttribs(array('class' => 'number input-xmedium require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->telefono->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Telefono 2:</label>
			<div class="controls">
				<? $hasError = $this->form->telefono2->hasErrors(); ?>
				<?= $this->form->telefono2->setAttribs(array('class' => 'number input-xmedium require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->telefono2->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Email:</label>
			<div class="controls">
				<? $hasError = $this->form->email->hasErrors(); ?>
				<?= $this->form->email->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->email->errMsg : '' ?></span>
			</div>
		</div>
		<div class="hide">
			<?=$this->form->id_referencia;?>
		</div>
	</div>
</li>
