<?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
<section class="interests_box">
   <form  action="<?=$this->url(array( 'controller' => 'registro', 'action' => 'paso3'), false, true)?>"  method="post" autocomplete="off" id="frmPrincipal" class="type1">
    <div class="center_box">
      <div class="register_title row">
        <div class="step_wrapper">
          <div class="step"><span>1</span></div>
          <div class="step"><span>2</span></div>
          <div class="step select_step"><span>3</span></div>
          <div class="step_line"></div>
        </div>
        <div class="step3_autocomplete">
          <div class="step3_title">
            <h3>Dinos cuáles son tus aptitudes</h3>
            <p>(Tienes un máximo de 10)</p>
            <div class="step3_skills_container">
              <div class="step3_skills_text">Ingresa una habilidad que consideres conocer</div>
              <div class="step3_skills_mini_form">
                <fieldset <?=  count($this->getAreaInteres['aptitudes'])>9?'disabled="disabled"':''?>>
                  <input type="text" id="txtSkillField" maxlength="60"  <?=  count($this->getAreaInteres['aptitudes'])>9?'disabled="disabled"':''?>/>
                  <button type="button" class="btn btn_add_skill" disabled="disabled">+</button>
                </fieldset>
                <div class="step3_skills_example">Ejm: Ofimática, Javascript, Google Analytics</div>
              </div>
            </div>
            <div class="step3_skills_selected_container">
            <?php if(isset($this->getAreaInteres["aptitudes"])){  ?>
                <?php foreach ($this->getAreaInteres["aptitudes"] as $key) { ?>
                <div class="step3_skills_selected_item" data-value="<?=$key['mostrar']?>" data-id="<?=$key['id']?>">
                  <label><?=$key['mostrar']?></label>
                  <span class="close_skills"><i class="icon icon_cross"></i></span>
                  <input type="hidden" value="<?=$key['id']?>" name="aptitudes[]">
                </div>
                <?php } ?>
            <?php } ?>
            </div>
          </div>
          <div class="step3_title">
            <h3>Pretensiones Salariales</h3>
            <p>(Dinos cuál es el rango de salario bruto adecuado a tus niveles y áreas seleccionadas)</p>
            <div class="container_slider" id="containerSlider">
              <img  id="loadingSlider" class="loading_slider" alt="Cargando..." height="32" width="32" src="<?=$this->S('/main/img/ajax-transparent-loader.gif');?>"/>
              <div id="sliderLoaded" class="hide">
                <div id="salarySlider"></div>
                <div class="min_salary"></div>
                <div class="max_salary"></div>
                <div class="salary_selected">de <span class="min_salary_selected"></span>, <span class="max_salary_selected"></span> mensuales</div>
                <div class="tooltip_salary_too_high hide">
                  <div class="message_salary">El rango ingresado está muy por encima del promedio, te aconsejamos modificarlo para que puedas tener sugerencias más precisas.
                    <div class="arrow"></div>
                  </div>
                </div>
              </div>
            </div>            
            <?=$this->form->txtremuneracion->setAttribs(array('id'=>'txtremuneracion'))->renderViewHelper();?>
          </div>
          <div class="step3_title step3_field_ubigeo">
            <h3>Selecciona una ubicación</h3>
            <p>(Selecciona la ubicación deseada para un puesto de trabajo. Tienes un máximo de 8)</p>
            <div class="step3_locations_container">
              <div class="step3_locations_mini_form">
                <fieldset <?=count($this->getAreaInteres['location'])>7?'disabled="disabled"':''?>>
                    <input type="text" id="txtUbicacion" name="txtUbicacion" maxlength="60" <?=  count($this->getAreaInteres['location'])>7?'disabled="disabled"':''?>/>
                  <?php /*
                  <button type="button" class="btn btn_add_locations" disabled="disabled">+</button>
                  */ ?>
                </fieldset>
              </div>
            </div>
            <div class="step3_locations_selected_container">
             <?php if($this->getAreaInteres['location']  && is_array($this->getAreaInteres['location'])  ) {?>   
              <?php foreach ($this->getAreaInteres['location'] as $key => $value) { ?>
                <div class="step3_locations_selected_item">
                    <label><?=$value['nombre']?></label>
                    <span class="close_location">X</span>
                    <input type="hidden" value="<?=$value['id']?>" name="ubigeo[]">
                 </div>
              <?php      }?>   
              <?php } ?>   
            </div>
          </div>         
        </div>
      </div>
    </div>
    <div class="step3_next">
        <?=$this->form->tokenhiden->setAttribs(array('id'=>'tokenhiden'))->renderViewHelper();?>
        <a class="btn btn_continuar"><span>Continuar</span><i></i></a>
     </div>
    </form>      
</section>
<script type='text/template' id="tplItemSkill">
  <div class='<%= classItem %>' data-value="<%= value %>" data-id="<%= id %>">
    <label><%= value %></label>
    <span class='<%= classClose %>'><i class="icon icon_cross"></i></span>
    <% if(id==''){ %>
      <input type="hidden" value="<%= value %>" name="aptitudes[]">
    <% }else{ %>
      <input type="hidden" value="<%= id %>" name="aptitudes[]">
    <% } %>
  </div>
</script>

<script type='text/template' id="tplItemLocation">
  <div class='<%= classItem %>' data-value="<%= value %>" data-id="<%= id %>">
    <label><%= value %></label>
    <span class='<%= classClose %>'>X</span>
    <% if(id==''){ %>
      <input type="hidden" value="<%= value %>" name="ubigeo[]">
    <% }else{ %>
      <input type="hidden" value="<%= id %>" name="ubigeo[]">
    <% } %>
  </div>
</script>
<?php 
$minCurrentSalario = isset($this->getAreaInteres['price1_punto']) ? $this->getAreaInteres['price1_punto'] : $this->salariosDefault[0];
$maxCurrentSalario = isset($this->getAreaInteres['price2_punto']) ? $this->getAreaInteres['price2_punto'] : $this->salariosDefault[1];
$this->HeadScript()->prependScript('yOSON.minCurrentInterval='.$minCurrentSalario.';yOSON.maxCurrentInterval='.$maxCurrentSalario.';');
?>