<?=$this->partial('_partials/_new_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
<section class="select_interest_wrapper">
	<div class="center_box">
		<div class="register_title row">
			<div class="step_wrapper">
				<div class="step"><span>1</span></div>
				<div class="step select_step"><span>2</span></div>
				<div class="step"><span>3</span></div>
				<div class="step_line"></div>
			</div>
			<div class="tittle_wrapper">
				<div class="title_select_interest"> 
					<p>Selecciona las áreas de tu interés</p>
					<p>(puedes seleccionar un máximo de 3 áreas)</p>
				</div>
			</div>
		</div>
		<div class="choose_area_box">
			<form method="post">
				<div class="row jobs_area_wrapper">
				 <?php foreach($this->areas as $area) : ?>
                                    <div class="job_area <?=(isset($area['selected']) ? 'active':'') ?>" id="item_<?=$area['id']?>" data-area="<?=$area['id'].'_'.$area['slug']?>" data-area-id="<?=$area['id']?>" >
						<i class="icon icon_check2"></i>
						<div class="image" title="<?=$area['nombre']?>"><img alt="<?=$area['nombre']?>" src="<?=$this->S('/eb/svg/icons-areas/'.$this->NombreArea($area['slug']).'.svg')?>"></div>
						<div class="information_area">
                                                <?php                                                        
                                                    if( $area['id'] == 39 ) {
                                                       $txt_nombre = str_ireplace('y publicas', 'y pub', $area['nombre']);
                                                    }else {
                                                        $txt_nombre = $area['nombre'];
                                                    }
                                                ?>                                                     
							<h4 title="<?=$area['nombre']?>" > <?=(strlen($txt_nombre) > 29) ? substr($txt_nombre, 0, 29) . '...' : $txt_nombre;?> </h4>
							 <?php 
                                                             $nivel='';
                                                             $nivelPint='';
                                                          if (isset($area['selected']) && count($area['selected'])>0) { 
                                                            foreach ($area['selected'] as $key => $value) { 
                                                                $nombre = $value['name'];
                                                                $nombre = $this->Util()->NombreArea($nombre);
                                                                $nivelPint.=$nombre.' , ';
                                                                $nivel.=$value['id'].'_'.$value['name'].',';
                                                            } 
                                                          }
                                                          ?>
                                                        <div class="nivel_text">                                                           
                                                             <?= '<p>'.substr($nivelPint, 0, -2).'</p>'; ?>                                                            
                                                        </div>                                                     
                                                         
						</div>
						<div class="mask"></div>
                                
                                <?php if (isset($area['selected']) && count($area['selected']) > 0) { ?>
                                        <input class="hid_nivel_selected" type="hidden" value="<?=substr($nivel, 0, -1) ?>" name="niveles[]">                                        
                                        <input class="hid_area_selected" type="hidden" value="<?=$area['id'].'_'.$area['slug']?>" name="areas[]">                                       
                                <?php } ?>
					</div>
					<?php endforeach;?>
				</div>
				<div class="align_right mb30">
						<button type="submit" value="Contuinar" class="btn btn_cuaternary">Continuar</button>
				</div>
                            
                            <input type="hidden" name="hash" value="<?=$this->csrfhash;?>" />
			</form>
		</div>
	</div>
</section>

<?php foreach ($this->niveles as $niveles) : ?>
<div id="JobAreaBox<?php echo $niveles['area']; ?>" class="page_modal modal_job_area" style="display: none;">
		<p>Selecciona tu nivel</p>
		<p class="info">(máximo 3 niveles)</p>
		<div class="select_level">
			<?php foreach ($niveles['niveles'] as $nivel) : ?>
				<span data-value="<?=$nivel['id'].'_'.$nivel['slug']?>"><?=$nivel['nombre']?></span>
			<?php endforeach; ?>
			<button class="btn btn_cuaternary" id="btnFinish" type="button">Listo</button>
		</div>
	</div>
<?php endforeach; ?>