<html>
<head>
    <title></title>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="<?php echo $this->S('/eb/css/empleo.busco.css');?>">
        <link rel="stylesheet" href="<?php echo $this->S('/eb/font-awesome/css/font-awesome.min.css');?>">
        <link rel="stylesheet" href="<?php echo $this->S('/eb/css/utilities.css');?>">

    <style type="text/css">
        body{
            box-sizing: border-box;
        }

    </style>
</head>
<body style="margin:0">
    <header style="border-bottom:3px solid #2A5E9A;max-width: 850px;padding-right: 20px;padding-left: 20px;margin-right: auto;margin-left: auto;">
        <table style="width:100%">
            <tr>
                <td>

                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>"  />
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://plus.google.com/114662004918934085669">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;" src="<?php echo $this->S('/images/email-logo/logo-googleplus.png');?>"/>
                    </a>
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://twitter.com/aquiempleos">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;padding:0.2em" src="<?php echo $this->S('/images/email-logo/twitter-4.png');?>" class="icon-social"/>
                    </a>
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://www.facebook.com/aquiempleos">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;" src="<?php echo $this->S('/images/email-logo/facebook.png');?>" class="icon-social"/>
                    </a>
                </td>
        </table>
    </header>
    <section style="font-family: gotham,arial,sans-serif;max-width: 750px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
             <?=$this->emailTemplate?>
    </section>
    <footer style="border-top:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table width="100%" style="text-align:center">
            <tr>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" style="width:90%;"/>
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/casa_209x150.jpg');?>" style="width:90%;"/>
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/carro_209x150.jpg');?>" style="width:90%;"/>
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/venta_209x150.jpg');?>" style="width:90%;"/>
                </td>
            </tr>
        </table>
    </footer>
</body>
</html>
