<html>
<head>
<!--general stylesheet-->
<meta http-equiv="Content-Language" content="es" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
body {
	font-family: Arial, Helvetica, sans-serif;
}
p {
	padding: 0;
	margin: 0;
}
h1, h2, h3, p, li {
	font-family: Arial, Helvetica, sans-serif;
}
ul, ol {
	margin: 0;
	padding: 0;
}
</style>
</head>
<body>
<table cellspacing="0" border="0" cellpadding="0" width="580px" align="center">
	 <tr valign="top">
		  <td>
				<!-- heaer -->
				<table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
					  <tr>
						  <td valign="middle" bgcolor="#ffffff" height="30" style="vertical-align: middle; border-bottom: #d6d6d6 0px solid">
								<p style="font-size: 12px;"> Para asegurar la entrega de nuestros e-mail en su correo, por favor agregue <a  style="COLOR: #0972D3;text-decoration:none;" href="mailto:<?=CORREO_NOTIFICACIONES?>" ><?=CORREO_NOTIFICACIONES?></a> a su libreta de contactos</p>
						  </td>
					  </tr>
				</table>
				<table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
					 <tr>
						  <td width="196" height="72" align="center" valign="middle" style="margin: 0px 0px 0px;color:#ffffff"><img style="border:none;margin: 15px 0px 0px 0px;" src="<?php echo $this->S('/img/logo_aquiesta.png');?>" alt="EMPLEOBUSCO"/></td>
						  <td width="554" align="right" valign="middle" bgcolor="#F0F0F0" style="padding:15px;text-transform:uppercase; font: bold 20px verdana"><?=$this->subject?></td>
					 </tr>
				</table>
				<!--container-->
				<table cellpadding=0 cellspacing=0 width="94%" align=center>
								<tr>
									 <td><p style="font-size:10px; margin:15px 0 10px; text-align:justify">Para asegurar la entrega de nuestros e-mails en su correo, por favor agregue <a style="color:#3366ff" href="mailto:<?=CORREO_NOTIFICACIONES?>"><?=CORREO_NOTIFICACIONES?></a> a su libreta de contactos
												Si no visualiza bien este correo electrónico, haga <a style="color:#3366ff" href="<?=SITE_URL?>" target="_blank">click aquí</a>. </p>
									 </td>
								</tr>
									 <td style="text-align:justify;font-family:verdana;font-size:12px">
										  <?= $this->emailTemplate ?>
										  <br>
										  <b>El equipo AquiEmpleos</b>
										  <br><br>
									 </td>
								</tr>
				</table>
				<!--/container-->
				<!--/pie de pagina-->
				<table align="center" width="750" cellspacing="0" border="0" cellpadding="0">
					 <tr>
						  <td style="background-repeat: no-repeat" align="center" >
								<table style="padding-bottom:8px"align="right" width="750"  cellspacing="0" border="0" cellpadding="0">
									 <tr bgcolor="#373737">
										  <td width="172" align="left" valign="middle" style="padding-right: 10px; padding-left: 20px; padding-top: 8px"></td>
										  <td width="441" align="right" valign="middle" style="padding: 10px;color:#FFF;font-size:12px"></td>
										  <td width="137" align="right" valign="middle" style="padding: 10px; text-align:right"></td>
									 </tr>
								</table>
						  </td>
					 </tr>
				</table>
		  </td>
	 </tr>
</table>
</body>
</html>
