<html>
<body><head>

	<meta http-equiv="Content-Language" content="es" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>


<table cellpadding=0 cellspacing=0 width="580px" align=center style="border:#cccccc 1px solid"><tr><td>
<table cellpadding=0 cellspacing=0 width="94%" align=center>
<tr><td><p style="font-size:10px; margin:15px 0 10px; text-align:justify">Para asegurar la entrega de nuestros e-mails en su correo, por favor agregue <a style="color:#3366ff" href="mailto:<?=CORREO_NOTIFICACIONES?>"><?=CORREO_NOTIFICACIONES?></a> a su libreta de contactos
Si no visualiza bien este correo electrónico, haga <a style="color:#3366ff" href="<?=SITE_URL?>" target="_blank">click aquí</a>. </p>
</td></tr>
<tr><td height=80px><img  style="border:none;margin: 15px 0px 0px 0px;" src="<?php echo $this->S('/images/emailing/logo.png');?>" alt="logo EMPLEOBUSCO" border=0 height=50px></td></tr>

<tr><td style="text-align:justify;font-family:verdana;font-size:12px">

<?=$this->emailTemplate?>

<br>
<b>El equipo AquiEmpleos</b>
<br><br>
</td></tr></table>
</td></tr></table>
</body>
</html>
