<table width="88%" style="margin: 10px 0px 0px 10px" align="center" border="0">
	 <tr>
	 <td colspan="2" height="25"></td>
	 </tr>
	 <tr>
		  <td colspan="2" align="center" valign="top" style="font-weight:bold;padding-bottom:10px;"><span style="color:#656565;font-size:30px;">Tu empresa ya tiene activo el plan de</span><br/><span style="color:#100F0F;font-size:30px;">Membresía AquiEmpleos Esencial</span></td>
	 </tr>
	 <tr>
		  <td colspan="2" align="center">
		  <table align="center" width="75%">
		  <tr><td>
					 <table style="font-size: 15px;" cellpadding="0" cellspacing="1">
					 <tr><td width="92">Inicio Plan
					 </td><td width="12"> : </td><td><?php echo $this->fecini; ?></td></tr>
					 <tr><td>Fin del Plan
					 </td><td> : </td><td><?php echo $this->fecfin; ?></td></tr>
					 </table>
		  </td>
		  <td valign="top">
				  <table style="font-size: 15px;" cellpadding="0" cellspacing="1">
					 <tr><td width="70">Usuario
					 </td><td width="12"> : </td><td><a style="color: #007FD2;text-decoration:none;" href="#"><?php echo $this->email; ?></a></td></tr>
					 <!--<tr><td>Contraseña
					 </td><td> : </td><td><a style="color: #007FD2;text-decoration:none;" href="#">loyalty</a></td></tr>-->
					 </table>
		  </td></tr>
		  </table>
		  </td>
	 </tr>
	 <tr><td height="15" colspan="2"></td></tr>
</table>

<table cellspacing="6" border="0" cellpadding="0" width="750">
	 <tr>
		  <td align="center">
				<table width="95%" cellspacing="3" border="0" cellpadding="1">
					<tr><td colspan="2" style="font-size: 16px;font-weight:bold;">A partir de ahora y durante un año podrá acceder a los siguientes beneficios en aquiempleos.com:</td></tr>
					 <tr>
						  <td colspan="2" height="10"></td>
					 </tr>
					 <tr>
						  <td width="50%" align="left">
						  <table width="98%" cellpadding="0" cellspacing="2" style="font-weight:bold;">
								<?php foreach ($this->beneficios as $beneficio) : ?>
								<tr>
									 <td width="25" style="vertical-align:top; padding-left:10px"><img src="<?=SITE_URL?>static/images/emailing/arrow.jpg" width="16" height="13" alt="-"></td>
									 <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $beneficio['descripcion'];?></td>
								 </tr>
								<?php endforeach;?>
								 <?php /* ?>
								<tr>
									 <td width="8%" valign="top" align="left">&raquo;</td>
									 <td width="92%" style="font-size:13px;padding-bottom:8px;">Avisos Ilimitados</td>
								</tr>
								<tr>
									 <td valign="top" align="left">&raquo;</td>
									 <td style="font-size:13px;">Prioridad en Ubicación del aviso sobre los avisos sueltos y gratuitos</td>
								</tr>
								<tr>
									 <td valign="top" align="left">&raquo;</td>
									 <td style="font-size:13px;">Acceso a la base de datos (Búsqueda en  AquiEmpleos)</td>
								</tr>
								<tr>
									 <td valign="top" align="left">&raquo;</td>
									 <td style="font-size:13px;">03 Evaluaciones AquiEmpleos Match</td>
								</tr>
								<tr>
									 <td valign="top" align="left">&raquo;</td>
									 <td style="font-size:13px;">02 Avisos Impresos de Imagen Marca Empleador en el Suplemento AquiEmpleos (La Prensa y/o El Talán del Diario El Trome)</td>
								</tr>
								<tr>
									 <td valign="top" align="left">&raquo;</td>
									 <td style="font-size:13px;">Descuentos en Avisos Impresos ( 4% en AquiEmpleos La Prensa y 6% en AquiEmpleos El Talan)</td>
								</tr>
								<tr><td colspan="2" height="10"></td></tr>
						<tr>
									 <td colspan="2" style="font-size:13px;">Contáctenos: 311-6500 Anexos 3726 / 2146</td>
								</tr>
								  <?php */ ?>
						  </table>
						  </td>
						  <td align="center" valign="top">
							  <a style="color: #007FD2;font-size:15px;" href="<?=SITE_URL.'/empresa/#loginP'?>">Ingresar a mi cuenta</a>
						  </td>
					 </tr>
				</table>
		  </td>
	 </tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff"
	 cellspacing="0" cellpadding="0" border="0">
	 <tr><td height="10">&nbsp;</td></tr>
	 <tr>
		  <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
		  <h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
								<span style="color:#232222; font-weight:normal; font-size:24px; font-family: Arial, Helvetica, sans-serif">&iexcl;&Eacute;xitos! </span>
								<span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo AquiEmpleos</span> </h1>
							</td>
	 </tr>
</table>
