<br><P align=center><font size=3>
<b>¡ Membresia comprado no registrado en Adecsys !</b></font></P>
<br />

EMPLEOBUSCO.com no pudo registrar el siguiente aviso en Adecsys:<br /><br />
<table>
	<tbody>
		<tr>
			<td>Empresa</td>
			<td>:</td>
			<td><?php echo $this->razonSocial; ?></td>
		</tr>
		<tr>
			<td>RUT</td>
			<td>:</td>
			<td><?php echo $this->numDocumento; ?></td>
		</tr>
		<tr>
			<td>Usuario</td>
			<td>:</td>
			<td><?php echo $this->nombre; ?></td>
		</tr>
		<tr>
			<td>Correo</td>
			<td>:</td>
			<td><?php echo $this->usuario; ?></td>
		</tr>
		<tr>
			<td>Membresia</td>
			<td>:</td>
			<td><?php echo $this->tipoMembresia; ?></td>
		</tr>
		<tr>
			<td>Medio de Pago</td>
			<td>:</td>
			<td><?php echo $this->medioPago; ?></td>
		</tr>
		<tr>
			<td>Id Membresia en EMPLEOBUSCO</td>
			<td>:</td>
			<td><?php echo $this->membresiaId; ?></td>
		</tr>
		<tr>
			<td>Id Compra en EMPLEOBUSCO</td>
			<td>:</td>
			<td><?php echo $this->compraId; ?></td>
		</tr>
		<tr>
			<td>Fecha Registro de Membresia</td>
			<td>:</td>
			<td><?php echo $this->FriendlyDate($this->fechaCreacion); ?></td>
		</tr>
		<tr>
			<td>Fecha de Pago</td>
			<td>:</td>
			<td><?php echo $this->FriendlyDate($this->fechaPago); ?></td>
		</tr>		
		<tr>
			<td>Estado de Membresia</td>
			<td>:</td>
			<td><?php echo $this->membresiaEstado; ?></td>
		</tr>
		<tr>
			<td>Estado de Compra</td>
			<td>:</td>
			<td><?php echo $this->compraEstado; ?></td>
		</tr>		
	</tbody>
</table><br /><br />
Este correo es enviado para que se puedan tomar las acciones necesarias para registrar el aviso mencionado en Adecsys,<br />
Ya que se trata de un aviso pagado y que el cliente espera esté publicado en el impreso.<br />El aviso en mención NO pudo ser registrado en Adecsys de forma automática<br /><br />
Muchas Gracias
<br /><br />