<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
	<tr><td height="32"></td></tr>
    <tr>
        <td align="center" style="font-size:26px;color:#100F0F;">El aviso <?=$this->puesto?>, ha sido asociado al código de Adecsys <?=$this->adecsys?> por el usuario <?=$this->usuAdmin?></td>
    </tr>
    <tr><td height="20"></td></tr>
    <tr>
        <td align="left" style="font-size: 16px;padding-left:80px;padding-right:80px;">Para mayor información comuníquese a <a style="color: #007FD2;text-decoration:none;" href="mailto:soporte@EMPLEOBUSCO.com.pe">soporte@EMPLEOBUSCO.com.pe</a> para solucionar este inconveniente: 
        </td>
    </tr>
    <tr><td height="25"></td></tr>
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="center" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>