<table>
    <tr>
        <td style="padding: 1.5em 0;">Hola <span style="font-weight:bold;"><?=$this->alt?></span></td>
    </tr>
    <tr>
        <td style="padding-bottom:1em;">Has realizado satisfactoriamente la publicación de tu aviso Simple en AquiEmpleos. Puedes revisar tu publicación aqui:</td>
    </tr>
</table>
<table align="center" style="border-collapse: collapse;" >
    <tr>
        <td style="width:30%"></td>
         <td style="border:1px solid #2A5E9A;width: 40%;height: 250px;display:table-cell;padding:1em;text-align:center">
            <img src="<?=$this->logo?>" alt="<?=$this->alt?>" width="80%">
        </td>
        <td style="width:30%"></td>
    </tr>
    <tr>
        <td style="width:30%"></td>
        <td style="border:1px solid #2A5E9A;width: 40%;height: 50px;text-align:center;background:#2A5E9A;color:white;padding:1em;"><?=$this->nombrePuesto?></td>
        <td style="width:30%"></td>
    </tr>
    <tr style="height:20px;"></tr>
    <tr>
        <td style="width:30%"></td>
        <td style="text-align:center;width: 40%">
            <a href="<?=$this->urlAviso?>" style="background:#2A5E9A;padding:0.5em 1em;color:white;text-decoration:none;border-radius:8px;">Ver Anuncio</a>

        </td>
        <td style="width:30%"></td>
    </tr>
</table>
<table style="text-align:center;margin:3em 0 2em 0;" width="100%">
    <tr>
        <td style="">Saludos cordiales,</td>
    </tr>
    <tr>
        <td style="font-weight:bold">Equipo AquiEmpleos</td>
    </tr>
</table>
