<table cellspacing="0" border="0" cellpadding="0" width="750">
	<tr><td>&nbsp;</td></tr>
    <tr>
        <td valign="top" align="center" colspan="2" style="text-align: center">
            <table width="100%" style="margin:0" align="center" border="0">                                   
                <tr>
                    <td align="center" style="color:#5a5658; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-weight:bold;font-size:28px; line-height:1">
                        <span style="color:#000000;font-size:28px; line-height:1">
						¡ <span><?= $this->nombre?></span>, tu cuenta ha sido bloqueada temporalmente en EMPLEOBUSCO !
                        </span>
                    </td>
                </tr>
                <tr>
                	<td>&nbsp;</td>
                </tr>
                <tr>    
                    <td align="center" width="100%" style="font-size:20px; padding:10px 80px; color:#232222; text-align:left">
                        Para mayor informaci&oacute;n comun&iacute;quese a <a href="mailto:soporte@EMPLEOBUSCO.com.pe">soporte@EMPLEOBUSCO.com.pe</a> para solucionar este incoveniente: 
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
				<tr>
                    <td>
                        <table cellspacing="0" cellpadding="0" border="0">
                            <tr>
                                <td align="center" width="750" style="padding-left:30px;padding-bottom:10px;"><h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                                    <span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo EMPLEOBUSCO</span> </h1>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
            </table>
        </td>
    </tr>
</table>