<table width="88%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
    <td colspan="2" height="25"></td>
    </tr>
    <tr>
        <td colspan="2" align="center" valign="top" style="font-weight:bold;padding-bottom:10px;">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2" align="center">&nbsp;</td>
    </tr>
    <tr>
      <td height="15" colspan="2"><p>¡Gracias!,  Por adquirir el plan de Membresía <strong>PREMIUM.</strong>      Se procederá a activar su Plan  en un  Plazo de 48 horas. </p></td></tr>
</table>
                     
<table cellspacing="6" border="0" cellpadding="0" width="750">
    <tr>
        <td align="center">
            <table width="95%" cellspacing="3" border="0" cellpadding="1">
                <tr>
                  <td colspan="2" style="font-size: 16px;font-weight:bold;">&nbsp;</td></tr>
                <tr>
                    <td colspan="2" height="10"><p> EMPLEOBUSCO.com:</p></td>
                </tr>
                <tr>
                    <td width="50%" align="left">
                 <table cellpadding=0 cellspacing=0 width="98%" align="center">
<tr>
<td style="text-align:justify;font-family:verdana;font-size:12px;width:4%">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Avisos Ilimitados</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Prioridad en Ubicación del aviso sobre los avisos Plan Esencial</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Acceso a la base de datos (Búsqueda en  EMPLEOBUSCO)</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Bolsa de CVs</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Trabaje con Nosotros</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>30 Evaluaciones EMPLEOBUSCO Match</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>04 Avisos Impresos de Imagen Marca Empleador en el Suplemento EMPLEOBUSCO</b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
&#10003;</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<b>Descuentos en Avisos Impresos ( 6% en EMPLEOBUSCO La Prensa y 8% en EMPLEOBUSCO El Talan)</b>
</td></tr></table>
                    </td>
                    <td align="center" valign="top">
                        <a style="color: #007FD2;font-size:15px;" href="<?=SITE_URL.'/empresa/#loginPEmp'?>">Ingresar a mi cuenta</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
                     
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff"
    cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td height="10"><table align="center" width="75%">
        <tr>
          <td><table style="font-size: 15px;" cellpadding="0" cellspacing="1">
            <tr>
              <td width="92">Inicio Plan </td>
              <td width="12"> : </td>
              <td><?= $this->fecini; ?></td>
            </tr>
            <tr>
              <td>Fin del Plan </td>
              <td> : </td>
              <td><?=  $this->fecfin; ?></td>
            </tr>
          </table></td>
          <td valign="top"><table style="font-size: 15px;" cellpadding="0" cellspacing="1">
            <tr>
              <td width="70">Usuario </td>
              <td width="12"> : </td>
              <td><a style="color: #007FD2;text-decoration:none;" href="#"><?php echo $this->email; ?></a></td>
            </tr>
            <tr>
                  <td width="70">Empresa</td>
              <td width="12">:</td>
              <td><?=$this->RazonSocial?></td>
            </tr>
            <!--<tr><td>Contraseña
                </td><td> : </td><td><a style="color: #007FD2;text-decoration:none;" href="#">loyalty</a></td></tr>-->
          </table></td>
        </tr>
      </table></td></tr>
    <tr>
      <td height="10"><p>Contáctenos:  311-6500 Anexos 3726 / 2146 También puedes ingresar a tu cuenta en EMPLEOBUSCO para  revisar este y todos tus mensajes en el siguiente enlace: Mi Cuenta EMPLEOBUSCO.</p></td>
    </tr>
    <tr>
        <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
        <h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                        <span style="color:#232222; font-weight:normal; font-size:24px; font-family: Arial, Helvetica, sans-serif">&iexcl;&Eacute;xitos! </span>
                        <span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo EMPLEOBUSCO</span> </h1>
                            </td>
    </tr>
</table>