<table cellspacing="0" border="0" cellpadding="0" width="750">
	<tr><td>&nbsp;</td></tr>
    <tr>
        <td valign="top" align="center" colspan="2" style="text-align: center">
            <table width="100%" style="margin: 0" align="center" border="0">
                <tr>
                    <td align="center" style="color:#5a5658; padding:0 30px; font-weight:bold; line-height:1">
                        <span style="color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:32px; line-height:1"><?= $this->nombreEmisor ?> te recomienda el puesto:</span>                                                                                                
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                	<td align="center"><span><a style="text-decoration:none; font-family:Arial, Helvetica, sans-serif; text-decoration:underline; color:#007FD2; font-size:20px" href="<?= $this->avisoUrl ?>"><?= $this->avisoUrl ?></a></span></td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                	<td style="font-size:16px; color:#232222; font-family:Arial, Helvetica, sans-serif; padding:0 40px"><?= $this->mensajeCompartir ?></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr></tr>
</table>
<table align="center" cellspacing="0" cellpadding="0" border="0" width="750">
    <tr>
        <td>
            <table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <td align="center" width="750" style="padding-left:30px; padding-bottom:10px;"><h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">                                              
                        <span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo EMPLEOBUSCO</span> </h1>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
