<div style="font-family: gotham,arial,sans-serif;max-width: 750px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
    <table>
        <tr>
            <td style="padding: 1.5em 0;">Hola Micaela:</td>
        </tr>
        <tr>
            <td style="padding-bottom:1em;">Se ha realizado correctamente el pago de la publicación de tu aviso <?= $this->anuncioPuesto ?> en el portal de AquiEmpleos</td>
        </tr>
        <tr>
            <td style="padding-bottom:1em;">Puedes revisar tu publicación en el siguiente enlace: <a href="#" style="text-decoration:none; color:#2A5E9A">Ver Aviso</a></td>
        </tr>
    </table>
    <table style="border-collapse: collapse;width: 100%;" >
        <tr>
            <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos del usuario</td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Nombres / Razón Social:</td>
            <td style="padding: 0.5em 1em;"><?= $this->razonSocial ?></td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Nombres + Apellido:</td>
            <td style="padding: 0.5em 1em;"><?= $this->usuario ?></td>
        </tr>
        <tr>
            <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de Facturación</td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Número de Factura:</td>
            <td style="padding: 0.5em 1em;"><?= $this->codigo_adecsys_compra ?></td>

        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Monto:</td>
            <td style="padding: 0.5em 1em;">$ <?= $this->montoTotal ?></td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">tipo de Documento:</td>
            <td style="padding: 0.5em 1em;"><?= $this->tipo_doc ?></td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Número de Documento:</td>
            <td style="padding: 0.5em 1em;"><?= $this->numDocumento ?></td>
        </tr>
        <tr>
            <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de la Transacción</td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Número de transacción:</td>
            <td style="padding: 0.5em 1em;"><?= $this->compraId ?></td>


        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Medio de Pago:</td>
            <td style="padding: 0.5em 1em;"><?= $this->medioPago ?></td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Fecha y Hora:</td>
            <td style="padding: 0.5em 1em;"><?= $this->fechaPago ?></td>
        </tr>
        <tr>
            <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de Publicación</td>
        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Medio de Publicación:</td>
            <td style="padding: 0.5em 1em;"><?= $this->medioPublicacion ?></td>

        </tr>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Tipo de Aviso Web:</td>
            <td style="padding: 0.5em 1em;"><?= $this->prioridad ?></td>
        </tr>
        <?php if ($this->tipo=='clasificado'): ?>
        <tr style="border: 1px solid #1e8048;">
            <td style="padding: 0.5em 1em;color:#2A5E9A">Tipo de Aviso Impreso:</td>
            <td style="padding: 0.5em 1em;"><?= $this->tipo ?></td>
        </tr>
        <?php endif; ?>
    </table>
    <table style="text-align:center;margin:3em 0 2em 0;" width="100%">
        <tr>
            <td style="">Saludos cordiales,</td>
        </tr>
        <tr>
            <td style="font-weight:bold">Equipo AquiEmpleos</td>
        </tr>
    </table>
</div>
