<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr><td height="30"></td></tr>
    <tr>
        <td align="center" style="font-weight:bold;"><span style="color:#100F0F;font-size:28px;">Su aviso <? $this->titulo ?> está publicado en EMPLEOBUSCO.com</span></td>
    </tr>
    <tr><td height="10"></td></tr>
    <tr>
        <td align="center" style="font-size: 16px;">Sus datos de acceso son: <br />
            <span style="font-weight:bold;">Usuario : </span><a style="color: #007FD2;text-decoration:none;" href="#"><?= $this->to ?></a>
        </td>
    </tr>
    <tr><td height="5"></td></tr>
</table>


<table cellspacing="6" border="0" cellpadding="0" width="750">
    <tr>
        <td align="center">
            <table width="95%" cellspacing="5" border="0" cellpadding="2">
                <tr>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="42%">
                        <table border="0" cellpadding="0" cellspacing="0" style="font-size:13px;">
                            <tr><td height="40">Su aviso ha sido registrado con las siguientes caracter&iacute;sticas:</td></tr>
                            <tr><td>
                                    <span style="font-weight:bold;">N&uacute;mero de Puestos:</span> <?= $this->nroPuestos ?><br/>
                                    <span style="font-weight:bold;">Empresa:</span> <?= $this->razonSocial ?><br/>
                                    <span style="font-weight:bold;">Precio:</span>S/ <?= $this->montoTotal ?><br/>
                                    <span style="font-weight:bold;">Medio de Pago:</span> <?= $this->medioPago ?>
                                </td></tr>
                        </table>
                    </td>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="48%" style="font-size:13px;">
                        <span style="font-weight:bold;">Clase de Aviso: </span><?= $this->anuncioClase ?><br />
                        <span style="font-weight:bold;">Tipo de Aviso: </span><?= $this->tipoAviso ?><br />
                        <span style="font-weight:bold;">C&oacute;digo de Aviso EMPLEOBUSCO: </span><?= $this->codigoAviso ?><br />
                        <span style="font-weight:bold;">Vigencia en Web: </span>Del <?= $this->FriendlyDate($this->fechaPago) ?> hasta <?= $this->FriendlyDate($this->anuncioFechaVencimiento) ?><br />
                        <span style="font-weight:bold;">Publicación en EMPLEOBUSCO Impreso: </span><?= $this->FriendlyDate($this->fechaPublicConfirmada) ?><br />
                        <span style="font-weight:bold;">Publicación en TALÁN Impreso: </span><?= $this->FriendlyDate($this->fechaPublicConfirmada) ?><br />
                        <span style="font-weight:bold;">Vigencia del Proceso de Selecci&oacute;n: </span>Del <?= $this->FriendlyDate($this->fechaPago) ?> hasta <?= $this->FriendlyDate($this->anuncioFechaVencimientoProceso) ?>
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td style="font-weight:bold;font-size:14px;">
                        Avisos Publicados:<br />
                    </td>
                    <td></td>
                    <td></td>
                </tr>
                <?php
                $cantp = $this->nroPuestos;
                $cont = 0;
                $nrogiros = ($cantp / 2);
                $cadComplete = '<td></td><td></td></tr>';
                foreach ($this->anunciosWeb as $aWeb) :
                    $cont++;
                    if ($cont % 2 != 0) {
                        echo '<tr>';
                    }
                    ?>
                    <td></td>
                    <td style="font-size:13px;">
                        Aviso: <?= $aWeb['titulo'] ?><br />
                        URL Aviso: <a style="color: #007FD2;" href="<?= SITE_URL . $this->url(array('slug' => $aWeb['slug'], 'url_id' => $aWeb['urlId']), 'aviso', true) ?>">Ver aviso publicado en la web</a>
                    </td>
                    <?php
                    if ($cont % 2 == 0) {
                        echo '</tr>';
                    }
                    if ($cont == $cantp && $cont % 2 != 0) {
                        echo $cadComplete;
                    }
                endforeach;
                ?>
            </table>
            <P align=center style="color:#3366ff"><a href="<?=SITE_URL?><?= $this->url(array('module' => 'empresa', 'controller' => 'publica-aviso', 'action' => 'index'), 'default', true) ?>"><b>Publicar otro aviso</b></a></P>
        </td>
    </tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
       cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl;Gracias por anunciar en EMPLEOBUSCO!</span><br />
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>
