<table width="750" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">
    <tr>
    	<td width="720px" style="padding:20px; vertical-align:top">
        	<table width="720" border="0" cellspacing="0" cellpadding="0" style="color:#333">
              <tr>
              	<td style="vertical-align:top">
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:22px;margin:0; padding:0 0 30px;">Hola <strong><?=$this->nombres?></strong></p>
                </td>
              </tr>
              <tr>
              	<td style="text-align:center; padding-bottom:40px;">
                	<h2 style="color: #666; font-family:Arial, Helvetica, sans-serif; font-size:20px; font-weight:400; line-height:22px; margin:0; padding:0 0 5px;">Gracias por adquirir tu</h2>
					<p style=" color:#000;font-family:Arial, Helvetica, sans-serif; font-size:29px; line-height:32px; margin:0; padding:0">Perfil Destacado</p>
                </td>
              </tr>
              <tr>
              	<td style="vertical-align:top">
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">Desde hoy tendrás los siguientes beneficios:</p>                	
                </td>
              </tr>
              <tr>
              	<td style="vertical-align:top; padding: 0 20px">
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Alertas de todas tus postulaciones.</p>
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Alertas del estado de tu proceso de postulación.</p>
                    <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Tu perfil aparecerá en un lugar preferencial en los resultados de búsqueda de postulantes que las empresas necesitan.</p>
                </td>
              </tr>
              <tr>
              	<td style="vertical-align:top">
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:20px 0 0;">Tu Perfil Destacado estará activo desde el <span style="color:#009FEC; font-weight:700"><?=$this->inicio?></span> hasta el <span style="color:#009FEC; font-weight:700"><?=$this->fin?></span></p>                	
                </td>
              </tr>
              <tr>
              	<td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; padding-top:60px;">
                	¡Éxitos!<br><br><strong>El equipo EMPLEOBUSCO</strong>.
                </td>
              </tr>
            </table>
        </td>
    </tr>
</table>
