<br><P align=center><font size=3>
<b>Su aviso para "<?=$this->anuncioPuesto?>" está publicado</b></font></P>
<br>
Sus datos de acceso son: <BR>
<span style="color:#000000;font-size:13px"><b>Usuario    : </b></span><span style="color:#3366ff;font-size:13px"><b><?=$this->to?></b></span><BR>
<br><br>
Se ha registrado su aviso con las siguientes características:
<br><br>
</td></tr>
<tr><td>

<table cellpadding=0 cellspacing=0 width="90%" align=center>
<tr><td style="text-align:justify;font-family:verdana;font-size:12px;width:30%">
Puesto solicitado</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
: <b><?=$this->anuncioPuesto?></b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
Empresa</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
: <b><?=$this->razonSocial?></b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
Precio</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
: <b>$<?=$this->montoTotal?></b>
</td></tr><tr><td style="text-align:justify;font-family:verdana;font-size:12px">
Medio de Pago</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
: <b><?=$this->medioPago?></b>
</td></tr></table>
<br>
<table cellpadding=0 cellspacing=0 width="90%" align=center>
<tr><td valign=top width="3%"><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px;width:45%">
Clase de Aviso
</td><td width="2%">: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
<b><?=$this->anuncioClase?></b>
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Tipo de Aviso
</td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
<b><?=$this->productoNombre?></b>
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Código de Aviso EMPLEOBUSCO
</td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
<b><?=isset($this->codigo_adecsys_compra)? $this->codigo_adecsys_compra:$this->anuncioUrl?></b>
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Vigencia en Web
</td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
<b>del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimiento)?></b>
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
<? if($this->medioPublicacion == "EMPLEOBUSCO"):?>
    Publicación en EMPLEOBUSCO Impreso
    </td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
    <b><?=$this->FriendlyDate($this->fechaPublicConfirmada)?></b>
    </td></tr><tr><td valign=top><li></td>
    <td style="text-align:justify;font-family:verdana;font-size:12px">
<? endif; ?>
<? if($this->medioPublicacion == "talan"):?>
    Publicación en TALÁN Impreso
    </td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
    <b><?=$this->FriendlyDate($this->fechaPublicConfirmada)?></b>
    </td></tr><tr><td valign=top><li></td>
    <td style="text-align:justify;font-family:verdana;font-size:12px">
<? endif; ?>
<? if($this->medioPublicacion == "EMPLEOBUSCO y talan"):?>
    Publicación en EMPLEOBUSCO Impreso
    </td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
    <b><?=$this->FriendlyDate($this->fechaPublicConfirmada)?></b>
    </td></tr><tr><td valign=top><li></td>
    <td style="text-align:justify;font-family:verdana;font-size:12px">
    Publicación en TALÁN Impreso
    </td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
    <b><?=$this->FriendlyDate($this->fechaPublicConfirmada)?></b>
    </td></tr><tr><td valign=top><li></td>
    <td style="text-align:justify;font-family:verdana;font-size:12px">
<? endif; ?>
Vigencia del Proceso de Selección
</td><td>: </td><td style="text-align:justify;font-family:verdana;font-size:12px">
<b>del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimientoProceso)?></b>
</td></tr></table>

</td></tr>   
<tr><td style="text-align:justify;font-family:verdana;font-size:12px">
<br><br>
<P align=center style="color:#3366ff"><a href="<?=SITE_URL.$this->url(array('slug' => $this->anuncioSlug, 'url_id' => $this->anuncioUrl), 'aviso', true)?>"><b>Ver Aviso publicado en la Web</b></a></P>
<br>
<P align=center style="color:#3366ff"><a href="<?=SITE_URL.'/empresa/publica-aviso/paso1'?>"><b>Publicar otro Aviso</b></a></P>
<br>¡Gracias por anunciar en EMPLEOBUSCO!
<br><br><br>
