<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
        <td align="center" style="font-weight:bold;"><span style="color:#656565;font-size:36px;">Su aviso </span><br/><span style="color:#100F0F;font-size:40px;">"<?= trim($this->anuncioPuesto) ?>" </span><br /><span style="color:#656565;font-size:36px;">est&aacute; registrado</span></td>
    </tr>
    <tr>
        <td align="center" style="font-size: 15px;"><br />
            <span style="">Usuario : </span><a style="color: #007FD2;text-decoration:none;" href="#"><?= $this->to ?></a>
        </td>
    </tr>
    <tr>
        <td align="left" style="font-size: 15px;padding-left:36px;">
            Al registrar su aviso usted escogió como medio de pago <b>Pago Efectivo</b> para su aviso de "<?= trim($this->anuncioPuesto) ?>". Hasta no realizar el pago del aviso no podrá ser publicado.
        </td>
    </tr>
    <tr><td height="5"></td></tr>
</table>

<table cellspacing="6" border="0" cellpadding="0" width="750">
    <tr>
        <td align="center">
            <table width="95%" cellspacing="5" border="0" cellpadding="2">
                <tr>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="42%" valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" style="font-size:13px;">
                            <tr><td height="40">Su aviso ha sido registrado con las siguientes caracter&iacute;sticas:</td></tr>
                            <tr><td>
                                    <span style="font-weight:bold;">Puesto solicitado:</span> <?= $this->anuncioPuesto ?><br/>
                                    <span style="font-weight:bold;">Empresa:</span> <?= $this->razonSocial ?><br/>
                                    <span style="font-weight:bold;">Por Pagar:</span> $<?= $this->montoTotal ?><br/>
                                    <span style="font-weight:bold;">Medio de Pago:</span> <?= $this->medioPago ?><br />
                                </td></tr>
                        </table>
                    </td>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="48%" style="font-size:13px;" valign="top">
                        En unos momentos <b>Pago Efectivo</b> le enviará un correo con el código generado para que pueda pagar el aviso en cualquier agencia del Banco de Crédito del Perú (BCP) o por internet a través de <a style="color: #007FD2;text-decoration:none;" href="<?php ?>">www.viabcp.com</a> .
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="3" style="font-weight:bold;font-size:13px;padding-top:15px;">
                        Tu aviso está guardado como borrador y puede revisarlo y editarlo antes de realizar el pago.<br />
                        <a style="color: #007FD2;" href="<?= SITE_URL ?><?= $this->url(array('module' => 'empresa', 'controller' => 'mis-procesos', 'action' => 'borradores')); //$this->url(array('url_id' => $this->urlId, 'slug'=> $this->slug), 'aviso', true)  ?>">Ver aviso</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
       cellspacing="0" cellpadding="0" border="0">
    <tr><td height="25">&nbsp;</td></tr>
    <tr>
        <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl;Gracias por anunciar en EMPLEOBUSCO!</span><br />
            </h1> 
        </td>
    </tr>
</table>