<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
        <td align="center" style="font-weight:bold;"><span style="color:#656565;font-size:36px;">Su aviso para </span><br/><span style="color:#100F0F;font-size:40px;">"<?=trim($this->anuncioPuesto)?>" </span><br /><span style="color:#656565;font-size:36px;">est&aacute; publicado</span></td>
    </tr>
    <tr>
        <td align="center" style="font-size: 15px;"><br />
            <span style="font-weight:bold;">Usuario : </span><a style="color: #007FD2;text-decoration:none;" href="#"><?=$this->to?></a>
        </td>
    </tr>
    <tr><td height="5"></td></tr>
</table>


<table cellspacing="6" border="0" cellpadding="0" width="750">
    <tr>
        <td align="center">
            <table width="95%" cellspacing="5" border="0" cellpadding="2">
                <tr>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="42%" valign="top">
                        <table border="0" cellpadding="0" cellspacing="0" style="font-size:13px;">
                            <tr><td height="40">
                                    Su aviso ha sido registrado con las siguientes caracter&iacute;sticas:
<!--                                    Se ha registrado su aviso con las siguientes caracter&iacute;sticas:-->
                                </td></tr>
                            <tr><td>
                                <span style="font-weight:bold;">Puesto solicitado:</span> <?=$this->anuncioPuesto?><br/>
                                <span style="font-weight:bold;">Empresa:</span> <?=$this->razonSocial?><br/>
                                <span style="font-weight:bold;">Precio:</span> <?=$this->montoTotal?><br/>
                                <span style="font-weight:bold;">Medio de Pago:</span> <?=ucfirst($this->medioPago)?>
                            </td></tr>
                        </table>
                    </td>
                    <td width="2%" valign="top">&raquo;</td>
                    <td width="48%" style="font-size:13px;">
                        <span style="font-weight:bold;">Clase de Aviso: </span><?=$this->anuncioClase?><br />
                        <span style="font-weight:bold;">Tipo de Aviso: </span><?=$this->productoNombre?><br />
                        <span style="font-weight:bold;">C&oacute;digo de Aviso EMPLEOBUSCO: </span><?=isset($this->codigo_adecsys_compra)? $this->codigo_adecsys_compra:$this->anuncioUrl?><br />
                        <span style="font-weight:bold;">Vigencia en Web: </span>Del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimiento)?><br />
                        <? if($this->medioPublicacion == "EMPLEOBUSCO" || $this->medioPublicacion == "EMPLEOBUSCO y talan"):?>
                        <span style="font-weight:bold;">Publicación en EMPLEOBUSCO Impreso: </span><?=$this->FriendlyDate($this->fechaPublicConfirmada)?><br />
                        <? endif; ?>
                        <? if($this->medioPublicacion == "talan" || $this->medioPublicacion == "EMPLEOBUSCO y talan"):?>
                        <span style="font-weight:bold;">Publicación en TALÁN Impreso: </span><?=$this->FriendlyDate($this->fechaPublicConfirmada)?><br />
                        <? endif; ?>
                        <span style="font-weight:bold;">Vigencia del Proceso de Selecci&oacute;n: </span>Del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimientoProceso)?><br /><br />
                        <a style="color: #007FD2;" href="<?=SITE_URL.$this->url(array('slug' => $this->anuncioSlug, 'url_id' => $this->anuncioUrl), 'aviso', true)?>">Ver aviso publicado en la web</a>
                        &nbsp;&nbsp;&nbsp;<a style="color: #007FD2;" href="<?=SITE_URL.'/empresa/publica-aviso/paso1'?>">Publicar otro aviso</a>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>



<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl;Gracias por anunciar en EMPLEOBUSCO!</span><br />
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>