<h2><?php echo $this->categoria; ?></h2><br/>
<span style="font-weight: bold;">Nombres :</span>
<span><?php echo $this->fNameCT; ?></span><br/>
<span style="font-weight: bold;">Apellidos :</span>
<span><?php echo $this->fApellidosCT; ?></span><br/>
<span style="font-weight: bold;">Documento :</span>
<span><?php echo $this->tipo_documento.' - '.$this->fDocCT; ?></span><br/>
<span style="font-weight: bold;">Teléfonos :</span>
<span><?php echo $this->fTlfCT; ?></span><br/>
<span style="font-weight: bold;">Email :</span>
<span><a href="mailto:<?php echo $this->fMailCT; ?>"><?php echo $this->fMailCT; ?></a></span><br/>
<span style="font-weight: bold;">Tipo :</span>
<span><?php echo $this->fSubjectCT; ?></span><br/>
<span style="font-weight: bold;">Mensaje :</span>
<span><?php echo $this->fMsjCT; ?></span><br/>
<br/><br/>
<span style="color: #666666;">Este es un correo generado de forma automática por EMPLEOBUSCO</span>
<br><br>