<br>
<table cellpadding=0 cellspacing=0 width="90%" align=center>
            
            <tr>
                <td colspan="2" style="text-align:justify;font-family:verdana;font-size:12px;width:20%">Este mensaje fue enviado
                     por <b><?= $this->nom_contacto ?></b> de la Empresa <b><?= $this->empresa ?></b>. 
                </td>
                
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width:10%"><br>E-mail</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width: 10%"> : <b><?= $this->email ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">El teléfono de la empresa es</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->tele_empresa ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Teléfono de Contacto</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->tele_contacto ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Consulta</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->consulta ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Enviado el <?=date('d-m-Y H:i:s')?>.</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px"></td>
            </tr>
            
        </table>
        <br>

    </td></tr>   

        <br><br>