<br><br>    
<table cellpadding=0 cellspacing=0 width="90%" align=center>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width:30%">Empresa</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->empresa ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Nombre de Contacto</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px"> : <b><?= $this->contacto ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Teléfono de Contacto</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->telefono ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">E-mail</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->correo ?></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Consulta</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b><?= $this->consulta ?></b></td>
            </tr>
            
        </table>
        <br>

    </td></tr>   
        
        <br>¡Gracias por anunciar en EMPLEOBUSCO!
        <br><br>