<table width="636" border="0" cellspacing="0" cellpadding="0" style="color:#000; background-color:#fff; font-family:Arial, Helvetica, sans-serif;" align="center">	
    <tr>
   	  <td style="padding:5px 20px 30px 55px;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px">        	
            <br>
            Se adjunta el archivo log de los avisos importados el día <?=$this->fecha?>.<br>
            Tipo <?=$this->tipo?> <br>
            <?=$this->msg?>
            <br>
      </td>
    </tr>
</table>