<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr><td height="32"></td></tr>
    <tr>
        <td align="center" style="font-weight:bold;font-size:32px;color:#100F0F;">¡ La Empresa: <?=$this->empresa?>, ha sido desbloqueada !</td>
    </tr>
    <tr><td height="25"></td></tr>
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="center" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 0px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>