<br>
Verificar la siguiente  membresía web no está generando código de Adecsys:
<br><br>
</td></tr>
<tr><td>
		  <br>
		  <table cellpadding=0 cellspacing=0 width="90%" align=center>
				<tr><td valign=top width="3%"><li></td>
				<td style="text-align:justify;font-family:verdana;font-size:12px;width:45%">
					 Tipo de perfil (Id Compra)
				</td><td style="text-align:justify;font-family:verdana;font-size:12px">
					 : <b><?= $this->tipo . "(" . $this->idCompra . ')' ?></b>
				</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Nro Doc
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->num_doc ?></b>
</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Ente Id
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->enteId ?></b>
</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Cliente
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->cliente ?></b>
</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Monto
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b> <?= $this->monto ?></b>
</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Medio de publicación
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->medPub ?></b>
</td></tr>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Id Tarifa
</td><td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->idTarifa ?></b>
</td></tr>
<tr>
	 <td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Id Producto
</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->idProducto ?></b>
</td>
</tr>

<tr>
	 <td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Fecha
</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->fecha ?></b>
</td>
</tr>

<tr>
	 <td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 Núm reproceso
</td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
	 : <b><?= $this->reproceso ?></b>
</td>
</tr>

</table>

</td></tr>
<tr><td style="text-align:justify;font-family:verdana;font-size:12px">
		  <br>
		  <br>¡Gracias por anunciar en AquiEmpleos!
		  <br><br>
