<table width="750" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">
	 <tr>
		 <td width="720px" style="padding:20px; vertical-align:top">
			  <table width="720" border="0" cellspacing="0" cellpadding="0" style="color:#333">
				  <tr>
					  <td style="vertical-align:top">
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:22px;margin:0; padding:0 0 30px;">Hola <strong><?=$this->nombre?></strong></p>
					 </td>
				  </tr>
				  <tr>
					  <td style="text-align:center; padding-bottom:40px;">
						 <h2 style="color: #666; font-family:Arial, Helvetica, sans-serif; font-size:20px; font-weight:400; line-height:22px; margin:0; padding:0 0 5px;">Está por expirar tu</h2>
					<p style=" color:#000;font-family:Arial, Helvetica, sans-serif; font-size:29px; line-height:32px; margin:0; padding:0">Perfil Destacado</p>
					 </td>
				  </tr>
				  <tr>
					  <td style="vertical-align:top">
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">Te recordamos que tu plan de <b>Perfil Destacado</b> expirará dentro de 1 semana:</p>
					 </td>
				  </tr>
				  <tr>
					  <td style="padding-bottom:30px; padding-left:40px; vertical-align:top">
						 <table width="600" border="0" cellspacing="0" cellpadding="0">
							 <tr>
								<td width="120" style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;">Inicio Plan</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;"><b><?=$this->inicio?></b></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;">Fin Plan</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;"><b><?=$this->fin?></b></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;">Usuario</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px;"><b><?=$this->to?></b></td>
							 </tr>
						  </table>
					 </td>
				  </tr>
				  <tr>
					  <td style="vertical-align:top">
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">Renuévalo y no pierdas estos beneficios:</p>
					 </td>
				  </tr>
				  <tr>
					  <td style="vertical-align:top; padding: 0 20px">
						  <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Alertas de todas tus postulaciones.</p>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Alertas del estado de tu proceso de postulación.</p>
						  <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 10px;"><span style="font-size:10px">&gt;&gt;</span> Tu CV aparecerá en un lugar preferencial en los resultados de búsqueda y en las ofertas de trabajo que realicen las empresas.</p>
					 </td>
				  </tr>
				  <tr>
					  <td style="vertical-align:top; text-align:center; padding-top:30px"><a href="<?php echo SITE_URL.'/perfil-destacado' ?>" target="_blank" title="Adquiere tu Perfil Destacado"><img src="<?php echo $this->S('/images/emailing/btn.jpg');?>" width="240" height="36" style="border:0" /></a>
					 </td>
				  </tr>
				  <tr>
					  <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; padding-top:60px;">
						 ¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
					 </td>
				  </tr>
				</table>
		  </td>
	 </tr>
</table>
