<table style="width:600px;margin:0 auto;background:#FFF" width="600" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td style="padding:0 10px" colspan="2"><table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td colspan="2" style="border-top:1px solid #999;padding:0 10px"><p style="padding:20px 0 25px;margin:0">Hola <strong style="color:#000"><?= $this->nombre ?></strong></p>
            <h3 style="margin:0 0 30px;font-size:17px;color:#000">¡Has sido Seleccionado!</h3>
            <p style="margin:0 0 18px">El equipo de <strong style="color:#000">EMPLEOBUSCO,</strong> te invita a que te registres en nuestro portal y a la véz puedas participar en el siguiente proceso de selección:</p>
            <h2 style="font-size:14px;color:#000;margin:0;text-align:center;padding-bottom:35px"><?= $this->puesto ?></h2></td>
        </tr>
        <tr>
          <td width="50%" style="width:50%;padding-right:2%" align="right" valign="middle"><a title="Ver Oferta de Trabajo" target="_blank" href="<?=SITE_URL?>/ofertas-de-trabajo/<?=$this->slug?>-<?=$this->url_id?>"><img border="0" src="<?php echo $this->S('/images/emailing/ver-oferta.gif');?>" width="180" height="43" alt="Ver Oferta de Trabajo"></a></td>
          <td width="46%" style="width:46%;padding-left:2%" align="left" valign="middle"><a title="Postula aquí" href="javascript:;"><a title="Registrate aquí" href="<?=SITE_URL?>/registro"><img border="0" src="<?php echo $this->S('/images/emailing/registrate.gif');?>" width="120" height="43" alt="Registrate Aquí"></a></td>
        </tr>
      </table></td>
  </tr>
</table>