<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
	 <tr><td height="32"></td></tr>
	 <tr>
		  <td align="center" style="font-weight:bold;font-size:28px;color:#100F0F;"><?= $this->nombre ?>, el administrador de AquiEmpleos te ha enviado un mensaje. </td>
	 </tr>
	 <tr><td height="20"></td></tr>
	 <tr>
		  <td align="center" style="font-size: 16px;padding-left:120px;padding-right:120px;">
				Tus datos de acceso son: <br/>
				<b>Usuario :</b> <a style="color: #007FD2;text-decoration:none;" href="#"><?= $this->email ?></a>
		  </td>
	 </tr>
	 <tr><td align="center" style="font-size: 15px;"><a href="<?=$this->url?>">Ver mensaje</a></td></tr>
	 <tr><td height="25"></td></tr>
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff"
	 cellspacing="0" cellpadding="0" border="0">
	 <tr>
		  <td align="center" width="750" style="padding-left:0px;padding-bottom:10px;">
				<h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
					 <span style="color:#000;font-family: Arial, Helvetica, sans-serif"><span style="font-weight: normal;">El equipo</span> AquiEmpleos</span>
				</h1>
		  </td>
	 </tr>
</table>
