<table cellspacing="0" border="0" cellpadding="0" width="750">
	<tr><td>&nbsp;</td></tr>
    <tr>
        <td style="font-family: Arial, Helvetica, sans-serif;">
            <table border="0" cellspacing="1" cellpadding="0" style="padding: 18px 0px 0px 0px">
                <tr>
                    <td style="font-weight: bold; font-size: 21px; color: #000000; padding:0 0 0 30px; margin:0">
                        Hola,
                    </td>
                </tr>                
            </table>
        </td>
    </tr>
    <tr>
        <td valign="top" align="center" colspan="2" style="text-align: center">
            <table width="100%" style="margin: 10px 0px 0px 10px" align="center" border="0">
                <tr>
                    <td align="center" style="color:#5a5658;font-weight:bold;font-size:36px; line-height:1">                        
                        <span style="line-height:1">
                            El postulante: <?= $this->nombres.' '.$this->apellidos ?>. 
                            Se ha retirado de la postulación para el puesto
                        </span><br/>
                        <span style="color:#000000;font-size:44px; line-height:1">
                        <a href="<?php echo SITE_URL.$this->urlAviso;?>"  style="color: #007FD2;">
                            <?= $this->puesto ?>
                        </a>
                        </span>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr></tr>
</table>

<table cellspacing="0" cellpadding="0" border="0" width="750">
    <tr>
        <td>
            <table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;"><h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                        <span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo EMPLEOBUSCO</span> </h1>
                        
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>