<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1">
            Mensaje: <?=$this->mensaje?> 
        </td>
    </tr>
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1"><br>
            Tracert: <?=$this->trace?>
        </td>
    </tr>
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1"><br>
            Refers: <?=$this->refer?>
        </td>
    </tr>
    
    <tr>
        <td height="25"></td>
    </tr>
    
</table>
