<table width="636" border="0" cellspacing="0" cellpadding="0" style="color:#000; background-color:#fff; font-family:Arial, Helvetica, sans-serif;" align="center">	
    <tr>
    	<td style="padding:30px 20px 10px;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:17px">
        	<span style="border-top: 4px solid #fff; padding-top:6px">Estimado(a) <?=$this->nombres?></span>
        </td>
    </tr>
    <tr>
   	  <td style="padding:5px 20px 30px 55px;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px">        	
            Adjuntamos el archivo sobre el archivo de reporte de usuarios registrados del día <?=$this->fecha?>
      </td>
    </tr>
</table>