<table width="636" border="0" cellspacing="0" cellpadding="0" style="color:#fff; background-color:#000; font-family:Arial, Helvetica, sans-serif;" align="center">
	<tr>
    	<td style="vertical-align:top"><img src="<?php echo $this->S('/images/emailing/upc_img.jpg');?>" alt="UPC" width="636" height="352" usemap="#Map" style="border:0" border="0"></td>
    </tr>
    <tr>
    	<td style="padding:30px 20px 10px;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:17px">
        	<span style="border-top: 4px solid #fff; padding-top:6px">Estimado(a) <?=$this->nombres?></span>
        </td>
    </tr>
    <tr>
   	  <td style="padding:5px 20px 30px 55px;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px">
        	<strong>¡Bienvenido a la UPC!</strong><br>
            Su registro está completo, en breves momentos un(a) asesor(a) se estará comunicando con usted.
      </td>
    </tr>
</table>

<map name="Map">
  <area shape="rect" coords="546,8,626,79" href="http://postgrado.upc.edu.pe" target="_blank" title="Postgrado UPC">
</map>