<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:arial;font-size:14px">
    <tr>
    	<td colspan="3" valign="top" style="padding:10px">
        	<p>Estimado <strong><?=$this->nombre?></strong></p>
        </td>
    </tr>
    <tr>
    	<td colspan="3" valign="top" style="padding:10px">
        	<p>Has sido asignado como <strong>Administrador Secundario</strong> del proceso:</p>
            <h2 style="margin-left:50px"><strong><?= $this->puesto?></h2>
        </td>
    </tr>

</table>