<?php
//    $visitas = (empty($this->visitas))?0:count(explode(',', $this->visitas));
//    $busquedas = (empty($this->busquedas))?0:count(explode(',', $this->busquedas));
//    $postulaciones = (empty($this->postulaciones))?0:count(explode(',', $this->postulaciones));
//    $invitaciones = (empty($this->invitaciones))?0:count(explode(',', $this->invitaciones));
//    $leidas = (empty($this->leidas))?0:count(explode(',', $this->leidas));
//    $mensajes = (empty($this->mensajes))?0:count(explode(',', $this->mensajes));
//
	 $visitas = $this->visitas;
	 $busquedas = $this->busquedas;
	 $postulaciones = $this->postulaciones;
	 $invitaciones = $this->invitaciones;
	 $leidas = $this->leidas;
	 $mensajes = $this->mensajes;
?>
<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">
	 <tr>
		 <td width="720px" style="padding:20px;">
			  <table width="720" border="0" cellspacing="0" cellpadding="0" style="color:#333">
				  <tr>
					  <td style="vertical-align:top">
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:20px;margin:0; padding:0 0 20px;">Hola <strong><?php echo ucwords($this->nombres)?></strong></p>
						  <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:17px;margin:0; padding:0 0 30px;">Aquí te contamos como va tu avance en AquiEmpleos,</p>
					 </td>
				  </tr>
				  <tr>
					  <td style="padding:0 0 30px 35px; vertical-align:top">
						 <table width="650" border="0" cellspacing="0" cellpadding="0">
							 <tr>
								<td width="350" style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Periodo: </td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $this->periodo?></strong></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Se mostró su Perfil en las Búsquedas de Empresas:</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $busquedas?> veces</strong></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Su perfil fue visto:</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $visitas?> veces</strong></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Fue invitado a postular en:</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $invitaciones?> procesos de selección</strong> <a style="color:#009FEB; font-size:14px; line-height:16px; text-decoration:none;" href="<?php echo SITE_URL.'/notificaciones' ?>" target="_blank" title="Ver historial de notificaciones">(ver procesos)</a></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Postuló a:</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $postulaciones?> procesos de selección</strong></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Postulaciones leidas por las Empresas:	</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $leidas?></strong> <a style="color:#009FEB; font-size:14px; line-height:16px; text-decoration:none;" href="<?php echo SITE_URL.'/postulaciones' ?>" target="_blank" title="Ver historial de postulaciones">(ver historial de postulaciones)</a></td>
							 </tr>
							 <tr>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;">Mensajes pendientes de respuesta:</td>
								<td style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px;margin:0; padding:0 0 6px;"><strong><?php echo $mensajes?></strong> <a style="color:#009FEB; font-size:14px; line-height:16px; text-decoration:none;" href="<?php echo SITE_URL.'/postulaciones' ?>" target="_blank" title="Ver mensajes">(ver mensajes)</a></td>
							 </tr>
						  </table>
					 </td>
				  </tr>
				  <tr>
					  <td style="text-align:center; vertical-align:top"><a href="<?php echo SITE_URL.'/postulaciones' ?>" target="_blank" title="Historial de Postulaciones"><img src="<?php echo $this->S('/images/emailing/btn_historial.jpg');?>" width="207" height="35" style="border:0" /></a></td>
				  </tr>
				  <tr>
					  <td style="text-align:center; vertical-align:top; border-bottom:1px solid #999; color:#666;font-family:Arial, Helvetica, sans-serif; font-size:12px; line-height:14px;margin:0; padding:5px 0 30px;">Revisa el historial y el estado de tus postulaciones.</td>
				  </tr>
				  <tr>
					  <td style="border-bottom:1px solid #999; vertical-align:top; padding-bottom: 30px;">
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:30px 0 30px; text-align:center">Tu perfil esta al <strong><?= $this->porcentaje['total_completado'] ?>%</strong><?php echo count($this->porcentaje['total_completado'] >0)?', completa tu perfil e incrementa las posibilidades':''?>.</p>
				<?php if(count($this->incompletos) > 0){?>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding: 0 20px 20px;">Tips para completar tu perfil</p>
						<?php foreach ($this->incompletos as $x){?>
								<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding: 0 20 0 20px;"><span style="color:#000; font-size:11px;">&gt;&gt;</span> <a style="color:#000; font-size:12px; line-height:14px; text-decoration:none;" href="<?=
										  $x['link']
										  ?>" target="_blank" title="<?= $x['item'] ?>"><?= $x['item']  ?></a> <span style="color:#FF6600; padding-left:20px">+<?=
												($x['porcentaje'])
												?>%</span></p>
				<?php }}?>
					 </td>
				  </tr>
				  <tr>
					  <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; padding-top:40px;">
						 ¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
					 </td>
				  </tr>
				</table>
		  </td>
	 </tr>
</table>
