<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">	
    <tr>
    	<td width="680px" style="padding:20px; vertical-align:top">

            
<table width="680" border="0" cellspacing="0" cellpadding="0" style="color:#333">
  <tr>
    <td style="text-align:left; padding-bottom:20px;">
        <p style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px; margin:0; padding:0 0 5px;">Hola <strong>ADMINISTRADOR</strong></p>
    </td>
  </tr>
  <tr>
    <td style="vertical-align:top">
            <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">La empresa <strong><?= $this->empresa['empresa']['razon_social']; ?></strong> con RUT <strong><?= $this->empresa['empresa']['ruc']; ?></strong> efectúo la siguiente compra a través del usuario administrador con email <strong><?php echo $this->admin['usuario']->email;?></strong>.</p>
    </td>
  </tr>
  <tr>
    <td style="padding:0 20px; vertical-align:top">
            <table width="680" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">N° de Voucher:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->datosPos['nro_voucher']; ?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Fecha de Pago:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->datosPos['fecha_pago_pos']?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Tarjeta/Banco:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->listaBancos[$this->datosPos['id_tarjeta_banco']]?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Tipo:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->listaTarjetas[$this->datosPos['id_tipo_tarjeta']]?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">N° de Lote:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->datosPos['lote']?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">ID Compra:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['id']; ?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Tipo Documento:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['tipo_doc']; ?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Fecha Compra:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['fh_creacion']?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Precio Total:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['precio_total']?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Adecsys Ente Id:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['adecsys_ente_id']; ?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Tipo Anuncio:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->compra['tipo_anuncio']?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">IP Origen:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ip?></td>
          </tr>
        </table>                	
    </td>
  </tr>  
  <tr>
    <td style="vertical-align:top">
            <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">Activar el aviso en EMPLEOBUSCO desde <a style="color:#009FEB; font-size:14px; line-height:16px; text-decoration:none;" href="<?=SITE_URL.'/activar-aviso/'.$this->token?>" target="_blank" title="Activar Aviso">Activar Aviso</a></p>
    </td>
  </tr>  
  <tr>
    <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px; padding-top:40px;">
            ¡Éxitos!<br><br><strong>El equipo EMPLEOBUSCO</strong>.
    </td>
  </tr>
</table>



        </td>
    </tr>
    
</table>