<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="font-family:arial;font-size:14px">
    <tr>
    	<td colspan="3" valign="top" style="padding:10px">
        	<p>Estimado <strong><?=$this->nombre_anterior?></strong></p>
        </td>
    </tr>
    <tr>
    	<td colspan="3" valign="top" style="padding:10px">
        	<p>Se ha asignado a <strong><?=$this->nombre?></strong> como nuevo administrador secundario del proceso</p>
            <h2 style="margin-left:50px"><strong><?=$this->puesto?></strong></h2>
            <p>Para cualquier otra modificación en los administradores de procesos, ingresar a:</p>
            <h4 style="margin-left:50px;font-weight:200">Mi Cuenta > Mis Datos > <a href="<?=SITE_URL?>/empresa/administrador" style="color:#5FAFE3">Administradores</a></h3>
        </td>
    </tr>
</table>