<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">
    <tr>
    	<td width="720px" style="padding:20px;">
        	<table width="720" border="0" cellspacing="0" cellpadding="0" style="color:#333">
              <tr>
              	<td>
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:22px;margin:0; padding:0 0 30px;">Hola <strong><?php echo $this->nombre ?></strong></p>
                </td>
              </tr>
              <tr>
              	<td>

                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 30px;">
                            Su solicitud de <strong><?php echo $this->nombrePuesto ?></strong> en <?php echo ($this->mostrarEmpresa == 1)?"la empresa <strong>$this->nombreEmpresa":"la empresa con alias <strong>'$this->nombreComercial'"?></strong> ha sido vista. Esto indica que el director de Recursos Humanos puede estar interesado en ponerse en contacto con usted, aunque no podemos garantizar una respuesta.</p>
                </td>
              </tr>
              <tr>
              	<td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; padding-top:60px;">
                	¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
                </td>
              </tr>
            </table>
        </td>
    </tr>
</table>
