<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">	
    <tr>
    	<td width="680px" style="padding:20px; vertical-align:top">

            
<table width="680" border="0" cellspacing="0" cellpadding="0" style="color:#333">
  <tr>
    <td style="text-align:left; padding-bottom:20px;">
        <p style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px; margin:0; padding:0 0 5px;">Hola <strong>ADMINISTRADOR</strong></p>
    </td>
  </tr>
  <tr>
    <td style="vertical-align:top">
            <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">Se activo la compra con ID <strong><?= $this->compra['id']; ?></strong> y N° de Voucher <strong><?= $this->compra['nro_voucher']; ?></strong>.</p>
    </td>
  </tr>
  <tr>
    <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px; padding-top:40px;">
            ¡Éxitos!<br><br><strong>El equipo EMPLEOBUSCO</strong>.
    </td>
  </tr>
</table>



        </td>
    </tr>
    
</table>