<table cellspacing="0" cellpadding="0" border="0" align="center" width="760" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px">
	<tbody>
    <tr>
    	<td width="680px" style="padding:20px; vertical-align:top">
        	<table cellspacing="0" cellpadding="0" border="0" width="680" style="color:#333">
            <tbody><tr>
              	<td style="text-align:left; padding-bottom:20px;">
                	<p style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px; margin:0; padding:0 0 5px;">Hola <strong>ADMINISTRADOR</strong></p>
                </td>
              </tr>
              <tr>
              	<td style="vertical-align:top">
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">El usuario "<?php echo $this->usuario;?>" registró cambios un Plan de Membresía de la Empresa "<?php echo $this->empresa;?>".</p>
                </td>
              </tr>

              <tr>
              	<td style="padding:0 20px; vertical-align:top">
                	<table cellspacing="1" cellpadding="0" border="0" width="300" style="background-color:#069">
                      <tbody>
                      <tr>
                        <td style="vertical-align:top;">
                        	<table cellspacing="0" cellpadding="0" border="0" width="300">
                              <tbody><tr>
                                <td width="110" style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:5px 0 5px 10px; vertical-align:top">Tipo de Plan</td>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:5px 0; vertical-align:top">: <?php echo $this->planMembresia;?></td>
                              </tr>
                              <tr>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 5px 10px; vertical-align:top">Estado</td>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px; vertical-align:top">: <?php echo $this->estado;?></td>
                              </tr>
                              <tr>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 5px 10px; vertical-align:top">Vigencia</td>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px; vertical-align:top">: <?php echo $this->vigencia;?></td>
                              </tr>
                              <tr>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; font-weight:700; line-height:18px;margin:0; padding:0 0 5px 10px; vertical-align:top">Monto</td>
                                <td style="background-color:#fff;font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 5px; vertical-align:top">: $ <?php echo $this->monto;?></td>
                              </tr>
                            </tbody></table>
                        </td>

                      </tr>
                    </tbody></table>
                </td>
              </tr>
              <tr>
              	<td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px; padding-top:40px;">
                	¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
                </td>
              </tr>
            </tbody></table>
        </td>
    </tr>

</tbody></table>
