<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">	
    <tr>
    	<td width="680px" style="padding:20px; vertical-align:top">

            
<table width="680" border="0" cellspacing="0" cellpadding="0" style="color:#333">
  <tr>
    <td style="text-align:left; padding-bottom:20px;">
        <p style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px; margin:0; padding:0 0 5px;">Hola <strong>ADMINISTRADOR</strong></p>
    </td>
  </tr>
  <tr>
    <td style="vertical-align:top">
            <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">La empresa <strong><?= $this->razonSocial; ?></strong> compró el Plan de Membresía <strong><?php echo $this->nombreMembresia;?></strong>. Crear el contrato en Adecsys y luego activar el Plan de Membresía en EMPLEOBUSCO desde <a style="color:#009FEB; font-size:14px; line-height:16px; text-decoration:none;" href="<?=SITE_URL.'/activar-membresia/'.$this->token?>" target="_blank" title="Activar Membresía">Activar Membresía</a></p>
    </td>
  </tr>

  <tr>
    <td style="padding:0 20px; vertical-align:top">
            <table width="680" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">RUT:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ruc; ?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Ente:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ente?></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Fecha de Pago:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->fechaPago?></td>
          </tr>
          
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"></td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top;font-weight: bold;" colspan="4">Tiempo de vigencia del contrato :</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"></td>
          </tr>
          <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"></td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"></td>
          </tr>
           <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Inicio de Plan:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->fini?></td>
          </tr>
           <tr>
            <td width="140" style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Fin de Plan:</td>
            <td style="color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ffin?></td>
          </tr>
        </table>                	
    </td>
  </tr>
  <tr>
    <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px; padding-top:40px;">
            ¡Éxitos!<br><br><strong>El equipo EMPLEOBUSCO</strong>.
    </td>
  </tr>
</table>



        </td>
    </tr>
    
</table>