<table width="760" cellspacing="0" cellpadding="0" border="0" align="center" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px">
	<tbody>
    <tr>
    	<td width="680px" style="padding:20px; vertical-align:top">
        	<table width="680" cellspacing="0" cellpadding="0" border="0" style="color:#333">
            <tbody><tr>
              	<td style="text-align:left; padding-bottom:20px;">
                	<p style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:16px; margin:0; padding:0 0 5px;">Hola </p>
                </td>
              </tr>
              <tr>
              	<td style="text-align:left; vertical-align:top">
                	<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 20px;">La empresa <strong><?php echo $this->razonSocial; ?></strong> compró el Plan de Membresía <strong><?php echo $this->nombreMembresia; ?></strong> desde el Portal.<br>Generar la Factura.</p>
                </td>
              </tr>

              <tr>
              	<td style="padding:0 20px; vertical-align:top">

                	<table width="640" cellspacing="0" cellpadding="0" border="0">
                      <tbody><tr>
                        <td style="vertical-align:top">
                        	<table width="320" cellspacing="0" cellpadding="0" border="0">
                              <tbody><tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Plan:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->descripcionMembresia; ?></td>
                              </tr>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Adecsys:</td>
                                <td style="text-align:left; color:#009FEB;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->adecsys; ?></td>
                              </tr>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Contrato:</td>
                                <td style="text-align:left; color:#009FEB;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->nroContrato; ?></td>
                              </tr>
                              <?php if($this->tokenCompra==null || $this->tokenCompra=='') : ?>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:20px 0 7px;vertical-align:top">Pagado:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:20px 0 7px;vertical-align:top">CIP - <?php echo $this->cip; ?></td>
                              </tr>
                              <?php else : ?>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:20px 0 7px;vertical-align:top">Pagado:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:20px 0 7px;vertical-align:top">Token - <?php echo $this->tokenCompra; ?></td>
                              </tr>
                              <?php endif; ?>
                               <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Importe:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">$ <?php echo number_format($this->importe, 2, '.', ','); ?></td>
                              </tr>
                            </tbody></table>
                        </td>
                        <td style="vertical-align:top">
                        	<table width="320" cellspacing="0" cellpadding="0" border="0">
                              <tbody><tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">RUT:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ruc; ?></td>
                              </tr>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Ente:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->ente; ?></td>
                              </tr>
                              <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Razón Social:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->razonSocialCompraEmpresa; ?></td>
                              </tr>
                               <tr>
                                <td width="110" style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top">Fecha de Pago:</td>
                                <td style="text-align:left; color:#333;font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px;margin:0; padding:0 0 7px;vertical-align:top"><?php echo $this->fechaPago; ?></td>
                              </tr>
                            </tbody></table>
                        </td>
                      </tr>
                    </tbody></table>

                </td>
              </tr>
              <tr>
              	<td style="text-align:left; font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:16px; padding-top:40px;">
                	¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
                </td>
              </tr>
            </tbody></table>
        </td>
    </tr>

</tbody></table>
