<br><P align=center><font size=3>
<b>¡ EMPLEOBUSCO le da la Bienvenida a <?=$this->empresa?>!</b></font></P>
<br>
Tus datos de acceso son: <BR>
<span style="color:#000000;font-size:13px"><b>Usuario    : </b></span><span style="color:#3366ff;font-size:13px"><b><?=$this->to?></b></span><BR>
<br><br>
Su empresa acaba de unirse al más importante portal de empleos del Perú, ingresa a <span align=center style="color:#3366ff"><b><?=SITE_URL?>/empresa</b></span> y podrá:
<br><br>
</td></tr>
<tr><td>

<table cellpadding=0 cellspacing=0 width="90%" align=center>
<tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Publicar desde la Web anuncios de empleo en el Suplemento EMPLEOBUSCO 
del diario La Prensa.
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Administrar sus Procesos de selección en el menor tiempo y de una manera
práctica y eficiente.
</td></tr><tr><td valign=top><li></td>
<td style="text-align:justify;font-family:verdana;font-size:12px">
Acceder a la mejor y más grande Base de Datos de Candidatos del país.
</td></tr></table>

</td></tr>   
<tr><td style="text-align:justify;font-family:verdana;font-size:12px">
<br><br>
<P align=center style="color:#3366ff"><a href="<?=SITE_URL?><?= $this->url(array('module' => 'empresa', 'controller' => 'publica-aviso', 'action' => 'paso1'), 'default', true) ?>"><b>Publicar Aviso</b></a></P>
<br>¡Gracias por anunciar en EMPLEOBUSCO!
<br><br>