<?php $recuperarClave = $this->url(array('module' => 'postulante', 'controller' => 'auth', 'action' => 'generar-clave', 'key' => $this->urlToken), 'default', true) ?>
<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
        <td height="32"></td>
    </tr>
    
    <tr>
        <td align="left" style="font-weight:bold;font-size:32px;color:#100F0F;">Hola <?=$this->nombre?>:</td>
    </tr>
    
    <tr>
        <td height="20"></td>
    </tr>
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1">
            <?=$this->empresa?> te ha asignado como Administrador secundario en <a href="<?= SITE_URL?>" style="color: #007FD2;">EMPLEOBUSCO.com</a>
        </td>
    </tr>
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1"><br>
            Tu usuario es : <a style="color: #007FD2;text-decoration:none;" href="#"><?=$this->to?></a><br/>
            Tu contraseña temporal es : <?=$this->pswd?>
        </td>
    </tr>
    
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1"><br>
            Para acceder a tu cuenta puedes ingresar desde el siguiente enlace <a href="<?= SITE_URL.'/empresa/mi-cuenta'?>" style="color: #007FD2;">Mi Cuenta</a><br>
            Ten en cuenta que puedes modificar tu contraseña en cualquier momento <br>
            desde <a href="<?= SITE_URL.'/empresa/mi-cuenta/cambio-clave'?>" style="color: #007FD2;">Mis Datos</a> en EMPLEOBUSCO.com
        </td>
    </tr>
    
    <tr>
        <td height="25"></td>
    </tr>
    
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
       cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="center" width="750" style="padding-left:0px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif"><span style="font-weight: normal;">El equipo</span> EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>
