<? $urlPP = $this->url(array('slug' => $this->slug), 'perfil_publico', true); ?>
<table width="760" border="0" cellspacing="0" cellpadding="0" style="color:#666; background-color:#fff; font-family:Arial, Helvetica, sans-serif; font-size:12px" align="center">
	 <tr>
		 <td width="680px" style="padding:20px;">
			  <table width="680" border="0" cellspacing="0" cellpadding="0" style="color:#333">
				  <tr>
					  <td style="text-align:center; padding-bottom:40px;">
						 <h2 style="color: #333; font-family:Arial, Helvetica, sans-serif; font-size:20px; line-height:22px; margin:0; padding:0 0 5px;"><?= $this->nombre ?>,</h2>
					<p style="font-family:Arial, Helvetica, sans-serif; font-size:27px; line-height:29px; margin:0; padding:0">ya eres parte de <strong>AquiEmpleos</strong></p>
					 </td>
				  </tr>
				  <tr>
					  <td>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0 0 30px;">Ahora perteneces al portal de empleos más importante: <a href="<?=SITE_URL?>" style="color:#00577F; text-decoration:none;" target="_blank"><?=SITE_URL?></a> donde encontrarás las mejores ofertas de trabajo, de las más prestigiosas empresas del país.</p>
					 </td>
				  </tr>
				  <tr>
					  <td>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0;">Tus datos de acceso son:</p>
						  <p style="font-family:Arial, Helvetica, sans-serif; font-size:17px; line-height:22px;margin:0; padding:0 0 30px;">Usuario: <span style="color:#00577F"><?= $this->user ?></span></p>
					 </td>
				  </tr>
				  <tr>
					  <td>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0;">Ya cuentas con tu Perfil Público, el cual puedes compartir con quien desees y podrás acceder a él directamente en:</p>
						<p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:5px 0 30px;"><a style="color:#00577F; font-size:18px; line-height:21px; text-decoration:none;" target="_blank" href="<?= SITE_URL ?><?= $urlPP ?>" ><?= SITE_URL ?><?= $urlPP ?></a></p>
					 </td>
				  </tr>
				  <tr>
					  <td>
						 <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:0;">Te aconsejamos mantener siempre actualizado tu perfil en el portal. Mientras más completo esté tu perfil, tendrás más oportunidades de ser considerado y encontrado por las empresas.</p>
						  <p style="font-family:Arial, Helvetica, sans-serif; font-size:14px; line-height:18px;margin:0; padding:5px 0 30px;"><span style="color:#00577F; font-size:12px;">&gt;&gt;</span> <a style="color:#00577F; font-size:18px; line-height:21px; text-decoration:none;" href="<?= SITE_URL ?><?= $this->url(array('controller' => 'buscar', 'action' => 'index'), 'default', true) ?>" target="_blank" title="Ver más ofertas de trabajo">Ver más ofertas de trabajo</a></p>
					 </td>
				  </tr>
				  <tr>
					  <td style="font-family:Arial, Helvetica, sans-serif; font-size:15px; line-height:18px; padding-top:60px;">
						 ¡Éxitos!<br><br><strong>El equipo AquiEmpleos</strong>.
					 </td>
				  </tr>
				</table>
		  </td>
	 </tr>
	 <tr>
</table>
