<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <style type="text/css">
        body{
            box-sizing: border-box;
        }
    </style>
</head>
<body style="margin:0">
    <header style="border-bottom:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table style="width:100%">
            <tr>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-google-plus" aria-hidden="true"></i>
            </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-twitter" aria-hidden="true"></i>
            </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-facebook" aria-hidden="true"></i>
            </td>
        </table>
    </header>
    <section style="font-family: gotham,arial,sans-serif;max-width: 750px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
            <table>
                <tr>
                    <td style="padding: 1.5em 0;">Hola <span style="font-weight:bold;">Micaela</span></td>
                </tr>
                <tr>
                    <td style="padding-bottom:1em;">Has realizado satisfactoriamente la publicación de tu aviso Simple en AquiEmpleos. Puedes revisar tu publicación aqui:</td>
                </tr>
            </table>
            <table style="border-collapse: collapse;width:100%" >
                <tr>
                    <td style="width:30%"></td>
                    <td style="border:1px solid #2A5E9A;width: 40%;height: 240px;display:table-cell;padding:1em;text-align:center">
                        <img src="" alt="" width="80%" />
                    </td>
                    <td style="width:30%"></td>
                </tr>
                <tr>
                    <td style="width:30%"></td>
                    <td style="border:1px solid #2A5E9A;width: 40%;height: 50px;text-align:center;background:#2A5E9A;color:white;padding:1em;">EJECUTIVOS DE CRÉDITOS PARA JUIGALPA</td>
                    <td style="width:30%"></td>
                </tr>
                <tr style="height:20px;"></tr>
                <tr>
                    <td style="width:30%"></td>
                    <td style="text-align:center;width: 40%; padding:2em 0;">
                        <a href="" style="background:#2A5E9A;padding:0.5em 1em;color:white;text-decoration:none;border-radius:8px;">Ver Anuncio</a>

                    </td>
                    <td style="width:30%"></td>
                </tr>
            </table>
            <table style="text-align:center;margin:3em 0 2em 0;" width="100%">
                <tr>
                    <td style="">Saludos cordiales,</td>
                </tr>
                <tr>
                    <td style="font-weight:bold">Equipo AquiEmpleos</td>
                </tr>
            </table>
    </section>
    <footer style="border-top:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table width="100%" style="text-align:center">
            <tr>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
            </tr>
        </table>
    </footer>
</body>
