<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <style type="text/css">
        body{
            font-family: scfly;
            box-sizing: border-box;
        }
    </style>
</head>
<body style="margin:0">
    <header style="border-bottom:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table style="width:100%">
            <tr>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-google-plus" aria-hidden="true"></i>
            </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-twitter" aria-hidden="true"></i>
            </td>
            <td style="width:40px;height:40px;border-radius:50%;background:#2A5E9A;font-size:1em;">
                <i class="fa fa-facebook" aria-hidden="true"></i>
            </td>
        </table>
    </header>
    <section>
        <div style="font-family: gotham,arial,sans-serif;max-width: 750px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
            <table>
                <tr>
                    <td style="padding: 1.5em 0;">Hola Micaela:</td>
                </tr>
                <tr>
                    <td style="padding-bottom:1em;">Se ha relaizado correctamente el apgo de la publicación de tu aviso + Título del Aviso en el portal de AquiEmpleos</td>
                </tr>
                <tr>
                    <td style="padding-bottom:1em;">Puedes revisar tu publicación en el siguiente enlace: <a href="#" style="text-decoration:none; color:#2A5E9A">Ver Aviso</a></td>
                    </tr>
            </table>
            <table style="border-collapse: collapse;width: 100%;" >
                <tr>
                    <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos del usuario</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Nombres / Razón Social:</td>
                    <td style="padding: 0.5em 1em;">Email</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Nombres + Apellido:</td>
                    <td style="padding: 0.5em 1em;">ejemplo@email.com</td>
                </tr>
                <tr>
                    <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de Facturación</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Número de Factura:</td>
                    <td style="padding: 0.5em 1em;">555555</td>

                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Monto:</td>
                    <td style="padding: 0.5em 1em;">$ 525</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">tipo de Documento:</td>
                    <td style="padding: 0.5em 1em;">RUT</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Número de Documento:</td>
                    <td style="padding: 0.5em 1em;">21324568787</td>
                </tr>
                <tr>
                    <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de la Transacción</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Número de transacción:</td>
                    <td style="padding: 0.5em 1em;">555555</td>


                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Medio de Pago:</td>
                    <td style="padding: 0.5em 1em;">Punto Facil</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Fecha y Hora:</td>
                    <td style="padding: 0.5em 1em;">07/10/2016 - 14:35hrs</td>
                </tr>
                <tr>
                    <td colspan="2" style="border: 1px solid #2A5E9A;background:#2A5E9A;color:white;padding: 0.5em 1em;">Datos de Publicación</td>
                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Medio de Publicación:</td>
                    <td style="padding: 0.5em 1em;">Web</td>

                </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Tipo de Aviso Web:</td>
                    <td style="padding: 0.5em 1em;">web Destacado plata</td>
                    </tr>
                <tr style="border: 1px solid #1e8048;">
                    <td style="padding: 0.5em 1em;color:#2A5E9A">Tipo de Aviso Impreso:</td>
                    <td style="padding: 0.5em 1em;">Lineal</td>
                </tr>
                </table>
                <table style="text-align:center;margin:3em 0 2em 0;" width="100%">
                    <tr>
                        <td style="">Saludos cordiales,</td>
                    </tr>
                    <tr>
                        <td style="font-weight:bold">Equipo AquiEmpleos</td>
                    </tr>
                </table>
        </div>
    </section>
    <footer style="border-top:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table width="100%" style="text-align:center">
            <tr>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
                <td>
                    <img src="<?php echo $this->S('/images/email-logo/empleo_209x150.jpg');?>" width="207" height="35" />
                </td>
            </tr>
        </table>
    </footer>
</body>
