<table width="90%" style="margin: 10px 0px 0px 10px" align="center" border="0">
	 <tr><td height="25"></td></tr>
		<tr><td align="center" style="font-weight:bold;font-size:16px;">
		  </td></tr>
	 <tr>
		  <td align="center" style="font-weight:bold;font-size:35px;"><span style="color:#100F0F;">Su proceso de "<?= $this->nombrePuesto ?>"</span><br /><span style="color:#C50606;">está por vencer en <?= $this->dias ?> día<?= ($this->dias > 1 ? 's' : ''); ?> </span></td>
	 </tr>
	 <tr><td height="10"></td></tr>
	 <tr>
		  <td align="center">
				<table style="font-size: 14px;font-weight:bold;">
					 <tr>
						  <td width="75">Empresa</td>
						  <td>:</td><td>
								<a style="color: #007FD2;text-decoration:none;" href="#"><?= $this->empresa ?></a>
						  </td>
					 </tr>
					 <tr>
						  <td>Usuario</td>
						  <td>:</td><td>
								<a style="color: #007FD2;text-decoration:none;" href="#"><?= $this->usuario ?></a>
						  </td>
					 </tr>
				</table>
		  </td>
	 </tr>
	 <tr><td height="6" colspan="2"></td></tr>
	 <tr>
		  <td colspan="2" align="center" style="font-size: 15px;padding-left:35px;padding-right:35px;">
				El proceso de Selección para el puesto de <span style="color:#007FD2"><b>"<?= $this->nombrePuesto ?>"</b></span> que se inició el <?= $this->FechaFullEspanol($this->fechaPub) ?> caduca el próximo <?= $this->FechaFullEspanol($this->fechaVenc) ?>. Cuando el proceso vence su empresa ya no podrá visualizar a los postulantes que aplicaron al aviso.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a style="color: #007FD2;" href="<?= SITE_URL . '/empresa/mis-procesos/index/extender/' . $this->urlId ?>#winExtendN">Extender mi proceso</a>
		  </td>
	 </tr>
	 <tr><td height="5" colspan="2"></td></tr>
	 <tr><td height="15"></td></tr>
	 <tr>
		  <td style="padding-left:35px;padding-right:35px;">
				<table width="100%" style="font-size:13px;">
					 <tr>
						  <td width="54%" valign="top">Si quiere tener más postulantes a su proceso tiene la opción de Re-Comprar el aviso que estuvo asociado al proceso.<br /><a style="color: #007FD2;" href="<?= SITE_URL ?><?= $this->url(array('republica' => $this->avisoId), 'republica_aviso', true) ?>">Recomprar aviso</a></td>
						  <td width="6%"></td>
						  <td width="50%" valign="top">Inicie otro proceso:<br /><a style="color: #007FD2;" href="<?= SITE_URL . '/empresa/publica-aviso/paso1' ?>">Publicar un aviso</a></td>
					 </tr>
				</table>
		  </td>
	 </tr>
	 <tr><td height="8"></td></tr>
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff"
		 cellspacing="0" cellpadding="0" border="0">
	 <tr>
		  <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;">
				<h1 style="padding-right: 0px; padding-left: 0px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
					 <span style="color:#000;font-family: Arial, Helvetica, sans-serif">&iexcl;Gracias por anunciar en AquiEmpleos!</span> 
				</h1>
		  </td>
	 </tr>
</table>
