<?php $perfilPublico = $this->url(array('module' => 'postulante', 'controller' => 'mi-cuenta', 'action' => 'perfil-publico', 'slug' => $this->slug), 'perfil_publico', true) ?>
<?php $recuperarClave = $this->url(array('module' => 'postulante', 'controller' => 'auth', 'action' => 'generar-clave', 'key' => $this->urlToken), 'default', true) ?>
<table cellspacing="0" border="0" cellpadding="0" width="750">
    <tr><td>&nbsp;</td></tr>
    <tr>
        <td valign="top" align="center" colspan="2" style="text-align: center">
            <table width="100%" style="margin:0" align="center" border="0">
                <tr>
                    <td align="center" style="color:#5a5658; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-weight:bold;font-size:32px; line-height:1">
                        <span style="color:#000000;font-size:32px; line-height:1">Cambio de Contrase&ntilde;a en EMPLEOBUSCO</span>
                    </td>
                </tr>
                <tr>
                    <td align="center" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1"><span><?= $this->nombre ?></span>, para cambiar tu contrase&ntilde;a en EMPLEOBUSCO haz click en el siguiente enlace: 
                        <br/><span><a href="<?= SITE_URL ?><?= $recuperarClave ?>" style="color: #007FD2;"><?= SITE_URL ?><?= $recuperarClave ?></a></span></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="color:#514f50; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:16px; line-height:1">
                        Te recordamos que cuentas con un Perfil P&uacute;blico, el cual puedes compartir con quien desees y podr&aacute;s acceder a &eacute;l directamente en :
                        <br/><span><a href="<?= SITE_URL ?><?= $perfilPublico ?>" style="color: #007FD2;"><?= SITE_URL ?><?= $perfilPublico ?></a></span>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td align="center" style="padding-left:20px;">
                        <table width="92%" cellspacing="5" border="0" cellpadding="2" style="font-size:14px;">
                            <tr>
                                <td valign="top" width="2%" style="color:#514f50; font-family:Arial, Helvetica, sans-serif">&raquo;</td>
                                <td valign="top" width="45%" style="color:#514f50; font-family:Arial, Helvetica, sans-serif">Te aconsejamos mantener siempre actualizado tu perfil en el portal, es muy importante.
                                </td>
                                <td valign="top" width="2%" style="color:#514f50; font-family:Arial, Helvetica, sans-serif">&raquo;</td>
                                <td valign="top" width="45%" style="color:#514f50; font-family:Arial, Helvetica, sans-serif">Mientras m&aacute;s completo est&eacute; tu perfil, tendr&aacute;s m&aacute;s oportunidades de ser considerado en tus postulaciones.
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
            </table>
        </td>
    </tr>
    <tr></tr>
</table>
<table align="center" cellspacing="0" cellpadding="0" border="0" width="750">
    <tr>
        <td>
            <table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <td align="left" width="750" style="padding-left:30px;padding-bottom:10px;"><h1 style="padding-right: 0px; padding-left: 20px; font-family:'Arial, Helvetica, sans-serif';font-weight: bold; font-size: 20px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                            <span style="color:#232222; font-weight:normal; font-size:24px; font-family: Arial, Helvetica, sans-serif">&iexcl;&Eacute;xitos! </span>
                            <span style="color:#000000; font-family: Arial, Helvetica, sans-serif"> El equipo EMPLEOBUSCO</span> </h1>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
