<?php $recuperarClave = $this->url(array('module' => 'postulante', 'controller' => 'auth', 'action' => 'generar-clave', 'key' => $this->urlToken), 'default', true) ?>
<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr><td height="32"></td></tr>
    <tr>
        <td align="center" style="font-weight:bold;font-size:34px;color:#100F0F;">Cambio de Contrase&ntilde;a en EMPLEOBUSCO</td>
    </tr>
    <tr><td height="10"></td></tr>
    <tr>
        <td align="center" style="font-size: 15px;padding-left:80px;padding-right:80px;">
            <span style="font-weight: bold;"><?= $this->nombre ?>, para cambiar tu contraseña en EMPLEOBUSCO haz click en el siguiente enlace:</span><br />
            <a style="color: #007FD2;text-decoration:none;" href="<?= SITE_URL ?><?= $recuperarClave ?>" alt="URL Token"><?= SITE_URL ?><?= $recuperarClave ?></a>
        </td>
    </tr>
    <tr><td height="10"></td></tr>
</table>
<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="left" valign="top" width="750" style="padding-left:90px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl; &Eacute;xitos !</span><br />
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo EMPLEOBUSCO</span> 
            </h1> 
        </td>
    </tr>
</table>
