<?php $recuperarClave = $this->url(array('module' => 'postulante', 'controller' => 'auth',
	 'action' => 'generar-clave', 'key' => $this->urlToken), 'default', true)
?>
<table width="630" style="font-size:13px">
	 <tr>
		  <td width="100%" height="50" style="font:15px Verdana"><strong>Sres. <?=$this->empresa?></strong></td>
	 </tr>
	 <tr>
		  <td height="32" style="font:15px Verdana">Para cambiar la contraseña de su cuenta en AquiEmpleos, asociada a la empresa debe hacer click en el siguiente enlace:</td>
	 </tr>
	 <tr>
		  <td><a style="color: #007FD2;text-decoration:none;" href="<?= SITE_URL ?><?= $recuperarClave ?>" alt="URL Token"><?= SITE_URL ?><?= $recuperarClave ?></a></td>
	 </tr>
	 <tr>
		  <td height="70">&nbsp;</td>
	 </tr>
	 <tr>
		  <td><strong>&iexcl;&Eacute;xitos!</strong></td>
	 </tr>
	 <tr>
		  <td height="43" style="font:15px Verdana"><strong>El equipo AquiEmpleos</strong></td>
	 </tr>
	 <tr>
		  <td>&nbsp;</td>
	 </tr>
</table>
