<table width="90%" style="margin: 10px 0px 0px 10px" align="center" border="0">
	<tr><td height="25"></td></tr>
   	<tr><td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1">
	Hola <?= $this->nomUsuEmpresa?>,<br>
               <?= $this->nombre?> ha respondido a tu consulta para el Proceso <b><?= $this->nombrePuesto ?></b> </td></tr>

    <tr><td height="10"></td></tr>
    <tr>
        <td align="left" style="color:#030303; padding:0 30px; font-family:Arial, Helvetica, sans-serif; font-size:18px; line-height:1">
            <span>Puedes ver la respuesta de la misma en el siguiente enlace: <a style="font-size:14px;color: #007FD2;" href="<?=SITE_URL?><?= $this->url(array('module'=>'empresa','controller'=>'mis-procesos', 'action'=> 'mensajes','postulacion'=>$this->id_postulacion),'default', true);?>">Ver respuesta</a><br><br></span>
        </td>
    </tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff"
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 0px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl; &Eacute;xitos !<br></span>&nbsp;
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">El equipo AquiEmpleos</span> 
            </h1>
        </td>
    </tr>
</table>
