<table width="700" style="font-size:13px">
    <tr>
        <td height="50" colspan="4" style="font:15px Verdana"><strong><?php echo $this->nombre_empresa; ?>(<?php echo $this->Nombre_Comercial?>)</strong></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="4"><strong>Su plan Membresía EMPLEOBUSCO Selecto está por vencer en <span style="color:#CC0C0C;font-size:30px;"><?php echo $this->nrodias; ?></span> días.</strong></td>
    </tr>
    <tr style="font-size:16px">
        <td width="6%" height="31" valign="middle">&nbsp;</td>
        <td width="24%" valign="middle">Inicio Plan :</td>
        <td colspan="2" valign="middle"><strong><?php echo $this->fecini; ?></strong></td>
    </tr>
    <tr style="font-size:16px">
        <td height="29" valign="middle">&nbsp;</td>
        <td valign="middle">Fin del Plan :</td>
        <td colspan="2" valign="middle"><strong><?php echo $this->fecfin; ?></strong></td>
    </tr>
    <tr style="font-size:16px">
        <td height="30" valign="middle">&nbsp;</td>
        <td valign="middle">Usuario :</td>
        <td colspan="2" valign="middle"><strong><a style="color: #007FD2;text-decoration:none;" href="#"><?php echo $this->email; ?></a></strong></td>
    </tr>
    <tr>
        <td colspan="2"></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td height="31" colspan="4"><strong>Te estaremos contactando para que puedas seguir obteniendo los siguientes beneficios:</strong></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Avisos Ilimitados</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Prioridad en Ubicación del aviso sobre los avisos Plan Esencial</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Acceso a la base de datos (Búsqueda en EMPLEOBUSCO)</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Bolsa de CVs</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Trabaje con Nosotros</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">6 Evaluaciones EMPLEOBUSCO Match</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">04 Avisos Impresos de Imagen Marca Empleador en el Suplemento EMPLEOBUSCO</td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3">Descuentos en Avisos Impresos ( 6% en EMPLEOBUSCO La Prensa y 8% en EMPLEOBUSCO El Talan)</td>
    </tr>
    <tr>
        <td height="72">&nbsp;</td>
        <td>&nbsp;</td>
        <td width="35%"><a style="background:#FF0088; border:1px solid #9F1D63; color: #FFF; padding:8px 10px; display:block; text-decoration:none; margin:10px; text-align:center; font-size:16px; font-weight:bold" href="<?= SITE_URL . '/empresa/#loginP' ?>">Ingresar a tu cuenta</a></td>
        <td width="35%">&nbsp;</td>
    </tr>
    <tr>
        <td height="73" colspan="4"><strong>Contáctenos: 311-6500 Anexos 3726 / 2146</strong></td>
    </tr>
    <tr>
        <td colspan="4"><strong>&iexcl;&Eacute;xitos!</strong></td>
    </tr>
    <tr>
        <td height="43" colspan="4" style="font:15px Verdana"><strong>El equipo EMPLEOBUSCO</strong></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
</table>