<table width="700" style="font-size:13px">
    <tr>
        <td height="50" colspan="4" style="font:15px Verdana"><strong><?php echo $this->nombre_empresa; ?>(<?php echo $this->Nombre_Comercial?>)</strong></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="4"><strong>Su plan Membresía EMPLEOBUSCO Esencial está por vencer en <span style="color:#CC0C0C;font-size:30px;"><?php echo $this->nrodias; ?></span> días.</strong></td>
    </tr>
    <tr style="font-size:16px">
        <td height="31" valign="middle">&nbsp;</td>
        <td width="24%" valign="middle">Inicio Plan :</td>
        <td colspan="2" valign="middle"><strong><?php echo $this->fecini; ?></strong></td>
    </tr>
    <tr style="font-size:16px">
        <td height="29" valign="middle">&nbsp;</td>
        <td valign="middle">Fin del Plan :</td>
        <td colspan="2" valign="middle"><strong><?php echo $this->fecfin; ?></strong></td>
    </tr>
    <tr style="font-size:16px">
        <td height="30" valign="middle">&nbsp;</td>
        <td valign="middle">Usuario :</td>
        <td colspan="2" valign="middle"><strong><a style="color: #007FD2;text-decoration:none;" href="#"><?php echo $this->email; ?></a></strong></td>
    </tr>
    <tr>
        <td colspan="2"></td>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td height="31" colspan="4"><strong>Te estaremos contactando para que puedas seguir obteniendo los siguientes beneficios:</strong></td>
    </tr>
    <tr>
        <td width="6%" valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>Avisos Ilimitados</em></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>Prioridad en Ubicación del aviso sobre los avisos sueltos y gratuitos</em></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>Acceso a la base de datos (Búsqueda en  EMPLEOBUSCO)</em></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>3 Evaluaciones EMPLEOBUSCO Match</em></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>02 Avisos Impresos de Imagen Marca Empleador en el Suplemento EMPLEOBUSCO (La Prensa y/o El Talán del Diario El Trome)</em></td>
    </tr>
    <tr>
        <td valign="top" align="right">&raquo;</td>
        <td colspan="3"><em>Descuentos en Avisos Impresos ( 4% en EMPLEOBUSCO La Prensa y 6% en EMPLEOBUSCO El Talan)</em></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td width="35%"><a style="background:#FF0088; border:1px solid #9F1D63; color: #FFF; padding:8px 10px; display:block; text-decoration:none; margin:10px; text-align:center; font-size:16px; font-weight:bold" href="<?= SITE_URL . '/empresa/#loginP' ?>">Ingresar a tu cuenta</a></td>
        <td width="35%">&nbsp;</td>
    </tr>
    <tr>
        <td height="73" colspan="4"><strong>Contáctenos: 311-6500 Anexos 3726 / 2146</strong></td>
    </tr>
    <tr>
        <td colspan="4"><strong>&iexcl;&Eacute;xitos!</strong></td>
    </tr>
    <tr>
        <td height="43" colspan="4" style="font:15px Verdana"><strong>El equipo EMPLEOBUSCO</strong></td>
    </tr>
    <tr>
        <td colspan="4">&nbsp;</td>
    </tr>
</table>