<?php if (count($this->expandible ? $this->data['visible'] : $this->data)): 
        $uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
        $purl = parse_url($uri);
        $purl['query'] = isset($purl['query']) ? $purl['query'] : '';
        parse_str($purl['query'], $vars);
        
?>
    <div class="option-list">
        <h5 class="EMPLEOBUSCO-title small">
            <i class="icon <?=$this->icon?>"></i>
            <?= $this->titulo ?>
            <span class="icon-tiny down"></span>
        </h5>
        <div class="wrap_checks open" data-type="<?=$this->param?>">
            <div class="flow-list">
            <?php
            $i = 0;
            foreach ($this->expandible ? $this->data['visible'] : $this->data as $item):
                $i++;
                $conf_programas = $this->constantes->programas;
                $conf_idiomas = $this->constantes->idiomas;
                $nombre = $item["nombre"];
                $idSubnivel=',0';
                
                if($nombre != null && $nombre != "") :
                    if(isset($vars[$this->param]) && in_array($item['id'],$vars[$this->param])) {
                        $checked = 'checked';
                    } else {
                        $checked = '';
                    }
                if ($this->titulo=='NIVEL DE ESTUDIOS' && ($item['id']== 1 || $item['id']== 2 || $item['id']== 3)  ) {
                         $idSubnivel=',0';
                } else {
                    if($this->param =='niveldeOtrosestudios' && ($item['id']== 24 || $item['id']== 23 || $item['id']== 25 || $item['id']== 28 || $item['id']== 27 || $item['id']== 26) && $this->titulo=='OTRO ESTUDIOS' ){
                       $idSubnivel=  $item['id'];
                       $item['id']='9,';
                       $idotrosestudios='otros';
                       }  
                }
                if($this->param=='niveldeestudios' &&  in_array($item['id'],array(4,8,10,13) ) && $this->titulo=='NIVEL DE ESTUDIOS'){
                    $buscador='';    
                    $idSubnivel=',0';
                    $idnethijo=$item["id"].$idSubnivel;
                    $label="<div class='ioption accord' >";
                    $label2=" </div>";
                    $labelhijo='<label class="ioption">';
                    $labelhijo2='</label>';
                    $subnivel=' <div class="more_options mL20 hide close" rel="'.$item["id"].'">';
                    $subnivel2='</div>';
                    $flecha='<span class="icon-tiny up" style="right: 0;"></span>';
                }else{
                    $idnethijo=$item["id"].$idSubnivel;
                    $buscador=''; 
                    $label="<label class='ioption' >";
                    $label2=" </label>";
                    $subnivel='';
                    $subnivel2='';
                    $flecha='';
                }?> 
                <?=$label?> 
                <?=$flecha?>
                <span class="aFilterB linkApt"><?= $this->CortarTexto($nombre, 50); ?> </span>
                <?php $idni=($this->titulo=='NIVEL DE ESTUDIOS'&&$idnethijo=='')?$idnethijo:$item["id"].$idSubnivel;?>
                 <input value="<?= $idni ?>"  name="filtroE1" type="checkbox" class="checkN <?=$buscador;?>">                      
                <?=$label2?>
                <?=$subnivel?> 
                <?=$this->Listarsubnivel($item["id"], $this->titulo,$this->param)?>
                <?=$subnivel2?>
                <?php endif;
            endforeach; ?>
            <?php
            if ($this->expandible > 0):
                ?>
                <?php
                if (count($this->data['ocultos']) > 0):
                    ?>
                    <div class="more_options hide">
                        <?php
                        foreach ($this->data['ocultos'] as $ite):
                            ?>
                            <?php
                            foreach ($ite as $item):
                                if (isset($vars[$this->param]) && in_array($item['id'],$vars[$this->param])) {
                                    $checked = 'checked';
                                } else {
                                    $checked = '';
                                }
                                
                                $i++; 
                
                    if(  $this->titulo=='NIVEL DE ESTUDIOS' && ($item['id']== 1 || $item['id']== 2 || $item['id']== 3)  ){
                         $idSubnivel=',0';
                     }else{
                        if($this->param =='niveldeOtrosestudios' && ($item['id']== 24 || $item['id']== 23 || $item['id']== 25 || $item['id']== 28 || $item['id']== 27 || $item['id']== 26) && $this->titulo=='OTRO ESTUDIOS' ){
                           $idSubnivel=  $item['id'];
                           $item['id']='9,';
                           $idotrosestudios='otros'; 
                        }
                    }
                    if($this->param=='niveldeestudios' &&  in_array($item['id'],array(4,8,10,13) ) && $this->titulo=='NIVEL DE ESTUDIOS'){
                        $buscador='';    
                        $idSubnivel=',0';
                        $idnethijo=$item["id"].$idSubnivel;
                        $label="<div class='ioption accord' >";
                        $label2=" </div>";
                        $labelhijo='<label class="ioption">';
                        $labelhijo2='</label>';
                        $subnivel=' <div class="more_options mL20 hide close" rel="'.$item["id"].'">';
                        $subnivel2='</div>';
                        $flecha='<span class="icon-tiny up" style="right: 0;"></span>';
                    }else{
                        $idnethijo=$item["id"].$idSubnivel;
                        $buscador=''; 
                        $label="<label class='ioption' >";
                        $label2=" </label>";
                        $subnivel='';
                        $subnivel2='';
                        $flecha=''; }?>               
                      <?=$label?> 
                      <?=$flecha?>
                    <span class="aFilterB linkApt"><?= $this->CortarTexto($item["nombre"], 50); ?></span>
                    <?php $idni=($this->titulo=='NIVEL DE ESTUDIOS'&&$idnethijo=='')?$idnethijo:$item["id"].$idSubnivel;?>
                    <input value="<?= $idni ?>" id="filtro<?= $this->param . $i ?>" name="filtroE56" type="checkbox" class="checkN checkbuscador">
                    <?=$label2?>
                    <?=$subnivel?> 
                    <?=$this->Listarsubnivel($item["id"], $this->titulo)?>
                     <?=$subnivel2?>
                     <?php endforeach; ?>
                     <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
            </div>
            <?php if (count($this->data['ocultos']) > 0): ?>
                <div class="wrap-btn right">
                    <a href="javascript:;" class="view-more">Ver todos</a>
                </div>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
