<?php if (count($this->expandible ? $this->data['visible'] : $this->data)): 
        $uri = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
        $purl = parse_url($uri);
        parse_str($purl['query'], $vars);
?>
<div class="option-list">
    <h5 class="EMPLEOBUSCO-title small">
        <i class="icon <?= $this->Util()->Ico_filter($this->titulo);?>"></i>
        <?= $this->titulo ?>
        <span class="icon-tiny down"></span>
    </h5>
    <div class="form-search open" data-type="<?php echo $this->param?>">
        <div class="flow-list">
            <?php 
            $i = 0;            
            if($this->titulo == 'NIVEL DE ESTUDIOS'){
                $data = array();
                foreach ($this->expandible ? $this->data['visible'] : $this->data as $ite):
                    $arrItem = explode('-',$ite['id']);
                    $data[$arrItem[0]][] = $ite;
                endforeach;
                foreach ($data as $k => $v){
                    $item = array_shift($v);
                        $i++;
                        $nombre = $item["nombre"];
                        if ($nombre != null && $nombre != "") :
                            
                            
                            if (isset($vars[$this->param]) && in_array($item["id"],$vars[$this->param])) {
                                $checked = 'checked';
                                $ver='open';
                            } else {
                                $checked = '';
                                $ver='close';
 
                            } 
                            
                        ?>
                        <?php if(in_array($k,array(1,2,3))) { ?>
                            <label class="ioption" title="<?= $nombre; ?>">
                                <?= $this->CortarTexto($nombre, 50); ?>
                                <?= (empty($item["total"]) ? "" : "<span class = 'count'>({$item["total"]})</span>")?>
                                <input rel="<?= $this->param . "/" . $item["id"] ?>" id="filtro<?= $this->param . $i ?>" name="<?php echo $this->param?>[]" type="checkbox" value="<?php echo $item["id"]?>" <?php echo $checked?>>
                            </label>
                        <?php } else {?>
            <div class='ioption accord' >
                <span class="icon-tiny up" style="right: 0;"></span>
<!--                            <label class="ioption" title="<?= $nombre; ?>">-->
                                <?= $this->CortarTexto($nombre, 50); ?>
                                <?= (empty($item["total"]) ? "" : "<span class = 'count'>({$item["total"]})</span>")?>
                                <input rel="<?= $this->param . "/" . $item["id"] ?>" id="filtro<?= $this->param . $i ?>" name="<?php echo $this->param?>[]" type="checkbox" value="<?php echo $item["id"]?>" <?php echo $checked?>>
<!--                            </label>                                        -->
                </div>  
            <?php }?>
            <?php endif; ?>
            <?php
            if (isset($vars[$this->param]) && in_array($item["id"], $vars[$this->param])) {
                $ver='open';
                $stile='style="display: block;"';
            } else {
                $ver='close';
                $stile='style="display: none;"';
            }                          
            ?>
            <div class="more_options mL20 hide <?=$ver?>" rel="<?php echo $item['id']?>" <?=$stile?>>
            <?php
                    foreach($v as $item){
                        $i++;
                        $nombre = isset($item["nombre"]) ? trim($item["nombre"]) : '';
                        if (!empty($nombre)) :
                            if (isset($vars[$this->param]) && in_array($item["id"], $vars[$this->param])) {
                                $checked = 'checked';
                                $ver='open';
                            } else {
                                $ver='close';
                                $checked = '';                            
                            }
                            ?>
                            <label class="ioption" title="<?= $nombre; ?>">
                                <?= $this->CortarTexto($nombre, 50); ?>
                                <?= (empty($item["total"]) ? "" : "<span class = 'count'>({$item["total"]})</span>")?>
                                <input rel="<?= $this->param . "/" . $item["id"] ?>" id="filtro<?= $this->param . $i ?>" name="<?php echo $this->param?>[]" type="checkbox" value="<?php echo $item["id"]?>" <?php echo $checked?>>
                            </label>
                        <?php endif; ?>
                <?php } ?>    
            </div>        
                <?php 
                }}else{
                foreach ($this->expandible ? $this->data['visible'] : $this->data as $item):
                $i++;
                $conf_programas = $this->constantes->programas;
                $conf_idiomas = $this->constantes->idiomas;
                $nombre = $item["nombre"];

                if ($nombre != null && $nombre != "") : 
                    
                    if (isset($vars[$this->param])) {
                        if(in_array($item["id"],$vars[$this->param])) {
                            $checked = 'checked';
                        } else {
                            $checked = '';
                        }
                    }
                
                
                    
                    ?>
            
               <?php 
                
             $idpadre =  strstr($item['id'], '-', true);
               if($this->param=='niveldeestudios' &&  in_array($idpadre,array(4,8,10,13) ) && $this->titulo=='NIVEL DE ESTUDIOS'){
                        $buscador='';    
                        
                        $label="<div class='ioption accord' >";
                        $label2=" </div>";
                        $labelhijo='<label class="ioption">';
                        $labelhijo2='</label>';
                        $subnivel=' <div class="more_options mL20 hide close" rel="'.$item["id"].'">';
                        $subnivel2='</div>';
                        $flecha='<span class="icon-tiny up" style="right: 0;"></span>';
                    }else{
                        $buscador=''; 
                        $label="<label class='ioption' >";
                        $label2=" </label>";
                        $subnivel='';
                        $subnivel2='';
                        $flecha='';
                    }?> 
                 <?=$label?> 
                    <?=$flecha?>
                        <?= $this->CortarTexto($nombre, 50); ?>
                        <?= (empty($item["total"]) ? "" : "<span class = 'count'>({$item["total"]})</span>")?>
                        <input rel="<?= $this->param . "/" . $item["id"] ?>" id="filtro<?= $this->param . $i ?>" name="<?php echo $this->param?>[]" type="checkbox" value="<?php echo $item["id"]?>" <?php echo (isset($checked) ? $checked : '');?>>
                <?=$label2?>
                    <?=$subnivel?> 
                        <?=$this->Listarsubnivel($idpadre, $this->titulo)?>
                    <?=$subnivel2?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php }?>
            <?php
            if ($this->expandible > 0):
                ?>
                <?php
                if (count($this->data['ocultos']) > 0):
                    ?>
                    <div class="more_options hide">
                        <?php foreach ($this->data['ocultos'] as $ite) : ?>
                            <?php
                            foreach ($ite as $item) : 
                                if(isset($vars[$this->param]) && in_array($item["id"], $vars[$this->param])) {
                                    $checked = 'checked';
                                } else {
                                    $checked = '';
                                }
                                
                                $i++;
                                ?>                                
                                <label class="ioption">
                                    <?= $this->CortarTexto($item["nombre"], 50); ?>
                                    <?= (empty($item["total"]) ? "" : "<span class = 'count'>({$item["total"]})</span>")?>
                                    <input rel="<?= $this->param . "/" . $item["id"] ?>" id="filtro<?= $this->param . $i ?>" name="<?php echo $this->param?>[]" type="checkbox" value="<?php echo $item["id"]?>" <?php echo $checked?>>
                                </label>
                            <?php endforeach; ?>                        
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>
        </div>
        <?php if (isset($this->data['ocultos']) && count($this->data['ocultos']) > 0) : ?>
            <div class="wrap-btn right">
                <a href="javascript:;" class="view-more">Ver todos</a>
            </div>
        <?php endif; ?>    
    </div>
</div>
<?php endif; ?>