<?
$this->isAuth = Zend_Auth::getInstance()->hasIdentity();
$this->auth = Zend_Auth::getInstance()->getStorage()->read();
$active = "active";
?>
<nav class="cont-menu">
    <ul class="row tocompany">
        <li><a class="<?= $this->menu_sel == App_Controller_Action_Postulante::MENU_INICIO ? $active : ''?>" href="<?=$this->url(array('module'=>'empresa','controller'=>'home','action'=>'index'),"default",true)?>">INICIO</a></li>
        <li><a href="<?=SITE_URL ?>/empresa/publica-aviso/index">PUBLICAR UN AVISO</a></li>
        <li><a class="" href="<?=SITE_URL ?>/empresa/home/que-es-aqui-esta-empresa/">¿QUÉ ES AQUIESTA EMPRESA?</a></li>
        <?php if(!$this->isAuth){ ?>
            <li><a class="" href="<?=SITE_URL ?>/empresa/home/nuevo-en-empleo-busco/">NUEVO EN EMPLEOBUSCO</a></li>
        <?php } ?>
        <!--<li><a class="<?=$this->menu_sel==App_Controller_Action_Empresa::MENU_SELECCION?$active:''?>" href="<?=SITE_URL ?>/empresa/seleccion">EMPLEOBUSCO SELECCIÓN</a></li>-->
<!--        <li><a class="<?=$this->menu_sel==App_Controller_Action_Empresa::MENU_PRODUCTOS?$active:''?>" href="<?=SITE_URL ?>/empresa/home/productos/">PRODUCTOS</a></li>-->
        <?php if(!isset($this->auth[Application_Form_Login::ROL_EMPRESA])){?>
        <li><a href="<?=$this->url(array('module' => Application_Form_Login::ROL_POSTULANTE),'default', true)?>">POSTULANTE</a></li>
        <?php } ?>
        <?php if($this->isAuth && isset($this->auth[Application_Form_Login::ROL_EMPRESA])){?>
            <li><a class="<?=$this->menu_sel==App_Controller_Action_Postulante::MENU_MI_CUENTA?$active:''?>" href="<?=$this->url(array('module'=>'empresa','controller'=>'mi-cuenta','action'=>'index'),"default",true)?>">MI CUENTA</a></li>
        <?php } ?>
    </ul>
</nav>
