<div class="cntFormNotaF">
<div class="loading hide showLoadF">&nbsp;</div>
    <div class="<?= $this->nota['id'] != -1? 'blockHideC':'hide' ?>" id="ind_<?= $this->nota['id'] ?>" >
    <?php if ($this->nota['id'] != -1 ) {?>
    		<div class="blockHsty blockDropDown notaShot <?= $this->nota['mostrar'] != true? '':'flagBlockEP'?>" >
    			<div class="txtHsty icoMsjEP">
                    <span class="boldBlockH bold">Nota <span class="notaItemsP"><?= $this->nota['contar']?></span></span> <span class="boldBlockH bold"><?= $this->FriendlyDate($this->nota['fecha']) ?></span>
    			</div>		
    		</div>
    <?php } ?>

		<div class="msgYellow msgDataCurr r5 hide"></div>	
		<blockquote class="blockInH <?= $this->nota['mostrar'] != true? 'hide':''?>">
			<div class="blockInnerH">
				<div class="actionsELP">
				    <a class="deleteEPLBCV <?= $this->nota['id'] != -1? '':'deleteNoteEPA' ?> sptIcoEmp right winAlertM" href="#winAlertBCV" rel="<?= $this->nota['id'] != -1? $this->form->id_nota->getValue():'-1'?>" href="#" title="¿Está seguro que desea eliminar la nota?">Eliminar</a>
					<?php if ($this->nota['id'] != -1 ) {?>
					<a class="editEPL sptIcoEmp right" href="#">Editar</a>
					<?php } ?>
				</div>
				
				<div class="dataAdjunto hide"></div>
				<div class="dataHideFlagE">
				
				<?php
				    $inicio = 0;
				    $fin = 50;
				    $canTexto = strlen($this->form->text->getValue());
				    if ($canTexto>$fin) {
				    $textCort = substr($this->form->text->getValue(),$inicio ,$fin).'...';
				    }else{
			        $textCort = $this->form->text->getValue();
				    }
				?>
				
					<div class="textbIn"><?= $this->escape($textCort); ?></div>
					<div  class="textbInAll breakWord hide"><?=$this->escape($this->form->text->getValue()) ?></div>
					<?php if ($this->nota['id'] != -1  && $canTexto > $fin) {?>
					<div class="asideBIn alignR"><a class="aBtnIn f11" href="#">Leer más</a></div>
					<?php } ?>
					
				</div>
        	<?php if($this->descartado != 1) {?>	
            <div class="editFormEP <?= $this->nota['id'] != -1? 'hide ':' ' ?> all">
            <?=$this->form->text->setAttribs(array('id' => "txtNota".$this->nota['id'], 'class'=>'dataTextEP','cols'=>'25','rows'=>'3'))->renderViewHelper(); ?>
        		<fieldset class="blockFltEP all">
        			<button type="button" class="dataBtnEP sptEmp right btnSptEmp btnEditNota notaVistaPerfil" rel="<?=$this->nota['id']?>"></button>        			
                                <div class="msgErrorEPA error left"></div>
        		</fieldset>

    		</div>
    		<?php } ?>	
		</div>	
		</blockquote>	
	</div>
	<?//php var_dump($this->form->getErrors());?>

</div>