<div class="cntFormNotaF">
<div class="loading hide showLoadF">&nbsp;</div>
<? $urlAction = $this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'guardar-nota','postulacion'=>$this->idPostulacion),"default",true) ?>
<form target="frmdescarga<?=$this->nota['id_nota']?>" class="formFields" id="ind_<?= $this->nota['id_nota'] != -1? $this->nota['id_nota']:'-1' ?>" action="<?=$urlAction?>" method="post" enctype="multipart/form-data" encoding="multipart/form-data">
<div class="<?= $this->nota['id_nota'] != -1? 'blockHideC':'hide' ?>" <?= $this->nota['id_nota'] != -1? '':'id="creatorNote"' ?> >
    <?php if ($this->nota['id_nota'] != -1 ) {?>
    		<div class="blockHsty blockDropDown notaShot <?= $this->nota['mostrar'] != true? '':'flagBlockEP'?>" >
    			<div class="txtHsty icoMsjEP"><span class="boldBlockH bold">Nota <span class="notaItemsP"><?= $this->nota['contar']?></span></span> <span class="boldBlockH bold"><?= $this->FriendlyDate($this->nota['fecha']) ?></span>
    			</div>		
    		</div>
    <?php } ?>

		<div class="msgYellow msgDataCurr r5 hide"></div>	
		<blockquote class="blockInH <?= $this->nota['mostrar'] != true? 'hide':''?>">
			<div class="blockInnerH">
				<?php if($this->descartado!= 1) {?>
				<div class="actionsELP">
				    <a class="deleteEPL <?= $this->nota['id_nota'] != -1? '':'deleteNoteEPA' ?> sptIcoEmp right winAlertM" href="#winAlert" rel="<?= $this->nota['id_nota'] != -1? $this->form->id_nota->getValue():'-1'?>" href="#" title="¿Está seguro que desea eliminar la nota?">Eliminar</a>
					<?php if ($this->nota['id_nota'] != -1 ) {?>
					<a class="editEPL sptIcoEmp right" href="#">Editar</a>
					<?php } ?>
					<div class="divAtachOpt right">
						<!--<a class="attachEPL sptIcoEmp right" href="#">Adjuntar</a>-->
						<label class="attachEPL sptIcoEmp linkApt right" for="inputFileUpload<?=$this->nota['id_nota']?>">Adjuntar</label>
						<?= $this->form->path->setAttribs(array('id'=>'inputFileUpload'.$this->nota['id_nota'], 'class' => 'inputAttachEPL opacity'))->renderFile(); ?>
					</div>
				</div>
				
				<div class="dataAdjunto hide"></div>
				<?php } ?>				
				<div class="dataHideFlagE">
				
				<?php
				    $inicio = 0;
				    $fin = 50;
				    $canTexto = strlen($this->form->text->getValue());
				    if ($canTexto>$fin) {
				    $textCort = substr($this->form->text->getValue(),$inicio ,$fin).'...';
				    }else{
			        $textCort = $this->form->text->getValue();
				    }
				?>
				
					<div class="textbIn"><?= $this->escape($textCort); ?></div>
					<div class="textbInAll breakWord hide"><?=$this->escape($this->form->text->getValue()) ?></div>
					<?php if ($this->nota['id_nota'] != -1  && $canTexto > $fin) {?>
					<div class="asideBIn alignR"><a class="aBtnIn f11" href="#">Leer más</a></div>
					<?php } ?>
					
				</div>
				<div class="hide">
				<?= $this->form->id_nota;?>
        		</div>
        		<div class="hide">
				<input type="hidden" name="iP" id="iP" value="<?= $this->idPostulacion ?>">
        		</div>
        	<?php if($this->descartado != 1) {?>	
            <div class="editFormEP <?= $this->nota['id_nota'] != -1? 'hide ':' ' ?> all">
            <?=$this->form->text->setAttribs(array('class'=>'dataTextEP','cols'=>'25','rows'=>'3'))->renderViewHelper(); ?>
        		<fieldset class="blockFltEP all">
        			<!--
        			<input class="dataBtnEP sptEmp right btnSptEmp" type="submit" value="" rel="<?= $this->idPostulacion ?>" />
        			-->
        			<!--
        			<a href="#" class="dataBtnEP sptEmp right btnSptEmp" rel="<?= $this->idPostulacion ?>" ><span class="hide">Guardar</span></a>
        			-->
        			<button type="button" class="dataBtnEP sptEmp right btnSptEmp" rel="<?= $this->idPostulacion ?>"></button>
        			
        			<div class="msgErrorEPA error left"></div>
        		</fieldset>
    		</div>
    		<?php } ?>	

			<?= $this->path_original ?>
			<?php  if($this->nota['path_original']!= null) {?>
			<div class="dataAdjuntada r5">					
				<!-- 1 -->					
				<div class="adjuntoD">
					<div class="msgInAdjEPL"><a href="<?= $this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'archivo-adjunto','id'=>$this->form->id_nota->getValue()),"default",true) ?>"><?=$this->nota['path_original'] ?></a>
						<a class="icoCloseMsjAdj closeAdjInP sptIcoEmp" rel="<?=$this->nota['id_nota']?>" href="#"><span class="hide">Cerrar</span></a>
					</div>			
				</div>
			</div>
			<?php }?>
			<!-- / -->
					
		</div>	
		</blockquote>	
	</div>
	<?//php var_dump($this->form->getErrors());?>
</form>
	<iframe id="frmdescarga<?=$this->nota['id_nota']?>" name="frmdescarga<?=$this->nota['id_nota']?>" src="javascript:false" class="hide iframeTrue"></iframe>    
</div>