<?php if (substr($this->rol, 0, 5) != Application_Form_Login::ROL_ADMIN): ?>
<form method="post" id="formEndP4Emp" action="<?=
    $this->url(array(
        'module' => 'empresa', 'controller' => 'comprar-aviso', 'action' => 'pagar',
        'aviso' => $this->dataAnuncio["anuncioId"]), 'default', true)
    ?>" class="frm-horizontal" data-parsley-validate>
<?php else: ?>
<form method="post" id="formEndP4Emp" action="<?=
    $this->url(array(
        'module' => 'admin', 'controller' => 'comprar-aviso', 'action' => 'pagar',
        'aviso' => $this->dataAnuncio["anuncioId"]), 'default', true)
    ?>" class="frm-horizontal" data-parsley-validate>
<?php endif; ?>
<input id="tipoAviso" name="tipoAviso" rel="<? echo $this->dataAnuncio['anuncioImpresoId']; ?>" type="hidden" value="<? echo $this->dataAnuncio['tipo']; ?>"></input>
<?php
    $precioR = 0;
    $precioC = 0;

    foreach ($this->contratos as $contrato) :
    if ($contrato["formaPago"] == "R")
        $precioR = $contrato["precio"];
    else
        $precioC = $contrato["precio"];
?>
    <input id="contrato<? if ($contrato["formaPago"] == "R") echo $contrato["formaPago"]; else echo "N";?>" descuento="<?= $contrato["descuento"] ?>" saldo="<?= $contrato["saldo"] ?>" tipo="<?= $contrato["tipo"] ?>" type="hidden" precio="<?= $contrato["precio"] ?>"></input>
    <?php endforeach; ?>
    <div class="row">
        <div class="grids-410">
            <h2 class="black-title txt-left">DETALLE DE COMPRA</h2>
            <div class="wrap-controls">
                <h6>Producto: <?= $this->dataAnuncio["nombreProducto"] . ' (' . $this->dataAnuncio["tamano"] . ')' ?></h6>
                <?php if (isset($this->medioPublicacion)): ?>
                    <p>Impreso en <?= $this->ItemList('MedioPublicacion',$this->medioPublicacion)?>
                        <?= ucfirst($this->CustomFormatDate($this->fechaImpreso,
                                "EEEE, d 'de' ")) . ucfirst($this->CustomFormatDate($this->fechaImpreso,
                                "MMMM 'de' YYYY"))
                        ?>
                    </p>
                    <p>Pago hasta <?= ucfirst($this->fhCierre->get("EEEE, d 'de' ")) . ucfirst($this->fhCierre->get("MMMM 'de' YYYY 'a' 'las' h:m a")) ?></p>
                <?php endif ?>
                <?php foreach ($this->dataAnuncio["beneficios"] as $i => $item): ?>
                    <?php
                    $desc = "";
                    switch ($item['codigo']) {
                        case 'ndiaspub':
                            $desc = (empty($item['valor']) ? ''
                                        : $item['valor']) . " " . $item['descbeneficio'];
                            $desc .= ', del ' . $this->FechaRangoPublicacionWeb(date('Y-m-d'),
                                    $item['valor'],
                                    Zend_Date::DAY);
                            break;
                        case 'ndiasproc':
                            break;
                        case 'ndiasprio':
                            if (!empty($item['valor']))
                                    $desc = (empty($item['valor'])
                                            ? '' : $item['valor']) . " " . $item['descbeneficio'];
                            break;
                        default:
                            $desc = (empty($item['valor']) ? ''
                                        : $item['valor']) . " " . str_replace('AquiEmpleos',
                                    'AquiEmpleos',
                                    $item['descbeneficio']);
                            break;
                    }
                    ?>
                    <?php if (!empty($desc)): ?>
                        <p>
                            <?= $desc ?>.
                        </p>
                    <?php endif ?>
                <?php endforeach ?>
                <?php
                $classDescuento = "";
                if ($this->descuentoAnuncio <= 0)
                        $classDescuento = "hide";
                ?>
                <?php if (!empty($this->dataAnuncio["url"]) && $this->dataAnuncio["slug_anuncio"]): ?>
                    <p class="row"><a rel="<?= $this->url(array(
                                'slug' => $this->dataAnuncio["slug_anuncio"],
                                'url_id' => $this->dataAnuncio["url"],
                                'id' => $this->dataAnuncio["anuncioId"]),
                                'avisoEmpresa', true)
                            ?>" href="#winVerProceso" class="winModal view-more">Mire su aviso</a></p>
                <?php else: ?>
                    <p class="row"><a rel="<?
                        echo $this->url(array(
                            'module' => 'empresa', 'controller' => 'mi-cuenta',
                            'action' => 'ver-aviso-preferencial',
                            'preferencial' => $this->dataAnuncio['anuncioImpresoId']),
                            'default', true);
                        ?>" href="#winVerProceso" class="winModal view-more">Mire su aviso web</a></p>
                <?php endif; ?>
                <?php if ($this->descuentoAnuncio > 0) : ?>
                    <div class="price_detail">
                        <div id="dvPrecioDescuento" class="pay_add green <?= $classDescuento ?>">
                            Su descuento es: <?php echo $this->moneda?> <b id="descuentoAP"><?= number_format($this->descuentoAnuncio, 2) ?></b>
                        </div>
                    </div>
                <?php endif; ?>
                <?php if (count($this->dataAnuncio["extracargos"]) > 0): ?>
                <div class="price_detail row">
                    <span class="txt_small flt_left">El precio incluye I.G.V.</span>
                    <div class="price">
                        <span class="first">Precio: </span><?php echo $this->moneda?> <span><?= number_format($this->dataAnuncio["tarifaPrecio"], 2) ?></span>
                    </div>
                </div>
                <?php endif; ?>
                <?php  /*if (count($this->Descuentos)>0) { ?>
                       <div class="price_discount">
                           <span class="txt_small">Descuento.</span>
                           <select class="selDescuento" id="selDiscount" name="selDiscount" required>
                           <option value="0">Seleccionar</option>
                            <?php foreach ($this->Descuentos as $key => $value) {
                                   echo "<option value='".$value."'>".ucwords(strtolower($value)).' % </option>';
                             }?>
                            </select>
                       </div>
                <?php  } */?>
                <!-- Esto esta en DURO hacerlo dinamico -->
                <?php if ($this->descuentoAnuncio > 0) : ?>

                    <div class="price_detail row">
                        <p id="dvPrecioNormal" class="<?= $classDescuento ?>">
                            Precio normal <?php echo $this->moneda?><?= number_format($this->dataAnuncio["tarifaPrecio"], '2', '.', ','); ?>
                        </p>
                        <span class="txt_small flt_left">El precio incluye I.G.V.</span>
                        <div class="price">
                            <span class="first">Precio: </span><?php echo $this->moneda?> <span id="priceTotP4" data-number="<?= $this->precioConDescuento ?>"><?= number_format($this->precioConDescuento, 2) ?></span>
                        </div>
                    </div>
                <?php else : ?>
                    <?php
                    if ((float) str_replace(",", "", $precioR) > 0):
                        $recargo = (float) str_replace(",", "", $precioR) - (float) str_replace(",", "", $precioC);
                    else:
                        $recargo = 0;
                    endif;

                    if ($recargo > 0):
                        ?>
                        <div class="price_detail">
                            <div id="mtoRecargoCreditoAVP" class="pay_add">Su recargo es: <?php echo $this->moneda?> <b><?= round($recargo, 2) ?></b></div>
                            <p id="mtoPrecioNormalAVP">Precio normal <?php echo $this->moneda?> <?php echo $precioC ?></p>
                        </div>
                    <?php endif; ?>
                    <div class="price_detail row">
                        <span class="txt_small flt_left">El precio incluye I.G.V.</span>
                        <div class="price">
                            <span class="first">Precio: </span><?php echo $this->moneda?> <span id="priceTotP4" data-number="<?=$this->precioConDescuento?>"><?= number_format($this->precioConDescuento, 2);?></span>
                        </div>
                    </div>
                <?php endif; ?>
                <!-- / Esto esta en DURO hacerlo dinamico -->
                <?php if (count($this->dataAnuncio["extracargos"]) > 0): ?>
                    <h6 class="mT20">Agregue destaques para el impreso</h6>
                    <?php foreach ($this->dataAnuncio["extracargos"] as  $i => $item):
                        ?>
                        <label class="ioption">
                            <label for="xc_negrita"><?= $item['nombreBeneficio'] ?> (<?php echo $this->moneda?> <?= $item['precioExtracargo'] ?>)</label>
                            <input value="<?= $item['precioExtracargo'] ?>" name="xc_<?= $i ?>" id="xc_<?= $i ?>" type="checkbox" class="checkEmpP4" rel="<?= $item['precioExtracargo'] ?>"/>

                            <a rel="<?= MEDIA_URL ?>/images/empresa/extracargos/clasificado_en_negritas.jpg" class="winModal noScrollTop imgExtraCargos mL20" href="#ejemploext">Ver Ejemplo</a>

                            <a rel="<?= MEDIA_URL ?>/images/empresa/extracargos/<?= $item['imagen'] ?>" class="winModal noScrollTop imgExtraCargos mL20" href="#ejemploext">Ver Ejemplo</a>

                        </label>
                    <?php endforeach; ?>
                <?php endif ?>
            </div>
        </div>
        <div class="grids-5">
            <h2 class="black-title txt-left">TIPO DE COMPROBANTE</h2>
                <div class="wrap-controls">
                          <p class="mB10 justify">A partir del 1 de octubre del 2014 se procederá a emitir los comprobantes de pago por los servicios que se les brinda mediante la modalidad de formato electrónico, los mismos que estarán a su disposición a través de la página web: <a style="color: #007FD2;text-decoration:none;"  href ="http://www.gec.pe/" target="_blank" >www.gec.pe</a>. En caso de no contar con un usuario y contraseña de acceso, deberá de enviarnos el nombre del funcionario y la dirección del correo electrónico oficial de su representada a la siguiente dirección electrónica: <a style="color: #007FD2;text-decoration:none;" href="mailto:facturacionelectronica@comercio.com.pe">facturacionelectronica@comercio.com.pe</a>  o comunicarse a la central telefónica 3116711, para la recepción de los documentos mencionados anteriormente.</p>
                    <div class="cgroup-inline mB10">
                        <div class="control-group"><label class="ioption p0">Desea una:</label></div>
                        <div class="control-group">
                            <label class="ioption">
                                <input name="radioTipoDoc" type="radio" id="radioP4EmpBX" class="radioEmpP4b" value="factura" checked="checked">Factura
                            </label>
                        </div>
                    </div>
                    <dl class="property m0">
                        <?=$this->partial('_partials/_pago-datos-factura.phtml', array( 'Formfacturacion'=>$this->Formfacturacion ))?>
                    </dl>
                    <?php if ($this->tieneMembresia) : ?>
                        <div class="cgroup-inline mT20">
                            <div class="control-group">
                                <label for="usoMembresia" class="control-label"><em>*</em> Pagar: </label>
                            </div>
                            <div class="control-group">
                                <?= $this->formAvisoPref->usoMembresia->setAttribs(array(
                                'id' => 'usoMembresia', 'class' => 'input-middle'))->renderViewHelper();
                            ?>
                            </div>
                            <?php $classSaldo = "";
                            if ($this->saldo <= 0) $classSaldo = "hide"; ?>
                            <div class="control-group">
                                <span id="lblSaldoEmpresa" class="control-label <?= $classSaldo ?>"> su saldo es : <?php echo $this->moneda?><b id="saldoAP"> <?=number_format($this->saldo, 2)?></b></span>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

            <h2 class="black-title txt-left">MÉTODO DE PAGO</h2>
            <div class="wrap-controls" id="blockTPBA">
                <?php if ($this->tieneCredito) : ?>
                    <h3 class="tit_pay m0">Pagar con Crédito La Prensa</h3>
                    <div class="pay_detail">
                        <input class="inputTarjM" type="radio" checked="checked" id="radioTarjV0" name="radioTipoPago" value="credito" />
                        <span class="pay_txt">
                            <p class="mt10">Utiliza crédito La Prensa</p>
                        </span>
                    </div>
                <?php endif ?>
                <h3 class="tit_pay row">
                    <span class="left">Pagar sin Tarjeta de Crédito</span>
                    <a class="fancy_modal icon_question" href="#wrapPagoEfectivo" title="¿Qué es PagoEfectivo?"></a>
                </h3>
                <div class="pay_detail">
                    <input class="inputTarjM" type="radio" checked="checked" id="radioTarjV1" name="radioTipoPago" value="pe" <? if (!$this->tieneCredito) echo 'checked="checked"'; ?> />
                    <span class="pay_logos pago_efectivo"></span>
                    <span class="pay_txt">
                        <p>
                            Compra con PagoEfectivo y paga a través de Internet o en cualquier
                            oficina del BCP, BBVA, ScotiaBank, Interbank, en agencias Western
                            Union y en establecimientos autorizados que tengan el logo de
                            PagoEfectivo y/o Fullcarga.<br>
                        </p>
                        <a class="fancy_modal" href="#wrapPagoEfectivo" title="¿Qué es PagoEfectivo?">
                            ¿Qué es PagoEfectivo?
                        </a>
                    </span>
                </div>


                <h3 class="tit_pay">Pagar con Tarjeta de Crédito</h3>
                <div class="pay_detail">
                    <input class="inputTarjM" type="radio" id="radioTarjV2" name="radioTipoPago" value="visa" />
                    <span class="pay_logos visa"></span>
                    <span class="pay_txt">
                        <p class="mt10">Paga con tarjeta de crédito </p>
                        <a href="http://www.visanet.com.pe/visa.htm" title="Verified by Visa" class="verified show_popup" target="_blank"></a>
                    </span>
                </div>
                <div class="pay_detail">
                    <input class="inputTarjM" type="radio" id="radioTarjV3" name="radioTipoPago" value="mc" />
                    <span class="pay_logos mastercard"></span>
                    <span class="pay_txt mt5">
                        <p>Pago con Tarjeta de Crédito Mastercard</p>
                        <span class="txt_small left">Se aceptan tarjetas Curacao, Carsa, Ace Home Center, Ripley y afiliadas.</span>
                    </span>
                </div>

                <?php if ($this->isSessionAdmin === true) :?>
                    <div class="pay_detail">
                        <input class="inputPOS" type="radio" id="rdPosVirtual" name="radioTipoPago" value="pos"  data-token="<?php echo CSRF_HASH;?>"/>
                        <span class="pay_pos"></span>
                        <span class="pay_txt pos">
                            <p>POS virtual</p>
                        </span>
                    </div>
                    <?php endif; ?>
                <p class="details">* Una vez efectuado el pago, el aviso no está sujeto a reclamo</p>
                <div class="pay_wrap_btn">
                    <button onclick="ga('send', 'event', 'P4_<?php echo str_replace(' ', '_', $this->producto['desc'])?>', '<?php echo $this->empresaId?>' , '<?php echo $this->producto['medio_publicacion']?>_');" type="submit" id="nextEmpP3" class="btn btn-primary btn-bigx ">Pagar</button>
                </div>
            </div>
        </div>
    </div>
</form>
<div class="wrap-btn right">
    <a href="/<?= $this->module; ?>/<?= $this->controller; ?>/paso3/impreso/<?= $this->anuncioImpresoId; ?>" id="backEmpP1" class="btnSptEmp btn btn-default">Regresar</a>
</div>
<div class="safe_box">
    <p>Te encuentras en un ambiente super seguro para transacciones por internet</p>
    <span class="icons_safe ssl"></span>
    <span class="icons_safe kaspersky"></span>
    <span class="icons_safe verisign"></span>
</div>
<!-- Que es Pago Efectivo -->
<?=$this->partial('_partials/_que_es_pago_efectivo.phtml', $this);?>
