<div id="divFactura">
    <div class="control-group">
            <label for="txtRuc" class="control-label">RUC:</label>
            <div class="controls">
                <?=$this->Formfacturacion->txtRuc->setAttribs(array('id'=>'txtRuc','class'=>'input-xsmall number','required' => '', 'data-parsley-minlength' =>2,'data-parsley-trigger'=>'change', 'data-parsley-type' => 'number', 'data-parsley-excluded' => '[disabled],:hidden'))->renderViewHelper(); ?>
            </div>
    </div>
    <div class="control-group">
            <label for="txtName" class="control-label">Razón social:</label>
            <div class="controls">
                <?=$this->Formfacturacion->txtName->setAttribs(array('id'=>'txtName','class'=>'input-xmiddle','required' => '', 'data-parsley-minlength' =>2,'data-parsley-trigger'=>'change', 'data-parsley-excluded' => '[disabled],:hidden'))->renderViewHelper(); ?>
            </div>
    </div>
        
    <p class="txt_small"></p>
</div>