<div class="wrap_joincv">
    <h1 class="title-bigxxx">Gracias por adquirir su membresía en <span class="logo_EMPLEOBUSCO"></span>!</h1>
    <p class="text-medium">Ahora podrás tener acceso a la base de datos de Perfiles,<br>ubicación preferencial de sus avisos web, Carpetas de Perfiles y más.</p>
    <br><br>
    <?php if ($this->tipoContrato != null): ?>
        <div class="blockPY1 heightPYL r5" id="infoAPPR">
            <p>Su aviso fue cargado a su <?= $this->tipoContrato ?></p>
            <table class="dataTableAPPR">
                <tr>
                    <td class="bold">Precio del Aviso: </td>
                    <td><?php echo $this->moneda?><span><?php echo $this->aw['montoTotal']; ?></span></td>
                </tr>
            </table>
        </div>
    <?php endif; ?>
    <!-- /para membresia -->    
    <table summary="Ficha de Pago" id="gridEndPayA" class="dataGrid">
        <thead>
            <tr>
                <th class="data1 titleGrid">Producto</th>
                <th class="data2 titleGrid">Detalle</th>
                <th class="data3 titleGrid">Fecha de inicio</th>
                <th class="data4 titleGrid">Fecha de fin</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="data1 dataPBig"><?= ucfirst($this->aw['Tipoproducto']) ?></td>
                <td class="data2 dataPBig">Membresía <?= $this->aw['productoNombre'] ?></td>
                <td class="data3 dataPBig"><?= $this->FriendlyDate($this->aw['fechaInicioMembresia']); ?></td>
                <td class="data3 dataPBig"><?= $this->FriendlyDate($this->aw['fechaFinMembresia']); ?></td>

            </tr>						
        </tbody>
    </table> 
    
    <div class="txt_center mB20 mT20">
         <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'), "default", true) ?>">Ir a mi Cuenta</a>
         &nbsp;&nbsp;
         <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'membresias'), 'default', true) ?>">Ver mis Membresías</a>
     </div>
     <div class="txt_center">
             <a href="<?= SITE_URL . '/empresa/publica-aviso' ?>" id="publushTAdvP4" class="btn btn-primary">
                 Publica un aviso
             </a>
     </div>
</div>
