<?php 
$readonly='';$disabled='';$blokear='';
if($this->codadecsys!=''){
	$readonly='readonly="readonly"';
	$disabled='disabled="disabled"';
}else{
    $blokear='readonly="readonly"';
 }
?>
<?php if (substr($this->rol, 0, 5) != "admin") : ?>
	<form method="post" id="frmFeaturedProfile" action="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'pago-membresia', 'MemBresia' => $this->mebMem["id"],'token' =>$this->tokenMemprecia), 'default', true) ?>" class="frm-horizontal" data-parsley-validate>
<?php else : ?>
		<form method="post" id="frmFeaturedProfile" action="<?= $this->url(array('module' => 'admin', 'controller' => 'comprar-aviso', 'action' => 'pagar', 'MemBresia' => $this->mebMem["id"],'token' =>$this->tokenMemprecia), 'default', true) ?>" class="frm-horizontal" data-parsley-validate>
<?php endif; ?>
	  <div class="row">
		<div class="grids-410">
			<h2 class="black-title txt-left">DETALLE DE COMPRA</h2>
			<div class="wrap-controls">
				<h6>Producto: Plan de Membresia <?= $this->mebMem["nombreProducto"] ?></h6>
                                <ul class="check-list first check-list-det-memb">
				<?php foreach ($this->mebMem["beneficios"] as $i => $item): ?>
                                    <li>
                                        <i class="icon icon_check" style="font-size: 18px; left: 9px; position: absolute;"></i>
                                        <?= $item['descbeneficio'] ?>
                                    </li>					
				<?php endforeach ?>
                                </ul>
                                <?php  $arMontos = $this->AvisoExtraCargo($this->mebMem, true); ?>
				<div class="price_detail row">
					<div class="price">
						<span class="first">Subtotal: <?php echo $this->moneda?> <?php echo $arMontos['subtotal']; ?></span><br>
						<span class="first"><?php echo $this->igv?>: <?php echo $this->moneda?> <?php echo $arMontos['igv']; ?></span>
					</div>
				</div>
				<div class="price_detail row"><span class="txt_small flt_left">El precio incluye I.G.V.</span><div class="price"><span class="first">Precio: </span><?php echo $this->moneda?> <span><?php echo $arMontos['total']; ?></span></div></div>
				
			</div>
		</div>
		<div class="grids-5">
			<h2 class="black-title txt-left">TIPO DE COMPROBANTE</h2>
			<div id="wrapFeaturedProfile" class="wrap-controls">
			  <p class="mB10 justify">A partir del 1 de octubre del 2014 se procederá a emitir los comprobantes de pago por los servicios que se les brinda mediante la modalidad de formato electrónico, los mismos que estarán a su disposición a través de la página web: <a style="color: #007FD2;text-decoration:none;"  href ="http://www.gec.pe/" target="_blank" >www.gec.pe</a>. En caso de no contar con un usuario y contraseña de acceso, deberá de enviarnos el nombre del funcionario y la dirección del correo electrónico oficial de su representada a la siguiente dirección electrónica: <a style="color: #007FD2;text-decoration:none;" href="mailto:facturacionelectronica@comercio.com.pe">facturacionelectronica@comercio.com.pe</a>  o comunicarse a la central telefónica 3116711, para la recepción de los documentos mencionados anteriormente.</p>
				<div class="cgroup-inline mB10">
					<div class="control-group"><label class="ioption p0">Desea una:</label></div>				 
					<div class="control-group">
						<label class="ioption">
							<input name="radioTipoDoc" type="radio" id="" value="factura" checked="checked">Factura
						</label>
					</div>
				</div>
                                <?=$this->partial('_partials/_pago-datos-factura.phtml', array( 'Formfacturacion'=>$this->Formfacturacion ))?>

			</div>
			<h2 class="black-title txt-left">MÉTODO DE PAGO</h2>
			<div class="wrap-controls">
				<h3 class="tit_pay row">
					<span class="left">Pagar sin Tarjeta de Crédito</span>
					<a class="fancy_modal icon_question" href="#wrapPagoEfectivo" title="¿Qué es PagoEfectivo?"></a>
				</h3>
				<div class="pay_detail">
					<input class="inputTarjM" type="radio" checked="checked" id="radioTarjV1" name="radioTipoPago" value="pe">
					<span class="pay_logos pago_efectivo"></span>
					<span class="pay_txt">
						<p>
							Compra con PagoEfectivo y paga a través de Internet o en cualquier 
							oficina del BCP, BBVA, ScotiaBank, Interbank, en agencias Western 
							Union y en establecimientos autorizados que tengan el logo de 
							PagoEfectivo y/o Fullcarga.<br>
						</p>
						<a href="#wrapPagoEfectivo" class="fancy_modal" title="¿Qué es PagoEfectivo?">¿Qué es PagoEfectivo?</a>
					</span>
				</div>
				<h3 class="tit_pay">Pagar con Tarjeta de Crédito</h3>
				<div class="pay_detail">
					<input class="inputTarjM" type="radio" id="radioTarjV2" name="radioTipoPago" value="visa">
					<span class="pay_logos visa"></span>
					<span class="pay_txt">
						<p class="mt10">Paga con tarjeta de crédito </p>
						<a href="http://www.visanet.com.pe/visa.htm" title="Verified by Visa" class="verified show_popup" target="_blank"></a>
					</span>
				</div>
				<div class="pay_detail">
					<input class="inputTarjM" type="radio" id="radioTarjV3" name="radioTipoPago" value="mc">
					<span class="pay_logos mastercard"></span>
					<span class="pay_txt mt5">
						<p>Pago con Tarjeta de Crédito Mastercard</p>
						<span class="txt_small left">Se aceptan tarjetas Curacao, Carsa, Ace Home Center, Ripley y afiliadas.</span>
					</span>
				</div>
				<p class="details">* Una vez efectuado el pago, el mismo no estará sujeto a reclamo.</p>
				  <div class="pay_wrap_btn">
					<button type="submit" id="btnPay" class="btn btn-primary btn-bigx " >Pagar</button>
				</div>
			</div>
		</div>
	</div>
</form>
<div class="wrap-btn right">
	<a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 
                    'controller' => 'home', 
                    'action' => 'membresia-anual'
                    ),false, true)?>" id="backEmpP1" class="btn btn-default btnSptEmp" >Regresar</a>
</div>
<div class="safe_box">
	<p>Te encuentras en un ambiente super seguro para transacciones por internet</p>
	<span class="icons_safe ssl"></span>
	<span class="icons_safe kaspersky"></span>
	<span class="icons_safe verisign"></span>
</div>
<!-- Que es Pago Efectivo -->
<?=
$this->partial('_partials/_que_es_pago_efectivo.phtml', $this);
?>
