<?php
if (isset($this->online) && $this->online == false) {
    unset($this->online);
}
?>
<h2 class="blue-title"><span class="icon-tiny white down"></span>Datos del puesto</h2>
<div id="basicDataF" class="frm-horizontal wrap-controls open">
<div class="skill-content">
	<?php echo $this->partial('publica-aviso/_datos_paso2.phtml', 'empresa',
        array('form' => $this->form,
            'isDato' => $this->isDato,
            'modulo' => $this->modulo,
            'numPalabraPuesto' => $this->numPalabraPuesto,
            'numPalabraOtroNombre' =>$this->numPalabraOtroNombre,
            'modulo' =>$this->modulo,'lock'=>(isset($this->lock))?$this->lock:'',
            'nombreComercial' => $this->nombreComercial,
            'showLogoEmpresa' => $this->showLogoEmpresa
        )
    ); ?>   
                
    <?php if ($this->showLogoEmpresa) { ?>
    <div id="divWrapFile" class="control-group">
        <label for="fPhoto" class="control-label no-req">Logotipo:
            <br/><br/>
            <p class="txt_small">Tamaño máximo 500Kb</p>
            <p class="txt_small">Formatos permitidos: JPG, PNG</p>
            <p class="txt_small">Los archivos no deben medir<br/> más de 640px X 480px</p>
        </label>
        <div class="controls">
            <div id="divImage" class="img-upload center-img">
                <img src="<?=$this->S('/images/empresa/photoEmpDefault.png'); ?>" alt="Logo" />
            </div>
            <div class="img-actions">
                <input type="hidden" name="filesize" value="512000" id="MAX_FILE_SIZE">
                <input type="hidden" name="tipo" value="emp">
                <a id="divDelFot" href="javascript:;" title="Eliminar foto" data-rel="" class="icon-trash <?= $this->imgPhoto!='' && $this->idEmpresa!=null ? '':'hide' ?>"></a>
                <input type="file" name="logotipo" id="txtLogo" class="medium">
                <?$hasError = $this->formEmpresa->logotipo->hasErrors();?>
                <br>
                <span class="response <?= $hasError ? ' bad' : '' ?>">
                <?
                    if ($this->formEmpresa->logotipo->hasErrors()) {
                        foreach ($this->formEmpresa->logotipo->getMessages() as $error) {
                            echo $error . "<br>";
                        }
                    }
                ?>
                </span>
                <p class="txt_small">Mejore la presencia y visibilidad de su aviso<br> agregando el logo de su empresa.</p>                
            </div>
        </div>
    </div>
    <?php } ?>  
                
	<h2 class="text-mediumx">Ubicación del Puesto</h2>
	<?= $this->partial('registro-empresa/_ubigeoEmpresa_paso1.phtml','empresa',array('formEmpresa'=>$this->frmUbigeo)); ?>

</div>
</div>
    
<?php $totalEstudio = count($this->formEstudio);
$data= $this->formEstudio;//$this->managerEstudio->getCleanPost()?$this->managerEstudio->getCleanPost():array();
foreach ($data as $d) {
    $d = $d->getValues();
    if ( ($d['id_nivel_estudio'] == 0 && $d['id_tipo_carrera'] == 0 && $d['id_carrera'] == 0) ||
         ($d['id_nivel_estudio'] == null && $d['id_tipo_carrera'] == null && $d['id_carrera'] == null)
        ) {
        $totalEstudio--;
    }
}
    $totalEstudioC = 0;
$data= $this->formEstudio;
$errEstudio = false;
foreach ($data as $d) {
    $er = $d->isErrors();
    if($er)
        $errEstudio = true;
    $d = $d->getValues();
  	    if (in_array($d['id_nivel_estudio'],array(1,2,3)))
        {
            $totalEstudioC++;
        }
    elseif ($d['id_nivel_estudio'] != 0 && $d['id_nivel_estudio_tipo'] != 0 && $d['id_tipo_carrera'] != 0 && $d['id_carrera'] != 0)
        {
            if($d['id_carrera']!=15||!empty($d['otra_carrera']))
                $totalEstudioC++;
        }
}
    ?>
<h2 class="blue-title">Estudios<span class="icon-tiny white down"></span>
	<span class="number"><?=(isset($this->isEstudio)&& $totalEstudioC != '0')?'('.$totalEstudioC.')' :''?></span>
</h2>
<div id="studyF" class="frm-horizontal wrap-controls <?=($errEstudio || !$this->isEstudio)?'open':'close'?>" data-delete="/empresa/aviso/borrar-estudio">
    <input type="hidden" name="managerEstudio" class="delete_reference">
	<ul class="wrap-skills">
		<?php
        $contador=0;  
        foreach($this->formEstudio as $indEst => $formEstudio) : ?>
		<?php echo $this->partial('publica-aviso/_estudio_paso2.phtml', 'empresa'
		    , array('form' => $formEstudio
		    , 'manager' => $this->managerEstudio
		    , 'idPost' => $this->idPost
		    , 'indice' => $indEst
		    , 'index' => $contador
		    , 'totalEstudio' => $totalEstudio
		    , 'isEditar' => $this->isEditarEstudio
		    , 'isEstudio' => (Count($this->formEstudio) - 1) == $contador ? false : $this->isEstudio
		    , 'online' => $this->online)); ?>
		<?php 
        $contador++;
        endforeach; 
        ?>
	</ul>
	<?php if (!isset($this->online) && $this->online!=true || !is_null($this->managerEstudio->getErrorMessage())) : ?>
		<div class="wrap-btn right">
			<span class="message bad hide"><?=$this->managerEstudio->getErrorMessage()?></span>
			<button id="btnStudy" type="button" class="btn btn-default" data-default="Añadir estudio">Añadir <?=isset($more) ? $more: ''?> estudio</button>
		</div>
	<?php endif; ?>
</div>

<?php $totalExperiencia = count($this->formExperiencia);
$data=$this->formExperiencia;//$this->managerExperiencia->getCleanPost()?$this->managerExperiencia->getCleanPost():array();
$errExperiencia = false;
foreach ($data as $d) {
    $er = $d->isErrors();
    if($er)
        $errExperiencia = true;
    $d = $d->getValues();
    if (($d['id_nivel_puesto'] == -1 && $d['id_area'] == -1 && $d['experiencia'] == 0) ||
        ($d['id_nivel_puesto'] == null && $d['id_area'] == null && $d['experiencia'] == null)
        ) {
        $totalExperiencia--;
    }
}
    $totalExperienciaC = 0;
$data=$this->formExperiencia;
foreach ($data as $d) {
    $d = $d->getValues();
    if ($d['id_nivel_puesto'] != 0 && $d['id_area'] != 0 && $d['experiencia'] >= 0)
        $totalExperienciaC++;
    }
    ?>

<h2 class="blue-title">Experiencia<span class="icon-tiny white down"></span>
	<span class="number"><?=(isset($this->isExperiencia)&& $totalExperienciaC != '0')?'('.$totalExperienciaC.')' :''?></span>
</h2>
<div id="experienceF" class="frm-horizontal wrap-controls <?=($errExperiencia || !$this->isExperiencia)?'open':'close'?>" data-delete="/empresa/aviso/borrar-experiencia">
    <input type="hidden" name="managerExperiencia" class="delete_reference">
	<ul class="wrap-skills">
		<?php $contador=0;foreach($this->formExperiencia as $indExp => $formExperiencia) : ?>
		<?php echo $this->partial('publica-aviso/_experiencia_paso2.phtml', 'empresa'
		    , array('form' => $formExperiencia
		    , 'manager' => $this->managerExperiencia
		    , 'idPost' => $this->idPost
		    , 'indice' => $indExp
		    , 'index' => $contador
		    , 'totalExperiencia' => $totalExperiencia
		    , 'isEditar' => $this->isEditarExperiencia
		    , 'isExperiencia' => (Count($this->formExperiencia) - 1) == $contador ? false : $this->isExperiencia
		    , 'online' => $this->online)); $contador++;?>
		<?php endforeach; ?>
	</ul>
	<?php if (!isset($this->online) || !is_null($this->managerExperiencia->getErrorMessage())) : ?>
		<div class="wrap-btn right">
			<span class="message bad hide"><?=$this->managerExperiencia->getErrorMessage()?></span>
			<button id="btnExperience" type="button" class="btn btn-default" data-default="Añadir experiencia">Añadir <?=(isset($more) ? $more : '')?> experiencia</button>
		</div>
	<?php endif; ?>
</div>

<?php $totalOtroEstudio = count($this->formOtroEstudio); 
$data= $this->formOtroEstudio;//$this->managerIdioma->getCleanPost()?$this->managerIdioma->getCleanPost():array();
$errOtroEstudio = false;
foreach ($data as $d) {
    $er = $d->isErrors();
    if($er)
        $errOtroEstudio = true;
    $d = $d->getValues();
    if ( ($d['id_nivel_estudio_tipo'] == "0") ||
         ($d['id_nivel_estudio_tipo'] == null) 
        ) {
        $totalOtroEstudio--;
    }
}
    $totalOtroEstudioC = 0; 
$data= $this->formOtroEstudio;
foreach ($data as $d) {
    $d = $d->getValues();
    if (!empty($d['id_nivel_estudio_tipo'])&&!empty($d['otra_carrera']))
       $totalOtroEstudioC++;
}
    ?>
<h2 class="blue-title">Otros Estudios<span class="icon-tiny white down"></span>
	<span class="number"><?=(isset($this->isOtroEstudio)&& $totalOtroEstudioC != '0')?'('.$totalOtroEstudioC.')' :''?></span>
</h2>
<div id="studyOtherF" class="frm-horizontal wrap-controls <?=($errOtroEstudio || !$this->isOtroEstudio)?'open':'close'?>" data-delete="/empresa/aviso/borrar-estudio">
   	<input type="hidden" name="managerOtroEstudio" class="delete_reference">
	<ul class="wrap-skills">
		<?php $contador=0;foreach($this->formOtroEstudio as $indOE => $formOtroEstudio) : ?>
		<?php echo $this->partial('publica-aviso/_otro_estudio_paso2.phtml', 'empresa'
		    , array('form' => $formOtroEstudio
		    , 'manager' => $this->managerOtroEstudio
		    , 'idPost' => $this->idPost
		    , 'indice' => $indOE
		    , 'index' => $contador
		    , 'totalOtroEstudio' => $totalOtroEstudio
		    , 'isEditar' => $this->isEditarOtroEstudio
		    , 'isOtroEstudio' => (Count($this->formOtroEstudio) - 1) == $contador ? false : $this->isOtroEstudio
		    , 'online' => $this->online)); $contador++;?>
		<?php endforeach; ?>
	</ul>
	<?php if (!isset($this->online)) : ?>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnOtherStudy" type="button" class="btn btn-default" data-default="Añadir otro estudio">Añadir <?=(isset($more) ? $more:'')?> estudio</button>
		</div>
	<?php endif; ?>
</div>

<?php $totalIdioma = count($this->formIdioma); 
$data= $this->formIdioma;//$this->managerIdioma->getCleanPost()?$this->managerIdioma->getCleanPost():array();
$errIdioma = false;
foreach ($data as $d) {
    $er = $d->isErrors();
    if($er)
        $errIdioma = true;
    $d = $d->getValues();
    if ( ($d['id_idioma'] == "0" && $d['nivel_idioma'] == "0") ||
         ($d['id_idioma'] == null && $d['nivel_idioma'] == null) 
        ) {
        $totalIdioma--;
    }
}
    $totalIdiomaC = 0; 
$data= $this->formIdioma;
foreach ($data as $d) {
    $d = $d->getValues();
    if (!empty($d['id_idioma']) && !empty($d['nivel_idioma']))
        $totalIdiomaC++;
}
    ?>
<h2 class="blue-title">Idiomas<span class="icon-tiny white down"></span>
	<span class="number"><?=(isset($this->isIdioma)&& $totalIdiomaC != '0')?'('.$totalIdiomaC.')' :''?></span>
</h2>
<div id="languagesF" class="frm-horizontal wrap-controls <?=($errIdioma || !$this->isIdioma)?'open':'close'?>" data-delete="/empresa/aviso/borrar-idioma">
   	<input type="hidden" name="managerIdioma" class="delete_reference">
	<ul class="wrap-skills">
		<?php $contador=0;foreach($this->formIdioma as $indIdi => $formIdioma) : ?>
		<?php echo $this->partial('publica-aviso/_idioma_paso2.phtml', 'empresa'
		    , array('form' => $formIdioma
		    , 'manager' => $this->managerIdioma
		    , 'idPost' => $this->idPost
		    , 'indice' => $indIdi
		    , 'index' => $contador
		    , 'totalIdioma' => $totalIdioma
		    , 'isEditar' => $this->isEditarIdioma
		    , 'isIdioma' => (Count($this->formIdioma) - 1) == $contador ? false : $this->isIdioma
		    , 'online' => $this->online)); $contador++;?>
		<?php endforeach; ?>
	</ul>
	<?php if (!isset($this->online)) : ?>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnLanguage" type="button" class="btn btn-default" data-default="Añadir idioma">Añadir <?=(isset($more) ? $more:'')?> idioma</button>
		</div>
	<?php endif; ?>
</div>

<?php $totalPrograma = count($this->formPrograma);
$data= $this->formPrograma;//$this->managerPrograma->getCleanPost()?$this->managerPrograma->getCleanPost():array();
$errPrograma = false;
foreach ($data as $d) {
    $er = $d->isErrors();
    if($er)
        $errPrograma = true;
    $d = $d->getValues();
    if ( ($d['id_programa_computo'] == 0 && $d['nivel'] == 0) ||
         ($d['id_programa_computo'] == null && $d['nivel'] == null)
        ) {
        $totalPrograma--;
    }
}
    $totalProgramaC = 0;
$data= $this->formPrograma;
foreach ($data as $d) {
    $d = $d->getValues();
    if (!empty($d['id_programa_computo']) && !empty($d['nivel']))
            $totalProgramaC++;
}
    ?>

<h2 class="blue-title">Programas de computadora<span class="icon-tiny white down"></span>
	<span class="number"><?=(isset($this->isPrograma)&& $totalProgramaC != '0')?'('.$totalProgramaC.')' :''?></span>
</h2>
<div id="programsF" class="frm-horizontal wrap-controls <?=($errPrograma || !$this->isPrograma)?'open':'close'?>" data-delete="/empresa/aviso/borrar-programa">
    <input type="hidden" name="managerPrograma" class="delete_reference">
	<ul class="wrap-skills">
		<?php $contador=0;foreach($this->formPrograma as $indProg => $formPrograma) : ?>
		<?php echo $this->partial('publica-aviso/_programa_paso2.phtml', 'empresa'
		    , array('form' => $formPrograma
		    , 'manager' => $this->managerPrograma
		    , 'idPost' => $this->idPost
		    , 'indice' => $indProg
		    , 'index' => $contador
		    , 'totalPrograma' => $totalPrograma
		    , 'isEditar' => $this->isEditarPrograma
		    , 'isPrograma' => (Count($this->formPrograma) - 1) == $contador ? false : $this->isPrograma
		    , 'online' => $this->online)); $contador++;?>
		<?php endforeach; ?>
	</ul>
	<?php if (!isset($this->online)) : ?>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnPrograms" type="button" class="btn btn-default" data-default="Añadir programa">Añadir <?=(isset($more) ? $more:'')?> programa</button>
		</div>
	<?php endif; ?>
</div>

<?php $totalPregunta = count($this->formPregunta); ?>
<?php
$status = ' close'; 
if (count($this->formPregunta) > 1) {
    $status = ' open';
} else {
        $first = reset($this->formPregunta);
        if($first)
        {
            $dataPreguntaValues = $first->getValues();
            if ($dataPreguntaValues['pregunta'] != null) {
                $status = ' open';
            }
        }
} ?>
<button id="btnQuestions" class="btn btn-option btn_question<?=isset($this->isPregunta)?' hide':''?>" type="button"><span class="icon-question"></span>Enviar preguntas al candidato</button>	
<div id="questionWrap" class="<?=isset($this->isPregunta)?'':'hide'?>">								
	<h2 class="blue-title">Enviar preguntas al candidato<span class="icon-tiny white down"></span></h2>
	<div id="preguntasF" class="frm-horizontal wrap-controls open<?//=$status ?>" data-delete="/empresa/aviso/borrar-pregunta">
	    <input type="hidden" name="managerPrograma" class="delete_reference">
		<ul class="wrap-skills">
			<?php $contador=0;foreach($this->formPregunta as $indPreg => $formPregunta) : ?>
			<?php echo $this->partial('publica-aviso/_pregunta_paso2.phtml', 'empresa'
			    , array('form' => $formPregunta
			    , 'manager' => $this->managerPregunta
                            , 'idPost' => $this->idPost
			    , 'indice' => $indPreg
        		    , 'index' => $contador
			    , 'totalPregunta' => $totalPregunta
			    , 'isEditar' => $this->isEditarPregunta
			    , 'isPregunta' => (Count($this->formPregunta) - 1) == $contador ? false : $this->isPregunta
			    , 'online' => $this->online)); $contador++;?>
			<?php endforeach; ?>
		</ul>
		<?php if (!isset($this->online)) : ?>
			<div class="wrap-btn right">
				<span class="response bad hide"></span>
				<button id="btnQuestion" type="button" class="btn btn-default" data-default="Añadir pregunta">Añadir <?=(isset($more) ? $more:'')?> pregunta</button>
			</div>
		<?php endif; ?>
	</div>
</div>

