<nav class="cont-menu row">
	<br>
</nav>
<div class="bg_register_contract">
	<div class="wrap_register_contract">
		<?=$this->partial('_partials/_messages.phtml', array("flashMessages" => $this->flashMessages)) ?>
		<h2>Registro de Contrato</h2>
		<div class="row">
			<div class="grids-4">
				<h3>Plan Aquirido</h3>
				<dl class="property m0">
					<dt>Plan</dt>
					<dd>: Membresia<?php echo $this->compra['nombreMembresia'];?></dd>
					<dt>Precio</dt>
					<dd>: <?php echo $this->moneda.' '.number_format($this->compra['montoTotal'], 2, '.', ',');?></dd>
					<dt>Fecha de pago</dt>
					<dd>: <?php echo date('d-m-Y',strtotime($this->compra['fechaPago']));?></dd>
					
					<dt>Tipo de pago</dt>
					<dd>: <?php 
					if ($this->compra['medioPago'] == 'visa' || $this->compra['medioPago'] == 'mc') : ?>
						 Pago con Tarjeta de Crédito
					<?php else : ?>
						Pago con Pago Efectivo
					<?php endif; ?></dd>
					<?php if ($this->compra['cip']) : ?>
					<dt>CIP</dt>
					<dd>: <?php echo $this->compra['cip'];?></dd>
					<?php endif; ?>
				</dl>
			</div>
			<div class="grids-4">
				<h3>Datos de la Empresa</h3>
				<dl class="property m0">
					<dt>Empresa</dt>
					<dd>: <?php echo $this->compra['razonSocial'];?></dd>
					<dt>Ruc</dt>
					<dd>: <?php echo $this->compra['numeroDoc'];?></dd>
					<dt>Codigo cliente</dt>
					<dd>: <?php echo $this->compra['codigoEnte'];?></dd>
				</dl>
			</div>
		</div>
		<?php if ($this->compra['nroContratoMembresia']) : ?>
			<div class="mT20 txt_center">Nro. de Contrato: <?php echo $this->compra['nroContratoMembresia'];?></div>
		<?php else : ?>
		<form id="frmRegisterContract" action="/empresa/activar-membresia/registrar-contrato" method="post" class="mT20">
			<div class="controls-inline">
				<div class="controls mT10">Ingresar el Nro. de Contrato</div>
				<div class="controls">
                                    <input type="text" name="num_contrato" id ="num_contrato" value="" placeholder="" maxlength="10" required data-parsley-type="alphanum" data-parsley-trigger="change"/>
					<input type="hidden" name="tok" id ="tok" value="<?php echo $this->compra['token']?>"/>
				</div>
				<div class="controls"><button type="submit" class="btn btn-primary">Guardar cambios</button></div>
			</div>
		</form>
		<?php endif; ?>
	</div>
</div>
