<div class="aside_who_is_EMPLEOBUSCO_item_blog">
    <div class="aside_who_is_EMPLEOBUSCO_item_blog_header">
        <h3>Blog AquiEmpleos</h3>
    </div>
    <div class="aside_who_is_EMPLEOBUSCO_item_blog_body">
        <dl class="aside_who_is_EMPLEOBUSCO_list">
            <?php $avisosRss = $this->AvisosBlog(4); $i=0;
            for($i=0;$i<4;$i++){ ?>
                <a href="<?= $avisosRss[$i][1] ?>" title="<?= $avisosRss[$i][2] ?>">
                <dt><?= $avisosRss[$i][2] ?></dt>
                <dd><?= date('d/m/Y', strtotime($avisosRss[$i][0])) ?></dd>
                </a>
            <?php } ?>
        </dl>
        <a href="http://blog.EMPLEOBUSCO.com/" target="_blank" class="aside_link_blog">Ir a Blog</a>
        <div class="clear"></div>
    </div>
</div>
