<div class="EMPLEOBUSCO-blog">
    <h4 class="EMPLEOBUSCO-title middle"><i class="icon icon_pencil"></i>BLOG EMPLEOBUSCO</h4>
    <ul class="list-items2">
        <? 
        $avisosRss = $this->AvisosBlog(4); 
        $i=0;
        for($i=0;$i<4;$i++){ ?>
            <li>
                <span class="icon-row big"></span>
                <a href="<?= $avisosRss[$i][1] ?>" title="<?= $avisosRss[$i][2] ?>"><?= $avisosRss[$i][2] ?></a>
                <p class="date"><?= date('d/m/Y', strtotime($avisosRss[$i][0])) ?></p>
            </li>
        <? } ?>
    </ul>
    <a href="http://blog.EMPLEOBUSCO.com/" title="Ir al Blog">Ir al Blog ›</a>
</div>
