<h4 class="EMPLEOBUSCO-title big"><i class="icon icon_finger"></i>AVISOS DESTACADOS</h4>
<div class="row recent-ads">
    <? foreach ($this->groupUltimosAvisos as $i => $item): 
            $url = $this->serverUrl() . $this->url(
                array(
                    'slug' => $item['slugaviso'], 
                    'url_id' => $item['urlaviso']
                ),'aviso', true); ?>
       <?php $importan=($item['destacado']==1)?'important':''; ?>
            <div class="row ad-box <?=$importan?>">
                <?
                $logo = ($item['logo'] == '' || $item["mostrar_empresa"] == '0' || $item["logo"]
                    == NULL) ? $this->verLogoDefecto ? $this->S('/images/' . $this->logoDefecto) : '' : ELEMENTS_URL_LOGOS . $item['logo'].$this->E()->getLastCommit();
                ?>
                <a href="<?= $url ?>" title="<?= $item['empresa_rs'] ?>" class="grids-1 center-img">
                    <? if ($logo != ''){ ?>
                    <img <?= ($this->ImgLadoMayor($logo)) == "width" ? "width='90'" : "height='90'"; ?>
                              data-src="<?= $logo ?>" alt="<?= $item['empresa_rs'] ?>" />
                    <? }else{ ?>
                    <img src="/static/images/no-image.jpg">
                    <? } ?>
                </a>
                <div class="grids-5">
                    <h2><a href="<?= $url ?>" title="<?= $this->escape($item['puesto']); ?>"><?= $this->escape($item['puesto']); ?></a></h2>
                    <h3><?= $item["empresa_rs"]; ?></h3>
                    <a href="<?= $url ?>" title="Ver aviso" class="view-more">Ver aviso</a>
                    <p>Hace <?= $this->Hace($item['fh_pub']) ?> - <?= $item['ubicacion']; ?></p>
                </div>
            </div>
    <? endforeach ?>
    <br>
    <div class="wrap-btn right"><a class="btn btn-primary" href="/buscar">Ver Todos</a></div>
</div>