<section class="empresas">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="a-destacados-titular">
                    <p class="azul">Empresas que confían en nosotros</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="owl-home-empresas" class=" owl-carousel">
                    <?php foreach ($this->tcn as $key => $value) { ?>
                        <div class="contenedor-contenedor">
                            <div class="contenedor-inline">
                                <div class="item contenedor-img-empresas">
                                    <img class="img-empresa" src="<?=$this->E()->getElementLogos($value['logo'])?>"">
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
</section>