<div class="grids-2">
    <h4 class="EMPLEOBUSCO-title middle"><i class="icon icon_medal"></i>POR PUESTO</h4>
    <ul class="list-items">
        <? $ind= 0;
        foreach ($this->groupNivelPuesto1 as $item):
        $ind++;
            if ($ind - 1 == Zend_Registry::get('config')->portadaPostulante->listaAvisosNivel->limite): 
                break; 
            else: ?>
                <li class="<?= (trim($item['label']) == "Otros") ? 'hide' : '' ?>">
                    <a href="<?= $this->url(array('nivel' => $item['slug']), "buscar", true) ?>" title="<?= $item['label'] ?>">
                        <?= (strlen($item['label']) > 18) ? substr($item['label'], 0, 18) . '...' : $item['label']; ?> 
                    </a>(<?= $item['count']; ?>)</li>
            <? endif; 
        endforeach ?>
    </ul>
    <a href="#moreWM2" title="Ver Todos" class="link view-more winIModal">Ver Todos ›</a>
</div>

<div id="moreWM2" class="moreWM bgWM2 hide">
    <div class="rel">
        <h3>Por Nivel de Puesto</h3>
        <a class="closeH0WM icoCWM" href="#cerrar"><span class="hide">Cerrar</span> </a>
        <fieldset class="fieldsetRBA">
            <label class="labelRadioBA left" for="filtroNivel11"><input name="filtroNivel1" id="filtroNivel11" type="radio" checked="checked" value="numerico" class="iptRadioBA" />
                Por número de avisos
            </label>              
            <label class="labelRadioBA right" for="filtroNivel12"><input name="filtroNivel1" id="filtroNivel12" type="radio" value="alfabetico" class="iptRadioBA" /> 
                Por orden alfabético
            </label>
        </fieldset>
    </div>
    <div class="cntBlocks">

        <!-- 1 -->         
        <div class="blockItemSB numerico">
                <?
                $esColor = 1;
                $count = count($this->groupNivelPuesto1);
                $cont = 0;
                $mostrarFieldSet = true;
                ?>
                <? foreach ($this->groupNivelPuesto1 as
                        $item): ?>
                    <? if ($cont
                        == 0) { ?>
                    <fieldset class="fieldsBA left">
                        <? } else if (($cont
                        >= $count / 2.0) && $mostrarFieldSet) {
                        ?>
                    </fieldset>
                    <fieldset class="fieldsBA right">
        <?
        $esColor = 1;
        $mostrarFieldSet = false;
    }
    ?>
                    <li class="liWM mB5"><a class="itemMWM <? if ($esColor == 2) {
                $esColor = 0;
                echo 'evenMWM';
            } ?>" href="<?= $this->url(array('nivel' => $item['slug']),
                'buscar', true) ?>"><?= $item['label']; ?> (<?= $item['count']; ?>)</a></li>
                    <? $esColor++;
                    $cont++;
                endforeach;
                ?>
            </fieldset>
                <? if ($count == 1) { ?>
                <fieldset class="fieldsBA right"></fieldset>
                <? } ?>
        </div>
        <!-- 2 -->
        <div class="blockItemSB alfabetico hide">
            <?
            $esColor = 1;
            $count = count($this->groupNivelPuesto2);
            $cont = 0;
            $mostrarFieldSet = true;
            ?>
<? foreach ($this->groupNivelPuesto2 as $item): ?>
    <? if ($cont
        == 0) { ?>
                    <fieldset class="fieldsBA left">
        <? } else if (($cont
        >= $count / 2.0) && $mostrarFieldSet) {
        ?>
                    </fieldset>
                    <fieldset class="fieldsBA right">
        <?
        $esColor = 1;
        $mostrarFieldSet = false;
    }
    ?>
                    <li class="liWM mB5"><a class="itemMWM <? if ($esColor == 2) {
        $esColor = 0;
        echo 'evenMWM';
    } ?>" href="<?= $this->url(array('nivel' => $item['slug']), 'buscar', true) ?>"><?= $item['label']; ?> (<?= $item['count']; ?>)</a></li>
    <? $esColor++;
    $cont++;
endforeach;
?>
            </fieldset>
<? if ($count == 1) { ?>
                <fieldset class="fieldsBA right"></fieldset>
<? } ?>
        </div> 
    </div>      
</div>
