<?php
$this->headScript()
    ->appendFile('static/eb/plugin/owl/owl.carousel.js')
    ->appendFile('static/eb/js/postulante/home/home.js')
;
?>
<section>
    <div class="home-principal">
        <div id="owl-home-postulante" class="owl-carousel">             
            <div class="item">
                <div class="contendor-img relative">
                    <img src="<?= $this->E()->banner1('/eb/img/postulante/slider/sp-2.jpg'); ?>)" class="img-home lazyload">

                </div>
            </div>
            <div class="item">
                <div class="contendor-img relative">
                    <img src="<?= $this->E()->banner2('/eb/img/postulante/slider/sp-1.jpg'); ?>)" class="img-home lazyload" ></div>
            </div>
        
        </div>

    </div>
    <div class="contenedor-formulario">
        <form action="<?= $this->url(array(), 'buscar', false); ?>" method="POST">
            <div class="col-sm-7 buscadorinput">
                <div class="text-center">
                    <input  id="q" name="q" type="text" class="form-control lupa" placeholder="Puesto de Trabajo" aria-describedby="sizing-addon2">
                </div>
            </div>
            <div class="col-sm-3 sin-padding buscadorinput">
                <div class="text-center">
                    <?php
                    echo
                    $this->form->pais->setAttribs(array(
                        'id' => 'pais',
                        'class' => 'form-control ubigeo',
                        'aria-describedby' => 'sizing-addon2',
                        'placeholder' => 'Ubicación'
                    ))->renderViewHelper();
                    ?>
                    <!--<input type="text" class="form-control direccion" placeholder="Ubicación" aria-describedby="sizing-addon2">-->
                </div>
            </div>
            <div class="col-sm-2 spb">
                <div class="text-center">
                    <a id="buscar" class="boton buscar" href="#" role="button">Buscar</a>
                </div>
            </div>
        </form>
    </div>
</div>
</section>