<?php $listAreas = $this->Util()->listaAreas($this->groupAreas1); ?>
<?php if (count($listAreas) > 0) : ?>
  <h2>Escoge el área en que deseas trabajar</h2>
  <div class="row jobs_area_wrapper" itemtype="http://schema.org/ItemList">
    <?php $position = 0;?>
    <?php foreach ( $listAreas  as $item) : ?>
    <div class="job_area" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
      <a href="<?=$this->url(array('areas' => $item['slug']), 'buscar', true)?>" onClick="ga('send','event','buscar_avisos','area_interes_<?=$item['slug']?>','<?=$this->postulante?>');" title="<?=$item['label'];?>" >
        <div class="image"><img alt="<?=$item['label'];?>" class="lazy" data-src="<?=$this->S('/main/img/icon_areas/'.$this->NombreArea($item['slug']).'.png')?>" src="<?=$this->S('/main/img/blank.gif')?>"></div>
        <div class="information_area">
          <h4 class="ellipsis" itemprop="item" itemtype="http://schema.org/JobPosting"> <?=$item['label'];?></h4><b><?= $item['count']; ?> puestos</b>
        </div>
      </a>
    </div>        
    <?php endforeach; ?>
  </div>
<?php endif; ?>