<!--No se utiliza por descición de comercial comentado en linea 22 de index.phtml -->
<div class="modArticle bgWhite r10 bgBLTIE">
    <h4 class="bgH4S titleAside">Últimos Avisos<span class="icoArtRel">&nbsp;</span></h4>
    <ul class="listArticle">
        <? foreach ($this->groupUltimosAvisos as $i => $item): ?>
            <li class="itemArticle"> <span class="dateArticle"><a href="./aviso.empleo.html"><?= $item['puesto'] ?></a></span> <span class="txtArticle bold"><?= $item['razon_social']; ?></span> <span class="txtArticle cGray"><?= $item['ubicacion']; ?></span> </li>
        <? endforeach ?>
    </ul>
    <div class="asideLink"> <a href="<?=$this->url(array(),'ultimos_avisos',true)?>" class="btnGoBlog">Ver más</a> </div>
    <div class="hide bgBLBIE">&nbsp;</div>
</div>
