<?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel)) ?>
<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
    <div id="content" class="grid13 rel left theta">
        <div class="texto paddingL10" id="contactCT">
            <h2 class="titleInfoQAPt"> Contáctanos </h2>
            <p class="introContact">Tus opiniones, comentarios y sugerencias son bienvenidos. A partir de ellos, podemos ofrecerte un mejor servicio. Por favor, utiliza el formulario para enviarnos un mensaje. Te responderemos a la brevedad posible.<br/>¡Gracias!</p>                  
            <?= $this->partial('_partials/_contacto.phtml', 'postulante', array('formContacto' => $this->formContacto, 'ispost' => $this->ispost, 'modulo' => $this->modulo)) ?>
        </div>

    </div>

    <div id="sidebar" class="grid7 right theta bgSITIE">
        <div class="innerAside r10 bLBlue bgLBlue"> 
<!--            <div class="eplanning ads300x250" data-section="Right1"></div>-->
        </div>
        <div class="hide bgSIBIE">&nbsp;</div>
    </div>
</div>