<div id="section1">

    <div class="container">

        <section>

            <header>

                <h1>Descubre por qué <a href="<?=SITE_URL?>"><img src="<?= $this->S('/images/landing-doble/logo.jpg'); ?>" alt="EMPLEOBUSCO.com" title="EMPLEOBUSCO.com" /></a> <br/> funciona demasiado bien</h1>

            </header>

        </section>

    </div>

</div> <!-- #section1 -->

<div id="section2">

    <section>

        <div class="container">

            <div class="saprator"></div>
            <iframe src="https://www.youtube.com/embed/nNMVq6nyCcc?autoplay=1" frameborder="0" allowfullscreen></iframe>

            <div class="clear"></div>

            <div class="social-icons">

                <a href="https://www.facebook.com/EMPLEOBUSCO.empleos?utm_source=web-dobles-de-riesgo-2&utm_medium=landing&utm_campaign=dobles-de-riesgo-2&utm_term=boton-facebook&utm_content=EMPLEOBUSCO-facebook" title="Facebook" class="fb" target="_blank">Facebook</a>
                <a href="https://twitter.com/EMPLEOBUSCOempleos?utm_source=web-dobles-de-riesgo-2&utm_medium=landing&utm_campaign=dobles-de-riesgo-2&utm_term=boton-twitter&utm_content=EMPLEOBUSCO-twitter" title="Twitter" class="tw" target="_blank">Twitter</a>
                <a href="https://www.linkedin.com/company/336364?utm_source=web-dobles-de-riesgo-2&utm_medium=landing&utm_campaign=dobles-de-riesgo-2&utm_term=boton-linkedin&utm_content=EMPLEOBUSCO-linkedin" title="Linkedin" class="lin" target="_blank">Linkedin</a>
                <a href="https://www.youtube.com/user/EMPLEOBUSCOpe?utm_source=web-dobles-de-riesgo-2&utm_medium=landing&utm_campaign=dobles-de-riesgo-2&utm_term=boton-youtube&utm_content=EMPLEOBUSCO-youtube=" title="Youtube" class="yt" target="_blank">Youtube</a>

            </div>

        </div>

    </section>

</div> <!-- #section2 -->

<div id="section3">
    <section>
        <div class="container text-center">
            <h2>Ingresa, postula y encuentra <br /> tu <span class="blue">próximo trabajo</span></h2>
            <a href="<?=SITE_URL?>/?utm_source=web-dobles-de-riesgo-2&utm_medium=landing&utm_campaign=dobles-de-riesgo-2&utm_term=boton-ir-a-la-web&utm_content=EMPLEOBUSCO-portada" class="btn">Ir a la Web</a>
        </div>
    </section>
</div> <!-- #section3 -->

<div id="section4">
    <section>
        <div class="container text-center">
            <footer>
                <p>EMPLEOBUSCO, el portal de empleos con más ofertas laborales en Perú</p>
            </footer>
        </div>
    </section>
</div>
