<html>
<head>
<!--general stylesheet-->
<style type="text/css">
body {
	font-family: Arial, Helvetica, sans-serif;
}
p {
	padding: 0;
	margin: 0;
}
h1, h2, h3, p, li {
	font-family: Arial, Helvetica, sans-serif;
}
ul, ol {
	margin: 0;
	padding: 0;
}
</style>
</head>
<body>
<table cellspacing="0" border="0" cellpadding="0" width="100%">
    <tr valign="top">
        <td>
            <!-- heaer -->
            <table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
                 <tr>
                    <td valign="middle" bgcolor="#ffffff" height="30" style="vertical-align: middle; border-bottom: #d6d6d6 0px solid">
                        <p style="font-size: 12px;"> Para asegurar la entrega de nuestros e-mail en su correo, por favor agregue <a  style="COLOR: #0972D3;text-decoration:none;" href="mailto:" ></a> a su libreta de contactos</p>
                    </td>
                 </tr>
            </table>
            <table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
                <tr>
                    <td width="196" height="72" align="center" valign="middle"  bgcolor="#009FEC" style="margin: 0px 0px 0px;color:#ffffff"><img style="border:none;margin: 15px 0px 0px 0px;" src="http://local.EMPLEOBUSCO.pe/static/images/emailing/TRABAJOBUSCO_logo.jpg?v=b2bbf095" alt="EMPLEOBUSCO"/></td>
                    <td width="554" align="right" valign="middle" bgcolor="#F0F0F0" style="padding:15px;text-transform:uppercase; font: bold 20px verdana">EMPLEOBUSCO Selección - Mensaje desde formulario</td>
                </tr>
            </table>
            <!--container-->
            <table cellspacing="0" cellpadding="0" border="0" align="center" width="750" bgcolor="#ffffff">
                <tr>                    
                    <td valign="top" align="center">
                        <!--content-->
                        <br>
<table cellpadding=0 cellspacing=0 width="90%" align=center>
            
            <tr>
                <td colspan="2" style="text-align:justify;font-family:verdana;font-size:12px;width:20%">Este mensaje fue enviado
                     por <b></b> de la Empresa <b></b>. 
                </td>
                
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width:10%"><br>E-mail</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width: 10%"> : <b></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">El teléfono de la empresa es</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Teléfono de Contacto</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Consulta</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>
            
            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Enviado el 23-12-2014 17:09:48.</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px"></td>
            </tr>
            
        </table>
        <br>

    </td></tr>   

        <br><br>                    </td>
                </tr>
	        </table>
            <!--/container-->
            <!--/pie de pagina-->
            <table align="center" width="750" cellspacing="0" border="0" cellpadding="0">
                <tr>
                    <td style="background-repeat: no-repeat" align="center" >
                        <table style="padding-bottom:8px"align="right" width="750"  cellspacing="0" border="0" cellpadding="0">
                            <tr bgcolor="#373737">
                                <td width="172" align="left" valign="middle" style="padding-right: 10px; padding-left: 20px; padding-top: 8px"></td>
                                <td width="441" align="right" valign="middle" style="padding: 10px;color:#FFF;font-size:12px">Los clasificados de empleos de</td>
                                <td width="137" align="right" valign="middle" bgcolor="#FDBF0E" style="padding: 10px; text-align:right"><img src="http://local.EMPLEOBUSCO.pe/static/images/emailing/logoEco.png?v=b2bbf095"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>