<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="who_is_EMPLEOBUSCO">
		  <div class="center_box">
			 <div class="content_who_is_EMPLEOBUSCO">
				<div class="header_who_is_EMPLEOBUSCO">
				  <h2>AquiEmpleos son los avisos clasificados de ofertas laborales del Grupo La Prensa.</h2>
				  <p>Y nuestra página web ayudará a las empresas a ubicar a los candidatos más competitivos del mercado según el perfil del puesto.</p><img src="<?=$this->S('/main/img/que-es-EMPLEOBUSCO.jpg');?>"height="439" width="630" alt="EMPLEOBUSCO.com - Los clasificados de ofertas laborales del Grupo La Prensa" class="hide_mobile">
				</div>
				<div class="body_who_is_EMPLEOBUSCO">
				  <p> <b>AquiEmpleos </b>está comprometida a ayudar a su organización a contratar y retener una fuerza de trabajo más productiva, porque hoy los Recursos Humanos son la ventaja competitiva por excelencia en la mayoría de industrias.</p>
				  <p> <b>AquiEmpleos </b>le ofrece una serie de soluciones que ayudarán a su empresa a conseguir tres cosas: </p>
				  <ul>
					 <li> <span>Contratar a la mejor persona para cada posición.</span></li>
					 <li> <span>Minimizar costos y procedimientos.</span></li>
					 <li> <span>Maximizar su desempeño dentro de la organización.</span></li>
				  </ul>
				</div>
			 </div>
			 <aside class="aside_who_is_EMPLEOBUSCO">
				<div class="aside_who_is_EMPLEOBUSCO_item">
				  <h3>Para empresas anunciantes</h3><i class="icon icon_queesEMPLEOBUSCO1"></i>
				  <p> <b>AquiEmpleos </b>Empresas es un paquete de soluciones flexible que le ayuda a ubicar al mejor candidato para cada puesto al menor costo y tiempo.</p>
				  <p>Si desea contratar cualquiera de estos servicios por favor escribanos a: <a class="blue">info@EMPLEOBUSCO.com </a></p>
				</div>
				<div class="aside_who_is_EMPLEOBUSCO_item">
				  <h3>Para candidatos</h3>
				  <p> <b>AquiEmpleos </b>postulante, es una plataforma multimedia de soluciones que le ayudará a ubicar una gran diversidad de posiciones colocadas por las más prestigiosas empresas del mercado, otorgándole la posibilidad de aplicar a los puestos que se adecúen a su perfil, de una manera rápida y efectiva.</p><i class="icon icon_check"></i><i class="icon icon_queesEMPLEOBUSCO2"></i>
				  <p>Si tiene alguna consulta, por favor escríbanos a: <a class="blue">soporte@EMPLEOBUSCO.com.pe </a></p>
				</div>
				<div class="hide_mobile">
					<?= $this->partial('home/_articulos_interes_new.phtml','postulante', $this->articulosInteres)?>
				</div>
			 </aside>
		  </div>
		</section>
