<?= $this->partial('_partials/_navigation.phtml',array('menu_sel' => $this->menu_sel))?>

<div id="wrapper" class="row">
	 <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
	 <div class="grids-6">
		  <h6 class="titulo-que-es-EMPLEOBUSCO">AquiEmpleos son los avisos clasificados de ofertas laborales del Grupo La Prensa.</h6>
		  <p class="introquees">
				Y nuestra página web ayudará a las empresas a ubicar a los candidatos más competitivos del mercado según el perfil del puesto.
		  </p>
		  <div class="infografia" alt="aquiempleos.com - Los clasificados de ofertas laborales del Grupo La Prensa" title="aquiempleos.com - Los clasificados de ofertas laborales del Grupo La Prensa">
		  </div>
		  <p class="introquees2">
				AquiEmpleos está comprometida a ayudar a su organización a contratar y retener una fuerza de trabajo más productiva, porque hoy los Recursos Humanos son la ventaja competitiva por excelencia en la mayoría de industrias.
		  </p>
		  <p class="introquees">
				AquiEmpleos le ofrece una serie de soluciones que ayudarán a su empresa a conseguir tres cosas:
		  </p>
		  <div class="benefits"></div>
	 </div>

	 <aside class="grids-300">

		  <div class="modArticle" style="background: #F4F7F7;line-height: 17px;">
				<h2 class="titulotipo bold">Para empresas anunciantes</h2>
				<p class="a-borderline">
					 <a href="/empresa/">AquiEmpleos Empresas</a> es un paquete de soluciones flexible que le ayuda a ubicar al mejor candidato para cada puesto al menor costo y tiempo. Si desea contratar cualquiera de estos servicios por favor escribanos a:
					 <a class="r10" href="mailto:<?=CORREO_INFO?>"><?=CORREO_INFO?></a>
				</p>
				<br>
				<h2 class="a-user-postulante bold">Para candidatos</h2>
				<p>
					 <a href="/postulante/">AquiEmpleos postulante</a>, es una plataforma multimedia de soluciones que le ayudará a ubicar una gran diversidad de posiciones colocadas por las más prestigiosas empresas del mercado, otorgándole la posibilidad de aplicar a los puestos que se adecúen a su perfil, de una manera rápida y efectiva. Si tiene alguna consulta, por favor escríbanos a:
					 <a class="r10" href="mailto:soporte@EMPLEOBUSCO.com.pe">soporte@EMPLEOBUSCO.com.pe</a>
				</p>
		  </div>

		  <?= $this->partial('home/_articulos_interes.phtml','postulante', $this->articulosInteres)?>

		  <div class="pubish-ad">
				<p>PUBLICA <span>TU AVISO</span></p>
				<a href="<?= SITE_URL . '/empresa/publica-aviso/' ?>" title="Ingresa Aquí" class="btn btn-primary">Ingresa Aquí</a>
				<span>PROGRAMA PARA EMPRESAS</span>
				<div class="img-aside"></div>
		  </div>
	 </aside>
</div>
