<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel))
?>

<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
    <div class="grids-6" id="contactCT">
        <h2 class="titleInfoQAPt"> Contáctenos </h2>
        <p class="introContact">Sus opiniones, comentarios y sugerencias son bienvenidos. A partir de ellos, podemos ofrecerle un mejor servicio. Por favor, utilice el formulario para enviarnos un mensaje. Le responderemos a la brevedad posible.<br/>¡Gracias!</p>

        <?=
        $this->partial('_partials/_contacto.phtml', 'postulante',
            array('formContacto' => $this->formContacto, 'ispost' => $this->ispost,
            'modulo' => $this->modulo))
        ?>
    </div>
    <aside class="grids-300">
        <div class="eplanning ads300x250" data-section="Right1"></div>
    </aside>
</div>