<?php 

$colores = array(
    'Digital' => 'purple',
    'Esencial' => 'orange',
    'Selecto' => 'blue',
    'Premium' => 'green'
);
?>
<nav><br></nav>
<div id="wrapper">
    <div class="legend"><a href="/empresa">Inicio</a> » <span>Planes de Membresías</span></div>
    <?= $this->partial('_partials/_messages.phtml', array("flashMessages" => $this->flashMessages))
    ?>
    <h2>Planes de Membresías</h2>
    <p>Si tienes dudas o consultas sobre los planes de membresía, llámenos al 311-6707 Opción 3</p>
    <br><br>
    <div class="row types-membership">
        <?php $first = true; ?>
        <?php foreach ($this->membresias as $membresia) : ?>
        <div itemscope itemtype="http://schema.org/Product" class="choose-ads <?php echo $colores[$membresia['nombreProducto']]?>">
            <?php // <div class="band_new"></div> ?>
            <div class="title-ads">
                <h2 class="title-big" itemprop="name">Membresía<br><span class="title-bigxx"><?php echo $membresia['nombreProducto'];?></span></h2> 
                <p class="text-smallxx">Desde</p><span class="text-white"><?php echo $this->moneda?> <?php echo number_format($membresia['tarifaPrecio'],0,'.',',');?></span><p class="text-right">+<?php echo $this->igv?></p>
            </div>
            
            
            <h3 class="title">Beneficios Medio Web:</h3>
            <ul  itemprop="description" class="check-list <?php echo ($first ? 'first' : '') ?>">
                <?php foreach($membresia['beneficios'] as $beneficio) : ?>                
                <?php if (strstr($beneficio['codigo'],'-web') || ($beneficio['codigo'] == 'memdigi') || ($beneficio['codigo'] == 'memmens') ) : ?>
                <li><i class="icon icon_check"></i><?=$beneficio['descbeneficio']?></li>
                <?php endif; ?>
                <?php endforeach;?>
            </ul>
            
            
            <?php 
                /*if($membresia['nombreProducto'] == 'Digital') {                    
                    
                    if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                            $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                        <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => $membresia['id']), false, true) ?>" onclick="ga('send', 'event', 'P1_Gratuito', '' , 'P1_Gratuito');" class="btn btn-primary btn-middle">Continuar</a>
                    <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                        <a class="btn btn-primary tooltip btn-middle" data-tool="Solo para empresas." disabled>Continuar</a> 
                    <?php } else { ?>
                        <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' =>$membresia['id']), false, true) ?>" href="#loginP" title="">Continuar</a>
                    <?php } 
                    
                    echo '</div>';
                    continue;
                }*/
            ?>
            
            <?php if($membresia['nombreProducto'] != 'Digital' && $membresia['nombreProducto'] != 'Mensual') { ?>
            <h3 class="title">Beneficios Medio Impreso:</h3>
            <ul  itemprop="description" class="check-list">
                <?php foreach($membresia['beneficios'] as $beneficio) : ?>
                <?php if (strstr($beneficio['codigo'],'-imp') ) : ?>
                <li><i class="icon icon_check"></i><?=$beneficio['descbeneficio']?></li>
                <?php endif; ?>
                <?php endforeach;?>
            </ul>
            <?php } else { ?>
            <h3 class="title">&nbsp;</h3>
            <ul class="check-list">
                <li>&nbsp;</li>                
            </ul>
            <?php } ?>
            
            
            <?php if($membresia['nombreProducto'] != 'Mensual') { ?>
            <h3 class="title">Beneficios Adicionales:</h3>
            <ul itemprop="description" class="check-list">
                <?php foreach($membresia['beneficios'] as $beneficio) : ?>
                <?php if (strstr($beneficio['codigo'],'-adic') ) : ?>
                <li><i class="icon icon_check"></i><?=$beneficio['descbeneficio']?></li>
                <?php endif; ?>
                <?php endforeach;?>
            </ul>
            <?php }?>
            
            
            

            <?php if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                    $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                <a itemprop="url" href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => $membresia['id']), false, true) ?>" onclick="ga('send', 'event', 'P1_Gratuito', '' , 'P1_Gratuito');" class="btn btn-primary btn-middle">Continuar</a>
            <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                <a class="btn btn-primary tooltip btn-middle" data-tool="Solo para empresas." disabled>Continuar</a> 
            <?php } else { ?>
                <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => $membresia['id']), false, true) ?>" href="#loginP" title="">Continuar</a>
            <?php } ?>
                
        </div>
        <?php $first = false; ?>
        <?php endforeach; ?>
        
        <?php /* ?>
        <div class="choose-ads purple">
            <div class="band_new"></div>
            <div class="title-ads"><h2 class="title-big">Membresía<br><span class="title-bigxx">DIGITAL</span></h2> <p class="text-smallxx">Desde</p><span class="text-white">$ 700*</span><p class="text-right">+IVA</p></div>
            
            <h3 class="title">Beneficios Medio Web:</h3>
            <ul class="check-list first">                                    
            <?php foreach($this->membresias as $membresia) : ?>
                <?php if ($membresia['id_membresia'] == 7) : ?>
                <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                <?php endif; ?>
            <?php endforeach;?>
            </ul>       
            <p class="title tip">*Oferta por tiempo limitado</p>

            <?php if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                    $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 7), false, true) ?>" onclick="ga('send', 'event', 'P1_Gratuito', '' , 'P1_Gratuito');" class="btn btn-primary btn-middle">Continuar</a>
            <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                <a class="btn btn-primary tooltip btn-middle" data-tool="Solo para empresas." disabled>Continuar</a> 
            <?php } else { ?>
                <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 7), false, true) ?>" href="#loginP" title="">Continuar</a>
            <?php } ?>
        </div>
        <div class="choose-ads orange">
            <div class="title-ads"><h2 class="title-big">Membresía Anual<br><span class="title-bigxx">ESENCIAL</span></h2> <p class="text-smallxx">Desde</p><span class="text-white">$ 3,000</span><p class="text-right">+IVA</p></div>
            
            <h3 class="title">Beneficios Medio Web:</h3>            
            <ul class="check-list first">
                <?php foreach($this->membresias as $membresia) : ?>
                <?php if ($membresia['id_membresia'] == 1 && $membresia['codigo'] == 'memesen-web') : ?>
                <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                <?php endif; ?>
                <?php endforeach;?>                
            </ul>
            <h3 class="title">Beneficios Medio Impreso:</h3>
            <ul class="check-list">
                <?php foreach($this->membresias as $membresia) : ?>
                <?php if ($membresia['id_membresia'] == 1 && $membresia['codigo'] == 'memesen-imp') : ?>
                <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                <?php endif; ?>
                <?php endforeach;?>                                
            </ul>

            <h3 class="title">Beneficios Adicionales:</h3>
            <ul class="check-list">
                <?php foreach($this->membresias as $membresia) : ?>
                <?php if ($membresia['id_membresia'] == 1 && $membresia['codigo'] == 'memesen-adic') : ?>
                <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                <?php endif; ?>
                <?php endforeach;?>                                
            </ul>
                                    
            
            <?php if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                    $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 1), false, true) ?>" class="btn btn-primary btn-middle" onclick="ga('send', 'event', 'P1_Destacado', '' , 'P1_Destacado');">Continuar</a>
            <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                <a class="btn btn-primary btn-middle tooltip" data-tool="Solo para empresas." disabled>Continuar</a> 
            <?php } else { ?> 
                <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 1), false, true) ?>" href="#loginP" title="">Continuar</a>
            <?php } ?>
                

        </div>
        <div class="choose-ads blue">
            <div class="title-ads"><h2 class="title-big">Membresía Anual<br><span class="title-bigxx">SELECTO</span></h2> <p class="text-smallxx">Desde</p><span class="text-white">$ 5,000</span><p class="text-right">+IVA</p></div>
            
            <h3 class="title">Beneficios Medio Web:</h3>
            <ul class="check-list first">
                <?php foreach($this->membresias as $membresia) : ?>
                    <?php if ($membresia['id_membresia'] == 2 && $membresia['codigo'] == 'memsele-web') : ?>
                    <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                    <?php endif; ?>
                <?php endforeach;?>                
            </ul>
            <h3 class="title">Beneficios Medio Impreso:</h3>
            <ul class="check-list">
                <?php foreach($this->membresias as $membresia) : ?>
                    <?php if ($membresia['id_membresia'] == 2 && $membresia['codigo'] == 'memsele-imp') : ?>
                    <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                    <?php endif; ?>
                <?php endforeach;?>
                
            </ul>

            <h3 class="title">Beneficios Adicionales:</h3>
            <ul class="check-list">
                <?php foreach($this->membresias as $membresia) : ?>
                    <?php if ($membresia['id_membresia'] == 2 && $membresia['codigo'] == 'memsele-adic') : ?>
                    <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
                    <?php endif; ?>
                <?php endforeach;?>                
            </ul>
            
            
            
            
            
            
            <?php if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                    $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 2), false, true) ?>" class="btn btn-primary btn-middle" data-type="selecto">Continuar</a>
            <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                <a class="btn btn-primary tooltip btn-middle" data-tool="Solo para empresas." disabled>Continuar</a> 
            <?php } else { ?>
                <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 2), false, true) ?>" href="#loginP" title="">Continuar</a>
            <?php } ?>
            
            
        </div>
        <div class="choose-ads green">
            <div class="title-ads"><h2 class="title-big">Membresía Anual<br><span class="title-bigxx">PREMIUM</span></h2> <p class="text-smallxx">Desde</p><span class="text-white">$ 7,500</span><p class="text-right">+IVA</p></div>
            
            <h3 class="title">Beneficios Medio Web:</h3>
            <ul class="check-list first">
                <?php foreach($this->membresias as $membresia) : ?>
            <?php if ($membresia['id_membresia'] == 3 && $membresia['codigo'] == 'memprem-web') : ?>
            <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
            <?php endif; ?>
            <?php endforeach;?>
            </ul>
            <h3 class="title">Beneficios Medio Impreso:</h3>
            <ul class="check-list">
                <?php foreach($this->membresias as $membresia) : ?>
            <?php if ($membresia['id_membresia'] == 3 && $membresia['codigo'] == 'memprem-imp') : ?>
            <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
            <?php endif; ?>
            <?php endforeach;?>
            </ul>
            <h3 class="title">Beneficios Adicionales:</h3>
            <ul class="check-list">
            <?php foreach($this->membresias as $membresia) : ?>
            <?php if ($membresia['id_membresia'] == 3 && $membresia['codigo'] == 'memprem-adic') : ?>
            <li><i class="icon icon_check"></i><?=$membresia['desc']?></li>
            <?php endif; ?>
            <?php endforeach;?>
            </ul>
            
            
            
            
            <?php if ($this->rol == Application_Model_Usuario::ROL_EMPRESA_ADMIN ||
                    $this->rol == Application_Model_Usuario::ROL_EMPRESA_USUARIO) { ?>
                <a href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 3), false, true) ?>" class="btn btn-primary btn-middle">Continuar</a>
            <?php } else if ($this->rol == Application_Model_Usuario::ROL_POSTULANTE) { ?>
                <a class="btn btn-primary tooltip btn-middle" data-tool="Solo para empresas." disabled>Continuar</a> 
            <?php } else { ?>
                <a class="btn btn-primary login_modal btn-middle" data-href="<?= $this->url(array('module' => 'empresa', 'controller' => 'comprar-membresia-anual', 'action' => 'paso1', 'membresia' => 3), false, true) ?>" href="#loginP" title="">Continuar</a>
            <?php } ?>
                
        </div>
         <?php */ ?>
        
    </div>

</div>