<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
    <h2 class="titleInfoQAPt">Nuevo en AquiEmpleos</h2>
    <div id="a_cont_nuevo">
        <p class="pNone f38 c3 bold alignC" id="titleInfAvP">
            Está en la página web de empleos
            <br />
            más importante del país
        </p>
        <p class="pNone_em c3 f18 alignC">
            En solo 4 pasos podrá registrarse, colocar avisos de empleos y administrar sus procesos de selección:
        </p>
        <div id="a-parte-emp" class="grid19 center">
        </div>
        <div id="a-se-parte_empr" class="grid19 center" >
            <div id="a-parte-elas-em">
                <div>
                    <p class="a-trabajamos_em f18">
                        Al ser parte de
                        <strong>AquiEmpleos</strong> obtendrá los siguientes beneficios:
                    </p><br>
                    <ul>
                        <li class="a-checkazul f14 bold">
                            Publicar desde la web, avisos de empleos en los diarios: La Prensa y Trome
                        </li>
                        <li class="a-checkazul f14 bold">
                            Administrar sus Procesos de Selección en el menor tiempo y de una manera práctica y eficaz
                        </li>
                        <li class="a-checkazul f14 bold">
                            Acceder a la mejor y más grande Base de Datos de Candidatos del país
                        </li>
                    </ul>
                    <div id="a-benefi-empresa">
                    </div>
                </div>
            </div>
        </div>
        <div id="aCntSumilla" class="grid19 center">

            <div id="a-sumilla-registrate" class="grid14 left">
                <p>
                    <span class="textRelAsid bold">!No esperes más!</span>
                    <span class="f14 bold">Regístrese en la web donde </span>
                    <span class="txtBigP1 f14">las empresas más prestigiosas
                        del país publican sus avisos y administran</span>
                    <span class="f14 bold"> sus procesos de selección.</span>
                </p>
            </div>
            <div id="a-registrate_emp" class="grid3 right">
                <a href="/empresa/registro-empresa" id="aRegistrateBtn" class="right btn btn-primary btnSptEmp">
                    Regístrate
                </a>
            </div>
        </div>
    </div>
</div>
