<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>


<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
    <div id="empWhatApt1" class="grids-6 content-text">
        <h2>¿Por qué usar aquiempleos.com?</h2>
        <p>Somos el portal de empleos líder en Perú, pertenecemos al grupo La Prensa y contamos con la base de CVs de candidatos más grande y completa en Perú.</p>
        <p>Nuestras soluciones únicas para tus procesos de selección a través de los siguientes medios:</p>
        <div id="a-screen-pro2" class="rel">
            <div id="a-tres-pro">
                <h6 class="a-nuestraweb bold">Nuestra Web</h6>
                <p class="a-nuestra-web-ap">www.aquiempleos.com</p>
                <h6 class="a-suplemento-EMPLEOBUSCO bold">Diario La Prensa</h6>
                <p></p>
                <h6 class="a-suplemento-talan bold">Diario Trome</h6>
                <p class="a-suplemen-talan">en la sección Empleos AquiEmpleos</p>
            </div>
        </div>
        <p>"Nuestros candidatos valoran nuestra seriedad, profesionalismo y tecnología de vanguardia para ofrecerte una herramienta acorde con tus requerimientos y necesidades para tus procesos de selección las 24 horas del día los 365 días del año"</p>
        <div class="whyus-ad">
            <p class="title-big">Sé parte del mundo AquiEmpleos</p>
            <p class="whyus-middle">Registra a tu empresa, ingresa tu aviso  y encontrarás los candidatos idóneos según el perfil que desees.</p>
            <a href="/empresa/registro-empresa" class="btn btn-primary">Registrate</a>
        </div>
        <p>Siempre encontrarás Tips, artículos y entrevistas que te ayudarán a prepararte en tus procesos de selección en:</p><br>
        <ul class="list-items fix">
            <li><a href="http://facebook.com/pages/EMPLEOBUSCOpe/156487814406534" target="_blank">Nuestra Página en Facebook</a></li>
            <li><a href="http://blog.EMPLEOBUSCO.com/" target="_blank">Nuestro blog</a></li>
            <li><a href="javascript:;">Nuestra Web</a></li>
            <li><a href="http://www.linkedin.com/company/EMPLEOBUSCO">Linkedin</a></li>
        </ul>
    </div>
    <aside class="grids-300">
        <div class="eplanning ads300x250" data-section="Right1"></div>
        <?=
        $this->partial('home/_articulos_interes.phtml', 'postulante',
            $this->articulosInteres)
        ?>
        <div class="pubish-ad">
            <p>PUBLICA <span>TU AVISO</span></p>
            <a href="<?= SITE_URL . '/empresa/publica-aviso/' ?>" title="Ingresa Aquí" class="btn btn-primary">Ingresa Aquí</a>
            <span>PROGRAMA PARA EMPRESAS</span>
            <div class="img-aside"></div>
        </div>
    </aside>
</div>
