<?=
$this->partial('_partials/_navigation.phtml',
	 array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>

<div id="wrapper" class="row">
	 <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
	 <div class="grids-6">
		  <h6 class="titulo-que-es-EMPLEOBUSCO">En aquiempleos.com podrás anunciar tus ofertas de trabajo en el portal Web y en su edición impresa en Prensiguia del Diario La Prensa.</h6>
		  <p class="introquees">
				Y nuestra página web  ayudará a las empresas a ubicar a los candidatos más competitivos del mercado según el perfil del puesto.
		  </p>
		  <div class="infografia"></div>
		  <br>
		  <h6 class="titulo-que-es-EMPLEOBUSCO">Para empresas anunciantes </h6>
		  <p class="introquees2">
				En aquiempleos.com estamos comprometidos a ayudar a tu organización a contratar y retener una fuerza de trabajo más productiva, porque hoy los Recursos Humanos son la ventaja competitiva por excelencia en la mayoría de industrias.
		  </p>
		  <p class="introquees">
				En aquiempleos.com  te ofrecemos una serie de soluciones que ayudarán a tu empresa a conseguir tres cosas:
		  </p>
		  <div class="benefits"></div>
	 </div>

	 <aside class="grids-300">

		  <div class="modArticle" style="background: #F4F7F7;line-height: 17px;">
				<h6 class="titulotipo bold">Para empresas anunciantes</h6>
				<p class="a-borderline">
					 <a href="/empresa/">aquiempleos.com Empresas</a> es un paquete de soluciones flexible que le ayuda a ubicar al mejor candidato para cada puesto al menor costo y tiempo. Si desea contratar cualquiera de estos servicios por favor escribanos a:
					 <a class="r10" href="mailto:<?=CORREO_INFO?>"><?=CORREO_INFO?></a>
				</p>
				<br>

		  </div>

		  <? //= $this->partial('home/_articulos_interes.phtml', 'postulante',$this->articulosInteres) ?>

		  <div class="pubish-ad">
				<p>PUBLICA <span>TU AVISO</span></p>
				<a href="<?= SITE_URL . '/empresa/publica-aviso/' ?>" title="Ingresa Aquí" class="btn btn-primary">Ingresa Aquí</a>
				<span>PROGRAMA PARA EMPRESAS</span>
				<div class="img-aside"></div>
		  </div>
	 </aside>
</div>
