<?=
$this->partial('_partials/_navigation.phtml',
	 array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>

<div id="wrapper">
	<?= $this->partial('_partials/_messages.phtml',
		  array("flashMessages" => $this->flashMessages)) ?>
	 <div class="box_info">
		  <h2>AquiEmpleos Selección</h2>
		  <p>Cuenta con la red más grande de medios del país y con profesionales especializados con amplio conocimiento del mercado laboral, garantizando así un servicio integral con un amplio poder de convocatoria, atención personalizada y con un fuerte compromiso orientado a la calidad.</p>
	 </div>

	 <div class="box_info blue">
		  <p>Es el servicio que AquiEmpleos  ofrece a las empresas para facilitarles y garantizarles la contratación de su personal, optimizando los tiempos en cada una de las etapas del proceso de reclutamiento, selección y evaluación. Obteniendo así, la mejor opción para su organización.</p>
		  <a href="javascript:;" onClick="ga('send', 'event', 'EMPLEOBUSCO_Selección', 'Contacto');" class="btn btn-primary btn-big btn_contact" title="Contáctate">Contáctate</a>
	 </div>

	 <div class="how_works">
		  <h2><span>Cómo funciona</span><br>AquiEmpleos SELECCIÓN</h2>
		  <div class="row">
				<div class="item_how fltleft">
					 <div class="row">
						  <h3>CONVOCATORIA</h3>
						  <span>1</span>
					 </div>
					 <p>AquiEmpleos realizará el levantamiento de perfil en base a las necesidades del puesto, planteando una estrategia de medios para una convocatoria eficiente y eficaz.</p>
				</div>
				<div class="item_how">
					 <div class="row">
						  <h3>RECLUTAMIENTO</h3>
						  <span>2</span>
					 </div>
					 <p>AquiEmpleos se encargará de aplicar a los candidatos, filtros curriculares según el perfil del puesto definido.</p>
				</div>
				<div class="item_how">
					 <div class="row">
						  <h3>SELECCIÓN</h3>
						  <span>3</span>
					 </div>
					 <p>AquiEmpleos aplicará evaluaciones, entrevistas y preparará informes psicolaborales de la terna final para la empresa.</p>
				</div>
		  </div>
	 </div>

	 <div class="box_infocontact row">
		  <p>
				Mayor información 3116500<br/>
				* Ximena Delgado (anexo 3672): ximena.delgado@comercio.com.pe<br/>
				* Carola Lambruschini (anexo 2146): clambruschini@comercio.com.pe
		  </p>
		  <div class="mail_info">
				<a href="javascript:;" onClick="ga('send', 'event', 'EMPLEOBUSCO_Selección', 'Contacto');" class="btn btn-primary btn_contact" title="Contáctate">Contáctate</a>
		  </div>
	 </div>



</div>
