<?=Application_Model_Partials::getMenuPostulante(); ?>
<div class="postulant_notification">
  <div class="center_box bg_white">
    <div class="header_postulant_notification">
      <div class="icon icon_mail"></div>
      <h2 class="title">Notificaciones <?php echo ($this->nroregistrosnoti == 0) ? '' : '(<span id="notificationCounter">'.$this->nroregistrosnoti.'</span> nuevos)'  ?></h2>
    </div>
    <div class="body_postulant_notification row">
        <?php if (count($this->notificaciones) > 0) : ?>

      <ul class="body_postulant_notification_list">
          <?php $i=0; ?>
          <?php  foreach ($this->notificaciones as $item): ?>
            <?php $class = ($i == 0) ? ' is_selected ': ''; ?>
            <li class="row<?=($item['leido'])?' is_read ':' is_stand ';  ?><?=$class?>"  data-postulacion="<?=$item['postulacion']?>" data-idaviso="<?=$item['idaviso']?>" >
              <p>
                <b class="bullet"></b>
                <span><?=$item['puesto']?></span>
                <small><?=$item['empresa_rs-post']?>.</small>
            </p>
            <div class="hour_list">
              <span><?=$this->Util()->fechaHora($item['fh-msg'])?></span>
              <b class="bullet"></b>
              <i class="icon icon_back"></i>
            </div>
          </li>
           <?php $i++; ?>
           <?php endforeach; ?>
      </ul>
      <div class="body_postulant_notification_messages">
        <div class="loading_error hide">Tuvimos un error al cargar la conversación, por favor inténtelo de nuevo</div>
        <div class="loading_box hide"><img src="<?=$this->S('/main/img/ajax-loader.gif');?>" alt="cargando"/><p>Cargando conversación..</p></div>
        <?php if(isset($this->datajsonoti)) { ?>
        <?php
            $logoEmpresa = empty($this->logoEmpresa) ?
                $this->S('/images/icon-empresa-blank.png')
                : ELEMENTS_URL_LOGOS .$this->logoEmpresa;

            $logoPostulante = empty($this->logopostulante) ?
                    $this->S('/images/profile-default.jpg')
                    : ELEMENTS_URL_IMG .$this->logopostulante;
        ?>
        <div class="body_messages">
            <?php   foreach ($this->datajsonoti as $msj) { ?>
                <?php if($msj['tipo_mensaje']=='pregunta') { ?>
                <div class="message_tx row">
                  <p>	<span class="date"><?=$this->Util()->fechaDiMes($msj['fh'])?>.- </span><?=$msj['cuerpo']?></p>
                  <div class="image_box center_image"><img src="<?= $logoEmpresa ?>"></div>
                </div>
                <?php } ?>
                <?php if($msj['tipo_mensaje']=='mensaje'){?>
                <div class="message_rx row">
                  <p> <span class="date"><?=$this->Util()->fechaDiMes($msj['fh'])?>.- </span><?=$msj['cuerpo']?></p>
                  <div class="crop_image" style="background-image:url(<?= $logoPostulante ?>)"></div>
                </div>
                <?php } ?>
                <?php if($msj['tipo_mensaje']=='invitación'){?>
                <div class="message_rx row">
                    <p> <span class="date"><?=$this->Util()->fechaDiMes($msj['fh'])?>.-
                        </span><?= str_replace("</P>","",str_replace("<P align=center style=\"color:#3366ff\">","",str_replace("<br><br>", "", $msj['cuerpo'])))?>.</p>
                  <div class="crop_image" style="background-image:url(<?= $logoPostulante ?>)"></div>
                </div>
                <?php } ?>
            <?php    } ?>
        </div>
        <div class="header_messages">
          <h2 class="job_title"><?=$this->puesto?></h2>
          <span class="company_name"><?=$this->empresa?></span>
          <form class="box_conteiner" action="<?=$this->url(array('module'=>'postulante','controller'=>'notificaciones','action'=>'guardar-rpta'))?>">
               <div class="box_conteiner_img row">
                 <div class="crop_image" style="background-image:url(<?= $logoPostulante ?>)"></div>
                 <div class="box_conteiner_talk"><i> </i>
                    <?=$this->formRest->mensaje->setAttribs(array('id'=>'mensaje', 'placeholder'=>'Ingresa una respuesta'))->renderViewHelper();?>
                   <p class="max_nummber">(máximo <?=$this->formRest->mensaje->getAttrib('data-maxlength')?> caracteres)</p><a href="#" class="btn btn_send" id="sendMessage"><span class="btn_label">Enviar</span><span class="btn_spinner"></span></a>
                 </div>
               </div>
                <?=$this->formRest->id_mensaje->setAttribs(array('id'=>'id_mensaje' ))->renderViewHelper();?>
                <?=$this->formRest->hidAuthTokenCuestion->setAttribs(array('id'=>'hidAuthTokenCuestion'))->renderViewHelper();?>
             </form>
        </div>
        <?php }?>
      </div>

        <?php else: ?>
        <div class="no_results">Aún no cuentas con notificaciones.</div>
        <?php endif; ?>

    </div>
  </div>
</div>
<script type='text/template' id="tplConversation">
  <% _.each(conversation, function(item) { %>

    <% if(item.type == "postulante"){ %>
      <div class="message_rx row">
        <p><span class="date"><%= item.date %>.- </span><%= item.text %></p>
        <div class="crop_image" style="background-image:url(<%= imgPerson %>)"></div>
      </div>
    <% }else{ %>
      <div class="message_tx row">
        <p> <span class="date"><%= item.date %>.- </span><%= item.text %>.</p>
        <div class="image_box center_image"><img src="<%= imgCompany %>"></div>
      </div>
    <% } %>

  <% }); %>
</script>
