<div class="iBlockMSA mB10">
    <h3 class="titleSA alignL active acordionJ"><?= $this->titulo ?><span class="<?= $this->ico ?> icoTi">&nbsp;</span><span class="icoTi icoATAP">&nbsp;</span></h3>
    <form id="fFilter<?= $this->pfijof1 ?>" action="#" class="fFilterS bgLBlue r10B open">
        <fieldset>
            <? foreach ($this->datos['visible'] as $item):?>
                <label for="areas<?= $item['slug'] ?>" class="labelFS">
                    <span class="iBlockLSA left">
                        <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>"
                               type="checkbox" class="checkN noBdr" <?=($this->param!=""?(in_array($item["slug"],explode($this->constantes->separador,$this->filtro))?"checked":""):"")?> />
                    </span> 
                    <span class="iBlockRSA right">
                        <?
                          $conf_areas= $this->constantes->areas;
                          $conf_nivel= $this->constantes->nivel;
                          $conf_fechapub= $this->constantes->fechapub;
                          $conf_remuneracion= $this->constantes->remuneracion;
                          $conf_empresa= $this->constantes->empresa;
                          $conf_ubicacion= $this->constantes->ubicacion;

                          $filtros2 = array();
                          $separador = $this->constantes->separador;
                          if($this->param==$conf_areas){ //areas
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{ 
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['areas'] = $valor;
                                if($filtros2["areas"]=="") $filtros2["areas"]=null;
                          }
                          if($this->param==$conf_nivel){ //nivel
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['nivel'] = $valor;
                                if($filtros2["nivel"]=="") $filtros2["nivel"]=null;
                          }
                          if($this->param==$conf_fechapub){ //FechaPub
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['fecha-publicacion'] = $valor;
                                if($filtros2["fecha-publicacion"]=="") $filtros2["fecha-publicacion"]=null;
                          }
                          if($this->param==$conf_remuneracion){ //Remuneracion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($nueva=="0")
                                {
                                    $valor = str_replace($actual, "", $actual);
                                }else{
                                    if($this->Existepalabra($nueva,$actual,$separador)){
                                        $x = explode("--", $actual);
                                        array_splice($x,array_search($item["slug"],$x),1);
                                        $valor = implode("--", $x);
                                    }else{
                                        if($actual!="") $valor = $actual.$separador.$nueva;
                                        else $valor = $nueva;
                                    }
                                }
                                $filtros2['remuneracion'] = $valor;
                                if($filtros2["remuneracion"]=="") $filtros2["remuneracion"]=null;
                          }
                          if($this->param==$conf_empresa){ //Empresa
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['empresa'] = $valor;
                                if($filtros2["empresa"]=="") $filtros2["empresa"]=null;
                          }
                          if($this->param==$conf_ubicacion){ //Ubicacion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['ubicacion'] = $valor;
                                if($filtros2["ubicacion"]=="") $filtros2["ubicacion"]=null;
                          }
                          
                          $ruta = $this->url($filtros2,'buscar',false);
                       ?>
                        <a class="aFilterB" href="<?=$ruta?>"><?= $this->escape($item['msg']) ?></a>
                        <span class="count">(<?= $item['cant'] ?>)</span>
                    </span>
                </label>
            <? endforeach; ?>
        </fieldset>
 
 
 <div rel="<?= count($this->datos['ocultos']) ?>" class="cntCloseIt hide bgLBlue ">
        <? foreach ($this->datos['ocultos'] as $columna): ?>
	            
	                    <? foreach ($columna as $item): ?>
	                        <label for="areas<?= $item['slug'] ?>" class="labelFS">
	                            <span class="iBlockLSA left">
	                                <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>" type="checkbox" class="checkN noBdr" <?=($this->param!=""?(in_array($item["slug"],explode($this->constantes->separador,$this->filtro))?"checked":""):"")?> />
	                            </span>
	                            <span class="iBlockRSA right">
	                            <?
	                          $conf_areas= $this->constantes->areas;
	                          $conf_nivel= $this->constantes->nivel;
	                          $conf_fechapub= $this->constantes->fechapub;
	                          $conf_remuneracion= $this->constantes->remuneracion;
	                          $conf_empresa= $this->constantes->empresa;
	                          $conf_ubicacion= $this->constantes->ubicacion;
	
	                          $filtros2 = array();
	                          $separador = $this->constantes->separador;
	                          if($this->param==$conf_areas){ //areas
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($this->Existepalabra($nueva,$actual,$separador)){
	                                    $x = explode("--", $actual);
	                                    array_splice($x,array_search($item["slug"],$x),1);
	                                    $valor = implode("--", $x);
	                                }else{
	                                    if($actual!="") $valor = $actual.$separador.$nueva;
	                                    else $valor = $nueva;
	                                }
	                                $filtros2['areas'] = $valor;
	                                if($filtros2["areas"]=="") $filtros2["areas"]=null;
	                          }
	                          if($this->param==$conf_nivel){ //nivel
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($this->Existepalabra($nueva,$actual,$separador)){
	                                    $x = explode("--", $actual);
	                                    array_splice($x,array_search($item["slug"],$x),1);
	                                    $valor = implode("--", $x);
	                                }else{
	                                    if($actual!="") $valor = $actual.$separador.$nueva;
	                                    else $valor = $nueva;
	                                }
	                                $filtros2['nivel'] = $valor;
	                                if($filtros2["nivel"]=="") $filtros2["nivel"]=null;
	                          }
	                          if($this->param==$conf_fechapub){ //FechaPub
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($this->Existepalabra($nueva,$actual,$separador)){
	                                    $x = explode("--", $actual);
	                                    array_splice($x,array_search($item["slug"],$x),1);
	                                    $valor = implode("--", $x);
	                                }else{
	                                    if($actual!="") $valor = $actual.$separador.$nueva;
	                                    else $valor = $nueva;
	                                }
	                                $filtros2['fecha-publicacion'] = $valor;
	                                if($filtros2["fecha-publicacion"]=="") $filtros2["fecha-publicacion"]=null;
	                          }
	                          if($this->param==$conf_remuneracion){ //Remuneracion
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($nueva=="0")
	                                {
	                                    $valor = str_replace($actual, "", $actual);
	                                }else{
	                                    if($this->Existepalabra($nueva,$actual,$separador)){
	                                        $x = explode("--", $actual);
	                                        array_splice($x,array_search($item["slug"],$x),1);
	                                        $valor = implode("--", $x);
	                                    }else{
	                                        if($actual!="") $valor = $actual.$separador.$nueva;
	                                        else $valor = $nueva;
	                                    }
	                                }
	                                $filtros2['remuneracion'] = $valor;
	                                if($filtros2["remuneracion"]=="") $filtros2["remuneracion"]=null;
	                          }
	                          if($this->param==$conf_empresa){ //Empresa
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($this->Existepalabra($nueva,$actual,$separador)){
	                                    $x = explode("--", $actual);
	                                    array_splice($x,array_search($item["slug"],$x),1);
	                                    $valor = implode("--", $x);
	                                }else{
	                                    if($actual!="") $valor = $actual.$separador.$nueva;
	                                    else $valor = $nueva;
	                                }
	                                $filtros2['empresa'] = $valor;
	                                if($filtros2["empresa"]=="") $filtros2["empresa"]=null;
	                          }
	                          if($this->param==$conf_ubicacion){ //Ubicacion
	                                $actual = $this->filtro;
	                                $nueva = $item['slug'];
	                                $valor="";
	                                if($this->Existepalabra($nueva,$actual,$separador)){
	                                    $x = explode("--", $actual);
	                                    array_splice($x,array_search($item["slug"],$x),1);
	                                    $valor = implode("--", $x);
	                                }else{
	                                    if($actual!="") $valor = $actual.$separador.$nueva;
	                                    else $valor = $nueva;
	                                }
	                                $filtros2['ubicacion'] = $valor;
	                                if($filtros2["ubicacion"]=="") $filtros2["ubicacion"]=null;
	                          }
	
	                          $ruta = $this->url($filtros2,'buscar',false);
	                       ?>
	
	                                <a class="aFilterB" href="<?=$ruta?>"><?= $item['msg'] ?></a>
	                                <span class="count">(<?= $item['cant'] ?>)</span>
	                            </span>
	                        </label>
	                    <? endforeach; ?>
	             	
	            <? endforeach; ?>

    </div>
 
        <?if (count($this->datos['ocultos'])): ?>
        <fieldset class="asideSA alignR"><a href="#verTodos" class="winMegaT winIModal">Ver todos</a></fieldset>

        <!-- Bloque -->                
        
        
        
        <div class="moreWM bgWM1 hide">
          <div class="rel">
              <h3>&Aacute;reas profesionales</h3>
              <a class="closeH0WM icoCWM" href="#cerrar"><span class="hide">Cerrar</span> </a>
              
              <fieldset class="fieldsetRBA">
              <label class="labelRadioBA left" for="fieldNum11"><input name="fieldNum1" id="fieldNum11" type="radio" class="iptRadioBA" /> Por número de avisos</label>              
              <label class="labelRadioBA right" for="fieldNum12"><input name="fieldNum1" id="fieldNum12" type="radio" class="iptRadioBA" /> Por orden alfabético</label>
              </fieldset>
          </div>
            
            <div class="cntBlocks">
            
            <!-- 1 -->
            <div class="blockItemSB ">

                <fieldset class="fieldsBA left">
                    <label for="areascontabilidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areascontabilidad" name="areascontabilidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/contabilidad">Contabilidad</a>
                            <span class="count">(483)</span>
                        </span>
                    </label>
                    <label for="areashoteleria-turismo-restaurantes" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areashoteleria-turismo-restaurantes" name="areashoteleria-turismo-restaurantes" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/hoteleria-turismo-restaurantes">Hotelería / Turismo / Restaurantes</a>
                            <span class="count">(470)</span>
                        </span>
                    </label>
                    <label for="areasinvestigacion-y-desarrollo" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasinvestigacion-y-desarrollo" name="areasinvestigacion-y-desarrollo" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/investigacion-y-desarrollo">Investigación y Desarrollo</a>
                        <span class="count">(468)</span>
                        </span>
                    </label>
                    <label for="areaslegal" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areaslegal" name="areaslegal" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/legal">Legal</a>
                        <span class="count">(456)</span>
                        </span>
                    </label>
                    <label for="areasmarketing-publicidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasmarketing-publicidad" name="areasmarketing-publicidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                                                <a class="aFilterB" href="/buscar/areas/marketing-publicidad">Marketing / Publicidad</a>
                        <span class="count">(443)</span>
                        </span>
                    </label>
                          
                </fieldset>                    
                    
                <fieldset class="fieldsBA right">
                    <label for="areascontabilidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areascontabilidad" name="areascontabilidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/contabilidad">Contabilidad</a>
                            <span class="count">(420)</span>
                        </span>
                    </label>
                    <label for="areashoteleria-turismo-restaurantes" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areashoteleria-turismo-restaurantes" name="areashoteleria-turismo-restaurantes" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/hoteleria-turismo-restaurantes">Hotelería / Turismo / Restaurantes</a>
                            <span class="count">(390)</span>
                        </span>
                    </label>
                    <label for="areasinvestigacion-y-desarrollo" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasinvestigacion-y-desarrollo" name="areasinvestigacion-y-desarrollo" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/investigacion-y-desarrollo">Investigación y Desarrollo</a>
                        <span class="count">(370)</span>
                        </span>
                    </label>
                    <label for="areaslegal" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areaslegal" name="areaslegal" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/legal">Legal</a>
                        <span class="count">(360)</span>
                        </span>
                    </label>
                    <label for="areasmarketing-publicidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasmarketing-publicidad" name="areasmarketing-publicidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                                                <a class="aFilterB" href="/buscar/areas/marketing-publicidad">Marketing / Publicidad</a>
                        <span class="count">(312)</span>
                        </span>
                    </label>
                </fieldset>                                         
                
            </div>
            <!-- 2 -->
            <div class="blockItemSB hide">

                <fieldset class="fieldsBA left">
                    <label for="areascontabilidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areascontabilidad" name="areascontabilidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/contabilidad">Contabilidad</a>
                            <span class="count">(483)</span>
                        </span>
                    </label>
                    <label for="areashoteleria-turismo-restaurantes" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areashoteleria-turismo-restaurantes" name="areashoteleria-turismo-restaurantes" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/hoteleria-turismo-restaurantes">Hotelería / Turismo / Restaurantes</a>
                            <span class="count">(470)</span>
                        </span>
                    </label>
                    <label for="areasinvestigacion-y-desarrollo" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasinvestigacion-y-desarrollo" name="areasinvestigacion-y-desarrollo" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/investigacion-y-desarrollo">Investigación y Desarrollo</a>
                        <span class="count">(468)</span>
                        </span>
                    </label>
                    <label for="areaslegal" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areaslegal" name="areaslegal" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/legal">Legal</a>
                        <span class="count">(456)</span>
                        </span>
                    </label>
                    <label for="areasmarketing-publicidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasmarketing-publicidad" name="areasmarketing-publicidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                                                <a class="aFilterB" href="/buscar/areas/marketing-publicidad">Marketing / Publicidad</a>
                        <span class="count">(443)</span>
                        </span>
                    </label>
                          
                </fieldset>                    
                    
                <fieldset class="fieldsBA right">
                    <label for="areascontabilidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areascontabilidad" name="areascontabilidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/contabilidad">Contabilidad</a>
                            <span class="count">(420)</span>
                        </span>
                    </label>
                    <label for="areashoteleria-turismo-restaurantes" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areashoteleria-turismo-restaurantes" name="areashoteleria-turismo-restaurantes" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                            <a class="aFilterB" href="/buscar/areas/hoteleria-turismo-restaurantes">Hotelería / Turismo / Restaurantes</a>
                            <span class="count">(390)</span>
                        </span>
                    </label>
                    <label for="areasinvestigacion-y-desarrollo" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasinvestigacion-y-desarrollo" name="areasinvestigacion-y-desarrollo" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/investigacion-y-desarrollo">Investigación y Desarrollo</a>
                        <span class="count">(370)</span>
                        </span>
                    </label>
                    <label for="areaslegal" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areaslegal" name="areaslegal" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                        <a class="aFilterB" href="/buscar/areas/legal">Legal</a>
                        <span class="count">(360)</span>
                        </span>
                    </label>
                    <label for="areasmarketing-publicidad" class="labelFS">
                        <span class="iBlockLSA left">
                            <input id="areasmarketing-publicidad" name="areasmarketing-publicidad" type="checkbox" class="checkN noBdr">
                        </span> 
                        <span class="iBlockRSA right">
                         <a class="aFilterB" href="/buscar/areas/marketing-publicidad">Marketing / Publicidad</a>
                        <span class="count">(312)</span>
                        </span>
                    </label>
                </fieldset>                                         
                
            </div>
            
            
            
            </div>     
    
        </div>      
            
            

        <!-- Bloque -->    
            
            
        <?endif?>
    </form>
    
    <div class="bgIRSBSE hide">&nbsp;</div>
</div>