<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages" => $this->flashMessages))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel,
    "tieneBuscador" => $this->tieneBuscador, 'tieneBolsaCVs' => $this->tieneBolsaCVs,
    'Look_Feel' => $this->Look_Feel))
?>
<?php
$facet = $this->proceso['ubi'];
/* foreach ($facet as $value => $count) {
  echo $value . ' [' . $count . ']<br/>';
  } */
?>
<div id="wrapper" class="row">
    <span id="busquedaAnterior" class="hide" idnivelpuesto="<?= $this->idNivelPuesto ?>" idarea="<?= $this->idArea ?>">
    <?= $this->idPostulacion ?>
    </span>
    <?
    if ($this->puesto == ""):
        ?>
        <h2>Cuenta de empresa: <span class="txtEmpresaEPL"><? echo $this->escape($this->auth['empresa']['nombre_comercial']); ?></span> </h2>
    <? else: ?>
        <h2>Proceso: <span class="txtEmpresaEPL"><a href="<?= SITE_URL.'/empresa/mis-procesos/ver-proceso/id/'.$this->idPostulacion ?>"><? echo $this->escape($this->puesto); ?></a></span> </h2>
<? endif; ?>
    <div class="row">
        <div class="grids-2">
            <form id="frmSearch" action="" method="get">
                <div class="search-box">
                    <h4 class="black-title">Buscador Postulantes</h4>
                    <div class="frm-search">
                        <p>Busca por nombre, apellidos o perfil profesional.</p>
                        <div class="control-group">
                            <input type="text" value="<?php echo $this->text ?>" id="fWordRS" class="input-middle" name="text">
                        </div>
                        <div id="containerTags" class="container_tags">
                            <?php foreach ($this->aptitudes as $aptitud) { ?>
                                <div data-id="<?php echo $aptitud['id'] ?>" title="<?php echo $aptitud['mostrar'] ?>" class="search_item_tag"><input type="hidden" value="<?php echo $aptitud['id'] ?>" name="tags[]"><label><?php echo $aptitud['mostrar'] ?></label><span class="close_tag">X</span></div>
<?php } ?>
                        </div>
                        <div class="wrap-btn center">
                            <button type="button" class="btn btn-primary btn-xsmall" id="btnSearch">Buscar</button>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="col" value="<?php echo $this->col ?>">
                <input type="hidden" name="ord" value="<?php echo $this->ord ?>">
                <div class="box-details">
                    <?=
                    $this->partialLoop('_partials/_buscador_empresa_empleo_busco_solar.phtml',
                        $this->dataFiltros)
                    ?>
                </div>
                <input type="hidden" name="token" value="<?php echo $this->token ?>"/>
            </form>
        </div>
        <div class="grids-7 content-search">
            <!--Inicio Modal-->
            <div class="mask-search"></div>
            <div id="alertSearch" class="window fix search-modal">
                <a class="closeWM icon-close big" href="#Cerrar" title="Cerrar ventana">Cerrar</a>
                Has clic en buscar cuando hayas terminado de seleccionar.
                <div class="wrap-btn center">
                    <a href="javascript:;" class="btn btn-primary" title="Buscar">Buscar</a>
                    <a href="#Cerrar" title="Cerrar ventana" class="btn btn-default closeWM">Cancelar</a>
                </div>
            </div>
            <!--Fin Modal-->
            <div class="txt_right">
                <?php if ($this->tieneBolsaCVs) : ?>
                    <a id="btnEnviarBolsaBusqueda" name="btnEnviarBolsaBusqueda" class="icon_file mR20 enviarABolsa" href="" title="Enviar a Carpetas de CVs"></a>
                <?php endif; ?>
                <?php if ($this->activarInvitar): ?>
                    <a id="invitarBusqueda" class="icon_person_add" href="#winRegistrarInvitacionBuscador" title="Invitar" idproceso="<?= $this->idPostulacion ?>"></a>
<?php endif; ?>
            </div>


            <div id="mensajesBuscador" class="dvMensajesBolsaCVs dvMensajeAccion hide mT10" style="display: none"></div>
            <?php if (!$this->get) { ?>
                <div class="box-message" id="mensajeEntradaBuscador">Use el Buscador para encontrar a los candidatos idóneos según su requerimiento.<br>¡Mucha suerte!</div>
            <?php } ?>
            <div id="wordsFtr" class="tags-box <?=
                 (count($this->msg_facets) > 0 ? "" : "hide")
                 ?>">
                <a id="closeWFA" class="right" href="/empresa/buscador-empleo-busco?token=<?php echo $this->token ?>">cerrar</a>
                <?
                $uri  = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
                $purl = parse_url($uri);
                if (!isset($purl['host'])) {
                    $purl['host'] = SITE_URL;
                }
                foreach ($this->msg_facets as $k => $item):
                    ?>
                    <h2 class="tags">
                        <?= $this->escape($item) ?>
                        <?
                        parse_str($purl['query'], $vars);
                        unset($vars['col']);
                        unset($vars['ord']);
                        unset($vars['token']);
                        unset($vars[$k]);
                        $queryString = http_build_query($vars);
                        $ruta        = $purl['host'].$purl['path'].'?'.$queryString.'&token='.$this->token;
                        ?>
                        <a class="icon-close" href="<?= $ruta ?>">&nbsp;</a>
                    </h2>
<? endforeach; ?>
            </div>
            <div class="row mT20">
<?php if (count($this->msg_facets) > 0) { ?>
                    <button id="btnSearchSave" class="btn btn-primary" title="Se permiten maximo 20 busquedas">Guardar Busqueda</button>
                    <!--                <a class="icon_question fancy_modal" href="#divWrapHelp" title="Ayuda"></a>-->
                <?php
                }
                $hide = '';
                if (count($this->alertas) == 0) {
                    $hide = ' hide';
                }
                ?>
                <div class="flt_right pos_relative<?= $hide ?>">
                    <div id="cboSearchSaved" class="search_saved_cbo"><span>Búsquedas Guardadas</span><span class="icon-tiny up"></span></div>
                    <ul id="searchList" class="search_saved_list">
                        <?php
                        foreach ($this->alertas as $alerta) {
                            $uri         = $alerta['url'];
                            $purl        = parse_url($uri);
                            parse_str($purl['query'], $vars);
                            unset($vars['token']);
                            $queryString = http_build_query($vars);
                            $ruta        = $purl['host'].$purl['path'].'?'.$queryString.'&token='.$this->token;
                            ?>
                            <li><a href="http://<?php echo $ruta ?>" title="Ver búsqueda"><?php echo $alerta['nombre'] ?></a><a href="javascript:;" data-id="<?php echo $alerta['id'] ?>" class="last" title="Eliminar búsqueda">X</a></li>
<?php } ?>
                    </ul>
                </div>

            </div>
            <div id="contenido_ajax" class="mT20">
                <div id="paginEPM" class="pagination bBGray all">
                    <p class="pagLegend grid5 mB0 theta alingL left"><?= $this->mostrando ?></p>
                <?= $this->partial('buscador-empleo-busco/_pag.phtml',
                    array("result" => $this->proceso, "token" => $this->token)) ?>
                </div>
                <?php
                if ($this->get) {
                    $uri         = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
                    $purl        = parse_url($uri);
                    parse_str($purl['query'], $vars);
                    unset($vars['col']);
                    unset($vars['ord']);
                    unset($vars['token']);
                    $queryString = http_build_query($vars);
                    $url         = (isset($purl['host']) ? $purl['host'] : '').$purl['path'].'?'.$queryString.'&token='.$this->token;
                    ?>
                    <table cadenabusqueda="<?= $this->cadenabusqueda ?>"  ord="<?= $this->ord ?>" col="<?= $this->col ?>" page="<?= $this->pagina ?>" class="dataGrid dataGridEnviarBolsa" id="dataProcesoBusqueda" summary="Proceso de Postulacion">
                        <thead>
                            <tr>
    <?php $base        = array('module' => 'empresa', 'controller' => 'mis-procesos',
        'action' => 'ver-proceso'); ?>
                                <th class="data0 titleGrid linkTitleG">
                                    <?php if ($this->option) { ?>
                                        <input type="checkbox"  name="selectAll" class="noBdr" />
    <?php } ?>
                                </th>
                                <th class="data1 titleGrid linkTitleG">
                                    <? $col = 'foto' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row">Foto</a>
                                </th>
                                <th class="data2 titleGrid linkTitleG">
                                    <? $col = 'nomape_ord' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row">Nombres</a>
                                </th>
                                <th class="data3 titleGrid linkTitleG">
                                    <? $col = 'sexo' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row">Sexo</a>
                                </th>
                                <th class="data4 titleGrid linkTitleG">
                                    <? $col = 'edad' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row">Edad</a>
                                </th>
                                <th class="data5 titleGrid linkTitleG">
                                    <? $col = 'mayor_nivel_estudio' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row" >Nivel estudio</a>
                                </th>
                                <th class="data6 titleGrid linkTitleG">
                                    <? $col = 'carrera_ord' ?>
    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row" >Carrera</a>
                                </th>
                                <th class="data6 titleGrid linkTitleG">
                            <? $col = 'ubigeo' ?>
                            <? $ord = ($this->col == $col && $this->ord
                                == 'ASC') ? 'DESC' : 'ASC' ?>
                                    <a href="<?php echo $url."&col=$col&ord=$ord" ?>" ord="<?= $ord ?>" col="<?= $col ?>" class="relArrow titleRow <?= strtolower($ord) ?>Row" >Lugar de<br/>Residencia</a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                                            <? foreach ($this->proceso['rows'] as $item): ?>
                                <tr>
                                    <td class="data0">
                                        <input type="checkbox" name="select" class="noBdr" id="<?= $item["idpostulante"] ?>" relpos="<?= $item["idpostulante"] ?>" />
                                    </td>
                                    <td class="data1">
                                        <span class="dateData cntImgFix">
                                            <a href="/empresa/buscador-empleo-busco/perfil-publico-emp-solr?slug=<?php echo $item["slug"] ?>" >
                                                <?php
                                                if (isset($item['foto'])) {
                                                    $logo = ($item['foto'] == ''
                                                        || $item['foto'] == NULL)
                                                            ?
                                                        $this->S('/images/photoDefault.jpg')
                                                            : ELEMENTS_URL_IMG.$item['foto'];
                                                } else {
                                                    $logo = $this->S('/images/photoDefault.jpg');
                                                }


                                                //$lado = $this->ImgLadoMayor($logo);
                                                $lado = 'height';
                                                ?>
                                                <img <?= $lado ?>="60" src="<?= $logo ?>" />
                                            </a>
                                        </span>
                                    </td>
                                    <td class="data2">

                                        <div class="nameFilPerfP bold"><a href="/empresa/buscador-empleo-busco/perfil-publico-emp-solr?slug=<?php echo $item["slug"] ?>" ><?php echo $item["nomape"] ?></a></div>
                                            <?php if (!empty($item["destacado"])) { ?>
                                            <span class="icon-medal"></span>
                                            <?php } ?>
                                        <div class="tlfFilPerfP sptIcoEmp" title="Telefono">&nbsp;<?php echo isset($item["telefono"])
                                                    ? $item["telefono"] : ''; ?></div>

                                        <div class="all">
                                        <? //if($item["slug"]!="" && $item["slug"]!=null):  ?>
                                            <a class="verPerfilFilPerfP sptIcoEmp left" rel="<?= $item["idpostulante"] ?>" href="/empresa/buscador-empleo-busco/perfil-publico-emp-solr?slug=<?php echo $item["slug"] ?>" title="Ver perfil" ></a>
                                            <? //endif;  ?>
                                            <? if (isset($item["path_cv"])
                                                && $item["path_cv"] != "" && $item["path_cv"]
                                                != null) : ?>
                                                <span class="pipeFilPerfP left">|</span>
                                                <a class="downFilPerfP sptIcoEmp left" href="<?= ELEMENTS_URL_CVS.$item["path_cv"] ?>" title="Ver CV"></a>
                                        <? endif; ?>
                                        </div>

                                    </td>
                                    <td class="data3">
                                    <?php if (isset($item["sexo"])) : ?>
                                            <div class="sptIcoEmp <?= $item["sexo"] == "M" ? "imgHombre"
                                    : "imgMujer"; ?>" title=" <?php echo $item["sexo"]
                            == "M" ? "Hombre" : "Mujer"; ?>">
                                        <?= $item["sexo"] ?>
                                            </div>
                                    <?php endif; ?>
                                    </td>
                                    <td class="data4">
        <?php if (isset($item["edad"])) : ?>
                                            <span class="dateData"><?= $item["edad"] ?></span>
        <?php endif; ?>
                                    </td>
        <?php
        if (isset($item["estudios"])) $mne = $item["estudios"];
        else $mne = '';
        if (isset($item["carrera"])) $mc  = $item["carrera"];
        else $mc  = '';
        ?>
                                    <td class="data5">
                                        <span class="dateData"><? if (trim($mne) == "") echo "Ninguno";
        else echo $mne; ?></span>
                                    </td>
                                    <td class="data6">
                                        <span class="dateData"><? if (trim($mc) == "") echo "Ninguna";
        else echo $mc; ?></span>
                                    </td>
                                    <td class="data6">
                                        <span class="dateData"><?= (isset($item['ubigeo'])
                            ? $item['ubigeo'] : '') ?></span>
                                    </td>
                                </tr>
    <? endforeach; ?>
                        </tbody>
                    </table>
<?php } ?>
                <div class="pagination all">
<? //= $this->paginationControl($this->proceso, 'Sliding', 'buscador-EMPLEOBUSCO-solr/_pag.phtml',array("estasArriba"=>0))  ?>
<?= $this->partial('buscador-empleo-busco/_pag.phtml',
    array("result" => $this->proceso, "token" => $this->token)) ?>
                </div>
            </div>
        </div>
    </div>
</div>
