<h3 class="titleAPLR">Invitar a un Proceso</h3>

<div id="cntAvisoInv">

    <div class="block">
        <h6 class="left bold titleTopInv">Nombre del proceso</h6>
        <?=
        $this->frmInvitar->aviso->setAttribs(array(
            'class' => 'left selectN selectInv', 'tabindex' => '1'))->renderViewHelper();
        ?>
        
        <?=$this->frmInvitar->tok->renderViewHelper();?>

    </div>
    <div id="mensajesVerProceso" class="hide r5" style="display: none"></div>
    <div class="loading center hide" id="cargandoInvitaBusqueda"></div>

    <div id="avisoFileCnt" class="hide">

        <div id="cntModalAEmp">

        </div>		
    </div>
    <br>

    <div class="wrap-btn center">
        <a class="invBtnProc btn btn-primary" href="#">Invitar</a>
    </div>

</div>
