<div id="cntModalAEmp" class="modalAvisoE modalAvisoCnt">
        <h6 class="titPosts">Funciones y responsabilidades</h6>
        <div class="txtPosts mB20">
                <?=$this->aviso["funciones"]?>
                <br>
                <?=$this->aviso["responsabilidades"];?>
        </div>
        <?php if($this->aviso['mostrar_salario'] == 1 && !($this->aviso['salario_min'] == null && $this->aviso['salario_max'] == null)) : ?>
        <h6 class="titPosts">Condiciones salariales</h6>
        <div class="txtPosts mB20">
            <ul class="listPosts">
            <?php if ($this->aviso['salario_min'] == 0) : ?>
                <li class="itemC">Sueldo: Menor a <?php echo $this->moneda?> <?=$this->aviso['salario_max']; ?></li>
            <?php elseif ($this->aviso['salario_max'] == '') : ?>
                <li class="itemC">Sueldo: Mayor a <?php echo $this->moneda?> <?=$this->aviso['salario_min']; ?></li>
            <?php elseif ($this->aviso['salario_min'] != $this->aviso['salario_max']) : ?>
                <li class="itemC">Sueldo: Entre <?php echo $this->moneda?> <?=$this->aviso['salario_min']; ?> y <?php echo $this->moneda?> <?=$this->aviso['salario_max']; ?></li>
            <?php else: ?>
                <li class="itemC">Sueldo: <?php echo $this->moneda?> <?=$this->aviso['salario_min']; ?></li>
            <?php endif; ?>
            </ul>
        </div>
        <?php endif; ?>        
</div>