<div id="boxes">
<!-- Box Mensajes -->
    <div id="winAlert" class="window fix win-small" rel="">
        <a href="#Cerrar" class="closeWM icon-close"><span class="hide">Cerrar</span></a>
        <div class="msjReemplazo">
            <p id="titleQ">Está seguro que desea eliminar?</p>
        </div>
        <div id="btnQ" class="">
            <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
            <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
        </div>
    </div>

    <div id="winAlertEliminarAdm" class="window" rel="">
        <div id="iwinAlertEliminarAdm" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertEliminarAdm" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea eliminar este Administrador?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="winAlertBloquearPost" class="window" rel="">
        <div id="iwinAlertBloquearPost" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearPost" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea bloquear al postulante?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
   <!-- Bloquear Testimonio -->
   <div id="winAlertBloquearTestimonio" class="window" rel="">
        <div id="iwinAlertBloquearTestimonio" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearTestimonio" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea desactivar el Testimonio?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                        <!-- a class="yesCM btnPink left" href="#actualizar">Aceptar</a -->
                    </div>
                </div>
            </div>
        </div>
    </div>
   <!-- FIN de Bloquear testimonio -->
   <!-- Seccion para Empresas Portada -->
   <div id="winAlertBloquearEportada" class="window" rel="">
        <div id="inwinAlertBloquearEportada" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearEPortada" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <div id="content-winEmpresaTCN" class="all">
                    </div>

                </div>
            </div>
        </div>
    </div>

   <!-- FIN de Seccion para Empresas Portada -->
    <div id="winAlertBloquearAviso" class="window" rel="">
        <div id="iwinAlertBloquearAviso" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearAviso" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea bloquear el aviso?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
   <?php /*
   <div id="winModalShowHomeAviso" class="window" rel="">
        <div id="iwinModalShowHomeAviso" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinModalShowHomeAviso" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Desea mostrar en la página principal el aviso?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="divWrapHomeAviso" class="hide">
        <p id="titleQ">¿Desea mostrar en la página principal el aviso?</p>
        <div class="txt_center">
            <button id="btnConfirmHomeAviso">Aceptar</button>
            <button id="btnCancelHomeAviso">Cancelar</button>
        </div>
    </div>*/?>

    <div id="winAlertBloquearEmp" class="window" rel="">
        <div id="iwinAlertBloquearEmp" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearEmp" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea bloquear la empresa?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="winAlertBloquearLookAndFeel" class="window" rel="">
        <div id="iwinAlertBloquearLookAndFeel" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearLookAndFeel" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Desea desactivar la vista look&feel?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="winAlertBloquearUsuAdmin" class="window">
        <div id="iwinAlertBloquearUsuAdmin" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearUsuAdmin" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea desactivar al administrador?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="winAlertBloquearUsuApi" class="window">
        <div id="iwinAlertBloquearApiAdmin" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertBloquearUsuAdmin" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea desactivar usuario?</p>
                    <br>
                    <div id="btnQElimAdm" class="btnQAllR ">
                        <a class="yesCM btnPink left" href="#aceptar">Aceptar</a>
                        <a class="cancelCM btnPink right closeWM" href="#cancelar">Cancelar</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<!-- Fin -->
    <div id="escapeFormPaso" class="window">
        <div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <p class="alertEsc">
                        <span class="bold f18 mB5 titTxtAE">Si no has guardado los cambios, al cambiar de puesto perderas los datos ingresados.</span>
                        <span class="relTxtAE cGray">Por lo que tendrá que volver a ingresar los datos.</span>
                    </p>
                    <div class="wrap-btn center">
                        <a id="btnNPasosNext" class="btn btn-primary" href="#">Ir al paso</a>
                        <a href="#" id="btnNPasos" class="closeWM btn btn-primary">Continuar registro de datos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
	<div id="winEditPostulante" class="window">
	    <div  class="innerWin">
	    <a href="#Cerrar" class="closeWM icoCWM">
	    <span class="hide">Cerrar</span></a>
	    <div  class="iWindow r5">
	        <div class="bLB3 r5 inWindow">
            <div id="content-winEditPostulante">
	      		<!--verProceso-->
            </div>
	   	    </div>
	  	</div>
		</div>
	</div>

        <!-- Enviar mensaje -->
        <div id="winAnadirMensaje" class="window">
            <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
                <div  class="iWindow r5">
                    <div class="bLB3 r5 inWindow">
                        <div id="content-winAnadirMensaje">
                            AÑADIR MENSAJE
                        </div>
                    </div>
                </div>
            </div>
	</div>

        <!-- Enviar mensaje -->
        <div id="editAdmL" class="window">
            <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
                <div class="iWindow r5">
                    <div class="bLB3 r5 inWindow">
                        <div id="content-winAnadirAdm" class="all">
                        </div>
                    </div>
                </div>
            </div>
	</div>


	<!-- Administrador  -->
	<div id="cntNewAdminEM" class="wwScroll">
		<div class="wwRelativo">
			<div class="wwModal">
		    <div id="newAdminEM" class="windowAll">
		        <div id="iNewAdmEM" class="innerWin">
		        	<a href="#Cerrar" class="closeWMM icoCWM"><span class="hide">Cerrar</span></a>
	            <div id="inNewAdmEM" class="iWindow r5">
	                <div id="iNAdmEM" class="bLB3 r5 inWindow">
                    <div id="loadHTMLAdm" class="all">
                    	<!-- Data ajax -->

                    </div>
	                </div>
	            </div>
		        </div>
		    </div>
			</div>
		</div>
	</div>
	<!-- Fin  -->

	<!-- Inicio Recupera tu Clave -->
		<div id="registerP" class="window">
	    <div id="iRegisterP" class="innerWin"> <a class="closeWM closeRegiFast icoCWM" href="#Cerrar" title="Cerrar ventana"><span class="hide">Cerrar</span></a>
	        <div id="inRegisterP" class="iWindow r5">
	            <div id="iRP" class="bLB3 r5">
	                <div id="cntForgotPReg" class="rel hide forgotFlag">
	                    <div class="all alignR">
	                        <a href="#Login" id="backLogWMReg">&laquo; Volver a Login</a>
	                    </div>
	                    <h2 class="titleForgetP mB10">Recupera tu clave</h2>
	                    <p class="c3">Ingresa tu  dirección de e-mail y te enviaremos tu nueva contraseña de verificación. Una vez que hayas recibido la contraseña, podrá elegir una nueva para su cuenta.</p>
	                    <form id="fForgotPassReg">
	                        <fieldset class="mB10">
	                            <label for="textForgotPReg" class="labelN mB5">Dirección de email</label>
	                            <input id="textForgotPReg" class="inputN" type="text" value="" />
	                            <div id="responseFPReg" class="f11 hide"></div>
	                        </fieldset>
	                        <fieldset class="">
	                            <input type="submit" id="sendForgotPReg" class="active btnPink" value="" />
	                        </fieldset>
	                    </form>
	                  	<div id="errorCmpReg" class="hide"></div>
                    	<div id="loadingCFPReg" class="all hide"></div>
	                </div>

	            </div>
	        </div>
	    </div>
	</div>
	<!-- Fin Recupera tu Clave -->

	<div id="winDividirAviso" class="window">
		<div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
	    <div  class="iWindow r5">
	      <div class="bLB3 r5 inWindow">
          <div id="content-winDividirAviso">
                    AÑADIR MENSAJE
        	</div>
      	</div>
	    </div>
		</div>
	</div>

    <div id="escapeFormAP" class="window">
        <div id="iEscpForm" class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inEscpForm" class="iWindow r5">
                <div id="iEscpF" class="bLB3 r5 inWindow">
                    <p class="alertEsc">
                        <span class="bold f18 mB5 titTxtAE">Al regresar al paso anterior se perderá todo lo ingresado.</span>
                        <span class="relTxtAE cGray">Por lo que tendrá que volver a ingresar los datos del aviso.</span>
                    </p>
                    <div class="wrap-btn center">
                        <a id="btnCEscp" class="btn btn-primary" href="/admin/publicar-aviso-preferencial/paso1/producto/<?php echo $this->layout()->productoId ?>/<?php echo $this->layout()->urlTarifa ?>">Confirmar salida</a>
                        <a href="#Continuar" id="btnNSh" class="closeWM btn btn-primary">Continuar registro de datos</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="ejmAvisoPA1" class="window">
        <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div  class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                    <div id="ejmSizeAdv">
                        <h3 class="titleAPLR">Aviso Preferencial <span id="planSizeAdv">&nbsp;</span></h3>
                          <div class="alignC"><img src="<? echo $this->S('/images/empresa/logoModalGP.png'); ?>" alt="Logo" /></div>
                        <div class="alignC loading" id="imgAvisoPA1"><img src="<? echo $this->S('/images/empresa/preferenciales/vistaprevia/previa1x1.jpg'); ?>" alt="Ejemplo de aviso" /></div>
                        <div class="divArrowAs">Aviso <span id="tamanioSizeAdv">&nbsp;</span> cm</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

	  <div id="ejmsAviso" class="window">
	    <div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
	      <div class="iWindow r5">
	      	<div class="bLB3 r5 inWindow">
	      		<div class="cntImgAvisoEPA"></div>
	   			</div>
	   		</div>
	    </div>
	  </div>

        <!-- Img Extracargos -->
    <div id="ejemploext" class="window">
        <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div  class="iWindow r5">
                <div class="bLB3 r5 inWindow">
                  <div id="cntExtracargos">
                  </div>
                </div>
            </div>
        </div>
    </div>


         <div id="winVerProceso" class="window">
	  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
	    <div  class="iWindow r5">
	      <div class="bLB3 r5 inWindow">
          <div id="content-winVerProceso">
	      		<!--verProceso-->
          </div>
	   		</div>
	  	</div>
		</div>
	</div>
	<div id="mask"> </div>
     <?php if (!isset($this->layout()->noMostrarWinAlertPrivilegioAdm)) : ?>
    <div id="winAlertPrivilegioAdm" class="window" rel="">
        <div id="iwinAlertPrivilegioAdm" class="innerWin">
            <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
            <div id="inwinAlertPrivilegioAdm" class="iWindow r5">
                <div id="iWinA" class="bLB3 r5 inWindow">
                    <p id="titleQ">¿Está seguro que desea conceder privilegios a este Administrador?</p>
                    <!-- <p id="titleQ">Are you sure you want to grant privileges to the Administrator?</p> -->
                    <p> Usted perderá todo los privilegios de administrador principal.</p>
                   <!-- <p> You will lose all the administrator privileges. -->
                    <br>
                    <div id="btnQElimAdm" class="wrap-btn center">
                        <form action="" method="post" name="frmprivilegioadm" id="frmprivilegioadm">
                            <?php if (!empty($this->layout()->hashForm->hash)) {
                            echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
                            <a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
                            <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>
</div>
