<?php
$this->isAuth = Zend_Auth::getInstance()->hasIdentity();
$this->auth = Zend_Auth::getInstance()->getStorage()->read();
?>
<div id="boxes">
	 <?php if (isset($this->layout()->compartirPorMail)) : ?>
		  <?php
		  $compartirAviso
				= $this->layout()->compartirPorMail;
		  ?>
		  <div id="shareMail" class="window fix">
				<a class="closeWM resetBtnClose icon-close big" href="#Cerrar" title="Cerrar ventana">Cerrar</a>
				<h3 class="title">Comparte por e-mail </h3>  <!-- Share via e-mail -->
				<form id="formShareCA" class="formShareCA" action="<?= SITE_URL . $compartirAviso->getAction(); ?>" method="post">
					 <?= $compartirAviso->hdnOculto->renderViewHelper() ?>
					 <div class="row">
						  <div class="blockWM left">
								<div class="block mB10">
									 <label for="fCAName" class="mB5 c3 labelOpt">Tu nombre</label>
									 <?php
									 if ($this->layout()->auth == null):
										  ?>
										  <?=
										  $compartirAviso->nombreEmisor->setAttribs(array(
												'id' => 'fCAName', 'class' => 'inputSm inputReset',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php else: ?>
										  <?=
										  $compartirAviso->nombreEmisor->setAttribs(array(
												'id' => 'fCAName', 'class' => 'inputSm ready',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php endif; ?>
									 <span class="response cGray"> </span>
								</div>
								<div class="block mB10">
									 <label for="fCAMail" class="mB5 c3 labelOpt">Tu e-mail</label>
									 <?php
									 if ($this->layout()->auth == null):
										  ?>
										  <?=
										  $compartirAviso->correoEmisor->setAttribs(array(
												'id' => 'fCAMail', 'class' => 'inputSm inputReset',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php else: ?>
										  <?=
										  $compartirAviso->correoEmisor->setAttribs(array(
												'id' => 'fCAMail', 'class' => 'inputSm ready',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php endif; ?>
									 <span class="response cGray"> </span>
								</div>
						  </div>
						  <div class="blockWM right">
								<div class="block mB10">
									 <label for="fCANameDes" class="mB5 c3 labelOpt">Nombre de destinatario</label>
									 <?=
									 $compartirAviso->nombreReceptor->setAttribs(array(
										  'id' => 'fCANameDes', 'class' => 'inputSm inputReset',
										  'maxlength' => '100'))->renderViewHelper()
									 ?>
									 <span class="response cGray"> </span>
								</div>
								<div class="block mB10">
									 <label for="fCAMailDes" class="mB5 c3 labelOpt">E-mail del destinatario</label>
									 <?=
									 $compartirAviso->correoReceptor->setAttribs(array(
										  'id' => 'fCAMailDes', 'class' => 'inputSm inputReset',
										  'maxlength' => '100'))->renderViewHelper()
									 ?>
									 <span class="response cGray"> </span>
								</div>
						  </div>
						  <div class="block mB10">
								<label for="fCACustomMsg" class="mB5 c3 labelOpt">Personaliza tu e-mail con un mensaje:</label>
								<?=
								$compartirAviso->mensajeCompartir->setAttribs(array(
									 'id' => 'fCACustomMsg', 'class' => 'areaN areaWM inputReset'))->renderViewHelper()
								?>
								<!--textarea id="fCACustomMsg" class="areaN areaWM"></textarea-->
								<span class="response cGray"> </span>
						  </div>
					 </div>
					 <div class="wrap-btn right">
						  <div id="cntNCaracterP" class="left">Te quedan <span class="bold" id="nCaracterP">300</span> caracteres.</div>
						  <a id="btnCancelCA" class="btnCEscp resetBtn closeWM btn btn-default" href="#Cancelar">Cancelar</a>
						  <?=
						  $compartirAviso->Submit->setAttribs(array(
								'id' => 'fSendCA', 'class' => 'btn btn-primary', 'value' => 'Enviar',
								'rel' => $compartirAviso->getAction()))->renderViewHelper()
						  ?>
					 </div>
					 <?= $compartirAviso->fCAtok->renderViewHelper(); ?>
				</form>
				<div id="loadMFF" class="block"><div class="good msjLoadMFF"></div></div>
		  </div>

		  <div id="divWrapSendEmail" class="hide">
				<h3 class="title-modal">Comparte por e-mail </h3>  <!-- Share via e-mail -->
				<form id="frmSendEmail" action="<?= SITE_URL . $compartirAviso->getAction(); ?>" method="post">
					 <?= $compartirAviso->hdnOculto->renderViewHelper() ?>

					 <div class="cgroup-inline">
						  <div class="control-group">
								<div class="control-label">Tu nombre</div>
								<div class="controls">
									 <?php
									 if ($this->layout()->auth == null):
										  ?>
										  <?=
										  $compartirAviso->nombreEmisor->setAttribs(array(
												'id' => 'fCAName', 'class' => 'inputSm inputReset',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php else: ?>
										  <?=
										  $compartirAviso->nombreEmisor->setAttribs(array(
												'id' => 'fCAName', 'class' => 'inputSm ready',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php endif; ?>
									 <div class="hide response bad">Campo requerido</div>
								</div>
						  </div>
						  <div class="control-group">
								<div class="control-label">Nombre de destinatario</div>
								<div class="controls">
									 <?=
									 $compartirAviso->nombreReceptor->setAttribs(array(
										  'id' => 'fCANameDes', 'class' => 'inputSm inputReset',
										  'maxlength' => '100'))->renderViewHelper()
									 ?>
									 <div class="hide response bad">Campo requerido</div>
								</div>
						  </div>
					 </div>
					 <div class="cgroup-inline">
						  <div class="control-group">
								<div class="control-label">Tu e-mail</div>
								<div class="controls">
									 <?php
									 if ($this->layout()->auth == null):
										  ?>
										  <?=
										  $compartirAviso->correoEmisor->setAttribs(array(
												'id' => 'fCAMail', 'class' => 'inputSm inputReset',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php else: ?>
										  <?=
										  $compartirAviso->correoEmisor->setAttribs(array(
												'id' => 'fCAMail', 'class' => 'inputSm ready',
												'maxlength' => '100'))->renderViewHelper()
										  ?>
									 <?php endif; ?>
									 <div class="hide response bad">Campo requerido</div>
								</div>
						  </div>
						  <div class="control-group">
								<div class="control-label">E-mail del destinatario</div>
								<div class="controls">
									 <?=
									 $compartirAviso->correoReceptor->setAttribs(array(
										  'id' => 'fCAMailDes', 'class' => 'inputSm inputReset',
										  'maxlength' => '100'))->renderViewHelper()
									 ?>
									 <div class="hide response bad">Campo requerido</div>
								</div>
						  </div>
					 </div>
					 <div class="cgroup-inline">
						  <div class="control-label">Personaliza tu e-mail con un mensaje:</div>
						  <?=
						  $compartirAviso->mensajeCompartir->setAttribs(array(
								'rows' => '8', 'cols' => '78', 'class' => '', 'id' => 'mensajeCompartir'))->renderViewHelper()
						  ?>
						  <div class="count-letter">Te quedan <span id="count-char">300</span> de 300 caracteres</div>
					 </div>
					 <div class="wrap-btn right">
						  <button type="button" id="btnCancelCA" class="btn btn-default">Cancelar</button>
						  <button type="button" id="btnSendEmail" class="btn btn-primary">Enviar</button>
					 </div>
					 <?= $compartirAviso->fCAtok->renderViewHelper(); ?>
				</form>
				<div class="response all"></div>
				<div id="loadMFF" class="block"><div class="good msjLoadMFF"></div></div>
		  </div>
	 <?php endif; ?>
	 <div id="escapeForm" class="window">
		  <div id="iEscpForm" class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inEscpForm" class="iWindow r5">
					 <div id="iEscpF" class="bLB3 r5 inWindow">
						  <p class="alertEsc">
								<span class="bold f18 mB5 titTxtAE">El registro de sus datos no se ha completado</span>
								<!-- <span class="bold f18 mB5 titTxtAE">The registration of your data has not been completed</span> -->
								<span class="relTxtAE cGray">por lo que no podrá participar en ningún proceso de postulación en AquiEmpleos</span>
								<!-- <span class="relTxtAE cGray">so you will not be able to participate in any public postulaciï¿½ process ï¿½ n in JobsDB</span> -->
						  </p>
						  <div class="wrap-btn center">
								<a id="btnCEscp" class="btnCEscp btn btn-default" href="<?=
								$this->url(array(
									 'controller' => $this->controlador, 'module' => $this->modulo,
									 'action' => 'index'), false, true)
								?>">Confirmar salida</a>
								<a href="#Continuar" id="btnNSh" class="closeWM btn btn-primary">Continuar registro de datos</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>

	 <?php if (!isset($this->layout()->noMostrarEscapeFormAP)) : ?>
	 <div id="escapeFormAP" class="window">
		  <div id="iEscpForm" class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inEscpForm" class="iWindow r5">
					 <div id="iEscpF" class="bLB3 r5 inWindow">
						  <p class="alertEsc">
								<span class="bold f18 mB5 titTxtAE">Al regresar al paso anterior se perderá todo lo ingresado.</span>
								<!--  <span class="bold f18 mB5 titTxtAE">Upon returning to the previous step will be lost everything entered.</span> -->
								<span class="relTxtAE cGray">Por lo que tendrá que volver a ingresar los datos del aviso.</span>
						  <!--  <span class="relTxtAE cGray">So you will have to re-enter the data of the notice.</span> -->
						  </p>
						  <div class="wrap-btn center">
								<?php
								if (isset($this->layout()->extiende)) {
									 $url = "/extiende/" . $this->layout()->extiende;
								} elseif (isset($this->layout()->republica)) {
									 $url = "/republica/" . $this->layout()->republica;
								} else {
									 $url = '';
								}
								?>
								<a id="btnCEscp" class="btnCEscp btn btn-default" href="/empresa/publica-aviso-preferencial/paso1/producto/<?php echo $this->layout()->productoId ?>/<?php echo $this->layout()->urlTarifa ?><?php echo $url ?>">Confirmar salida</a>
								<a href="#Continuar" id="btnNSh" class="closeWM btn btn-primary">Continuar registro de datos</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarescapeFormPaso)) : ?>
	 <div id="escapeFormPaso" class="window">
		  <div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <p class="alertEsc">
								<span class="bold f18 mB5 titTxtAE">Si no has guardado los cambios, al cambiar de puesto perderas los datos ingresados.</span>
								<!--  <span class="bold f18 mB5 titTxtAE">If you have not saved your changes, the shift will lose the data entered.</span> -->
								<span class="relTxtAE cGray">Por lo que tendrá que volver a ingresar los datos.</span>
								<!-- <span class="relTxtAE cGray">So you will have to re-enter data.</span> -->
						  </p>
						  <div class="wrap-btn center btnsPasos">
								<a id="btnNPasosNext" class="btnCEscp btn btn-default" href="#">Confirmar salida</a> <!-- Keep up -->
								<a href="#" id="btnNPasos" class="closeWM btn btn-primary">Guardar Puesto</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarnextFormAP)) : ?>
	 <div id="nextFormAP" class="window">
		  <div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <p class="alertEsc">
								<span class="bold f18 mB5 titTxtAE">Guarde los datos del puesto <span id="numPuestoPP"></span>.</span>
								<!--  <span class="bold f18 mB5 titTxtAE">Keep post data <span id="numPuestoPP"></span>.</span> -->
								<span class="relTxtAE cGray">Sino guarda, al continuar perdera los datos ingresados del puesto.</span>
						  <!-- <span class="relTxtAE cGray">But saved by continuing to lose the data entered since.</span> -->
						  </p>
						  <div class="wrap-btn center">
								<div id="btnSavePAP" class="btn btn-default  btnSavePAP">Guardar Puesto</div>
								<a id="btnNextPAP" href="#" class="btn btn-primary  btnNextPAP">Continuar ></a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>
	 <?php /*
		<div id="winPromotion" class="window">
		<div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
		<div class="iWindow r5">
		<div class="bLB3 r5 inWindow">
		<!--<iframe id="player_yt" width="100%" height="540" src="//www.youtube.com/embed/lmv1dTnhLH4?list=PLOU2XLYxmsIJOOTFfYzhR2d-rcSbBbEE_" frameborder="0" allowfullscreen></iframe>-->

		<iframe id="player_yt" width="100%" height="540" src="" frameborder="0" allowfullscreen></iframe>
		</div>
		</div>
		</div>
		</div>
	  */ ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlert)) : ?>
	 <div id="winAlert" class="window fix win-small" rel="">
		  <a class="closeWM icon-close big" href="#Cerrar" title="Cerrar ventana">Cerrar</a>
		  <div class="msjReemplazo">
				<p id="titleQ">Está seguro que desea eliminar?</p>
				<!--  <p id="titleQ">Is safe to delete?</p> -->
		  </div>
		  <div id="btnQ" class="wrap-btn center">
				<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
				<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertBCV)) : ?>
	 <div id="winAlertBCV" class="window" rel="">
		  <div class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div class="msjReemplazo">
								<p id="titleQBCV">¿Está seguro que desea eliminar la nota?</p>
								<!--   <p id="titleQBCV">Are you sure you want to delete the note?</p> -->
						  </div>
						  <div id="btnQBCV" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarCntDataMsjs)) : ?>
	 <div id="cntDataMsjs" class="wwScroll">
		  <div class="wwRelativo">
				<div class="wwModal">
					 <div id="dataMsjs" class="windowAll">
						  <div id="iDataMsjs" class="innerWin"> <a href="#Cerrar" class="closeWMM icoCWM"><span class="hide">Cerrar</span></a>
								<div id="inDataM" class="iWindow r5">
									 <div id="iDataM" class="bLB3 r5 inWindow">
										  <div id="loadDataHTML" class="all">
												<!-- Data ajax -->
										  </div>
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarCntDataNotifs)) : ?>
	 <div id="cntDataNotifs" class="wwScroll">
		  <div class="wwRelativo">
				<div class="wwModal">
					 <div id="dataNotifs" class="windowAll">
						  <div id="idataNotifs" class="innerWin"> <a href="#Cerrar" class="closeWMM icoCWM"><span class="hide">Cerrar</span></a>
								<div id="inDataNot" class="iWindow r5">
									 <div id="iDataNot" class="bLB3 r5 inWindow">
										  <div id="loadDHTMLNoti" class="all">
												<!-- Data ajax -->
										  </div>
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAtencionN)) : ?>
	 <div id="winAtencionN" class="window">
		  <div class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="cntAteMsjNotif" class="r2">
								<h6 class="icoSpt titleModalW">¡Ten Cuidado!</h6>
								<blockquote class="blockInfoM">"Comunicamos a todas las personas que buscan empleo que existen empresas que constantemente publican multitud de ofertas falsas con el objeto de estafar"</blockquote>
								<!--  <blockquote class="blockInfoM">"Comunicamos a todas las personas que buscan empleo que existen empresas que constantemente publican multitud de ofertas falsas con el objeto de estafar"</blockquote> -->
								<div id="cntTxtNF" class="all f12">
									 <div class="left txtNF">
										  <p>Registran empresas con nombres y emails falsos que cambian constantemente para poder pasar desapercibidos y a veces nos es difí­cil detectarlos. Estos grupos de estafadores profesionales intentan atraer el mayor número de solicitudes posible usando ofertas de trabajo falsas de muy diversos perfiles profesionales, para posteriormente pedirles dinero, usando diversas excusas, como:</p>
									<!-- <p>Companies registered with false names and emails constantly changing in order to go unnoticed and sometimes we are difficult to detect. These groups of con artists trying to attract the largest number of applications possible using fake job offers diverse professional profiles, later asking for money, using various excuses, like:</p> -->
									 </div>
									 <div class="right txtNF">
										  <p>La realización de un test de aptitud profesional, test psicométricos, pruebas médicas, cuotas para el pago de papelerí­a o visados para el extranjero, etc., tras lo cual desaparecen.</p>
										  <!-- <p>The realization ï¿½ n a career aptitude test, psychometric test ï¿½ tric, ï¿½ dicas more tests, assessments for the payment of papelerï¿½a or abroad visas, etc., After which disappear.</p> -->
										  <p>Desconfí­en de toda empresa que les pida dinero por adelantado. Por favor, no se dejen estafar.</p>
										  <!--  <p>Desconfí­en de toda empresa que les pida dinero por adelantado. Por favor, no se dejen estafar.</p> -->
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinExtendN)) : ?>
	 <div id="winExtendN" class="window">
		  <div class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="cntExtendNotif" class="all">
								<!-- <h3 class="title">Extiende tu proceso</h3> -->
								<h3 class="title">Amplíe su proceso</h3>
								<!--<h3 class="title">AMPLA-and its process</h3>  -->
								<div class="sepBlockBtn">
									 <div class="leftBlockBtn left">
										  <p>Tu aviso sera idéntico.</p><!-- <p>Your ad will be gone ï¿½ ntico.</p> -->
									 </div>
									 <div class="rightBlockBtn right">
										  <?php
										  if ($this->layout()->extender != '') :
												?>
												<a href="<?=
												$this->url(array('module' => 'empresa',
													 'controller' => 'mis-procesos', 'action' => 'extender-proceso',
													 'aviso' => $this->layout()->extender),
													 'default', true)
												?>" id="btnIdentico" class="sptEmp "><span class="hide">Identico</span></a>
											  <?php else : ?>
												<a href="#" id="btnIdentico" class="sptEmp "><span class="hide">Identico</span></a>
										  <?php endif; ?>
									 </div>
								</div>
								<div class="sepBlockBtn">
									 <div class="leftBlockBtn left">
										  <p>Tu aviso será personalizado.</p><!-- <p>Your ad will be personalized.</p> -->
									 </div>
									 <div class="rightBlockBtn right">
										  <?php
										  if ($this->layout()->extender != '') :
												?>
												<a href="<?=
												$this->url(array('module' => 'empresa',
													 'controller' => 'publica-aviso', 'action' => 'index',
													 'extiende' => $this->layout()->extender))
												?>" id="btnPersonali" class="sptEmp "><span class="hide">Identico</span></a>
											  <?php else : ?>
												<a href="#" id="btnPersonali" class="sptEmp "><span class="hide">Identico</span></a>
										  <?php endif; ?>
									 </div>
								</div>
								<div class="sepBlockBtn btnsBlockBtn">
									 <a href="#" class="closeWM cancelEmpPD sptEmp btnCenterAllB "><span class="hide">Cancelar</span></a>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (isset($this->layout()->formCuestionario)) : ?>
		  <?php
		  $formCuestionario
				= $this->layout()->formCuestionario;
		  ?>
		  <div id="questionsWM" class="window fix">
				<a href="#Cerrar" class="closeWM resetQuest icon-close big">Cerrar</a>
				<h3>Preguntas</h3>
				<form id="formQuestions" class="formShareCA all" action="<?= SITE_URL . $formCuestionario->getAction(); ?>" method="post">
					 <fieldset class="questionsN">
						  <p class="c3">La empresa <?= $this->layout()->empresa ?> desea que contestes estas preguntas para poder tener una visión más clara de sus postulantes:</p>
						  <!-- <p class="c3">La empresa <? //= $this->layout()->empresa                  ?>want you to answer these questions in order to have a vision more clear from their applicants s:</p> -->
						  <br>
						  <div id="cntScrollData">
								<?php
								$i
									 = 1;
								?>
								<?php
								foreach ($formCuestionario->getElements() as $pregunta) :
									 ?>
									 <?php
									 if ($pregunta->getType() != 'Zend_Form_Element_Hidden') :
										  ?>
										  <div class="block mB10">
												<div class="left blockEnum"><span class="eNumQ left"><?= $i ?></span></div>
												<div class="right blockQuest">
													 <label for="question<?= $i ?>" class="mB5 c3 block"><?= $pregunta->getLabel(); ?></label>
													 <?=
													 $pregunta->setAttribs(array(
														  'id' => 'question' . $i,
														  'class' => 'areaN questionI areaWM'))->renderViewHelper()
													 ?>
													 <span class="response cGray"> </span>
												</div>
										  </div>
									 <?php else : ?>
										  <?= $pregunta->renderViewHelper() ?>
									 <?php endif; ?>
									 <?php $i++; ?>
								<?php endforeach; ?>
						  </div>
					 </fieldset>

					 <fieldset class="wrap-btn right">
						  <span class="c6 txtRelBtn">Las respuestas son de carácter obligatorio.</span>
						  <a id="btnQCancelCA" class="btnCEscp resetQuest closeWM btn btn-default" href="#Cancelar">Cancelar</a>
						  <input type="submit" id="fQSendCA" value="Continuar" class="btn btn-primary"/>
						  <!-- <span class="c6 txtRelBtn right">The answers are mandatory character.</span>  -->
					 </fieldset>
				</form>
		  </div>
	 <?php endif; ?>
	 <?php if (isset($this->layout()->formReportarAbuso)) : ?>
		  <?php
		  $formReportarAbuso
				= $this->layout()->formReportarAbuso;
		  ?>
		  <div id="reportAbuse" class="window fix">
				<a href="#Cerrar" class="closeWM icon-close big">Cerrar</a>
				<h3>Reportar Abuso</h3>
				<form id="formReportA" class="formShareCA" action="<?= SITE_URL . $formReportarAbuso->getAction(); ?>" method="post">
					 <p><b>¿Por qué quieres reportar un abuso?</b></p><!-- <p class="bold c3"> Why do you want to report abuse?</p> -->
					 <br>
					 <div class="control-group">
						  <?php
						  foreach ($formReportarAbuso->tipo_abuso->getMultiOptions() as
									 $key => $tipo) :
								?>
								<label for="fReport<?= $key ?>" class="mB10 c3 block"><input name="tipo_abuso" id="fReport<?= $key ?>" class="checkN noBdr" type="radio" value="<?= $key ?>" <?=
									 ($key == -1) ? 'checked="checked"' : ''
									 ?> /><?= $tipo ?></label>
								<?php endforeach; ?>
					 </div>
					 <div class="control-group center">
						  <?=
						  $formReportarAbuso->comentario->setAttribs(array(
								'id' => 'fCAReportMsg', 'class' => 'cGray placeH input-xmedium', 'rows' => 10,
								'cols' => 55,
								'alt' => 'Detalla el motivo que has seleccionado (Opcional)'))->renderViewHelper()
						  ?>
						  <span class="response cGray"> </span>
					 </div>
					 <div class="wrap-btn right">
						  <a id="btnRCancelCA" class="closeWM btn btn-default" href="#Cancelar">Cancelar</a>
						  <input type="submit" id="fRSendCA" value="Reportar" class="btn btn-primary"/>
						  <span id="msgErrorReport" class="msgErrorDef right error"></span>
					 </div>
					 <?=$formReportarAbuso->tok->renderViewHelper();?>
				</form>
		  </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarcntNewAdminEM)) : ?>
	 <!-- empresa -->
	 <div id="cntNewAdminEM" class="wwScroll">
		  <div class="wwRelativo">
				<div class="wwModal">
					 <div id="newAdminEM" class="windowAll">
						  <div id="iNewAdmEM" class="innerWin">
								<a href="#Cerrar" class="closeWMM icoCWM"><span class="hide">Cerrar</span></a>
								<div id="inNewAdmEM" class="iWindow r5">
									 <div id="iNAdmEM" class="bLB3 r5 inWindow">
										  <div id="loadHTMLAdm" class="all">
												<!-- Data ajax -->

										  </div>
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAvisoEmpleo)) : ?>
	 <div id="winAvisoEmpleo" class="wwScroll">
		  <div class="wwRelativo">
				<div class="wwModal">
					 <div id="wAvisoEmpleo" class="windowAll">
						  <div id="iWAdvEmpleo" class="innerWin">
								<a href="#Cerrar" class="closeWMM icoCWM"><span class="hide">Cerrar</span></a>
								<div id="inWAdvEmpleo" class="iWindow r5">
									 <div id="iNWAdvEmpleo" class="bLB3 r5 inWindow">
										  <div id="loadHTMLA" class="all">
												<!-- Data ajax aviso -->
										  </div>
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinVerProceso)) : ?>
	 <!-- Inicio Historial de Mis Procesos Borradores -->
	 <div id="winVerProceso" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winVerProceso">
								<!--verProceso-->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>
	 <?php if (!isset($this->layout()->noMostrarWinVerHistorial)) : ?>
	 <div id="winVerHistorial" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winVerHistorial">

						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>
	 <?php if (!isset($this->layout()->noMostrarWinAlertVerProceso)) : ?>
	 <div id="winAlertVerProceso" class="window" rel="">
		  <div id="iWinAlertVerProceso" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inWinAlertVerProceso" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea cerrar el proceso seleccionado?</p>
						  <!--  <p id="titleQ">Are you sure you want to close the selected process?</p> -->
						  <p> Si acepta, su aviso ya no se verá en la web y su proceso
								de selección se cerrará.
						  </p>
						  <!--                     <p> If you accept, your notice no longer will see on the web and its process
								of selection n will close.
						  </p> -->
						  <br>
						  <div id="btnQEmpR" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarProceso)) : ?>
	 <div id="winAlertEliminarProceso" class="window" rel="">
		  <div id="iwinAlertEliminarProceso" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarProceso" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea eliminar el aviso seleccionado?</p>
						  <!--  <p id="titleQ"> Are you sure you want to delete the selected message?</p> -->
						  <p> Si acepta, su aviso será eliminado definitivamente.
						  </p>
						  <!-- <p> If you accept, your announcement will be permanently removed.
						  </p> -->
						  <br>
						  <div id="btnQEliPro" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertAnularCip)) : ?>
	 <div id="winAlertAnularCip" class="window" rel="">
		  <div id="" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea anular el Código de Pago?</p>
						  <!--      <p id="titleQ">Are you sure you want to cancel the Payment code?</p> -->
						  <p> Si acepta, el código de pago será anulado pero el aviso permanecerá como borrador, desde donde podrá indicar otro medio de pago.
						  </p>
						  <!-- <p> If accepted, the payment code will be canceled but the warning will remain in draft form, where you can specify other means of payment.
						  </p> -->
						  <br>
						  <div id="" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>
	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarAviso)) : ?>
	 <div id="winAlertEliminarAviso" class="window" rel="">
		  <div id="iwinAlertEliminarAviso" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAviso" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea Eliminar?</p>
						  <!--<p id="titleQ">¿Está seguro que desea Eliminar?</p>-->
						  <p> eliminando su aviso será eliminado definitivamente.
						  </p>
						  <!--  <p> eliminating your notice will be permanently removed.
						  </p> -->
						  <br>
						  <div id="btnQElimAvi" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertBajaAviso)) : ?>
	 <div id="winAlertBajaAviso" class="window" rel="">
		  <div id="iwinAlertBajaAviso" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertBajaAviso" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea dar de Baja?</p>
						  <!-- <p id="titleQ">Are you sure you want to Baja?</p> -->
						  <br>
						  <div id="btnQBajAvi" class="wrap-btn center">
								<a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
								<a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarAdm)) : ?>
	 <div id="winAlertEliminarAdm" class="window" rel="">
		  <div id="iwinAlertEliminarAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea eliminar este Administrador?</p>
						  <!-- <p id="titleQ">Are you sure you want to delete this manager?</p> -->
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
										  <?php if (!empty($this->layout()->hashForm->hash)) {
												echo $this->layout()->hashForm->hash->renderViewHelper();
										  } ?>
									 <a class="yesCMbtn btn btn-primary" href="#aceptar">Aceptar</a>
									 <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarprocess)) : ?>
	 <div id="winAlertEliminarprocess" class="window" rel="">
		  <div id="iwinAlertEliminarAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">El proceso y su correspondiente notificación se eliminarán de forma permanente.</p>
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary" href="#aceptarr">Aceptar</a>
									 <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarAllprocess)) : ?>
	 <div id="winAlertEliminarAllprocess" class="window" rel="">
		  <div id="iwinAlertEliminarAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">Los procesos seleccionados y sus anuncios se eliminarán de forma permanente.</p>
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
									 <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertPrivilegioAdm)) : ?>
	 <div id="winAlertPrivilegioAdm" class="window" rel="">
		  <div id="iwinAlertPrivilegioAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertPrivilegioAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Está seguro que desea conceder privilegios a este Administrador?</p>
						  <!-- <p id="titleQ">Are you sure you want to grant privileges to the Administrator?</p> -->
						  <p> Usted perderá todo los privilegios de administrador principal.</p>
						 <!-- <p> You will lose all the administrator privileges. -->
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmprivilegioadm" id="frmprivilegioadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary" href="#aceptar">Aceptar</a>
									 <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>
	 <!-- Fin Historial de Mis Procesos Borradores -->

	 <?php if (!isset($this->layout()->noMostrarWinAnadirNotas)) : ?>
	 <!-- INICIO Anadir notas  -->
	 <div id="winAnadirNotas" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winAnadirNotas">
								AÑADIR NOTAS  <!-- ADD NOTES -->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Anadir notas -->
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinAnadirMensaje)) : ?>
	 <!-- INICIO Anadir mensaje -->
	 <div id="winAnadirMensaje" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winAnadirMensaje">
								AÑADIR MENSAJE<!-- add message -->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Anadir mensaje -->
	 <?php endif; ?>

	 <?php
	 if (substr($this->url(), 0, 28) == "/empresa/publica-aviso/paso1" || substr($this->url(),
				0, 41) == "/empresa/publica-aviso-preferencial/paso1") :
		  ?>
		  <div id="ejmsAviso" class="window">
				<div class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
					 <div class="iWindow r5">
						  <div class="bLB3 r5 inWindow">
								<div class="cntImgAvisoEPA"></div>
						  </div>
					 </div>
				</div>
		  </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinInvitarProceso)) : ?>
	 <!-- Enviar Invitacion -->
	 <div id="winInvitarProceso" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winInvitarProceso">
								<!--verProceso-->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarEjemploext)) : ?>
	 <!-- Img Extracargos -->
	 <div id="ejemploext" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="cntExtracargos">
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinRegistrarReferenciado)) : ?>
	 <!-- Agregar referenciado -->
	 <div id="winRegistrarReferenciado" class="window">
		  <div  class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM">
					 <span class="hide">Cerrar</span>
				</a>
				<div class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winRegistrarReferenciado">
								<div id="cargandoReferenciado" class="loading center hide"></div>
								<div id="mainReferenciado" class="center">
									 <h3 class="title">Registrar Referido</h3><!-- Referred Register -->
									 <div id="cntSearchDat">
										  <div class="mB10 all" id="buscarReferenciado">
												<label for="txtbuscaEmail" class="control-label left mR20">E-mail:</label>
												<input type="text" class="inputN left inputNTM" id="txtbuscaEmail" name="buscaEmail" value="">
												<button id="btnBuscarxEmail" class="btn btn-primary mL20 left" type="button">Buscar</button>
												<span class="error respEmailE right msg"></span>
										  </div>
										  <div class="mB20 r5 alignC center hide" id="resultadoReferenciado"></div>
										  <div id="listReference" class="hide"></div>
										  <div id="tablaExistePostulante" class="hide">
												<table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
													 <thead>
														  <tr>
																<th class="data1 titleGrid">&nbsp;</th>
																<th class="data2 titleGrid">Postulante</th>
																<th class="data3 titleGrid"></th>
														  </tr>
													 </thead>
													 <tbody></tbody>
												</table>
										  </div>
										  <div class="hide" id="frmRegistroReferente"></div>
										  <div id="totalRegReferente" class="wrap-btn center">
												<button type="button" id="registerRefer" class=" fix btn btn-primary" >Registrar</button>
										  </div>
									 </div>
								</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinRegistrarInvitacionBuscador)) : ?>
	 <!-- Invitar -->
	 <div id="winRegistrarInvitacionBuscador" class="window">
		  <div  class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM">
					 <span class="hide">Cerrar</span>
				</a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winRegistrarInvitacionBuscador" class="center">

						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinEnviarBolsa)) : ?>
	 <!-- INICIO Enviar a Bolsa -->
	 <div id="winEnviarBolsa" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winAnadirNotas">
								<!-- CONTENIDO VARIABLE -->

								<h3 class="title"> Enviar a Carpetas de CVs</h3> <!--Email CVs Folders  -->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <form method="post" name="frm" id="frm" class="formDataNotaEPA">
										  <input type="hidden" name="id" value="" />
										  <div class="all cntNotaDataEPA" >
												<div class="left"><span id="spEPLabel">Enviar el postulante</span> <span id="spEPNombrePostulante" class="bold">""</span> a:</div>
										  <!-- <div class="left"><span id="spEPLabel">Send the applicant</span> <span id="spEPNombrePostulante" class="bold">""</span> a:</div> -->
										  </div>
										  <div id="chkAllSendCv" class="chkOpMPB chk_allcv">
												<input id="chkGrupo1" type="checkbox"><label for="chkGrupo1">Seleccionar todos</label>
										  </div>
										  <div id="divBolsasEnviar" class="r5">
<!--                                    <div class="chkOpEB"><input id="chk1" type="checkbox"/><label for="chk1">General</label></div>
												<div class="chkOpEB"><input id="chk2" type="checkbox"/><label for="chk2">Programadores PHP</label></div>
												<div class="chkOpEB"><input id="chk3" type="checkbox"/><label for="chk3">Programadores JAVA</label></div>
												<div class="chkOpEB"><input id="chk4" type="checkbox"/><label for="chk4">Programadores NET</label></div>-->
										  </div>
										  <div id="msgErrorNotasAg" class="error hide">*</div>
										  <br>
										  <div class="wrap-btn center">
												<a id="" class=" btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
												<input id="btnAceptarEnviarBolsa" class=" btn btn-primary" href="#" value="Aceptar" type="button"/>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Enviar a Bolsa -->
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinBloquearPos)) : ?>
	 <!-- INICIO Bloquear Postulande -->
	 <div id="winBloquearPos" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div class="loading hide showLoadF">&nbsp;</div>
						  <div id="cntBloquear">
								<!-- CONTENIDO VARIABLE -->
								<h3 class="title">Bloquear Postulante</h3>
								<!-- <h3 class="title">Block Applicant</h3> -->
								<div class="iContenNotaEPA">
									 <form method="post" name="frm" id="frm" class="formDataNotaEPA">
										  <div class="all cntNotaDataEPA" >
												<p>¿Está seguro de bloquear permanentemente el postulante <span id="spBLNombrePostulante" class="bold"></span>de todos los procesos?</p>
										<!--  <p>Are you sure the applicant permanently block <span id="spBLNombrePostulante" class="bold"></span>of all processes?</p>-->
										  </div>
										  <div class="wrap-btn center">
												<button type="button" class="btn btn-default cancelHEPA closeWM">Cancelar</button>
												<button type="button" class="btn btn-primary btnbloquear" id="btnBloquearPos" title="Bloquear">Bloquear</button>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Enviar a Bolsa -->
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinDesBloquearPos)) : ?>
	 <!-- INICIO DesBloquear Postulande -->
	 <div id="winDesBloquearPos" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div class="loading hide showLoadF">&nbsp;</div>
						  <div id="cntDesBloquear">
								<!-- CONTENIDO VARIABLE -->
								<h3 class="title">Desbloquear Postulante</h3>
								<!--    <h3 class="title">unlock Applicant</h3> -->
								<div class="iContenNotaEPA">
									 <form method="post" name="frm" id="frm" class="formDataNotaEPA">
										  <div class="all cntNotaDataEPA" >
												<p id="txtdesbl">¿Está seguro de desloquear permanentemente el postulante <span class="bold">Luis Alberto Mayta Mamani</span> de todos los procesos?</p>
												<!--  <p id="txtdesbl"> Are you sure the applicant permanently desloquear <span class="bold">Luis Alberto Mamani Mayta</span> of all processes?</p> -->
										  </div>
										  <div class="wrap-btn center">
												<button type="button" class="btn btn-default cancelHEPA closeWM">Cancelar</button>
												<button type="button" class="btn btn-primary btndesbloquear" id="btnBloquearPos" title="Desbloquear">Desbloquear</button>
										  </div>
									 </form>
								</div>
								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Enviar a Bolsa -->
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarEjmAvisoPA1)) : ?>
	 <!-- FIN Detalle Membresia -->
	 <div id="ejmAvisoPA1" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="ejmSizeAdv">
								<h3 class="title">Aviso Preferencial <span id="planSizeAdv">&nbsp;</span></h3>
								<div class="alignC"><img src="<? echo $this->S('/images/empresa/logoModalGP.png'); ?>" alt="Logo" /></div>
								<div class="alignC loading" id="imgAvisoPA1"><img src="<? echo $this->S('/images/empresa/preferenciales/vistaprevia/previa1x1.jpg'); ?>" alt="Ejemplo de aviso" /></div>
								<div class="divArrowAs">Aviso <span id="tamanioSizeAdv">&nbsp;</span> cm</div>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Detalle Membresia -->
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinMoverBolsa)) : ?>
	 <!-- INICIO Mover en Bolsa -->
	 <div id="winMoverBolsa" class="window">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winMoverBolsa">
								<!-- CONTENIDO VARIABLE -->

								<h3 id="titleMoverPostulante" class="title">Mover Postulante</h3>
								<!-- <h3 id="titleMoverPostulante" class="title">move Applicant</h3> -->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <form method="post" name="frm" id="frm" class="">
										  <input type="hidden" name="id" value="" />
										  <div class="all cntNotaDataEPA" >
												<div class="left"><span id="spMPLabel">Mover al postulante</span> <span id="spMPNombrePostulante" class="bold">""</span> a:</div>
												<!--  <div class="left"><span id="spMPLabel">Move to the postulant</span> <span id="spMPNombrePostulante" class="bold">""</span> a:</div> -->
										  </div>
										  <div id="divBolsasMover" class="r5">
	 <!--                                <div class="chkOpMPB"><input id="chk1MP" type="checkbox"/><label for="chk1MP">Grupo 1</label></div>
												<div class="chkOpMPB"><input id="chk2MP" type="checkbox"/><label for="chk2MP">Grupo 2</label></div>
												<div class="chkOpMPB"><input id="chk3MP" type="checkbox"/><label for="chk3MP">Grupo 3</label></div>
												<div class="chkOpMPB"><input id="chk4MP" type="checkbox"/><label for="chk4MP">Grupo 4</label></div>-->
										  </div>
										  <div id="msgErrorNotasMov" class="error hide">*</div>
										  <br>
										  <div class="wrap-btn center">
												<a id="" class="btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
												<input id="btnAceptarMoverBolsa" class="btn btn-primary aceptEBCVS" href="#" value="Aceptar" type="button"/>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Mover en Bolsa -->
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarWinAddGroup)) : ?>
	 <!-- INICIO Añadir Grupo -->
	 <div id="winAddGroup" class="window winOperaGroup">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winAddGroup">
								<!-- CONTENIDO VARIABLE -->

								<h3 class="title">Añadir grupo</h3>
								<!--<h3 class="title"> add group </h3>-->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <form method="post" name="frm" id="frm" class="">
										  <input type="hidden" name="id" value="" />
										  <div class="all cntNotaDataEPA" >
												<label for="txtNameGroup" class="control-label">
													 Nombre  <!-- name -->
												</label>
												<input type="text" class="cGray placeH txtNameG left" <?=
												defined('MAX_CHARS_GROUP_NAME') ? ' maxlength="' . MAX_CHARS_GROUP_NAME . '"'
														  : ''
												?> id="txtNameGroup" name="txtNameGroup" alt="Ingresar nombre de grupo" value="Ingresar nombre de grupo"/>
												<input type="hidden" id="tok_bolsa_grp" name="tok_bolsa_grp" value="<?php echo (defined('CSRF_HASH') === true) ? constant('CSRF_HASH') : '';  ?>" />
										  </div>
										  <div id="msgErrorAgregarGrupo" class="error hide">*</div>
										  <br>
										  <div class="wrap-btn center">
												<a id="" class="btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
												<input id="btnAceptarAnadirGrupo" class="btn btn-primary aceptEBCVS" href="#" value="Aceptar" type="button"/>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Añadir Grupo -->
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinChangeNameGroup)) : ?>
	 <!-- INICIO Editar Nombre Grupo -->  <!-- Home Edit Group Name -->
	 <div id="winChangeNameGroup" class="window winOperaGroup">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winChangeNameGroup">
								<!-- CONTENIDO VARIABLE -->

								<h3 class="title">Cambiar nombre de Grupo</h3>
								<!-- <h3 class="title">Rename Group</h3> -->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <form method="post" name="frm" id="frm" class="">
										  <input type="hidden" name="id" value="" />
										  <div class="all cntNotaDataEPA" >
												<label for="txtNameEditGroup" class="control-label">
													 Nombre <!-- name -->
												</label>
												<input type="text" class="txtNameG left" <?=
												defined('MAX_CHARS_GROUP_NAME') ? ' maxlength="' . MAX_CHARS_GROUP_NAME . '"'
														  : ''
												?> id="txtNameEditGroup" name="txtNameEditGroup" alt="" value=""/>
										  </div>
										  <div id="msgErrorEditarGrupo" class="error hide">*</div>
										  <br>
										  <div class="wrap-btn center">
												<a id="" class="btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
												<input id="btnAceptarModificarGrupo" class="btn btn-primary aceptEBCVS" href="#" value="Aceptar" type="button"/>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <!-- FIN Editar Nombre Grupo -->
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinDeleteGroup)) : ?>
	 <!-- INICIO Eliminar Grupo -->
	 <div id="winDeleteGroup" class="window winOperaGroup">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winDeleteGroup">
								<!-- CONTENIDO VARIABLE -->

								<h3 class="title">Eliminar Grupo</h3>
								<!--<h3 class="title">remove group</h3>  -->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <form method="post" name="frm" id="frm" class="">
										  <input type="hidden" name="id" value="" />
										  <div class="all cntNotaDataEPA" >
												<p class="left">¿Está seguro que desea eliminar el grupo "<span id="spEPNombreGrupo"></span>"?</p>
												<!-- <div class="left">Are you sure you want to delete the group "<span id="spEPNombreGrupo"></span>"?</div> -->
										  </div>
										  <div id="divEnviaBolsa" class="r5">
												<dipv class="chkOpEB"><input id="chkCopyG" type="checkbox"/><label for="chkCopyG">Copiar postulantes al grupo "GENERAL"</label></p>
												<!--  <div class="chkOpEB"><input id="chkCopyG" type="checkbox"/><label for="chkCopyG">Copy applicants to the group "GENERAL"</label></div> -->
										  </div>
										  <div id="msgErrorNotas" class="error hide">*</div>
										  <br>
										  <div class="wrap-btn center">
												<a id="" class="btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
												<input id="btnAceptarEliminarGrupo" class="btn btn-primary aceptEBCVS" href="#" value="Aceptar" type="button"/>
										  </div>
									 </form>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarBusqueda)) : ?>
	 <!-- Remove Busqueda alert box-->
	 <div id="winAlertEliminarBusqueda" class="window" rel="">
		  <div id="iwinAlertEliminarAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Estás seguro que deseas eliminar la busqueda seleccionada?</p>
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary" href="#aceptarr">Aceptar</a>
									 <a class="cancelCM btn btn-default closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarWinAlertEliminarRecom)) : ?>
	 <!-- Remove Recommendation alert box-->
	 <div id="winAlertEliminarRecom" class="window" rel="">
		  <div id="iwinAlertEliminarAdm" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">¿Estás seguro que deseas eliminar la recomendación solicitar seleccionada?</p>
						  <br>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary" href="#aceptarr">Aceptar</a>
									 <a class="cancelCM btn btn-primary closeWM" href="#cancelar">Cancelar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>



	 <?php if (!isset($this->layout()->noMostrarWinAlertVerRecom)) : ?>
	 <!-- Recommendation not approved alert box-->
	 <div id="winAlertVerRecom" class="window" rel="">
		  <div id="iwinAlertVerRecom" class="innerWin">
				<a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div id="inwinAlertEliminarAdm" class="iWindow r5">
					 <div id="iWinA" class="bLB3 r5 inWindow">
						  <p id="titleQ">La recomendación no ha sido aprobado</p>
						  <div id="btnQElimAdm" class="wrap-btn center">
								<form action="" method="post" name="frmdeleteadm" id="frmdeleteadm">
									 <?php if (!empty($this->layout()->hashForm->hash)) {
									 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
									 <a class="yesCM btn btn-primary closeWM" href="#cancelar">Aceptar</a>
								</form>
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>


	 <!-- FIN Eliminar Grupo -->

	 <?php if (!isset($this->layout()->noMostrarWinQuitarPostulante)) : ?>
	 <!-- INICIO Quitar Postulante -->  <!--HOME Remove Applicant  -->
	 <div id="winQuitarPostulante" class="window winOperaGroup">
		  <div  class="innerWin"> <a href="#Cerrar" class="closeWM icoCWM"><span class="hide">Cerrar</span></a>
				<div  class="iWindow r5">
					 <div class="bLB3 r5 inWindow">
						  <div id="content-winRemovePostulant">
								<!-- CONTENIDO VARIABLE -->

								<h3 class="title">Quitar Postulante</h3>
								<!-- <h3 class="title">Remove Applicant</h3> -->
								<div class="iContenNotaEPA">
									 <div id="cargando" class="hide"></div>
									 <input type="hidden" name="id" value="" />
									 <div class="all cntNotaDataEPA" >
										  <div class="alignL"><span id="spQPLabel">¿Está seguro que desea quitar el postulante</span><span id="spQPNombrePostulante" class="bold">""</span> de este grupo?</div>
									 <!--  <div class="alignL"><span id="spQPLabel">Are you sure you want to remove the applicant</span><span id="spQPNombrePostulante" class="bold">""</span> de este grupo?</div> -->
									 </div>
									 <div id="msgErrorNotas" class="error hide">*</div>
									 <br>
									 <div class="wrap-btn center">
										  <a id="" class="btn btn-default cancelHEPA closeWM" href="#">Cancelar</a>
										  <input id="btnAceptarQuitarBolsa" class="btn btn-primary aceptEBCVS" href="#" value="Aceptar" type="button"/>
									 </div>
								</div>

								<!---->
						  </div>
					 </div>
				</div>
		  </div>
	 </div>
	 <?php endif; ?>



	 <?php if (!isset($this->layout()->noMostrarDivModalContact)) : ?>
	 <!--  Modal Contactar -->
	 <?php
	 $email = '';
	 $rs = '';
	 $nom = '';
	 $fono = '';
		  if (isset($this->layout()->auth['empresa'])) {
				$auth = $this->layout()->auth;
				$email = $auth['usuario']->email;
				$rs = $auth['empresa']['razon_social'];
				$nom = $auth['usuario-empresa']['nombres'].' '.$auth['usuario-empresa']['apellidos'];
				$fono = $auth['usuario-empresa']['telefono'];
		  }
		  //<div class="hide response bad"></div></div>
	 ?>

	 <div id="regP" class="hide">
		  <h2 class="text-mediumx center">REGISTRATE EN EMPLEOBUSCO</h2>
		  <p> Quiero registrarme en AquiEmpleos como: </p><br>
		  <div class="cgroup-inline">
				<div class="control-group">
					 <label class="ioption" for="userPE-Pos">
						  <input type="radio" name="userPE" id="userPE-Pos" value="Pos" errMsg="Campo Requerido" class="" tabindex="10" />Postulante</label><label class="ioption" for="userPE-Emp"><input type="radio" name="userPE" id="userPE-Emp" value="Emp" checked="checked" errMsg="Campo Requerido" class="" tabindex="10" />Empresa
					 </label>
				</div>
				<span class="response cGray left"> </span>
		  </div>
		  <div id="msgLoadReturnPP" class="box-message hide"></div>
		  <div class="wrap-btn center" id="register_hide">
				<a class="btn btn-primary input-big" href="/empresa/registro-empresa">Regístrate</a>
		  </div>
		  <p class="center mT10">Si ya estás registrado <a title="" class="login_modal" href="#loginP">Ingresa</a></p>
	 </div>

	 <div id="divModalContact" class="contact-modal hide">
		  <h2 class="text-mediumx">Planes de Membresía</h2>
		  <form id="frmContactMemberShip" name="frmContactMemberShip" method="post" action="" class="frm-horizontal">
				<div class="control-group">
					 <label for="txtCompany" class="control-label"><em>*</em> Empresa: </label>
					 <div class="controls"><input type="text" name="txtCompany" id="txtCompany" value="<?=$rs?>" class="input-xxmiddle" maxlength="50" required data-parsley-trigger="change" data-parsley-minlength="2"  data-parsley-maxlength="50" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚ ]+$/gi"></div>
				</div>
				<div class="control-group">
					 <label for="txtContact" class="control-label"><em>*</em> Nombre de Contacto: </label>
					 <div class="controls"><input type="text" name="txtContact" id="txtContact" value="<?=$nom?>" class="input-xxmiddle" maxlength="50" required data-parsley-trigger="change" data-parsley-minlength="2" data-parsley-maxlength="50" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚ ]+$/gi"></div>
				</div>
				<div class="control-group">
					 <label for="txtPhone" class="control-label"><em>*</em> Teléfono de Contacto: </label>
					 <div class="controls"><input type="text" name="txtPhone" id="txtPhone" maxlength="15" value="<?=$fono?>" class="input-xxmiddle number" required data-parsley-trigger="change" data-parsley-minlength="6" data-parsley-minlength-message="La longitud mínima es de 6 dígitos" data-parsley-maxlength="9" data-parsley-type="number"></div>
				</div>
				<div class="control-group">
					 <label for="txtEmail" class="control-label"><em>*</em> E-mail: </label>
					 <div class="controls"><input type="text" name="txtEmail" id="txtEmail" value="<?=$email?>" class="input-xxmiddle" maxlength="50" required="" data-parsley-type="email" data-parsley-trigger="change" data-parsley-maxlength="100"></div>
				</div>
				<div class="control-group">
					 <label for="txaMessage" class="control-label"><em>*</em> Consulta</label>
					 <div class="controls"><textarea name="txaMessage" id="txaMessage" maxlength="3000" required data-parsley-trigger="change"></textarea></div>
				</div>

				<div class="txt_right">
					 <input type="hidden" name="hidMembresia" id="hidMembresia" value="">
					 <?php if (!empty($this->layout()->hashForm->hash)) {
					 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>
					 <div class="hide response left">Campo requerido</div>
					 <button type="submit" id="btnSendMemberShip" title="Enviar" class="btn btn-primary input-small">Enviar</button>
				</div>
		  </form>
	 </div>
	 <?php endif; ?>


	 <?php if (!isset($this->layout()->noMostrarDivWrapSelection)) : ?>
	 <div id="divWrapSelection" class="contact-modal hide">
		  <h2 class="text-mediumx">EMPLEOBUSCO SELECCIÓN</h2>
		  <form id="frmContacSelection" name="frmContactSeleccion" method="post" action="" class="frm-horizontal">
				<div class="control-group">
					 <label for="txtCompany" class="control-label"><em>*</em> Razón Social: </label>
					 <div class="controls"><input type="text" name="txtCompany" id="txtCompany" value="<?=$rs?>" class="input-xxmiddle" maxlength="50" required data-parsley-trigger="change" data-parsley-minlength="2"  data-parsley-maxlength="50" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚ ]+$/gi"></div>
				</div>
				<div class="control-group">
					 <label for="txtPhoneCompany" class="control-label"><em>*</em> Teléfono de Empresa: </label>
					 <div class="controls"><input type="text" name="txtPhoneCompany" id="txtPhoneCompany" class="input-xxmiddle number" maxlength="9" required data-parsley-trigger="change" data-parsley-minlength="6" data-parsley-minlength-message="La longitud mínima es de 6 dígitos" data-parsley-maxlength="9" data-parsley-type="number"></div>
				</div>
				<div class="control-group">
					 <label for="txtContact" class="control-label"><em>*</em> Nombre de contacto: </label>
					 <div class="controls"><input type="text" name="txtContact" id="txtContact" value="<?=$nom?>" placeholder="" class="input-xxmiddle" maxlength="50" required data-parsley-trigger="change" data-parsley-minlength="2" data-parsley-maxlength="50" data-parsley-pattern="/^[a-z-ñáéíóúÑÁÉÍÓÚ ]+$/gi"></div>
				</div>
				<div class="control-group">
					 <label for="txtPhone" class="control-label"><em>*</em> Teléfono de contacto: </label>
					 <div class="controls"><input type="text" name="txtPhone" id="txtPhone" maxlength="9" value="<?=$fono?>" class="input-xxmiddle number" maxlength="9" required data-parsley-trigger="change" data-parsley-minlength="6" data-parsley-minlength-message="La longitud mínima es de 6 dígitos" data-parsley-maxlength="9" data-parsley-type="number"></div>
				</div>
				<div class="control-group">
					 <label for="txtEmail" class="control-label"><em>*</em> E-mail de contacto: </label>
					 <div class="controls"><input type="text" name="txtEmail" id="txtEmail"  maxlength="100" value="<?=$email?>" class="input-xxmiddle" value="<?=$email?>" class="input-xxmiddle" maxlength="50" required="" data-parsley-type="email" data-parsley-trigger="change" data-parsley-maxlength="100"></div>
				</div>
				<div class="control-group">
					 <label for="txaMessage" class="control-label"><em>*</em> Consulta:</label>
					 <div class="controls"><textarea name="txaMessage" id="txaMessage" maxlength="3000" required data-parsley-trigger="change"></textarea></div>
				</div>
				<div class="control-label"><em>*</em> Campo requerido</div>
				<div class="wrap-btn right">
					 <?php if (!empty($this->layout()->hashForm->hash)) {
					 echo $this->layout()->hashForm->hash->renderViewHelper(); }?>

					 <button type="submit" id="btnSendContact"  onClick="ga('send', 'event', 'EMPLEOBUSCO_Selección', 'Enviar');" title="Enviar" class="btn btn-primary input-small">Enviar</button>
				</div>
		  </form>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarDivModalSaveSearch)) : ?>
	 <div id="divModalSaveSearch" class="hide">
		  <h2 class="modal-title">Guardar Búsqueda</h2>
		  <div class="controls-inline">
				<div class="controls"><label for="txaMessage" class="control-label no-req"> Nombre de la búsqueda</label></div>
				<div class="controls"><input type="text" name="txtNameSaveSearch" id="txtNameSaveSearch" maxlength="40" class="input-xxmiddle"></div>
		  </div>
		  <div class="center mT20">
				<button id="btnSave" class="btn btn-primary">Guardar Búsqueda</button>
				<button id="btnClose" class="btn btn-default">Cancelar</button>
		  </div>
		  <div class="response good hide"></div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarDivModalDeleteSearch)) : ?>
	 <div id="divModalDeleteSearch" class="hide">
		  <h2 class="modal-title">Eliminar Búsqueda</h2>
		  <p class="txt_center">¿Desea eliminar la búsqueda guardada <b class="name_search"></b> ?</p>
		  <div class="center mT20">
				<button id="btnDelete" class="btn btn-primary">Eliminar</button>
				<button id="btnClose" class="btn btn-default">Cancelar</button>
		  </div>
		  <div class="response good hide"></div>
	 </div>
	 <?php endif; ?>

	 <?php if (!isset($this->layout()->noMostrarDivWrapHelp)) : ?>
	 <div id="divWrapHelp" class="hide">
		  <h2 class="modal-title">Ayuda</h2>
	 </div>
	 <?php endif; ?>

	 <!-- Fin -->
	 <div id="mask"></div>

	 <?php
		  if (isset($this->layout()->loginForm)) :
				echo $this->partial('_box_login.phtml',
						  array(
								'loginForm' => $this->loginForm,
								'recuperarClaveForm' => $this->recuperarClaveForm,
								'AppFacebook' => $this->layout()->AppFacebook,
								'urlAuthAppFacebook' => $this->layout()->urlAuthAppFacebook,
								'ingresaSelectorForm' => $this->layout()->ingresaSelectorForm,
								'ingresaEmpSelectorForm' => $this->layout()->ingresaEmpSelectorForm,
								'postulanteDni' => $this->layout()->postulanteDni));
		  endif;
	 ?>
</div>
