<footer>
   <div class="box-center">
      <div class="grids-2">

         <img class="responsive-img-footer" src="<?= $this->S('/img/logo_empleobusco-footer.png'); ?>" alt="AquiEmpleos">
         <a href="" title="corporation">(C) 2016 aquiempleos.com</a>
      </div>
      <div class="grids-2">
         <h3 class="footer-title fix">Postulantes</h3>
         <ul class="list-footer">
            <li><a href="/empresa/registro-empresa" title="Inicio">Crea tu Cuenta</a></li>
            <li><a href="/#loginP" title="Mis Avisos">Ingresar</a></li>
            <li><a href="/buscar" title="Buscar">Empleo Busco</a></li>
         </ul>
      </div>
      <div class="grids-2">
         <h3 class="footer-title fix">Empresas</h3>
         <ul class="list-footer">
            <li><a href="/empresa/registrar-empresa" title="Registro">Crea tu Cuenta</a></li>
            <li><a href="/empresa/#loginP" title="Registrar Empresa">Ingresar</a></li>
         </ul>
      </div>
      <div class="grids-2">
         <h3 class="footer-title fix">Síguenos</h3>
         <div class="icons">
            <i class="fa fa-facebook" aria-hidden="true"></i>
            <i class="fa fa-twitter" aria-hidden="true"></i>
         </div>
      </div>
   </div>
</footer>
