<div id="header" class="gridS20">
    <div id="logoSlogan" class="grid9 alpha left">
        <h1 id="logo">
       <img data-png="<?= $this->S('/img/logo_aquiesta.png'); ?>" src="<?= $this->S('/img/logo_aquiesta.png'); ?>" alt="AquiEmpleos" height="27" width="171">
        </h1>
    </div>
    <div id="asideHead" class="grid11 last right">
        <ul id="menuHead">
             <?if(!is_null($this->auth)): ?>
                <li class="itemHead lineNone">
                <?php if (isset($this->auth['usuario'])){
                        echo 'Bienvenido (a) ';
                        echo $this->escape(ucfirst($this->auth['usuario']->nombre)." ".ucfirst($this->auth['usuario']->apellido));
                   } ?>
                </li>
                <li class="itemHead linePTB lineRight"><a href="<?=SITE_URL.'/auth/logouta'?>">Salir</a></li>
            <? endif; ?>
        </ul>
    </div>
</div>
