<header>
    <div class="box-center">
    	<a href="/empresa">
			<img data-png="<?=SITE_URL?>/static/main/img/logo_empleobusco.png?v=dere3" src="<?=SITE_URL?>/static/main/img/logo_empleobusco.png?v=d" alt="AquiEmpleos" height="27" width="171">
    	</a>
        <ul class="head-buttons">
            <?= $this->Headerbuttons($this->ModuleActual(),$this->auth); ?>
        </ul>
    </div>
</header>
