<!DOCTYPE html>
<!--[if lt IE 7]>
<html lang="es" xmlns:fb="http://ogp.me/ns/fb#" class="lt-ie6"></html><![endif]--><!--[if IE 7]>
<html lang="es" xmlns:fb="http://ogp.me/ns/fb#" class="lt-ie7"></html><![endif]--><!--[if IE 8]>
<html lang="es" xmlns:fb="http://ogp.me/ns/fb#" class="lt-ie8"></html><![endif]--><!--[if IE 9]>
<html lang="es" xmlns:fb="http://ogp.me/ns/fb#" class="lt-ie9"></html><![endif]-->
<!-- [if (gt IE 9)|!(IE)] <!-->
<html lang="es" xmlns:fb="http://ogp.me/ns/fb#">
    <!-- <![endif]-->
    <head>
        <?= $this->headMeta() ?>

        <meta http-equiv="Content-Language" content="es" />
        <meta name="robots" content="<?php echo empty($this->layout()->robots) ? 'index,follow' : $this->layout()->robots ?>"/>
        <meta name="robots" content="noodp,noydir" >
        <meta name="Author" content="Empleos.com" />
        <meta name="geo.placename" content="Peru" />
        <meta name="msvalidate.01" content="050EB16938699EA18AA37FCBD106D6FE" />
        <meta name="format-detection" content="telephone=no">

        <?= $this->headTitle() ?>
        <?= $this->headLink() /* = $this->headLink() 
          <link href="<?= $this->S('/css/layout.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/portada.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/icons.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/plugins.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/layout2.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/plugins/jquery.fancybox.css'); ?>" media="all" rel="stylesheet" type="text/css">
          <link href="<?= $this->S('/css/printCip.css'); ?>" media="all" rel="stylesheet" type="text/css">
         */ ?>
        <link href="<?= $this->S('/css/bootstrap.min.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/css/bootstrap-theme.min.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/font-awesome/css/font-awesome.min.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/css/main.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/css/utilities.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <?= $this->headScript() ?>
        <?php
        if(isset($this->layout()->trackingFacebook)) {
            //echo $this->TrackingPixelFacebook();
        }
        ?>
        <script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <script type='text/javascript'>
<?php echo "var tmp = { appIdFacebook: '" . (isset($this->AppFacebook->appid) ? $this->AppFacebook->appid : '') . "'};" ?>
        </script>
    </head>
    <body <?= $this->attribs($this->layout()->bodyAttr) ?><?= defined('CSRF_HASH') ? ' data-hash="' . CSRF_HASH . '"' : '' ?>>
        <?php // $this->PixelSegmentacion(MODULE, CONTROLLER, ACTION); ?>
        <?php echo $this->DaxTag($this->layout()->params, $this->layout()); ?>
        <?php //= $this->render('_band-top.phtml') ?>
        <?=
        /* Header Page */
        $this->partial('_header.phtml', array(
            'auth' => $this->layout()->auth,
            'menu_sel' => $this->layout()->menu_sel,
            'modulo' => $this->layout()->modulo
                )
        )
        ?>
        <?= $this->layout()->content ?>
        <?= $this->render('_footer.phtml'); ?>
        <?=
        $this->partial('_boxes.phtml', array(
            'loginForm' => $this->layout()->loginForm,
            'recuperarClaveForm' => $this->layout()->recuperarClaveForm,
            'modulo' => $this->layout()->modulo,
            'registrorapido' => $this->layout()->registrorapido,
            'ingresaSelectorForm' => $this->layout()->ingresaSelectorForm,
            'postulanteDni' => $this->layout()->postulanteDni
                )
        );
        
       // var_dump( $this->layout()->loginForm);
        ?>

        <script src="<?php echo $this->S('/js/jquery-3.0.0.min.js'); ?>"></script>
        <script src="<?php echo $this->S('/js/bootstrap.min.js'); ?>"></script>

        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/utils/utils.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/schemas/modules.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/template/template.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/all.js'); ?>"></script>
        <?php if(MODULE == 'empresa') { ?>
            <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/' . MODULE . '.js'); ?>"></script>
            <?php if(CONTROLLER == 'look-and-feel') { ?>
                <script type="text/javascript" src="<?php echo $this->S('/main/js/modules/empresa/look-and-feel/look-and-feel.js'); ?>"></script>
            <?php } ?>
        <?php } ?>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/postulante.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/appLoad.js'); ?>"></script>
        <div id="fb-root"></div>
        <?= $this->ClickTale()->Inferior(); ?>
    </body>
</html>
