<!DOCTYPE html>

<html lang="es" xmlns:fb="http://ogp.me/ns/fb#">
    <!-- <![endif]-->
    <head>
        <?= $this->headMeta() ?>
        <meta http-equiv="Content-Language" content="es" />
        <meta name="robots" content="<?php echo empty($this->layout()->robots) ? 'index,follow' : $this->layout()->robots ?>"/>
        <meta name="robots" content="noodp,noydir" >
        <meta name="Author" content="Empleos.com" />
        <meta name="geo.placename" content="Peru" />
        <meta name="msvalidate.01" content="050EB16938699EA18AA37FCBD106D6FE" />
        <meta name="format-detection" content="telephone=no">
        <?= $this->headTitle() ?>
        <link href="<?= $this->S('/font-awesome/css/font-awesome.min.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/css/footer.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <link href="<?= $this->S('/css/utilities.css'); ?>" media="all" rel="stylesheet" type="text/css">
        <?= $this->headLink() ?>
        <!--
           <link rel="canonical" href="<?= SITE_URL . $this->userAgent()->getServerValue('request_uri'); ?>" />
             <link title="Empleos.com" rel="search" type="application/opensearchdescription+xml" href="<?= $this->S('/opensearch/opensearch-description.xml') ?>" />
        -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css'>
        <?php // = isset($this->layout()->SEOCanonical)?$this->layout()->SEOCanonical:'' ?>
        <?= isset($this->layout()->SEONext) ? $this->layout()->SEONext : '' ?>
        <?= isset($this->layout()->SEOPrev) ? $this->layout()->SEOPrev : '' ?>
        <?= $this->headScript() ?>
        <!--[if lte IE 9]>
            <script type="text/javascript" src="<?= $this->S('/js/libs/html5shiv.js') ?>"></script>
        <![endif]-->
        <?php if(!(MODULE == 'postulante' && CONTROLLER == 'home' && ACTION == 'index')) { ?>
            <script type="text/javascript" src="<?php echo $this->S('/js/main.js'); ?>"></script>
        <?php } ?>
        <script type="text/javascript" src="http://www.google.com/jsapi"></script>
        <?= $this->GoogleAnalytics(); ?>
        <?php if(MODULE == 'postulante' && CONTROLLER == 'home' && ACTION == 'index') { ?>
            <?php //= $this->SitelinksSearchBox(); ?>
        <?php } ?>
        <?php if(isset($this->layout()->trackingFacebook)) {
           // echo $this->TrackingPixelFacebook();
        } ?>
        <script type='text/javascript'>
        <?php echo "var tmp = { appIdFacebook: '" . (isset($this->AppFacebook->appid) ? $this->AppFacebook->appid : '') . "'};" ?>
        </script>
    </head>
    <body <?= $this->attribs($this->layout()->bodyAttr) ?><?= defined('CSRF_HASH') ? ' data-hash="' . CSRF_HASH . '"' : '' ?>>
        <?= $this->PixelSegmentacion(MODULE, CONTROLLER, ACTION); ?>

        <?php echo $this->DaxTag($this->layout()->params, $this->layout()); ?>
        <?php //= $this->render('_band-top.phtml') ?>

        <?=
        /* Header Page */
        $this->partial('_header.phtml', array(
            'auth' => $this->layout()->auth,
            'menu_sel' => $this->layout()->menu_sel,
            'modulo' => $this->layout()->modulo
                )
        )
        ?>

        <?php echo $this->layout()->content ?>

        <?php
        $mostrarFooter = true;
        if(isset($this->layout()->auth["usuario"]))
            if($this->layout()->auth["usuario"]->rol == "admin")
                $mostrarFooter = false;
        ?>

        <?= ($mostrarFooter) ? $this->render('_footer.phtml') : "" ?>
        <?=
        $this->partial('_boxes.phtml', array(
            'loginForm' => $this->layout()->loginForm,
            'recuperarClaveForm' => $this->layout()->recuperarClaveForm,
            'modulo' => $this->layout()->modulo,
            'registrorapido' => $this->layout()->registrorapido,
            'ingresaSelectorForm' => $this->layout()->ingresaSelectorForm,
            'postulanteDni' => $this->layout()->postulanteDni
                )
        );
        ?>

        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/utils/utils.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/schemas/modules.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/template/template.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/all.js'); ?>"></script>
        <?php if(MODULE == 'empresa') { ?>
            <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/' . MODULE . '.js'); ?>"></script>
            <?php if(CONTROLLER == 'look-and-feel') { ?>
                <script type="text/javascript" src="<?php echo $this->S('/main/js/modules/empresa/look-and-feel/look-and-feel.js'); ?>"></script>
            <?php } ?>
        <?php } ?>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/modules/postulante.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->S('/js/src/libs/yoson/appLoad.js'); ?>"></script>
        <script language="JavaScript1.3" src="http://b.scorecardresearch.com/c2/6906602/ct.js"></script>
        <script id="navegg" type="text/javascript" src="//tag.navdmp.com/tm42256.js"></script>
        <div id="fb-root"></div>
        <?= $this->ClickTale()->Inferior(); ?>
    </body>
</html>
