<!DOCTYPE html>
<html lang="es" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://ogp.me/ns/fb#">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="language" content="es">
        <?= $this->headTitle() ?>
        <?= $this->headMeta() ?>
        <meta name="robots" content="<?php echo $this->layout()->robots ?>"/>
        <meta name="robots" content="noodp,noydir" >
        <meta name="Author" content="Empleos.com">
        <meta name="geo.placename" content="Peru">
        <meta name="geo.position" content="-12.0478;-77.0622">
        <meta name="geo.region" content="PE-LIM">
        <meta name="ICBM" content="-12.0478, -77.0622">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
        <meta name="msvalidate.01" content="050EB16938699EA18AA37FCBD106D6FE" />
        <meta name="format-detection" content="telephone=no">
        <link title="Empleos.com" rel="search" type="application/opensearchdescription+xml" href="<?= $this->S('/opensearch/opensearch-description.xml') ?>" />
        <!--<link rel="canonical" href="<?= SITE_URL.$this->userAgent()->getServerValue('request_uri'); ?>" />-->
        <?php //echo $this->layout()->SEOCanonical; ?>
        <?php echo $this->layout()->SEONext; ?>
        <?php echo $this->layout()->SEOPrev; ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->GoogleAnalytics(); ?>
        <?php //echo $this->SitelinksSearchBox(); ?>
        <?php //echo $this->TrackingPixelFacebook($this->layout()->trackingFacebook); ?>
        <?php ///$this->PixelSegmentacion(); ?>

    </head>

    <body>
        <?php echo $this->DaxTag($this->layout()->params, $this->layout()); ?>
        <?php
        echo $this->partial('render/_header.phtml',
            array(
            'layout' => $this->layout(),
            'auth' => $this->layout()->auth));
        ?>
        <div class="page_default">
            <?php echo $this->layout()->content ?>
            <?php
            echo $this->partial('render/_footer.phtml',
                array(
                'auth' => $this->layout()->auth))
            ?>
        </div>
        <?= $this->LayoutBoxes($this->layout()); ?>
        <?= $this->headScript() ?>
        <div id="fb-root"></div>
<?php $this->Util()->fontsIE8(); ?>

<script id="navegg" type="text/javascript" src="//tag.navdmp.com/tm42256.js"></script>


    </body>
</html>
