<!DOCTYPE html>
<html lang="en">
  <head>
	 <meta charset="utf-8">
	 <meta name="viewport" content="width=device-width, initial-scale=1.0">
	 <meta name="description" content="">
	 <meta name="author" content="">
	 <title>Empresas | AQUIESTA - EMPLEO</title>
	 <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
	 <link href="css/bootstrap.min.css" rel="stylesheet">
	 <link href="css/font-awesome.min.css" rel="stylesheet">
	 <link rel="stylesheet" href="css/bootstrap.min.css">
	 <link rel="stylesheet" href="font-awesome/css/font-awesome.min.css">
	 <link rel="stylesheet" href="css/header.css">
	 <link rel="stylesheet" href="css/footer.css">
	 <link rel="stylesheet" href="css/main.css">
	 <link rel="stylesheet" href="css/utilities.css">
	 <link rel="stylesheet" type="text/css" href="slick/slick.css">
	 <link rel="stylesheet" type="text/css" href="slick/slick-theme.css">
	 <link rel="stylesheet" href="css/carusel.css">
	 <link rel="stylesheet" href="css/responsive.css">
  </head>
  <body>
	 <header>
		<nav class="navbar
		navbar-default navbar-fixed-top">
		  <div class="container-fluid">
			 <div class="link-todobusco">
				<a href="#"><h3>aquiempleos.com</h3></a>
			 </div>
		  </div>
		  <div class="container">
			 <div class="navbar-header page-scroll">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"> <img src="img/empresas/logo.png"></a>

			 </div>
			 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav top-a">
					 <li class="categoria mcl">Empresas</li>
				</ul>
				<ul class="nav navbar-nav navbar-right top-b">
				  <li class="hidden"><a href="#page-top"></a></li>
				  <li class="page-scroll"><a class="one" href="#">Ingresar</a></li>
				  <li class="page-scroll"><a class="two" href="#">Regístrate</a></li>
				  <li class="page-scroll"><a class="tree" href="#">Soy un postulante</a></li>
				</ul>
			 </div>
		  </div>
		</nav>
	 </header>
	 <!--CAROUSEL-->
	 <section id="main-slider" class="carusell">
		<div class="carousel slide">
		  <ol class="carousel-indicators">
			 <li data-target="#main-slider" data-slide-to="0" class="active"></li>
			 <li data-target="#main-slider" data-slide-to="1"></li>
			 <li data-target="#main-slider" data-slide-to="2"></li>
		  </ol>
		  <div class="carousel-inner">
			 <div class="item active img-responsive" style="background-image: url(img/empresas/slider/bg1.jpg)">
				<div class="container">
				  <div class="row">
					 <div class="col-sm-3"></div>
					 <div class="col-sm-6">
						<div class="caro centrado text-center">
						  <h3>Encuentra al postulante idónea para tu empresa</h3>
						  <a class="boton" href="#" role="button">Publicar Aviso</a>
						</div>
					 </div>
					 <div class="col-sm-3"></div>
				  </div>
				</div>
			 </div>
			 <div class="item img-responsive" style="background-image: url(img/empresas/slider/bg2.jpg)">
				<div class="container">
				  <div class="row">
					 <div class="col-sm-3"></div>
					 <div class="col-xs-12 col-sm-6">
						<div class="caro centered text-center">
						  <h3>Gestiona tu Proceso de Selección</h3>
						  <a class="boton" href="#" role="button">Publicar Aviso</a>
						</div>
					 </div>
					 <div class="col-sm-3"></div>
				  </div>
				</div>
			 </div>
			 <div class="item img-responsive" style="background-image: url(img/empresas/slider/bg3.jpg)">
				<div class="container">
				  <div class="row">
					 <div class="col-sm-3"></div>
					 <div class="col-sm-6">
						<div class="caro centered text-center">
						  <h3>En aquiempleos.com encontrarás a los mejores profesionales.</h3>
						  <a class="boton" href="#" role="button">Publicar Aviso</a>
						</div>
					 </div>
					 <div class="col-sm-3"></div>
				  </div>
				</div>
			 </div>
		  </div>
		</div>
		<!--CAROUSEL FLECHAS-->
		<a class="prev hidden-xs" href="#main-slider" data-slide="prev"><i class="icon-angle-left"></i></a>
		<a class="next hidden-xs" href="#main-slider" data-slide="next"><i class="icon-angle-right"></i></a>
	 </section>
	 <section class="points">
	  <div class="container">
		<div class="row text-center">
		  <div class="points-text">
			 <div class="col-xs-12 col-sm-12 col-md-4">
				<img class="" src="img/empresas/a.png" alt="">
				<p class="azul pd-rl-30">Más de 20,580 postulantes</p>
			 </div>
			 <div class="col-xs-12 col-sm-12 col-md-4">
				<img class="responsive-img" src="img/empresas/b.png" alt="">
				<p class="azul pd-rl-30">Más de 5,320 CVs mensuales</p>
			 </div>
			 <div class="col-xs-12 col-sm-12 col-md-4">
				<img class="responsive-img" src="img/empresas/c.png" alt="">
				<p class="azul pd-rl-30">Más de 38,719 visitas mensuales</p>
			 </div>
		  </div>
		</div>
	  </div>
	 </section>
	 <section class="conoce">
		<div class="container text-center">
		  <div class="row">
			 <div class="col-xs-12 col-md-12">
				<h1 class="azul">Conoce nuestros productos y elige el mejor</h1>
			 </div>
		  </div>
		  <div class="row">
			 <div class="col-xs-12 col-sm-12 col-md-6">
				<div class="box-two pd-10 mg-b-40">
				  <p class="title">
				  Aviso Web
				  </p>
				  <div class="row">
					 <div class="col-xs-12 col-sm-6 col-md-6">
						<img class="img-responsive img-r-position" src="img/empresas/a-web.png" alt="">
					 </div>
					 <div class="col-xs-12 col-sm-6 col-md-6">
						<p class="conoce-parrafo pd-20">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem quam beatae, officia temporibus consequuntur quia corrupti minus rerum harum saepe.</p>
						<button class="buttom-blue">Publicar</button>
					 </div>
				  </div>
				</div>
			 </div>
			 <div class="col-xs-12 col-sm-12 col-md-6">
				<div class="box-two pd-10">
				  <p class="title">
				  Aviso Web + Impreso
				  </p>
				  <div class="row">
					 <div class="col-xs-12 col-sm-6 col-md-6">
						<img class="img-responsive img-r-position" src="img/empresas/a-web-impreso.png" alt="">
					 </div>
					 <div class="col-xs-12 col-sm-6 col-md-6">
						<p class="conoce-parrafo pd-20">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem quam beatae, officia temporibus consequuntur quia corrupti minus rerum harum saepe.</p>
						<button class="buttom-blue">Publicar</button>
					 </div>
				  </div>
				</div>
			 </div>
		  </div>
		</div>
	 </section>
	 <section class="clientes">
		<div class="container text-center">
		  <div class="row">
			 <div class="col-xs-12 col-sm-12">
				<h1 class="clientes-titulo blanco">Conoce a nuestros Clientes</h1>
			 </div>
		  </div>
		  <div class="row">
			 <div class="responsive slider">
				<div>
				  <img src="img/empresas/cliente-a-demo.png">
				</div>
				<div>
				  <img src="img/empresas/cliente-b-demo.png">
				</div>
				<div>
				  <img src="img/empresas/cliente-b-demo.png">
				</div>
				<div>
				  <img src="img/empresas/cliente-a-demo.png">
				</div>
				<div>
				  <img src="img/empresas/cliente-b-demo.png">
				</div>
				<div>
				  <img src="img/empresas/cliente-b-demo.png">
				</div>
			 </div>
		  </div>
		  <div class="row">
			 <div class="col-md-12 text-center">
				  <picture>
					 <source
						media="(min-width: 650px)"
						class="diagrama img-responsive"
						srcset="img/empresas/diagrama-de-flujo.png">
					 <source
						media="(min-width: 465px)"
						class="diagrama img-responsive"
						srcset="img/empresas/diagrama-de-flujo2.png">
					 <img
						class="diagrama img-responsive"
						src="img/empresas/diagrama-de-flujo2.png"
						alt="Nuestros Servicios">
				  </picture>
			 </div>
		  </div>
		</div>
	 </section>
	 <section class="publica">
		<div class="container">
		  <div class="row text-center">
			 <div class="col-md-6">
				<h2 class="publica-text azul">No pierdas la oportunidad de<br> Publicar un Aviso</h2>
			 </div>
			 <div class="col-md-6 pd-tp-10">
				<button class="button-accion">Publicar Aviso</button>
			 </div>
		  </div>
		</div>
	 </section>
	 <footer>
		<div class="container-fluid">
		  <div class="footer"></div>
		</div>
		<div class="container-fluid">
		  <div class="row width">
				<div class="col-xs-12 col-sm-6 col-md-3">
					 <div class="logo-footer">
						<img src="img/empresas/logo_empleobusco-footer.svg">
					 </div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-3">
					 <div class="text-center">
						<div class="valores">
						  <h3>¿Qué es AquiEmpleos?</h3>
						  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. Suspendisse urna nibh, viverra non, semper suscipit.
						  </p>

						  <h3 >Síguenos</h3>
						  <div class="social-media-footer">
								<a href=""><i class="fa fa-facebook" aria-hidden="true"></i></a>
								<a href=""><i class="fa fa-twitter" aria-hidden="true"></i></a>
						  </div>
						</div>
					 </div>
				</div>
				<div class="col-xs-12 col-sm-12 col-md-6">
					 <div class="valores-dos text-right">
						<div class="enlaces">
						  <a href="#">Suscribete</a>
						  <a href="#">Publica tu aviso</a>
						  <a href="#">Regístrate</a>
						  <input type="button" value="Ingresa" class="button-ingresa">
						</div>
						<div class="text-left">
						  <h3>Busca entre más de 84,000 avisos</h3>
						  <input placeholder="Buscar por distrito, descripción o código" class="footer-input-busqueda">
						</div>
						<button class="fot-btn-buscar">Buscar</button>
					 </div>
				</div>
		  </div>
		  <div class="row width">
			 <div class="text-center copyright">
				<p>&copy; Copyright 2016 - All Rights Reservered</p>
			 </div>
		  </div>
		</div>
	 </footer>
	 <script src="js/jquery.js"></script>
	 <script src="js/bootstrap.min.js"></script>
	 <script src="./slick/slick.js" type="text/javascript" charset="utf-8"></script>
	 <script src="js/main.js"></script>

  </body>
</html>
