<div class="all">
	<h2>Nombre: <?= $this->nombres.' '.$this->apellidos ?></h2>
	<div class="legend history">
	<?php if ($this->activo != 0) {?>
	<a href="#winAlertBloquearPost" class="blockAdmEMP pos winModal" rel="<?= $this->idPostulante ?>">Bloquear</a> &nbsp;
	<a class="enviarMensaje winModal" href="#winAnadirMensaje" rel="<?=$this->idPostulante ?>" >Enviar mensaje</a>
	<?php } else {?>
	<a href="#winAlertBloquearPost" class="desblockAdmEMP pos winModal" rel="<?= $this->idPostulante ?>">Desbloquear</a> &nbsp;
	<?php } ?>
	<a href="<?= $this->urlvolver ?>" class="f14 right" id="backToProcess" >&laquo; Volver</a>
	
	</div>
	
</div>

