<div id="modalRegisterUser" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close modal-home-postulante-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="box-modal">
                    <div class="text-center">
                        <img src="<?= $this->S('/eb/img/modal/login/ico-cuenta.svg'); ?>" alt="" class="img-ico-cuenta">
                    </div>   
                    <div class="container little-box-bg">
                        <div class="row">
                            <div class="col-md-12 text-center box-title">
                                <span class="title">Crear tu cuenta</span>
                            </div>
                            <div class="text-center parrafo">
                                <img src="<?= $this->S('/eb/img/modal/registro/square.png'); ?>" alt="">
                                <span>Regístrate y descubre cómo puedes obtener el empleo ideal para ti</span>
                            </div>
                            <form role="form" id="contactForm"  method="post">
                                <div class="row pd-5">
                                    <div class="col-md-6 text-center">
                                        <div class="controls">
                                            <?=
                                            $this->formRegistroRapido->txtName->setAttribs(array(
                                                'class' => 'form-control-modal-r registro',
                                                'placeholder' => 'Nombre',
                                                'required' => ''))->renderViewHelper();
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-md-6 text-center">
                                        <div class="controls">
                                            <?=
                                            $this->formRegistroRapido->txtFirstLastName->setAttribs(array(
                                                'class' => 'form-control-modal-r registro',
                                                'placeholder' => 'Apellido Paterno',
                                                'required' => ''))->renderViewHelper();
                                            ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row pd-5">
                                    <div class="col-md-6 text-center">
                                        <div class="controls">
<?=
$this->formRegistroRapido->txtSecondLastName->setAttribs(array(
    'class' => 'form-control-modal-r registro',
    'placeholder' => 'Apellido Materno',
    'required' => ''))->renderViewHelper();
?>
                                        </div>
                                    </div>
                                    <div class="col-md-6 text-center">
                                        <div class="controls">

                                            
                                              
                                                    <div class='input-group date' id='datetimepicker4'>
                                                        <?=
                                                        $this->formRegistroRapido->txtBirthDay->setAttribs(array(
                                                            'class' => 'form-control-modal-r',
                                                            'type' => 'text',
                                                            'placeholder' => 'Fecha de Nacimiento'
                                                        ))->renderViewHelper();
                                                        ?>
                                                        <span class="input-group-addon"><span class="glyphicon glyphicon-time"></span>
                                                        </span>
                                                    </div>
                                              
                                           
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="row pd-5">
                                    <div class="col-md-12 text-center">
                                        <div class="controls">
<?=
$this->formRegistroRapido->txtEmail->setAttribs(array(
    'id' => 'txtEmail',
    'class' => 'form-control-modal-r user',
    'placeholder' => 'Email',
    'required' => ''))->renderViewHelper();
?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row pd-5">
                                    <div class="col-md-6 text-center">
                                        <div class="controls">
<?=
$this->formRegistroRapido->pswd->setAttribs(
    array(
        'class' => 'form-control-modal-r',
        'placeholder' => 'Contraseña',
        'required' => ''))->renderViewHelper();
?>
                                        </div>
                                    </div>
                                    <div class="col-md-6 text-center">
                                        <div class="controls">
<?=
$this->formRegistroRapido->pswd2->setAttribs(
    array(
        'id' => 'pswd2',
        'class' => 'form-control-modal-r',
        'placeholder' => 'Confirme su Contraseña',
        'required' => ''))->renderViewHelper();
?>                                   
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 text-left condiciones">
                                    <span>Al crear una cuenta aceptas estar de acuerdo con nuestras</span><a href=""> políticas de privacidad, términos y condiciones</a>
                                </div> 
                                <div class="row pd-5">
                                    <div class="col-md-6 text-center">
<?php
$redirect_uri  = $this->layout()->urlAuthAppFacebook;
$redirecFormFB = $this->layout()->loginFormNew->returnFB->getValue();
if ($redirecFormFB != '/mi-cuenta') {
    $redirect_uri .= '/go/'.$redirecFormFB;
}
?>
                                        <button id="registroF" type="button" class="ingresar-facebook" 
                                               data-src="<?= $this->layout()->facebook; ?>">
                                            <i class="fa fa-facebook" aria-hidden="true"></i>
                                            <span class="btn_label-face-registro">Registrar</span>
                                        </button>
                                    </div>
                                    <div class="col-md-6 text-center">
<?= $this->formRegistroRapido->auth_token->renderViewHelper(); ?>
                                        <button id="registroP" type="button" class="ingresar">
                                            <span class="btn_label">Crea tu cuenta</span>
                                        </button>
                                    </div>
                                </div>
                                <!--                    <div class="col-md-12 text-center registrate">
                                                        <span class="no-cuenta">¿Ya te encuentras registrado?</span><a href="">Ingresa aquí</a>
                                                    </div>-->
                            </form>
                            <div class="errorMesajes"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>