<div id="modalLoginUser" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close modal-home-postulante-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div  class="box-modal"  >
                    <div class="text-center">
                        <img src="<?= $this->S('/eb/img/modal/login/ico-cuenta.svg'); ?>" alt="" class="img-ico-cuenta">
                    </div>
                    <div class="container little-box-bg">
                        <div class="row">
                            <div class="col-md-12 text-center">
                                <span class="title">Accede a tu cuenta</span>
                            </div>
                            <div class="col-md-12">
                                <form role="form" id="frmUserLogIn" autocomplete="off"  action="<?=
                                $this->url(array(
                                    'module' => MODULE,
                                    'controller' => 'mi-cuenta',
                                    'action' => 'index'))
                                ?>">
                                    <div class="control-group">
                                        <label class="control-label" for="email"></label>
                                        <div class="controls">
                                                <!--<input type="text" id="email" name="email de usuario" class="form-control user" placeholder="Email">-->
                                            <?=
                                            str_replace('type="text"',
                                                'type="email"',
                                                $this->loginFormNew->txtUser->setAttribs(array(
                                                    'id' => 'emailPersonalizado',
                                                    'class' => 'form-control form-login email',
                                                    'placeholder' => 'Email',
                                                    'required' => ''))->renderViewHelper());
                                            ?>
                                        </div>
                                    </div>
                                    <div class="control-group">
                                        <label class="control-label" for="password"></label>
                                        <div class="controls">
                                                <!--<input type="password" id="password" name="Apellido de usuario" class="form-control password" placeholder="Contraseña">-->
                                            <?=
                                            $this->loginFormNew->txtPasswordLogin->setAttribs(array(
                                                'id' => 'txtPasswordLogin',
                                                'class' => 'form-control form-login password',
                                                'required' => '',
                                                'placeholder' => 'Contraseña'
                                            ))->renderViewHelper();
                                            ?>
                                        </div>
                                    </div>
                                    <div class="col-md-12 text-left help-password">
                                        <a href="">he olvidado mi contraseña</a>
                                    </div>
                                    <?php //= //$this->loginFormNew->chkRemember->setAttribs(array())->renderViewHelper();  ?>
                                    <?=
                                    $this->loginFormNew->tipo->setAttribs(array(
                                        'id' => 'chkTipo'))->renderViewHelper();
                                    ?>
                                    <?= $this->loginFormNew->hidAuthToken->renderViewHelper(); ?>
                                    <?=
                                    isset($this->layout->question) ? '<input type="hidden" name="question" value="'.$this->layout->question.'">'
                                            : ''
                                    ?>

                                    <?php
                                    $redirect_uri  = $this->layout()->urlAuthAppFacebook;
                                    $redirecFormFB = $this->loginFormNew->returnFB->getValue();
                                    if ($redirecFormFB != '/mi-cuenta') {
                                        $redirect_uri .= '/go/'.$redirecFormFB;
                                    }
                                    ?>
                                    <div class="col-md-12 text-center help-password">
                                        <button id="loginP" name="loginP" type="button" class="ingresar">
                                            <span class="btn_label">Ingresar</span>
                                        </button>
                                    </div>
                                    <div class="errorMesajes"></div>
                                </form>
                            </div>
                            <div class="col-md-12 text-center">
                                <label class="checkbox">
                                    <input id="chkRemember" type="checkbox" class="check-in"id="terms-and-conditions" name="chkRemember"/>
                                    <small class="password-remind">Recordar mi contraseña
                                    </small>
                                </label>
                            </div>
<?php if (MODULE == 'postulante') { ?>
                                <div class="col-md-12 text-center">
                                    <button id="loginP" type="submit" class="ingresar-facebook" data-src="<?= $this->layout()->facebook; ?>"
                                            >

                                        <i class="fa fa-facebook" aria-hidden="true"></i>
                                        <span class="btn_label-face">Ingresar con Facebook</span>
                                    </button>
                                </div>
<?php } ?>
                            <div class="col-md-12 text-center registrate">
                                <span class="no-cuenta">¿No tienes cuenta?</span><a href="<?=$this->Menus()->linkRegistro();?>" data-toggle="modal" > Regístrate</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>