<div class="modal fade page_modal recover_password_modal" tabindex="-1" role="dialog" id="modalMsg">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title modal-recuperar-contra-title"></h4>
            </div>
            <div class="modal-body">
                <label>
                    Actualmente estás logueado como Postulante. Ingresa como Empresa para poder Publicar Avisos
                </label>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

