<div class="modal fade page_modal recover_password_modal" tabindex="-1" role="dialog" id="modalMsgSoyEmpresa">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title modal-recuperar-contra-title"></h4>
            </div>
            <div class="modal-body">
            <button type="button" class="close modal-home-postulante-close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <label>
                    ¿Desea logearse como empresa?
                </label>
                <div>
                    <a class=" btn btn-sesion" href="/logout">Aceptar</a>
                    <a class=" btn btn-sesion" data-dismiss="modal">Cerrar</a>
                </div>
            </div>
            <br>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

