<div class="page_modal hide fast_register_modal" id="modalRegisterUser" >
   <div class="title align_center"><span>Crear cuenta</span><i class="icon icon_cross"></i></div>
   <form id="frmUserRegistrationFast" class="type1" method="post">
      <h2>Regístrate y descubre cómo puedes obtener el empleo ideal para ti</h2>
      <div class="form_box border_grey">
         <div class="form_row">
            <div class="form_col6">
               <fieldset>
               <label>Nombre</label>
               <?=$this->formRegistroRapido->txtName->setAttribs(array('placeholder'=>'','required'=>''))->renderViewHelper();?>
                  </fieldset>
            </div>   
            <div class="form_col6">
               <fieldset>
               <label>Apellido Paterno</label>
               <?=$this->formRegistroRapido->txtFirstLastName->setAttribs(array('placeholder'=>'','required'=>''))->renderViewHelper();?>
               </fieldset>
            </div>
         </div>
         <div class="form_row">
            <div class="form_col6">
               <fieldset>
               <label>Apellido Materno</label>
               <?=$this->formRegistroRapido->txtSecondLastName->setAttribs(array('placeholder'=>'','required'=>''))->renderViewHelper();?>
               </fieldset>
            </div>
            <div class="form_col6">
               <fieldset>
               <label>Fecha de Nacimiento</label>
               <?php $min_edad = Application_Form_RegistroRapidoPostulante::MIN_EDAD; ?>
               <?=$this->formRegistroRapido->txtBirthDay->setAttribs(array('minyear'=>date('Y')-100, 'maxyear'=>date('Y') - $min_edad,'placeholder'=>'dd/mm/yyyy','required'=>'', 'type'=>'text'))->renderViewHelper();?>
               </fieldset>
            </div>            
         </div>
         <div class="form_row">
            <div class="form_col12">
               <fieldset>
               <label>Email</label>
               <?= str_replace('type="text"', 'type="email"', $this->formRegistroRapido->txtEmail->setAttribs(array('placeholder'=>'','required'=>'' ))->renderViewHelper());?>
               </fieldset>
            </div>
         </div>
         <div class="form_row">
            <div class="form_col6">
               <fieldset>
               <label>Contraseña</label>
               <?=$this->formRegistroRapido->pswd->setAttribs(array('placeholder'=>'','required'=>''))->renderViewHelper();?>
               </fieldset>
            </div>
            <div class="form_col6">
               <fieldset>
               <label>Confirmar Contraseña</label>
               <?=$this->formRegistroRapido->pswd2->setAttribs(array('placeholder'=>'','required'=>''))->renderViewHelper();?>                                   
               </fieldset>
            </div>   
         </div>
      </div>
      <div class="row mt7">
         <?= $this->formRegistroRapido->auth_token->renderViewHelper() ?>
         <span class="conditions">Al crear una cuenta aceptas estar de<br>acuerdo con nuestras <a href="http://centraldeayuda.trabajobusco.com/forums/20710432-Terminos-y-Condiciones-de-trabajo-busco" class="type_white" target="_blank">políticas de privacidad, términos y condiciones</a></span>
         <button class="btn btn_tertiary" onClick="ga('send', 'event', 'registro','crea_tu_cuenta', 'registro_home');"><span class="btn_label">Crea tu cuenta</span><span class="btn_spinner"></span></button>
      </div>
   </form>

   <?php                  
   $redirect_uri  =  $this->layout()->urlAuthAppFacebook;  
   $redirecFormFB = $this->layout()->loginFormNew->returnFB->getValue();                     
            if ($redirecFormFB!='/mi-cuenta') {                       
                $redirect_uri .= '/go/'. $redirecFormFB;
            }
   ?>
   <a href="http://www.facebook.com/v2.0/dialog/oauth?client_id=<?= $this->layout()->AppFacebook->appid ?>&redirect_uri=<?=$redirect_uri;?>&scope=email&state=<?=$this->tokenFacebook?>" class="btn_social fb" onClick="ga('send','event','logueo','home','loguearse_facebook');"><span class="logo"></span><span class="name">Conéctate</span> con Facebook<i class="icon icon_arrow_right"></i></a>
   <p class="row_modal_box">¿Ya te encuentras registrado? <a href="#">Ingresa aquí</a></p>
</div>