<div class="page_modal hide fast_login_modal" id="modalLoginUser" >
   <div class="title align_center"><span>Accede a tu cuenta</span><i class="icon icon_cross"></i></div>
   <form action="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'index'))?>" class="type1" id="frmUserLogIn">
      <div class="form_box border_grey">
         <div class="form_row">
            <div class="form_col12">
               <fieldset>
                  <label>Email</label>
                  <?= str_replace('type="text"', 'type="email"',$this->loginFormNew->txtUser->setAttribs(array('id' => 'txtUser','size'=>'50','required'=>''))->renderViewHelper());?>
                  </fieldset>
            </div>
         </div>
         <div class="form_row">
            <div class="form_col12">
               <fieldset>
               <label>Contraseña</label>
               <?=$this->loginFormNew->txtPasswordLogin->setAttribs(array('id' => 'txtPasswordLogin','size'=>'50','required'=>''))->renderViewHelper();?>
               </fieldset>
            </div>   
         </div>
      </div>
      <button class="btn btn_tertiary mt10"><span class="btn_label">Ingresar</span><span class="btn_spinner"></span></button>
      <p class="mt10"><a href="#modalRecoverPassword" class="fancybox type_white recover_init">Olvidé mi contraseña</a></p>
      <label for="" class="ioption">Recordar mi contraseña
         <?=$this->loginFormNew->chkRemember->setAttribs(array())->renderViewHelper();?>
         <?=$this->loginFormNew->tipo->setAttribs(array('id'=>'chkTipo'))->renderViewHelper();?>
         <?=$this->loginFormNew->hidAuthToken->renderViewHelper();?>
         <?=isset($this->layout->question)?'<input type="hidden" name="question" value="'.$this->layout->question.'">':''?>
          
         <?php 
         $redirect_uri  =  $this->layout()->urlAuthAppFacebook;  
         $redirecFormFB = $this->loginFormNew->returnFB->getValue();                     
                if ($redirecFormFB!='/mi-cuenta') {                       
                    $redirect_uri .= '/go/'. $redirecFormFB;
                }
         ?>
      </label>
   </form>
   <a href="<?=$this->layout()->facebook;?>" class="btn_social fb"><span class="logo"></span>Ingresar con Facebook<i class="icon icon_arrow_right"></i></a>
   <p class="row_modal_box">¿No tienes cuenta? <a href="#">Regístrate</a></p>
</div>