<div class="contenedor-preload hideDiv">
	<div class="contenedor-hijo-preload">

			 <div class="load-bar">
			  <div class="bar"></div>
			  <div class="bar"></div>
			  <div class="bar"></div>
			</div>
		<div class="contenedor-preload-2">
			<div class="sk-cube-grid">
			  <div class="sk-cube sk-cube1"></div>
			  <div class="sk-cube sk-cube2"></div>
			  <div class="sk-cube sk-cube3"></div>
			  <div class="sk-cube sk-cube4"></div>
			  <div class="sk-cube sk-cube5"></div>
			  <div class="sk-cube sk-cube6"></div>
			  <div class="sk-cube sk-cube7"></div>
			  <div class="sk-cube sk-cube8"></div>
			  <div class="sk-cube sk-cube9"></div>
			</div>
		</div>
	</div>

</div>
