<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>	
    		<div class="gridTab">
		<div class="gridIT">
            <h5 class="h5TitleAdm">Módulo de Administración</h5>
            <?=$this->partial('_partials/_accion-adminEmpresa.phtml',array('razonsocial'=>$this->razonsocial,'empresaAdminUrl'=>$this->empresaAdminUrl,'activo'=>$this->activo,'idEmpresa'=>$this->idEmpresa))?>
            <div class="row">
                <div class="grids-2">
                    <?=$this->partial('mi-cuenta-empresa/_sidebar-menu.phtml',
                    array(
                        'menu_sel_side' => $this->menu_sel_side,
                        'rel' => $this->idEmpresa,
                        'rol' => $this->rol,
                        'membresiaTipo' => $this->membresiaTipo
                        )
                    )?>
                </div>
                <div class="grids-7">
                    <h2>Cambio de Clave</h2>
                    <form action="" method="post" id="frmChangePassword" class="frm-horizontal large" data-parsley-validate>
                        <?= $this->partial('mi-cuenta/_cambio_clave.phtml','postulante',array('formCambioClave'=>$this->formCambioClave)); ?>
                        <div class="txt_right">
                            <input type="submit" class="btn btn-primary" value="Guardar cambios">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>            
    </div>
        </div>
    </div>
