<div id="main" class="all empMiCuenM">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=
            $this->partial('_partials/_navigation.phtml',
                array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages" => $this->flashMessages))
            ?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <?=
                    $this->partial('_partials/_accion-adminEmpresa.phtml',
                        array(
                        'razonsocial' => $this->razonsocial,
                        'empresaAdminUrl' => $this->empresaAdminUrl,
                        'activo' => $this->activo,
                        'idEmpresa' => $this->idEmpresa
                        )
                    )
                    ?>
                    <div class="iAccount" id="innerMain">
                        <?=
                        $this->partial('mi-cuenta-empresa/_sidebar-menu.phtml',
                            array(
                            'menu_sel_side' => $this->menu_sel_side,
                            'rel' => $this->idEmpresa,
                            'rol' => $this->rol,
                            'membresiaTipo' => $this->membresiaTipo
                            )
                        );
                        ?>
                        <div id="gridTableR" class="blockAR alpha right">
                            <form action="" method="post" id="frmCompanyRegistration" enctype="multipart/form-data" class="frm-horizontal medium">
                                <h2>Datos de la empresa</h2>
                                <div class="wrap-controls">
                                    <?php echo $this->partial('registro-empresa/_usuario_paso1.phtml',
                                        'empresa',
                                        array('emailMicuenta' => $this->emailMicuenta, 'modulo' => $this->modulo, 'controlador' => $this->controlador));
                                    ?>
                                    <?php echo $this->partial('registro-empresa/_empresa_paso1.phtml',
                                        'empresa',
                                        array(
                                        'formEmpresa' => $this->frmEmpresa,
                                        'imgPhoto' => $this->imgPhoto,
                                        'config' => $this->config,
                                        'idEmpresa' => $this->idEmpresa,
                                        'modulo' => $this->modulo
                                        )
                                    );
                                    ?>
                                </div>
                                <h2>Ubicación</h2>
                                <div class="wrap-controls">
                                    <?=
                                    $this->partial('registro-empresa/_ubigeoEmpresa_paso1.phtml',
                                        'empresa',
                                        array('formEmpresa' => $this->frmEmpresa));
                                    ?>
                                </div>
                                <div class="txt_right">
                                    <button type="submit" id="btnCompanyRegister" class="btn btn-primary input-xsmall">Guardar Cambios</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
