<div class="bgAll gridS20">
	<div class="gridForm">
		<div class="legend">
			<a href="<?=$this->url(array('controller'=>'home','action'=>'index'),false,true)?>">Inicio</a> » <span class="noLink">Publica un aviso</span>
		</div>
		<h2 class="titleOrig">Datos del puesto</h2>
		<blockquote id="modStepsForm"><img src="<?= $this->S('/images/empresa/avisoPaso2.jpg'); ?>" alt="Paso 2" /></blockquote>
		<div class="gridIFormEmp resG">
			<div id="innerMain">
				<div id="content" class="formRegister">
					<div id="cntEmpRelF">
						<h2 id="titleRelF" class="titleInDB left mB0">Datos del puesto</h2>
						<p id="infoRelF" class="alignR txtReq right bold">Los datos con <span class="req">*</span> son obligatorios</p>
					</div>
					<form action="" id="frmPublishAd" method="post">
					<?php if (isset($this->back)) : ?>
					<input type="hidden" value="true" name="back" />
					<?php endif; ?>
					<?php echo $this->partial('_partials/_paso2_aviso.phtml', 'empresa', 
					    array(
					    'form' => $this->form, 'isDato' => $this->isDato, 'online' => $this->online, 
					    'numPalabraPuesto' => $this->numPalabraPuesto,
	                    'numPalabraOtroNombre' =>$this->numPalabraOtroNombre,
					    'formEstudio' => $this->formEstudio, 'managerEstudio'=> $this->managerEstudio, 'isEstudio' => $this->isEstudio, 'isEditarEstudio' => $this->isEditarEstudio,
					    'formOtroEstudio' => $this->formOtroEstudio, 'managerOtroEstudio'=> $this->managerOtroEstudio, 'isOtroEstudio' => $this->isOtroEstudio, 'isEditarOtroEstudio' => $this->isEditarOtroEstudio,
					    'formExperiencia' => $this->formExperiencia, 'managerExperiencia'=> $this->managerExperiencia, 'isExperiencia' => $this->isExperiencia, 'isEditarExperiencia' => $this->isEditarExperiencia, 
					    'formIdioma' => $this->formIdioma, 'managerIdioma'=> $this->managerIdioma, 'isIdioma' => $this->isIdioma, 'isEditarIdioma' => $this->isEditarIdioma,
					    'formPrograma' => $this->formPrograma, 'managerPrograma'=> $this->managerPrograma, 'isPrograma' => $this->isPrograma, 'isEditarPrograma' => $this->isEditarPrograma,
					    'formPregunta' => $this->formPregunta, 'managerPregunta'=> $this->managerPregunta, 'isPregunta' => $this->isPregunta, 'isEditarPregunta' => $this->isEditarPregunta, 'frmUbigeo' => $this->frmUbigeo
					    )
				    ); ?>
			    	<div class="wrap-btn right mT20"> 
                		<span id="msgErrorStep2" class="response error"></span>
                        <input id="aSetep2" class="btn btn-primary" type="submit" value="Continuar >>"/> 
                	</div>
    				</form>
    				<?php echo $this->partial('_partials/_paso2_aviso_blank.phtml', 'empresa', 
					    array(
					    'managerEstudio'=> $this->managerEstudio,
					    'managerOtroEstudio'=> $this->managerOtroEstudio,
					    'managerExperiencia'=> $this->managerExperiencia, 
					    'managerIdioma'=> $this->managerIdioma,
					    'managerPrograma'=> $this->managerPrograma,
					    'managerPregunta'=> $this->managerPregunta,
					    )
				    ); ?>
				</div>
			</div>
		</div>
	</div>
</div>

