<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=
            $this->partial('_partials/_navigation.phtml', 'admin',
                array('isAuth' => $this->isAuth, 'auth' => $this->auth, "flashMessages" => $this->flashMessages))
            ?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>    
                    <?=
                    $this->partial('_partials/_accion-adminAviso.phtml',
                        'admin',
                        array('puesto' => $this->puesto, 'avisoAdminUrl' => $this->avisoAdminUrl,
                        'estado' => $this->estado,
                        'idAviso' => $this->idAviso))
                    ?>
                    <div id="avisoAdmin">
                        <!-- Inicio Form -->
                        <h2 class="titleOrig">Datos del puesto</h2>
                        <div class="gridIFormEmp resG">
                            <div id="innerMain">
                                <div id="content" class="formRegister">
                                    <form action="" id="frmPublishAd" method="post" class="frm-horizontal">
                                        <div id="basicDataF">
                                        
                                        <?php
                                        echo $this->partial('_partials/_paso2_aviso.phtml',
                                            'admin',
                                            array(
                                            'form' => $this->form,
                                            'isDato' => $this->isDato,
                                            'numPalabraPuesto' => $this->numPalabraPuesto,
                                            'numPalabraOtroNombre' => $this->numPalabraOtroNombre,
                                            'modulo' => $this->modulo,
                                            'nombreComercial' => $this->nombreComercial,
                                            'formEstudio' => $this->formEstudio,
                                            'managerEstudio' => $this->managerEstudio,
                                            'isEstudio' => $this->isEstudio,
                                            'isEditarEstudio' => $this->isEditarEstudio,
                                            'formOtroEstudio' => $this->formOtroEstudio,
                                            'managerOtroEstudio' => $this->managerOtroEstudio,
                                            'isOtroEstudio' => $this->isOtroEstudio,
                                            'isEditarOtroEstudio' => $this->isEditarOtroEstudio,
                                            'formExperiencia' => $this->formExperiencia,
                                            'managerExperiencia' => $this->managerExperiencia,
                                            'isExperiencia' => $this->isExperiencia,
                                            'isEditarExperiencia' => $this->isEditarExperiencia,
                                            'formIdioma' => $this->formIdioma,
                                            'managerIdioma' => $this->managerIdioma,
                                            'isIdioma' => $this->isIdioma, 'isEditarIdioma' => $this->isEditarIdioma,
                                            'formPrograma' => $this->formPrograma,
                                            'managerPrograma' => $this->managerPrograma,
                                            'isPrograma' => $this->isPrograma,
                                            'isEditarPrograma' => $this->isEditarPrograma,
                                            'formPregunta' => $this->formPregunta,
                                            'managerPregunta' => $this->managerPregunta,
                                            'isPregunta' => $this->isPregunta,
                                            'isEditarPregunta' => $this->isEditarPregunta,
                                            'frmUbigeo' => $this->frmUbigeo
                                            )
                                        );
                                        ?>
                                        <div class="wrap-btn right mT20"> 
                                            <span id="msgErrorStep2" class="response error"></span>
                                            <input id="aSetep2" class="btn btn-primary" type="submit" value="Continuar >>"/> 
                                        </div>                                        
                                        </div>
                                    </form>
                                    <?php
                                    echo $this->partial('_partials/_paso2_aviso_blank.phtml',
                                        'admin',
                                        array(
                                        'managerEstudio' => $this->managerEstudio,
                                        'managerOtroEstudio' => $this->managerOtroEstudio,
                                        'managerExperiencia' => $this->managerExperiencia,
                                        'managerIdioma' => $this->managerIdioma,
                                        'managerPrograma' => $this->managerPrograma,
                                        'managerPregunta' => $this->managerPregunta,
                                        )
                                    );
                                    ?>
                                </div>
                            </div>
                            <!-- Fin Form -->
                        </div>
                    </div>
                </div>            
            </div>
        </div>
    </div>
</div>







