<div class="control-group">
    <label for="cbotipo" class="control-label"><em>*</em> Tipo de membresía:</label>
    <div class="controls">
        <?=$this->frmMembresia->cbotipo->setAttribs(array('class'=>'sel-xsmall', 'required'=>'', 'data-parsley-trigger'=>'change'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="id_membresia" class="control-label"><em>*</em> Membresía:</label>
    <div class="controls">
        <?=$this->frmMembresia->id_membresia->setAttribs(array('class'=>'sel-xsmall', 'required'=>'', 'data-parsley-trigger'=>'change'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="txtcontrato" class="control-label"><em>*</em> Contrato:</label>
    <div class="controls">
        <?=$this->frmMembresia->txtcontrato->setAttribs(array('class'=>'input-xsmall','maxlength' => '10', 'data-parsley-required'=>'true', 'data-parsley-trigger'=>'change', 'data-parsley-type'=>'alphanum'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="txtfecini" class="control-label"><em>*</em> Fecha Inicio:</label>
    <div class="controls">
        <?=$this->frmMembresia->txtfecini->setAttribs(array('class'=>'input-xsmall', 'required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-pattern'=>'^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="txtfecfin" class="control-label"><em>*</em> Fecha Fin:</label>
    <div class="controls">
        <?=$this->frmMembresia->txtfecfin->setAttribs(array('class'=>'input-xsmall', 'required'=>'', 'data-parsley-trigger'=>'change', 'data-parsley-pattern'=>'^[0-9]{2}\/[0-9]{2}\/[0-9]{4}$'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="txtmonto" class="control-label"><em>*</em> Monto Inicial (<?php echo $this->moneda?>):</label>
    <div class="controls">
        <?=$this->frmMembresia->txtmonto->setAttribs(array('class'=>'input-xsmall decimal','readonly'=>'readonly', 'required'=>'', 'data-parsley-trigger'=>'change'))->renderViewHelper(); ?>
    </div>
</div>
<div class="control-group">
    <label for="cboestado" class="control-label"><em>*</em> Estado:</label>
    <div class="controls">
        <?=$this->frmMembresia->cboestado->setAttribs(array('class'=>'sel-xsmall', 'required'=>'', 'data-parsley-trigger'=>'change'))->renderViewHelper(); ?>
    </div>
</div>
<?=$this->frmMembresia->tok->renderViewHelper(); ?>
