<div id="main" class="all">
  <div class="innerAll">
    <div class="bgAll gridS20">
      <?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages"=>$this->flashMessages)) ?>
      <div class="gridTab">
        <div class="gridIT">
            <h5 class="h5TitleAdm">Módulo de Administración</h5>
            <?=$this->partial('_partials/_accion-adminEmpresa.phtml',array('razonsocial'=>$this->razonsocial,'empresaAdminUrl'=>$this->empresaAdminUrl,'activo'=>$this->activo,'idEmpresa'=>$this->idEmpresa))?>
            <div class="iAccount" id="innerMain">
                <?=$this->partial('mi-cuenta-empresa/_sidebar-menu.phtml',
                    array(
                    	'menu_sel_side' => $this->menu_sel_side,
                    	'rel' => $this->idEmpresa,
                    	'rol' =>$this->rol,
                    	'membresiaTipo' => $this->membresiaTipo
                    )
                )?>
                <div class="blockAR grid15 alpha right">
                    <div class="iBlockAR">
                        <input type="hidden" name="txturlimageC" id="txturlimageC" value="<?php echo $this->S('/images/calendar.png')?>"></input>
                        <div id="titleyBtn">
                            <h2 class="titleMAU">Membresía de la empresa</h2>
                        </div>
                        <div class="txt_right mB20">
                            <?php
                                $activo = $this->activoMembresia; $classes = '';
                                
                                if(!$activo){
                                    $classes = 'href="javascript:;" class="btn btn-primary editMembAdmin"';
                                }else{
                                    $classes = 'href="javascript:;" class="btn btn-primary" disabled="disabled"';
                                }
                                
                                                           

                            ?>
                            <a id="btnAddMembresiaE" rel="" idEmp="<?= $this->idEmpresa ?>" <?php echo $classes; ?>>Añadir Membresía</a>
                            <span id="msgErrorDef" class="right error"></span>
                        </div>
                        <div id="divAjaxMembEmp">
                            <?php echo $this->partial('membresia-empresa/lista-membresias.phtml','empresa',array('membresiasEmp'=>$this->membresiasEmp,'rol' =>$this->rol,'idEmpresa'=>$this->idEmpresa)); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>