<form id="frmPosVirtual" class="frm-horizontal small">
    <h3>Finalización de pago</h3>            
    <?= $this->form->auth_token->renderViewHelper(); ?>
    <div class="control-group">
        <label class="control-label" for="txtVoucher">N° de Voucher: </label>
        <div class="controls">
            <?= $this->form->voucher->setAttribs(array(
                'data-parsley-trigger' => 'change',
                'data-parsley-required' => 'true',
                'data-parsley-type' => 'number',
                'data-parsley-minlength' => 5,
                'autocomplete' => 'off',
                'class' => 'input-xmedium number',
                'style' => 'width:200px',
                'maxlength' => 16,
                'id' => 'txtVoucher',                                               
            ))->renderViewHelper(); ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="txtPaymentDate">Fecha de Pago: </label>
        <div class="controls">                    
            <?= $this->form->payment_date->setAttribs(array(
                'data-parsley-trigger' => 'change',
                'data-parsley-required' => 'true',                        
                'data-parsley-date' => '',
                'readonly' => '',
                'autocomplete' => 'off',
                'class' => 'input-xmedium',
                'style' => 'width:200px; background-color: #fcfcfc',
                'maxlength' => 10,
                'id' => 'txtPaymentDate',                                               
            ))->renderViewHelper(); ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="txtPaymentDate">Tarjeta/Banco: </label>
        <div class="controls">
            <?= $this->form->banco->setAttribs(array(
                'class' => 'sel-xxsmall',
                'data-parsley-trigger' => 'change',
                'data-parsley-required' => 'true',
                'style' => 'width:220px'
            ))->renderViewHelper(); ?>
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="txtPaymentDate">Tipo: </label>
        <div class="controls">
            <?= $this->form->tarjeta->setAttribs(array(
                'class' => 'sel-xxsmall',
                'data-parsley-trigger' => 'change',
                'data-parsley-required' => 'true',
                'style' => 'width:220px'
            ))->renderViewHelper(); ?>                    
        </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="txtLote">N° de Lote: </label>
        <div class="controls">
            <?= $this->form->lote->setAttribs(array(
                'data-parsley-trigger' => 'change',
                'data-parsley-required' => 'true',                        
                'data-parsley-type' => 'number',
                'autocomplete' => 'off',
                'class' => 'input-xmedium number',
                'style' => 'width:200px',
                'maxlength' => 3,
                'id' => 'txtLote',                                               
            ))->renderViewHelper(); ?>                    
        </div>
    </div>

    <div class="txt_center">
        <button type="button" class="btn btn-default" id="btnCancel">Cancelar</button>
        <button type="submit" class="btn btn-primary" id="btnProcess">Procesar</button>
    </div>
</form>