<div id="modal_pago_satisfactorio" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">×
        </button>      
      </div>
      <div class="modal-body">        
        <?php echo $this->promoMsg ?>
      </div>
    </div>
  </div>
</div>