<? $active2 = "active"; ?>

    <div class="blockAL grid4 theta left">
        <h5 class="tituloPC r5T">Mantenimiento</h5>
        <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
        <?php if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || (
        	    $this->rol != Application_Form_Login::ROL_ADMIN_DIGITADOR && 
        	    $this->rol != Application_Form_Login::ROL_ADMIN_CALLCENTER &&
        	    $this->rol != Application_Form_Login::ROL_ADMIN_MODERADOR //&& $this->rol != Application_Form_Login::ROL_ADMIN_SOPORTE
        	    )
        	    ) { ?>
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_USUARIOS?$active2:''?>"><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'usuarios-admin'),"default",true)?>"><span class="sThird">Administradores</span></a></li>
        <?php }?>
            <li class="liThird liLast <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_CAMBIOCLAVE?$active2:''?>"><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'cambio-clave'),"default",true)?>"><span class="sThird">Cambio de clave</span></a></li>
        </ul>
        
        <h5 class="tituloPC r5T">Gestión</h5>
        <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
        	<?php if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || (
        	    $this->rol != Application_Form_Login::ROL_ADMIN_DIGITADOR && 
        	    $this->rol != Application_Form_Login::ROL_ADMIN_CALLCENTER) ) { ?>
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_POSTULANTES?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'postulantes'),"default",true)?>"><span class="sThird">Postulantes</span></a></li>
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_AVISOS?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'avisos'),"default",true)?>"><span class="sThird">Avisos</span></a></li>
            <li class="liThird <?= $this->menu_sel_side == App_Controller_Action_Admin::MENU_POST_SIDE_LISTAVISOS
                    ? $active2 : '' ?>"><a class="aThird" href="<?= $this->url(array(
                'module' => 'admin', 'controller' => 'gestion', 'action' => 'avisos-callcenter'),
                "default", true) ?>"><span class="sThird">Listado de Avisos</span></a></li>

            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_EMPRESAS?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'empresas'),"default",true)?>"><span class="sThird">Empresas</span></a></li>
            <?php }?>
            
            <?php if ($this->rol == Application_Form_Login::ROL_ADMIN_CALLCENTER || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_MASTER || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE
                  ) { ?>
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_CALLCENTER?$active2:''?>"><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'callcenter'),"default",true)?>"><span class="sThird">Call Center</span></a></li>
            <?php } ?>

            <?php if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_TESTIMONIOS
                  ) { ?>
            <li class="liThird <?= $this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_TESTIMONIOS?$active2:''?>" ><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'testimonios'),"default",true)?>"><span class="sThird">Testimonios</span></a></li>
            <?php } ?>

            <?php if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE || 
                      $this->rol == Application_Form_Login::ROL_ADMIN_EMPRESASPORTADA
                  ) { //Se desactiva la opción Empresa en Portada, porque esta opción ya no funciona de esa manera. ?>
            <li class="liThird liLast <?= $this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_EMPRESASPORTADA?$active2:''?>" ><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'gestion','action'=>'empresas-portada'),"default",true)?>"><span class="sThird">Empresas en Portada</span></a></li>
            <?php } ?>
        </ul>
       
        <? if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || 
               $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE 
               ) :?>
            <h5 class="tituloPC r5T">Trabaja con Nosotros</h5>
            <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
                <li class="liThird liLast <?=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_API_LISTARUSUARIO?$active2:''?>"><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'admin','controller'=>'api','action'=>'listar-usuarios'),"default",true)?>"><span class="sThird">Empresas</span></a></li>
<!--                <li class="liThird liLast <?//=$this->menu_sel_side==App_Controller_Action_Admin::MENU_POST_SIDE_API_AGREGARUSUARIO?$active2:''?>"><a class="aThird ie6Last" href="<?//=$this->url(array('module'=>'admin','controller'=>'api','action'=>'agregar-usuario'),"default",true)?>"><span class="sThird">Agregar Usuario</span></a></li>-->
            </ul>
        <? endif; ?>
        
    </div>

