 <div class="contenNotaEPA all">
	<h3 class="titleAPLR">Enviar Mensaje</h3>
 	<div class="iContenNotaEPA">
 		<form class="formDataNotaEPA">
	 		<div class="all cntNotaDataEPA" >
	 			<div class="left textAdjNotaEPA bold">Escribe aquí tu mensaje: </div>
	 			<div class="right cntActionsELP">
					<div class="actionsELP hide">					
                    <input type="hidden" class="idPoHidden" value="<?= $this->idPostulante ?>">
					</div>	 				
	 			</div>
	 		</div>
	 		<div class="all">
                        <?=$this->form->cuerpo->setAttribs(array('id'=>'areaMsjProEPA','class'=>'areaMsjProEPA'))->renderViewHelper(); ?>
            </div>
        	<div class="all">
	 			<div class="left">Te quedan <span id="cantMsjProEPA">300</span> caracteres</div>
                        <?= $this->form->token->renderViewHelper() ?>
                                <input class="btnPink btnSptEmp right submitSendHEPA" href="#" value="Guardar" id="guardarMensajeVerProceso" type="button"/>
	 		</div>
            <div id="msgErrorMensaje" class="error hide">*Debes Seleccionar un Archivo adjunto o Escribir una Nota.</div>
 		</form>
 	</div>	
 </div>