
<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml','admin',array('isAuth'=>$this->isAuth, "flashMessages"=>$this->flashMessages))?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <div class="iAccount" id="innerMain">
                    
                        <div id="admLeftNM" class="blockAL grid4 omega left">
                        <?=$this->partial('gestion/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rol' => $this->rol))?>
                        </div>
                        
                        <div class="blockAR alpha right blockFix">
                            <div class="iBlockAR">
                            <h2 class="titleMAU">Avisos Preferenciales Importados desde Impreso</h2>
                            <form action="" method="post" id="frmBuscar_avisosPreferenciales" class="r2 fieldsetAdm">
                              <div class="block">
                                <label for="fNomPuesto" class="labelN"> Nombre del Puesto:</label>
                                <?$hasError = $this->formAvisoPref->nom_puesto->hasErrors(); ?>
                                <?=$this->formAvisoPref->nom_puesto->setAttribs(array('id'=>'fNomPuesto','class'=>'fields inputN left replaceNbsp','tabindex'=>'6'))->renderViewHelper(); ?>
                                <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAvisoPref->nom_puesto->errMsg:''?></span>
                              </div>
                              
                              <div class="block">
                                <label for="fRuc" class="labelN"> Ruc:</label>
                                <?$hasError = $this->formAvisoPref->num_ruc->hasErrors(); ?>
                                <?=$this->formAvisoPref->num_ruc->setAttribs(array('id'=>'fRuc','class'=>'fields inputN left replaceNbsp','tabindex'=>'7'))->renderViewHelper(); ?>
                                <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAvisoPref->num_ruc->errMsg:""?> </span>
                              </div>
                              
                              <div class="block">
                                <label for="fBirthDate" class="labelN"> Fecha:</label>
                                <div class="blockBDC alignMeses left">
                                   <?$hasError = $this->formAvisoPref->fh_pub->hasErrors(); ?>
                                   <?  if ($hasError != 0){
                                    	$ErrorFecNac= $this->formAvisoPref->fh_pub->getErrors();
                                    	$errMsg = Application_Form_Paso1Postulante::$errorsFechaNac[$ErrorFecNac[0]];
                                    	} else{
                                    	$errMsg ='';
                                    	}	
                                    ?>
                                   <?=$this->formAvisoPref->fh_pub->setAttribs(array('id'=>'fBirthDate','class'=>'fields inputN iDateP datepicker left ready','tabindex'=>'7','readonly'=>'readonly'))->renderViewHelper(); ?>
									<select id="dayjFunctions" class="left"></select> 
									<select id="monthjFunctions" class="left"></select> 
									<select id="yearjFunctions" class="left"></select>                                                                                 
        						</div> 
                                <span class="response cGray left<?=$hasError?' bad':''?>"><?=$errMsg?> </span> 
                              </div>
                              
                              <div class="block">
                                <label for="fOrigen" class="labelN"> Origen:</label>
                                <?$hasError = $this->formAvisoPref->origen->hasErrors(); ?>
                                <?=$this->formAvisoPref->origen->setAttribs(array('id'=>'fOrigen','class'=>'fields inputN left','tabindex'=>'6'))->renderViewHelper(); ?>
                                <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAvisoPref->origen->errMsg:''?></span>
                              </div>
                              
                              <div class="block">
                              	<label class="labelN left" id="lblP3" for="optCheckP3">
                                <?=$this->formAvisoPref->tipobusq->setAttribs(array('id'=>'optCheckP3','class'=>'checkNI noBdr left'))->renderViewHelper(); ?>
                            	
                                Código Adecsys
                                </label>
                                <?$hasError = $this->formAvisoPref->cod_ade->hasErrors(); ?>
                                <?=$this->formAvisoPref->cod_ade->setAttribs(array('id'=>'fCodigoAdecsys','class'=>'fields inputN left replaceNbsp ','disabled'=>'disabled','tabindex'=>'6'))->renderViewHelper(); ?>
                              </div>

        						<div class="all">
        							<input id="fSendRS"  type="submit" class="active btnSptAdm sptAdm right" value="">
                                    <input id="fResetRS"  type="reset" class="active btnSptAdm sptAdm right" value="">
        						</div>
    						</form>
                			</div>
                			<?php if(isset($this->avisoPreferencialAdminUrl)) { ?>
                    <div class="gridYScroll">
                      <table summary="Administradores" id="dataAadmins" class="dataGrid">
                				<thead>
                				<?php $base = $this->avisoPreferencialAdminUrl ?>
                					<tr>
                						<th class="data1 titleGrid"></th>
                						<th class="data2 titleGrid linkTitleG">
                						<? $col = 'puesto' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                           <a href="<?=$url?>" class="rel relArrow">Puesto<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                           </th>
                						<th class="data3 titleGrid linkTitleG">
                						<? $col = 'ruc' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Ruc<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                        </th>
                						<th class="data4 titleGrid linkTitleG">
                						<? $col = 'medio_publicacion' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Origen<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                						</th>
    									<th class="data5 titleGrid linkTitleG">
    									<? $col = 'razon_social' ;
                                         $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC'; 
                                         $base['col']=$col;
                                         $base['ord']=$ord;
                                         $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Empresa<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
    									</th>
    									<th class="data6 titleGrid linkTitleG">
    									<? $col = 'fh_pub' ;
                                         $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC'; 
                                         $base['col']=$col;
                                         $base['ord']=$ord;
                                         $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Fecha Publicación<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
    									</th>
    									<th class="data7 titleGrid linkTitleG">
    									<? $col = 'chequeado' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Editado<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                        </th>
    									<th class="data8 titleGrid">Acción</th>
    									
    								</tr>
                				</thead>
                				<tbody>
                				<?php
                				if (count($this->arrayBusqueda)>0) {
                				    $cantidad =5;//$this->arrayBusqueda->getCurrentItemCount() 
                				    $count = ($this->pagina - 1)*$cantidad + 1 ;
                				}
                				?>
                				<?php foreach ($this->arrayBusqueda as $item) {?>
    								<tr>
                						<td class="data1"><?= $count++; ?></td>
                						<td class="data2"><?= $item['puesto'] ?></td>
                						<td class="data3"><?= $item['ruc'] ?></td>
                						<td class="data4"><?= $item['medio_publicacion'] ?></td>
    									<td class="data5"><?= $item['razon_social'] ?></td>
    									<td class="data6">
    									<?php if ($item['fh_pub']!= null) { ?>
                						<?=  date('d/m/Y', strtotime($item['fh_pub']));?>
                						<?php } else { ?>
                						Sin Fecha
                						<?php } ?>
                						</td>
                						<td class="data7"><?= $item['chequeado']==1? 'Si':'No' ?></td>
                						<td class="data8">
                							<div class="editAdmEPI"><a href="<?=$this->url(array('module'=>'admin','controller'=>'aviso-preferencial','action'=>'editar','rel'=>$item['id']),"default",true)?> ">Editar</a></div>
                						</td>
    								</tr>
    								<?php } ?>
    							</tbody>
          			</table>
          			</div>
                			<?php if (count($this->arrayBusqueda) != 0) { ?>
                            <div class="pagination all">
                            <?= $this->paginationControl($this->arrayBusqueda, 'Sliding', 'gestion/_pag.phtml') ?>
                            </div>
                            <?php } else { ?>
                            <div class="pagination all">
                            <div class='pagUl theta alignL'> - No existen avisos para la búsqueda realizada </div>
                        	</div>
                            <?php }  ?>
                        <?php } ?>
                        </div>
                	</div>
                </div>
            </div>
        </div>
    </div>
</div>
