<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=
            $this->partial('_partials/_navigation.phtml',
                array('isAuth' => $this->isAuth, 'auth' => $this->auth, "flashMessages" => $this->flashMessages))
            ?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>

                    <div class="row">
                        <div class="grids-2">
                            <?=
                            $this->partial('gestion/_sidebar-menu.phtml',
                                array('menu_sel_side' => $this->menu_sel_side, 'rol' => $this->rol))
                            ?>
                        </div>
                        <div class="grids-7">
                            <h2>Cambio de clave</h2>
                            <form action="" method="post" id="frmChangePassword" class="frm-horizontal large" data-parsley-validate>
                                <?php
                                echo $this->partial('mi-cuenta/_cambio_clave.phtml',
                                    'postulante',
                                    array('formCambioClave' => $this->formCambioClave));
                                ?>
                                <div class="txt_right">
                                    <input type="submit" class="btn btn-primary" value="Guardar cambios">
                                </div>
                            </form>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
</div>
