<h3 class="titleAPLR">Actualizar:  </h3>
<form method="post" class="all formFieldEmpresa hide" id="formFieldEditar" msg-error="<?= $this->error ?>" action="<?= $this->url(array('module'=>'admin','controller'=>'gestion','action'=>'get-company-tcn'),'default',true) ?>">
    <div class="block">
        <label for="fDomain" class="labelN"> Url TCN: </label>
        <?=$this->formCompanyTCN->url_tcn->setAttribs(array('class'=>'inputN left', 'maxlength' => '75'))->renderViewHelper(); ?>
        <?$hasError = $this->formCompanyTCN->url_tcn->hasErrors(); ?>
        <span class="response cGray left<?= $hasError?' bad':''?>"><?= $hasError? $this->formCompanyTCN->url_tcn->errMsg:''?></span>
    </div>
    <div class="block">
        <label for="fDomain" class="labelN"> Prioridad: </label>
        <?=$this->formCompanyTCN->prioridad_home->setAttribs(array('id'=>'prioridad_home','class'=>'inputN left', 'maxlength' => '3'))->renderViewHelper(); ?>
        <?$hasError = $this->formCompanyTCN->prioridad_home->hasErrors(); ?>
        <span class="response cGray left<?= $hasError?' bad':''?>"><?= $hasError? $this->formCompanyTCN->prioridad_home->errMsg:''?></span>
    </div>
    <div class="block">
        <label for="" class="labelN">En portada: </label>
        <div class="left clearBApi">
            <?=$this->formCompanyTCN->portada->setAttribs(array('id'=>'portada','class'=>'left'))->renderViewHelper(); ?>
        </div>
        <span class="response cGray left"></span>
    </div>
    <?=$this->formCompanyTCN->id_empresa ?>
     <div class="all" id="cntOptSaveApi">
        <input id="saveUserAPI"  type="submit" class="active btnSptAdm sptAdm" value="">
     </div>
</form>
