<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml',array('isAuth'=>$this->isAuth,'auth'=>$this->auth, "flashMessages"=>$this->flashMessages))?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <div class="iAccount" id="innerMain">
                    <?=$this->partial('gestion/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side))?>
                    <div id="gridTableR" class="blockAR alpha right">
               			<div class="iBlockAR">
						</div>
            		</div>
            		</div>
            	</div>
            </div>
        </div>
    </div>
</div>
