<h3 class="titleAPLR"><?= $this->idUsuAdmin!= null? 'Editar ':'Nuevo '?> administrador</h3>
<form method="post" class="all formFieldAdm hide" id="formFieldAdm" msg-error="<?= $this->error ?>" action="<?= $this->url(array('module'=>'admin','controller'=>'gestion','action'=>'nuevo-usuario-admin'),'default',true) ?>">

    <div class="block">
        <label class="labelN left" for="fEmail"><span class="req">*</span> Usuario</label>
        <?php $hasError = $this->formUsuario->email->hasErrors(); ?>
        <?=$this->formUsuario->email->setAttribs(array('id'=>'fEmail','class'=>'inputN left','tabindex'=>'1'))->renderViewHelper(); ?>
        <?php  if ($hasError != 0){
            $ErrorPhoto= $this->formUsuario->email->getErrors();
            $errMsg = Application_Form_Paso1Usuario::$errorsEmail[$ErrorPhoto[0]];
            } else{
            $errMsg ='';
            }
        ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$errMsg?></span>
    </div> 
    <div class="block">
        <label class="labelN left" for="fNombre"><span class="req">*</span> Nombres</label>
        <?$hasError = $this->formUsuAdmin->nombre->hasErrors(); ?>
        <?=$this->formUsuAdmin->nombre->setAttribs(array('id'=>'fNombre','class'=>'inputN left','tabindex'=>'2'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuAdmin->nombre->errMsg:''?></span>
    </div> 
    <div class="block">
        <label class="labelN left" for="fApellido"><span class="req">*</span> Apellidos</label>
        <?$hasError = $this->formUsuAdmin->apellido->hasErrors(); ?>
        <?=$this->formUsuAdmin->apellido->setAttribs(array('id'=>'fApellido','class'=>'inputN left','tabindex'=>'3'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuAdmin->apellido->errMsg:''?></span>
    </div> 
    <div class="block">
        <label class="labelN left" for="fRol"><span class="req">*</span> Rol</label>
        <?$hasError = $this->formUsuAdmin->rol->hasErrors(); ?>
        <?=$this->formUsuAdmin->rol->setAttribs(array('id'=>'fRol','class'=>'selectN left','tabindex'=>'4'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuAdmin->rol->errMsg:''?></span>
    </div> 
    <div class="block">
        <label class="labelN left" for="fEstado"><span class="req">*</span> Estado</label>
        <?$hasError = $this->formUsuAdmin->activo->hasErrors(); ?>
        <?=$this->formUsuAdmin->activo->setAttribs(array('id'=>'fEstado','class'=>'selectN left','tabindex'=>'5'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuAdmin->activo->errMsg:''?></span>
    </div>   
    <div class="block">
        <label class="labelN left" for="fClave"><span class="req"><?= isset($this->idUsuAdmin)? '&nbsp':'*' ?> </span> Clave <br/><span class="cGray f11 nBold">(Mín. 6 caracteres)</span></label>
        <?$hasError = $this->formUsuario->pswd->hasErrors(); ?>
        <?=$this->formUsuario->pswd->setAttribs(array('id'=>'fClave','class'=>'inputN left','tabindex'=>'6'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuario->pswd->errMsg:''?></span>
    </div> 
    <div class="block">
        <label class="labelN left" for="fNClave"><span class="req"><?= isset($this->idUsuAdmin)? '&nbsp':'*' ?> </span> Confirmar clave</label>
        <?$hasError = $this->formUsuario->pswd2->hasErrors(); ?>
        <?=$this->formUsuario->pswd2->setAttribs(array('id'=>'fNClave','class'=>'inputN left','tabindex'=>'7'))->renderViewHelper(); ?>
        <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formUsuario->pswd2->errMsg:''?></span>
    </div>
    <div class="hide">
        <input id="idUsuAdmin" type="hidden" name="idUsuAdmin" value="<?= $this->idUsuAdmin ?>">
    </div>
    <div class="divClearBtn">
        <input type="submit" id="saveNEAdmin" class="sptAdm <?= isset($this->idUsuAdmin)? 'editWMADM':'' ?>" value="" tabindex="8" />
    </div>
    <?=$this->formUsuAdmin->tok->renderViewHelper(); ?>
</form>
