<div id="main" class="all">
    <div class="innerAll">
        <div class="bgAll gridS20">
            <?=$this->partial('_partials/_navigation.phtml','admin',array('isAuth'=>$this->isAuth, "flashMessages"=>$this->flashMessages))?>
            <div class="gridTab">
                <div class="gridIT">
                    <h5 class="h5TitleAdm">Módulo de Administración</h5>
                    <div class="iAccount" id="innerMain">
                    
                        <div id="admLeftNM" class="blockAL grid4 omega left">
                        <?=$this->partial('gestion/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rol' => $this->rol))?>
                        </div>
                        <div class="blockAR alpha right blockFix">
                            <div class="iBlockAR">
                            <h2 class="titleMAU">Postulantes</h2>
                            <form action="" method="post" id="frmBuscar_postulantes" class="r2 fieldsetAdm">
                    					<div class="block">
                                  	<label for="fEmail" class="labelN"><?= $this->modulo == 'postulante'? ' Email:':' Email:'?> </label>
                                    <?$hasError =$this->formAdmin->email->hasErrors(); ?>
                                    <?=$this->formAdmin->email->setAttribs(array('id'=>'fEmail','class'=>'fields inputN left'.((!$hasError && $this->idPostulante==null) ?'':' ready'),'tabindex'=>1))->renderViewHelper(); ?>
                                    <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAdmin->email->errMsg:''?></span>
                              	</div>
                              	<div class="block">
                                    <label for="fNames" class="labelN"> Nombres:</label>
                                    <?$hasError = $this->formAdmin->nombres->hasErrors(); ?>
                                    <?=$this->formAdmin->nombres->setAttribs(array('id'=>'fNames','class'=>'fields inputN left replaceNbsp'.((!$hasError && $this->idPostulante==null)?'':' ready'),'tabindex'=>'5'))->renderViewHelper(); ?>
                                    <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAdmin->nombres->errMsg:''?></span> 
                                </div>
                              	<div class="block">
                                    <label for="fSurname" class="labelN"> Apellidos:</label>
                                    <?$hasError = $this->formAdmin->apellidos->hasErrors(); ?>
                                    <?=$this->formAdmin->apellidos->setAttribs(array('id'=>'fSurname','class'=>'fields inputN left replaceNbsp'.((!$hasError && $this->idPostulante==null)?'':' ready'),'tabindex'=>'6'))->renderViewHelper(); ?>
                                    <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formAdmin->apellidos->errMsg:''?></span> 
                                </div>
                              	<div class="block">
                                    <label for="fNDoc" class="labelN"> Número de documento:</label>
                                    <?$hasError = $this->formAdmin->num_doc->hasErrors(); ?>
                                    <?  if ($hasError != 0){
                                            $Error= $this->formAdmin->num_doc->getErrors();
                                            $errMsg = Application_Form_Paso1Postulante::$errors[$Error[0]];
                                    	} else{
                                    	    $errMsg ='';
                                    	}	
                                    ?>
                                    <?=$this->formAdmin->num_doc->setAttribs(array('id'=>'fNDoc','class'=>'fields inputN left'.((!$hasError && $this->idPostulante==null)?'':' ready'),'tabindex'=>'11'))->renderViewHelper(); ?>
                                    <span class="response cGray left<?=$hasError?' bad':''?>"><?=$errMsg?> </span> 
        										</div>
        						<div class="all">
                                   <?php if($this->navegapostulante) {?>
                                   <a id="btnUserNavigator" class="btn btn-primary" target="_blank" href="/mi-cuenta">Navegar como usuario</a>     
                                   <?php } ?>  
        							<button id="fSendRS"  type="submit" class="active btnSptAdm sptAdm right btn-gestion" value="">Buscar</button>
        							<button id="fResetRS"  type="reset" class="active btnSptAdm sptAdm right btn-gestion" value="">Limpiar</button>
        						</div>
    							</form>
                			</div>
                			<?php if(isset($this->postulanteAdminUrl)) { ?>
                    <div class="gridYScroll">
                      <table summary="Administradores" id="dataAadmins" class="dataGrid">
                				<thead>
                				<?php $base = $this->postulanteAdminUrl ?>
                					<tr>
                						<th class="data1 titleGrid">#</th>
                						<th class="data2 titleGrid linkTitleG">
                						<? $col = 'nombres' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Nombres<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                        </th>
                						<th class="data3 titleGrid linkTitleG">
                						<? $col = 'apellidos' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Apellidos<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                        </th>
                						<th class="data4 titleGrid linkTitleG">
                						<? $col = 'num_doc' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">N° Documento<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                						</th>
                						
    									<th class="data5 titleGrid linkTitleG">
    									<? $col = 'email' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">E-mail<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
										</th>
										
										<th class="data6 titleGrid">Estado</th>
										<th class="data7 titleGrid linkTitleG">
										<? $col = 'fh_registro' ?>
                                        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                                        <? $base['col']=$col;
                                           $base['ord']=$ord;
                                           $url = $this->url($base,'default',true) ?>
                                        <a href="<?=$url?>" class="rel relArrow">Fecha Registro<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                                        </th>
										<th class="data8 titleGrid">Acción</th>
    									
										</tr>
                				</thead>
                				<tbody>
                				<?php
                				if (count($this->arrayBusqueda)>0) { 
                				    $cantidad =5;//$this->arrayBusqueda->getCurrentItemCount() 
                				    $count = ($this->pagina - 1)*$cantidad + 1 ; 
                				}
                				?>
                				<?php foreach ($this->arrayBusqueda as $item) {
                                                        $gp = new Zend_Session_Namespace('gestionPostulantes');
                                                        $clavegp = 'gestionPostulantes'.$item['id'];
                                                        $gp->$clavegp = $item['token'];
                                                    ?>
										<tr>
                						<td class="data1"><?= $count++; ?></td>
                						<td class="data2"><?= $item['nombres'] ?></td>
                						<td class="data3"><?= $item['apellidos'] ?></td>
                						<td class="data4"><?= $item['num_doc'] ?></td>
										<td class="data5"><?= $item['email']?></td>
                						<td class="data6"> <?= $item['activo']==1? 'Activo':'Inactivo'?>
                						</td>
                						<td class="data7">
                						<?=  date('d/m/Y', strtotime($item['fh_registro']));?>
                						</td>
                						<td class="data8">
                							<div class="editAdmEPI"><a href="<?=$this->url(array('module'=>'admin','controller'=>'mi-cuenta','action'=>'mis-datos-personales','rel'=>$item['id']),"default",true)?> ">Editar</a></div>
                							<?php if ($item['activo'] != 0) {?>
                							<div class="msjeAdmEPI" rel="-1"><a class="enviarMensaje winModal" href="#winAnadirMensaje" rel="<?=$item['id'] ?>" >Enviar msje</a></div>
											<div class="blockAdmEPI"><a class="blockAdmEMP pos winModal" href="#winAlertBloquearPost" rel="<?=$item['id'].'|'.$item['token']?>">Bloquear</a></div>
											<?php } else {?>
											<div class="blockAdmEPI"><a class="desblockAdmEMP pos winModal" href="#winAlertBloquearPost" rel="<?=$item['id'].'|'.$item['token']?>">Desbloquear</a></div>
											<?php } ?>
                						</td>
										</tr>
									<?php } ?>
								</tbody>
              </table>
            </div>
    						<?php if (count($this->arrayBusqueda) != 0) { ?>
                            <div class="pagination all">
                            <?= $this->paginationControl($this->arrayBusqueda, 'Sliding', 'gestion/_pag.phtml') ?>
                            </div>
                            <?php } else { ?>
                            <div class="pagination all">
                            <div class='pagUl theta alignL'> - No hay Postulante que se adecuen a Búsqueda </div>
                        	</div>
                            <?php }  ?>
                        <?php } ?>
                        </div>
                	</div>
                </div>
            </div>
        </div>
    </div>
</div>