<div id="pesatanaflotante" class="left hide">
  <a href="#" class="right triggerSdb"><span class="hide">Flecha</span></a>
</div>

<div id="blockProEmpAl" class="blockAL grid4 theta left ieEmpAside">
   	<h5 id="cabezasidebar" class="tituloPC r5T">Estado de Cuenta <a href="#" class="right triggerSdb"><span class="hide">Flecha</span></a></h5>
    <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
        <li class="liThird <?= ($this->menu_sidebar_sel == App_Controller_Action_Empresa::MENU_SIDEBAR_MI_ESTADO_CUENTA_AVISOS_PAGADOS)? 'active':''?>"><a class="aThird" href="<?= $this->url(array('module' => 'empresa', 'controller' => 'mi-estado-cuenta', 'action' => 'index'), 'default', true) ?>"><span class="sThird">Avisos Pagados</span></a></li>
        <li class="liThird <?= ($this->menu_sidebar_sel == App_Controller_Action_Empresa::MENU_SIDEBAR_MI_ESTADO_CUENTA_AVISOS_EN_PROCESO)? 'active':''?>"><a class="aThird" href="<?= $this->url(array('module' => 'empresa', 'controller' => 'mi-estado-cuenta', 'action' => 'en-proceso'), 'default', true) ?>"><span class="sThird">Avisos en Proceso</span></a></li>
        <!--
        <li class="liThird liLast <?= ($this->menu_sidebar_sel == App_Controller_Action_Empresa::MENU_SIDEBAR_MI_ESTADO_CUENTA_MEMBRESIAS)? 'active':''?>"><a class="aThird ie6Last" href="<?= $this->url(array('module' => 'empresa', 'controller' => 'mi-estado-cuenta', 'action' => 'membresias'), 'default', true) ?>"><span class="sThird">Membresías</span></a></li>
        -->
    </ul>
    
    
</div>