<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,'Look_Feel'=>$this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>  

    <div class="blockAL grid4 theta left">
        <h5 class="tituloPC r5T">Estado de Cuenta</h5>
        <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
            <li class="liThird liLast"><a class="aThird" href="<?=
                $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-estado-cuenta'),
                    'default', true)
                ?>"><span class="sThird">Pagados</span></a></li>
            <li class="liThird active"><a class="aThird ie6Last" href="#"><span class="sThird">En Proceso</span></a></li>
        </ul>
    </div>

    <div id="gridTableR" class="blockAR theta right">
        <div class="iBlockAR">
            <!-- tabla en proceso -->
            <table summary="En Proceso" id="dataAdvPorcess" class="dataGrid">
                <thead>
                    <tr>
                        <th class="data1 titleGrid">fecha creacion</th>
                        <th class="data2 titleGrid">Aviso</th>
                        <th class="data3 titleGrid">Tipo</th>
                        <th class="data4 titleGrid">Estado</th>
                        <th class="data5 titleGrid">Código</th>         
                        <th class="data6 titleGrid">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?
                    foreach ($this->estadoCuentaEnProceso as $key => $value):
                        ?>
                        <tr>
                            <td class="data1"><?= $value['fechaCreacion'] ?></td>
                            <td class="data2"><?= $value['puestoAnuncio'] ?></td>
                            <td class="data3"><?= $value['productoNombre'] ?></td>
                            <td class="data4"><?= $value['estadoCompra'] ?></td>
                            <td class="data5"><?= $value['cipCompra'] ?></td>
                            <td class="data6">
                                <div class="dataLinkAEM"><a rel="<?=
                                    $this->url(array(
                                        'slug' => $value['slug'],
                                        'url_id' => $value['anuncioUrl']),
                                        'avisoEmpresa', true)
                                    ?>" href="#winVerProceso" class="winModal">Ver Aviso</a></div>
                                <div class="dataLinkAEM"><a href="<?=
                                    $this->url(array(
                                        'module' => 'empresa',
                                        'controller' => 'mi-estado-cuenta',
                                        'action' => 'anular-pago-efectivo',
                                        'cip' => $value['cipCompra']),
                                        "default", true)
                                    ?>">Anular</a></div>
                                <div class="dataLinkAEM"><a href="<?=
                                    $this->url(array(
                                        'module' => 'empresa',
                                        'controller' => 'publica-aviso',
                                        'action' => 'paso4',
                                        'aviso' => $value['anuncioId']),
                                        "default", true)
                                    ?>">Cambiar Pago</a></div>
                            </td>
                        </tr>
                    <? endforeach; ?>																
                </tbody>
            </table>
            <div class="pagination all">
                <div class="paginador all">
                    <ul class="pagUl theta alignR right">
                        <li class="itemPag"><a class="linkPag active">1 </a></li>
                    </ul>
                </div>
            </div>  
        </div>
    </div>
</div>