<?=
$this->partial('_partials/_navigation.phtml',
	 array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>

<div id="wrapper" class="row">
	 <?=
	 $this->partial('_partials/_messages.phtml',
		  array("flashMessages" => $this->flashMessages))
	 ?>

	 <div id="cntTitlesEF" class="cntTitlePEL cntTopTitleAP">
		  <h2 class="titleModSP titlePEL">Cuenta de empresa: <span class="txtEmpresaEPL"><?= $this->membresia['e_nombre'] ?></span> </h2>
		  <a href="<?=
		  $this->url(array(
				'module' => 'empresa', 'controller' => 'mi-estado-cuenta', 'action' => 'membresias'),
				'default', true);
		  ?>" class="backToAP">Volver</a>
	 </div>
	 <h6 class="titleDetAP r5">Detalle: <span id="nameAdvAP">Aviso Comprados con <?= $this->membresia['m_descripcion'] ?> (a través de <span id="urlAdvAP">aquiempleos.com</span>)</span></h6>
	 <div class="divAllCntAP">
		  <div class="left divCntAPS">Fecha: Del <span><?=
					 date('d/m/Y',
						  strtotime($this->membresia['em_fh_inicio_membresia']))
					 ?></span> a <span><?=
					 date('d/m/Y', strtotime($this->membresia['em_fh_fin_membresia']))
					 ?></span></div>
		  <div class="absCenterAP divCntAPS">Monto Comprado: <span><?php echo $this->moneda?> <?=
					 number_format($this->membresia['c_total'], 2)
					 ?></span></div>
<!-- >div class="right divCntAPS">Monto Descuento: <span>$ 0.00</span></div-->
	 </div>
	 <div id="cntMembresiaAP">
		  <table summary="Pagados" id="tableMembresiaAP" class="dataGrid">
				<thead>
					 <tr>
						  <!--<th class="data1 titleGrid linkTitleG"><a class="rel relArrow" href="">fecha creacion<span class="arrowDG asc"></span></a></th>-->
						  <th class="titleGrid">Aviso</th>
						  <th class="titleGrid">Tipo</th>
						  <th class="titleGrid">Fecha</th>
						  <th class="titleGrid">Monto (<?php echo $this->moneda?>)</th>
					 </tr>
				</thead>
				<tbody>
					 <?
					 foreach ($this->avisos as $aviso):
						  ?>
						  <tr>
								<td class=""><?= $aviso['aviso'] ?></td>
								<td class=""><?= $aviso['tipo'] ?></td>
								<td class=""><?=
					 date('d/m/Y', strtotime($aviso['fh_confirmacion']))
						  ?></td>
								<td class="" style="text-align: right"><?=
									 number_format($aviso['precio_total'], 2)
									 ?></td>
						  </tr>
								<? endforeach; ?>
				</tbody>
		  </table>
	 </div>
</div>
