<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages" => $this->flashMessages))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,'Look_Feel'=>$this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>  

    <?=
    $this->partial('mi-estado-cuenta/_sidebar-menu.phtml',
        array('menu_sidebar_sel' => $this->menu_sidebar_sel))
    ?>
    <div id="gridTableR" class="blockAR alpha right">
        <div class="iBlockAR">
            <h2>Avisos en Proceso</h2>												
            <a name="anclaPag"></a>
            <!-- tabla en proceso -->
            <table summary="En Proceso" id="dataAdvProcess" class="dataGrid">
                <thead>
                    <tr>
                        <?
                        $base
                            = array('module' => 'empresa',
                            'controller' => 'mi-estado-cuenta',
                            'action' => 'en-proceso');
                        ?>
                        <th class="data1 titleGrid linkTitleG">
                            <?
                            $col
                                = 'fh_creacion'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Fecha creación<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data2 titleGrid linkTitleG">
                            <?
                            $col
                                = 'aviso'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Aviso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data3 titleGrid linkTitleG">
                            <?
                            $col
                                = 'tipo'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Tipo<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data4 titleGrid linkTitleG">
                            <?
                            $col
                                = 'estado'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col,
                                'ord' => $ord)), 'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Estado<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data5 titleGrid linkTitleG">
                            <?
                            $col
                                = 'compra'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col,
                                'ord' => $ord)), 'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Código<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data6 titleGrid">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?
                    foreach ($this->estadoCuentaEnProceso as $key => $value):
                        ?>
                        <tr>
                            <td class="data1"><?= $value['fechaCreacion'] ?></td>
                            <td class="data2"><?= $value['puestoAnuncio'] ?></td>
                            <td class="data3"><?=$this->Util()->isvalidProducto($value);?></td>
                            <td class="data4"><?=
                                $this->ItemList('EstadoCompra',
                                    $value['estadoCompra'])
                                ?>
                            </td>
                            <td class="data5"><?= $value['cipCompra'] ?><br><?=
                                ($value['fechaExpiracionCip'] != '') ? 'Expira:(' . $this->FriendlyDate($value['fechaExpiracionCip']) . ')'
                                        : 'No tiene Código';
                                ?></td>
                            <td class="data6">
                                <div class="dataLinkAEM">
                                    <?
                                    if ($value['tipoAnuncio'] == 'preferencial') :
                                        ?>
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'mi-cuenta',
                                            'action' => 'ver-aviso-preferencial',
                                            'preferencial' => $value['anuncioId']),
                                            'default', true);
                                        ?>
                                    <? else: ?>
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'slug' => $value['slug'],
                                            'url_id' => $value['anuncioUrl'],
                                            'id' => $value['anuncioId']),
                                            'avisoEmpresa', true);
                                        ?>
                                    <? endif; ?>
                                    <a rel="<?= $url ?>" href="#winVerProceso" class="winModal">Ver Aviso Web</a>
                                </div>

                                <div class="dataLinkAEM"><a href="#winAlertAnularCip"
                                                            class="winModal" rel="<?=
                                                            $this->url(array(
                                                                'module' => 'empresa',
                                                                'controller' => 'mi-estado-cuenta',
                                                                'action' => 'anular-pago-efectivo',
                                                                'cip' => $value['cipCompra'],
                                                                'compraId' => $value['compraId'],
                                                                'csrfhash' => $this->csrfhash),
                                                                "default", true)
                                                            ?>">Anular</a></div>
                                    <?
                                    if ($value['tipoAnuncio'] == 'preferencial') :
                                        ?>
                                    <div class="dataLinkAEM"><a href="<?=
                                        $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'publica-aviso-preferencial',
                                            'action' => 'paso4',
                                            'impreso' => $value['anuncioId']),
                                            "default", true)
                                        ?>">Cambiar Pago</a></div>
                                    <? else : ?>
                                    <div class="dataLinkAEM"><a href="<?=
                                        $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'publica-aviso',
                                            'action' => 'paso4',
                                            'aviso' => $value['anuncioId']),
                                            "default", true)
                                        ?>">Cambiar Pago</a></div>
                                    <? endif; ?>
                                <div class="dataLinkAEM"><a href="<?=
                                    $this->url(array(
                                        'module' => 'empresa',
                                        'controller' => 'mi-estado-cuenta',
                                        'action' => 'detalle-compra',
                                        'compra' => $value['compraId']),
                                        'default', false)
                                    ?>">Ver Detalle</a></div>
                            </td>
                        </tr>
                    <? endforeach; ?>
                </tbody>
            </table>
            <div class="pagination all">
                <?=
                $this->paginationControl($this->estadoCuentaEnProceso,
                    'Sliding', 'mis-procesos/_pag.phtml')
                ?>
            </div>
        </div>
    </div>
</div>