<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,
        'tieneBolsaCVs' => $this->tieneBolsaCVs,'auth' => $this->auth ,'Look_Feel'=>$this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>  

    <?=
    $this->partial('mi-estado-cuenta/_sidebar-menu.phtml',
        array('menu_sidebar_sel' => $this->menu_sidebar_sel))
    ?>
    <div id="gridTableR" class="blockAR alpha right">
        <div class="iBlockAR">
            <h2>Avisos pagados</h2>													
            <a name="anclaPag"></a>
            <table summary="Pagados" id="dataAdvPagados" class="dataGrid">
                <thead>
                    <tr>
                        <?
                        $base
                            = array('module' => 'empresa',
                            'controller' => 'mi-estado-cuenta',
                            'action' => 'index');
                        ?>
                        <th class="data1 titleGrid linkTitleG">
                            <?
                            $col
                                = 'fh_creacion'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Fecha creación<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data2 titleGrid linkTitleG">
                            <?
                            $col
                                = 'aviso'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Aviso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data3 titleGrid linkTitleG">
                            <?
                            $col
                                = 'tipo'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Tipo<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data4 titleGrid linkTitleG">
                            <?
                            $col
                                = 'forma-pago'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Forma de Pago<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data5 titleGrid linkTitleG">
                            <?
                            $col
                                = 'monto'
                            ?>
                            <?
                            $ord
                                = ($this->col == $col && $this->ord == 'ASC') ? 'DESC'
                                    : 'ASC'
                            ?>
                            <?
                            $url
                                = $this->url(array_merge($base,
                                    array('col' => $col, 'ord' => $ord)),
                                'default', false)
                            ?>
                            <a href="<?= $url ?>" class="rel relArrow">Monto (<?php echo $this->moneda?>)<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                        </th>
                        <th class="data7 titleGrid">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    <?
                    foreach ($this->estadoCuentaPagados as $key => $value):
                        ?>
                        <tr>
                            <td style="width: 60px;"><?= $value['fechaCreacion'] ?></td>
                            <td class="data2"><?= $value['puestoAnuncio'] ?></td>
                            <td class="data3"><?=$this->Util()->isvalidProducto($value);
                              
                                ?></td>
                            <td class="data4"  style="width: 120px;"><?=
                                $this->ItemList('MedioPago', $value['medioPago'])
                                ?></td>
                            <td class="data5" style="text-align: right; width: 90px;"><?php echo $this->moneda?> <?=
                                number_format($value['precioTotal'], 2)
                                ?></td>
                            <?php
                            $Dscto = $value['precioBase'] - $value['precioTotal'];
                            /* Cuando se registra con extraCargo realiza la condicion */
                            if ($Dscto <= 0) {
                                $Dscto = 0;
                            }
                            ?>
                           
                            <td class="data7" style="width: 115px;">
                                <div class="dataLinkAEM">
                                    <?
                                    if ($value['tipoAnuncio'] == 'preferencial') :
                                        ?>
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'mi-cuenta',
                                            'action' => 'ver-aviso-preferencial',
                                            'preferencial' => $value['anuncio_impreso']),
                                            'default', true);
                                        ?>
                                    <? else: ?>
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'slug' => $value['slug'],
                                            'url_id' => $value['anuncioUrl'],
                                            'id' => $value['anuncioId']),
                                            'avisoEmpresa', true);
                                        ?>
                                    <? endif; ?>
                                    <a rel="<?= $url ?>" href="#winVerProceso" class="winModal">Ver Aviso Web</a>
                                </div>
                                <?php
                                if ($value['tipoAnuncio'] == 'preferencial') {
                                    $urlScot = "";
                                    if ($value["urlScotEMPLEOBUSCO"] != null && $value["urlScotEMPLEOBUSCO"]
                                        != "")
                                            $urlScot = $value["urlScotEMPLEOBUSCO"];
                                    elseif ($value["urlScotTalan"] != null && $value["urlScotTalan"]
                                        != "")
                                            $urlScot = $value["urlScotTalan"];
                                    ?>
                                    <?
                                    if ($urlScot != "") :
                                        ?>
                                        <div class="dataLinkAEM"><a target="_blank" href="<?= $urlScot ?>">Ver Diseño Impreso</a></div>
                                    <? endif; ?>
                                <?php } ?>
                                <div class="dataLinkAEM"><a href="<?=
                                    $this->url(array(
                                        'module' => 'empresa',
                                        'controller' => 'mi-estado-cuenta',
                                        'action' => 'detalle-compra',
                                        'compra' => $value['compraId']),
                                        'default', false)
                                    ?>">Ver Detalle</a></div>
                            </td>
                        </tr>
                    <? endforeach; ?>																
                </tbody>
            </table>										
            <div class="pagination all">
                <?=
                $this->paginationControl($this->estadoCuentaPagados, 'Sliding',
                    'mis-procesos/_pag.phtml')
                ?>
            </div>
        </div>
    </div>
</div>
