<?=Application_Model_Partials::getMenuPostulante(); ?>
<section class="buy_highlight">
  <form action="/comprar-perfil/pagar" method="post" id="frmFeaturedProfile">
  <div class="center_box">
    <div class="row">
      <div class="col_four buy_detail">
        <div class="row_content_head">
          <h3>Detalle de Compra</h3>
        </div>
        <div class="row_content_body"><img src="<?=$this->S('/main/img/detalle-de-compra.jpg')?>" height="183" width="304" alt="EMPLEOBUSCO.com - Los clasificados de ofertas laborales del Grupo La Prensa">
          <h4><?=$this->producto ?> </h4>
          <ul class="list_profile">
            <li> <i class="icon icon_check2"></i>Prioridad en Resultados de Búsqueda.</li>
            <li> <i class="icon icon_check2"></i>Alertas del proceso de postulación.</li>
            <li> <i class="icon icon_check2"></i>Lugar preferencial en ofertas de trabajo.</li>
            <li> <i class="icon icon_check2"></i>Evaluación Psicológica Online.</li>
          </ul>
          <p class="line"><small>El precio incluye I.G.V.</small><span class="buy_detail_amount"><span class="buy_detail_text">Precio: </span><span class="buy_detail_price"><?php echo $this->moneda?> <?=$this->precio?></span></span></p>
        </div>
      </div>
      <div class="col_four type_invoice">
        <div class="row_content_head">
          <h3>Tipo de Comprobante</h3>
        </div>
        <div class="row_content_body">
          <p>A partir del 1 de octubre del 2014 se procederá a emitir los comprobantes de pago por los servicios que se les brinda mediante la modalidad de formato electrónico, los mismos que estarán a su disposición a través de la página web: <a href="http://www.gec.pe" target="_blank">www.gec.pe</a>. </p>
          <p>En caso de no contar con un usuario y contraseña de acceso, deberá de enviarnos el nombre del funcionario y la dirección del correo electrónico oficial de su representada a la siguiente dirección electrónica:<br><b>facturacionelectronica@comercio.com.pe </b>o comunicarse a la central telefónica 3116711, para la recepción de los documentos mencionados anteriormente.</p>
          <div class="option_type_document_wrap mb20">
              <span>Desea una: &nbsp;</span>
              <fieldset>
                <label class="ioption">
                  <input name="radioTipoDoc" type="radio" id="" value="boleta" checked="checked">Boleta
                </label>
                <label class="ioption">
                  <input name="radioTipoDoc" type="radio" id="" value="factura">Factura
                </label>
              </fieldset>
          </div>
          <div class="fields_dni_wrap form_control_inline" id="ticketWrap">
            <fieldset class="form_control">
              <input class="txt_control" type="text" value="<?=$this->nombres?>" disabled="disabled">
            </fieldset>
            <fieldset class="form_control">
              <input class="txt_control" type="text" value="<?= $this->dni ?>"  disabled="disabled">
            </fieldset>
          </div>
          <div class="fields_ruc_wrap hide" id="commercialTicketWrap">
            <fieldset class="form_control">
                <label class="lbl_control" for="txtRuc">RUT:</label>
                <input class="txt_control" type="text" name="txtRuc" id="txtRuc" maxlength="11" required minlength="2" autocomplete="off">
            </fieldset>
            <fieldset class="form_control hide">
                <label class="lbl_control" for="txtSocialReason">Razón social:</label>
                <input class="txt_control" type="text" name="txtSocialReason" id="txtSocialReason" required minlength="2">
            </fieldset>
            <fieldset class="form_control hide">
                <label class="lbl_control" for="selVia">Tipo vía:</label>
                <select class="txt_control" id="selVia" name="selVia" required>
                  <option value="0">Seleccionar</option>
                    <?php foreach ($this->via as $via) {
                        echo "<option value='".$via['codigo']."'>".ucwords(strtolower($via['descripcion'])).'</option>';
                    } ?>
                </select>
            </fieldset>
            <fieldset class="form_control hide">
                <label class="lbl_control" for="txtLocation">Dirección:</label>
                <input class="txt_control" type="text" name="txtLocation" id="txtLocation" required minlength="2" maxlength="40">
            </fieldset>
             <fieldset class="form_control hide">
                <label class="lbl_control" for="txtNroPuerta">Nro de puerta:</label>
                <input class="txt_control" type="text" name="txtNroPuerta" id="txtNroPuerta" required minlength="2" maxlength="10">
            </fieldset>
            <p class="mt10">Para cualquier consulta o modificación en su facturación llamar al 311600 anexo 3104 / 3411 / 3402. Revisar los datos del comprobante ya que una refacturación generaría un costo adicional.</p>
        </div>
            <input type="hidden" name="token" value="<?=$this->token?>">
            <input type="hidden" name="id_tarifa" value="<?=$this->id_tarifa?>">
            <input type="hidden" name="ente_dni" value="<?=$this->val_dni?>">
            <input type="hidden" name="ente_ruc" id="hidEnteRuc">
            <input type="hidden" name="ruc_adecsys" id="hidRucAdecsys" value="0">
        </div>
      </div>
      <div class="col_four method_pay">
        <div class="row_content_head">
          <h3>Método de Pago</h3>
        </div>
        <div class="row_content_body">
          <fieldset class="custom_check">
            <label> <span class="subtitle"> <span>Pagar sin Tarjeta de Crédito </span><i class="icon icon_help"></i></span></label>
            <label class="radio_inline">
                <input type="radio" name="radioTipoPago" value="pe" checked="checked"><span class="card_pago_efectivo"></span>
              <p>Compra con PagoEfectivo y paga a través de Internet o en cualquier oficina del BCP, BBVA, ScotiaBank, Interbank, en agencias Western Union y en establecimientos autorizados que tengan el logo de PagoEfectivo y/o Fullcarga. <br><a href="https://pagoefectivo.pe/" target="_blank" class="link_info">¿Qué es PagoEfectivo? </a></p>
            </label>
          </fieldset>
          <fieldset class="custom_check">
            <label> <span class="subtitle">Pagar con Tarjeta de Crédito</span></label><br>
            <label class="radio_inline">
              <input type="radio" name="radioTipoPago" value="visa"><span class="card_visa"></span>
              <p class="verified_visa">Paga con tarjeta de crédito. <span class="verified_by_visa"></span></p>
            </label>
            <label class="radio_inline">
              <input type="radio" name="radioTipoPago" value="mc"><span class="card_mastercard"></span>
              <p>Pago con Tarjeta de Crédito Mastercard.<i>Se aceptan tarjetas Curacao, Carsa, Ace Home Center, Ripley y afiliadas</i></p>
            </label>
          </fieldset>
        </div>
        <p class="subject_claim">* Una vez efectuado el pago, el mismo no estará sujeto a reclamo.</p>
      </div>
    </div>
    <div class="align_right">
      <a class="btn btn_return" href="#">Regresar</a>
      <button class="btn btn_pay" id="btnPay" type="submit">
        <span class="btn_label">Pagar</span>
        <span class="btn_spinner"></span>
      </button>
    </div>
    <div class="void_ssl">
      <div class="disclaimer_secure"></div>
      <p>Te encuentras en un ambiente muy seguro para transacciones por internet</p>
      <div class="disclaimer_ssl"> </div>
      <div class="disclaimer_kaspersky"></div>
      <div class="disclaimer_verising"></div>
    </div>
  </div>
  </form>
</section>
