<nav class="cont-menu"><br></nav>
<div id="wrapper">
    <div class="head-title row">
       
        <div class="title-step">
            <div class="legend">
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                    false, true)
                ?>">Inicio</a> »
                <span class="noLink">Compra de Membresia Anual</span>
            </div>
        </div>
    </div>

    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>
    <?=  $this->partial('_partials/_pagar_membresia_anual.phtml',
        array(
        "mebMem" => $this->mebMem,
        'medioPublicacion' => $this->medioPublicacion,
         'codadecsys'  =>   $this->view->codadecsys
        )
    )
    ?>
</div>