<?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel)) ?>
<div id="wrapper">
    <div class="legend">
        <a href="<?=SITE_URL?>">Inicio</a> » <span class="noLink">Membresia</span>
    </div>
    <div class="wrap_joincv">
        <h1 class="title-bigxxx">¡Ya tienes tu Membresia en <span class="logo_EMPLEOBUSCO"></span>!</h1>
    

    <table summary="Ficha de Pago" id="gridEndPayA" class="dataGrid">
        <thead>
            <tr>
                <th class="data1 titleGrid">Tipo</th>
                <th class="data2 titleGrid">Nombre</th>
                <th class="data3 titleGrid">Fecha de inicio</th>
                <th class="data4 titleGrid">Fecha de fin</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="data1 dataPBig"><?=$this->membresi['m_tipo'] ?></td>
                <td class="data2 dataPBig"><?=$this->membresi['m_nombre'] ?></td>
                <td class="data3 dataPBig"><?=$this->FriendlyDate($this->membresi['fh_inicio_membresia']);?></td>
                <td class="data3 dataPBig"><?=$this->FriendlyDate($this->membresi['fh_fin_membresia']);?></td>
            </tr>						
        </tbody>
    </table>
        <a href="/mi-cuenta" title="Ir a mi cuenta" class="mR20">Ir a mi cuenta</a>
        <a href="/mi-cuenta/mis-datos-personales" title="Ver mi perfil">Ver mi perfil</a>
    </div>
</div>