<nav class="cont-menu"><br></nav>
<div id="wrapper">
    <div class="head-title row">
       
        <div class="title-step">
            <div class="legend">
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                    false, true)
                ?>">Inicio</a> »
                <span class="noLink"><?=$this->textoMembresia?></span>
            </div>
        </div>
    </div>

    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>
    <?=  
        $this->partial('_partials/_pagar_membresia_anual.phtml',
            array(
                "mebMem" => $this->mebMem,
                'medioPublicacion' => $this->medioPublicacion,
                'tokenMemprecia'=>   $this->tokenMemprecia,
                'via'=>  $this->via ,
               'razonsocial' =>$this->razonsocial,
               'ruc'=> $this->ruc  ,
               'codvia'=>$this->codvia,
               'direc'=>$this->direc,
               'codadecsys'  => isset( $this->codadecsys) ? $this->codadecsys:'',
                'Formfacturacion'=> $this->Formfacturacion,
                'moneda' => $this->moneda,
                'igv' => $this->igv
            )
        )
    ?>
</div>