<?php $isError = $this->form->isErrors(); ?>
<?php $tarifa_class = '' ?>
<?php $lock =(isset($this->lock) && $this->lock!='')?($this->lock):'';
        ?>
<?php if (!empty($this->form->id_puesto)) { ?>
    <?php 
    $modelProducto = new Application_Model_Producto();
    $tipoProducto = $modelProducto->obtenerTipoAviso($this->form->id_tarifa->getValue());
    ?>
    <?php $tarifa_class = ($this->form->id_puesto->getValue() == Application_Model_Puesto::OTROS_PUESTO_ID || $tipoProducto == Application_Model_AnuncioWeb::TIPO_CLASIFICADO) ? '' : ' hide'; ?>
    <?php $puesto_class = ($this->form->id_tarifa->getValue() == 1) ? ' changeNombrePuesto' : ''; ?>
    <div class="control-group">
        <label for="" class="control-label"><em>*</em> Tipo del puesto:</label>
        <div class="controls">
            <? $hasError = $this->form->id_puesto->hasErrors(); ?>
            <?= $this->form->id_puesto->setAttribs(array('class' => 'sel-medium require'. $puesto_class ,  'data-function-lock'=>$lock))->renderViewHelper(); ?>
            <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_puesto->errMsg : '' ?></span>
        </div>
    </div>
<?php } ?>
<div class="control-group<?= $tarifa_class; ?>">
    <label for="" class="control-label"><em>*</em> Nombre del puesto:</label>
    <div class="controls">
        <? $hasError = $this->form->nombre_puesto->hasErrors(); ?>
        <?= $this->form->nombre_puesto->setAttribs(array('class' => 'input-xmedium onlytext require', 'data-limit' => $this->numPalabraPuesto))->renderViewHelper(); ?>
        <? if ($hasError != 0) {
            $ErrorOtroMensaje = $this->form->nombre_puesto->getErrors();
            $errMsg = Application_Form_Paso2PublicarAviso::errorsOtroPuesto($ErrorOtroMensaje[0]);
        } else {
            $errMsg = '';
        } ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $errMsg ?></span>
    </div>
</div>
<div class="control-group">
    <label for="" class="control-label"><em>*</em> Área:</label>
    <div class="controls">
        <? $hasError = $this->form->id_area->hasErrors(); ?>
        <?= $this->form->id_area->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_area->errMsg : '' ?></span>        
    </div>
</div>
<div class="control-group">
    <label for="" class="control-label"><em>*</em> Nivel del puesto:</label>
    <div class="controls">
        <? $hasError = $this->form->id_nivel_puesto->hasErrors(); ?>
        <?= $this->form->id_nivel_puesto->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_puesto->errMsg : '' ?></span>
        <label class="control-conadis">
             <?= $this->form->discapacidad->setAttribs(array('class' => ''))->renderViewHelper(); ?>&nbsp;Este trabajo podra ser desempeñado por una persona con discapacidad.
        </label>
    </div>
</div>

<div class="control-group">
    <label for="" class="control-label"><em>*</em> Descripción del puesto:</label>
    <div class="controls">
        <? $hasError = $this->form->funciones->hasErrors(); ?>
        <?= $this->form->funciones->setAttribs(array('class' => 'input-xmedium require', 'rows' => '7', 'cols' => '20'))->renderViewHelper(); ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->funciones->errMsg : '' ?></span>
    </div>
</div>
<div class="control-group">
    <label for="" class="control-label no-req"><em>&nbsp;</em> Otros:</label>
    <div class="controls">
        <? $hasError = $this->form->responsabilidades->hasErrors(); ?>
        <?= $this->form->responsabilidades->setAttribs(array('class' => 'input-xmedium require', 'rows' => '7', 'cols' => '20'))->renderViewHelper(); ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->responsabilidades->errMsg : '' ?></span>
    </div>
</div>
<div class="cgroup-inline">
    <label for="" class="control-label no-req"><em>&nbsp;</em> Salario:</label>
    <div class="control-group">
        <? $hasError = $this->form->mostrar_salario->hasErrors(); ?>
        <?php if (!$hasError && $this->isExperiencia) { ?>
            <?= $this->form->salario->setAttribs(array('class' => 'sel-xmiddle'))->renderViewHelper(); ?>
        <?php } else { ?>
            <?= $this->form->salario->setAttribs(array('class' => 'sel-xmiddle'))->renderViewHelper(); ?>
        <?php } ?>
    </div>
    <div class="control-group">
        <label class="ioption">
            <?= $this->form->mostrar_salario->setAttribs(array('class' => ''))->renderViewHelper(); ?>Mostrar en el aviso
        </label>
    </div>
    <div class="control-group">
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->mostrar_salario->errMsg : '' ?></span>
    </div>
</div>
<div class="cgroup-inline">
    <label for="" class="control-label no-req"><em>&nbsp;</em> Nombre de la empresa en aviso:</label>
    <div class="control-group">
        <? $nombreEmpresa = $this->layout()->auth['empresa']['nombre_comercial'];?>
        <? $hasError = $this->form->otro_nombre_empresa->hasErrors(); ?>
        <?php $dataTexto = $this->form->otro_nombre_empresa->getValue() ?>
        <?php
        if ($dataTexto == $nombreEmpresa) {
            $dataTexto = 'Importante Empresa';
        }
        ?>
        <?php if ($this->form->mostrar_empresa->getValue() == 1) : ?>
            <?= $this->form->otro_nombre_empresa->setAttribs(array('class' => 'input-xmiddle onlytext', 'data-limit' => $this->numPalabraOtroNombre, 'data-empresa' => $nombreEmpresa, 'data-text' => $dataTexto))->renderViewHelper(); ?>
        <?php else : ?>
            <?= $this->form->otro_nombre_empresa->setAttribs(array('class' => 'input-xmiddle onlytext', 'data-limit' => $this->numPalabraOtroNombre, 'data-empresa' => $nombreEmpresa, 'data-text' => $dataTexto, 'readonly' => 'readonly'))->setValue($nombreEmpresa)->renderViewHelper(); ?>
        <?php endif; ?>
    </div>
    <div class="control-group">
        <?
        if ($hasError != 0) {
            $ErrorOtroMensaje = $this->form->otro_nombre_empresa->getErrors();
            $errMsg = Application_Form_Paso2PublicarAviso::errorsOtroNombre($ErrorOtroMensaje[0]);
        } else {
            $errMsg = '';
        }
        ?>
        <?php if ($this->form->mostrar_empresa->getValue() == 1) : ?>
            <label class="ioption">
                <?= $this->form->mostrar_empresa_opcion->setAttribs(array('class' => ''))->setValue(false)->renderViewHelper(); ?> Mostrar otro nombre
            </label>
        <?php else : ?>
            <label class="ioption">
                <?= $this->form->mostrar_empresa_opcion->setAttribs(array('class' => ''))->setValue(true)->renderViewHelper(); ?> Mostrar otro nombre
            </label>
        <?php endif; ?>
    </div>
    <div class="control-group txt_small">
        <?php if ($this->showLogoEmpresa) { ?>
            (No aparecerá el Logotipo de la Empresa).  
        <?php } else { ?>
            Este texto reemplaza el nombre de la empresa.<br/>Si desea puede cambiarlo por otro.
        <?php } ?>
        <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $errMsg ?></span>
    </div>    
</div>
<?= $this->form->mostrar_empresa; ?>


<?php
if (isset($this->modulo)) {
    if ($this->modulo == 'admin') {
        ?>
        <div class="control-group">
            <label for="" class="control-label"><em>*</em> Correo electrónico:</label>
            <div class="controls">
                <? $hasError = $this->form->correo->hasErrors(); ?>
                <?= $this->form->correo->setAttribs(array('class' => 'input-xmedium require'))->renderViewHelper(); ?>
                <?
                if ($hasError != 0) {
                    $Error = $this->form->correo->getErrors();
                    $errMsg = Application_Form_Paso2PublicarAviso::$errorsEmail[$Error[0]];
                } else {
                    $errMsg = '';
                }
                ?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $errMsg ?></span>
                <p id="pMsnfEmail">* Puede ingresar hasta 70 caracteres. | <span>0</span> c.</p>
            </div>
        </div>
        <div class="control-group">
            <label for="" class="control-label no-req"><em>&nbsp;</em>Código Adecsys:</label>
            <div class="controls">
                <? $hasError = $this->form->adecsys_code->hasErrors(); ?>
                <?= $this->form->adecsys_code->setAttribs(array('class' => 'input-xsmall'))->renderViewHelper(); ?>
                <?
                if ($hasError != 0) {
                    $Error = $this->form->adecsys_code->getErrors();
                    $errMsg = 'Solo números';
                } else {
                    $errMsg = '';
                }
                ?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $errMsg ?></span>
            </div>
        </div>
        <?php
    }
}
?>


<div class="hide">
    <?= $this->form->id_aviso; ?>
    <?= $this->form->id_tarifa; ?>
    <?= $this->form->token->renderViewHelper() ?>
</div>
