<!-- Título -->
<div class="row smb">
    <div class="col-md-12 spb">
        <div class="title">
            <div class="row smb">
                <div class="relative">
                    <div class="borde-azul-empleo"></div>
                        <h2 class="dottedN">Datos de Publicación de tu Aviso Impreso</h2>
                    <span class="sub-title-azul">(Completa los datos faltantes para que tu aviso impreso pueda ser publicado)</span>
                </div>
                
               
                
            </div>
        </div>
    </div>
</div>
<!--Datos de Publicación de tu Aviso Impreso-->
<div class="row bg-color-gray">
    <div class="aviso-body">
        <div class="row">
            <div class="col-md-4">
                <div class=" bg-gray text-center">
                    <div>Fecha de Publicación</div>
                    <div>y Medio de Publicación</div>
                </div>
                <div class="box-body contenedor-calendario-all">                 
                    
                    <div class="row smb">
                        <div class="mensaje-import-calendario">
                            <div>
                                <div class="contenedor-title-warning">
                                    <i class="fa fa-exclamation-triangle colorWarningRed" aria-hidden="true"></i>
                                    <span class="colorWarningRed">!Importante!</span>    
                                </div>
                                
                                <div class="contenedor-cuadros">
                                    <div class="cuadro-calednar">1</div>
                                    <div class="cuadro-calednar">2</div>
                                    <div class="cuadro-calednar">3</div>
                               
                                    <span class="msj-grup-min">(Grupos mínimos de 3 días)</span>
                                </div>
                                    
                            </div>
                            
                        </div>
                        <div id="contenedor-calendario">
                            <div id="simple-select-min-max"></div>
                        </div>                        
                    </div>
                    <div class="row smb">
                        
                        <span class="number-dias-class">Total de días:</span><span  class="number-dias-class" id="dias">0</span>
                    </div>
                    <div class="row smb topnro3">
                            <span class="number-dias-class">Eliga el Medio que desea Publicar</span>
                    </div>
                    <div class="row smb contenedor-radio-2">
                 
                            <div class="">
                                <input class="radio-empleo" name="dp" data-value="1" value="1" checked="checked" type="checkbox" id="check_dp">
                                <label class="text-to-radio number-dias-class" for="check_dp">Diario La Prensa</label>
                            </div>
                            <div class="">
                                <input class="radio-empleo" name="dh" data-value="1" value="1" type="checkbox" id="check_dh">
                                <label class="text-to-radio number-dias-class" for="check_dh">Diario Hoy</label>
                            </div>

                    </div>
                </div>
            </div>
            <div class="col-md-4">                
                <div class=" bg-gray text-center">
                    <div>Sólo para Aviso Lineal</div>
                    <div>Destaque su Aviso</div>
                </div>
                <div class="box-body">
                    <div class="row smb">
                        <div class="col-md-12 smb contenedor-calendario-all">
                            <div class="title-destaque-impreso">
                                <span>Días de Destaque en el Impreso</span>
                                <div class="texto-total-dias-check">( Total de días publicados= <span class="texto-total-dias-check" id="totalDiasPublicacion">0 </span>)</div>
                                <div class="texto-total-dias-check">( Total de días de destaque= <span class="texto-total-dias-check" id="totalDiasDestaque">0 </span>)</div>
                            </div>
                            
                            <div id="contenedor-fechas-check">

                            </div>
                        </div>
                    </div>
                   

                </div>
            </div>
            <div class="col-md-4">
               
                <div class=" bg-gray text-center text-clasificaciones-bg">
                    <div class="text-clasificados">Clasificación y Costo</div>
                </div>
                <div class="box-body contenedor-calendario-all heithImpreso">
                    <div class="row smb">
                        <div>
                            <div class="col-md-12 spb">
                                <p>Clasificación</p>
                                <select name="clasificacion" id="clasificacion"  class="selectpicker" data-style="btn-warning" data-width="100%">
                                    <option value="02" selected="selected">Empleos</option>
                                </select>
                            </div>
                        </div>
                        
                    </div>
                  
                    <div class="row smb">
                        <div class="col-md-12 spb">
                            <p>Sub-clasificación</p>
                        </div>
                    </div>
                    <div class="row smb">
                        <select name="subclasificacion" id="subclasificacion" class="selectpicker" data-style="btn-warning" data-width="100%">
                            <?php if (isset($this->data[$this->idTarifaImpreso]['SubCategoria'])): ?>
                                <?php foreach ($this->data[$this->idTarifaImpreso]['SubCategoria'] as $key => $value) : ?>
                                    <option value="<?= $key; ?>"><?= $value; ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                    </div>
                    <?php /* if ($this->isauthAdmin): /*?>
<!--                        <div class="row">
                            <div class="col-md-12">
                                <p>Costro Extra</p>
                            </div>
                        </div>
                        <div class="row">
                            <select class="selectpicker" data-style="btn-warning" data-width="100%">
                                <option>Costo 1 = $20</option>
                                <option></option>
                                <option></option>
                            </select>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <p>Descuento</p>
                            </div>
                        </div>
                        <div class="row">
                            <select class="selectpicker" data-style="btn-warning" data-width="100%">
                                <option>Descuento 1 = 10% del total</option>
                                <option></option>
                                <option></option>
                            </select>
                        </div>-->
                    <?php endif;*/ ?>
                </div>
            </div>

        </div>
        

    </div>

</div>

<div id="anuncioWeb" class="row smb contenedor-btnImpreso">
    <div class="texto-btn-impreso">Para continuar con la publicación de tu aviso impreso debes de realizar el cálculo de la tarifa.</div>
    <button id="btn-calcular" type="button"  disabled="true" class="opacity" data-id="<?=$this->idTarifaImpreso?>">Calcular tarifa de Impreso</button>
    <button id="btn-limpiar" type="button" >Considerar sólo Aviso Web</button>
</div>
