<?php
$ind = (isset($this->indice)) ? $this->indice : 'blank';
$index = $this->index;
$dataInd = 'data-index="' . $ind . '"';

if($this->form->id_estudio != null){
    if($this->form->id_estudio->getValue() != ''){
        $dataRol = 'data-rol="'.$this->form->id_estudio->getValue().'"';
    }
}
$dataRel = 'data-rel="' . $this->idPost . '"';
$condicion = $this->form->id_nivel_estudio->getValue() != 1 && $this->form->id_nivel_estudio->getValue() != 2 && $this->form->id_nivel_estudio->getValue() != 3
?>



<li <?= isset($dataRol) ? $dataRol : '' ?> <?= $dataRel ?> <?= $dataInd ?>>
    <?php $isError = $this->form->isErrors();  ?>
    <?php if (!$isError && ($this->isEstudio || isset($this->isEditar) )) : ?>
        <ul class="skill-title row">
            <li><?php echo $index + 1; ?>. </li>
            <li><b><?= $this->escape($this->form->id_nivel_estudio->getMultiOption($this->form->id_nivel_estudio->getValue())); ?></b>
                <?php if ($condicion) : ?>
                    en <b><?=($this->form->otra_carrera->getValue()=='')?$this->escape($this->form->id_carrera->getMultiOption($this->form->id_carrera->getValue())):$this->escape($this->form->otra_carrera->getValue()); ?></b>
                <?php endif; ?>
            </li>
            <li class="last">
                <?php if (!isset($this->online)) : ?>
                    <a href="#Editar" class="action-icons edit" title="Editar"></a>
                    <?php if (isset($this->form->id_estudio)) : ?>
                        <?php $value = $this->form->id_estudio->getValue(); ?>
                    <?php endif; ?>
                    <a href="javascript:;" class="action-icons delete<?= isset($value) ? ' eliminarItemEmp' : '' ?>" title="Eliminar"></a>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif; ?>

    <div class="skill-content<?=(!$isError && ($this->isEstudio || isset($this->isEditar))) ? ' hide' : '' ?>">
        <div class="control-group">
            <label for="" class="control-label"><em>*</em> Grado:</label>
            <div class="controls">
                <? $hasError = $this->form->id_nivel_estudio->hasErrors(); ?>
                <?= $this->form->id_nivel_estudio->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_estudio->errMsg : '' ?></span>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label"><em>*</em> Estado:</label>
            <div class="controls">
                <? $hasError = $this->form->id_nivel_estudio_tipo->hasErrors(); ?>
                <?php if ($condicion) { ?>
                    <?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'sel-medium require','disabled'=> 'disabled'))->renderViewHelper(); ?>
                <?php } ?>
                <?php /*if (!$hasError && isset($this->isEstudio) && $this->totalEstudio > 0 || $this->form->id_nivel_estudio_tipo->getValue()=='0'  ) { ?>
                <?= $this->form->id_nivel_estudio_tipo->setAttribs(array('class' => 'selectN selectReq left ready', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->id_nivel_estudio_tipo->setAttribs(array(
                    'class' => 'selectN selectReq left', 
                    'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } */?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_nivel_estudio_tipo->errMsg : '' ?></span>
            </div>
        </div>

        <div class="control-group">
            <label for="" class="control-label"><em>*</em> Tipo de Carrera:</label>
            <div class="controls">
                <? $hasError = $this->form->id_tipo_carrera->hasErrors(); ?>
                <?php if ($condicion) { ?>
                    <?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
                <?php } ?>
                <?php
                /* if (!$hasError && isset($this->isEstudio) && $this->totalEstudio > 0) { ?>
                    <?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'fNiv selectN tipoCarreraN left selectEstH selectReq ready', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->id_tipo_carrera->setAttribs(array('class' => 'fNiv selectN tipoCarreraN left selectEstH selectReq', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } */ 
                ?>

                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_tipo_carrera->errMsg : '' ?></span>
            </div>
        </div>
        <div class="control-group">
            <label for="" class="control-label"><em>*</em> Carrera:</label>
            <div class="controls">
                <? $hasError = $this->form->id_carrera->hasErrors(); ?>
                <?php if ($condicion) { ?>
                    <?php if ($this->form->otra_carrera->getValue() == ''){ ?>
                        <?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium second_title require'))->renderViewHelper(); ?>
                    <?php } else { ?>
                        <?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium require'))->renderViewHelper(); ?>
                    <?php } ?>
                <?php } else { ?>
                    <?= $this->form->id_carrera->setAttribs(array('class' => 'sel-medium require','disabled' => 'disabled'))->renderViewHelper(); ?>
                <?php } ?>
                <?php
                /* if (!$hasError && isset($this->isEstudio) && $this->totalEstudio > 0) { ?>
                    <?= $this->form->id_carrera->setAttribs(array('class' => 'fNiv career selectN left selectEstH selectReq ready', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->id_carrera->setAttribs(array('class' => 'fNiv career selectN left selectEstH selectReq', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper(); ?>
                <?php } */
                ?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_carrera->errMsg : '' ?></span>
            </div>
        </div>
        <div class="control-group<?=($this->form->id_carrera->getValue() == 15) ? '' : ' hide'; ?>">
            <label for="" class="control-label"><em>*</em> Descripci&oacute;n Carrera:</label>
            <div class="controls">
                <? $hasError = $this->form->otra_carrera->hasErrors(); ?>
                <?php if (in_array($this->form->id_carrera->getValue(),array(69,65,101,184,125,103,15,50,130,94,158,152,86,207,76))){ ?>
                    <?= $this->form->otra_carrera->setAttribs(array('class' => 'input-xmedium require second_title', 'autocomplete' => 'off'))->renderViewHelper(); ?>
                <?php } else { ?>
                    <?= $this->form->otra_carrera->setAttribs(array('class' => 'input-xmedium require', 'autocomplete' => 'off'))->renderViewHelper(); ?>
                <?php } ?>
                <?/*= $this->form->otra_carrera->setAttribs(array('class' => 'inputN left inputReq ready', 'disable' => ($condicion) ? '' : 'disable'))->renderViewHelper();*/ ?>
                <span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->otra_carrera->errMsg : '' ?></span>
            </div>
        </div>
        <div class="hide">
            <?= $this->form->id_estudio; ?>
        </div>
    </div>
</li>

