<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
$index = $this->index;
$dataInd = 'data-index="' . $ind . '"';


if($this->form->id_dominioIdioma != null){
    if($this->form->id_dominioIdioma->getValue() != ''){
        $dataRol = 'data-rol="'.$this->form->id_dominioIdioma->getValue().'"';
    }
}
$dataRel = 'data-rel="' . $this->idPost . '"';
$validacionHide = ($this->form->id_idioma->getValue()!= "0" && $this->form->id_idioma->getValue()!= null) && ($this->form->nivel_idioma->getValue()!= "0" && $this->form->nivel_idioma->getValue()!= null)
?>

<li <?= isset($dataRol) ? $dataRol : '' ?> <?= $dataRel ?> <?= $dataInd ?>>
        <?php $isError = $this->form->isErrors(); ?>
	<?php if ( ($this->isIdioma || isset($this->isEditar)) && (!$isError ) ) : ?>
		<ul class="skill-title row">
            <li><?php echo $index + 1; ?>. </li>
            <li><b><?=$this->escape($this->form->id_idioma->getMultiOption($this->form->id_idioma->getValue())); ?></b> en <b><?=$this->escape($this->form->nivel_idioma->getMultiOption($this->form->nivel_idioma->getValue())); ?></b>
            </li>
            <li class="last">
            	<?php if (!isset($this->online)) : ?>
            		<a href="#Editar" class="action-icons edit" title="Editar"></a>
					<?php if (isset($this->form->id_dominioIdioma)) : ?>
						<?php $value = $this->form->id_dominioIdioma->getValue(); ?>
					<?php endif; ?>
					<a href="javascript:;" class="action-icons delete<?= isset($value) ? ' eliminarItemEmp' : '' ?>" title="Eliminar"></a>
				<?php endif; ?>
            </li>
        </ul>
	<?php endif; ?>
	<?$isError = $this->form->isErrors();?>
	<div class="skill-content<?=(!$isError && ($this->isIdioma || isset($this->isEditar)) )?' hide':''?>">
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Idioma:</label>
			<div class="controls">
				<? $hasError = $this->form->id_idioma->hasErrors(); ?>
				<?= $this->form->id_idioma->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_idioma->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Nivel:</label>
			<div class="controls">
				<? $hasError = $this->form->nivel_idioma->hasErrors(); ?>
				<?= $this->form->nivel_idioma->setAttribs(array('class' => 'sel-medium second_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->nivel_idioma->errMsg : '' ?></span>
			</div>
		</div>
		<div class="block">
			<?=$this->form->id_dominioIdioma;?>
		</div>
	</div>
</li>		
