<div class="row bg-color-gray">
    <div id="accordion" role="tablist" aria-multiselectable="true">
        <div role="tab" id="headingOne">
            <div class="aviso-title">
                <h2>Publicacion de aviso <span>Inserto</span></h2>
                <div class="right position-arrow">
                    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="true" aria-controls="collapseOne">
                        <i class="fa fa-chevron-up" aria-hidden="true"></i>
                    </a>
                </div>
            </div>
        </div>
        <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
            <div class="aviso-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="box-title text-center">
                            <p>Color y Apariencia del Aviso</p>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Color de Arte</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">Blanco y Color
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">Full Color
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">1 Color
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">2 Colores
                                        </label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="precio-col">
                                        <p class="precio"></p>
                                        <p class="precio"></p>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Fondo</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">Fondo Amarillo(base)
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">Fondo Blanco
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input name="lineal" data-value="estilos" value="" type="radio">Fondo Cian
                                        </label>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="precio-col">
                                        <p class="precio"></p>
                                        <p class="precio"></p>
                                        <p class="precio"></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="box-title text-center">
                            <p>Detalles del Aviso </p>
                        </div>
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Adjuntar la imagen para el impreso</p>
                                </div>
                            </div>
                            <div class="row">
                                <input id="fileupload" type="file" class="filestyle" data-placeholder="Elegir un Archivo">
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Comentario para diseñar el arte</p>
                                </div>
                            </div>
                            <div class="row">
                                <textarea name="" id="" rows="6">
                                </textarea>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Medidas del arte</p>
                                </div>
                            </div>
                            <div class="row">
                                <select class="selectpicker" data-style="btn-warning" data-width="100%">
                                    <option>2 pulgadas x 3.5 pulgadas</option>
                                    <option>2 pulgadas x 3.5 pulgadas</option>
                                    <option>2 pulgadas x 3.5 pulgadas</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
    </div>
</div>