<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
$index = $this->index;
$dataInd = 'data-index="' . $ind . '"';

if($this->form->id_pregunta != null){
    if($this->form->id_pregunta->getValue() != ''){
        $dataRol = 'data-rol="'.$this->form->id_pregunta->getValue().'"';
    }
}
$dataRel = 'data-rel="' . $this->idPost . '"';
?>

<li <?= isset($dataRol) ? $dataRol : '' ?> <?= $dataRel ?> <?= $dataInd ?>>
    <?php $isError = $this->form->isErrors(); ?>
	<?php if (!$isError && ($this->isPregunta || isset($this->isEditar))) : ?>
		<ul class="skill-title row">
            <li><?php echo $index + 1; ?>. </li>
            <li><b><?=$this->escape($this->form->pregunta->getValue()); ?></b></li>
            <li class="last">
            	<?php if (!isset($this->online)) : ?>
            		<a href="#Editar" class="action-icons edit" title="Editar"></a>
					<?php if ($this->form->id_pregunta != null) : ?>
						<?php $value = $this->form->id_pregunta->getValue(); ?>
					<?php endif; ?>
					<a href="javascript:;" class="action-icons delete<?= isset($value) ? ' eliminarItemEmp' : '' ?>" title="Eliminar"></a>
				<?php endif; ?>
            </li>
        </ul>
	<?php endif; ?>
	<?$isError = $this->form->isErrors(); ?>
	<div class="skill-content<?=(!$isError && ($this->isPregunta || isset($this->isEditar)))?' hide':''?>" >
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Redactar su pregunta:</label>
			<div class="controls">
				<?php $hasError = $this->form->pregunta->hasErrors(); ?>
				<?=$this->form->pregunta->setAttribs(array('class'=>'input-xmedium first_title','rows'=>'7','cols'=>'20'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->pregunta->errMsg : '' ?></span>
			
                                 </div>
                                 
		</div>
		<div class="hide">
		<?=$this->form->id_pregunta;?>
		</div>
	</div>
</li> 
