<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
$index = $this->index;
$dataInd = 'data-index="' . $ind . '"';

if($this->form->id_dominioComputo != null){
    if($this->form->id_dominioComputo->getValue() != ''){
        $dataRol = 'data-rol="'.$this->form->id_dominioComputo->getValue().'"';
    }
}
$dataRel = 'data-rel="' . $this->idPost . '"';
$validacionHide = ($this->form->id_programa_computo->getValue()!= '0' && $this->form->id_programa_computo->getValue()!= null) && ($this->form->nivel->getValue()!= '0' && $this->form->nivel->getValue()!= null)

?>

<li <?= isset($dataRol) ? $dataRol : '' ?> <?= $dataRel ?> <?= $dataInd ?>>
    <?php $isError = $this->form->isErrors(); ?>
	<?php if (($this->isPrograma || isset($this->isEditar)) && (!$isError) ) : ?>
		<ul class="skill-title row">
            <li><?php echo $index + 1; ?>. </li>
            <li><b><?=$this->escape($this->form->id_programa_computo->getMultiOption($this->form->id_programa_computo->getValue())); ?></b> en <b><?=$this->escape($this->form->nivel->getMultiOption($this->form->nivel->getValue())); ?></b>
            </li>
            <li class="last">
            	<?php if (!isset($this->online)) : ?>
            		<a href="#Editar" class="action-icons edit" title="Editar"></a>
					<?php if (isset($this->form->id_dominioComputo)) : ?>
						<?php $value = $this->form->id_dominioComputo->getValue(); ?>
					<?php endif; ?>
					<a href="javascript:;" class="action-icons delete<?= isset($value) ? ' eliminarItemEmp' : '' ?>" title="Eliminar"></a>
				<?php endif; ?>
            </li>
        </ul>
	<?php endif; ?>
	<?$isError = $this->form->isErrors(); ?>
	<div class="skill-content<?=(!$isError && ($this->isPrograma || isset($this->isEditar)))?' hide':''?>">
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Programa:</label>
			<div class="controls">
				<? $hasError = $this->form->id_programa_computo->hasErrors(); ?>
				<?= $this->form->id_programa_computo->setAttribs(array('class' => 'sel-medium first_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->id_programa_computo->errMsg : '' ?></span>
			</div>
		</div>
		<div class="control-group">
			<label for="" class="control-label no-req"><em>&nbsp;</em> Nivel:</label>
			<div class="controls">
				<? $hasError = $this->form->nivel->hasErrors(); ?>
				<?= $this->form->nivel->setAttribs(array('class' => 'sel-medium second_title require'))->renderViewHelper(); ?>
				<span class="response<?= $hasError ? ' bad' : '' ?>"><?= $hasError ? $this->form->nivel->errMsg : '' ?></span>
			</div>
		</div>
		<div class="hide">
			<?=$this->form->id_dominioComputo;?>
		</div>
	</div>
</li>
