<div>
    <div class="row smb">
        <div  class="col-md-12 spb">
            <div class="title">
                <div class="relative">
                    <div class="borde-azul-empleo"></div>
                    <h2 class="dottedN">Resumen</h2>
                    <span class="sub-title-azul"></span>
                </div>
            </div>
        </div>
    </div>
    <!-- Resumen -->
    <div class="row bg-color-gray">
        <div class="resumen" >
            <div class="row">
                <div class="col-md-6">
                    <div class="row">
                        <div class="col-md-12">
                            <p class="resumen-title">Aviso Web</p>
                        </div>
                    </div>
                    <div class="row" >
                        <div class="col-md-6">
                            <div class="resumen-web">
                                <p>Destaque tu publicación</p>
                            </div>
                            <div class="resumen-web">
                                <p>Días de Publicación</p>
                            </div>
                            <div class="resumen-web">
                                <p>Días de Destaque</p>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="resumen-web" id="anclaImpreso" style="display: flex;">
                                <p id="tipo_web" class="azul">Aviso Simple </p>
                                <!-- <div class="line"></div> -->
                                <span class="precio-destaque">( $  <span id="radioPrecioDestaque">0.00 </span> )</span>
                            </div>
                            <div class="resumen-web">
                                <p class="azul"><span id="radioDiasPublicacion">0</span> días.</p>
                            </div>
                            <div class="resumen-web">
                                <p class="azul"><span id="radioDiasDestaque">0</span> días.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="row pd-tb-1em">
                        <img src="<?= $this->S('/eb/img/resumen-web.jpg') ?>" alt="Vista Previa del Aviso Web">
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
