<section class="pasarela">
<div class="container">

  <?=
  $this->partial('_partials/_messages.phtml',
      array("flashMessages" => $this->flashMessages))
  ?>
  <?=
  $this->partial(
      '_partials/_pagar_anuncio.phtml',
      array(
        'idtarifa'=>$this->idtarifa,
        'Formfacturacion'=>$this->Formfacturacion,
        'razonsocial' =>$this->razonsocial,
        'ruc'=> $this->ruc,
        "dataAnuncio" => $this->dataAnuncio,
        'medioPublicacion' => $this->medioPublicacion,
        'producto' => $this->producto,
        'token' => $this->token,
          'detalle_producto_web'=>$this->detalle_producto_web,
        'detalle_producto_impreso' => $this->detalle_producto_impreso,
        'isSessionAdmin' => ($this->isSessionAdmin ? true : false),
          'montoWeb'=>$this->montoWeb,          'montoImpreso'=>$this->montoImpreso

      )
  );
  ?>
</div>
</section>
<!-- Start of aquiesta Zendesk Widget script -->
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(e){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("//assets.zendesk.com/embeddable_framework/main.js","todobusco.zendesk.com");
/*]]>*/</script>
<!-- End of aquiesta Zendesk Widget script -->
