<section class="repotenciar-aviso">
    <form id="frm-product" action="" method="post" enctype="multipart/form-data">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="title">
                        <div class="row smb">
                            <div class="relative">
                                <div class="borde-azul-empleo"></div>
                                <h2 class="dottedN">Publica tu Aviso Web</h2>
                                <span class="sub-title-azul">(Elige el destaque para tu Aviso Web)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--  Publica tu Aviso Web-->
            <div class="row bg-color-gray smb">
                <div class="col-md-4 spb">
                    <div class="announcement-title">
                        <div class="row aviso-destacados-box smb">
                            <div class="text-center">
                                <h3>Destaca tu publicación Web</h3>
                                <p>Los avisos con destaque, son los más vistos</p>
                            </div>
                            <div class="avisos-destacados-input">
                                <div class="col-sm-6 col-xs-8 col-md-6 spb">
                                    <?php
                                    $idtarifa = 0;
                                    $checked  = ''
                                    ?>
                                    <?php foreach ($this->productos as $key => $item): ?>
                                        <div class="<?= $this->Tarifa()->Etiqueta($item['descripcion']) ?>">
                                            <label class="texto-producto">
                                                <?php
                                                if ($key == 0):
                                                    ?>
                                                    <?php
                                                    $idtarifa = $item['id_tarifa'];
                                                    $checked  = 'checked="checked"';
                                                    ?>
                                                <?php endif; ?>
                                                <input <?= $checked ?> id="tarifa"  class="destaque-simple" data-web="true" name="tarifa" data-diasweb="<?php echo $item['detalle_producto'][0]['valor'] ?>" data-diasdestaque="<?php echo $item['detalle_producto'][2]['valor'] ?>" data-pw="<?php echo $item['valor'] ?>" data-value="<?php echo $item['id'] ?>" value="<?php echo $item['id_tarifa'] ?>" type="radio" class="rd-destaque" data-descripcion=" <?= $item['descripcion'] ?>" required> <?= $item['descripcion'] ?>
                                            </label>
                                            <?php
                                            $checked = '';
                                            ?>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                                <div class="col-sm-6 col-xs-4 col-md-6 text-right spb">
                                    <div class="precio">
                                        <?php foreach ($this->productos as $key => $item): ?>
                                            <div class="box">
                                                <span><?= $this->Tarifa()->precios($item['valor']) ?></span> <i class="<?= $this->Tarifa()->Icon($item['descripcion']) ?>" aria-hidden="true"></i>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div id="renderList">
                        <?php foreach ($this->productos as $key => $item): ?>
                            <ul class="proList list-<?= $item['id'] ?>">
                                <div  class="aviso">
                                    <p class="titulo-empleo-busco"><?= $item['descripcion'] ?>: Características del aviso según su tipo</p>
                                    <?php foreach ($item['detalle_producto'] as $key => $d): ?>
                                        <li class="item"><span>-</span> <?php echo $d['desc'] ?></li>
                                    <?php endforeach; ?>
                                </div>
                            </ul>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>

            <!-- Resumen -->
            <?php
            echo
            $this->partial(
                'publica-aviso/_resumem-aviso.phtml',
                array(
                'data' => $this->data,
                )
            )
            ?>
        </div>
        <div class="text-center">
         <button id="continuar" type="submit" class="buttom-gray-w"  >Continuar</button>
        </div>
        <hr/>
        <input type="hidden" name="id_tarifa" value="<?= $idtarifa ?>" />
        <input type="hidden" name="aviso" value="<?php echo $this->idAviso ?>" />
        <input type="hidden" name="precio_aw" value="0" />
        <input type="hidden" name="precio_ai" value="0" />
    </form>
</section>
<!-- Start of aquiesta Zendesk Widget script -->
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(e){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("//assets.zendesk.com/embeddable_framework/main.js","todobusco.zendesk.com");
/*]]>*/</script>
<!-- End of aquiesta Zendesk Widget script -->
