<nav class="cont-menu"><br></nav>
<div id="wrapper">
    <div class="head-title row">
        <ul class="steps">
            <li>Escoge<br> el Aviso<span></span></li>
            <li>Datos<br> del Aviso<span></span></li>
            <li>Aviso<br> Impreso<span></span></li>
            <li class="act">Verifica<br> tus datos<span></span></li>
        </ul>
        <div class="title-step">
            <div class="legend">
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                    false, true)
                ?>">Inicio</a> »
                <span class="noLink">Paso 4 - Pague su Aviso</span>
            </div>
            <h1>Pague su Aviso</h1>
        </div>
    </div>

    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>
    <?=
    $this->partial(
        '_partials/_pagar_aviso.phtml',
        array(
            'Formfacturacion'=>$this->Formfacturacion,
            'Descuentos'=>$this->Descuentos,
           'via'=>  $this->via ,
           'razonsocial' =>$this->razonsocial,
           'ruc'=> $this->ruc  ,
           'codvia'=>$this->codvia,
           'direc'=>$this->direc,
           'codadecsys'  => isset( $this->codadecsys) ? $this->codadecsys:'',
           "dataAnuncio" => $this->dataAnuncio,
           'medioPublicacion' => $this->medioPublicacion,
           'fechaImpreso' => $this->fechaImpreso,
           'fhCierre' => $this->fhCierre,
           'empresaId' => $this->empresaId,
           'producto' => $this->producto,
           'fechaCierreWeb' => $this->fechaCierreWeb,
           'isSessionAdmin' => ($this->isSessionAdmin ? true : false)
        )
    )
    ?>
</div>
