<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth  ))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,
        'tieneBolsaCVs' => $this->tieneBolsaCVs,'Look_Feel'=>$this->Look_Feel))
?>
<div id="wrapper">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>

    <div class="row">
        <div class="grids-2">
            <?=
            $this->partial('mi-cuenta/_sidebar-menu.phtml',
                array('menu_sel_side' => $this->menu_sel_side))
            ?>
        </div>
        <div class="grids-7">
            <h2>Cambio de Clave</h2>
            <form action="" method="post" id="frmChangePassword" class="frm-horizontal large" data-parsley-validate>
                <?php
                echo $this->partial('mi-cuenta/_cambio_clave.phtml',
                    'postulante',
                    array('formCambioClave' => $this->formCambioClave));
                ?>
                <div class="txt_right">
                    <input type="submit" class="btn btn-primary" value="Guardar cambios">
                </div>
            </form>

        </div>
    </div>
</div>