<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,
        'tieneBolsaCVs' => $this->tieneBolsaCVs ,'Look_Feel'=>$this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>  

    <?=
    $this->partial('mi-cuenta/_sidebar-menu.phtml',
        array('menu_sel_side' => $this->menu_sel_side))
    ?>
    <div id="gridTableR" class="blockAR theta right">
        <!-- edit -->
        <div id="managerEdit">
            <div id="msgResult" class="none cf">
                <div id="msgResultBox"></div>
                <a id="msgResultClose" href="#">X</a>
            </div>
            <div id="loadingAdmin" class="none">
                <div class="loading"></div>
            </div>
        </div>
        <!-- //edit -->
        <div id="adminListTable" class="iBlockAR">
            <div id="titleyBtn">
<!--		<h2 class="titleMAU">Cuenta de empresa: <span class="empAccount"><? //= $this->escape($this->razon_social);                ?></span></h2>-->
                <h2>Mis Avisos</h2>
            </div>
            <div id="linksTable" class="all">
                <a href="<?=
                $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta',
                    'action' => 'mis-avisos'), 'default', true);
                ?>" class="left aLinkTable <?=
                   (!$this->sonAvisosInactivos) ? '' : 'aLinkOn'
                   ?> ">Avisos activos</a>
                <a href="<?=
                $this->url(array(
                    ), 'avisos-inactivos', true);
                ?>" class="left aLinkTable <?=
                   (!$this->sonAvisosInactivos) ? 'aLinkOn' : ''
                   ?>">Avisos de baja</a>
            </div>
            <?php
            echo $this->partial('mi-cuenta/_avisos_activos.phtml', 'empresa',
                array('arrayAviso' => $this->arrayAviso, 'tipoAviso' => $this->sonAvisosInactivos,
                'col' => $this->col, 'ord' => $this->ord, 'redirect' => $this->redirect,
                'creador' => $this->creador,
                'asignarProcesos' => $this->asignarProcesos,'moneda'=>$this->moneda));
            ?>
        </div>
    </div>
</div>
