<?=$this->ListaPreferencial('listPagerAP1', $this->maximoAnuncios, $this->dataPosicion, $this->dataAjax, false) ?>
<div id="cntLoadAAP" class="all">
    <div id="dataFormAddNADM" class="hidex">
            <?=$this->partial('aviso/_ver_aviso.phtml',
                array('aviso' => $this->aviso,
                    'online' => $this->online,
                    'hasPostulado' =>$this->hasPostulado,
                    'cuestionario' => $this->cuestionario, 
                    'auth' =>$this->auth,
                    'urlAviso'=> $this->urlAviso,
                    'module' => $this->module,
                    'isAuth' => $this->isAuth,
                    'acceso' => $this->acceso,
                    'logo' => $this->logo,
                    'moneda' => $this->moneda
                    )
                )?>
    </div>
</div>