<div id="iSectionsEM" class="sectionEM">
    <!-- 1 -->
    <div id="section1BW" class="iSectionTMB iSectionTMBL secAdvW1 left">
        <h2 class="titleAdvW1 active">Aviso<br/>Web <span class="iSpanW">(Gratis)</span></h2>
        <div class="sectionWTop all">
            <div class="sectionWMiddle">
                <div class="sectionHW active">
                    <div class="imgAdvWeb"><img src="<?php echo $this->S('/images/empresa/imgAdvW1.jpg'); ?>" alt="Aviso Web" /></div>
                    <div class="secText1">
                        <p class="textAdvW1">Publique su aviso gratuitamente en <br />www.aquiempleos.com</p>
                    </div>
                    <div class="textBenW1">Beneficios</div>
                    <div class="textBenW2">4 semanas de publicaci&oacute;n web</div>
                    <dl class="dlListEmp">
                        <dt class="dtListEmp bold">Administración de sus Procesos de Selecci&oacute;n desde la web.</dt>
                        <dt class="dtListEmp bold">Utilizaci&oacute;n de Filtros de B&uacute;squeda de sus candidatos.</dt>
                    </dl>
                </div>
                <div class="wrap-btn center">
                    <?php
                    if ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || $this->rol
                        == Application_Form_Login::ROL_ADMIN_SOPORTE) {
                        ?>
                        <form action="<?=
                        $this->url(array(
                            'module' => 'admin', 'controller' => 'publicar-aviso',
                            'action' => 'paso1'), false, true)
                        ?> " id="fStep1hb" method="post" >
                            <input type="hidden" name="id_tarifa" value="1" />
                            <input type="submit" id="segOptP1" value="Continuar" class=" continNAdv1 iBtn1S2M btn btn-primary"/>
                        </form>
                    <?php } else { ?>
                        <div class="btnSptEmp inactiveB"></div>
                    <?php } ?>
                </div>
            </div>
            <div class="sectionWBottom all"></div>
        </div>
    </div>
    <!-- 2 -->
    <div id="section2BW" class="iSectionTMB secAdvW2 left">
        <h2 class="titleAdvW2 active">Aviso<br/>Econ&oacute;mico</h2>
        <div class="sectionWTop all">
            <div class="sectionWMiddle">
                <div class="sectionHW active">
                    <div class="imgAdvWeb"><img src="<?php echo $this->S('/images/empresa/imgAdvW2.jpg'); ?>" alt="Aviso Web" /></div>
                    <div class="secText1">
                        <p class="textAdvW1">Su aviso web se publicará el día domingo en Los Clasificados del suplemento AquiEmpleos de:</p>
                        <p class="textAdvW2">Diario La Prensa y/o<br/> Talán del diario El Trome</p>
                    </div>
                    <div class="textBenW1">Beneficios</div>
                    <div class="textBenW2">Beneficios del Aviso WEB</div>
                    <dl class="dlListEmp">
                        <dt class="dtListEmp bold">Mejor ubicación web de su aviso sobre los Avisos WEB.</dt>
                    </dl>
                </div>
                <div class="wrap-btn center">
                    <?php
                    if ($this->rol != Application_Form_Login::ROL_ADMIN_SOPORTE) {
                        ?>
                        <a class="btn btn-primary continNAdv1" href="<?= SITE_URL ?>/admin/publicar-aviso/paso1/slide/2/">
                            Continuar
                        </a>
                    <?php } else { ?>
                        <div class="btnSptEmp inactiveB"></div>
                    <?php } ?>
                </div>
            </div>
            <div class="sectionWBottom all"></div>
        </div>
    </div>
    <!-- 3 -->
    <div id="section3BW" class="iSectionTMB secAdvW3 right">
        <h2 class="titleAdvW3 active">Aviso<br/>Preferencial</h2>
        <div class="sectionWTop all">
            <div class="sectionWMiddle">
                <div class="sectionHW active">
                    <div class="imgAdvWeb"><img src="<?php echo $this->S('/images/empresa/imgAdvW3.jpg'); ?>" alt="Aviso Web" /></div>
                    <div class="secText1">
                        <p class="textAdvW1">Su aviso web se publicará el día domingo en la sección de avisos Preferenciales del suplemento AquiEmpleos de:</p>
                        <p class="textAdvW2">Diario La Prensa y/o<br/> Talán del diario El Trome</p>
                    </div>
                    <div class="textBenW1">Beneficios</div>
                    <div class="textBenW2">Beneficios del Aviso Preferencial</div>
                    <dl class="dlListEmp">
                        <dt class="dtListEmp bold">Mejor ubicación web sobre los Avisos Económicos.</dt>
                        <dt class="dtListEmp bold">Acceso a la Base de Datos de CVS de AquiEmpleos por 2 semanas.</dt>
                    </dl>
                </div>
                <div id="heightGHT" class="hide"></div>
                <div class="wrap-btn center" id="heightTHG">
                    <?php
                    if ($this->rol != Application_Form_Login::ROL_ADMIN_SOPORTE) {
                        ?>
                        <a class="btn btn-primary continNAdv1" href="<?= SITE_URL ?>/admin/publicar-aviso-preferencial/paso1/">
                            Continuar
                        </a>
                    <?php } else { ?>
                        <div class="btnSptEmp inactiveB"></div>
                    <?php } ?>
                </div>
            </div>
            <div class="sectionWBottom all"></div>
        </div>
    </div>
    <!-- /End -->
</div>
