<form id="formEmpP1" action="" method="POST">
    <div id="elije3Opt">
        <h3 class="elecSec election1Sec">
            <input id="optP1Emp1" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
            <label for="optP1Emp1" class="labelEMP1">
                Web + AquiEmpleos impreso
            </label>
            <label for="optP1Emp1" class="priceEMP1">
                <?php echo $this->moneda?> <span id="priceRelp1"></span>
            </label>
            <label for="optP1Emp1" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['EMPLEOBUSCO']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['EMPLEOBUSCO']->get("MMMM")) ?></span>.</label>
            <label for="optP1Emp1" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP1"><?= ucfirst($this->fchCierreImp['EMPLEOBUSCO']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['EMPLEOBUSCO']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
        </h3>
        <h3 class="elecSec election2Sec">
            <input id="optP1Emp2" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
            <label for="optP1Emp2" class="labelEMP1">
                Web + El Talán impreso
            </label>
            <label for="optP1Emp2" class="priceEMP1">
                <?php echo $this->moneda?> <span id="priceRelp2"></span>
            </label>
            <label for="optP1Emp2" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['talan']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['talan']->get("MMMM")) ?></span>.</label>
            <label for="optP1Emp2" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP2"><?= ucfirst($this->fchCierreImp['talan']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['talan']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
        </h3>
        <h3 class="elecSec election3Sec">
            <input id="optP1Emp3" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
            <label for="optP1Emp3" class="labelEMP1">
                Web + AquiEmpleos + El Talán impresos
            </label>
            <label for="optP1Emp3" class="priceEMP1">
                <?php echo $this->moneda?> <span id="priceRelp3"></span>
            </label>
            <label for="optP1Emp3" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['combo']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['combo']->get("MMMM")) ?></span>.</label>
            <label for="optP1Emp3" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP2"><?= ucfirst($this->fchCierreImp['combo']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['combo']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
        </h3>
    </div>
    <div id="footEmpP1" class="all">
        <input type="submit" id="nextEmpP1" value="Siguiente" class="btnPink right logoutEmp btnSptEmp"/>
        <input type="hidden" id="idProductoLg" value="" />
        <a href="#" id="backEmpP1" class="btnGrey right btnSptEmp">
        Regresar
        </a>
        <div id="msgErrorEmpP1" class="msgErrorDef right error"></div>
    </div>
</form>
