<div id="iSection2EM" class="sectionEM">
<?php $i = 1; ?>
<?php foreach ($this->arrayClasificado as $row) {?>
    <?php $i = $i+1 ?>
	<div id="iBlock<?= $i?>S2M" class="cntTopTitP2 left">
		<div class="topTitP2 topTitP2S<?= $i?> <?= ($i==1 && ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE))? '':' inactiveB' ?>" <?= $i==1? 'id="freeAdv"':'' ?> >
			<h3 class="titAdvTopP2">Aviso Web</h3>
			<h3 class="titAdvMidP2"><?= $row['0']['descripcion']=='Sólo Web'? 'PUBLICACIÓN WEB':'IMPRESO '.mb_strtoupper($row['0']['descripcion']) ?></h3>
			<div class="priceP2 priceDef">
				<?php echo $this->moneda?><?= $i==1? '20':number_format(substr($row['0']['valor'],0,-3))?>
			</div>
		</div>
		<div class="topbodyP2 row<?= $row['0']['id']?>EM">
			<div class="cntBodyP2 <?= ($i==1 && ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE))? '':' inactiveB' ?>">
				<div class="textCntE">
					<div <?= $i==1? 'id="clickAFC"':'' ?> class="textEM1 c3">
						PUBLICACIÓN WEB
					</div>
					<div class="textEM2 c3">
						en aquiempleos.com
					</div>
				</div>
				<div class="textEM3 c3 bold">
					Utilización de Filtros
				</div>
                <?php $valor2 = explode(',', $row['1']['valor']) ?>
				<div class="textEM4"><?= $valor2['0'] ?> días </div>
				<div class="textEM5 c3 mB20 bold">de publicación web</div>
                <?php if ($i != 1) {?>
                <?php $valor2 = explode(',', $row['1']['valor']) ?>
                <div class="textEM4"> <span id="<?= $i?>WordsEM"><?= $valor2['1'] ?> palabras</span> </div>
                <div class="textEM5 c3 mB20 bold"> en el aviso impreso </div>
                <div class="textEM5">Aviso <span class="bold"> Publicado</span> en </div>
                <div class="textEM4 c3 bold"> AquiEmpleos o El Talán </div>
                <?php }?>
				</div>
            <?php if ($i== 1 && ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE) ) {?>
			<div class="all alignC"><a class="winModal viewShowEjm" rel="web.jpg" href="#ejmsAviso">Ver ejemplo</a></div>
            <?php } elseif ($i == 2) {?>
            <div class="all alignC"><a class="winModal viewShowEjm" rel="clasico.jpg" href="#ejmsAviso">Ver ejemplo</a></div>
            <?php } elseif ($i == 3) {?>
            <div class="all alignC"><a class="winModal viewShowEjm" rel="oro.jpg" href="#ejmsAviso">Ver ejemplo</a></div>
            <?php } elseif ($i == 4) {?>
            <div class="all alignC"><a class="winModal viewShowEjm" rel="platinum.png" href="#ejmsAviso">Ver ejemplo</a></div>
            <?php }?>
			<div class="all">
				<!-- flag -->
            <?php $precio = explode(',', $row['2']['valor'])?>
            <?php $id = explode(',', $row['2']['id'])?>
            <?php if ($i == 1 && ($this->rol == Application_Form_Login::ROL_ADMIN_MASTER || $this->rol == Application_Form_Login::ROL_ADMIN_SOPORTE)) {?>
				<form action="" id="fStep1hb" method="post" >
                    <input type="hidden" name="id_tarifa" value="1" />
                    <input type="submit" id="segOptP1" value="Continuar" class="btnPink logoutPrimP1 continNoP2 btnSptEmp iBtn1S2M"/>
				</form>
            <?php } elseif ($i ==2) {?>
                <a rel="{id1:'<?= $id['0'] ?>',id2:'<?= $id['1'] ?>',id3:'<?= $id['2'] ?>',words:'<?= $valor2['1'] ?> palabras',precio1:'<?= number_format($precio['0']) ?>',precio2:'<?= number_format($precio['1']) ?>',precio3:'<?= number_format($precio['2']) ?>'}" href="#2" class="btnPink continP2 btnSptEmp iBtn<?= $i ?>S2M">
                Continuar
                </a>
            <?php } elseif ($i ==3) {?>
                <a rel="{id1:'<?= $id['0'] ?>',id2:'<?= $id['1'] ?>',id3:'<?= $id['2'] ?>',words:'<?= $valor2['1'] ?> palabras',precio1:'<?= number_format($precio['0']) ?>',precio2:'<?= number_format($precio['1']) ?>',precio3:'<?= number_format($precio['2']) ?>'}" href="#3" class="btnPink continP2 btnSptEmp iBtn<?= $i ?>S2M">
                Continuar
                </a>
            <?php } elseif ($i ==4) {?>
                <a rel="{id1:'<?= $id['0'] ?>',id2:'<?= $id['1'] ?>',id3:'<?= $id['2'] ?>',words:'<?= $valor2['1'] ?> palabras',precio1:'<?= number_format($precio['0']) ?>',precio2:'<?= number_format($precio['1']) ?>',precio3:'<?= number_format($precio['2']) ?>'}" href="#4" class="btnPink continP2 btnSptEmp iBtn<?= $i ?>S2M">
                Continuar
                </a>
            <?php }?>
    		</div>
    	</div>
	</div>
    <?php }?>
</div>
