<div class="bgAll gridS20">
    <div class="gridForm">
        <div class="legend">
            <a href="/admin/">Inicio</a> »
            <span class="noLink">Paso 1 - Elige tu aviso</span>
        </div>
        <h1 class="titleOrig">Elija su aviso</h1>
        <blockquote id="modStepsForm"><img src="<?= $this->S('/images/empresa/avisoPaso1.jpg'); ?>" alt="Paso 1"/></blockquote>
        <div class="gridIStepEmp" class="all">
            <div class="sectionEM cntTopAllW openSection<?= $this->slide ?>">
                <div class="sectionEM">
                    <div class="sectionEM">
                        <?php
                        echo $this->partial('publicar-aviso/_paso1a.phtml',
                            'admin', array('rol' => $this->rol));
                        ?>
                    </div>									                                    
                </div>
            </div>
        </div>
    </div>
</div>
