<div class="bgAll gridS20">
	<div class="gridForm">
		<div class="legend">
			<a href="<?= $this->url(array('module' => 'admin', 'controller' => 'gestion', 'action' => 'index'), false, true) ?>">Inicio</a> »
			<span class="noLink">Paso 1 - Elige tu aviso</span>
		</div>
        <h1 class="titleOrig">Elija su aviso</h1>
		<blockquote id="modStepsForm"><img src="<?=$this->S('/images/empresa/avisoPaso1.jpg');?>" alt="Paso 1"/></blockquote>
		<div class="gridIStepEmp" class="all">
            <h6 id="countWordEM" class="titleGrayEM">Elija su tipo de aviso : </h6>
			<div id="sectionsEM" class="sectionEM openSection<?=$this->slide?>">
				<div id="innerSectionEmp" class="sectionEM">
                    <!--
					<div id="section1EM" class="sectionEM">
                    <?php //echo $this->partial('publica-aviso/_paso1a.phtml', 'empresa'); ?>
					</div>
                    -->
					<div id="section2EM" class="sectionEM">
					<?php echo $this->partial('publicar-aviso/_paso1b.phtml', 'admin',array('rol' => $this->rol, 'arrayClasificado' => $this->arrayClasificado,'moneda'=>$this->moneda)); ?>
					</div>

					<div id="section3EM" class="sectionEM">
					<?php echo $this->partial(
                        'publicar-aviso/_paso1c.phtml', 'admin', 
                        array(
                            'fchCierreImp' => $this->fchCierreImp,
                            'fchPubsImp' => $this->fchPubsImp,
                            'moneda'=>$this->moneda
                        )
                        ); ?>
					</div>
				</div>
			</div>
			<div class="asideFootAX">
				<a href="<?= $this->url(array('module' => 'admin', 'controller' => 'publicar-aviso','action' => 'index'), null, true); ?>" id="backEmpXF" class="btnGrey right btnSptEmp">
				Regresar
				</a>		
			</div> 				
		</div>
	</div>
</div>