<div class="bgAll gridS20">
	<div class="gridForm">
		<div class="legend">
	           <a href="<?= $this->url(array('module' => 'admin', 'controller' => 'gestion', 'action' => 'index'), false, true) ?>">Inicio</a> »
			<span class="noLink">Paso 4 - Pague su Aviso</span>
		</div>
            <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?>
		<h1 class="titleOrig">Pague su Aviso</h1>
		<blockquote id="modStepsForm"><img src="<?=$this->S('/images/empresa/avisoPaso4.jpg');?>" alt="Paso 4"/></blockquote>
		<div class="gridIStepEmp" class="all">
			<?= $this->partial('_partials/_pagar_aviso.phtml',"empresa", 
			array( 
    			"dataAnuncio"=>$this->dataAnuncio, 
    			"rol"=>$this->auth["usuario"]->rol,
    			'medioPublicacion' => $this->medioPublicacion,
			    'fhCierre' =>$this->fhCierre,
			    'fechaImpreso' =>$this->fechaImpreso
			    ) 
			) ?>
		</div>
	</div>
</div>