<div class="bgAll">
	<div class="gridForm">
		<div class="legend">
			<a href="<?= $this->url(array('module' => 'admin', 'controller' => 'gestion', 'action' => 'index'), false, true) ?>">Inicio</a> » <span class="noLink">Paso 2 - Ingrese el Perfil del puesto</span>
		</div>
		<h2 class="titleOrig">Ingrese el perfil del puesto</h2>
		<blockquote id="modStepsForm"><img src="<?= $this->S('/images/empresa/avisoPaso2.jpg'); ?>" alt="Paso 2" /></blockquote>
		<div class="gridIFormEmp resG">
			<div id="innerMain">
				<div id="content" class="formRegister">
					<div id="cntEmpRelF">
						<h2 id="titleRelF" class="titleInDB left mB0">Datos del puesto</h2>
						<p id="infoRelF" class="alignR txtReq right bold">Los campos con <span class="req">*</span> son necesarios</p>
					</div>
					<div id="formReg">
    					<form action="" id="frmPublishAd" method="post">
    					<?php echo $this->partial('_partials/_paso2_aviso.phtml', 'empresa', 
    					    array(
    					    'form' => $this->form, 'isDato' => $this->isDato,
    					    'numPalabraPuesto' => $this->numPalabraPuesto,
		                    'numPalabraOtroNombre' =>$this->numPalabraOtroNombre,
    					    'modulo' =>$this->modulo,
    					    'nombreComercial' => $this->nombreComercial,
    					    'formEstudio' => $this->formEstudio, 'managerEstudio'=> $this->managerEstudio, 'isEstudio' => $this->isEstudio, 'isEditarEstudio' => $this->isEditarEstudio,
                                            'formOtroEstudio' => $this->formOtroEstudio, 'managerOtroEstudio' => $this->managerOtroEstudio, 'isOtroEstudio' => $this->isOtroEstudio, 'isEditarOtroEstudio' => $this->isEditarOtroEstudio,
    					    'formExperiencia' => $this->formExperiencia, 'managerExperiencia'=> $this->managerExperiencia, 'isExperiencia' => $this->isExperiencia, 'isEditarExperiencia' => $this->isEditarExperiencia, 
    					    'formIdioma' => $this->formIdioma, 'managerIdioma'=> $this->managerIdioma, 'isIdioma' => $this->isIdioma, 'isEditarIdioma' => $this->isEditarIdioma,
    					    'formPrograma' => $this->formPrograma, 'managerPrograma'=> $this->managerPrograma, 'isPrograma' => $this->isPrograma, 'isEditarPrograma' => $this->isEditarPrograma,
    					    'formPregunta' => $this->formPregunta, 'managerPregunta'=> $this->managerPregunta, 'isPregunta' => $this->isPregunta, 'isEditarPregunta' => $this->isEditarPregunta, 'frmUbigeo' => $this->frmUbigeo
    					    )
    				    ); ?>
                        
                    	<fieldset class="wrap-btn right mT20">
                            <span id="msgErrorStep2" class="response error"></span>
                            <?php if ($this->tarifa == 1 ) {?> 
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'publicar-aviso', 'action'=>'index'),false,true)?>" id="backEmpP1" class="btn btn-default">Regresar</a>
                            <?php } else { ?>
                                <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'publicar-aviso', 'action'=>'paso1','slide'=>'2'),false,true)?>" id="backEmpP1" class="btn btn-default">Regresar</a>
                            <?php }?>
                    		<button id="aSetep2" class="btn btn-primary" type="submit" value=""/>Continuar >></button>
                    	</fieldset>
        				</form>
        				<?php echo $this->partial('_partials/_paso2_aviso_blank.phtml', 'empresa', 
    					    array(
    					    'managerEstudio'=> $this->managerEstudio,
                                            'managerOtroEstudio' => $this->managerOtroEstudio,
    					    'managerExperiencia'=> $this->managerExperiencia, 
    					    'managerIdioma'=> $this->managerIdioma,
    					    'managerPrograma'=> $this->managerPrograma,
    					    'managerPregunta'=> $this->managerPregunta,
    					    )
    				    ); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

