<div id="main" class="all">
  <div class="innerAll">
    <div class="bgAll gridS20">
      <?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages"=>$this->flashMessages)) ?>
      <div class="gridTab">
        <div class="gridIT">
            <h5 class="h5TitleAdm">Módulo de Administración</h5>
            <?=$this->partial('_partials/_accion-adminEmpresa.phtml',array('razonsocial'=>$this->razonsocial,'empresaAdminUrl'=>$this->empresaAdminUrl,'activo'=>$this->activo,'idEmpresa'=>$this->idEmpresa))?>
      			<div class="iAccount" id="innerMain">
	            <?=$this->partial('mi-cuenta-empresa/_sidebar-menu.phtml',array('menu_sel_side' => $this->menu_sel_side,'rel' => $this->idEmpresa,'rol' =>$this->rol,'membresiaTipo' => $this->membresiaTipo))?>
                 <div class="blockAR grid15 alpha right">
                 <?php echo $this->partial('administrador-empresa/_administrador.phtml','admin',array('arrayAdm'=>$this->arrayAdm,'rol' =>$this->rol,'idEmpresa'=>$this->idEmpresa,'idUsuLog'=>$this->idUsuLog ,'id_usuario'=>  isset( $this->id_usuario)? $this->id_usuario:0)); ?>
	             </div>
         		</div>
        </div>
      </div>
    </div>
  </div>
</div>