
<div class="blockAL cv-bags">
    <h5 class="black-title">Grupos<span class="icon-tiny white down"></span></h5>

    <div class="open mT10">
        <a href="#winAddGroup" id="btnModalAnadirGrupo" class="winModal noScrollTop" title="Añadir Grupo"><img src="<?php echo $this->S('/images/empresa/btnaddgroup.png'); ?>"/></a>
        <ul class="option-list">
            <?
            foreach ($this->gruposEmpresa as $grupo) {
                ?>
                <li class="ioption">
                    <a href="<?=
                    $this->url(array(
                        "module" => "empresa", "controller" => "bolsa-cvs", "action" => "index",
                        "id" => $grupo["id"]), "default", true)
                    ?>"><?= $this->escape($grupo["nombre"]) ?></a>
                    <span class="count">(<?= $grupo["cant"] ?>)</span>
                </li>
            <? } ?>
        </ul>
    </div>
</div>
