
<div class="row search-box">
    <form id="fIRSearchCV" method="get" class="btnImgH" action="#">
        <input type="text" value="<?= $this->query; ?>" id="fWordRS" class="mR5 left">
        <input type="submit" value="BUSCAR" class="btn btn-primary left" id="fSendRS">
        <p class="pagLegend grid5 mB0 theta alingL left mT10"><?= $this->mostrando ?></p>
    </form>
</div>
<ul id="listActionE" class="hide" style="left: 190px; top: 26px; ">
    <li class="liActionE" ><a id="lnkCopiarPostulantes" name="lnkCopiarPostulantes" class="aActionE" rel="0" href="">Copiar a otro grupo</a></li>
    <li class="liActionE" ><a id="lnkMoverPostulantes" name="lnkMoverPostulantes" class="aActionE" rel="1" href="">Mover a otro grupo</a></li>
    <li class="liActionE" ><a class="aActionE winModal" rel="2" href="#winQuitarPostulante">Quitar de este grupo</a></li>
</ul>
<div id="cntOptionsCR" class="all">
    <div id="leftBtnsCR" class="divListHeadE left">
        <ul class="nav horizontal">
            <li><a id="invitarBusqueda" class="btn btn-option left" href="#winRegistrarInvitacionBuscador">Invitar</a></li>
            <li id="aLinkFlechaT" rel="der"><button type="button" class="btn btn-option aLinkFlechaT cntFGrisT left">Más acciones <span class="flechaGrisT upFlechaEP"></span></button></li>
            <li  rel="der">
                <?php
                $url = $this->url(array('module' => 'empresa',
                    'controller' => 'bolsa-cvs',
                    'action' => 'exportar-resultado-filtro',
                    'idgrupo'=>$this->idGrupo), "default", true);
                ?>
                <a class="btn btn-option cnt-export left" href="<?= $url . '/' . $this->cadenabusqueda; ?>">Exportar resultado <span class="icon-export"></span></a>
            </li>
        </ul>
    </div>
</div>
<!--<div class="hide r5 dvMensajesBolsaCVs"><< MENSAJES >></div>-->

<div id="titleyBtn">
    <div id="divOperBCVS">
        <?php if ($this->esEditable) : ?>
            <a id="lnkEditarGrupo" class="left winModal noScrollTop" href="#winChangeNameGroup">Editar</a>
            <span class="pipeFilPerfP left">|</span>
            <a id="lnkEliminarGrupo" class="left winModal noScrollTop" href="#winDeleteGroup">Eliminar</a>
        <?php endif; ?>
    </div>
</div>

<div id="contenido_ajax_old">
    <!-- PAGINACION -->
    <div id="paginEPM" class="pagination bBGray all">
        <!--<p class="pagLegend grid5 mB0 theta alingL left"><?= $this->mostrando ?></p>-->
        <?= $this->paginationControl($this->postulantes, 'Sliding', 'bolsa-cvs/_pag.phtml', array('idGrupo' => $this->idGrupo)) ?>
    </div>
    <!-- ##### -->
    <!--<table class="dataGrid" id="dataBolsaCVs" idgrupo="<?= $this->idGrupo ?>" page="<?= $this->page ?>" col="<?= $this->col ?>" ord="<?= $this->ord ?>" >-->

    <table class="dataGrid dataGridEnviarBolsa" id="dataBolsaCVs" idgrupo="<?= $this->idGrupo ?>" page="<?= $this->page ?>" col="<?= $this->col ?>" ord="<?= $this->ord ?>"
           cadenabusqueda="<?= $this->cadenabusqueda ?>" opcionlista="<?= $this->opcionlista ?>" summary="Bolsa de CVs">
        <thead>
            <tr>
                <th class="data0 titleGrid">
                    <input type="checkbox" id="chkSelectAll" name="selectAll" class="noBdr">
                </th>
                <th class="data2 titleGrid linkTitleG">
                    <?php $col = 'path_foto' ?>
                    <?php $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow">Foto<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data4 titleGrid linkTitleG">
                    <? $col = 'nombres' ?>
                    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow">Nombres<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data5 titleGrid linkTitleG">
                    <? $col = 'sexo' ?>
                    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow">Sexo<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data5 titleGrid linkTitleG">
                    <? $col = 'edad' ?>
                    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"> Edad <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data2 titleGrid linkTitleG">
                    <? $col = 'nivel_estudio' ?>
                    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"> Nivel<br>estudio <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data2 titleGrid linkTitleG">
                    <? $col = 'carrera' ?>
                    <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
                    <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"> Carrera <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                </th>
                <th class="data5 titleGrid">Acciones</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->postulantes as $item): ?>
                <tr class="pintarLeidos">
                    <td class="data0">
                        <input rel="<?= $item["idpostulante"] ?>" type="checkbox" name="select">
                    </td>
                    <td class="data2">
                        <span class="dateData">
                            <a href="#" class="verPerfilFilPerfP_Imagen">
                                <?php
                                $logo = ($item["path_foto"] == "" || $item["path_foto"] == NULL) ?
                                        $this->S('/images/photoDefault.jpg') : ELEMENTS_URL_IMG . $item["path_foto"];
                                $lado ='width' //$this->ImgLadoMayor($logo);
                                ?>
                                <img <?= $lado ?>="55" src="<?= $logo ?>" />
                            </a>
                        </span>
                    </td>
                    <td class="data4">
                        <div class="bold nameFilPerfP"><a id="lnkNombrePostulante<?= $item["idpostulante"] ?>" href="#" class="verPerfilFilPerfP_Nombre"><?= $item["nombres"] ?></a></div>
                        <?php if(!empty($item["destacado"])){?>
                        <span class="icon-medal"></span>
                        <?php }?>
                        <div class="tlfFilPerfP sptIcoEmp" title="Telefono">&nbsp;<?= $item["celular"] ?></div>
                        <div class="all">
                            <a class="verPerfilFilPerfP sptIcoEmp left" href="#" rel="<?= $item["idpostulante"] ?>" title="Ver perfil"></a>
                            <?php if (isset($item['path_cv']) && $item['path_cv'] != "") : ?>
                                <span class="pipeFilPerfP left">|</span>
                                <a class="downFilPerfP sptIcoEmp left" href="<?= ELEMENTS_URL_CVS . $item['path_cv'] ?>" title="Ver CV"></a>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td class="data5">
                        <div class="sptIcoEmp imgHombre" title="<? echo ($item["sexoMF"] == 'M') ? "Hombre" : "Mujer"; ?>"><?= $item["sexoMF"] ?> </div>
                    </td>
                    <td class="data5">
                        <span class="dateData"><?= $item["edad"] ?> años</span>
                    </td>
                    <td class="data2">
                        <span class="dateData"><?= $item["nivel_estudio"] ?></span>
                    </td>
                    <td class="data2">
                        <span class="dateData"><?= $item["carrera"] ?></span>
                    </td>
                    <td class="data5">
                        <div class="dataLinkAEM"><a rel="<?= $item["idpostulante"] ?>" href="#winAnadirNotas" class="winModal anadirNotaBolsa">Añadir notas</a></div>
                        <div class="dataLinkAEM"><a rel="<?= $item["idpostulante"] ?>" id="lnkCopPostulante<?= $item["idpostulante"] ?>" name="lnkCopPostulante<?= $item["idpostulante"] ?>" href="" class="noScrollTop copPostulante" >Copiar</a></div>
                        <div class="dataLinkAEM"><a rel="<?= $item["idpostulante"] ?>" id="lnkMovPostulante<?= $item["idpostulante"] ?>" name="lnkMovPostulante<?= $item["idpostulante"] ?>" href="" class="noScrollTop movPostulante">Mover</a></div>
                        <div class="dataLinkAEM"><a rel="<?= $item["idpostulante"] ?>" href="#winQuitarPostulante" class="winModal noScrollTop kickPostulante">Quitar</a></div>
                    </td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    <!-- PAGINACION -->
    <div class="pagination all">
        <?= $this->paginationControl($this->postulantes, 'Sliding', 'bolsa-cvs/_pag.phtml', array("isfoot" => true, 'idGrupo' => $this->idGrupo, 'query' => $this->query)) ?>
    </div>
    <!-- ##### -->
</div>
