<?=
$this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>

<?=
$this->partial('mi-cuenta/_sec-menu.phtml', array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,
    'tieneBolsaCVs' => $this->tieneBolsaCVs,'Look_Feel'=>$this->Look_Feel))
?>

<?php
//                    Zend_Debug::dump($this->dataFiltros);
?>

<div id="wrapper">
    <?= $this->partial('_partials/_messages.phtml', array("flashMessages" => $this->flashMessages)); ?>
    <div id="innerMain" class="row">
        <div id="filterProcEmp" class="blockAL grid4 theta left">
            <div id="dvGruposEmpresa">
                <?= $this->partial('bolsa-cvs/_main_grupos.phtml', array('gruposEmpresa' => $this->gruposEmpresa)); ?>
            </div>

            <!--<div class="blockAL grid4 theta left">-->
            <div class="box-details">
                <input type="hidden" value="<?php echo $this->idGrupo; ?>" id="idGrupo" class="mB10">
                <input type="hidden" value="" id="rutaFiltro" class="mB10">
                <?= $this->partialLoop('_partials/_buscador_empresa_empleo_busco.phtml', $this->dataFiltros) ?>
            </div>
        </div>
        <div id="innerProcEmp" class="grids-710" style="position:relative">
            <!--            <div id="titleyBtn">
                            <h2 class="titleMAU left w64">Grupo "<span id="spNameGroup"><?= $this->escape($this->nombreGrupo) ?></span>"</h2>
                            <div id="divOperBCVS">
            <? // if ($this->esEditable) : ?>
                                            <a id="lnkEditarGrupo" class="left winModal noScrollTop" href="#winChangeNameGroup">Editar</a>
                                            <span class="pipeFilPerfP left">|</span>
                                            <a id="lnkEliminarGrupo" class="left winModal noScrollTop" href="#winDeleteGroup">Eliminar</a>
            <? // endif; ?>
                            </div>
                        </div>
                        <ul id="listActionE" class="hide" style="left: 190px; top: 26px; ">
                            <li class="liActionE" ><a id="lnkCopiarPostulantes" name="lnkCopiarPostulantes" class="aActionE" rel="0" href="">Copiar a otro grupo</a></li>
                            <li class="liActionE" ><a id="lnkMoverPostulantes" name="lnkMoverPostulantes" class="aActionE" rel="1" href="">Mover a otro grupo</a></li>
                            <li class="liActionE" ><a class="aActionE winModal" rel="2" href="#winQuitarPostulante">Quitar de este grupo</a></li>
                        </ul>
                        <div id="cntOptionsCR" class="all">
                            <div id="leftBtnsCR" class="divListHeadE left">
                                <ul class="ulListHeadE all">
                                    <li class="liListHeadE left"><a id="invitarBusqueda" class="aListHeadE left" href="#winRegistrarInvitacionBuscador">Invitar</a></li>
                                    <li id="aLinkFlechaT" class="liListHeadE left" rel="der"><a class="aListHeadE aLinkFlechaT cntFGrisT left" href="#">Más acciones <span class="flechaGrisT upFlechaEP"></span></a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="hide r5 dvMensajesBolsaCVs"><< MENSAJES >></div>-->

            <div id="titleyBtn">
                <h2 class="titleMAU left w64">Grupo "<span id="spNameGroup"><?= $this->escape($this->nombreGrupo) ?></span>"</h2>
                <div id="divOperBCVS">
                    <?php if ($this->esEditable) : ?>
                        <a id="lnkEditarGrupo" class="left winModal noScrollTop" href="#winChangeNameGroup">Editar</a>
                        <span class="pipeFilPerfP left">|</span>
                        <a id="lnkEliminarGrupo" class="left winModal noScrollTop" href="#winDeleteGroup">Eliminar</a>
                    <?php endif; ?>
                </div>
            </div>

            <div id="contenido_ajax">
                <?=
                $this->partial(
                        'bolsa-cvs/_main_contenido.phtml', array(
                    'ord' => $this->ord, 'col' => $this->col,
                    "postulantes" => $this->postulantes,
                    "page" => $this->page, "idGrupo" => $this->idGrupo,
                    "mostrando" => $this->mostrando,
                ));
                ?>

            </div>
                  <div id="alertSearch" class="window fix search-modal hide" style="display: none;">
                    <a class="closeWM icon-close big" href="#Cerrar" title="Cerrar ventana">Cerrar</a>
                    Has clic en buscar cuando hayas terminado de seleccionar.
                    <div class="wrap-btn center">
                        <a href="javascript:;" id="modalUrl" class="btn btn-primary">Buscar</a>
                        <a href="#Cerrar" title="Cerrar ventana" class="btn btn-default closeWM">Cancelar</a>
                    </div>
                </div>
                <div class="mask-search" style="display: none; top:0"></div>
        </div>
    </div>
    
    <div id="ajax-loading" class="loading" style="width: 100%;"></div>  
</div>
