<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="/static/js/csrf.js"></script>
<script>
    $(function() {
        var TIPO_REGISTADO      = 1;
        var TIPO_NO_REGISTRADO  = 2;
        
        var site = window.site || {};
                       
        site.urlVerificar       = '/empresa/postulantes-referidos/verificar-postulante';
        site.urlFormulario      = '/empresa/postulantes-referidos/obtener-formulario';
        site.urlFormulario      = '/empresa/postulantes-referidos/obtener-formulario';
        site.urlAgregar         = '/empresa/postulantes-referidos/agregar';
        
        site.email  = $('#email');
        site.box    = $('#box');

        site.verificar = function() {
            var datos = {};
            datos = {};
            datos.email     = site.email.val();
            datos.anuncio   = site.email.attr('data-anuncio');
            
            $.ajax({
                url: site.urlVerificar,
                data: datos,
                success: function(respuesta){
                    respuesta = JSON.parse(respuesta)
                    
                    if (respuesta.tipo == TIPO_NO_REGISTRADO) {
                        site.obtenerFormulario();
                        return;
                    }                   
                }
            });
        };
        
        site.obtenerFormulario = function() {
            $.ajax({
                url: site.urlFormulario,
                success: function(respuesta){
                    site.box.html(respuesta);
                }
            });
        };
        
        site.agregar = function() {
            $.ajax({
                url: site.urlAgregar,
                type: POST,
                success: function(respuesta){
                    site.box.html(respuesta);
                }
            });
        }   

        site.init = function() {
            $('a.btn-verificar').on('click.verificar', function(e){
                site.verificar();
            });      
        }

        $(site.init);

    });
</script>
Email:<input data-anuncio="726559" type="text" id="email" name="email" /><a class="btn-verificar" href="#ancla">Verificar</a>

<div id="box"></div>