<form id="datoBasicoEPF" method="post" action="/empresa/postulantes-referidos/agregar" enctype="multipart/form-data" target="frmref">
    <fieldset class="all">
        <div class="block blockNProc">
            <label for="fEmail" class="left labelN labelNProc">
                <span class="req">*</span> Email:
            </label>
            <?= $this->formulario->email ?> 
            <span class="response cGray left"></span>
        </div>
        <div class="block blockNProc">
            <label for="fSexo" class="left labelN labelNProc">
                <span class="req">*</span> Sexo:
            </label>
            <div id="efSex" class="iBlockN left">
                <?= $this->formulario->sexo ?>
            </div>
            <span class="response cGray left"></span>
        </div>
        <div class="block blockNProc">
            <label for="fNombres" class="left labelN labelNProc">
                <span class="req">*</span> Nombres:
            </label>
            <?= $this->formulario->nombres ?>
            <span class="response cGray left"></span>
        </div>
        <div class="block blockNProc">
            <label for="fApellidos" class="left labelN labelNProc">
                <span class="req">*</span> Apellidos:
            </label>
            <?= $this->formulario->apellidos ?>
            <span class="response cGray left"></span>
        </div>
        <div class="block blockNProc">
            <label for="fTelefono" class="left labelN labelNProc">
                <span class="req">*</span> Telefono:
            </label>
            <?= $this->formulario->telefono ?>
            <span class="response cGray left"></span>
        </div>
        <div class="block mB0">
            <label for="pCV" class="left labelN labelNProc">
                <span class="req">*</span> Sube tu CV:<br/>
                <span class="msgAside nBold f11 cRed">Tamaño máximo del archivo 2MB</span>
            </label>
            <input class="inputN cGray inputNProc placeH left" id="repCV" type="text" readonly="true" />
            <div id="cntFieldCV" class="btnFileU left rel">
                <?php /* <label for="pCV" id="fieldCV" class="fileUp"></label> */ ?>
                <div id="refer-form" class="opacity">
                    <?= $this->formulario->path_cv ?>
                </div>
            </div>
            <span class="response cGray left">Seleccione un Archivo .pdf, .doc, .docx</span>
        </div>
        <input type="hidden" id="anuncio" name="anuncio">
        <div class="wrap-btn right" >
            <button type="button" id="registerProcE" class="btn btn-default">Añadir otro referido</button>
        </div>
    </fieldset>
</form>
<iframe class="hide" src="javascript:false" name="frmref" id="frmref"></iframe>