<html>
<head>
    <title></title>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="http://aquiempleos.local/static/eb/css/empleo.busco.css?v=b2bbf095aaa1212454545454541555">
        <link rel="stylesheet" href="http://aquiempleos.local/static/eb/font-awesome/css/font-awesome.min.css?v=b2bbf095aaa1212454545454541555">
        <link rel="stylesheet" href="http://aquiempleos.local/static/eb/css/utilities.css?v=b2bbf095aaa1212454545454541555">

    <style type="text/css">
        body{
            box-sizing: border-box;
        }

    </style>
</head>
<body style="margin:0">
    <header style="border-bottom:3px solid #2A5E9A;max-width: 850px;padding-right: 20px;padding-left: 20px;margin-right: auto;margin-left: auto;">
        <table style="width:100%">
            <tr>
                <td>

                    <img src="http://aquiempleos.local/static/images/email-logo/empleo_209x150.jpg?v=b2bbf095aaa1212454545454541555"  />
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://plus.google.com/u/0/114662004918934085669">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;" src="http://aquiempleos.local/static/images/email-logo/logo-googleplus.png?v=b2bbf095aaa1212454545454541555"/>
                    </a>
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://twitter.com/aquiempleos">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;padding:0.2em" src="http://aquiempleos.local/static/images/email-logo/twitter-4.png?v=b2bbf095aaa1212454545454541555" class="icon-social"/>
                    </a>
                </td>
                <td style="width: 20px;padding-right:0.5em;">
                    <a href="https://www.facebook.com/aquiempleos">
                        <img style="width: 40px;background: #2A5E9A;border-radius:50%;" src="http://aquiempleos.local/static/images/email-logo/facebook.png?v=b2bbf095aaa1212454545454541555" class="icon-social"/>
                    </a>
                </td>
        </table>
    </header>
    <section style="font-family: gotham,arial,sans-serif;max-width: 750px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
             <br>
<table cellpadding=0 cellspacing=0 width="90%" align=center>

            <tr>
                <td colspan="2" style="text-align:justify;font-family:verdana;font-size:12px;width:20%">Este mensaje fue enviado
                     por <b>ronald</b> de la Empresa <b></b>.
                </td>

            </tr>

            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width:10%"><br>E-mail</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px;width: 10%"> : <b>ronaldfox2015@gmail.com</b></td>
            </tr>

            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">El teléfono de la empresa es</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>

            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px">Teléfono de Contacto</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>

            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Consulta</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px">: <b></b></td>
            </tr>

            <tr>
                <td style="text-align:justify;font-family:verdana;font-size:12px"><br>Enviado el 17-10-2016 15:13:25.</td>
                <td style="text-align:justify;font-family:verdana;font-size:12px"></td>
            </tr>

        </table>
        <br>

    </td></tr>

        <br><br>    </section>
    <footer style="border-top:3px solid #2A5E9A;max-width: 850px;padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;">
        <table width="100%" style="text-align:center">
            <tr>
                <td>
                    <img src="http://aquiempleos.local/static/images/email-logo/empleo_209x150.jpg?v=b2bbf095aaa1212454545454541555" style="width:90%;"/>
                </td>
                <td>
                    <img src="http://aquiempleos.local/static/images/email-logo/casa_209x150.jpg?v=b2bbf095aaa1212454545454541555" style="width:90%;"/>
                </td>
                <td>
                    <img src="http://aquiempleos.local/static/images/email-logo/carro_209x150.jpg?v=b2bbf095aaa1212454545454541555" style="width:90%;"/>
                </td>
                <td>
                    <img src="http://aquiempleos.local/static/images/email-logo/venta_209x150.jpg?v=b2bbf095aaa1212454545454541555" style="width:90%;"/>
                </td>
            </tr>
        </table>
    </footer>
</body>
</html>
