<ul data-key="<?php echo $this->param;?>" class="filters">
    <li><?= $this->titulo;?> <i class="icon icon_arrow_down2"></i></li>    
    <li>
        <form id="fFilter<?= $this->pfijof1 ?>" action="#" class="form-search open" data-type="<?= $this->param ?>">
            <ul><?php 
            
            foreach ($this->datos['visible'] as $item):
                
                $conf_areas = $this->constantes->areas;
                $conf_nivel = $this->constantes->nivel;
                $conf_fechapub = $this->constantes->fechapub;
                $conf_ubicacion = $this->constantes->ubicacion;
                $conf_discapacidad = $this->constantes->discapacidad;

                $conf_remuneracion = $this->constantes->remuneracion;
                
                if (($this->param != $conf_fechapub && $item['count'] > 0) || $this->param == $conf_fechapub) { ?>
                <li class="filter_options">
                    <label><?php

                        $filtros2 = array();
                        $separador = $this->constantes->separador;
                        if ($this->param == $conf_areas) { //areas
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                        $valor = $actual . $separador . $nueva;
                                } else { 
                                    $valor = $nueva;
                                }
                            }
                            $filtros2['areas'] = $valor;
                            if ($filtros2["areas"] == "") {
                                    $filtros2["areas"] = null;
                            }
                        }
                        
                        if ($this->param == $conf_nivel) { //nivel
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                            $valor = $actual . $separador . $nueva;
                                } else {
                                    $valor = $nueva; 

                                }
                            }
                            $filtros2['nivel'] = $valor;
                            if ($filtros2["nivel"] == "") {
                                    $filtros2["nivel"] = null;
                            }
                        }
                        
                        if ($this->param == $conf_fechapub) { //FechaPub
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                        $valor = $actual . $separador . $nueva;
                                } else {
                                    $valor = $nueva;
                                }
                            }
                            $filtros2['fecha-publicacion'] = $valor;
                            if ($filtros2["fecha-publicacion"] == "") {
                                    $filtros2["fecha-publicacion"] = null;
                            }
                        }
                        
                        if ($this->param == $conf_ubicacion) { //Ubicacion
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                    $valor = $actual . $separador . $nueva;
                                } else {
                                    $valor = $nueva;
                                }
                            }
                            $filtros2['ubicacion'] = $valor;
                            if ($filtros2["ubicacion"] == "")
                                    $filtros2["ubicacion"] = null;
                        }
                        
                        if ($this->param == $conf_discapacidad) {
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                    $valor = $actual . $separador . $nueva;
                                } else {
                                    $valor = $nueva;
                                }
                            }
                            $filtros2['discapacidad'] = $valor;
                            if ($filtros2["discapacidad"] == "")
                                    $filtros2["discapacidad"] = null;
                            
                        }
                        
                        $ruta = $this->url($filtros2, 'buscar', false);
                        
                        if (($this->param != $conf_fechapub && $item['count'] > 0) || $this->param == $conf_fechapub) { 
                                echo trim($this->escape($item['label'])); 
                                
                        } 
                        
                        //if ($this->param != $conf_fechapub) { 
                            if ($item['count'] > 0) { ?> <span class="count">(<?= $item['count'] ?>)</span><?php } 
                        //} 
                        
                        $val = $item['slug'];
                        $type = "checkbox";
                        if ($this->param == $conf_fechapub || $this->param == $conf_remuneracion) {
                            $type = 'radio';
                            $val = '';
                        }  
                        
                            ?>
                        <input id="areas<?= $item['slug'] ?>" name="areas<?= $val ?>" data-value="<?= $item['slug'] ?>" value="<?= $item['slug'] ?>"
                           type="<?=$type?>" disabled class="checkN" <?=
                           ($this->param != "" ? (in_array($item["slug"],
                                   explode($this->constantes->separador,
                                       $this->filtro)) ? "checked" : "") : "")
                           ?> />
                    <?php } ?>
                    </label>
                  </li>
            <?php endforeach; ?>
                                                      
              
              
              
              
              
              
              <?php if (isset($this->datos['ocultos']) && count($this->datos['ocultos']) > 0): ?>
                
                    <?php foreach ($this->datos['ocultos'] as $ite): ?>
                        <?php  foreach ($ite as $item): ?>
                            <? //$i++; ?>
                            <?php if ($item['count'] > 0) { ?>
                    <li  class="filter_options more_options">
                            <label>    
                                <?= $item["label"] ?> <span class="count">(<?= $item['count'] ?>)</span>
                                <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>" data-value="<?= $item['slug'] ?>" value="<?= $item['slug'] ?>"
                                       type="checkbox" disabled class="checkN" <?=
                                       ($this->param != "" ? (in_array($item["slug"],
                                               explode($this->constantes->separador,
                                                   $this->filtro)) ? "checked" : "")
                                               : "")
                                       ?> />
                            </label>
                    </li>
                        <?php } ?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                

            <?php endif; ?> 
              
              
              


            </ul>
            
            <?php if (isset($this->datos['ocultos']) && count($this->datos['ocultos']) > 0) { ?>
            <a href="javascript:;" title="Ver todos" class="see_more">Ver todos</a>                    
            <?php } ?>
            
            
        </form>
        
    </li>
</ul>




<?php


/*
$conf_nivel = $this->constantes->nivel;
$showFilterSalario = false;
if ($this->param == $conf_nivel)
    $showFilterSalario = true;
?>
<?php if ($showFilterSalario) { ?>
<ul data-key="area" class="filters">
    <li><?= $this->titulo ?> <i class="icon icon_arrow_down2"></i></li>    
    <li>
        <form class="form-search open" data-type="remuneracion" action="">
            <ul>
                <li class="filter_options">
                    
                    <label>De $0 a $750<input id="radSpecify1" name="radRemuneration" value="0-750" type="radio" <?=($this->remuneracion == 2)?'checked="checked"':''?>></label>
                    <label>De $751 a $1500<input id="radSpecify2" name="radRemuneration" value="751-1500" type="radio" <?=($this->remuneracion == 3)?'checked="checked"':''?>></label>
                    <label>De $1501 a $3000<input id="radSpecify3" name="radRemuneration" value="1501-3000" type="radio" <?=($this->remuneracion == 4)?'checked="checked"':''?>></label>
                    <label>De $3001 a $6000<input id="radSpecify4" name="radRemuneration" value="3001-6000" type="radio" <?=($this->remuneracion == 5)?'checked="checked"':''?>></label>
                    <label>De $6001 a $10000<input id="radSpecify5" name="radRemuneration" value="6001-10000" type="radio" <?=($this->remuneracion == 6)?'checked="checked"':''?>></label>
                    <label>Más de $10000<input id="radSpecify6" name="radRemuneration" value="mas-10000" type="radio" <?=($this->remuneracion == 7)?'checked="checked"':''?>></label>
                    
                </li>
            </ul>
        
    </form>
    </li>
</ul>
<?php } ?>






<div class="option-list">
    <h3 class="EMPLEOBUSCO-title small">
        <i class="icon <?= $this->ico ?>"></i>
        <?= $this->titulo ?>
        <span class="icon-tiny down"></span>
    </h3>
    <form id="fFilter<?= $this->pfijof1 ?>" action="#" class="form-search open" data-type="<?= $this->param ?>">
        <div class="flow-list">
            <?php 
            foreach ($this->datos['visible'] as $item):
                
                $conf_areas = $this->constantes->areas;
                $conf_nivel = $this->constantes->nivel;
                $conf_fechapub = $this->constantes->fechapub;
                $conf_ubicacion = $this->constantes->ubicacion;
                $conf_remuneracion = $this->constantes->remuneracion;
                ?>
            <?php  //if (($this->param != $conf_fechapub && $item['count'] > 0) || $this->param == $conf_fechapub) { ?>
            <?php  if ($item['count'] > 0) { ?>
                <label class="ioption">
                        <?php

                        $filtros2 = array();
                        $separador = $this->constantes->separador;
                        if ($this->param == $conf_areas) { //areas
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "")
                                        $valor = $actual . $separador . $nueva;
                                else $valor = $nueva;
                            }
                            $filtros2['areas'] = $valor;
                            if ($filtros2["areas"] == "")
                                    $filtros2["areas"] = null;
                        }
                        if ($this->param == $conf_nivel) { //nivel
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "")
                                        $valor = $actual . $separador . $nueva;
                                else $valor = $nueva;
                            }
                            $filtros2['nivel'] = $valor;
                            if ($filtros2["nivel"] == "")
                                    $filtros2["nivel"] = null;
                        }
                        if ($this->param == $conf_fechapub) { //FechaPub
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "")
                                        $valor = $actual . $separador . $nueva;
                                else $valor = $nueva;
                            }
                            $filtros2['fecha-publicacion'] = $valor;
                            if ($filtros2["fecha-publicacion"] == "")
                                    $filtros2["fecha-publicacion"] = null;
                        }
                        if ($this->param == $conf_remuneracion) { //FechaPub
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "")
                                        $valor = $actual . $separador . $nueva;
                                else $valor = $nueva;
                            }
                            $filtros2['remuneracion'] = $valor;
                            if ($filtros2["remuneracion"] == "")
                                    $filtros2["remuneracion"] = null;
                        }
                        if ($this->param == $conf_ubicacion) { //Ubicacion
                            $actual = $this->filtro;
                            $nueva = $item['slug'];
                            $valor = "";
                            if ($this->Existepalabra($nueva, $actual, $separador)) {
                                $x = explode("--", $actual);
                                array_splice($x,
                                    array_search($item["slug"], $x), 1);
                                $valor = implode("--", $x);
                            } else {
                                if ($actual != "") {
                                    $valor = $actual . $separador . $nueva;
                                } else {
                                    $valor = $nueva;
                                }
                            }
                            $filtros2['ubicacion'] = $valor;
                            if ($filtros2["ubicacion"] == "")
                                    $filtros2["ubicacion"] = null;
                        }

                        $ruta = $this->url($filtros2, 'buscar', false);
                        ?>
                        <?php  //if (($this->param != $conf_fechapub && $item['count'] > 0) || $this->param == $conf_fechapub) { ?>
                        <?php  if ($item['count'] > 0) { ?>
                        <?= $this->escape($item['label']) ?>
                        <?php } ?>
                        
                        <?php
                        //if ($this->param != $conf_fechapub || $this->param != $conf_remuneracion) {
                            ?>
                            <?php if ($item['count'] > 0) { ?>
                            <span class="count">(<?= $item['count'] ?>)</span>
                        <?php } ?>
                        <?php //} ?>    
                    
                            <?php 
                            $val = $item['slug'];
                            $type = "checkbox";
                            if ($this->param == $conf_fechapub || $this->param == $conf_remuneracion) {
                                $type = 'radio';
                                $val = '';
                            }  
                            ?>
                    
                    <input id="areas<?= $item['slug'] ?>" name="areas<?= $val ?>" value="<?= $item['slug'] ?>"
                           type="<?=$type?>" class="checkN" <?=
                           ($this->param != "" ? (in_array($item["slug"],
                                   explode($this->constantes->separador,
                                       $this->filtro)) ? "checked" : "") : "")
                           ?> />
                    <?php } ?>
                </label>
            <?php endforeach; ?>
            <?php if (isset($this->datos['ocultos']) && count($this->datos['ocultos']) > 0): ?>
                <div class="more_options hide">
                    <?php
                    foreach ($this->datos['ocultos'] as $ite):
                        ?>
                        <?php
                        foreach ($ite as $item):
                            ?>
                            <? //$i++; ?>
                            <?php if ($item['count'] > 0) { ?>
                            <label class="ioption">    
                                <label><?= $item["label"] ?><span class="count">(<?= $item['count'] ?>)</span></label>
                                <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>" value="<?= $item['slug'] ?>"
                                       type="checkbox" class="checkN" <?=
                                       ($this->param != "" ? (in_array($item["slug"],
                                               explode($this->constantes->separador,
                                                   $this->filtro)) ? "checked" : "")
                                               : "")
                                       ?> />
                            </label>
                        <?php }?>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </div>

            <?php endif; ?> 
            
        </div>
        <?php if (isset($this->datos['ocultos']) && count($this->datos['ocultos']) > 0) { ?>
            <div class="wrap-btn right">
                <a href="javascript:;" class="view-more">Ver todos</a>
            </div>
        <?php } ?>
    </form>
</div>



    
<?php
$conf_nivel = $this->constantes->nivel;
$showFilterSalario = false;
//if ($this->param == $conf_nivel)
//    $showFilterSalario = true;
?>
<?php if ($showFilterSalario) { ?>
<div class="option-list wrap-payment">
    <h3 class="EMPLEOBUSCO-title small"><i class="icon icon_money"></i><span class="icon-tiny down"></span>SALARIO</h3>
    <form class="form-search open" data-type="remuneracion" action="">
        <label class="ioption">De $0 a $750<input id="radSpecify1" name="radRemuneration" value="0-750" type="radio" <?=($this->remuneracion == 2)?'checked="checked"':''?>></label>
        <label class="ioption">De $751 a $1500<input id="radSpecify2" name="radRemuneration" value="751-1500" type="radio" <?=($this->remuneracion == 3)?'checked="checked"':''?>></label>
        <label class="ioption">De $1501 a $3000<input id="radSpecify3" name="radRemuneration" value="1501-3000" type="radio" <?=($this->remuneracion == 4)?'checked="checked"':''?>></label>
        <label class="ioption">De $3001 a $6000<input id="radSpecify4" name="radRemuneration" value="3001-6000" type="radio" <?=($this->remuneracion == 5)?'checked="checked"':''?>></label>
        <label class="ioption">De $6001 a $10000<input id="radSpecify5" name="radRemuneration" value="6001-10000" type="radio" <?=($this->remuneracion == 6)?'checked="checked"':''?>></label>
        <label class="ioption">Más de $10000<input id="radSpecify6" name="radRemuneration" value="mas-10000" type="radio" <?=($this->remuneracion == 7)?'checked="checked"':''?>></label><br>
    </form>
</div>
<?php } 

 */ 

?>
