<?php //$pageActual = ($this->pageActual == '' ? 1: $this->pageActual); 
      $pageActual = $this->pageActual;
      $totalPage = $this->totalPage;
      $first = 1;
      $ultimo = $totalPage;
      $paginaSiguiente = $pageActual + 1;
      $paginaAnterior = $pageActual - 1;
?>    
    <?php if ($totalPage) { ?>
        <ul class="pagination">
            <?php
            if ($totalPage > 1) {
                if ($paginaAnterior != 0) {
                    $params = array('page' => $paginaAnterior);
                    //echo '<li class="itemPag prevPag"><a class="linkPag first" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '">&laquo; Anterior</a></li>';
                    echo '<li><a class="paginator_item_target" title="prev" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '"><i class="icon icon_double_arrow fa fa-angle-double-left"></i></a></li>';
                } else {
                    echo '<li><a class="paginator_item_target" disabled><i class="icon icon_double_arrow fa fa-angle-double-left"></i></a></li>';
                }
            }
            //var_dump($this);
            //echo '<li class="itemPag"><a class="linkPag active">Página</a></li>';
            $viewPages = array();
            if ($totalPage <= 5) {
                //$contador = 1;
                for ($page = 1; $page <= $totalPage; $page++){ 
                    $viewPages[] = array('page' => $page, 'label' => $page);
                }
            } else {
                if($pageActual <= $first + 3){
                    for ($i = $first; $i <= ($first + 3); $i++) {
                        $viewPages[] = array('page' => $i, 'label' => $i);
                    }
                    $viewPages[] = array('page' => $i, 'label' => "...");
                    $viewPages[] = array('page' => $ultimo, 'label' => $ultimo);
                } else if ($pageActual >= $ultimo - 3){
                    $viewPages[] = array('page' => $first, 'label' => $first);
                    $viewPages[] = array('page' => ($ultimo - 4), 'label' => "...");
                    for ($i = ($ultimo - 3); $i <= $ultimo; $i++) {
                        $viewPages[] = array('page' => $i, 'label' => $i);
                    }
                } else {
                    $viewPages[] = array('page' => $first, 'label' => $first);
                    if ($first < ($pageActual - 2)) {
                        $viewPages[] = array('page' => ($pageActual - 2), 'label' => "...");
                    }
                    
                    $viewPages[] = array('page' => ($pageActual - 1), 'label' => ($pageActual - 1));
                    $viewPages[] = array('page' => $pageActual, 'label' => $pageActual);
                    $viewPages[] = array('page' => ($pageActual + 1), 'label' => ($pageActual + 1));
                    
                    if ($ultimo > ($pageActual + 2)) {
                        $viewPages[] = array('page' => ($pageActual + 2), 'label' => "...");
                    }
                    $viewPages[] = array('page' => $ultimo, 'label' => $ultimo);
                }
                    
            }
            ?>
            
            <?php foreach ($viewPages as $page): ?>
                <?php if ($page['page'] != $pageActual): ?>
                    <li><a href="<?= str_replace("/search-cmp/busqueda/", "/buscar/", $this->url(array('page' => $page['page']))); ?>" class="paginator_item_target"><?= $page['label']; ?></a></li>
                    <?= $ultimo == $page['page'] ? '' : '' ?>
                <?php else: ?>
                    <li class="active"><a class="paginator_item_target selected"><?= $page['label']; ?> <?= $ultimo == $page['page'] ? '' : '' ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php
            if($totalPage > 1){
                if ($paginaSiguiente <= $totalPage) {
                    $params = array('page' => $paginaSiguiente);
                    echo '<li><a class="paginator_item_target" title="next" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '"><i class="icon icon_double_arrow next fa fa-angle-double-right"></i></a></li>';
                } else {
                    echo '<li><a class="paginator_item_target" disabled><i class="icon icon_double_arrow next fa fa-angle-double-right"></i></a></li>';
                }
            }
            ?>
        </ul>
 
         <ul class="mobile_paginator row">
            <?php
             if($totalPage > 1 && $paginaAnterior != 0) {
                 $params = array('page' => $paginaAnterior);
                 echo '<li class="mobile_paginator_item prev"><a class="mobile_paginator_item_target" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '"><i class="icon icon_double_arrow mobile"></i>anterior</a></li>';
             } else {
                 echo '<li class="mobile_paginator_item prev"><a class="mobile_paginator_item_target" disabled><i class="icon icon_double_arrow mobile"></i>anterior</a></li>';
             }
?>

           <?php
            if($totalPage > 1 && $paginaSiguiente <= $totalPage) {
                $params = array('page' => $paginaSiguiente);                
                echo '<li class="mobile_paginator_item next"><a class="mobile_paginator_item_target" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '">siguiente<i class="icon icon_double_arrow next mobile"></i></a></li>';
            } else {
                echo '<li class="mobile_paginator_item next"><a class="mobile_paginator_item_target" disabled>siguiente<i class="icon icon_double_arrow next mobile"></i></a></li>';
            }
            ?>
        </ul>
        
    <?php
    } 
    ?>