<div id="content" class="rel right theta">
    <div id="wordsFtr" class="tags-box <?=(count($this->msg_facets)>0?"":"hide")?>">
        <a id="closeWFA" class="right" href="/buscar">cerrar</a>
        <? foreach($this->msg_facets as $item): ?>
        <h2 class="tags">
            <?=$this->escape($item["msg"])?>
            <?
                $conf_areas= $this->constantes->areas;
                $conf_nivel= $this->constantes->nivel;
                $conf_fechapub= $this->constantes->fechapub;
                $conf_remuneracion= $this->constantes->remuneracion;
                $conf_empresa= $this->constantes->empresa;
                $conf_ubicacion= $this->constantes->ubicacion;
                $separador = $this->constantes->separador;
                $filtros2 = array();
                foreach($this->msg_facets as $item2){
                    if($item2["param"]==$conf_areas){ //areas
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2['areas'] = $valor;
                       if($filtros2[$conf_areas]=="") $filtros2[$conf_areas]=null;
                    }
                    if($item2["param"]==$conf_nivel){ //nivel
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2[$conf_nivel] = $valor;
                       if($filtros2[$conf_nivel]=="") $filtros2[$conf_nivel]=null;
                    }
                    if($item2["param"]==$conf_fechapub){ //fechapub
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2[$conf_fechapub] = $valor;
                       if($filtros2[$conf_fechapub]=="") $filtros2[$conf_fechapub]=null;
                    }
                    if($item2["param"]==$conf_remuneracion){ //remuneracion
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2[$conf_remuneracion] = $valor;
                       if($filtros2[$conf_remuneracion]=="") $filtros2[$conf_remuneracion]=null;
                    }
                    if($item2["param"]==$conf_empresa){ //empresa
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2[$conf_empresa] = $valor;
                       if($filtros2[$conf_empresa]=="") $filtros2[$conf_empresa]=null;
                    }
                    if($item2["param"]==$conf_ubicacion){ //ubicacion
                       $valor = str_replace($item["filtro"], "", $item2["filtro"]);
                       $filtros2[$conf_ubicacion] = $valor;
                       if($filtros2[$conf_ubicacion]=="") $filtros2[$conf_ubicacion]=null;
                    }
                }
                $ruta = $this->url($filtros2,'buscar',false);
            ?>
            <a class="icon-close" href="<?=$ruta?>">&nbsp;</a>
        </h2>
        <? endforeach; ?>
    </div>
    <div class="pagination bBGray all">
        <p class="pagLegend grid7 mB0 cGray theta alingL left"><?=$this->mostrando?></p>
        <ul class="pagUl theta alignR right">
           <?//=$this->paginationControl($this->totalPage,'Sliding','buscar/_pag.phtml')?>
            <?= $this->partial('buscar/_pag.phtml',array('totalPage' => $this->totalPage, 'pageActual' => $this->pageActual)); ?>
        </ul>
    </div>
    <div class="blocksRes">
        <? $x=0;
        foreach ($this->anuncioswebs as $item): ?>
        <? $x++; ?>
        <div class="blockEntry <?=$x%2==0?"evenList":"";?> ">
            <a name="aviso_<?=$item['id_anuncio_web']?>"></a>
            <div class="all">
                <div class="contenImg left">
                   <?
                        $logo = "";
                        if (!empty($item["logoanuncio"]))
                                $logo = ELEMENTS_URL_LOGOS.$item["logoanuncio"];
                           /*($item["logoanuncio"]=="" || $item["logoanuncio"]==NULL) ? 
                                $this->verLogoDefecto ?  $this->S('/images/'.$this->logoDefecto) : '' 
                                : ELEMENTS_URL_LOGOS.$item["logoanuncio"]; 
                            * */
                            
                   if (!empty($logo)): ?>
                    <a class="logoEntry left center-img" 
                       href="<?=$this->serverUrl().$this->url(array('slug' => $item['slug_aviso'], 'url_id' => $item['id_anuncio_web']), 'aviso_resultado', true)?>">
                        <img <?=($this->ImgLadoMayor($logo))=="width"? "width='90'" : "height='90'"; ?>
                            src="<?=$logo;?>" alt="<?=$item["empresa_rs"]?>" title="<?=$item["empresa_rs"]?>">
                    </a>
                   <? else: ?>
                    <a class="logoEntry left center-img" href="<?=$this->serverUrl().$this->url(array('slug' => $item['slug_aviso'], 'url_id' => $item['id_anuncio_web']), 'aviso_resultado', true)?>">
                        <img src="<?=$this->S('/images/'.$this->logoDefecto) ?>" alt="<?=$item["empresa_rs"]?>" title="<?=$item["empresa_rs"]?>">
                    </a>
                    <? endif; ?>
                   
                </div>
                <div class="dataEntry left">
                    <h2 class="jobEntry mB5 bold"><a href="<?php echo $item['url'] ?>"><?=$item["puesto"]?></a></h2>
                    <h3 class="nameEntry"><?=$item["empresa_rs"]?> - <?=$item["ubicacion"];?> </h3>
                    <p class="dataStr mB0 c3" ><?=substr($item["descripction"],0,$this->recortaraviso)." ..."?></p>
                </div>
                <div class="options right"> <span class="currentTime">
                        <? if($item["dias_fp"]!=0): ?>
                            Publicado hace <em class="bold"><?=$item["dias_fp"]?> días
                        <? else: ?>
                            Publicado hoy    
                        <? endif; ?>
                 </em></span>
                <div class="spanView"><a class="linkView" href="<?php echo $item['url'] ?>">Ver aviso</a></div>

                <span class="spanView"><? if($item["idpostulante"]!=null) echo "<span><img align=left style='margin-left:50px;' src='".$this->S('/images/check.png')."' />Ya Postulaste</span>" ?></span>
                </div>
            </div>
        </div>
        <? endforeach; ?>
         <div class="blockAds">
            <a href="#"></a>
        </div>
        <!--
        <div class="ads728x90 blockAds">
            <a href="#">
                <img src="<?= $this->S('/images/banner-728x90.jpg'); ?>" alt="Banner" />
            </a>
        </div>
        -->
    </div>
    <div class="pagination all">
        <?//=$this->paginationControl($this->totalPage,'Sliding','buscar/_pag.phtml', array("isfoot" => true))?>
        <?= $this->partial('buscar/_pag.phtml',array('totalPage' => $this->totalPage, 'pageActual' => $this->pageActual)); ?>
    </div>
</div>
