<section class="search">
      <div class="mobile_fix_header"></div>
      <div class="center_box">
        <div class="row">
          <div class="mobile_personal_search"><i class="icon icon_lens"></i> Filtrar tu Búsqueda <i class="icon icon_arrow_downn"></i></div>
          <div class="grid_search_sidebar">
              
              
            <div class="search_form">
                
    <?php 
            $conf_areas = $this->constantes->areas;
            $conf_nivel =  $this->constantes->nivel;
            $conf_fechapub = $this->constantes->fechapub;
            $conf_remuneracion = $this->constantes->remuneracion;
            $conf_empresa = $this->constantes->empresa;
            $conf_ubicacion = $this->constantes->ubicacion;
            $conf_carrera = 'carrera';
            $separador = $this->constantes->separador;
            $conf_discapacidad = $this->constantes->discapacidad;
            $filtros3 = array();    
            
            foreach ($this->msg_facets as $item2) {
                if ($item2['param'] == $conf_areas) { //areas                    
                    $filtros3['areas'] = $item2['filtro'];
                    $filtros3[$conf_areas] = ($filtros3[$conf_areas] == '') ? null : $filtros3[$conf_areas];                    
                }
                
                if ($item2['param'] == $conf_nivel) { //nivel                    
                    $filtros3[$conf_nivel] = $item2['filtro'];
                    $filtros3[$conf_nivel] =  ($filtros3[$conf_nivel] == '') ? null : $filtros3[$conf_nivel];                    
                }
                
                if ($item2['param'] == $conf_fechapub) { //fechapub                    
                    $filtros3[$conf_fechapub] = $item2['filtro'];
                    $filtros3[$conf_fechapub] = ($filtros3[$conf_fechapub] == '') ? null : $filtros3[$conf_fechapub];                    
                }
                
                if ($item2['param'] == $conf_remuneracion) { //remuneracion                    
                    $filtros3[$conf_remuneracion] = $item2['filtro'];
                    $filtros3[$conf_remuneracion] = ($filtros3[$conf_remuneracion] == '') ? null : $filtros3[$conf_remuneracion];                    
                }
                
                if ($item2['param'] == $conf_empresa) { //empresa                    
                    $filtros3[$conf_empresa] = $item2['filtro'];
                    $filtros3[$conf_empresa] = ($filtros3[$conf_empresa] == '') ? null : $filtros3[$conf_empresa];                    
                }
                
                if ($item2['param'] == $conf_ubicacion) { //ubicacion                    
                    $filtros3[$conf_ubicacion] = $item2['filtro'];
                    $filtros3[$conf_ubicacion] = ($filtros3[$conf_ubicacion] == '') ? null : $filtros3[$conf_ubicacion];                    
                }
                
                if ($item2['param'] == $conf_carrera) { //carrera                    
                    $filtros3[$conf_carrera] = $item2['filtro'];
                    $filtros3[$conf_carrera] = ($filtros3[$conf_carrera] == '') ? null : $filtros3[$conf_carrera];                    
                }
            }
            
            $ruta3 = $this->url($filtros3, 'buscar', true);
            $queryx = str_replace(" ", "+", $this->query);
        ?>
                
                
                <form id="frmSearchPage" method="get" action="<?php echo $ruta3; ?>">
                    <div>Tu Búsqueda</div>
                    <p>Busca por descripción del puesto o código impreso</p>
                    <div class="form_control">
                        <input class="disable_especial_characters txt_search" type="text" name="q" tabindex="1" value="<?= htmlspecialchars($this->query) ?>" maxlength="60" id="txtSearchMenu"/>
                    </div>
                    <button type="submit" class="btn btn_primary btn_search tracking" data-track-strategy="normal_search">Buscar</button>
                    <a href="/busqueda-avanzada" title="Búsqueda Avanzada">Búsqueda Avanzada</a>                

                </form>
            </div>
            
            <div class="filter_bar">
                <?=$this->partialLoop('buscar/_filtro.phtml', $this->dataFiltros)?>
            </div>
          </div>
          <div class="grid_search_results">
              <?php if (count($this->msg_facets) > 0) :?>
              <div class="search_tags_wrapper">
              <?php foreach ($this->msg_facets as $item): ?>
                    <div class="search_tag">
                        <?= $this->escape($item["msg"]) ?>
                        <?php 
                        $conf_areas = $this->constantes->areas;
                        $conf_nivel =  $this->constantes->nivel;
                        $conf_fechapub = $this->constantes->fechapub;
                        $conf_remuneracion = $this->constantes->remuneracion;
                        $conf_empresa = $this->constantes->empresa;
                        $conf_ubicacion = $this->constantes->ubicacion;
                        $conf_carrera = 'carrera';
                        $conf_discapacidad = $this->constantes->discapacidad;

                        $separador = $this->constantes->separador;
                        $filtros2 = array();
                        foreach ($this->msg_facets as $item2) {
                            
                            if ($item2['param'] == $conf_areas) { //areas                                
                                $filtros2['areas'] = str_replace($item['filtro'], '', $item2['filtro']);
                                $filtros2[$conf_areas] = ($filtros2[$conf_areas] == '') ? null : $filtros2[$conf_areas];
                                
                            }
                            
                            if ($item2['param'] == $conf_nivel) { //nivel                                
                                $filtros2[$conf_nivel] = str_replace($item['filtro'], '', $item2['filtro']);
                                $filtros2[$conf_nivel] = ($filtros2[$conf_nivel] == '') ? null : $filtros2[$conf_nivel];                                
                            }
                            
                            if ($item2['param'] == $conf_fechapub) { //fechapub                                
                                $filtros2[$conf_fechapub] = str_replace($item['filtro'], '', $item2['filtro']);
                                $filtros2[$conf_fechapub] = ($filtros2[$conf_fechapub] == '') ? null : $filtros2[$conf_fechapub];
                                
                            }
                            if ($item2['param'] == $conf_remuneracion) { //remuneracion  
                                if ($item['filtro']=='1') {
                                    $filtros2[$conf_remuneracion] =$item2['filtro'];
                                } else {
                                    $filtros2[$conf_remuneracion] =  str_replace($item['filtro'], '', $item2['filtro']);
                                }
                                $filtros2[$conf_remuneracion] =  ($filtros2[$conf_remuneracion] == '') ? null : $filtros2[$conf_remuneracion]; 
                                
                            }
                            
                            if ($item2['param'] == $conf_empresa) { //empresa                                
                                $filtros2[$conf_empresa] = str_replace($item['filtro'], '', $item2['filtro']);
                                $filtros2[$conf_empresa] = ($filtros2[$conf_empresa] == '') ? null : $filtros2[$conf_empresa];                                
                            }
                            
                            if ($item2['param'] == $conf_ubicacion) { //ubicacion                                
                                $filtros2[$conf_ubicacion] = str_replace($item['filtro'], '', $item2['filtro']);
                                $filtros2[$conf_ubicacion]  = ($filtros2[$conf_ubicacion] == '') ? null : $filtros2[$conf_ubicacion];
                                
                            }
                            if ($item2['param'] == $conf_carrera) { //carrera                                
                                $filtros2[$conf_carrera] = str_replace($item['filtro'], '',$item2['filtro']);
                                $filtros2[$conf_carrera] = ($filtros2[$conf_carrera] == '') ? null : $filtros2[$conf_carrera];
                                
                            }
                            if ($item2['param'] == $conf_discapacidad) { //discapacidad      
                                $filtros2[$conf_discapacidad] = str_replace($item['filtro'], '',$item2['filtro']);
                                $filtros2[$conf_discapacidad] = ($filtros2[$conf_discapacidad] == '') ? null : $filtros2[$conf_discapacidad];
                                
                            }
                        }
                        $ruta = $this->url($filtros2, 'buscar', false);
                        ?>                        
                        <a class="search_tag_close" href="<?= $ruta ?>">x</a>
                    </div>                  
                <?php endforeach; ?>
                  </div>
              <?php endif; ?>
                
            
            <div class="jobs_ads_results_info"><span><?= $this->mostrando ?></span><span class="jobs_ads_extra"><span class="info_modal_search">Atención</span><span class="font_size_manage"><i class="smaller_font">A-</i><i class="bigger_font">A+</i></span></span></div>
            
            
            
            <div class="jobs_ads_results_wrapper">
              <div class="search_waiting_confirm"></div>
              <div class="search_modal">
                <p>Haz clic en buscar cuando hayas terminado de seleccionar tus filtros.</p>
                <div><a href="javascript:;" title="buscar" class="btn btn_tertiary btn_filter_search tracking" data-track-strategy="normal_search">Buscar <i class="icon icon_lens"></i></a></div><i class="close_modal">X</i>
              </div>
              <?php if ($this->totalPage==0) { ?>
                <div class="no_records_found">
                    <p>No se encontró ofertas laborales en relación a su búsqueda.</p>
                    <p><a href="<?=SITE_URL; ?>/buscar/" title="Limpiar busqueda">Limpiar mi búsqueda</a></p>
                </div>            
              <?php } ?>
              <?php if (count($this->anuncioswebs)>0) : ?>
              <?php $cont = 0;
              foreach ($this->anuncioswebs as $item) : ?>   
              
              <?php if ($cont==2) { ?>
<!--              <div class="eplanning row" data-section="Middle"></div>-->
              <?php } ?>
              
              <?php
                    $urlA = explode('/',str_replace('http://','',$item['url'])); 
//                    $url = SITE_URL.'/'.$urlA[1]."/".$urlA[2];
                    $url = SITE_URL.'/'.$urlA[1]."/".$item['slug']."--".App_Util::validateSlugEmpresa($item['empresaslug'],$item['mostrar_empresa'])."--".$item['ubicacionslug']."-".$item['url_id'];
                    $logo = ($item["logoanuncio"] == "" || $item['logoanuncio']
                                    == " " || $item["logoanuncio"] == NULL) ?
                                    $this->verLogoDefecto ? $this->S('/images/' . $this->logoDefecto)
                                            : ''  : ELEMENTS_URL_LOGOS . $item["logoanuncio"].$this->E()->getLastCommit();
                                        
//                    $destacado = ($item['prioridad'] <= EMPLEOBUSCO_BUSQUEDA_DESTACADOS);                                        
                    $destacado = $item['destacado'];
              ?>
              
            <a class="jobs_ads <?php echo ($destacado ? 'jobs_ads_highlight_job' : ''); ?>"  href="<?php echo $url ?>" title="<?= $item["empresa_rs"] ?>" title="<?= $this->escape($item["puesto"]) ?>" >
                <?=($destacado) ? '<span class="top_job_offer"><i class="icon icon_snood"></i><span>DESTACADO</span></span>' : '';?>
                <div class="row">
                  <div class="jobs_ads_image_container">
                    <div class="center_image"><img src="<?=$logo?>" alt="<?= $item["empresa_rs"] ?>" width="87" height="87"></div>
                  </div>
                  <div class="jobs_ads_description">
                    <h3><?= $this->escape($item["puesto"]) ?></h3>
                        
                    <?php if (isset($item['empresaslug'])) { ?>
                    <span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?= $this->escape($item['empresa_rs']) ?>">
                        <?= $this->escape($item['empresa_rs']) ?>
                    </span>
                    <?php } else { ?>
                    <span title="<?= $this->escape($item['empresa_rs']) ?>">
                        <?= $this->escape($item['empresa_rs']) ?>
                    </span>
                    <?php }  ?>
                                                                    
                    <p><?php echo mb_substr($this->escape($item["description"]), 0,$this->recortaraviso, 'utf-8') . " ..."?></p>
                    <p class="search_address"><i class="icon icon_location"></i><?= $item["ubicacion"]; ?></p>
                   
                  </div>
                  <div class="jobs_ads_options_wrapper">
                    <div class="jobs_ads_options">                              
                        <span>Hace <?php 
                        $z = substr($item["dias_fp"], -1); 
                        $n = substr($item["dias_fp"], 0, -1);
                        $t = array('s'=>'segundos','m'=>'minutos','h'=>'horas','d'=>'días');
                        if($n == '1')
                            $tt = substr($t[$z], 0, -1);
                        else
                            $tt = $t[$z];
                        echo $n.' '.$tt;
                        ?>   </span>                                        
                    </div>
                  </div>
                </div>
            </a>
              <?php $cont++;
              endforeach; ?>
              <?php endif; ?>
                           
                  <div class="search_results_pagination mt30">
                    <?=
                        $this->partial('buscar/_pag.phtml',
                            array('totalPage' => $this->totalPage, 'pageActual' => $this->pageActual,
                            'isfoot' => true));
                    ?>
                </div>
            </div>
          </div>
        </div>
        

    
          
          
      </div>
    </section>
<div class="page_modal hide information_modal" id="informationModal"><h3>Atención</h3><p>"Estimado Postulante, por su seguridad recomendamos no enviar documentación personal a las empresas. Además, no realice ningún pago previo a iniciar un proceso de selección. En caso detecte empresas de este tipo, agradecemos notificarnos inmediatamente."</p></div>
