<?php
$conf_areas = $this->constantes->areas;
$conf_nivel = $this->constantes->nivel;
$conf_fechapub = $this->constantes->fechapub;
$conf_remuneracion = $this->constantes->remuneracion;
$conf_empresa = $this->constantes->empresa;
$conf_ubicacion = $this->constantes->ubicacion;
$conf_carrera = 'carrera';
$separador = $this->constantes->separador;
$conf_discapacidad = $this->constantes->discapacidad;
$filtros3 = array();
$filtros3['pais'] = 'peru';
$filtros3['pais'] = ($filtros3['pais'] == '') ? null : $filtros3['pais'];
foreach ($this->msg_facets as $item2) {
    // if ($item2['param'] == 'pais') { //pais
    //}

    if($item2['param'] == $conf_areas) { //areas
        $filtros3['areas'] = $item2['filtro'];
        $filtros3[$conf_areas] = ($filtros3[$conf_areas] == '') ? null : $filtros3[$conf_areas];
    }

    if($item2['param'] == $conf_nivel) { //nivel
        $filtros3[$conf_nivel] = $item2['filtro'];
        $filtros3[$conf_nivel] = ($filtros3[$conf_nivel] == '') ? null : $filtros3[$conf_nivel];
    }

    if($item2['param'] == $conf_fechapub) { //fechapub
        $filtros3[$conf_fechapub] = $item2['filtro'];
        $filtros3[$conf_fechapub] = ($filtros3[$conf_fechapub] == '') ? null : $filtros3[$conf_fechapub];
    }

    if($item2['param'] == $conf_remuneracion) { //remuneracion
        $filtros3[$conf_remuneracion] = $item2['filtro'];
        $filtros3[$conf_remuneracion] = ($filtros3[$conf_remuneracion] == '') ? null : $filtros3[$conf_remuneracion];
    }

    if($item2['param'] == $conf_empresa) { //empresa
        $filtros3[$conf_empresa] = $item2['filtro'];
        $filtros3[$conf_empresa] = ($filtros3[$conf_empresa] == '') ? null : $filtros3[$conf_empresa];
    }

    if($item2['param'] == $conf_ubicacion) { //ubicacion
        $filtros3[$conf_ubicacion] = $item2['filtro'];
        $filtros3[$conf_ubicacion] = ($filtros3[$conf_ubicacion] == '') ? null : $filtros3[$conf_ubicacion];
    }

    if($item2['param'] == $conf_carrera) { //carrera
        $filtros3[$conf_carrera] = $item2['filtro'];
        $filtros3[$conf_carrera] = ($filtros3[$conf_carrera] == '') ? null : $filtros3[$conf_carrera];
    }
}
$ruta3 = $this->url($filtros3, 'buscar', true);
?>
<section class="busqueda">
    <div class="container">
        <div class="row">
            <div class="col-md-3 filter_bar">
                <form id="" method="POST" action="<?php echo $ruta3 ?>">
                    <div class="mg-bt-10">
                        <a href="#" class="list-group-item active">Tu Búsqueda</a>
                    </div>
                    <small>Busca por descripción del puesto o código impreso</small>
                    <div class="search_form text-center">
                        <input class="txt_search" type="text" name="q" id="q" tabindex="1" value="<?php echo htmlspecialchars($this->query) ?>" maxlength="60" id=""/>
                        <button id="buscar" type="submit" class="btn" data-track-strategy="normal_search">Buscar</button>
                    </div>
                    <input id="pais" name="pais" type="hidden" value="<?php echo $this->pais ?>" />
                </form>

                <?= $this->partialLoop('buscar/_filtro.phtml', $this->dataFiltros) ?>

                <? //=$this->partialLoop('buscar/_filtro-old.phtml', $this->dataFiltros) ?>
            </div>


            <div class="col-md-9">
                <div class="grid_search_results">

                </div>

                <small><?php echo $this->mostrando ?></small>
                <!--                <div class="right">
                                                                  <a href="#"><small>Atención</small></a>
                                                                  <a href="#"><i class="fa fa-search-plus azul" aria-hidden="true"></i></a>
                                                                  <a href="#"><i class="fa fa-search-minus amarillo" aria-hidden="true"></i></a>
                                                         </div>
                -->
                <div class="resultados">

                    <div class="search_modal" style="display:none;">
                        <p>Haz clic en buscar cuando hayas terminado de seleccionar tus filtros.</p>
                        <div><a href="javascript:;" title="buscar" class="btn btn_tertiary btn_filter_search tracking" data-track-strategy="normal_search">Buscar <i class="icon icon_lens"></i></a></div><i class="close_modal">X</i>
                    </div>

                    <?php
                    $cont = 0;
                    foreach ($this->anuncioswebs as $item) :
//var_dump($item); die(" -------- ");
                        $eliminar = array("!", "·", "$", "%", "&", "/", "(", ")", "=", "?", "¿", "¡");
                        $item['empresaslug'] = str_replace($eliminar, "", $item['empresaslug']);

                        $urlA = explode('/', str_replace('http://', '', $item['url']));

                        $url = SITE_URL . '/' . $urlA[1] . "/" . $item['slug'] . "--" . App_Util::validateSlugEmpresa($item['empresaslug'], $item['mostrar_empresa']) . "--" . $item['ubicacionslug'] . "-" . $item['url_id'];

                        $logo = ($item["logoanuncio"] == "" || $item['logoanuncio'] == " " || $item["logoanuncio"] == NULL) ?
                                $this->verLogoDefecto ? $this->S('/eb/img/' . $this->logoDefecto) : '' : ELEMENTS_URL_LOGOS . $item["logoanuncio"] . $this->E()->getLastCommit();
                        $destacado = $item['destacado'];
                        $prioridad = $item['prioridad'];
                        //  var_dump($item['prioridad']);
                        switch($item['prioridad']) {
                            case 1:
                                $_medal = "medal1.svg";
                                $_class = "-a";
                                break;

                            case 2:
                                $_medal = "medal2.svg";
                                $_class = "-b";
                                break;

                            case 3:
                                $_medal = "medal3.svg";
                                $_class = "-c";
                                break;

                            default:
                                $_medal = "";
                                $_class = "";
                                break;
                        }
                        ?>

                        <div class="resultados-box">
                            <?php if(!empty($_medal)): ?>
                                <div class="box-star right-two">
                                    <img src="<?php echo $this->S('/eb/svg/' . $_medal); ?>" alt="" class="bandera right">
                                </div>
                            <?php endif ?>

                            <div class="contenedor<?php echo $_class ?>">
                                <a href="<?php echo $url ?>">
                                    <div class="media">
                                        <div class="contenedor-height-img">
                                            <img src="<?php echo $logo ?>" alt="<?php echo $item["empresa_rs"]; ?>" class="img-center">
                                        </div>

                                        <div class="media-body">
                                            <h4><?php echo $this->escape($item["puesto"]); ?> </h4>
                                            <p class="azul mg-b-0"><?php echo $this->escape($item['empresa_rs']); ?></p>
                                            <small>
                                                <i class="fa fa-clock-o" aria-hidden="true"></i>
                                                Hace
                                                <?php
                                                $z = substr($item["dias_fp"], -1);
                                                $n = substr($item["dias_fp"], 0, -1);
                                                $t = array('s' => 'segundos', 'm' => 'minutos', 'h' => 'horas', 'd' => 'días');
                                                if($n == '1')
                                                    $tt = substr($t[$z], 0, -1);
                                                else
                                                    $tt = $t[$z];
                                                echo $n . ' ' . $tt;
                                                ?>
                                                <span>|</span>
                                                <i class="fa fa-map-marker" aria-hidden="true"></i>
                                                <?php echo $item["ubicacion"]; ?></small>
                                            <p class="parrafo">
                                                <?php echo mb_substr($this->escape($item["description"]), 0, $this->recortaraviso, 'utf-8') . " ..." ?></p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <hr>
                        </div>

                        <?php
                        $cont++;
                    endforeach;
                    ?>

                    <nav>
                        <?=
                        $this->partial('buscar/_pag.phtml', array('totalPage' => $this->totalPage, 'pageActual' => $this->pageActual,
                            'isfoot' => true));
                        ?>
                    </nav>


                </div>
            </div>
        </div>
    </div>
</section>
