<div class="bgAll gridS20">
	<div class="gridForm">
		<div class="legend">
			<a href="<?=$this->url(array('controller'=>'home','action'=>'index'),false,true)?>">Inicio</a> » <span class="noLink">Publica un aviso</span>
		</div>
		<h2 class="titleOrig">Datos del puesto</h2>
		<blockquote id="modStepsForm"><img src="<?= $this->S('/images/bgSteps2.png'); ?>" alt="Paso 2" /></blockquote>
		<div class="gridIForm resG">
			<div id="innerMain" class="center">
				<div id="content" class="formRegister">
					<div id="cntDataRelF">
						<p id="infoRelF" class="alignR txtReq right bold">Los datos con <span class="req">*</span> son obligatorios</p>
					</div>
					<div id="formReg">
					<form action="" id="fStep2" method="post" class="fStep2">
						<h6 class="titleDiv onAcor">Datos del puesto <span class="icoArrowP onAct"></span></h6>
						
						<div id="datosF" class="feildset r2 open" rel="<?=count($this->formExperiencia)-1?>">
							<div id="expeDisabled" class="fieldDisabled">
								<fieldset id="contentFromDat" class="flt">
	    						<?php echo $this->partial('publica-aviso/_datos_paso2.phtml', 'empresa'
	    						    , array('form' => $this->form
	    						    , 'isDato' => $this->isDato)); ?>
								</fieldset>
							</div>
						</div>
						
						<h6 class="titleDiv onAcor">Estudios <span class="icoArrowP onAct"></span></h6>
						<div id="studyF" class="feildset r2 open" rel="<?=count($this->formEstudio)-1?>">
							<div id="estudyDisabled" class="fieldDisabled<?=($this->isEstudio == true || !isset($this->isExperiencia))?'':' hide'?>">
								<fieldset id="contentFromEst" class="flt">
    							<?php foreach($this->formEstudio as $indEst => $formEstudio) : ?>
    							<?php echo $this->partial('publica-aviso/_estudio_paso2.phtml', 'empresa'
    							    , array('form' => $formEstudio
    							    , 'manager' => $this->managerEstudio
    							    , 'indice' => $indEst
    							    , 'isEstudio' => $this->isEstudio)); ?>
    							<?php endforeach; ?>
								</fieldset>
								<fieldset class="asideAds send2 btnImg alignR all">
									<a id="btnEst" rel="sectionEst" href="#studyF" class="right inactive btnPink"><span class="hide">Añadir otros estudios</span></a>
									<span id="msgErrorStudy" class="right error"></span>
								</fieldset>
							</div>
						</div>
						
						<h6 class="titleDiv onAcor">Experiencia <span class="icoArrowP onAct"></span></h6>
						<div id="experienceF" class="feildset r2 open" rel="<?=count($this->formExperiencia)-1?>">
							<div id="expeDisabled" class="fieldDisabled<?=($this->isExperiencia == true || !isset($this->isExperiencia))?'':' hide'?>">
								<fieldset id="contentFromExp" class="flt">
	    						<?php foreach($this->formExperiencia as $indExp => $formExperiencia) : ?>
	    						<?php echo $this->partial('publica-aviso/_experiencia_paso2.phtml', 'empresa'
	    						    , array('form' => $formExperiencia
	    						    , 'manager' => $this->managerExperiencia
	    						    , 'indice' => $indExp
	    						    , 'isLinkedin' => $this->isLinkedin
	    						    , 'isExperiencia' => $this->isExperiencia)); ?>
	    						<?php endforeach; ?>
								</fieldset>
								<fieldset class="asideAds send1 btnImg alignR all">
									<a id="btnExp" rel="sectionExp" href="#experienceF" class="right inactive btnPink"><span class="hide">Añadir otra experiencia</span></a>
									<span id="msgErrorF" class="right error"></span>
								</fieldset>
							</div>
						</div>
						
						<h6 class="titleDiv offAcor">Idiomas <span class="icoArrowP onAct"></span></h6>
						<div id="languagesF" class="feildset r2 open" rel="<?=count($this->formIdioma)-1?>">
							<div id="checkInv3" class="checkInv hide"></div>	
							<div id="langDisabled" class="fieldDisabled">
								<fieldset id="contentFromLang" class="flt">
								<?php foreach($this->formIdioma as $indIdi => $formIdioma) : ?>
								<?php echo $this->partial('publica-aviso/_idioma_paso2.phtml', 'empresa'
								    , array('form' => $formIdioma
								    , 'manager' => $this->managerIdioma
								    , 'indice' => $indIdi
								    , 'isLinkedin' => $this->isLinkedin
								    , 'isIdioma' => $this->isIdioma)); ?>
								<?php endforeach; ?>
								</fieldset>
								<fieldset class="asideAds send3 btnImg alignR all">
									<a id="btnIdi" rel="sectionIdi" href="#languagesF" class="right inactive btnPink"><span class="hide">Añadir idioma</span></a>
									<span id="msgErrorLang" class="right error"></span>
								</fieldset>
							</div>
						</div>
						
						<h6 class="titleDiv offAcor">Programas de computadora <span class="icoArrowP onAct"></span></h6>
						<div id="programsF" class="feildset r2 open" rel="<?=count($this->formPrograma)-1?>">
							<div id="checkInv4" class="checkInv hide"></div>
							<div id="progDisabled" class="fieldDisabled">
								<fieldset id="contentFromPro" class="flt">
									<?php foreach($this->formPrograma as $indProg => $formPrograma) : ?>
									<?php echo $this->partial('publica-aviso/_programa_paso2.phtml', 'empresa'
									    , array('form' => $formPrograma
									    , 'manager' => $this->managerPrograma
									    , 'indice' => $indProg
									    , 'isPrograma' => $this->isPrograma)); ?>
									<?php endforeach; ?>
								</fieldset>
								<fieldset class="asideAds send4 btnImg alignR all">
									<a id="btnPro" rel="sectionPro" href="#programsF" class="right inactive btnPink"><span class="hide">Añadir otro programa</span></a>
									<span id="msgErrorProg" class="right error"></span>
								</fieldset>
							</div>
						</div>
						
						<h6 class="titleDiv offAcor">Enviar preguntas al candidato <span class="icoArrowP onAct"></span></h6>
						<div id="preguntasF" class="feildset r2 open" rel="<?=count($this->formPregunta)-1?>">
							<div id="checkInv4" class="checkInv hide"></div>
							<div id="progDisabled" class="fieldDisabled">
								<fieldset id="contentFromPre" class="flt">
									<?php foreach($this->formPregunta as $indPreg => $formPregunta) : ?>
									<?php echo $this->partial('publica-aviso/_pregunta_paso2.phtml', 'empresa'
									    , array('form' => $formPregunta
									    , 'manager' => $this->managerPregunta
									    , 'indice' => $indPreg
									    , 'isPrograma' => $this->isPrograma)); ?>
									<?php endforeach; ?>
								</fieldset>
								<fieldset class="asideAds send4 btnImg alignR all">
									<a id="btnPro" rel="sectionPre" href="#preguntasF" class="right inactive btnPink"><span class="hide">Añadir otro programa</span></a>
									<span id="msgErrorPreg" class="right error"></span>
								</fieldset>
							</div>
						</div>
						<fieldset class="asideAds send6 btnImg alignR all"> 
							<input id="aSetep2" class="right active btnPink" type="submit" value=""/> 
							<a id="btnBack" class="right f14 btnPink" href="<?=$this->url(array('controller'=>'registro','action'=>'paso1'),false,true)?>">Regresar</a> 
							<span id="msgErrorStep2" class="right error"></span>
						</fieldset>
					</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

