<div class="paginator all">
    <?php if ($this->pageCount) { ?>
        <ul class="pagUl all theta alignR right">
            <?php
            /*
             if (isset($this->previous)) {

                $params = array('page' => $this->first);
                echo '<li class="itemPag firstNextP">« <a class="linkPag firstP" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '#anclaPag">Primero</a></li>';
            }
            */
            if($this->pageCount > 1){
                if (isset($this->previous)) {
                    $params = array('pagina' => $this->previous);
                    echo '<li class="itemPag prevPag"><a rel="'.$this->previous.'" class="linkPag first" href="' . $this->url($params) . '#anclaPag">&laquo; Anterior</a></li>';
                }else {
                    echo '<li class="itemPag prevPag"><a class="linkPag active">&laquo; Anterior</a></li>';
                }
            }
            //var_dump($this);
            echo '<li class="itemPag"><a class="linkPag active">Página</a></li>';
            $viewPages = array();
            if ($this->pageCount <= 5) {
                foreach ($this->pagesInRange as $page){
                    $viewPages[] = array('pagina' => $page, 'label' => $page);
                }
            } else {
                if($this->current <= $this->first + 3){
                    for ($i = $this->first; $i <= ($this->first + 3); $i++) {
                        $viewPages[] = array('pagina' => $i, 'label' => $i);
                    }
                    $viewPages[] = array('pagina' => $i, 'label' => "...");
                    $viewPages[] = array('pagina' => $this->last, 'label' => $this->last);
                }else if($this->current >= $this->last - 3){
                    $viewPages[] = array('pagina' => $this->first, 'label' => $this->first);
                    $viewPages[] = array('pagina' => ($this->last - 4), 'label' => "...");
                    for ($i = ($this->last - 3); $i <= $this->last; $i++) {
                        $viewPages[] = array('pagina' => $i, 'label' => $i);
                    }
                }else{
                    $viewPages[] = array('pagina' => $this->first, 'label' => $this->first);
                    if ($this->first < ($this->current - 2)) {
                        $viewPages[] = array('pagina' => ($this->current - 2), 'label' => "...");
                    }

                    $viewPages[] = array('pagina' => ($this->current - 1), 'label' => ($this->current - 1));
                    $viewPages[] = array('pagina' => $this->current, 'label' => $this->current);
                    $viewPages[] = array('pagina' => ($this->current + 1), 'label' => ($this->current + 1));

                    if ($this->last > ($this->current + 2)) {
                        $viewPages[] = array('pagina' => ($this->current + 2), 'label' => "...");
                    }
                    $viewPages[] = array('pagina' => $this->last, 'label' => $this->last);
                }

            }
            ?>
            
            <? foreach ($viewPages as $page): ?>
                <?php 
                    $params = array('pagina' => $page['pagina']);
                    if (count($this->variables) > 0) {
                        $params = array_merge($this->variables, $params);
                    }
                
                ?>
                <? if ($page['pagina'] != $this->current): ?>
                    <li class="itemPag"><a rel="<?= $page['pagina']; ?>" href="<?= $this->url($params); ?>#anclaPag"><?= $page['label']; ?></a></li>
                    <?= $this->last == $page['pagina'] ? '' : '' ?>
                <? else: ?>
                    <li class="itemPag"><a class="linkPag active"><?= $page['label']; ?> <?= $this->last == $page['pagina'] ? '' : '' ?></a></li>
                <? endif; ?>
            <? endforeach; ?>

            <?
            if($this->pageCount > 1){
                if (isset($this->next)) {
                    $params = array('pagina' => $this->next);
                    if (count($this->variables) > 0) {
                        $params = array_merge($this->variables, $params);
                    }                                    
                    echo '<li class="itemPag nextPag"><a rel="'.$this->next.'" class="linkPag next" href="' . $this->url($params) . '#anclaPag">Siguiente &raquo;</a></li>';
                }else {
                    echo '<li class="itemPag nextPag"><a class="linkPag active">Siguiente &raquo;</a></li>';
                }
            }
            /*
            if (isset($this->next)) {
                $params = array('page' => $this->last);
                echo '<li class="itemPag lastNext"><a class="linkPag nextLastP" href="' . str_replace("/search-cmp/busqueda/", "/buscar/", $this->url($params)) . '#anclaPag">Último</a> »</li>';
            }
            */
            ?>
        </ul>

    <?php
    } else {
        echo '<div class="paginador all">';
        if($this->isfoot) {
            echo "<div class='pagUl grid8 theta alignC'> - No hay Avisos registrados </div>";
        }
    	echo '</div>';
    }
    ?>
</div>