<!DOCTYPE html>
<html lang="es" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://ogp.me/ns/fb#">
  <head>
	 <meta charset="utf-8">
	 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	 <meta name="language" content="es">
	 <title>AquiEmpleos – Encuentra tu pasión</title>
	 <link rel="canonical" href="<?=SITE_URL?>/encuentra-tu-pasion">
	 <meta name="title" content="AquiEmpleos – Encuentra tu pasión">
	 <meta name="description" content="Descarga la canción que estabas buscando – “AquiEmpleos All Right”. No busques trabajo, encuentra tu pasión | aquiempleos.com.">
	 <meta name="author" content="aquiempleos.com">
	 <meta name="DC.Title" content="AquiEmpleos – Encuentra tu pasión">
	 <meta name="DC.Contributor" content="aquiempleos.com">
	 <meta name="DC.Creator" content="aquiempleos.com">
	 <meta name="DC.Description" content="Descarga la canción que estabas buscando – “AquiEmpleos All Right”. No busques trabajo, encuentra tu pasión | aquiempleos.com.">
	 <meta name="DC.Language" content="es">
	 <meta name="DC.Publisher" content="Publisher">
	 <meta name="geo.placename" content="Cercado de Lima">
	 <meta name="geo.position" content="-12.0478;-77.0622">
	 <meta name="geo.region" content="PE-LIM">
	 <meta name="ICBM" content="-12.0478, -77.0622">
	 <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	 <meta name="robots" content="index,follow">
	 <meta name="robots" content="noodp,noydir">
	 <meta name="keywords" content="AquiEmpleos, Ofertas de trabajo, Bolsas de trabajo, avisos de trabajo, empleos peru, buscar empleo, AquiEmpleos empleo, búsqueda de empleo, búsqueda de trabajo, empleo La Prensa">
	 <meta property="og:description" content="Descarga la canción que estabas buscando – “AquiEmpleos All Right”. No busques trabajo, encuentra tu pasión | aquiempleos.com.">
	 <meta property="og:image" content="<?=MEDIALANDING?>images/logo_fb.jpg<?=$this->E()->getLastCommit()?>">
	 <meta property="og:image:height" content="250">
	 <meta property="og:image:type" content="image/jpg">
	 <meta property="og:image:width" content="250">
	 <meta property="og:site_name" content="Encuentra tu pasión">
	 <meta property="og:title" content="AquiEmpleos – Encuentra tu pasión">
	 <meta property="og:type" content="website">
	 <meta property="og:url" content="<?=SITE_URL?>/encuentra-tu-pasion">
	 <meta name="twitter:card" content="summary">
	 <meta name="twitter:site" content="@AquiEmpleosempleos">
	 <meta name="twitter:title" content="AquiEmpleos – Encuentra tu pasión">
	 <meta name="twitter:description" content="Descarga la canción que estabas buscando – “AquiEmpleos All Right”. No busques trabajo, encuentra tu pasión | aquiempleos.com.">
	 <meta name="twitter:image" content="<?=MEDIALANDING?>images/logo_fb.jpg<?=$this->E()->getLastCommit()?>">
	 <link href="<?=MEDIALANDING?>css/layout/fonts.css<?=$this->E()->getLastCommit()?>" media="all" rel="stylesheet" type="text/css">
	 <link href="<?=MEDIALANDING?>css/layout/layout.css<?=$this->E()->getLastCommit()?>" media="all" rel="stylesheet" type="text/css">
	 <link href="<?=MEDIALANDING?>css/views/index.css<?=$this->E()->getLastCommit()?>" media="all" rel="stylesheet" type="text/css">
	 <link href="<?=MEDIA_URL?>/main/img/favicon.ico<?=$this->E()->getLastCommit()?>" rel="icon" type="image/vnd.microsoft.icon">
	 <link href="<?=MEDIA_URL?>/main/img/favicon.ico<?=$this->E()->getLastCommit()?>" rel="shortcut icon" type="image/vnd.microsoft.icon">
	 <link href="<?=MEDIA_URL?>/main/img/favicon.ico<?=$this->E()->getLastCommit()?>" rel="shortcut icon" type="image/x-icon">
	 <link href="<?=MEDIALANDING?>images/logo_fb.jpg<?=$this->E()->getLastCommit()?>" rel="image_src" type="image/jpeg"><!--[if lte IE 9]>
	 <link href="<?=MEDIALANDING?>css/ie/ie.css<?=$this->E()->getLastCommit()?>" media="all" rel="stylesheet" type="text/css">
	 <script src="<?=MEDIALANDING?>js/libs/selectivizr/selectivizr.js<?=$this->E()->getLastCommit()?>"></script>
	 <script src="<?=MEDIALANDING?>js/libs/html5shiv/dist/html5shiv.min.js<?=$this->E()->getLastCommit()?>"></script><![endif]-->
  </head>
  <script type="text/javascript">
	 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	 ga('create', 'UA-54051215-1', 'auto');
	 ga('require', 'displayfeatures');
	 ga('send', 'pageview');
  </script>
  <body data-image-mobile-src="<?=MEDIALANDING?>images/landing_mobile.jpg" data-image-src="<?=MEDIALANDING?>images/landing.jpg" style="background-image: url(<?=MEDIALANDING?>images/landing<?=($this->Util()->isMobile())?'_mobile':''?>_lq.jpg)">
	 <header>
		<div class="center_box">
		  <div class="left_wrapper"><a href="http://EMPLEOBUSCO.com/" target="_blank" class="lnk_go_page">Ir a aquiempleos.com</a></div>
		  <div data-url="<?=SITE_URL?>/encuentra-tu-pasion" data-title="AquiEmpleos – Encuentra tu pasión" class="right_wrapper"><span>Compártelo</span>
			 <button class="twitter"><i class="icon icon_twitter"></i></button>
			 <button class="fb"><i class="icon icon_facebook"></i></button>
			 <button class="linkedin"><i class="icon icon_linkedin"></i></button>
		  </div>
		  <div class="center_wrapper hide animation"><i data-box="wave" class="icon icon_wave selected"></i><i data-box="video" class="icon icon_video"></i><i data-box="search" class="icon icon_search"></i></div>
		</div>
	 </header>
	 <h1 class="hide">Encuentra tu Pasión</h1>
	 <div class="main_box center_box"><span class="util_middle"></span>
		<div class="landing row">
		  <div class="logo_box row">
			 <div class="slidein animation row"><a href="http://EMPLEOBUSCO.com/" target="_blank"><img src="<?=MEDIALANDING?>images/logo.svg" width="264" class="mb10"><img src="<?=MEDIALANDING?>images/com.svg" width="120" class="mb20"></a></div>
			 <div class="logo_box_title slidein animation"><span class="mb10">encuentra</span><span class="mb10 second">tu</span><span>pasión</span></div>
		  </div>
		  <div class="row items_box">
			 <div class="wave_box items row">
				<div class="item_music bounceInLeft animation is_selected">
				  <div class="item_header"><i data-box="wave" class="icon icon_wave"></i>
					 <h2 data-box="wave">Descargar "AquiEmpleos Alright"</h2>
				  </div>
				  <div class="item_footer"><a href="<?=SITE_URL.'/encuentra-tu-pasion/descarga/token/'. $this->token.'/tipo/mp3';?>">DESCARGAR MP3</a><a href="<?=SITE_URL.'/encuentra-tu-pasion/descarga/token/'. $this->token.'/tipo/ringtone'?>">DESCARGAR RINGTONE</a><a href="" class="track">
						<div class="track_content">
						  <p class="text">ESCUCHAR PREVIEW</p>
						  <div class="progress-bar">
							 <div class="bars"></div>
						  </div>
						</div><i class="icon icon_play"></i></a>
					 <audio preload="auto" class="audioPreview">
						<source src="<?=$this->ruta;?>" type="audio/mpeg">  Tu navegador no soporta la etiqueta audio.
					 </audio>
				  </div>
				</div>
				<div class="bounceInLeft animation">
				  <div class="item_header"><i data-box="video" class="icon icon_video"></i>
					 <h2 data-box="video">Ver video</h2>
				  </div>
				</div>
				<div class="bounceInLeft animation">
				  <div class="item_header"><i data-box="search" class="icon icon_search"></i>
					 <h2 data-box="search">Buscar empleo</h2>
				  </div>
				</div>
			 </div>
			 <div class="search_box hide">
				<div class="input_box">
				  <input type="text" placeholder="Busca por área o puesto" class="disable_especial_characters">
				  <button><i class="icon icon_search"></i></button>
				</div>
				<h3>Más de <span>3 mil </span>empresas publicando en más de <span>16 mil </span>avisos activos</h3>
			 </div>
			 <div class="video_box hide">
				<div id="player"></div>
			 </div>
		  </div>
		</div>
	 </div>
	 <footer></footer>
	 <script type="text/javascript">var tmp = {baseHost: '<?=SITE_URL?>/encuentra-tu-pasion'}</script>
	 <script src="<?=MEDIALANDING?>js/libs/jquery/dist/jquery.min.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
	 <script src="<?=MEDIALANDING?>js/libs/utils.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
	 <script src="<?=MEDIALANDING?>js/libs/jquery.vide.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
	 <script src="<?=MEDIALANDING?>js/libs/devicejs/lib/device.min.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
	 <script src="<?=MEDIALANDING?>js/libs/jquery-alphanum/jquery.alphanum.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
	 <script src="<?=MEDIALANDING?>js/sections/home/home.js<?=$this->E()->getLastCommit()?>" type="text/javascript"></script>
  </body>
</html>
