<?php
$tieneSugeridos = isset($this->avisosSugerencias['data']) && count($this->avisosSugerencias["data"]);
$existeError = isset($this->avisosSugerencias['error']);
$tieneAreas = isset($this->avisosSugerencias['params']) && $this->avisosSugerencias['params'] == 0 ? false : true;
?>
<!--<div class="eplanning advertisement" data-section="Right1"></div>-->
<div class="suggested_aside">
  <div class="suggested_jobs_title">Te sugerimos <?=isset($this->avisosSugerencias["ntotal"])?$this->avisosSugerencias["ntotal"]:0  ?> puestos de acuerdo a tu perfil
	 <a id="btnSlider" href="/avisos-sugeridos" class="btn btn_desplegate">+</a>
  </div>
  <ul class="suggested_tabs_header">
	 <li class="is_active" data-rel="sugerencia"><i class="icon icon_reload"></i><span class="number"><?=isset($this->avisosSugerencias["ntotal"])?$this->avisosSugerencias["ntotal"]:0  ?></span> <span>Sugerencias</span></li>
	 <li data-rel="favoritos"><i class="icon icon_star"></i><span class="number"></span> <span>Favoritos</span></li>
	 <li data-rel="eliminados"><i class="icon icon_delete2"></i><span class="number"></span> <span>Eliminados</span></li>
  </ul>

  <?php if ($tieneSugeridos) { ?>
  <div class="suggested_tabs_content">
	 <ul>
		<?php foreach($this->avisosSugerencias["data"] as $item) {
				$logo = (!empty($item["logoanuncio"]) || $item["logoanuncio"] != NULL || $item["logoanuncio"] != '') ? ELEMENTS_URL_LOGOS . $item["logoanuncio"].$this->E()->getLastCommit():$this->S('/images/icon-empresa-blank.png' ) ;
				$url = SITE_URL . $item['url'];
		  ?>
		<li>
		  <a class="jobs_ads <?php echo ( $item['destacado']? 'jobs_ads_highlight_job' : ''); ?>"  href="<?php echo $url ?>" title="Ver aviso">
			 <?=($item['destacado']) ? '<span class="top_job_offer"><i class="icon icon_snood"></i><span>DESTACADO</span></span>' : '';?>
			 <div class="row smb">
			 <div class="jobs_ads_image_container">
				<div class="center_image"><img src="<?=$logo?>" alt="<?= $item["empresa_rs"] ?>" width="87" height="87"></div>
			 </div>
			 <div class="jobs_ads_description">
				<h3><?=$item['puesto']?></h3>
				<?php if (isset($item['empresaslug'])) { ?>
				<span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
				<?php } else { ?>
				<span title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
				<?php }  ?>
				<p class="search_address"><i class="icon icon_location"></i><?= $item["ubicacion"]; ?></p>
			 </div>

			 <div class="jobs_ads_options_wrapper">
				<div class="jobs_ads_options">
				<span><?= $item["dias_fp"] ?></span>
				<button class="btn btn_hightlight" data-page="<?=$this->paginaActual?>" data-id="<?=$item['id']?>" data-highlight="/avisos-sugeridos/agregar-favoritos-ajax" data-urlaviso="<?=$item['slugaviso']?>" title="<?=($this->tab == 'favoritos') ? "" : "Agregar a favoritos"  ?>">
				  <span class="btn_label"><i class="icon icon_star_hover animated paintStarAnimation<?=($this->tab == 'favoritos') ? " selected" : ""  ?>"></i></span>
				  <span class="btn_spinner tiny"></span>
				</button>
				<button class="btn btn_delete_ads" data-page="<?=$this->paginaActual?>" data-id="<?=$item['id']?>" data-del="/avisos-sugeridos/eliminar-anuncio-sugerido-ajax" title="Eliminar">
				  <span class="btn_label"><i class="icon icon_delete2"></i></span>
				  <span class="btn_spinner tiny"></span>
				</button>
				</div>
			 </div>

			 </div>
		  </a>
		</li>
		<?php }?>
	 </ul>
		<div class="suggested_job_see_more"><a href="/avisos-sugeridos" title="ver todos">Ver Todos</a></div>
	 </div>
  <?php } else { ?>
  <div class="suggested_tabs_content">
  <ul>
	 <li>
		<span class="helper_center"></span>
		<div class="not_enough_message">
		<?php if(!$tieneAreas) :?>
		  <p class="title">¿No tienes sugerencias?</p>
		  <p>AquiEmpleos te recomienda completar tus áreas de interés, tu ubicación y tus pretensiones salariales.</p>
		  <a class="btn btn_primary" href="<?=SITE_URL.'/registro/paso2'?>" title="Completa para cambiar tus sugerencias.">Completar</a>
		</div>
		<?php else : ?>
		 <p>No hay avisos sugeridos para mostrar.</p>
		  <a href="/mi-cuenta/mis-datos-personales" class="btn btn_primary">Ir a mi cuenta</a>
		<?php endif; ?>
	 </li>
  </ul>
  </div>
  <?php } ?>
</div>

<script id ="tplSuggestedJobs" type="text/template">
  <ul>
  <% _.each(items_list, function(item){ %>
	 <li>
	 <a class="jobs_ads<%=(item.ishighlight == 1) ? ' jobs_ads_highlight_job':'' %>" href="<%=item.url%>" title="Ver aviso">
		<span class="top_job_offer"><i class="icon icon_snood"></i><span>DESTACADO</span></span>
		<div class="row smb">
		  <div class="jobs_ads_image_container">
			 <div class="center_image"><img src="<%=item.image%>" alt="<%=item.company%>"></div>
		  </div>
		  <div class="jobs_ads_description">
			 <h3><%=item.title%></h3>
			 <span title="<%=item.company%>"><%=item.company%></span>
			 <!-- <p><%=item.content%></p> -->
			 <p class="search_address"><i class="icon icon_location"></i><%=item.ubigeo%></p>
		  </div>
		  <div class="jobs_ads_options_wrapper">
			 <div class="jobs_ads_options">
				<span><%=item.date%></span>
				<% if(action != "favoritos"){ %>
				<button class="btn btn_hightlight" data-urlaviso="<%=item.urlAviso%>" data-page="<%=item.page%>" data-id="<%=item.id%>" data-highlight="<%=urlHighlight%>" title="Agregar a favoritos">
				  <span class="btn_label"><i class="icon icon_star_hover animated paintStarAnimation"></i></span>
				  <span class="btn_spinner tiny"></span>
				</button>
				<% } %>
				<% if(action != "eliminados"){ %>
				<button class="btn btn_delete_ads" data-page="<%=item.page%>" data-id="<%=item.id%>" data-del="<%=urlDelete%>" title="Eliminar">
				  <span class="btn_label"><i class="icon icon_delete2"></i></span>
				  <span class="btn_spinner tiny"></span>
				</button>
				<% } %>
			 </div>
		  </div>
		</div>
	 </a>
	 </li>
  <% }) %>
  </ul>
  <div class="suggested_job_see_more"><a href="<%=vertodos%>" title="Ver todos">Ver Todos</a></div>
</script>
<?= $this->partial('avisos-sugeridos/_template.phtml',$this); ?>
