<div class="company_content">
  <h3 class="job_box_title"><?=$this->LookAndFeelColors['titulo_sidebar']?></h3>
  <div class="company_description"><?php if(!empty($this->LookAndFeelColors['youtube'])) :?>
    <div class="company_video">
      <div class="company_display_image">
        <img class="thumbnail_video" src="" data-videourl="<?=$this->LookAndFeelColors['youtube']?>" >
        <a class="btn_play" href="javascript:void(0);"><img src="https://www.radiotronics.com/images/icons/YouTube-social-icon_red_48px.png" alt="<?= $this->escape($this->aviso['nombre_empresa']); ?>"></a>
      </div>
      <div class="doesnt_show_vimeo">
        <h3 class="job_box_title">Lo sentimos</h3>
        <p>Tu navegador no permite reproducir este video :(</p>
      </div>
      <div class="company_display_video">
      </div>
    </div><?php endif;?>
    <p><?=$this->LookAndFeelColors['texto']?></p><?php if(!empty($this->LookAndFeelColors['img_seccion'])) :?>
    <img class="company_img" src="<?=$this->LookAndFeelColors['img_seccion'] ?>" alt="<?= $this->escape($this->aviso['nombre_empresa']); ?>"><?php endif;?>
  </div><?php if(count($this->anunciosRelacionados)>0){?>
  <h3 class="job_box_title">Más avisos de <?= $this->escape($this->aviso['nombre_empresa']); ?></h3>
  <div class="company_advertisement">
    <div class="suggested_aside">
      <div class="suggested_tabs_content">
        <ul><?php foreach ($this->anunciosRelacionados as $item): ?>
          <li><?php $logoAnuncio = (isset($item['logo'])) ? trim($item['logo']) : '';$logo = empty($logoAnuncio) ? $this->S('/images/' . $this->LogoDefecto)   :  ELEMENTS_URL_LOGOS . $logoAnuncio.$this->E()->getLastCommit();?>
            <a class="jobs_ads jobs_ads_highlight_job" href="<?=SITE_URL . $item['url']?>" title="Ver aviso">
            <?php if ($item['destacado']) { ?><span class="top_job_offer"><i class="icon icon_snood"></i><span>DESTACADO</span></span><?php } ?>
              <div class="row">
                <div class="jobs_ads_image_container">
                  <div class="center_image">
                    <img src="<?= $logo?>" alt="<?= $this->escape($item['empresa_rs']) ?>" width="87" height="87">
                  </div>
                </div>
                <div class="jobs_ads_description">
                  <h3><?= $item['puesto'] ?></h3>
                  <span title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
                  <p class="search_address"><?= $item["ubicacion"]; ?></p>
                </div>
                <div class="jobs_ads_options_wrapper">
                  <div class="jobs_ads_options">
                    <span><?= $item['dias_fp'] ?></span>
                    <?php if($this->auth['usuario']->rol=='postulante'): ?>
                    <button class="btn btn_hightlight" data-page="1" data-id="<?= $item["id"]; ?>" data-highlight="/avisos-sugeridos/agregar-favoritos-ajax" data-urlaviso="economico-platinum-EMPLEOBUSCO" title="Agregar a favoritos">
                      <span class="btn_label"><i class="icon icon_star_hover animated paintStarAnimation"></i></span>
                      <span class="btn_spinner tiny"></span>
                    </button>
                    <?php endif; ?>
                  </div>
                </div>
              </div>
            </a>
          </li>
          <?php endforeach; ?>
        </ul>
        <div class="suggested_job_see_more">
          <a class="btn bg_primary" href="<?=($this->auth['usuario']->rol=='postulante')?'/avisos-sugeridos':'/buscar/empresa/'.$this->aviso['slug_empresa'];?>" title="ver todos">Ver más avisos de la empresa</a>
        </div>
      </div>
    </div>
  </div><?php } ?>
</div>