<div class="suggested_aside">
  <div class="suggested_jobs_title">También te puede interesar estos puestos de trabajo.</div>
  <?/*Tienes <b><?=count($this->anunciosRelacionados)?></b> avisos relacionados a este puesto.*/?>

  <div class="suggested_tabs_content">
  <ul>
	 <?php foreach ($this->anunciosRelacionados as $item): ?>
	 <?php
	 $logoAnuncio = (isset($item['logo'])) ? trim($item['logo']) : '';
	 $logo = empty($logoAnuncio) ? $this->S('/images/' . $this->LogoDefecto)   :  ELEMENTS_URL_LOGOS . $logoAnuncio.$this->E()->getLastCommit();
	 ?>
	 <li>
		<a class="jobs_ads <?php //echo ( $item['destacado']? 'jobs_ads_highlight_job' : ''); ?>"
			href="<?=$this->url(array('slug' => $item['slug'],'empresaslug' => App_Util::validateSlugEmpresa($item['empresaslug'],$item['mostrar_empresa']),'ubicacionslug' => $item['ubicacionslug'],'url_id' => $item['url_id']), 'aviso_detalle', true)?>"
			title="Ver aviso" onClick="ga('send','event','Avisos de Empleo','oferta_sugerida','ingresar_<?= $this->escape($item['url_id']) ?>');">
		  <div class="row">
			 <div class="jobs_ads_image_container">
				<div class="center_image"><img alt="<?= $this->escape($item['empresa_rs']) ?>" src="<?= $logo?>" title="<?= $this->escape($item['empresa_rs']) ?>"> </div>
			 </div>
			 <div class="jobs_ads_description">
				<h3><?= $item['puesto'] ?></h3>

				<?php if (isset($item['empresaslug'])) { ?>
				<span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?=$item['empresa_rs']?>"><?=$item['empresa_rs']?></span>
				<?php } else { ?>
				<span title="<?=$item['empresa_rs']?>"><?=$item['empresa_rs']?></span>
				<?php }  ?>

				<p><?php echo mb_substr($this->escape($item["description"]), 0,50, 'utf-8') . " ..."?></p>
				<p class="search_address"><i class="icon icon_location"></i><?= $item["ubicacion"]; ?></p>
				<?php if ($this->PostuloAvisoRelacionado($item['id'])) : ?>
				  <span class="posit-ok">
					 <img style="margin: 0 5px;" src='<?php echo $this->S('/images/check.png'); ?>'>Ya postulaste
				  </span>
				<?php endif; ?>
			 </div>
			 <div class="jobs_ads_options_wrapper">
				<div class="jobs_ads_options">
				<span><?=$item["dias_fp"] ?></span>
				</div>
			 </div>
		  </div>
		</a>
	 </li>
	 <?php endforeach; ?>
  </ul>
  </div>
</div>
