<div class="box-subtitular-resultados text-center">
  <p>También te puede interesar estos puestos de trabajo.</p>
</div>
<div class="resultados">
  <?php foreach ($this->anunciosRelacionados as $item): ?>
  <?php
  $logoAnuncio = (isset($item['logo'])) ? trim($item['logo']) : '';
  $logo = empty($logoAnuncio) ? $this->S('/images/' . $this->LogoDefecto)   :  ELEMENTS_URL_LOGOS . $logoAnuncio.$this->E()->getLastCommit();
  ?>

  <div class="resultados-box">
    
    <div class="contenedor">
      <a href="<?=$this->url(array('slug' => $item['slug'],'empresaslug' => App_Util::validateSlugEmpresa($item['empresaslug'],$item['mostrar_empresa']),'ubicacionslug' => $item['ubicacionslug'],'url_id' => $item['url_id']), 'aviso_detalle', true)?>">
        <div class="media">          
          <img src="<?php echo $logo; ?>" alt="<?= $item["empresa_rs"] ?>">
          <div class="media-body">
            <p class="empresa"><?php echo $item['puesto']; ?></p>
            <small><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $item["dias_fp"]; ?></small>

          <div class="media-body">
            <small><i class="fa fa-map-marker" aria-hidden="true"></i>
            <?php echo $item["ubicacion"]; ?></small>
             <div class="media-body right">
              <small></small>
            </div>
          </div>
            <p class="parrafo">
              <?php if (isset($item['empresaslug'])) { ?>
              <span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
              <?php } else { ?>
              <span title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
              <?php }  ?>
              <p><?php echo mb_substr($this->escape($item["description"]), 0,$this->recortaraviso, 'utf-8') . " ..."?></p>              
            </p>
          </div>
        </div>
      </a>
    </div>
    <hr>
  </div>

  <?php endforeach; ?>
</div>