<?php if (count($this->anunciosRelacionados) > 0): ?>
    <div class="box-subtitular-resultados text-center">
        <p>Avisos Similares</p>
    </div>
    <div class="resultados">
        <?php foreach ($this->anunciosRelacionados as $key => $value): ?>
            <?php
            $logoAnuncio = (isset($item['logo'])) ? trim($item['logo']) : '';
            $logo        = $this->E()->getElementLogos($logoAnuncio);
            $eliminar = array("!", "·", "$", "%", "&", "/", "(", ")", "=", "?", "¿", "¡");
            $value['empresaslug'] = str_replace($eliminar, "", $value['empresaslug']);
            ?>
            
            <div class="resultados-box">
                <?php if (!empty($this->verAviso($value)->medalla())): ?>
                    <div class="box-star right-two">
                        <img src="<?= $this->S('/eb/svg/'.$this->verAviso($value)->medalla()); ?>" alt="" class="bandera bandera-avisos"/>
                    </div>
                <?php endif; ?>

                <div class="contenedor<?=$this->verAviso($value)->medaList()?>">
                    <a href="<?=
                    $this->url(
                        array(
                        'url_id' => $value["url_id"],
                        'empresaslug' => !empty($value["empresaslug"]) ? $value["empresaslug"]
                                : 'importante-empresa',
                        'ubicacionslug' => $value["ubicacionslug"],
                        'slug' => $value["slug"]
                        ), 'aviso_detalle', true
                    )
                    ?>">
                        <div class="media">

                            <img src="<?php echo $logo; ?>" alt="<?= $value["empresa_rs"] ?>">
                            <div class="media-body">
                                <p class="empresa"><?php echo $value['puesto']; ?></p>
                                <small><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $value["dias_fp"]; ?></small>

                                <div class="media-body">
                                    <small><i class="fa fa-map-marker" aria-hidden="true"></i>
                                        <?php echo $value["ubicacion"]; ?></small>
                                    <div class="media-body right">

                                    </div>
                                </div>
                                <p class="parrafo"><?php
                                    echo mb_substr($this->escape($value["description"]),
                                        0, 100, 'utf-8')." ..."
                                    ?></p>
                            </div>
                        </div>
                    </a>
                </div>
                <hr>
            </div>
        <?php endforeach ?>

    </div>
    <?php






 endif ?>