<ul class="row">
  <li class="icon_profile"><a href="#"> <i class="icon icon_reload"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Cambiar Sugerencias</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_person2"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Perfil</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_arrow"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Ubicación</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_education"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Estudios</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_tie"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Experiencia</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_speak"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Idiomas</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_mouse"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Informatica</p>
      </div></a></li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_books"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Otros Estudios</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_medal"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Logros</p>
      </div></a>
  </li>
  <li class="icon_profile"><a href="#"> <i class="icon icon_guitar"></i><span class="percentage"> <span class="text_number">100%+</span><span class="icon icon_check"></span></span>
      <div class="selection_title">
        <p>Hobbies</p>
      </div></a>
  </li>
</ul>