<form id="formContactApt" action="" method="POST">
      <div class="block">
          <label class="labelN left"><span class="req">*</span> Nombres:</label>
          <?php
        $errors = $this -> formContacto -> fNameCT -> hasErrors();
        echo $this -> formContacto -> fNameCT -> setAttribs(array('id' => 'fNameCT', 'class' => 'inputN left fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '1', 'errmsg'=>'Se requieren tus Nombres')) -> renderViewHelper();
      ?>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?> "><?php  echo($errors ? $this -> formContacto -> fNameCT -> errMsg : '');?></span>
  </div>
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Apellidos:</label>
      <?php
        $errors = $this -> formContacto -> fApellidosCT -> hasErrors();
        echo $this -> formContacto -> fApellidosCT -> setAttribs(array('id' => 'fApellidosCT', 'class' => 'inputN left fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '2','errmsg'=>'Se requieren tus Apellidos')) -> renderViewHelper();
      ?>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?> "><?php  echo($errors ? $this -> formContacto -> fApellidosCT -> errMsg : '');?></span>
  </div>  
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Documento:</label>
      <div class="divCT left">
      <?php
      $errors = $this -> formContacto -> tipo_documento -> hasErrors();
      $properties = array('id' => 'tipo_documento', 'class' => 'left', 'tabindex' => '3');
      echo $this -> formContacto -> tipo_documento -> setAttribs($properties) -> renderViewHelper();
      ?>
      <?php
      $errors = $this -> formContacto -> fDocCT -> hasErrors();
      $properties = array('id' => 'fDocCT', 'class' => 'inputN right fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '4','errmsg' =>'Ingrese nro de documento valido');
      echo $this -> formContacto -> fDocCT -> setAttribs($properties) -> renderViewHelper();
      ?>
      </div>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?>"><?php  echo($errors ? $this -> formContacto -> fDocCT -> errMsg : '');?></span>
  </div>
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Teléfonos:</label>
      <?php
        $errors = $this -> formContacto -> fTlfCT -> hasErrors();
        echo $this -> formContacto -> fTlfCT -> setAttribs(array('id' => 'fTlfCT', 'class' => 'inputN left fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '5','errmsg'=>'Se requiere tu Nro Telefonico / Celular')) -> renderViewHelper();
      ?>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?> "><?php  echo($errors ? $this -> formContacto -> fTlfCT -> errMsg : '');?></span>
  </div> 
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Email:</label>
       <?php
        $errors = $this -> formContacto -> fMailCT -> hasErrors();
        echo $this -> formContacto -> fMailCT -> setAttribs(array('id' => 'fMailCT', 'class' => 'inputN left fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '6','errmsg'=>'No parece ser un correo electrónico valido')) -> renderViewHelper();
      ?>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?> "><?php  echo($errors ? $this -> formContacto -> fMailCT -> errMsg : '');?></span>
  </div> 
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Asunto:</label>
       <?php
      $errors = $this -> formContacto -> fSubjectCT -> hasErrors();
      $properties = array('id' => 'fSubjectCT', 'class' => 'selectN left ready fields', 'tabindex' => '7');
      echo $this -> formContacto -> fSubjectCT -> setAttribs($properties) -> renderViewHelper();
      ?>
      <span class="response cGray left"></span>
  </div>  
  <div class="block">
      <label class="labelN left"><span class="req">*</span> Mensaje:</label>
       <?php
        $errors = $this -> formContacto -> fMsjCT -> hasErrors();
        echo $this -> formContacto -> fMsjCT -> setAttribs(array('id' => 'fMsjCT', 'class' => 'areaN left fields '.(!$errors && $this->ispost?'ready':''), 'tabindex' => '8','errmsg'=>'Se requiere un mensaje')) -> renderViewHelper();
      ?>
      <span class="response cGray left <?php echo ($errors)?'bad':'' ?> "><?php  echo($errors ? $this -> formContacto -> fMsjCT -> fMailCT : '');?></span>
  </div>
  
  <div class="block">
      <div class="pNMT">
      <?php  echo $this -> formContacto -> challenge;?>
      </div>
  </div>    
  
  <div class="wrap-btn center">          
        <input type="submit" id="MictaSendbtn" value="Enviar" class="btn btn-primary btn-big">                                        
  </div>
  
</form>
