<form action="" enctype="multipart/form-data" id="experienceF" method="post" class="frm-horizontal mT20" data-delete="/<?=$this->modulo?>mi-cuenta/borrar-experiencia">
	<input type="hidden" name="managerExperiencia" class="delete_reference">
	<div class="wrap-controls">
		<ul class="wrap-skills">
			<?php
			$contador = 0;
			$count = count($this->formExperiencia);
			?>
			<?php foreach ($this->formExperiencia as $indExp => $formExperiencia) : ?>
				<?php                                
				echo $this->partial('registro/_experiencia_paso2.phtml', 'postulante', array('form' => $formExperiencia,
					'manager' => $this->managerExperiencia,
					'indice' => $contador,
					'index' => $indExp,
					'isLinkedin' => (count($this->formExperiencia) - 1) == $contador ? null : $this->isLinkedin,
					'isExperiencia' => (count($this->formExperiencia) - 1) == $contador ? false : $this->isExperiencia,
					'idPostulante' => $this->idPostulante,
					'action' => isset($this->action) ? $this->action : '',
                                        'moneda' => $this->moneda,
					'count' => $count)
				);
				?>
				<?php $contador++; ?>
			<?php endforeach; ?>
		</ul>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnExperience" type="button" class="btn btn-default" data-more="Añadir otra experiencia">Añadir <?= ($count > 1) ? 'otra' : ''; ?> experiencia</button>
		</div>
	</div>
	<div class="wrap-btn right">
		<input type="submit" class="btn btn-primary" value="Guardar cambios">
	</div>
        <?php if(isset($this->csrfhash_a_tok)) : ?>
        <input type="hidden" id="csrfhash_a_tok" name="csrfhash_a_tok" value="<?=CSRF_HASH?>" />
        <?php endif; ?>
</form>
<script id="tplExperience" type="text/template">
	<?= $this->partial('registro/_experiencia_paso2.phtml', 'postulante', array('form' => $this->managerExperiencia->getForm('blank'),'moneda'=>$this->moneda)); ?>
</script>