<form id="formFind" action="/buscar" method="get" class="row fix-search">
    <div class="grids-6">
        <h2><?=($this->ActionActual() == "paso3")? "Consigue ahora tu nuevo trabajo" : "Encuentra tu próximo trabajo"?></h2>
        <!--<div id="logoEcoFB" class="stpAll <?php
                echo ($this->ActionActual() == "paso3") ? 'lEcoFBpaso3' : ''?>">
                </div>-->
        <div class="controls">
            <?=$this->form->txtDescription->setAttribs(array(
                'maxlength' => Application_Form_BuscarHome::QUERY_LENGTH_MAX,
                'id' => 'fieldSearch',//txtSearch
                'class' => 'input-big',
                'placeholder' => 'Busca por descripción del puesto o código del impreso'))->renderViewHelper();
            ?>
        </div>
        <div class="controls-inline">
            <div class="controls">
                <?= $this->form->selArea->setAttribs(array(
                    'id' => 'fAreas', 'class' => 'sel-small'))->renderViewHelper(); //ID: selArea
                ?>
            </div>
            <div class="controls">
                <?= $this->form->nivelPuestos->setAttribs(array(
                    'id' => 'fAreas', 'class' => 'sel-small'))->renderViewHelper(); //ID: selPuesto
                ?>
            </div>
            <div class="controls">
                <?= $this->form->selCity->setAttribs(array(
                    'id' => 'fAreas', 'class' => 'sel-small'))->renderViewHelper(); //ID: selUbicacion
                ?>
            </div>
        </div>
    </div>
    <div class="grids-300">
        <?=$this->form->button->setAttribs(array(
            'id' => 'sbtSearch', 'class' => 'btn btn-primary btn-big', 'type' => 'submit'))->renderViewHelper(); //ID: btn-search
        ?>
        <a href="/busqueda-avanzada" title="Búsqueda Avanzada">Búsqueda Avanzada</a>
    </div>
</form>
