<form action="" enctype="multipart/form-data" id="languagesF" method="post" class="frm-horizontal mT20" data-delete="/<?=$this->modulo?>mi-cuenta/borrar-idioma">
	<input type="hidden" name="managerIdioma" class="delete_reference">
	<div class="wrap-controls">
		<ul class="wrap-skills">
			<?php
			$contador = 0;
			$count = count($this->formIdioma);
			?>
			<?php foreach ($this->formIdioma as $indIdi => $formIdioma) : ?>
				<?php
				echo $this->partial('registro/_idioma_paso2.phtml',
					'postulante',
					array('form' => $formIdioma,
					'manager' => $this->managerIdioma,
					'indice' => $contador,
					'isLinkedin' => (Count($this->formIdioma) - 1) == $contador ? null : $this->isLinkedin,
					'isIdioma' => (Count($this->formIdioma) - 1) == $contador ? true : $this->isIdioma,
					'idPostulante' => $this->idPostulante,
					'action' => isset($this->action)?$this->action:'',
					'count' => $count)
				);
				?>
				<?php $contador++; ?>
			<?php endforeach; ?>
		</ul>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnLanguage" type="button" class="btn btn-default" data-more="Añadir otro idioma">Añadir <?= ($count > 1) ? 'otro' : ''; ?> idioma</button>
		</div>
	</div>	
	<div class="wrap-btn right">
		<input type="submit" class="btn btn-primary" value="Guardar cambios"> 
	</div>
        <?php if(isset($this->csrfhash_a_tok)) : ?>
        <input type="hidden" id="csrfhash_a_tok" name="csrfhash_a_tok" value="<?=CSRF_HASH?>" />
        <?php endif; ?>
</form>
<script id="tplLanguage" type="text/template">
	<?= $this->partial('registro/_idioma_paso2.phtml', 'postulante', array('form' => $this->managerIdioma->getForm('blank'))); ?>
</script>
