<div class="modal_helper" id="modalHelp">
    <div class="center_box hide_mobile">

        <div class="content_modal_rigth">

          <div class="over_options">
            <div class="over_text_options">Opciones para seguir tus postulaciones y destacar</div>
            <i class="icon icon_arrowh_bottom"></i>
            <div class="over_dotted_profile">
            </div>
          </div>

          <div class="over_icons">
            <div class="over_text_icons">Estos son los temas de tu perfil <br>
              que aun no has completado, estos temas <br>
              influyen en las sugerencias que te enviamos</div>
              <div class="over_content_icons_down">
                <i class="icon icon_arrowh_down_diagonal_right"></i>
                <i class="icon icon_arrowh_bottom"></i>
                <i class="icon icon_arrowh_down_diagonal_left"></i>
              </div>
            <div class="over_dotted_icons">
                
              <div class="over_themes">
                <i class="icon icon_arrowh_top"></i>
                <div class="over_text_themes">Vuelve a configurar tus temas de búsqueda</div>
              </div>

              <div class="over_moment">
                <i class="icon icon_arrowh_big"></i>
                <div class="over_text_moment">Al momento de completar un tema de tu perfil se actualizarán las sugerencias</div>
              </div>

            </div>
          </div>
          <?php
          /*
          <div class="over_tools_row">
            <div class="over_tools">
              <i class="icon icon_arrowh_top2"></i>
              <div class="over_text_tools">Importa tus datos de Linkedin</div>
            </div>
            

            <div class="over_tools">
              <i class="icon icon_arrowh_top2"></i>
              <div class="over_text_tools">Imprime tu CV</div>
            </div>

            <div class="over_tools end">
            </div>
          </div>
          */
          ?>

        </div>

        
        <div class="content_modal_left">
            
            <div class="over_know">
                <i class="icon icon_arrowh_top_diagonal_left"></i>
                <div class="over_text_know">Configura tu cuenta</div>
            </div>

            <div class="over_higtlight">
                <div class="over_text_higtlight">Destacados</div>
                <i class="icon icon_arrowh_bottom"></i>
            </div>

            <div class="over_match">
                <div class="over_text_match">Sugerencias de empleo <br> que hacen match con tu <br> Perfil completado</div>
                <i class="icon icon_arrowh_bottom"></i>
            </div>

        </div>
        
    </div>

    <div class="center_box hide_desktop">
      <div class="row_icons">
        <i class="icon icon_arrowh_movil_top_left"></i>
        <i class="icon icon_arrowh_movil_top_right"></i>
      </div>
      <div class="clear"></div>
      <p>Mientras más temas vás agregando a tu perfil, el porcentaje de completado va aumentando y los puestos sugeridos van siendo más precisos</p>
    </div>

    <a href="#" class="icon icon_cross" id="btnCloseHelp"></a>
    
</div>