<?
$active = "active";
$this->isAuth = Zend_Auth::getInstance()->hasIdentity();
$this->auth = Zend_Auth::getInstance()->getStorage()->read();
?>
<nav class="cont-menu row">
    <ul class="row">
        <li><a class="<?= $this->menu_sel == App_Controller_Action_Postulante::MENU_INICIO ? $active : ''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'home','action'=>'index'),"default",true)?>">INICIO</a></li>
        <li><a class="<?= $this->menu_sel == App_Controller_Action_Postulante::MENU_AVISOS ? $active : ''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'buscar','action'=>'index'),"default",true)?>">BUSCAR</a></li>
        <li><a class="<?=$this->menu_sel==App_Controller_Action_Postulante::MENU_QUE_ES_EMPLEOBUSCO?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'home','action'=>'que-es-EMPLEOBUSCO'),"que-es-EMPLEOBUSCO",true)?>">¿QUÉ ES EMPLEOBUSCO?</a></li>
        <? if($this->isAuth && isset($this->auth[Application_Form_Login::ROL_POSTULANTE])){ ?>
            <li><a class="<?=$this->menu_sel==App_Controller_Action_Postulante::MENU_MI_CUENTA?$active:''?>" href="<?=$this->url(array('module'=>'postulante','controller'=>'mi-cuenta','action'=>'index'),"default",true)?>">MI CUENTA</a></li>
        <? } ?>
        <li><a href="<?=$this->url(array('module' => Application_Form_Login::ROL_EMPRESA),'default', true)?>">EMPRESAS</a></li>
        <li><a class="<?= $this->menu_sel == App_Controller_Action_Postulante::MENU_PERFIL_DESTACADO ? $active : ''?>" href="<?=$this->url(array('module' => 'postulante','controller' => 'perfil-destacado'),'default', true)?>">PERFIL DESTACADO</a></li>
        
    </ul>
</nav>

