<form id="frmUserLogIn" autocomplete="off" action="<?=$this->url(array('module'=>'postulante','controller'=>'home','action'=>'index'))?>" class="type1">
	<div class="form_box">
		<div class="form_row">
			<div class="form_col12">
				<fieldset>
				<label>Email</label>
				<?= str_replace('type="text"', 'type="email"',$this->loginFormNew->txtUser->setAttribs(array('id' => 'txtUser','required'=>'','maxlength'=>'75'))->renderViewHelper());?>
				</fieldset>
			</div>
		</div>
		<div class="form_row">
			<div class="form_col12">
				<fieldset>
				<label>Contraseña</label>
				<?=$this->loginFormNew->txtPasswordLogin->setAttribs(array('id' => 'txtPasswordLogin','size'=>'50','required'=>''))->renderViewHelper();?>
				</fieldset>
			</div>	
		</div>
	</div>
	<button class="btn btn_tertiary mt10"><span class="btn_label">Ingresar</span><span class="btn_spinner"></span></button>
	<p class="mt10"><a href="javascript:;" class="type_white recover_init">Olvidé mi contraseña</a></p>
	<label for="" class="ioption">Recordar mi contraseña
		<?=$this->loginFormNew->chkRemember->setAttribs(array())->renderViewHelper();?>
		<?=$this->loginFormNew->tipo->setAttribs(array('id'=>'tipo'))->renderViewHelper();?>
		<?=$this->loginFormNew->hidAuthToken->renderViewHelper();?>
	</label>
</form>
