<form id="frmSearch" action="/buscar" method="post">
  <h2 class="search_home_box_header">Busca tu próximo empleo</h2>
  <div class="search_home_box_body row">
    <fieldset>
      <div><?=$this->form->txtDescription->setAttribs(array(
        'maxlength' => Application_Form_BuscarHome::QUERY_LENGTH_MAX,
        'id' => 'txtDescription',//txtSearch
        'autocomplete'=>'off',
        'placeholder' => 'Puesto o palabra clave',
        'class' => 'disable_especial_characters',
        'value'=>''
        ))->renderViewHelper();
      ?></div>
    </fieldset>
    <fieldset>
      <button class="btn btn_cuaternary tracking" data-track-strategy="quickly_search"><span>Buscar</span><i class="icon icon_lens"></i></button>
    </fieldset>
  </div>
 </form>