<form action="" enctype="multipart/form-data" id="studyOtherF" method="post" class="frm-horizontal mT20" data-delete="/<?=$this->modulo?>mi-cuenta/borrar-estudio">
	<input type="hidden" name="managerOtroEstudio" class="delete_reference">
	<div class="wrap-controls">
		<ul class="wrap-skills">
			<?php
			$contador = 0;
			$count = count($this->formEstudio);
			?>
			<?php foreach ($this->formEstudio as $indEst => $formEstudio) : ?>
				<?php
				echo $this->partial('registro/_otro_estudio_paso2.phtml', 'postulante', array('form' => $formEstudio,
					'manager' => $this->managerEstudio,
					'indice' => $contador,
					'isLinkedin' => (Count($this->formEstudio) - 1) == $contador ? null : $this->isLinkedin,
					'isOtroEstudio' => (Count($this->formEstudio) - 1) == $contador ? true : $this->isOtroEstudio,
					'idPostulante' => $this->idPostulante,
					'action' => isset($this->action)?$this->action:'',
					 'count' => $count)
				);
				?>
				<?php $contador++; ?>
			<?php endforeach; ?>
		</ul>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnOtherStudy" type="button" class="btn btn-default" data-more="Añadir otro estudio">Añadir <?= ($count > 1) ? 'otro' : ''; ?> estudio</button>
		</div>
	</div>
	<div class="wrap-btn right">
		<input type="submit" class="btn btn-primary" value="Guardar cambios">
	</div>
        <?php if(isset($this->csrfhash_a_tok)) : ?>
        <input type="hidden" id="csrfhash_a_tok" name="csrfhash_a_tok" value="<?=CSRF_HASH?>" />
        <?php endif; ?>
</form>
<script id="tplStudyOther" type="text/template">
	<?= $this->partial('registro/_otro_estudio_paso2.phtml', 'postulante', array('form' => $this->managerEstudio->getForm('blank'))); ?>
</script>