<form action="" enctype="multipart/form-data" id="programsF" method="post" class="frm-horizontal mT20" data-delete="/<?=$this->modulo?>mi-cuenta/borrar-programa">
	<input type="hidden" name="managerPrograma" class="delete_reference">
	<div class="wrap-controls">
		<ul class="wrap-skills">
			<?php
			$contador = 0;
			$count = count($this->formPrograma);
			?>
			<?php foreach ($this->formPrograma as $indProg => $formPrograma) : ?>
				<?php
				echo $this->partial('registro/_programa_paso2.phtml',
					'postulante',
					array('form' => $formPrograma,
					'manager' => $this->managerPrograma,
					'indice' => $contador,
					'isPrograma' => (Count($this->formPrograma) - 1) == $contador ? true : $this->isPrograma,
					'idPostulante' => $this->idPostulante,
					'action' => isset($this->action)?$this->action:'',
					'count' => $count)
				);
				?>
				<?php $contador++; ?>
			<?php endforeach; ?>
		</ul>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnPrograms" type="button" class="btn btn-default" data-more="Añadir otro programa">Añadir <?= ($count > 1) ? 'otro' : ''; ?> programa</button>
		</div>
	</div>
	<div class="wrap-btn right">
		<input type="submit" class="btn btn-primary" value="Guardar cambios">
	</div>
        <?php if(isset($this->csrfhash_a_tok)) : ?>
        <input type="hidden" id="csrfhash_a_tok" name="csrfhash_a_tok" value="<?=CSRF_HASH?>" />
        <?php endif; ?>
</form>
<script id="tplPrograms" type="text/template">
	<?= $this->partial('registro/_programa_paso2.phtml', 'postulante', array('form' => $this->managerPrograma->getForm('blank'))); ?>
</script>
