<p><b><?= $this->escape(ucfirst($this->nombre)); ?>.</b><br> Recuerda que las referencias que las empresas toman en cuenta son las de tus últimos trabajos.</p>            
<form action="" enctype="multipart/form-data" id="referenceF" method="post" class="frm-horizontal mT20" data-delete="/<?=$this->modulo?>mi-cuenta/borrar-referencia">
	<input type="hidden" name="managerReferencia" class="delete_reference">
	<div class="wrap-controls">
		<ul class="wrap-skills">
			<?php
			$contador = 0;
			$count = count($this->formReferencia);
			?>
			<?php foreach ($this->formReferencia as $indExp => $formReferencia) : ?>
				<?php 
				echo $this->partial('registro/_referencia_paso2.phtml',
					'postulante',
					array('form' => $formReferencia,
					'manager' => $this->managerReferencia,
					'indice' => $contador,
					'isLinkedin' => (Count($this->formReferencia) - 1) == $contador ? null : $this->isLinkedin,
					'isReferencia' => (Count($this->formReferencia) - 1) == $contador ? false : $this->isReferencia,
					'idPostulante' => $this->idPostulante,
					 'action' => isset($this->action)?$this->action:'',
					 'count' => $count)
				);
				?>
				<?php $contador++; ?>
			<?php endforeach; ?>
		</ul>
		<div class="wrap-btn right">
			<span class="response bad hide"></span>
			<button id="btnReference" type="button" class="btn btn-default" data-more="Añadir otra referencia">Añadir <?= ($count > 1) ? 'otra' : ''; ?> referencia</button>
		</div>
	</div>
	<div class="wrap-btn right">
		<input type="submit" class="btn btn-primary" value="Guardar cambios">
	</div>
        <?php if(isset($this->csrfhash_a_tok)) : ?>
        <input type="hidden" id="csrfhash_a_tok" name="csrfhash_a_tok" value="<?=CSRF_HASH?>" />
        <?php endif; ?>
</form>
<script id="tplReference" type="text/template">
	<?= $this->partial('registro/_referencia_paso2.phtml', 'postulante', array('form' => $this->managerReferencia->getForm('blank'))); ?>
</script>


