	        <div id="innerMain" class="grid20 center">
	          
	          <div id="content" class="grid13 rel left theta">
	          	
	           <div class="texto paddingL10">
              <h2 class="h2InfoPost">Términos de Uso</h2>
              <div class="informacion">
                <h6 class="tituloInfo bold">¿La información provista será tratada de manera privada?</h6>
              </div>
              <p class="text-page-info">La información que envíes será tratada con el nivel de privacidad que tú indiques al momento de completar tus datos personales:</p>
              <div id="nivel-privacidad" class="all">
                <div class="all">
                <div class="publico left">
                  <h6 class="titulonivel bold">Pública:</h6>
                  <p class="text-page-nivel">Aparecerá tu perfil completo en resultados de búsquedas.</p>
                </div>
                <div class="privado right">
                  <h6 class="titulonivel bold left block">Privada:</h6>
                  <p class="text-page-nivel">No aparece en resultados de búsqueda. Sólo aparece en resultados de búsqueda por la posición a la que postuló.</p>
                </div>
                </div>
                <div class="micuenta-screen"> </div>
                <h6 class="tituloInfo bold">¿Qué debo hacer si otra persona esta usando mis datos?</h6>
                <p>Inmediatamente tienes que enviarnos un correo a <a href="mailto:soporte@EMPLEOBUSCO.com.pe">soporte@EMPLEOBUSCO.com.pe</a><br/>Indicándonos los motivos por los cuales esa persona está utilizando tu Información.</p>
                <h6 class="tituloInfo bold">¿Qué debo hacer si perdí mi contraseña?</h6>
                <p class="text">Si pierdes tu contraseña, ingresa a la página principal y en la parte superior derecha podrás encontrar la opción Ingresar y solicita que te enviemos tu contraseña a la dirección de correo electrónica que ingresaste al crear tu cuenta).</p>
                <div class="olvide-clave-screen"> </div>
              </div>
            </div>
	            	
	            	
	          	</div>
	          
		          <div id="sidebar" class="grid7 right theta bgSITIE">
		          	<div class="innerAside r10 bLBlue bgLBlue"> 
                  <div class="eplanning ads300x250" data-section="Right1"></div>
		            	<?=$this->partial('home/_articulos_interes.phtml','postulante')?>
		            	<div class="published"> <a href="/empresa/publica-aviso/paso1"><img src="<?php echo $this->S('/images/publicaAviso.jpg'); ?>" alt="Publica tu aviso" /></a> </div>
		          	</div>
		          	<div class="hide bgSIBIE">&nbsp;</div>
		        	</div>
		        						    
					  
					  </div>