<?php
$tieneSugeridos = isset($this->avisosSugerencias['data']) && count($this->avisosSugerencias["data"]);
$existeError = isset($this->avisosSugerencias['error']);
$tieneAreas = isset($this->avisosSugerencias['params']) && $this->avisosSugerencias['params'] == 0 ? false : true;
?>          

<div class="box-subtitular-resultados text-center">
  <p>Avisos Similares</p>
</div>
<div class="resultados">

  <?php if ($tieneSugeridos): ?>

  <?php foreach($this->avisosSugerencias["data"] as $item):
      $logo = (!empty($item["logoanuncio"]) || $item["logoanuncio"] != NULL || $item["logoanuncio"] != '') ? ELEMENTS_URL_LOGOS . $item["logoanuncio"].$this->E()->getLastCommit():$this->S('/images/icon-empresa-blank.png' ) ;
      $url = SITE_URL . $item['url'];

      switch($item['prioridad']) {          
        case 1:
            $_medal = "medal1.svg";
            $_class = "-a";
            break;

        case 2:
            $_medal = "medal2.svg";
            $_class = "-b";
            break;

        default:   
            $_medal = "";
            $_class = "";
            break;
      }
  ?>

  <div class="resultados-box">
    <?php if(!empty($_medal)): ?>
      <div class="box-star right-two">
        <img src="<?php echo $this->S('eb/svg/'.$_medal); ?>" class="right">
      </div>
    <?php endif ?>
    
    <div class="contenedor<?php echo $_class; ?>">
      <a href="<?php echo $url; ?>">
        <div class="media">          
            <img width="90"  height="90" src="<?php echo $logo; ?>" alt="<?= $item["empresa_rs"] ?>">
          <div class="media-body">
            <p class="empresa"><?php echo $item['puesto']; ?></p>
            <small><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $item["dias_fp"]; ?></small>

          <div class="media-body">
            <small><i class="fa fa-map-marker" aria-hidden="true"></i>
            <?php echo $item["ubicacion"]; ?></small>
             <div class="media-body right">
              <small></small>
            </div>
          </div>
            <p class="parrafo">
              <?php if (isset($item['empresaslug'])) { ?>
              <span href='<?=SITE_URL; ?>/buscar/empresa/<?=$item['empresaslug']?>' title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
              <?php } else { ?>
              <span title="<?= $this->escape($item['empresa_rs']) ?>"><?= $this->escape($item['empresa_rs']) ?></span>
              <?php }  ?>
              <p><?php echo mb_substr($this->escape($item["description"]), 0,$this->recortaraviso, 'utf-8') . " ..."?></p>              
            </p>
          </div>
        </div>
      </a>
    </div>
    <hr>
  </div>

  <?php endforeach; ?>
  <?php endif; ?>
                 
</div>