<div class="iBlockMSA mB10">
    <h5 class="titleSA alignL active acordionJ"><?= $this->titulo ?><span class="<?= $this->ico ?> icoTi">&nbsp;</span><span class="icoTi icoATAP">&nbsp;</span></h5>
    <form id="fFilter<?= $this->pfijof1 ?>" action="#" class="fFilterS bgLBlue r10B open">
        <fieldset>
            <? foreach ($this->datos['visible'] as $item):?>
                <label for="areas<?= $item['slug'] ?>" class="labelFS">
                    <span class="iBlockLSA left">
                        <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>"
                               type="checkbox" class="checkN noBdr" <?=($this->param!=""?(in_array($item["slug"],explode($this->constantes->separador,$this->filtro))?"checked":""):"")?> />
                    </span> 
                    <span class="iBlockRSA right">
                        <?
                          $conf_areas= $this->constantes->areas;
                          $conf_nivel= $this->constantes->nivel;
                          $conf_fechapub= $this->constantes->fechapub;
                          $conf_remuneracion= $this->constantes->remuneracion;
                          $conf_empresa= $this->constantes->empresa;
                          $conf_ubicacion= $this->constantes->ubicacion;

                          $filtros2 = array();
                          $separador = $this->constantes->separador;
                          if($this->param==$conf_areas){ //areas
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{ 
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['areas'] = $valor;
                                if($filtros2["areas"]=="") $filtros2["areas"]=null;
                          }
                          if($this->param==$conf_nivel){ //nivel
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['nivel'] = $valor;
                                if($filtros2["nivel"]=="") $filtros2["nivel"]=null;
                          }
                          if($this->param==$conf_fechapub){ //FechaPub
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['fecha-publicacion'] = $valor;
                                if($filtros2["fecha-publicacion"]=="") $filtros2["fecha-publicacion"]=null;
                          }
                          if($this->param==$conf_remuneracion){ //Remuneracion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($nueva=="0")
                                {
                                    $valor = str_replace($actual, "", $actual);
                                }else{
                                    if($this->Existepalabra($nueva,$actual,$separador)){
                                        $x = explode("--", $actual);
                                        array_splice($x,array_search($item["slug"],$x),1);
                                        $valor = implode("--", $x);
                                    }else{
                                        if($actual!="") $valor = $actual.$separador.$nueva;
                                        else $valor = $nueva;
                                    }
                                }
                                $filtros2['remuneracion'] = $valor;
                                if($filtros2["remuneracion"]=="") $filtros2["remuneracion"]=null;
                          }
                          if($this->param==$conf_empresa){ //Empresa
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['empresa'] = $valor;
                                if($filtros2["empresa"]=="") $filtros2["empresa"]=null;
                          }
                          if($this->param==$conf_ubicacion){ //Ubicacion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['ubicacion'] = $valor;
                                if($filtros2["ubicacion"]=="") $filtros2["ubicacion"]=null;
                          }
                          
                          $ruta = $this->url($filtros2,'buscar',false);
                       ?>
                        <a class="aFilterB" href="<?=$ruta?>"><?= $item['msg'] ?></a>
                        <span class="count">(<?= $item['cant'] ?>)</span>
                    </span>
                </label>
            <? endforeach; ?>
        </fieldset>
        <?if (count($this->datos['ocultos'])): ?>
            <fieldset class="asideSA alignR"><a href="#verTodos" class="winMegaT">Ver todos</a></fieldset>
        <?endif?>
    </form>
    <div id="megaTool1" rel="<?= count($this->datos['ocultos']) ?>" class="megaTool bgLBlue hide">
        <form id="fExtend<?= $this->pfijof2 ?>" action="#" class="innerMegaT hide rel">
            <a href="#Cerrar" class="closeMTWM right"><span class="iCloseMTWM">Cerrar</span></a>										
            <? foreach ($this->datos['ocultos'] as $columna): ?>
                <fieldset class="iMTFilterS left">
                    <? foreach ($columna as $item): ?>
                        <label for="areas<?= $item['slug'] ?>" class="labelFS">
                            <span class="iBlockLSA left">
                                <input id="areas<?= $item['slug'] ?>" name="areas<?= $item['slug'] ?>" type="checkbox" class="checkN noBdr" <?=($this->param!=""?(in_array($item["slug"],explode($this->constantes->separador,$this->filtro))?"checked":""):"")?> />
                            </span>
                            <span class="iBlockRSA right">
                            <?
                          $conf_areas= $this->constantes->areas;
                          $conf_nivel= $this->constantes->nivel;
                          $conf_fechapub= $this->constantes->fechapub;
                          $conf_remuneracion= $this->constantes->remuneracion;
                          $conf_empresa= $this->constantes->empresa;
                          $conf_ubicacion= $this->constantes->ubicacion;

                          $filtros2 = array();
                          $separador = $this->constantes->separador;
                          if($this->param==$conf_areas){ //areas
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['areas'] = $valor;
                                if($filtros2["areas"]=="") $filtros2["areas"]=null;
                          }
                          if($this->param==$conf_nivel){ //nivel
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['nivel'] = $valor;
                                if($filtros2["nivel"]=="") $filtros2["nivel"]=null;
                          }
                          if($this->param==$conf_fechapub){ //FechaPub
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['fecha-publicacion'] = $valor;
                                if($filtros2["fecha-publicacion"]=="") $filtros2["fecha-publicacion"]=null;
                          }
                          if($this->param==$conf_remuneracion){ //Remuneracion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($nueva=="0")
                                {
                                    $valor = str_replace($actual, "", $actual);
                                }else{
                                    if($this->Existepalabra($nueva,$actual,$separador)){
                                        $x = explode("--", $actual);
                                        array_splice($x,array_search($item["slug"],$x),1);
                                        $valor = implode("--", $x);
                                    }else{
                                        if($actual!="") $valor = $actual.$separador.$nueva;
                                        else $valor = $nueva;
                                    }
                                }
                                $filtros2['remuneracion'] = $valor;
                                if($filtros2["remuneracion"]=="") $filtros2["remuneracion"]=null;
                          }
                          if($this->param==$conf_empresa){ //Empresa
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['empresa'] = $valor;
                                if($filtros2["empresa"]=="") $filtros2["empresa"]=null;
                          }
                          if($this->param==$conf_ubicacion){ //Ubicacion
                                $actual = $this->filtro;
                                $nueva = $item['slug'];
                                $valor="";
                                if($this->Existepalabra($nueva,$actual,$separador)){
                                    $x = explode("--", $actual);
                                    array_splice($x,array_search($item["slug"],$x),1);
                                    $valor = implode("--", $x);
                                }else{
                                    if($actual!="") $valor = $actual.$separador.$nueva;
                                    else $valor = $nueva;
                                }
                                $filtros2['ubicacion'] = $valor;
                                if($filtros2["ubicacion"]=="") $filtros2["ubicacion"]=null;
                          }

                          $ruta = $this->url($filtros2,'buscar',false);
                       ?>

                                <a class="aFilterB" href="<?=$ruta?>"><?= $item['msg'] ?></a>
                                <span class="count">(<?= $item['cant'] ?>)</span>
                            </span>
                        </label>
                    <? endforeach; ?>
                </fieldset>	
            <? endforeach; ?>
        </form>
    </div>
    <div class="bgIRSBSE hide">&nbsp;</div>
</div>