<div class="row">
	 <div id="paginEPM" class="pagination bBGray all">
		  <p class="pagLegend grid5 mB0 theta alingL left"><?= $this->mostrando ?>
				&nbsp;(<?php
				if (isset($this->opcionlista)) {
					 switch ($this->opcionlista) {
						  case -3: echo "Referidos";
								break;
						  case -2: echo "Descartados";
								break;
						  case -1: echo "Todos";
								break;
						  case 0: echo "Leídos";
								break;
						  case 1: echo "No Leídos";
								break;
					 }
				} else {
					 echo "Todos";
				}
				?>)</p>
		  <?=
		  $this->paginationControl($this->proceso, 'Sliding',
				'mis-procesos/_pag_verproceso.phtml',
				array("opcionlista" => $this->opcionlista, "estasArriba" => 1))
		  ?>
	 </div>

	 <table cadenabusqueda="<?= $this->cadenabusqueda ?>" opcionlista="<?= $this->opcionlista ?>" categoria="<?= isset($this->categoria) ? $this->categoria : "" ?>" ord="<?= $this->ord ?>" col="<?= $this->col ?>" page="<?= $this->pagina ?>" idanuncio="<?= $this->idanuncio ?>" class="dataGrid dataGridEnviarBolsa tlbfix" id="dataProcesoPostulacion" summary="Proceso de Postulacion">
		  <thead>
				<tr>
					 <? $base = array('module' => 'empresa', 'controller' => 'mis-procesos','action' => 'ver-proceso'); ?>
					 <th class="data0 titleGrid linkTitleG">
						  <input type="checkbox" name="selectAll" class="noBdr" />
					 </th>
					 <th class="data1 titleGrid linkTitleG">
						  <? $col = 'match' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow fix"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Match</a>
					 </th>
					 <th class="data2 titleGrid linkTitleG">
						  <? $col = 'path_foto' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Foto</a>
					 </th>
					 <th class="data3 titleGrid linkTitleG">
						  <? $col = 'nombres' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Nombres</a>
					 </th>
					 <th class="data4 titleGrid linkTitleG">
						  <? $col = 'fecha_nac' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow fix"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Edad</a>
					 </th>
					 <th class="data5 titleGrid linkTitleG">
						  <? $col = 'nivel_estudio' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Nivel<br/>Estudio</a>
					 </th>
					 <th class="data6 titleGrid linkTitleG">
						  <? $col = 'carrera' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Carrera</a>
					 </th>
					 <th class="data7 titleGrid linkTitleG">
						  <? $col = 'id_ubigeo' ?>
						  <? $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC' ?>
						  <a href="#anclaCol" ord="<?= $ord ?>" col="<?= $col ?>" class="rel relArrow"><span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span> Lugar de<br/>Residencia</a>
					 </th>
					 <? if ($this->online && $this->opcionlista != -3): ?>
						  <th class="data8 titleGrid">Acciones</th>
					 <? endif; ?>
				</tr>
		  </thead>
		  <tbody>
				<?php
                                foreach ($this->proceso as $item):
					 $idPostulante = "";
					 if (isset($item['idpostulante']))
						  $idPostulante = $item["idpostulante"];
					 ?>
					 <tr class="<?= ($item["es_nuevo"] ? "pintarNoLeidos" : "pintarLeidos") ?>">
						  <td class="data0">
								<input type="checkbox" name="select" id="<?= $item["idpostulacion"] ?>" relpos="<?= $idPostulante ?>" />
						  </td>
						  <td class="data1">
								<?php if ($item["invitacion"] != 0): ?>
									 <span class="icfix">
										  <img src="<?php echo $this->S('/images/empresa/invitados.png'); ?>" alt="Invitado" title="Invitado"/>
									 </span>
								<?php endif; ?>
								<?php if ($item["referenciado"] != 0): ?>
									 <span class="icfix">
										  <img src="<?php echo $this->S('/images/empresa/referidos.png'); ?>" alt="Referido" title="Referido" />
									 </span>
								<?php endif; ?>
								<?= $item["match"] ?>%
						  </td>
						  <td class="data2">
								<span class="dateData cntImgFix">
									 <a href="#" class="verPerfilFilPerfP_Imagen">
										  <?php
										  $logo = ($item["foto"] == "" || $item["foto"] == NULL)
													 ?
												$this->S('/images/photoDefault.jpg') : ELEMENTS_URL_IMG . $item["foto"];
										 /// $lado = $this->ImgLadoMayor($logo);
										  ?>
										  <img width="60" src="<?= $logo ?>" alt="<?=$item["nombres"]." ".$item["apellido_paterno"]." ".$item["apellido_materno"]?>"/>
									 </a>
								</span>
						  </td>
						  <td class="data3">
								<div class="bold nameFilPerfP">
								<?php
									 $url = $this->url(array(
										  'module' => 'empresa',
										  'controller' => 'mis-procesos',
										  'action' => 'perfil-publico-emp',
										  'id' => $item["idpostulacion"],
										  'idAviso' => $item["id"],
										  'idsback' => $item["id"],
                                                                                  'postulaciones' => $this->Util()->listPostulantes($this->dtproceso),
										  ),
										  "default",
										  true);
								?>
								<a href="<?php echo $url; ?>" class="_verPerfilFilPerfP_Nombre"><?= $item["nombres"] . " " . $item["apellido_paterno"] . " " . $item["apellido_materno"]; ?></a>
								</div>
								<?php if(!empty($item["destacado"])){?>
								<span class="icon-medal"></span>
								<?php }?>
								<div class="tlfFilPerfP sptIcoEmp" title="Telefono">&nbsp;<?= $item["telefono"] ?></div>
								<?php if ($item["sexo"] == 'M'): ?>
									 <span title="Hombre" class="sptIcoEmp imgHombre fix">M</span>
								<?php else: ?>
									 <span title="Mujer" class="sptIcoEmp imgMujer fix">F</span>
								<?php endif; ?>
								<?php if ($this->online && $this->opcionlista != -3): ?>
										  <?php if($item["origen_postulacion"]=='api'){?>
									 <span title="Trabaja Con Nosotros" class="dateData fix">TCN</span>
											<?php }elseif($item["origen_postulacion"]=='referido'){?>
									 <span title="Referido" class="dateData fix">REF</span>
										  <?php }else{?>
									 <span title="AquiEmpleos" class="dateData fix">WEB</span>
										  <?php }?>
								<?php endif; ?>
								<div class="all">
									 <?php if ($item["slug"] != "" && $item["slug"] != null): ?>
										  <a class="verPerfilFilPer sptIcoEmp left" rel="<?=$item['idpostulacion'] ?>" href="<?=$url?>" title="Ver perfil"></a>
									 <?php endif; ?>
									 <?php if ($item["path_cv"] != "" && $item["path_cv"] != null): ?>
										  <span class="pipeFilPerfP left">|</span>
										  <?php
										  $doc = strtolower(substr($item["path_cv"],
													 strlen($item["path_cv"]) - 3,
													 strlen($item["path_cv"])));
										  $target = '';
										  if ($doc == 'pdf') $target = "TARGET='_blank'";
										  ?>
										  <a class="downFilPerfP sptIcoEmp left" href="<?= ELEMENTS_URL_CVS . $item["path_cv"] ?>" <?= $target ?> title="Ver CV"></a>
									 <?php endif; ?>
									 <span class="pipeFilPerfP left">|</span>
									 <div class="msjFilPerfP sptIcoEmp left" title="Mensajes">(<?=
										  $item["msg_respondido"] != null ? $item["msg_respondido"]
													 : '0'
										  ?>)
									 </div>
								</div>
						  </td>
						  <td class="data4">
								<span class="dateData"><?= $item["edad"] ?></span>
						  </td>
						  <td class="">
								<span class="dateData"><?= $item["nivel_estudio"] ?></span>
						  </td>
						  <td class="">
								<span class="dateData"><?= $item["carrera"] ?></span>
						  </td>
						  <td class="">
								<span class="dateData"><?= (!empty($item["ubigeo"])) ? $item["ubigeo"] : ''; ?></span>
						  </td>
						  <?php if ($this->online && $this->opcionlista != -3): ?>
								<td class="data8">
									 <? $url = "#"; //$this->url(array('module' => 'empresa', 'controller' => 'mis-procesos', 'action' => 'ver-proceso','id'=>$item["id"]),"default",false);  ?>
									 <? $idpos = $item["idpostulacion"]; ?>
									 <div class="moveraetapafila moveFilPerfP upFlechaEP mB5" rel="izq">
										  <?php
										  $js = '';
										  $winModal = '';
										  $winNotas = '';
										  if ($this->flagAcciones['acciones']['tooltip'] == '') {
												$js = "javacript:;";
												$winModal = "winModal";
												$winNotas = "#winAnadirNotas";
										  }
												?>
										  <a class="<?=$this->flagAcciones['acciones']['tooltip']?> fix-tool" <?=$this->flagAcciones['acciones']['texto']?> href="<?=$js?>">Acciones</a>
										  <?php if ($this->flagAcciones['acciones']['tooltip'] == '') { ?>
										  <ul class="menuinterno hide r5 fix">
												<li>
													 <div class="addNoteFilPerfP"><a class="<?=$winModal?> anadirnotas" href="<?=$winNotas?>" rel="<?= $idpos ?>">Añadir notas</a></div>
												</li>
												<li>
													 <div class="descartarFilPerfP <?= $this->opcionlista == -2 ? "restituirButton" : "descartarButtonVerProceso" ?>" rel="<?= $idpos ?>">
														  <a href="<?= $url ?>"><?= $this->opcionlista == -2 ? "Restituir" : "Descartar" ?></a>
													 </div>
												</li>
											  <?php if($this->empresaMembresia!= 11 ){?>
												 <li>
													 <div class="">
														  <a id="lnkAgrPostulante<?= $idPostulante ?>" name="lnkAgrPostulante<?= $idPostulante ?>" href="" class="envPostulanteABolsa noScrollTop" rel="<?= $idPostulante ?>">Enviar a Carpeta CVs</a>
													 </div>
												 </li>
														  <?php }?>

										  </ul>
										  <?php }?>
									 </div>
									 <?php if ($this->opcionlista != -2): ?>
										  <div class="moveFilPerfP upFlechaEP moveraetapafila" rel="izq">
												<a class="tool-right <?=$this->flagAcciones['moverEtapa']['tooltip']?>" <?=$this->flagAcciones['moverEtapa']['texto']?> href="<?= $url ?>">Mover <br/>a etapa</a>
												<?php if ($this->flagAcciones['moverEtapa']['tooltip'] == '') { ?>
												<ul class="menuinterno hide r5">
													 <?php if ($this->categoria != ""): ?>
														  <li class="liActionM"><a class="aActionM" idpostulacion="<?= $idpos ?>" rel="-1" href="#verProceso">Sin Seleccionar</a></li>
													 <?php else: ?>
														  <li class="liActionM"><a class="aActionMDisable">Sin Seleccionar</a></li>
													 <?php endif; ?>
													 <?php foreach ($this->categoriaPostulacion as $item): ?>
														  <?php if ($this->categoria != $item["id"]): ?>
																<li class="liActionM"><a class="aActionM" idpostulacion="<?= $idpos ?>" rel="<?= $item["id"] ?>" href="#verProceso"><?= $item["nombre"] ?></a></li>
														  <?php else: ?>
																<li class="liActionM"><a class="aActionMDisable"><?= $item["nombre"] ?></a></li>
														  <?php endif; ?>
													 <?php endforeach; ?>
												</ul>
												<?php }?>
										  </div>
									 <?php endif; ?>
								</td>
						  <?php endif; ?>
					 </tr>
				<?php endforeach; ?>
		  </tbody>
	 </table>
	 <div class="pagination all">
		  <?= $this->paginationControl($this->proceso, 'Sliding','mis-procesos/_pag_verproceso.phtml',array("opcionlista" => $this->opcionlista, "estasArriba" => 0)) ?>
	 </div>
</div>
