<div id="paginEPM" class="pagination bBGray all">
    <p class="pagLegend grid5 mB0 theta alingL left"><?=$this->mostrando?></p>
    <?= $this->paginationControl($this->proceso, 'Sliding', 'mis-procesos/_pag_candidatos.phtml',array("opcionlista"=>$this->opcionlista, "estasArriba"=>1)) ?>
</div>
<!-- se saco el id='dataProcesoBusqueda' de la trabla-->
<table cadenabusqueda="<?=$this->cadenabusqueda?>" opcionlista="<?=$this->opcionlista?>" ord="<?=$this->ord?>" col="<?=$this->col?>" page="<?=$this->pagina?>" 
       class="dataGrid dataGridEnviarBolsa" id="dataProcesoBusquedaCandi" summary="Proceso de Postulacion" relIdA="<?= $this->anuncioId ?>"
       relPhoto="<?= $this->photoD; ?>" relPhotN="<?= $this->photoDN; ?>">
<thead>
    <tr>
        <? $base = array('module' => 'empresa', 'controller' => 'mis-procesos', 'action' => 'ver-proceso'); ?>
        <th width="5%" class="titleGrid selectAll">
            <input type="checkbox" id="chkSelectAll" name="selectAll" class="noBdr">
        </th>
        <th width="10%" class="titleGrid linkTitleG">
            <? $col = 'match' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
        <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Match<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="12%" class="titleGrid linkTitleG">
            <a href="#anclaCol" ord="ASC" col="match" class="relArrow titleRow">Foto</a>
        </th>
        <th width="18%" class="titleGrid linkTitleG">
            <? $col = 'po.nombres' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
            <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Nombres<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="11%" class="titleGrid linkTitleG">
            <? $col = 'po.sexo' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
           <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Sexo<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="10%" class="titleGrid linkTitleG">
            <? $col = 'po.fecha_nac' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
           <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Edad<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="17%" class="titleGrid linkTitleG">
            <? $col = 'ne.nombre' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
           <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Nivel de<br/>Estudio<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="17%" class="titleGrid linkTitleG">
        <? $col = 'car.nombre' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
        <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Carrera<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
        </th>
        <th width="13%" class="titleGrid linkTitleG">
                <? $col = 'ubi.display_name' ?>
        <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
        <? $base['col']=$col;
           $base['ord']=$ord;
           $url = $this->url($base,'default',true) ?>
                <a href="<?=$url?>" ord="<?= $ord ?>" col="<?= $col ?>" class="candiC rel relArrow">Lugar de<br/>Residencia<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
            </th>
    </tr>
</thead>
<tbody>
    <? foreach ($this->proceso as $item): ?>
       <tr class="<?=($item["leido"]?"pintarNoLeidos":"pintarLeidos")?>">
            <td width="5%" class="data0">
                <input type="checkbox" name="select[]" id="<?= $item['id_anuncio_web'] ?>" relpos="<?= $item['id_postulante'] ?>">
            </td>
            <td width="10%"><span class="dateData"><?= $item['match']; ?>%</span></td>
            <td width="12%">
                <span class="dateData cntImgFix">
                    <a href="#" class="verPerfilFilPerfP_Imagen">
                         <img height="60" src="<?= $item['path_foto'] =='' ? $this->photoD.'/images/photoDefault.jpg' : $this->photoDN.$item['path_foto']; ?>">
                    </a>
                </span>
            </td>
            <td width="18%">
                <div class="bold nameFilPerfP">
                    <a href="#" class="verPerfilFilPerfP_Nombre"><?= $item['nombres'] . " ". $item['apellidos']; ?></a></div>
                <div class="tlfFilPerfP sptIcoEmp" title="Telefono">&nbsp;<?= $item['celular'] ?></div>
                <div class="all">
                    <a class="verPerfilFilPerfP sptIcoEmp left" rel="<?= $item['id_postulante'] ?>" href="#" title="Ver perfil"></a>
                    <span class="pipeFilPerfP left">|</span>
                    <div class="msjFilPerfP sptIcoEmp left" title="Mensajes">(<?= $item['notif_no_leidas'] ?>)</div>
                </div>
            </td>
            <td width="11%">
                <div class="sptIcoEmp img<?= $item['sexo']=='M'? 'Hombre':'Mujer'; ?>"
                     title=" <?= $item['sexo']=='M'? 'Hombre':'Mujer'; ?>"><?= $item['sexo'] ?></div>
            </td>
            <td width="10%">
                    <span class="dateData"><?php
                    //echo $item['fecha_nac'] . "<br>";
                    list($ano,$mes,$dia) = explode("-",$item['fecha_nac']);
        $ano_diferencia  = date("Y") - $ano;
        $mes_diferencia = date("m") - $mes;
        $dia_diferencia   = date("d") - $dia;
        if ($dia_diferencia < 0 || $mes_diferencia < 0){
            $ano_diferencia;
        }
        echo $ano_diferencia;
                    ?></span>
            </td>
            <td width="17%">
                <span class="dateData"><?= $item['nombre']; ?></span>
            </td>
            <td width="17%">
                <span class="dateData"><?= $item['nombreCarrera']; ?></span>
            </td>
            <td width="17%">
                <span class="dateData"><?= $item['display_name']; ?></span>
            </td>
       </tr>
    <? endforeach; ?>
    </tbody>
</table>
<?php if (count($this->proceso) != 0) { ?>
    <div class="pagination all">
<?= $this->paginationControl($this->proceso, 'Sliding', 'mis-procesos/_pag_candidatos.phtml',array("estasArriba"=>0)) ?>
    </div>
<?php } else { ?>
    <div class="pagination all">
    <div class='pagUl theta alignL'> - No hay resultados que se adecúen a tu búsqueda </div>
</div>
<?php }  ?>
