<? $active2 = "active"; ?>
    <div class="iAccount contraido rel" id="innerMain"></div>
    <div id="pesatanaflotante" class="left hide">
		  <a href="#" class="right triggerSdb"><span class="hide">Flecha</span></a>
	</div>
    <div id="blockProEmpAl" class="blockAL grid4 theta left ieEmpAside">
        <h5 id="cabezasidebar" class="tituloPC r5T">Mis Procesos <a href="#" class="right triggerSdb"><span class="hide">Flecha</span></a></h5>
        
        <ul class="thirdMenu bLBlue bgLBlue r5B mB20">
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Empresa::MENU_POST_SIDE_PROCESOS_ACTIVOS?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'index'),"default",true)?>"><span class="sThird">Procesos Activos</span></a></li>
            <li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Empresa::MENU_POST_SIDE_PROCESOS_CERRADOS?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'procesos-cerrados'),false,true)?>"><span class="sThird">Procesos Cerrados</span></a></li>
            <?php //if($this->verSugerenciaCandidatos == 1){ ?>
            <!-- li class="liThird <?=$this->menu_sel_side==App_Controller_Action_Empresa::MENU_POST_SIDE_CANDIDATOS_SUGERIDOS?$active2:''?>"><a class="aThird" href="<?=$this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'candidatos-sugeridos'),false,true)?>"><span class="sThird">Candidatos Sugeridos</span></a></li -->
            <?php //} ?>
            <li class="liThird liLast <?=$this->menu_sel_side==App_Controller_Action_Empresa::MENU_POST_SIDE_PROCESOS_BORRADORES?$active2:''?>"><a class="aThird ie6Last" href="<?=$this->url(array('module'=>'empresa','controller'=>'mis-procesos','action'=>'borradores'),false,true)?>"><span class="sThird">Borradores</span></a></li>
        </ul>
    </div>

