 <div class="contenNotaEPA all">
     <h3 class="titleAPLR">Enviar Mensaje</h3>
 	<div class="iContenNotaEPA">
 		<form class="formDataNotaEPA">
	 		<div class="all cntNotaDataEPA" >
	 			<div class="left textAdjNotaEPA bold">Escribe aquí tu mensaje: </div>
	 			<div class="right cntActionsELP">
					<div class="actionsELP alignR">					
						<label class="labelCheckReqResp">
                                                    <?= $this->form->tipo_mensaje->setAttribs(array('id'=>'tipomensaje', 'class'=>'iptCheckReqResp'))->renderViewHelper(); ?>
                                                    <span class="textAsideReqR">Requiere Respuesta</span></label>
					</div>	 				
	 			</div>
	 		</div>
	 		<div class="all">
                        <?=$this->form->cuerpo->setAttribs(array('id'=>'areaMsjProEPA','class'=>'areaMsjProEPA'))->renderViewHelper(); ?>
                        </div>
                    	<div class="all">
	 			<div class="left">Te quedan <span id="cantMsjProEPA">300</span> caracteres</div>
	 			<input class="right submitSendHEPA btn btn-primary" href="#" value="Enviar" id="guardarMensajeVerProceso" type="button"/>
	 		</div>
                        <div id="msgErrorMensaje" class="error hide">*Debes Seleccionar un Archivo adjunto o Escribir una Nota.</div>
                        <?=$this->form->token->renderViewHelper(); ?>
 		</form>
 	</div>	
 </div>