 <?php echo $this->partial('_partials/_nota_verproceso.phtml', array('form'=>$this->formNota,
                                                                     'nombreAnuncio'=>$this->nombreAnuncio,
                                                                     'nombrePostulante'=>$this->nombrePostulante,
                                                                     'fecha'=>$this->fecha,
                                                                     'id'=>$this->id,
                                                                     'idAnuncio'=>$this->idAnuncio)); ?>
