<?=
$this->partial('_partials/_navigation.phtml', array(
    'menu_sel' => $this->menu_sel,
    'isAuth' => $this->isAuth,
    "flashMessages" => $this->flashMessages))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml', array(
    'menu_post_sel' => $this->menu_post_sel,
    "tieneBuscador" => $this->tieneBuscador,
    'Look_Feel' => $this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml', array(
        "flashMessages" => $this->flashMessages))
    ?>  
    <?=
    $this->partial('mis-procesos/_sidebar-menu.phtml', array(
        'menu_sel_side' => $this->menu_sel_side,
        'verSugerenciaCandidatos' => $this->verSugerenciaCandidatos))
    ?>
    <div id="gridTableR" class="blockAR alpha right">
        <div class="iBlockAR">
            <form id="datoBasicoF" method="post" action="" enctype="multipart/form-data">
                <h2>Borradores</h2>
                <a name="anclaPag"></a>
                <div class="pagination all">
                    <?= $this->paginationControl($this->procesosborradores, 'Sliding', 'mis-procesos/_pag.phtml') ?>
                </div>                                        
                <table class="dataGrid" id="dataProcesosBorradores" summary="Procesos Borradores">
                    <thead>
                        <tr>
                            <?php
                            $base = array(
                                'module' => 'empresa',
                                'controller' => 'mis-procesos',
                                'action' => 'borradores');
                            ?>
                            <th class="data1 titleGrid linkTitleG">
                                <?php
                                $col = 'puesto'
                                ?>
                                <?php
                                $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC' : 'ASC'
                                ?>
                                <?php
                                $url = $this->url(array_merge($base, array(
                                    'col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Aviso <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data2 titleGrid linkTitleG">
                                <?php
                                $col = 'fh_creacion'
                                ?>
                                <?php
                                $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC' : 'ASC'
                                ?>
                                <?php
                                $url = $this->url(array_merge($base, array(
                                    'col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Fecha<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data3 titleGrid linkTitleG">
                                <?php
                                $col = 'tipo'
                                ?>
                                <?php
                                $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC' : 'ASC'
                                ?>
                                <?php
                                $url = $this->url(array_merge($base, array(
                                    'col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Tipo<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data4 titleGrid linkTitleG">
                                <?php
                                $col = 'estado'
                                ?>
                                <?php
                                $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC' : 'ASC'
                                ?>
                                <?php
                                $url = $this->url(array_merge($base, array(
                                    'col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Estado<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data5 titleGrid linkTitleG">
                                <?php
                                $col = 'codigo_pago'
                                ?>
                                <?php
                                $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC' : 'ASC'
                                ?>
                                <?php
                                $url = $this->url(array_merge($base, array(
                                    'col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Código<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data9 titleGrid">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($this->procesosborradores as $item):
                            ?>
                            <tr>
                                <td class="data1">
                                    <?= $item['puesto'] ?>
                                    <?php if ($this->auth['usuario']->rol == 'empresa-admin') { ?>
                                        <div class="tiny-text">(<?php echo $item['email'] ?>)</div>
                                    <?php } ?>
                                    <div>
                                        <?php
                                        if ($item['tipoAnuncio'] == 'preferencial') :
                                            $url = $this->url(array(
                                                'module' => 'empresa',
                                                'controller' => 'mi-cuenta',
                                                'action' => 'ver-aviso-preferencial',
                                                'preferencial' => $item['anuncio_impreso']), 'default', true);
                                        else :
                                            $url = $this->url(array(
                                                'slug' => $item['slug'],
                                                'url_id' => $item['url_id'],
                                                'id' => $item['id']), 'avisoEmpresa', true);
                                        endif;
                                        ?>
                                        <a rel="<?= $url ?>" class="winModal" href="#winVerProceso">Ver</a> &nbsp;
                                    </div>
                                </td>
                                <td class="data2">
                                    <span class="dateData"><?= $item["fcreacion"] ?></span>
                                </td>
                                <td class="data3">
                                    <span class="dateData"><?=
                                        $item["nombreProducto"] . (empty($item['tamanoId']) ? '' : ' (' . $item['tamanio'] . ')')
                                        ?></span>
                                </td>
                                <td class="data4">
                                    <?php
                                    if ($item["estado"] == 'registrado') :
                                        ?>
                                        <span class="dateData">Registrado</span>
                                    <?php else : ?>
                                        <span class="dateData"><?=
                                            $this->ItemList('EstadoCompra', $item["estado"])
                                            ?></span>
                                    <?php endif; ?>
                                </td>
                                <td class="data5">
                                    <span class="dateData"><?= $item["codigoCip"] ?></span>
                                </td>
                                <td class="data6">
                                    <?php
                                    if ($item["estado"] == 'registrado') :
                                        ?>
                                        <?php
                                        $url = $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'aviso',
                                            'action' => 'editar',
                                            'idPost' => $item["id"],
                                            'redirect' => $this->redirect), 'default', true);
                                        ?>
                                        <a href="<?= $url ?>">Editar</a>
                                    <?php endif; ?>
                                    <?php
                                    //if ($item['tipoAnuncio'] == 'preferencial') { 
                                    $url2 = $this->url(array_merge($base, array(
                                        'eliminar' => $item['id'],
                                        'csrfhash' => $this->csrfhash)), 'default', true);
                                    /* } else {
                                      $url2 = $this->url(array_merge($base,array('eliminar'=>$item["id"],'csrfhash'=>$this->csrfhash)), 'default',true);
                                      } */
                                    ?>
                                    <a href="#winAlertEliminarProceso"
                                       class="winModal"
                                       rel="<?= $url2 ?>">Eliminar</a>
                                    <a href="<?= SITE_URL ?>/empresa/publica-aviso/paso1/aviso/<?= $item["id"] ?>">Pagar</a>

                                </td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class="pagination all">
                    <?=
                    $this->paginationControl($this->procesosborradores, 'Sliding', 'mis-procesos/_pag.phtml')
                    ?>
                </div>
            </form>
        </div>
    </div>
</div>