<?=
$this->partial('_partials/_navigation.phtml',
	 array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth, "flashMessages" => $this->flashMessages))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
	 array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador))
?>

<div id="wrapper" class="row">
	 <div class="block">
		  <!-- >a href="/empresa/mis-procesos" class="f14">« Volver</a-->
		  <a href="javascript:this.history.back()" class="f14"  >« Volver</a>
	 </div>
	 <div id="cntTextAR">
		  <div id="leftTextAR" class="left">
				<div id="leftTextMid" class="content-text">
					 <h2>¿Desea ampliar este proceso exactamente igual?</h2>
					 <div class="inLeftText">
						  <p><a rel="<?=
								$this->url(array(
									 'slug' => $this->slug, 'url_id' => $this->url_id,
									 'id' => $this->rel), 'avisoEmpresa', true)
								?>" class="aEPLLinksF winModal" href="#winVerProceso"> <?php echo $this->puesto ?> </a></p>

						  <p>“Si elige <strong>Sí</strong>, tanto el proceso como su aviso relacionado estarán vigentes una cantidad de días adicionales, iguales a los adquiridos al comprar el aviso. El costo de la ampliación también será el mismo.</p>
						  <p>En cambio, si elige <strong>más y mejores opciones</strong>, los días y el costo van a depender del tipo de aviso que se seleccione al ampliar.”</p>
					 </div>
					 <br>
					 <div class="wrap-btn center">
						  <a id="inBtnYes" class="btn btn-primary" href="<?=
						  $this->url(array(
								'module' => 'empresa', 'controller' => 'mis-procesos',
								'action' => 'extender-proceso',
								'aviso' => $this->rel, 'csrfhash' => CSRF_HASH),
								'default', true)
						  ?>">Sí</a>
						  <a id="inBtnNot" class="btn btn-default" href="<?php
						  echo $this->url(array(
								'module' => 'empresa', 'controller' => 'publica-aviso',
								'action' => 'index',
								'extiende' => $this->rel), 'default', true)
						  ?>">¡No! Quiero más y mejores opciones</a>
					 </div>
				</div>
				<div id="leftTextBot"></div>
		  </div>
		  <div id="rightTextAR" class="right">
				<!-- Aviso -->

				<?php
				if ($this->tipo == Application_Model_AnuncioWeb::TIPO_CLASIFICADO) {
					 ?>
					 <?php
					 $i
						  = $this->idProd;
					 ?>
					 <?php
					 foreach ($this->arrayProdDetalle as $row) {
						  ?>
						  <? //php $i = $i+1   ?>
						  <div id="iBlock<?= $i ?>S2M" class="cntTopTitP2 left">
								<div class="topTitP2 topTitP2S<?= $i-1 ?>" <?=
								($i == 1 || $i == 13) ? 'id="freeAdv"' : ''
								?> >
											<?php
											$prod
												 = '';
											if ($i == 13) $prod = 'Destacado';
											?>
									 <h3 class="titAdvTopP2">Aviso Web <?= $prod ?></h3>
									 <h3 class="titAdvMidP2"><?=
										  ($row['0']['descripcion'] == 'Sólo Web' || $row['0']['descripcion']
										  == 'Web destacado') ? 'PUBLICACIÓN WEB' : 'IMPRESO ' . mb_strtoupper($row['0']['descripcion'])
										  ?></h3>
									 <?php
									 $gratis = 'ahora <br> ¡Gratis!';
									 //if ($row['0']['descripcion'] == 'Web destacado')
									 if ($row['0']['descripcion'] != 'Sólo Web')
										  $gratis = $this->moneda.number_format(substr($row['0']['valor'], 0, -3));
									 ?>
									 <div class="priceDef" style="font-size: 33px;margin: 0 0 0 31px;font-weight: bold;color: #FFF;"><?=$gratis?></div>
								</div>
								<div class="topbodyP2 row<?= $row['0']['id'] ?>EM">
									 <div class="cntBodyP2">
										  <div class="textCntE">
												<div <?=
												($i == 1 || $i == 13) ? 'id="clickAFC"' : ''
												?> class="textEM1 c3">
													 PUBLICACIÓN WEB
												</div>
												<div class="textEM2 c3">
													 en aquiempleos.com
												</div>
										  </div>
										  <div class="textEM3 c3 bold">
												Utilización de Filtros
										  </div>
										  <?php
										  $valor2
												= explode(',', $row['1']['valor'])
										  ?>
										  <div class="textEM4"><?= $valor2['0'] ?> días </div>
										  <div class="textEM5 c3 mB20 bold">de publicación web</div>
										  <?php
										  if ($i != 1) {
												?>
												<?php
												$valor2
													 = explode(',', $row['1']['valor'])
												?>
												<?php
												if (count($valor2) > 1) {
													 ?>
													 <div class="textEM4"> <span id="<?= $i ?>WordsEM"><?= $valor2['1'] ?> palabras</span> </div>
													 <div class="textEM5 c3 mB20 bold"> en el aviso impreso </div>
													 <div class="textEM5">Aviso <span class="bold"> Publicado</span> en </div>
													 <div class="textEM4 c3 bold"> AquiEmpleos o El Talán </div>
												<?php } ?>
										  <?php } ?>
									 </div>
								</div>
						  </div>
					 <?php } ?>
				<?php } else { ?>
					 <?php
					 if ($this->idProd == 6) {
						  $i = 0;
					 } elseif ($this->idProd == 7) {
						  $i = 1;
					 } else {
						  $i = 2;
					 }
					 ?>
					 <?php
					 foreach ($this->arrayProdDetalle as $row) :
						  ?>
						  <?php
						  $i
								= $i + 1
						  ?>
						  <div id="iBlock<?= $i ?>S2MAP" class="cntTopTitP2 left">
								<div class="topTitP2 topTitP2AP topTitP2S<?= $i ?>">
									 <h3 class="titAdvTopP2">Aviso Web</h3>
									 <h3 class="titAdvMidP2"><?= strtoupper($row['0']['descripcion']) ?></h3>
									 <div class="desdeAP">Desde</div>
									 <div class="priceDef" style="font-size: 33px;margin: 0 0 0 31px;font-weight: bold;color: #FFF;"><br><?php echo $this->moneda?><?=number_format(substr($row['0']['valor'], 0, -3))?></div>
								</div>
								<div class="topbodyP2 row<?= $row['0']['id'] ?>EM">
									 <div class="cntBodyP2">
										  <div class="textCntE">
												<div id="clickAFCAP" class="textEM1 c3">PUBLICACIÓN WEB</div>
												<div class="textEM2 c3">en aquiempleos.com</div>
										  </div>
										  <?php
										  $desc2
												= explode(',', $row['2']['descripcion'])
										  ?>
										  <div class="textEM3 c3 textEMNM3"><div>Utilización de Filtros</div><div class="nBold"><?= ucfirst($desc2['1']) ?></div></div>
										  <?php
										  $valor2
												= explode(',', $row['2']['valor'])
										  ?>
										  <div class="textEM4"><?= $valor2['0'] ?> días</div>
										  <div class="textEM5 c3 mB20 bold">de publicación web</div>
										  <?php
										  $desc1
												= explode(',', $row['1']['descripcion'])
										  ?>
										  <div class="textEM4">
												<?php
												foreach ($desc1 as $item) :
													 ?>
													 <span class="spanAP"><?= $item ?></span>
												<?php endforeach; ?>
										  </div>
										  <div class="textEM5 c3 mB20 bold">tamaños de avisos en el impreso</div>
										  <div class="textEM5">Aviso <span class="bold">Publicado</span> en</div>
										  <div class="textEM4 c3 bold">AquiEmpleos o El Talán</div>
									 </div>
								</div>
						  </div>
					 <?php endforeach; ?>
				<?php } ?>

				<!-- /Aviso -->
		  </div>
	 </div>
</div>
