<?=
$this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml', array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscadorEMPLEOBUSCO, 'tieneBolsaCVs' => $this->tieneBolsaCVs))
?>

<?php 
    $maxValor = 0;  
    $arData = json_decode($this->data);
    if (count($arData)>0) {
        foreach ($arData as $p => $item)  {            
            if ($p > 0) {                
                if (isset($item[2]) && ($maxValor < $item[2])) {
                    $maxValor = $item[2];
                }

                if (isset($item[1]) && ($maxValor < $item[1])) {
                    $maxValor = $item[1];
                }

            }
        } 
    } else {
        
    }
    
    //var_dump($this->dataInitial,$this->data,$this->edad,$this->estudios);
?>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">        
	tmp.chartData = {
                maxValue :  <?php echo $maxValor;?>,
		postulant : {
			empty : <?php echo $this->dataInitial?>,
			full : <?php echo $this->data?>
		},
                genre : <?php echo $this->sexo?>,
		age : <?php echo $this->edad?>,
		studies : <?php echo $this->estudios?>
	};
        
</script>
 
<div class="wrap_bg">
	 <div class="box-center">
		 	<div class="message_charts">
		 		<span></span>
				<b>Solo se mostrará la información de los últimos 30 días.</b>
		 	</div>
	 		<div class="chart_relative">
	 			<div class="chart_total_number first hide">(<?=$this->tvisitas;?>)</div>
	            <div class="chart_total_number second hide">(<?=$this->tpostulaciones;?>)</div>
				<div id="divChartPostulant" class="linechart_wrapper">
					<div class="load-wrap"><span></span></div>
				</div>
	 		</div>
	 </div>
</div>
<div class="wrapper">
	<div class="mB20">
		<div class="row">
			<div class="grids-300"><h3>Tiempo de Publicación</h3></div>
			<div class="grids published_range">
				<i class="icon icon_calendar"></i><span>Inicio: <?php echo $this->aviso['fechaInicio'];?></span>
				<i class="icon icon_calendar mL10"></i><span>Fin: <?php echo $this->aviso['fechaFin'];?></span>
			</div>
		</div>
		<div class="rank" data-percent="<?=$this->diasProceso; ?>">
	      <span style="width: <?=$this->diasProceso; ?>%;"> </span>
	   </div>
		<p>Faltan <?=$this->tdias; ?> días para el vencimiento de la publicación</p>
	</div>

	<div class="row">
		<div class="grids-3">
			 <h3 class="EMPLEOBUSCO-title small"><i class="icon icon_person"></i>Sexo</h3>
			 <div id="divChartGender" class="charts"><div class="load-wrap"><span></span></div></div>
		</div>
		<div class="grids-3">
			 <h3 class="EMPLEOBUSCO-title small"><i class="icon icon_person"></i>Edad</h3>
			 <div id="divCharAge" class="charts"><div class="load-wrap"><span></span></div></div>
		</div>
		<div class="grids-3">
			 <h3 class="EMPLEOBUSCO-title small"><i class="icon icon_education"></i>Estudios</h3>
			 <div id="divChartStudy" class="charts"><div class="load-wrap"><span></span></div></div>
		</div>
	</div>
	<div class="row">
		<div class="grids-6 detail_information_box">
			<div class="black-title txt-left row">Descripción del Puesto:<a href="<?=$this->url(array("module" => "empresa","controller" => "aviso", "action" => "editar",
                            'idPost' => $this->aw["id"],'redirect'=>$this->redirect),"default", true)?>" class="btn"><i class="icon icon_pencil"></i>EDITAR</a></div>
			<div class="detail_information">
				<div class="information_wrapper inline row"><h4>TÍTULO DE POSTULACIÓN</h4><p> <?=( $this->aw["tituloaviso"] );?></p></div>
				<div class="information_wrapper inline row"><h4>NOMBRE DE LA EMPRESA</h4><p> <?=$this->aw["nombre_empresa"];?></p></div>
				<div class="information_wrapper">
					<h4>FUNCIONES</h4>
					<p>  <?= nl2br($this->escape($this->aw['funciones'])) . "<br>" ; ?></p>
				</div>
				<div class="information_wrapper last">
					<h4>RESPONSABILIDADES</h4>
					<p> <?= nl2br($this->escape($this->aw['responsabilidades'])) . "<br>" ; ?></p>
				</div>
			</div>
		</div>
		<div class="grids-300 other_detail_ads">
			<?php foreach (  $this->categoria as $key => $value) {?>
	            <div class="row">
	            	<h3><?php echo $value[0][0];?></h3>
	            	<span class="flt_left"><i class="icon icon_person"></i> <?php echo $value[1];?></span>
	            	<a class="flt_right" href="<?=$this->url(array("module" => "empresa","controller" => "mis-procesos", "action" => "ver-proceso",
                            'id' => $this->aw["id"],'categoria'=>$value[0][1]),"default", true)?>"><i class="icon icon_eye"></i> Ver</a>
	            </div>
	        <?php  }?>
		</div>
	</div>
</div>
