<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,
        'tieneBolsaCVs' => $this->tieneBolsaCVs,'Look_Feel' =>  $this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=$this->partial('_partials/_messages.phtml',array("flashMessages"=>$this->flashMessages))?> 
    <?=
    $this->partial('mis-procesos/_sidebar-menu.phtml',
        array('menu_sel_side' => $this->menu_sel_side,
        'verSugerenciaCandidatos' => $this->verSugerenciaCandidatos))
    ?>
    <div id="gridTableR" class="blockAR alpha right">
        <div class="iBlockAR">
            <form id="datoBasicoF" method="post" action="" enctype="multipart/form-data">
                <h2>Procesos Activos</h2>
                <div class="row">
                    <a class="action-btn view"></a>
                </div>        														
                <a name="anclaPag"></a>
                <div class="overflowX">
                    <div class="pagination all">
                        <?=
                        $this->paginationControl($this->procesosactivos,
                            'Sliding', 'mis-procesos/_pag.phtml')
                        ?>
                    </div>                                    
                    <table class="dataGrid" id="dataProcesosAct" summary="Procesos Activos">
                        <thead>
                            <tr>
                                <?php
                                $base
                                    = array('module' => 'empresa',
                                    'controller' => 'mis-procesos',
                                    'action' => 'index');
                                ?>
                                <th class="data1 titleGrid linkTitleG">
                                    <?php $col  = 'puesto'    ?>
                                    <?php $ord  = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC' ?>
                                    <?php $url  = $this->url(array_merge($base,array('col' => $col,'ord' => $ord)), 'default', false) ?>
                                    <a href="<?= $url ?>" class="rel relArrow">Proceso <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data2 titleGrid linkTitleG">
                                    <?php $col = 'fh_pub'  ?>
                                    <?php $ord = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC' ?>
                                    <?php $url = $this->url(array_merge($base, array('col' => $col,'ord' => $ord)), 'default', false)   ?>
                                    <a href="<?= $url ?>" class="rel relArrow">Inicio<br/>Proceso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data3 titleGrid linkTitleG">
                                    <?php $col = 'fh_vencimiento'  ?>
                                    <?php $ord = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC' ?>
                                    <?php $url = $this->url(array_merge($base,array('col' => $col,'ord' => $ord)), 'default', false)   ?>
                                    <a href="<?= $url ?>" class="rel relArrow">Fin<br/>Publicación<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data4 titleGrid linkTitleG">
                                    <?php $col   = 'fh_vencimiento_proceso'   ?>
                                    <?php $ord   = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC' ?>
                                    <?php $url   = $this->url(array_merge($base,array('col' => $col,'ord' => $ord)), 'default', false)  ?>
                                    <a href="<?= $url ?>" class="rel relArrow">Fin<br/>Proceso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data5 titleGrid postuIco linkTitleG">
                                    <?php $col  = 'ntotal'  ?>
                                    <?php $ord  = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC'  ?>
                                    <?php $url  = $this->url(array_merge($base,
                                            array('col' => $col,
                                        'ord' => $ord)), 'default', false)
                                    ?>
                                    <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Postulantes"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data6 titleGrid msjNLIco linkTitleG">
                                    <?php $col  = 'nnuevos'   ?>
                                    <?php $ord   = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC'   ?>
                                    <?php $url   = $this->url(array_merge($base,array('col' => $col,  'ord' => $ord)), 'default', false)  ?>
                                    <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="No Leidos"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data7 titleGrid nInvitIco linkTitleG">
                                    <?php $col = 'ninvitaciones'  ?>
                                    <?php $ord = ($this->col == $col && $this->ord == 'ASC') ? 'DESC' : 'ASC'?>
                                    <?php $url = $this->url(array_merge($base, array('col' => $col,'ord' => $ord)), 'default', false)           ?>
                                    <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Invitados"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data8 titleGrid msjLIco linkTitleG">
                                    <?php $col = 'total_referidos'?>
                                    <?php $ord = ($this->col == $col && $this->ord == 'ASC')? 'DESC' : 'ASC'?>
                                    <?php $url = $this->url(array_merge($base,  array('col' => $col, 'ord' => $ord)), 'default', false)    ?>
                                    <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Referidos"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                                </th>
                                <th class="data9 titleGrid">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php  foreach ($this->procesosactivos as $item):                               ?>
                                <?php
                                $finPub = $this->DiasRestantes($item["f_publicacion"]);
                                $baja = $this->DiasRestantes($item["f_baja"]);
                                $finProc = $this->DiasRestantes($item["f_vencimiento"]);
                                ?>
                                <tr>
                                    <td class="data1">
                                        <?= $item['puesto'] ?>
                                        <?php if($this->auth['usuario']->rol=='empresa-admin'){?>
                                        <div class="tiny-text">(<?php echo $item['email']?>)</div>
                                        <?php }?>
                                        <div class="lineEmpRgt">
                                            <a rel="<?=
                                            $this->url(array(
                                                'slug' => $item['slug'],
                                                'url_id' => $item['url_id'],
                                                'id' => $item['id']),
                                                'avisoEmpresa', true)
                                            ?>" class="winModal" href="#winVerProceso">Ver</a>
                                                <a href="<?php
                                                echo $this->url(array(
                                                    'module' => 'empresa',
                                                    'controller' => 'mis-procesos',
                                                    'action' => 'decision-aviso',
                                                    'idP' => $item['id_producto'],
                                                    'rel' => $item['id']),
                                                    'default', true)
                                                ?>" rel="<?php echo $item['id'] ?>" class="hrefExtend">Ampliar</a>
                                               <?php
                                               $url
                                                   = $this->url(array(
                                                   'module' => 'empresa',
                                                   'controller' => 'aviso',
                                                   'action' => 'editar',
                                                   'idPost' => $item["id"],
                                                   'redirect' => $this->redirect),
                                                   'default', false)
                                               ?>
                                         <?php if($item["estado"]!='dado_baja'){?>   
                                            <a href="<?= $url ?>" class="">Editar</a>
                                            <?php } ?>
                                        </div>
                                    </td>
                                    <td class="data2">
                                        <span class="dateData"><?= $item["fcreacion"] ?></span>
                                    </td>
                                    <td class="data3">
                                        <?=
                                        $baja != '' ? $baja : $finPub; // $this->DiasRestantes($item["fpublicacion"])."<br/>".$item["fpublicacion"];  
                                        ?>
                                    </td>
                                    <td class="data4">
                                        <?= $finProc; //$this->DiasRestantes($item["fvencimiento"])."<br/>".$item["fvencimiento"];      ?>
                                    </td>
                                    <td class="data5">
                                        <?=
                                        ($item["npostulantes"] == null) ? "0" : $item["npostulantes"];
                                        ?>
                                    </td>
                                    <td class="data6">
                                        <?=
                                        ($item["nnoleidos"] == null) ? "0" : $item["nnoleidos"]
                                        ?>
                                    </td>
                                    <td class="data7">
                                        <?=
                                        ($item["ninvitaciones"] == null) ? "0" : $item["ninvitaciones"]
                                        ?>
                                    </td>
                                    <td class="data8">
                                        <?=
                                        ($item["total_referidos"] == null) ? "0"
                                                : $item["total_referidos"]
                                        ?>
                                    </td>
                                    <td class="data9">
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'mis-procesos',
                                            'action' => 'ver-proceso',
                                            'id' => $item["id"]), "default",
                                            true);
                                        ?>
                                        <a class="lineEmpRgt" href="<?= $url ?>">Ver Proceso</a>
                                        <?php /**
                                         *  @todo se realiza esto para realizar el pase, cambiarlo despues
                                         */
                                        ?>
                                        <?=$this->LimitarOpcionesProceso($this->empresaMembresia,null)->showExportExcel($item["id"]);?>
                                        <?php
                                        $url  = $this->url(array_merge($base, array('cerrar' => $item["id"], 'csrfhash' => CSRF_HASH)), 'default', false)
                                        ?>
                                        <a href="#winAlertVerProceso"
                                           class="winModal lineEmpRgt"
                                           rel="<?= $url ?>">Cerrar</a>

                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                    <div class="pagination all">
                        <?=
                        $this->paginationControl($this->procesosactivos,
                            'Sliding', 'mis-procesos/_pag.phtml')
                        ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

