<div id="paginEPM" class="pagination bBGray all">
    <p class="pagLegend grid5 mB0 theta alingL left"><?=$this->mostrando?></p>
    <?=$this->paginationControl($this->arrayBusqueda,'Sliding','mis-procesos/_pag_detacandi.phtml')?>
</div>

            <div class="gridYScroll">
<table summary="Administradores" id="dataAadmins" class="dataGrid">
        <thead>
        <?php  $base = $this->empresaAdminUrl ?>
            <tr>
                <th width="5%" class="titleGrid selectAll">
                    <input type="checkbox" id="chkSelectAll" name="selectAll" class="noBdr">
                </th>
                <th width="10%" class="titleGrid linkTitleG">
                    <? $col = 'match' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                    <a page="<?php echo $this->pagina; ?>" col="<?php echo $col; ?>" ord="<?php echo $ord; ?>" href="<?=$url?>" class="detCandiC rel relArrow">Match<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
                <th width="12%" class="titleGrid linkTitleG">
                    <a href="#anclaCol" ord="ASC" col="match" class="relArrow titleRow ascRow">Foto</a>
                </th>
                <th width="18%" class="titleGrid linkTitleG">
                    <? $col = 'po.nombres' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                    <a href="<?=$url?>" class="rel relArrow">Nombres<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
                <th width="11%" class="titleGrid linkTitleG">
                    <? $col = 'po.sexo' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                   <a href="<?=$url?>" class="rel relArrow">Sexo<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
                <th width="10%" class="titleGrid linkTitleG">
                    <? $col = 'po.fecha_nac' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                   <a href="<?=$url?>" class="rel relArrow">Edad<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
                <th width="17%" class="titleGrid linkTitleG">
                    <? $col = 'ne.nombre' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                   <a href="<?=$url?>" class="rel relArrow">Nivel de<br/>Estudio<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
                <th width="17%" class="titleGrid linkTitleG">
                <? $col = 'car.nombre' ?>
                <? $ord = $this->col == $col && $this->ord == 'ASC' ? 'DESC': 'ASC' ?>
                <? $base['col']=$col;
                   $base['ord']=$ord;
                   $url = $this->url($base,'default',true) ?>
                <a href="<?=$url?>" class="rel relArrow">Carrera<span class="arrowDG <?=strtolower($ord)?>">&nbsp;</span></a>
                </th>
            </tr>
        </thead>
        <tbody>
        <?php
        if (count($this->arrayBusqueda)>0) {
            $cantidad = $this->arrayBusqueda->getCurrentItemCount();
            $count = ($this->pagina - 1) * $cantidad + 1 ;
        }
        foreach ($this->arrayBusqueda as $item) { ?>
            <tr>
                <td width="5%" class="data0">
                    <input type="checkbox" name="select[]" id="<?= $item['id'] ?>" relpos="<?= $item['id'] ?>">
                </td>
                <td width="10%"><span class="dateData"><?= $item['match']; ?>%</span></td>
                <td width="12%">
                    <span class="dateData cntImgFix">
                        <a href="#" class="verPerfilFilPerfP_Imagen">
                            <img height="60" src="<?= $item['path_foto']==''? $this->photoD : $this->mediaUrl . "/images/" . $item['path_foto']; ?>">
                        </a>
                    </span>
                </td>
                <td width="18%">
                    <div class="bold nameFilPerfP">
                        <a href="#" class="verPerfilFilPerfP_Nombre"><?= $item['nombres'] . " ". $item['apellidos']; ?></a></div>
                    <div class="tlfFilPerfP sptIcoEmp" title="Telefono">&nbsp;<?= $item['celular'] ?></div>
                    <div class="all">
                        <a class="verPerfilFilPerfP sptIcoEmp left" rel="<?= $item['id_postulante'] ?>" href="#" title="Ver perfil"></a>
                        <span class="pipeFilPerfP left">|</span>
                        <div class="msjFilPerfP sptIcoEmp left" title="Mensajes">(<?= $item['notif_no_leidas'] ?>)</div>
                    </div>
                </td>
                <td width="11%">
                    <div class="sptIcoEmp img<?= $item['sexo']=='M'? 'Hombre':'Mujer'; ?>"
                         title=" <?= $item['sexo']=='M'? 'Hombre':'Mujer'; ?>"><?= $item['sexo'] ?></div>
                </td>
                <td width="10%">
                        <span class="dateData"><?php
                        //echo $item['fecha_nac'] . "<br>";
                        list($ano,$mes,$dia) = explode("-",$item['fecha_nac']);
            $ano_diferencia  = date("Y") - $ano;
            $mes_diferencia = date("m") - $mes;
            $dia_diferencia   = date("d") - $dia;
            if ($dia_diferencia < 0 || $mes_diferencia < 0){
                $ano_diferencia;
            }
            echo $ano_diferencia;

                        ?></span>
                </td>
                <td width="17%">
                    <span class="dateData"><?= $item['nombre']; ?></span>
                </td>
                <td width="17%">
                    <span class="dateData"><?= $item['nombreCarrera']; ?></span>
                </td>
            </tr>
            <?php } ?>
            </tbody>
</table>
</div>
<?php if (count($this->arrayBusqueda) != 0) { ?>
<div class="pagination all">
<?= $this->paginationControl($this->arrayBusqueda, 'Sliding', 'mis-procesos/_pag_detacandi.phtml') ?>
</div>
<?php } else { ?>
<div class="pagination all">
<div class='pagUl theta alignL'> - No hay Resultados que se adecuen a tu Búsqueda </div>
</div>
<?php }  ?>

        