<?=
$this->partial('_partials/_navigation.phtml',
    array('menu_sel' => $this->menu_sel, 'isAuth' => $this->isAuth))
?>
<?=
$this->partial('mi-cuenta/_sec-menu.phtml',
    array('menu_post_sel' => $this->menu_post_sel, "tieneBuscador" => $this->tieneBuscador,'Look_Feel' =>  $this->Look_Feel))
?>
<div id="wrapper" class="row">
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>  
    <?=
    $this->partial('mis-procesos/_sidebar-menu.phtml',
        array('menu_sel_side' => $this->menu_sel_side,
        'verSugerenciaCandidatos' => $this->verSugerenciaCandidatos))
    ?>
    <div id="gridTableR" class="blockAR alpha right">
        <div class="iBlockAR">
            <form id="datoBasicoF" method="post" action="" enctype="multipart/form-data">
                <h2>Procesos Cerrados</h2>                               
                <a name="anclaPag"></a>
                <div class="pagination all">
                    <?=
                    $this->paginationControl($this->procesoscerrados, 'Sliding',
                        'mis-procesos/_pag.phtml')
                    ?>
                </div>
                <table class="dataGrid" id="dataProcesosAct" summary="Procesos Cerrados">
                    <thead>
                        <tr>
                            <?
                            $base
                                = array('module' => 'empresa',
                                'controller' => 'mis-procesos',
                                'action' => 'procesos-cerrados');
                            ?>
                            <th class="data1 titleGrid linkTitleG">
                                <?
                                $col
                                    = 'puesto'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Proceso <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data2 titleGrid linkTitleG">
                                <?
                                $col
                                    = 'fh_pub'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Inicio<br/>Proceso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data3 titleGrid linkTitleG">
                                <?
                                $col
                                    = 'fh_vencimiento'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Fin<br/>Publicación<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data4 titleGrid linkTitleG">
                                <?
                                $col
                                    = 'fh_vencimiento_proceso'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel relArrow">Fin<br/>Proceso<span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data5 titleGrid postuIco linkTitleG">
                                <?
                                $col
                                    = 'ntotal'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Postulantes"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data6 titleGrid msjNLIco linkTitleG">
                                <?
                                $col
                                    = 'nnuevos'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="No Leidos"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data7 titleGrid nInvitIco linkTitleG">
                                <?
                                $col
                                    = 'ninvitaciones'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Invitados"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data8 titleGrid msjLIco linkTitleG">
                                <?
                                $col
                                    = 'total_referidos'
                                ?>
                                <?
                                $ord
                                    = $this->col == $col && $this->ord == 'ASC' ? 'DESC'
                                        : 'ASC'
                                ?>
                                <?
                                $url
                                    = $this->url(array_merge($base,
                                        array('col' => $col,
                                    'ord' => $ord)), 'default', false)
                                ?>
                                <a href="<?= $url ?>" class="rel iIcoTh relArrow" title="Referidos"> <span class="arrowDG <?= strtolower($ord) ?>">&nbsp;</span></a>
                            </th>
                            <th class="data9 titleGrid">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?
                        foreach ($this->procesoscerrados as $item):
                            ?>
                            <tr>
                                <td class="data1">
                                    <?= $item['puesto'] ?>
                                        <?php if($this->auth['usuario']->rol=='empresa-admin'){?>
                                        <div class="tiny-text">(<?php echo $item['email']?>)</div>
                                        <?php }?>
                                    <div>
                                        <a rel="<?=
                                        $this->url(array(
                                            'slug' => $item['slug'],
                                            'url_id' => $item['url_id'],
                                            'id' => $item['id']),
                                            'avisoEmpresa', true)
                                        ?>"
                                           class="winModal"
                                           href="#winVerProceso">Ver</a> &nbsp;
                                          
                                            <a href="<?php
                                            echo $this->url(array(
                                                'module' => 'empresa',
                                                'controller' => 'mis-procesos',
                                                'action' => 'decision-aviso',
                                                'idP' => $item['id_producto'],
                                                'rel' => $item['id']),
                                                'default', true)
                                            ?>" rel="<?php echo $item['id'] ?>" class="hrefExtend">Ampliar</a>&nbsp;
                                        <!-- a href="<?=
                                        $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'publica-aviso',
                                            'action' => 'index',
                                            'republica' => $item['id']),
                                            'default', true);
                                        ?>" rel="<?php echo $item['id'] ?>" class="">Republicar</a -->
                                    </div>
                                </td>
                                <td class="data2">
                                    <span class="dateData"><?= $item["fcreacion"] ?></span>
                                </td>
                                <td class="data3">
                                    <span class="dateData"><?= $item["f_publicacion"] ?></span>
                                </td>
                                <td class="data4">
                                    <span class="dateData"><?= $item["fvencimiento"] ?></span>
                                </td>
                                <td class="data5">
                                    <?=
                                    ($item["npostulantes"] == null) ? "0" : $item["npostulantes"];
                                    ?>
                                </td>
                                <td class="data6">
                                    <?=
                                    ($item["nnoleidos"] == null) ? "0" : $item["nnoleidos"]
                                    ?>
                                </td>
                                <td class="data7">
                                    <?=
                                    ($item["ninvitaciones"] == null) ? "0" : $item["ninvitaciones"]
                                    ?>
                                </td>
                                <td class="data8">
                                    <?=
                                    ($item["total_referidos"] == null) ? "0" : $item["total_referidos"]
                                    ?>
                                </td>
                                <td class="data9">
                                    <?
                                    $url
                                        = $this->url(array('module' => 'empresa',
                                        'controller' => 'mis-procesos',
                                        'action' => 'ver-proceso',
                                        'id' => $item["id"]), "default", true);
                                    ?>
                                    <a href="<?= $url ?>">Ver Proceso</a>

                                    <a rel="<?= $item["extiende_a"] ?>" class="winModal" href="#winVerHistorial">Historial</a>
                                    <?php
                                    if (
                                        isset($this->auth['empresa']['membresia_info']['membresia']['m_nombre'])
                                        &&
                                        $this->auth['empresa']['membresia_info']['membresia']['m_nombre']
                                        != Application_Model_Membresia::M_NOMBRE_ESENCIAL):
                                        ?>
                                        <?php
                                        $url
                                            = $this->url(array(
                                            'module' => 'empresa',
                                            'controller' => 'mis-procesos',
                                            'action' => 'exportar-proceso',
                                            'id' => $item["id"]), "default",
                                            true);
                                        ?>
                                        <a href="<?php echo $url ?>">Exportar a Excel</a>
                                    <?php endif; ?>
                                </td>
                            </tr>
                        <? endforeach; ?>
                    </tbody>
                </table>
                <div class="pagination all">
                    <?=
                    $this->paginationControl($this->procesoscerrados, 'Sliding',
                        'mis-procesos/_pag.phtml')
                    ?>
                </div>
            </form>
        </div>
    </div>
</div>
