<div id="cargandoReferenciado" class="loading center hide"></div>
<div id="mainReferenciado" class="center">

    <h3 class="titleAPLR">Registrar Referido</h3>

    <div id="cntSearchDat">
        <!-- BUSCAR POR EMAIL -->
        <div id="buscarReferenciado" class="mB10 all">
            <label class="labelN labelNTM left" for="txtbuscaEmail">
                Email:
            </label>
            <input value="<?= $this->email ?>" type="text" name="buscaEmail" id="txtbuscaEmail" class="inputN left inputNTM" />
            <button type="button" class="sptEmp btnSptEmp left" id="btnBuscarxEmail">
            </button>
            <span class="error respEmailE left msg"></span>
        </div>
        <!-- RESULTADO DE BUSQUEDA -->
        <?
        if ($this->result == "0"):
            ?>
            <div id="resultadoReferenciado" class="msgYellow mB20 r5 alignC center">
                No hay resultados,
                <a id="agregarReferenciado" href="#">Agregar Un Referido</a>
            </div>
        <? endif; ?>

        <!-- CUANDO EXISTE POSTULANTE -->
        <?
        if ($this->result == "1"):
            ?>
            <div id="tablaExistePostulante">
                <table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
                    <thead>
                        <tr>
                            <th class="data1 titleGrid">&nbsp;</th>
                            <th class="data2 titleGrid"> Postulante</th>
                            <th class="data3 titleGrid"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="data1">
                                <img src="<?=
                                ($this->objPostulante["path_foto"] == "") ? $this->S('/images/photoDefault.jpg')
                                        : ELEMENTS_URL_IMG . $this->objPostulante["path_foto"];
                                ?>" />
                            </td>
                            <td class="data2">
                                <?= $this->objPostulante["nombres"] . " " . $this->objPostulante["apellidos"] ?> <br>
                                Cel. <?= $this->objPostulante["telefono"] . "-" . $this->objPostulante["celular"] ?> <br>
                                <span class="sptIcoEmp <?=
                                ($this->objPostulante["sexo"] == "M") ? "imgHombre"
                                        : "imgMujer"
                                ?>" title=" <?=
                                      ($this->objPostulante["sexo"] == "M") ? "Hombre"
                                              : "Mujer"
                                      ?>"><?= $this->objPostulante["sexo"] ?></span>
                                <br>
                                <?
                                if ($this->objPostulante["path_cv"] != ""):
                                    ?>
                                    <a href=" <?= ELEMENTS_URL_CVS . $this->objPostulante["path_cv"] ?>" target="_blank">
                                        Ver CV
                                    </a>
                                <? endif; ?>
                            </td>     
                            <td class="data3 tcnt">
                                <a id="linkreferenciarPostulante" rel="<?= $this->objPostulante["id"] ?>" href="#">Referenciar</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <? endif; ?>

        <!-- CUANDO YA POSTULO ANTERIORMENTE -->
        <?
        if ($this->result == "3"):
            ?>
            <div id="tablaExistePostulante">
                <table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
                    <thead>
                        <tr>
                            <th class="data1 titleGrid">&nbsp;</th>
                            <th class="data2 titleGrid"> Postulante</th>
                            <th class="data3 titleGrid"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="data1">
                                <img src="<?=
                                ($this->objPostulante["path_foto"] == "") ? $this->S('/images/photoDefault.jpg')
                                        : ELEMENTS_URL_IMG . $this->objPostulante["path_foto"];
                                ?>" />
                            </td>
                            <td class="data2">
                                <?= $this->objPostulante["nombres"] . " " . $this->objPostulante["apellidos"] ?> <br>
                                Cel. <?= $this->objPostulante["telefono"] . "-" . $this->objPostulante["celular"] ?> <br>
                                <span class="sptIcoEmp <?=
                                ($this->objPostulante["sexo"] == "M") ? "imgHombre"
                                        : "imgMujer"
                                ?>" title=" <?=
                                      ($this->objPostulante["sexo"] == "M") ? "Hombre"
                                              : "Mujer"
                                      ?>"><?= $this->objPostulante["sexo"] ?></span>
                                <br>
                                <?
                                if ($this->objPostulante["path_cv"] != ""):
                                    ?>
                                    <a href=" <?= ELEMENTS_URL_CVS . $this->objPostulante["path_cv"] ?>" target="_blank">
                                        Ver CV
                                    </a>
                                <? endif; ?>
                            </td>     
                            <td class="data3 tcnt">
                                <p class="pstr"><?php echo $this->msgYaPostulo; ?></p>
                                <?php /* <!-- linkreferenciarPostulante-->
                                  <!-- linkUpdateReferenciarPostulante--> */ ?>
                                <a id="linkreferenciarPostulante" rel="<?= $this->objPostulante["id"] ?>" href="#">Referenciar</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <? endif; ?>

        <!-- CUANDO YA POSTULO ANTERIORMENTE -->
        <?
        if ($this->result == "5"):
            ?>
            <div id="tablaExistePostulante">
                <table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
                    <thead>
                        <tr>
                            <th class="data1 titleGrid">&nbsp;</th>
                            <th class="data2 titleGrid"> Postulante</th>
                            <th class="data3 titleGrid"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="data1">
                                <img src="<?=
                                ($this->objPostulante["path_foto"] == "") ? $this->S('/images/photoDefault.jpg')
                                        : ELEMENTS_URL_IMG . $this->objPostulante["path_foto"];
                                ?>" />
                            </td>
                            <td class="data2">
                                <?= $this->objPostulante["nombres"] . " " . $this->objPostulante["apellidos"] ?> <br>
                                Cel. <?= $this->objPostulante["telefono"] . "-" . $this->objPostulante["celular"] ?> <br>
                                <span class="sptIcoEmp <?=
                                ($this->objPostulante["sexo"] == "M") ? "imgHombre"
                                        : "imgMujer"
                                ?>" title=" <?=
                                      ($this->objPostulante["sexo"] == "M") ? "Hombre"
                                              : "Mujer"
                                      ?>"><?= $this->objPostulante["sexo"] ?></span>
                                <br>
                                <?
                                if ($this->objPostulante["path_cv"] != ""):
                                    ?>
                                    <a href=" <?= ELEMENTS_URL_CVS . $this->objPostulante["path_cv"] ?>" target="_blank">
                                        Ver CV
                                    </a>
                                <? endif; ?>
                            </td>     
                            <td class="data3 tcnt">
                                <p class="pstr"><?php echo $this->msgYaPostulo; ?></p>              
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <? endif; ?>

        <!-- CUANDO EL POSTULANTE HA SIDO INVITADO -->
        <?
        if ($this->result == "6"):
            ?>
            <div id="tablaExistePostulante">
                <table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
                    <thead>
                        <tr>
                            <th class="data1 titleGrid">&nbsp;</th>
                            <th class="data2 titleGrid"> Postulante</th>
                            <th class="data3 titleGrid"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="data1">
                                <img src="<?=
                                ($this->objPostulante["path_foto"] == "") ? $this->S('/images/photoDefault.jpg')
                                        : ELEMENTS_URL_IMG . $this->objPostulante["path_foto"];
                                ?>" />
                            </td>
                            <td class="data2">
                                <?= $this->objPostulante["nombres"] . " " . $this->objPostulante["apellidos"] ?> <br>
                                Cel. <?= $this->objPostulante["telefono"] . "-" . $this->objPostulante["celular"] ?> <br>
                                <span class="sptIcoEmp <?=
                                ($this->objPostulante["sexo"] == "M") ? "imgHombre"
                                        : "imgMujer"
                                ?>" title=" <?=
                                      ($this->objPostulante["sexo"] == "M") ? "Hombre"
                                              : "Mujer"
                                      ?>"><?= $this->objPostulante["sexo"] ?></span>
                                <br>
                                <?
                                if ($this->objPostulante["path_cv"] != ""):
                                    ?>
                                    <a href=" <?= ELEMENTS_URL_CVS . $this->objPostulante["path_cv"] ?>" target="_blank">
                                        Ver CV
                                    </a>
                                <? endif; ?>
                            </td>     
                            <td class="data3 tcnt">
                                <p class="pstr"><?php echo $this->msgYaPostulo; ?></p>              
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <? endif; ?>


        <!-- CUANDO EL POSTULANTE ESTA BLOQUEADO -->
        <?
        if ($this->result == "4"):
            ?>
            <div id="tablaExistePostulante">
                <table class="dataGrid" id="tablaEPostulante" style="width: 530px;">
                    <thead>
                        <tr>
                            <th class="data1 titleGrid">&nbsp;</th>
                            <th class="data2 titleGrid"> Postulante</th>
                            <th class="data3 titleGrid"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="data1">
                                <img src="<?=
                                ($this->objPostulante["path_foto"] == "") ? $this->S('/images/photoDefault.jpg')
                                        : ELEMENTS_URL_IMG . $this->objPostulante["path_foto"];
                                ?>" />
                            </td>
                            <td class="data2">
                                <?= $this->objPostulante["nombres"] . " " . $this->objPostulante["apellidos"] ?> <br>
                                Cel. <?= $this->objPostulante["telefono"] . "-" . $this->objPostulante["celular"] ?> <br>
                                <span class="sptIcoEmp <?=
                                ($this->objPostulante["sexo"] == "M") ? "imgHombre"
                                        : "imgMujer"
                                ?>" title=" <?=
                                      ($this->objPostulante["sexo"] == "M") ? "Hombre"
                                              : "Mujer"
                                      ?>"><?= $this->objPostulante["sexo"] ?></span>
                                <br>
                                <?
                                if ($this->objPostulante["path_cv"] != ""):
                                    ?>
                                    <a href=" <?= ELEMENTS_URL_CVS . $this->objPostulante["path_cv"] ?>" target="_blank">
                                        Ver CV
                                    </a>
                                <? endif; ?>
                            </td>     
                            <td class="data3 tcnt">
                                <p class="pstr"><?php echo $this->msgYaPostulo; ?></p>              
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        <? endif; ?>

        <!-- CUANDO EXISTE REFERENIADO -->
        <?
        if ($this->result == "2"):
            ?>
            <div id="resultadoReferenciado" class="msgYellow mB20 r5 alignC center">
                Ya existe en los referidos.<br>
                <b>Nombre: </b><?= $this->nombreReferenciado ?> 
            </div>
        <? endif; ?>

        <!-- CUANDO SE HACE CLICK EN REGISTRAR REFERENTE -->
        <div id="frmRegistroReferente"  class="hide">
            <form target="frmref" id="datoBasicoEPF" method="post" action="/empresa/mis-procesos/registrar-referenciado" enctype="multipart/form-data">
                <input type="hidden" name="idanuncio" id="idocultoanuncio" value="0" />
                <input type="hidden" name="emailoculto" id="ocultoemail" value="<?= $this->email ?>" />
                <fieldset class="all">
                    <div class="block blockNProc">
                        <label for="fEmail" class="left labelN labelNProc">
                            <span class="req">*</span> Email:
                        </label>
                        <?
                        $hasError
                            = $this->frmReferenciado->email->hasErrors();
                        ?>
                        <?=
                        $this->frmReferenciado->email->setAttribs(array(
                            'id' => 'fEmail', 'disable' => 'true', 'class' => 'fields inputN inputNProc left'))->renderViewHelper();
                        ?>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                                  <?=
                                  $hasError ? $this->frmReferenciado->email->errMsg
                                          : ''
                                  ?>
                        </span>
                    </div>
                    <div class="block blockNProc">
                        <label for="fSexo" class="left labelN labelNProc">
                            <span class="req">*</span> Sexo:
                        </label>

                        <div id="efSex" class="iBlockN left">
                            <?
                            $hasError
                                = $this->frmReferenciado->sexoMF->hasErrors();
                            ?>
                            <?=
                            $this->frmReferenciado->sexoMF->setAttribs(array(
                                'id' => 'fSexo', 'class' => 'checkN noBdr radioOpt'))->renderViewHelper();
                            ?>
                        </div>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                                  <?=
                                  $hasError ? $this->frmReferenciado->sexoMF->errMsg
                                          : ''
                                  ?>
                        </span>
                    </div>
                    <div class="block blockNProc">
                        <label for="fNombres" class="left labelN labelNProc">
                            <span class="req">*</span> Nombres:
                        </label>
                        <?
                        $hasError
                            = $this->frmReferenciado->nombre->hasErrors();
                        ?>
                        <?=
                        $this->frmReferenciado->nombre->setAttribs(array(
                            'id' => 'fNombres', 'class' => 'fields inputN inputNProc left'))->renderViewHelper();
                        ?>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                                  <?=
                                  $hasError ? $this->frmReferenciado->nombre->errMsg
                                          : ''
                                  ?>
                        </span>
                    </div>
                    <div class="block blockNProc">
                        <label for="fApellidos" class="left labelN labelNProc">
                            <span class="req">*</span> Apellidos:
                        </label>
                        <?
                        $hasError
                            = $this->frmReferenciado->apellidos->hasErrors();
                        ?>
                        <?=
                        $this->frmReferenciado->apellidos->setAttribs(array(
                            'id' => 'fApellidos', 'class' => 'fields inputN inputNProc left'))->renderViewHelper();
                        ?>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                                  <?=
                                  $hasError ? $this->frmReferenciado->apellidos->errMsg
                                          : ''
                                  ?>
                        </span>
                    </div>
                    <div class="block blockNProc">
                        <label for="fTelefono" class="left labelN labelNProc">
                            <span class="req">*</span> Telefono:
                        </label>
                        <?
                        $hasError
                            = $this->frmReferenciado->telefono->hasErrors();
                        ?>
                        <?=
                        $this->frmReferenciado->telefono->setAttribs(array(
                            'id' => 'fTelefono', 'class' => 'fields inputN inputNProc left'))->renderViewHelper();
                        ?>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                                  <?=
                                  $hasError ? $this->frmReferenciado->telefono->errMsg
                                          : ''
                                  ?>
                        </span>
                    </div>
                    <div class="block mB0">
                        <label for="pCV" class="left labelN labelNProc">
                            <span class="req">*</span> Sube tu CV:<br/>
                            <span class="msgAside nBold f11 cRed">Tamaño máximo del archivo 2MB</span>
                        </label>

                        <input class="inputN cGray inputNProc placeH left" id="repCV" type="text" readonly="true" />
                        <div id="cntFieldCV" class="btnFileU left rel">
                            <label for="pCV" id="fieldCV" class="fileUp">
                            </label>
                            <div id="attrUpCv" class="opacity">
                                <?=
                                $this->frmReferenciado->path_cv->setAttribs(array(
                                    'id' => 'pCV', 'name' => 'path_cv', 'class' => 'fileUp',
                                    'value' => 'Examinar'))->renderFile();
                                ?>
                            </div>
                        </div>
                        <span class="response cGray left<?=
                        $hasError ? ' bad' : ''
                        ?>">
                            Seleccione un Archivo .pdf, .doc, .docx
                        </span>
                    </div>
                    <br>
                    <div class="wrap-btn right" >
                        <button type="button" id="registerProcE" class="btn btn-default">Añadir otro referido</button>
                    </div>
                </fieldset>

            </form>
        </div>
    </div>
</div>
<iframe id="frmref" name="frmref" src="javascript:false" class="hide"></iframe>
