<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
?>

<?php $validacionHide = ($this->form->id_idioma->getValue()!= '-1' && $this->form->id_idioma->getValue()!= null) && ($this->form->nivel_idioma->getValue()!= '-1' && $this->form->nivel_idioma->getValue()!= null) ?>

<div id="i<?php echo $ind ?>_expeN" class="skillN" rol="<?= $this->form->id_dominioIdioma!=null? ( $this->form->id_dominioIdioma->getValue()==''? '-1':$this->form->id_dominioIdioma->getValue() ):'-1';?>">
	<div id="i<?php echo $ind ?>_expTDiv" class="expTDiv">
	<?php if ( ($this->totalIdioma >= 1 || isset($this->isEditar)) && ($validacionHide) ) : ?>
	<blockquote class="addReg">
		<span class="wCount left">
			<span class="countN"><?php echo $ind + 1; ?></span>
		</span>
		<span class="wJob left">
			<span class="jobReg bold"><?=$this->escape($this->form->id_idioma->getMultiOption($this->form->id_idioma->getValue())); ?></span> en 
			<span class="eJob bold"><?=$this->escape($this->form->nivel_idioma->getMultiOption($this->form->nivel_idioma->getValue())); ?></span>
		</span>
		<?php if (!isset($this->online)) : ?>
		<a href="#Editar" class="editB hide" title="Editar"><span class="sEditB f11">Editar</span></a>
		<?php if (isset($this->form->id_dominioIdioma)) : ?>
		<?php $value = $this->form->id_dominioIdioma->getValue(); ?>
		<?php endif; ?>
		<a rel="#i<?php echo $ind ?>_expeN" rol="#winAlert" href="#winAlert" class="deleteB winAlertM<?=isset($value)?' eliminarItemEmp':''?>" title="¿Está seguro que desea eliminar el idioma seleccionado?"><span class="sDeleteB f11">Eliminar</span></a>
		<?php endif; ?>
	</blockquote>
	<?php endif; ?>
	</div>
	<?$isError = $this->form->isErrors(); ?>
	<div id="i<?php echo $ind ?>_fSkill" class="fSkill <?=(!$isError && ($this->totalIdioma > 1 || isset($this->isEditar) || ($validacionHide)) )?'hide':''?>">
		<div class="block" rel="sectionIdi">
			<label for="<?=$this->form->id_idioma->getAttrib('id')?>" class="labelN">Idioma:</label>
			<?$hasError = $this->form->id_idioma->hasErrors(); ?>
			<?php if (isset($this->isIdioma) && $this->form->id_idioma->getValue() != '-1') { ?>
			<?=$this->form->id_idioma->setAttribs(array('class'=>'selectN left selectReq field1Req ready'))->renderViewHelper(); ?>
			<?php } else { ?>
			<?=$this->form->id_idioma->setAttribs(array('class'=>'selectN left selectReq field1Req'))->renderViewHelper(); ?>
			<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->id_idioma->errMsg:''?></span>
		</div>
		<div class="block" rel="sectionIdi">
			<label for="<?=$this->form->nivel_idioma->getAttrib('id')?>" class="labelN">Nivel:</label>
			<?$hasError = $this->form->nivel_idioma->hasErrors(); ?>
			<?php if (isset($this->isIdioma) && $validacionHide) { ?>
			<?=$this->form->nivel_idioma->setAttribs(array('class'=>'selectN left selectReq ready'))->renderViewHelper(); ?>
			<?php } else { ?>
			<?=$this->form->nivel_idioma->setAttribs(array('class'=>'selectN left selectReq'))->renderViewHelper(); ?>
			<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->nivel_idioma->errMsg:''?></span>
		</div>
		<div class="block">
		<?=$this->form->id_dominioIdioma;?>
		</div>
	</div>
</div>		
