<form id="formEmpP1" action="" method="POST">
	 <div id="elije3Opt">
		  <h3 class="elecSec election1Sec">
				<input id="optP1Emp1" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
				<label for="optP1Emp1" class="labelEMP1">
					 Web + AquiEmpleos impreso
				</label>
				<label for="optP1Emp1" class="priceEMP1">
					 $ <span id="priceRelp1"></span>
				</label>
				<label for="optP1Emp1" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['EMPLEOBUSCO']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['EMPLEOBUSCO']->get("MMMM")) ?></span>.</label>
				<label for="optP1Emp1" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP1"><?= ucfirst($this->fchCierreImp['EMPLEOBUSCO']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['EMPLEOBUSCO']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
		  </h3>
		  <h3 class="elecSec election2Sec">
				<input id="optP1Emp2" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
				<label for="optP1Emp2" class="labelEMP1">
					 Web + El Talán impreso
				</label>
				<label for="optP1Emp2" class="priceEMP1">
					 $ <span id="priceRelp2"></span>
				</label>
				<label for="optP1Emp2" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['talan']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['talan']->get("MMMM")) ?></span>.</label>
				<label for="optP1Emp2" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP2"><?= ucfirst($this->fchCierreImp['talan']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['talan']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
		  </h3>
		  <h3 class="elecSec election3Sec">
				<input id="optP1Emp3" name="optP1Emp" class="radioEMP1 noBdr" type="radio" />
				<label for="optP1Emp3" class="labelEMP1">
					 Web + AquiEmpleos + El Talán impresos
				</label>
				<label for="optP1Emp3" class="priceEMP1">
					 $ <span id="priceRelp3"></span>
				</label>
				<label for="optP1Emp3" class="asideDateAE">Fecha de publicación de aviso: <span class="textDateAvs"><?= ucfirst($this->fchPubsImp['combo']->get("EEEE d 'de' ")) . ucfirst($this->fchPubsImp['combo']->get("MMMM")) ?></span>.</label>
				<label for="optP1Emp3" class="asideDateCls">Cierre de publicación y pago hasta: <span class="textDateAvs" id="dateCloseAP2"><?= ucfirst($this->fchCierreImp['combo']->get("EEEE d 'de' ")) . ucfirst($this->fchCierreImp['combo']->get("MMMM 'de' YYYY 'a' 'las' h:m a")); ?></span></label>
		  </h3>
	 </div>
	 <div class="wrap-btn right">
		  <a href="#" id="backEmpP1" class="btn btn-default btnSptEmp">Regresar</a>
		  <?php if ($this->layout()->auth != null && array_key_exists('empresa', $this->layout()->auth)): ?>
				<input type="submit" id="nextEmpP1" value="Continuar >" class="btn btn-primary logoutEmp btnSptEmp"/>
				<input type="hidden" id="idProductoLg" value="" />
		  <?php else: ?>
				<a href="#loginP" id="nextEmpP1" class="btn btn-primary login_modal" title="">Continuar ></a>
		  <?php endif; ?>
		  <div id="msgErrorEmpP1" class="msgErrorDef error"></div>
	 </div>
</form>
