<?php 
$ind = (isset($this->indice)) ? $this->indice : 'blank';
?>

<?php $validacionHide = ($this->form->id_programa_computo->getValue()!= '-1' && $this->form->id_programa_computo->getValue()!= null) && ($this->form->nivel->getValue()!= '-1' && $this->form->nivel->getValue()!= null) ?>

<div id="p<?php echo $ind ?>_expeN" class="skillN" rol="<?= $this->form->id_dominioComputo!=null? ( $this->form->id_dominioComputo->getValue()==''? '-1':$this->form->id_dominioComputo->getValue() ):'-1';?>">
	<div id="p<?php echo $ind ?>_expTDiv" class="expTDiv">
	<?php if (($this->totalPrograma >= 1 || isset($this->isEditar)) && ($validacionHide) ) : ?>
	<blockquote class="addReg">
		<span class="wCount left">
			<span class="countN"><?php echo $ind + 1; ?></span>
		</span>
		<span class="wJob left">
			<span class="jobReg bold"><?=$this->escape($this->form->id_programa_computo->getMultiOption($this->form->id_programa_computo->getValue())); ?></span> en 
			<span class="eJob bold"><?=$this->escape($this->form->nivel->getMultiOption($this->form->nivel->getValue())); ?></span>
		</span>
		<?php if (!isset($this->online)) : ?>
		<a href="#Editar" class="editB hide" title="Editar"><span class="sEditB f11">Editar</span></a>
		<?php if (isset($this->form->id_dominioComputo)) : ?>
		<?php $value = $this->form->id_dominioComputo->getValue(); ?>
		<?php endif; ?>
		<a rel="#p<?php echo $ind ?>_expeN" rol="#winAlert" href="#winAlert" class="deleteB winAlertM<?=isset($value)?' eliminarItemEmp':''?>" title="¿Está seguro que desea eliminar el programa de computadora seleccionado?"><span class="sDeleteB f11">Eliminar</span></a>
		<?php endif; ?>
	</blockquote>
	<?php endif; ?>
	</div>
	<?$isError = $this->form->isErrors(); ?>
	<div id="p<?php echo $ind ?>_fSkill" class="fSkill <?=(!$isError && ($this->totalPrograma > 1 || isset($this->isEditar)) || ($validacionHide) )?'hide':''?>">
		<div class="block" rel="sectionPro">
			<label for="<?=$this->form->id_programa_computo->getAttrib('id')?>" class="labelN">Programa:</label>
			<?$hasError = $this->form->id_programa_computo->hasErrors(); ?>
			<?php if (isset($this->isPrograma) && $this->form->id_programa_computo->getValue() != '-1') { ?>
			<?=$this->form->id_programa_computo->setAttribs(array('class'=>'selectN left selectReq field1Req ready'))->renderViewHelper(); ?>
			<?php } else { ?>
			<?=$this->form->id_programa_computo->setAttribs(array('class'=>'selectN left selectReq field1Req'))->renderViewHelper(); ?>
			<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->id_programa_computo->errMsg:''?></span>
		</div>
		<div class="block" rel="sectionPro">
			<label for="<?=$this->form->nivel->getAttrib('id')?>" class="labelN">Nivel:</label>
			<?$hasError = $this->form->nivel->hasErrors(); ?>
			<?php if (isset($this->isPrograma) && ($validacionHide) ) { ?>
			<?=$this->form->nivel->setAttribs(array('class'=>'selectN left selectReq ready'))->renderViewHelper(); ?>
			<?php } else { ?>
			<?=$this->form->nivel->setAttribs(array('class'=>'selectN left selectReq'))->renderViewHelper(); ?>
			<?php } ?>
			<span class="response def cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->form->nivel->errMsg:''?></span>
		</div>
		<div class="hide">
			<?=$this->form->id_dominioComputo;?>
		</div>
	</div>
</div>

