<nav class="cont-menu row">
    <br>
</nav>
<div id="wrapper" class="row">
    <div class="head-title row">
        <ul class="steps">
            <li>Escoge<br> el Aviso<span></span></li>
            <li class="act">Datos<br> del Aviso<span></span></li>
            <li>Verifica<br> tus datos<span></span></li>
        </ul>
        <div class="title-step">
            <div class="legend">
                <a href="<?=
                $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                    false, true)
                ?>">Inicio</a> » <span class="noLink">Paso 2 - Ingrese el aviso web</span>
            </div>
            <h1>Ingrese el aviso web</h1>
        </div>
    </div>

    <div class="row">
        <p class="right bold">Los campos con <span class="req">*</span> son necesarios</p>
        <h2 class="title-big">Datos del aviso web</h2>
    </div>
    <form action="" id="frmPublishAd" method="post" <?= isset($this->showLogoEmpresa)?'enctype="multipart/form-data"':''?> class="frm-horizontal wrap-register" autocomplete="off">
        <?php
        echo $this->partial('_partials/_paso2_aviso.phtml', 'empresa',
            array(
            'form' => $this->form, 'isDato' => $this->isDato,
            'numPalabraPuesto' => $this->numPalabraPuesto,
            'numPalabraOtroNombre' => $this->numPalabraOtroNombre,
            'modulo' => $this->modulo,
            'formEstudio' => $this->formEstudio, 'managerEstudio' => $this->managerEstudio,
            'isEstudio' => $this->isEstudio, 'isEditarEstudio' => $this->isEditarEstudio,
            'formExperiencia' => $this->formExperiencia, 'managerExperiencia' => $this->managerExperiencia,
            'isExperiencia' => $this->isExperiencia, 'isEditarExperiencia' => $this->isEditarExperiencia,
            'formOtroEstudio' => $this->formOtroEstudio, 'managerOtroEstudio' => $this->managerOtroEstudio,
            'isOtroEstudio' => $this->isOtroEstudio, 'isEditarOtroEstudio' => $this->isEditarOtroEstudio,
            'formIdioma' => $this->formIdioma, 'managerIdioma' => $this->managerIdioma,
            'isIdioma' => $this->isIdioma, 'isEditarIdioma' => $this->isEditarIdioma,
            'formPrograma' => $this->formPrograma, 'managerPrograma' => $this->managerPrograma,
            'isPrograma' => $this->isPrograma, 'isEditarPrograma' => $this->isEditarPrograma,
            'formPregunta' => $this->formPregunta, 'managerPregunta' => $this->managerPregunta,
            'isPregunta' => $this->isPregunta, 'isEditarPregunta' => $this->isEditarPregunta,
            'frmUbigeo' => $this->frmUbigeo,
            'showLogoEmpresa' => isset($this->showLogoEmpresa)?true:false,
            'formEmpresa' => isset($this->frmEmpresa)?$this->frmEmpresa:''
            )
        );
        ?>    				    	
        <div class="txt_right mT20"> 
            <span id="msgErrorStep2" class="error"></span>
            <?php
            if ($this->tarifa == 1) {
                ?>
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'publica-aviso',
                    'action' => 'index'), false, true);
                ?>" id="backEmpP1" class="btn btn-default">Regresar</a>
                <input onClick="ga('send', 'event', 'Apt-PublicacionSimple', 'Apt-paso2-PublicacionSimple', '<?= $this->idAnunciante ?>-PublicacionSimple');" id="aSetep2" class="btn btn-primary" type="submit" value="Continuar >"/>
            <?php } else { ?>
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'publica-aviso'), false, true);
                ?>" id="backEmpP1" class="btn btn-default">Regresar</a>
                <input id="aSetep2" onclick="ga('send', 'event', 'P2_Destacado', '<?php echo $this->empresaId?>' , 'P2_Destacado');" class="btn btn-primary" type="submit" value="Continuar >"/>
               <?php } ?>
        </div>
    </form>
    <?php
    echo $this->partial('_partials/_paso2_aviso_blank.phtml', 'empresa',
        array(
        'managerEstudio' => $this->managerEstudio,
        'managerOtroEstudio' => $this->managerOtroEstudio,
        'managerExperiencia' => $this->managerExperiencia,
        'managerIdioma' => $this->managerIdioma,
        'managerPrograma' => $this->managerPrograma,
        'managerPregunta' => $this->managerPregunta,
        )
    );
    ?>
</div>

