
<nav class="cont-menu"><br></nav>
<div id="wrapper">
    <div class="head-title row">
        <ul class="steps">
            <li>Escoge<br> el Aviso<span></span></li>
            <li>Datos<br> del Aviso<span></span></li>
            <li class="act">Verifica<br> tus datos<span></span></li>
        </ul>
        <div class="title-step">
            <div class="legend">
                <a href="<?php
                echo $this->url(array(
                    'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                    false, true)
                ?>">Inicio</a> »
                <span class="noLink">Paso 3 - Pague su Aviso</span>
            </div>
            <h1>Pague su Aviso</h1>
        </div>
    </div>

    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>
    <?=
    $this->partial(
        '_partials/_pagar_aviso_destacado.phtml',
        array(
        'Formfacturacion'=>$this->Formfacturacion,
        "dataAnuncio" => $this->dataAnuncio,
        'medioPublicacion' => $this->medioPublicacion,
        'fechaImpreso' => $this->fechaImpreso,
        'fhCierre' => $this->fhCierre,
        'empresaId' => $this->empresaId,
        'fechaCierreWeb' => $this->fechaCierreWeb,
        'isSessionAdmin' => ($this->isSessionAdmin ? true : false)
        )
    )
    ?>
</div>