        <div class="block">
            <label for="fNombreEmpresa" class="labelN"><span class="req">*</span> Empresa:</label>
            <?php $hasError = $this->formRegistroTestimonio->razonsocial->hasErrors(); ?>
            <?= $this->formRegistroTestimonio->razonsocial->setAttribs(array('id'=>'fNombreEmpresa','class'=>'fields inputN left','tabindex'=>'5'))->renderViewHelper(); ?>
            <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formRegistroTestimonio->razonsocial->errMsg:''; ?></span>
        </div>
        <div class="block">
            <label for="fUbicacion" class="labelN"><span class="req">*</span> Ubicación:</label>
            <?php $hasError = $this->formRegistroTestimonio->ubicacion->hasErrors(); ?>
            <?= $this->formRegistroTestimonio->ubicacion->setAttribs(array('id'=>'fUbicacion','class'=>'fields inputN left','tabindex'=>'6','value'=>'thisrazonsocial'))->renderViewHelper(); ?>
            <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formRegistroTestimonio->ubicacion->errMsg:'';?></span>
        </div>
        <div class="block">
            <label for="fTestimonio" class="labelN"><span class="req">*</span> Testimonio:</label>
            <div class="blockClearN left">
                <?php $hasError = $this->formRegistroTestimonio->testimonio->hasErrors(); ?>
                <?= $this->formRegistroTestimonio->testimonio->setAttribs(array('id'=>'fTestimonio','class'=>'fields left','tabindex'=>'7','rows'=>'4','maxlength'=>$this->maxcaracteres,'value'=>'thisrazonsocial'))->renderViewHelper(); ?>
            	<div class=blockClearN>Tiene <span id="count2P3" class="bold" data-chars="<?= $this->maxcaracteres; ?>"></span>&nbsp;caracteres para el contenido del aviso</div>
            </div>
            <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formRegistroTestimonio->testimonio->errMsg:'';?></span>
        </div>
        <div class="block">
            <label for="fReferente" class="labelN"><span class="req">*</span> Referente:</label>
            <?php $hasError = $this->formRegistroTestimonio->referente->hasErrors(); ?>
            <?= $this->formRegistroTestimonio->referente->setAttribs(array('id'=>'fReferente','class'=>'fields inputN left','tabindex'=>'8','value'=>'thisrazonsocial'))->renderViewHelper(); ?>
            <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formRegistroTestimonio->referente->errMsg:'';?></span>
        </div>
        <div class="block">
            <label for="fCargo" class="labelN"><span class="req">*</span> Cargo:</label>
            <?php $hasError = $this->formRegistroTestimonio->cargo->hasErrors(); ?>
            <?= $this->formRegistroTestimonio->cargo->setAttribs(array('id'=>'fCargo','class'=>'fields inputN left','tabindex'=>'9','value'=>'thisrazonsocial'))->renderViewHelper(); ?>
            <span class="response cGray left<?=$hasError?' bad':''?>"><?=$hasError?$this->formRegistroTestimonio->cargo->errMsg:'';?></span>
        </div>

        <div class="block" style="<?php if((($this->action == 'update') && ($this->estado != 'activo')) /*|| ($this->testimoniosActivos == $this->numtestimonio)*/){ ?>visibility: hidden; height: 2px;<?php } ?>">
            <label for="fEstado" class="labelN"><!-- span class="req">*</span --> Estado:</label>
            <div class="blockClearN left">
                <?= $this->formRegistroTestimonio->estado->setAttribs(array('id'=>'fEstado','class'=>'fields selectMN left','tabindex'=>'10'))->renderViewHelper(); ?>
            	<span class="response cGray left<?//=$hasError?' bad':''?>"><?//=$hasError?$this->formRegistroTestimonio->estado->errMsg:'';?></span>
            </div>
        </div>
        <div class="block" style="<?php if((($this->action == 'update') && ($this->estado != 'activo')) /*|| ($this->testimoniosActivos == $this->numtestimonio)*/){ ?>visibility: hidden; height: 2px;<?php } ?>">
            <label for="fOrden" class="labelN"><!-- span class="req">*</span --> Orden:</label>
            <div class="blockClearN left">
                <?= $this->formRegistroTestimonio->orden->setAttribs(array('id'=>'fOrden','class'=>'fields selectMN left','tabindex'=>'11'))->renderViewHelper(); ?>
            	<span class="response cGray left<?//=$hasError?' bad':''?>"><?//=$errMsg?></span>
			</div>
        </div>
        <?= $this->formRegistroTestimonio->tok->renderViewHelper(); ?>