<div id="iSectionsEM" class="sectionEM">
	 <?php $i = 0; ?>
	 <?php
	 foreach ($this->arrayPreferencial as $row) :
		  ?>
		  <?php $i = $i + 1 ?>
		  <div id="iBlock<?= $i ?>S2MAP" class="cntTopTitP2 formatAdv formatAdv<?= $i ?> left">
				<div class="topTitP2 topTitP2AP topTitP2S<?= $i ?>">
					 <? $nameAvd = explode(" ", $row['0']['descripcion']); ?>
					 <h3 style="font-size: 27px;text-align: center;padding-top: 20px;">Aviso Preferencial <b><?=((strtoupper($nameAvd["1"]) == "CLASICO") ? 'CLÁSICO' : strtoupper($nameAvd["1"]));?></b></h3>
					 <div class="desdeAP">Desde</div>
					 <div class="priceP2 priceDef"><?php echo $this->moneda?><?=
						  number_format($row['0']['valor'],0)
						  ?></div>
				</div>
				<div class="topbodyP2 row<?= $row['0']['id'] ?>EM">
					 <div class="cntBodyP2">
						  <ul>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Usuario y cuenta en AquiEmpleos</span>
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Utilización de Filtros de CVs</span>
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">4 Semanas</span>
									 <span class="br liTxtSmallL">de publicación Web</span>
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Ubicación Preferencial</span>
									 <span class="br liTxtSmallL">del aviso web sobre los Avisos Económicos (3 días)</span>
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Compra de Avisos Impresos desde la web</span>
									 <span class="br liTxtSmallL">para el suplemento AquiEmpleos del Diario La Prensa y/o en El Talan del Diario El Trome.</span>
									 <!--<span class="br liTxtSmallL">use plantillas de avisos o envíenos su diseño desde la web.</span>-->
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Escoge tu diseño de aviso impreso</span>
									 <span class="br liTxtSmallL">desde nuestra plantillas de avisos o envianos tu diseño desde la web.</span>
									 <!--<span class="br liTxtSmallL">use plantillas de avisos o envíenos su diseño desde la web.</span>-->
								</li>
								<li class="liArrowIW liLineHL">
									 <span class="br liTxtSmall">Medidas que aplican para el Aviso impreso</span>
									 <span class="br liTxtSmallL">
										  <?php
										  $desc1
												= explode(',', $row['1']['descripcion'])
										  ?>
										  <?php
										  foreach ($desc1 as $item) :
												?>
												/ <span><?= $item ?></span>
										  <?php endforeach; ?>
									 </span>
								</li>
						  </ul>


					 </div>
					 <?php
					 if ($row['0']['id'] == 5) :
						  ?>
						  <div class="all alignC">
								<a class="winModal viewShowEjmAP" rel="{tipo:'Aviso Preferencial STANDAR',avisos:['1x1','2x1','3x1','2x2'],tamanios:['1.94 x 3.77 cm','4.27 x 3.77 cm','6.60 x 3.77 cm','4.27 x 4.96 cm']}" href="#ejmsAviso">Ver ejemplo</a>
						  </div>
						  <?php
					 elseif ($row['0']['id'] == 6) :
						  ?>
						  <div class="all alignC">
								<a class="winModal viewShowEjmAP" rel="{tipo:'Aviso Preferencial CL&Aacute;SICO',avisos:['2x1','2x2','3x2'],tamanios:['4.27 x 3.77cm','4.27 x 7.96cm','6.60 x 7.96cm']}" href="#ejmsAviso">Ver ejemplo</a>
						  </div>
						  <?php
					 elseif ($row['0']['id'] == 7) :
						  ?>
						  <div class="all alignC">
								<a class="winModal viewShowEjmAP" rel="{tipo:'Aviso Preferencial ORO',avisos:['4x2','4x3','6x3'],tamanios:['8.92 x 7.96cm','8.92 x 12.16cm','13.58 x 12.16cm']}" href="#ejmsAviso">Ver ejemplo</a>
						  </div>
					 <?php else : ?>
						  <div class="all alignC">
								<a class="winModal viewShowEjmAP" rel="{tipo:'Aviso Preferencial PLATINUM',avisos:['6x6','12x3','12x6'],tamanios:['13.58 x 24.74cm','27.55 x 12.16cm','27.55 x 24.74cm']}" href="#ejmsAviso">Ver ejemplo</a>
						  </div>
					 <?php endif; ?>
					 <div class="all">
						  <!-- flag -->
						  <div rel="{idProd:'<?= $row['0']['id'] ?>'}" onclick="ga('send', 'event', 'P1.1_<?php echo str_replace(' ', '_', $row['0']['descripcion'])?>', '<?php echo $this->empresaId?>' , 'P1.1_<?php echo str_replace(' ', '_', $row['0']['descripcion'])?>');" id="avispPref<?= $row['0']['id'] ?>" class="btnPink continueP1C continNoP2 btnSptEmp iBtn<?= $i ?>S2MAP">
								Continuar
						  </div>

					 </div>
				</div>
		  </div>
	 <?php endforeach; ?>
</div>
