<nav class="cont-menu row">
    <br>
</nav>
<div id="wrapper" class="row">
    <div class="head-title row">
        <ul class="steps">
            <li>Escoge<br> el Aviso<span></span></li>
            <li>Datos<br> del Aviso<span></span></li>
            <li>Aviso<br> Impreso<span></span></li>
            <li class="act">Verifica<br> tus datos<span></span></li>
        </ul>
        <div class="legend">
            <a href="<?php
            echo $this->url(array(
                'module' => 'empresa', 'controller' => 'mi-cuenta', 'action' => 'index'),
                false, true)
            ?>">Inicio</a> »
            <span class="noLink">Paso 4 - Pague su Aviso</span>
        </div>
    </div>
    <?=
    $this->partial('_partials/_messages.phtml',
        array("flashMessages" => $this->flashMessages))
    ?>
    <h1>Pague su Aviso</h1>
    <?=
    $this->partial('_partials/_pagar_aviso_preferencial.phtml', $this);
    ?>
</div>
