<div class="bgAll gridS20">
    <?= $this->partial('_partials/_navigation.phtml', array('menu_sel' => $this->menu_sel,'isAuth'=>$this->isAuth, "flashMessages"=>$this->flashMessages)) ?>
    <div class="gridTab">
        <div class="gridIT">
            <?= $this->partial('mi-cuenta/_sec-menu.phtml', array('menu_post_sel' => $this->menu_post_sel)) ?>
            <div id="innerMain" class="iAccount">
                
            </div>
        </div>
    </div>
</div>
